export type RoutePath = string | ((...args: string[]) => string);

export interface RouteMap {
  HOME: string;
  PUBLIC: Record<string, RoutePath>;
  ERRORS: Record<string, string>;
  AUTH: Record<string, string>;
  USER: Record<string, RoutePath>;
  /** Store management dashboard (requires seller role). Replaces the old SELLER section. */
  STORE: Record<string, RoutePath>;
  ADMIN: Record<string, RoutePath>;
  DEMO: Record<string, RoutePath>;
  BLOG: Record<string, RoutePath>;
}

export const DEFAULT_ROUTE_MAP = {
  HOME: "/",
  PUBLIC: {
    FAQS: "/faqs",
    FAQ_CATEGORY: (category: string) => `/faqs/${category}`,
    PROFILE: (userId: string) => `/profile/${userId}`,
    PRODUCTS: "/products",
    PRODUCT_DETAIL: (slugOrId: string) => `/products/${slugOrId}`,
    AUCTIONS: "/auctions",
    AUCTION_DETAIL: (id: string) => `/auctions/${id}`,
    PRE_ORDERS: "/pre-orders",
    PRE_ORDER_DETAIL: (id: string) => `/pre-orders/${id}`,
    // SB1-J — bundles + prize draws (additive, pages not yet built)
    BUNDLES: "/bundles",
    BUNDLE_DETAIL: (slug: string) => `/bundles/${slug}`,
    PRIZE_DRAWS: "/prize-draws",
    PRIZE_DRAW_DETAIL: (slug: string) => `/prize-draws/${slug}`,
    SELLER_GUIDE_BUNDLES: "/seller-guide/bundles",
    SELLER_GUIDE_PRIZE_DRAWS: "/seller-guide/prize-draws",
    SELLERS: "/sellers",
    SELLER_DETAIL: (id: string) => `/sellers/${id}`,
    STORES: "/stores",
    STORE_DETAIL: (storeSlug: string) => `/stores/${storeSlug}`,
    STORE_PRODUCTS: (storeSlug: string) => `/stores/${storeSlug}/products`,
    STORE_AUCTIONS: (storeSlug: string) => `/stores/${storeSlug}/auctions`,
    STORE_PRE_ORDERS: (storeSlug: string) => `/stores/${storeSlug}/pre-orders`,
    STORE_PRIZE_DRAWS: (storeSlug: string) => `/stores/${storeSlug}/prize-draws`,
    STORE_BUNDLES: (storeSlug: string) => `/stores/${storeSlug}/bundles`,
    STORE_REVIEWS: (storeSlug: string) => `/stores/${storeSlug}/reviews`,
    STORE_ABOUT: (storeSlug: string) => `/stores/${storeSlug}/about`,
    STORE_COUPONS: (storeSlug: string) => `/stores/${storeSlug}/coupons`,
    CATEGORIES: "/categories",
    CATEGORY_DETAIL: (slug: string) => `/categories/${slug}`,
    BRANDS: "/brands",
    BRAND_DETAIL: (slug: string) => `/brands/${slug}`,
    REVIEWS: "/reviews",
    REVIEW_DETAIL: (id: string) => `/reviews/${id}`,
    SEARCH: "/search",
    PROMOTIONS: "/promotions",
    ABOUT: "/about",
    CONTACT: "/contact",
    BLOG: "/blog",
    HELP: "/help",
    TERMS: "/terms",
    PRIVACY: "/privacy",
    SECURITY: "/security",
    TRACK_ORDER: "/track",
    SELLER_GUIDE: "/seller-guide",
    COOKIE_POLICY: "/cookies",
    REFUND_POLICY: "/refund-policy",
    SHIPPING_POLICY: "/shipping-policy",
    HOW_AUCTIONS_WORK: "/how-auctions-work",
    HOW_PRE_ORDERS_WORK: "/how-pre-orders-work",
    HOW_OFFERS_WORK: "/how-offers-work",
    HOW_CHECKOUT_WORKS: "/how-checkout-works",
    HOW_ORDERS_WORK: "/how-orders-work",
    HOW_REVIEWS_WORK: "/how-reviews-work",
    HOW_PAYOUTS_WORK: "/how-payouts-work",
    FEES: "/fees",
    EVENTS: "/events",
    EVENT_DETAIL: (id: string) => `/events/${id}`,
    EVENT_PARTICIPATE: (id: string) => `/events/${id}/participate`,
    EVENT_LEADERBOARD: (id: string) => `/events/${id}/leaderboard`,
    EVENT_WINNER: (id: string) => `/events/${id}/winner`,
    SUBLISTING_CATEGORIES: "/sublisting-categories",
    SUBLISTING_CATEGORY: (slug: string) => `/sublisting-categories/${slug}`,
    SUPPORT: "/support",
    SCAMS: "/scams",
    SCAM_DETAIL: (id: string) => `/scams/${id}`,
    SCAM_REPORT: "/scams/report",
    REPORT_ENTITY: "/report",
    ITEM_REQUESTS: "/item-requests",
    ITEM_REQUEST_DETAIL: (id: string) => `/item-requests/${id}`,
    ITEM_REQUESTS_NEW: "/item-requests/new",
    SCAM_TYPES: "/scams/types",
    SCAM_FAQS: "/scams/faqs",
    CLASSIFIED: "/classified",
    CLASSIFIED_DETAIL: (slug: string) => `/classified/${slug}`,
    DIGITAL_CODES: "/digital-codes",
    DIGITAL_CODE_DETAIL: (slug: string) => `/digital-codes/${slug}`,
    LIVE: "/live",
    LIVE_DETAIL: (slug: string) => `/live/${slug}`,
  },
  ERRORS: {
    UNAUTHORIZED: "/unauthorized",
  },
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_EMAIL: "/auth/verify-email",
    OAUTH_LOADING: "/auth/oauth-loading",
    CLOSE: "/auth/close",
  },
  USER: {
    PROFILE: "/user/profile",
    SETTINGS: "/user/settings",
    ORDERS: "/user/orders",
    WISHLIST: "/wishlist",
    HISTORY: "/user/history",
    ADDRESSES: "/user/addresses",
    ADDRESSES_ADD: "/user/addresses/add",
    ADDRESSES_EDIT: (id: string) => `/user/addresses/edit/${id}`,
    ORDER_DETAIL: (id: string) => `/user/orders/view/${id}`,
    ORDER_CANCEL: (id: string) => `/user/orders/${id}/cancel`,
    ORDER_TRACK: (id: string) => `/user/orders/${id}/track`,
    ORDER_INVOICE: (id: string) => `/user/orders/${id}/invoice`,
    NOTIFICATIONS: "/user/notifications",
    MESSAGES: "/user/messages",
    /** Plan §10 — claimed-coupons wallet (Active / Expired / Used tabs). */
    CLAIMED_COUPONS: "/user/coupons",
    BECOME_SELLER: "/user/become-seller",
    CART: "/cart",
    CHECKOUT: "/checkout",
    CHECKOUT_SUCCESS: "/checkout/success",
    OFFERS: "/user/offers",
    REVIEWS: "/user/reviews",
    BIDS: "/user/bids",
    RETURNS: "/user/returns",
    SUPPORT: "/user/support",
    SUPPORT_TICKET: (id: string) => `/user/support/${id}`,
    PRE_ORDERS: "/user/pre-orders",
    DIGITAL_CODES: "/user/digital-codes",
    PRIZE_DRAWS: "/user/prize-draws",
    EVENTS: "/user/events",
  },
  STORE: {
    DASHBOARD: "/store",
    PRODUCTS: "/store/products",
    PRODUCTS_NEW: "/store/products/new",
    PRODUCTS_EDIT: (id: string) => `/store/products/${id}/edit`,
    ORDERS: "/store/orders",
    ORDER_DETAIL: (id: string) => `/store/orders/${id}/view`,
    AUCTIONS: "/store/auctions",
    AUCTIONS_NEW: "/store/auctions/new",
    AUCTIONS_EDIT: (id: string) => `/store/auctions/${id}/edit`,
    PRE_ORDERS: "/store/pre-orders",
    PRE_ORDERS_NEW: "/store/pre-orders/new",
    PRE_ORDERS_EDIT: (id: string) => `/store/pre-orders/${id}/edit`,
    COUPONS: "/store/coupons",
    COUPONS_NEW: "/store/coupons/new",
    COUPONS_EDIT: (id: string) => `/store/coupons/${id}/edit`,
    TEMPLATES: "/store/templates",
    TEMPLATES_NEW: "/store/templates/new",
    TEMPLATES_EDIT: (id: string) => `/store/templates/${id}/edit`,
    ANALYTICS: "/store/analytics",
    PAYOUTS: "/store/payouts",
    STOREFRONT: "/store/storefront",
    SHIPPING: "/store/shipping",
    PAYOUT_SETTINGS: "/store/payout-settings",
    ADDRESSES: "/store/addresses",
    OFFERS: "/store/offers",
    WHATSAPP: "/store/whatsapp",
    REVIEWS: "/store/reviews",
    BIDS: "/store/bids",
    SUBLISTING_CATEGORIES: "/store/sublisting-categories",
    SUBLISTING_CATEGORIES_NEW: "/store/sublisting-categories/new",
    SUBLISTING_CATEGORIES_EDIT: (id: string) => `/store/sublisting-categories/${id}/edit`,
    FEATURES: "/store/features",
    FEATURES_NEW: "/store/features/new",
    FEATURES_EDIT: (id: string) => `/store/features/${id}/edit`,
    SLUG: "/store/slug",
    // SB1-J — bundles + prize draws
    BUNDLES: "/store/bundles",
    BUNDLES_NEW: "/store/bundles/new",
    BUNDLES_EDIT: (id: string) => `/store/bundles/${id}/edit`,
    PRIZE_DRAWS: "/store/prize-draws",
    PRIZE_DRAWS_NEW: "/store/prize-draws/new",
    PRIZE_DRAWS_EDIT: (id: string) => `/store/prize-draws/${id}/edit`,
    PRODUCT_CODES: (id: string) => `/store/products/${id}/codes`,
    // SB-UNI-R — classified / digital-code / live
    CLASSIFIED: "/store/classified",
    CLASSIFIED_NEW: "/store/classified/new",
    CLASSIFIED_EDIT: (id: string) => `/store/classified/${id}/edit`,
    DIGITAL_CODES: "/store/digital-codes",
    DIGITAL_CODES_NEW: "/store/digital-codes/new",
    DIGITAL_CODES_EDIT: (id: string) => `/store/digital-codes/${id}/edit`,
    LIVE_ITEMS: "/store/live",
    LIVE_ITEMS_NEW: "/store/live/new",
    LIVE_ITEMS_EDIT: (id: string) => `/store/live/${id}/edit`,
    PRINT_CENTER: "/store/print-center",
    INVENTORY_PRINT: "/store/inventory/print",
    // S-STORE Tier — new extension routes
    PAYOUT_METHODS: "/store/payout-methods",
    PAYOUT_METHODS_NEW: "/store/payout-methods/new",
    PAYOUT_METHODS_EDIT: (id: string) => `/store/payout-methods/${id}/edit`,
    SHIPPING_CONFIGS: "/store/shipping-configs",
    SHIPPING_CONFIGS_NEW: "/store/shipping-configs/new",
    SHIPPING_CONFIGS_EDIT: (id: string) => `/store/shipping-configs/${id}/edit`,
    ANALYTICS_CARDS: "/store/analytics/cards",
    ANALYTICS_ALERTS: "/store/analytics/alerts",
    STORE_CATEGORIES: "/store/categories",
    STORE_CATEGORIES_NEW: "/store/categories/new",
    STORE_CATEGORIES_EDIT: (id: string) => `/store/categories/${id}/edit`,
    LISTING_TEMPLATES: "/store/listing-templates",
    LISTING_TEMPLATES_NEW: "/store/listing-templates/new",
    LISTING_TEMPLATES_EDIT: (id: string) => `/store/listing-templates/${id}/edit`,
    GOOGLE_REVIEWS: "/store/google-reviews",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    SITE: "/admin/site",
    CAROUSEL: "/admin/carousel",
    CAROUSEL_NEW: "/admin/carousel/new",
    CAROUSEL_EDIT: (id: string) => `/admin/carousel/${id}/edit`,
    CAROUSELS: "/admin/carousels",
    CAROUSEL_DETAIL: (id: string) => `/admin/carousels/${id}`,
    SECTIONS: "/admin/sections",
    NAVIGATION: "/admin/navigation",
    CATEGORIES: "/admin/categories",
    CATEGORIES_NEW: "/admin/categories/new",
    CATEGORIES_EDIT: (id: string) => `/admin/categories/${id}/edit`,
    BRANDS: "/admin/brands",
    BRANDS_NEW: "/admin/brands/new",
    BRANDS_EDIT: (id: string) => `/admin/brands/${id}/edit`,
    FAQS: "/admin/faqs",
    FAQS_NEW: "/admin/faqs/new",
    FAQS_EDIT: (id: string) => `/admin/faqs/${id}/edit`,
    REVIEWS: "/admin/reviews",
    COUPONS: "/admin/coupons",
    COUPONS_NEW: "/admin/coupons/new",
    COUPONS_EDIT: (id: string) => `/admin/coupons/${id}/edit`,
    MEDIA: "/admin/media",
    PRODUCTS: "/admin/products",
    PRODUCTS_NEW: "/admin/products/new",
    PRODUCTS_EDIT: (id: string) => `/admin/products/${id}/edit`,
    DEALS: "/admin/deals",
    FEATURED: "/admin/featured",
    ORDERS: "/admin/orders",
    ORDER_DETAIL: (id: string) => `/admin/orders/${id}/view`,
    BIDS: "/admin/bids",
    BLOG: "/admin/blog",
    BLOG_NEW: "/admin/blog/new",
    BLOG_EDIT: (id: string) => `/admin/blog/${id}/edit`,
    ANALYTICS: "/admin/analytics",
    PAYOUTS: "/admin/payouts",
    EVENTS: "/admin/events",
    EVENTS_NEW: "/admin/events/new",
    EVENTS_EDIT: (id: string) => `/admin/events/${id}/edit`,
    EVENT_ENTRIES: (id: string) => `/admin/events/${id}/entries`,
    STORES: "/admin/stores",
    FEATURE_FLAGS: "/admin/feature-flags",
    COPILOT: "/admin/copilot",
    ADS: "/admin/ads",
    ADS_NEW: "/admin/ads/new",
    ADS_EDIT: (id: string) => `/admin/ads/${id}/edit`,
    NEWSLETTER: "/admin/newsletter",
    CONTACT: "/admin/contact",
    SESSIONS: "/admin/sessions",
    ALL_EVENT_ENTRIES: "/admin/event-entries",
    NOTIFICATIONS: "/admin/notifications",
    CARTS: "/admin/carts",
    WISHLISTS: "/admin/wishlists",
    HISTORY: "/admin/history",
    RETURN_REQUESTS: "/admin/return-requests",
    STORE_ADDRESSES: "/admin/store-addresses",
    ADDRESSES: "/admin/addresses",
    ADDRESSES_NEW: "/admin/addresses/new",
    ADDRESSES_EDIT: (id: string) => `/admin/addresses/${id}/edit`,
    SUBLISTING_CATEGORIES: "/admin/sublisting-categories",
    SUBLISTING_CATEGORIES_NEW: "/admin/sublisting-categories/new",
    SUBLISTING_CATEGORIES_EDIT: (id: string) => `/admin/sublisting-categories/${id}/edit`,
    FEATURES: "/admin/features",
    FEATURES_NEW: "/admin/features/new",
    FEATURES_EDIT: (id: string) => `/admin/features/${id}/edit`,
    // SB1-J — bundles + prize draws (admin moderation)
    // S-SBUNI-4 — BUNDLES_NEW added alongside BUNDLES_EDIT.
    BUNDLES: "/admin/bundles",
    BUNDLES_NEW: "/admin/bundles/new",
    BUNDLES_EDIT: (id: string) => `/admin/bundles/${id}/edit`,
    PRIZE_DRAWS: "/admin/prize-draws",
    PRIZE_DRAWS_EDIT: (id: string) => `/admin/prize-draws/${id}/edit`,
    TEAM: "/admin/team",
    SUPPORT_TICKETS: "/admin/support-tickets",
    SUPPORT_TICKET_BY_ID: (id: string) => `/admin/support-tickets/${id}`,
    SCAMMERS: "/admin/scammers",
    SCAMMER_BY_ID: (id: string) => `/admin/scammers/${id}`,
    SETTINGS_ACTIONS: "/admin/settings/actions",
    SETTINGS_NAVIGATION: "/admin/settings/navigation",
    PRINT_CENTER: "/admin/print-center",
    // S-STORE Tier — admin moderation + reports + item requests
    MODERATION: "/admin/moderation",
    MODERATION_DETAIL: (id: string) => `/admin/moderation/${id}`,
    REPORTS: "/admin/reports",
    REPORT_DETAIL: (id: string) => `/admin/reports/${id}`,
    ITEM_REQUESTS: "/admin/item-requests",
    ITEM_REQUEST_DETAIL: (id: string) => `/admin/item-requests/${id}`,
    ROLES: "/admin/roles",
    ROLES_NEW: "/admin/roles/new",
    ROLES_EDIT: (id: string) => `/admin/roles/${id}/edit`,
    PERMISSIONS: "/admin/permissions",
    ADMIN_NOTIFICATIONS: "/admin/admin-notifications",
  },
  DEMO: {
    SEED: "/demo/seed",
  },
  BLOG: {
    LIST: "/blog",
    ARTICLE: (slug: string) => `/blog/${slug}`,
  },
} as const satisfies RouteMap;

export function createRouteMap(overrides: Partial<RouteMap> = {}): RouteMap {
  return {
    ...DEFAULT_ROUTE_MAP,
    ...overrides,
    PUBLIC: {
      ...DEFAULT_ROUTE_MAP.PUBLIC,
      ...(overrides.PUBLIC ?? {}),
    },
    ERRORS: {
      ...DEFAULT_ROUTE_MAP.ERRORS,
      ...(overrides.ERRORS ?? {}),
    },
    AUTH: {
      ...DEFAULT_ROUTE_MAP.AUTH,
      ...(overrides.AUTH ?? {}),
    },
    USER: {
      ...DEFAULT_ROUTE_MAP.USER,
      ...(overrides.USER ?? {}),
    },
    STORE: {
      ...DEFAULT_ROUTE_MAP.STORE,
      ...(overrides.STORE ?? {}),
    },
    ADMIN: {
      ...DEFAULT_ROUTE_MAP.ADMIN,
      ...(overrides.ADMIN ?? {}),
    },
    DEMO: {
      ...DEFAULT_ROUTE_MAP.DEMO,
      ...(overrides.DEMO ?? {}),
    },
    BLOG: {
      ...DEFAULT_ROUTE_MAP.BLOG,
      ...(overrides.BLOG ?? {}),
    },
  };
}

export const ROUTES = DEFAULT_ROUTE_MAP;

/** @deprecated Use ROUTES.STORE instead */
export const SELLER_ROUTES = ROUTES.STORE;

export const PUBLIC_ROUTES = [
  ROUTES.HOME,
  ROUTES.PUBLIC.FAQS as string,
  ROUTES.PUBLIC.PRODUCTS as string,
  ROUTES.PUBLIC.AUCTIONS as string,
  ROUTES.PUBLIC.PRE_ORDERS as string,
  ROUTES.PUBLIC.SELLERS as string,
  ROUTES.PUBLIC.STORES as string,
  ROUTES.PUBLIC.CATEGORIES as string,
  ROUTES.PUBLIC.SEARCH as string,
  ROUTES.PUBLIC.PROMOTIONS as string,
  ROUTES.PUBLIC.ABOUT as string,
  ROUTES.PUBLIC.CONTACT as string,
  ROUTES.PUBLIC.BLOG as string,
  ROUTES.PUBLIC.HELP as string,
  ROUTES.PUBLIC.TERMS as string,
  ROUTES.PUBLIC.PRIVACY as string,
  ROUTES.ERRORS.UNAUTHORIZED,
  ROUTES.AUTH.LOGIN,
  ROUTES.AUTH.REGISTER,
  ROUTES.AUTH.FORGOT_PASSWORD,
  ROUTES.AUTH.RESET_PASSWORD,
  ROUTES.AUTH.VERIFY_EMAIL,
] as const;

export const PROTECTED_ROUTES = [
  ROUTES.USER.PROFILE as string,
  ROUTES.USER.SETTINGS as string,
  ROUTES.USER.ORDERS as string,
  ROUTES.USER.ADDRESSES as string,
  ROUTES.USER.ADDRESSES_ADD as string,
  ROUTES.USER.NOTIFICATIONS as string,
  ROUTES.USER.CART as string,
] as const;

export const AUTH_ROUTES = [ROUTES.AUTH.LOGIN, ROUTES.AUTH.REGISTER] as const;
