import { defineConfig } from "tsup";
import path from "path";

// Alias map — resolves old @mohasinac/* package names to internal paths.
// This ensures tsup/esbuild bundles everything from src/ without
// needing to rewrite every import statement in the copied source files.
const alias: Record<string, string> = {
  // Primitive layers
  "@mohasinac/contracts": path.resolve("src/contracts"),
  "@mohasinac/core": path.resolve("src/core"),
  "@mohasinac/http": path.resolve("src/http"),
  "@mohasinac/errors": path.resolve("src/errors"),
  "@mohasinac/utils": path.resolve("src/utils"),
  "@mohasinac/validation": path.resolve("src/validation"),
  "@mohasinac/tokens": path.resolve("src/tokens"),
  "@mohasinac/next": path.resolve("src/next"),
  "@mohasinac/react": path.resolve("src/react"),
  "@mohasinac/ui": path.resolve("src/ui"),
  "@mohasinac/security": path.resolve("src/security"),
  "@mohasinac/seo": path.resolve("src/seo"),
  "@mohasinac/monitoring": path.resolve("src/monitoring"),
  "@mohasinac/instrumentation": path.resolve("src/instrumentation"),
  "@mohasinac/css-tailwind": path.resolve("src/style/tailwind"),
  "@mohasinac/css-vanilla": path.resolve("src/style/vanilla"),
  // Provider layers
  "@mohasinac/db-firebase": path.resolve("src/providers/db-firebase"),
  "@mohasinac/auth-firebase": path.resolve("src/providers/auth-firebase"),
  "@mohasinac/email-resend": path.resolve("src/providers/email-resend"),
  "@mohasinac/storage-firebase": path.resolve("src/providers/storage-firebase"),
  "@mohasinac/payment-razorpay": path.resolve("src/providers/payment-razorpay"),
  "@mohasinac/search-algolia": path.resolve("src/providers/search-algolia"),
  "@mohasinac/shipping-shiprocket": path.resolve("src/providers/shipping-shiprocket"),
  // Feature layers
  "@mohasinac/feat-layout": path.resolve("src/features/layout"),
  "@mohasinac/feat-forms": path.resolve("src/features/forms"),
  "@mohasinac/feat-filters": path.resolve("src/features/filters"),
  "@mohasinac/feat-media": path.resolve("src/features/media"),
  "@mohasinac/feat-auth": path.resolve("src/features/auth"),
  "@mohasinac/feat-account": path.resolve("src/features/account"),
  "@mohasinac/feat-admin": path.resolve("src/features/admin"),
  "@mohasinac/feat-blog": path.resolve("src/features/blog"),
  "@mohasinac/feat-cart": path.resolve("src/features/cart"),
  "@mohasinac/feat-categories": path.resolve("src/features/categories"),
  "@mohasinac/feat-checkout": path.resolve("src/features/checkout"),
  "@mohasinac/feat-collections": path.resolve("src/features/collections"),
  "@mohasinac/feat-consultation": path.resolve("src/features/consultation"),
  "@mohasinac/feat-corporate": path.resolve("src/features/corporate"),
  "@mohasinac/feat-events": path.resolve("src/features/events"),
  "@mohasinac/feat-faq": path.resolve("src/features/faq"),
  "@mohasinac/feat-homepage": path.resolve("src/features/homepage"),
  "@mohasinac/feat-loyalty": path.resolve("src/features/loyalty"),
  "@mohasinac/feat-orders": path.resolve("src/features/orders"),
  "@mohasinac/feat-payments": path.resolve("src/features/payments"),
  "@mohasinac/feat-products": path.resolve("src/features/products"),
  "@mohasinac/feat-promotions": path.resolve("src/features/promotions"),
  "@mohasinac/feat-reviews": path.resolve("src/features/reviews"),
  "@mohasinac/feat-search": path.resolve("src/features/search"),
  "@mohasinac/feat-seller": path.resolve("src/features/seller"),
  "@mohasinac/feat-stores": path.resolve("src/features/stores"),
  "@mohasinac/feat-wishlist": path.resolve("src/features/wishlist"),
  "@mohasinac/feat-auctions": path.resolve("src/features/auctions"),
  "@mohasinac/feat-pre-orders": path.resolve("src/features/pre-orders"),
  "@mohasinac/feat-preorders": path.resolve("src/features/pre-orders"),
  "@mohasinac/feat-before-after": path.resolve("src/features/before-after"),
  "@mohasinac/feat-whatsapp-bot": path.resolve("src/features/whatsapp-bot"),
};

const primitiveEntries = {
  "index": "src/index.ts",
  "contracts/index": "src/contracts/index.ts",
  "core/index": "src/core/index.ts",
  "http/index": "src/http/index.ts",
  "errors/index": "src/errors/index.ts",
  "utils/index": "src/utils/index.ts",
  "validation/index": "src/validation/index.ts",
  "tokens/index": "src/tokens/index.ts",
  "next/index": "src/next/index.ts",
  "react/index": "src/react/index.ts",
  "ui/index": "src/ui/index.ts",
  "security/index": "src/security/index.ts",
  "seo/index": "src/seo/index.ts",
  "monitoring/index": "src/monitoring/index.ts",
  "instrumentation/index": "src/instrumentation/index.ts",
  "style/tailwind/index": "src/style/tailwind/index.ts",
  "style/vanilla/index": "src/style/vanilla/index.ts",
};

const providerEntries = {
  "providers/db-firebase/index": "src/providers/db-firebase/index.ts",
  "providers/auth-firebase/index": "src/providers/auth-firebase/index.ts",
  "providers/email-resend/index": "src/providers/email-resend/index.ts",
  "providers/storage-firebase/index": "src/providers/storage-firebase/index.ts",
  "providers/payment-razorpay/index": "src/providers/payment-razorpay/index.ts",
  "providers/search-algolia/index": "src/providers/search-algolia/index.ts",
  "providers/shipping-shiprocket/index": "src/providers/shipping-shiprocket/index.ts",
};

const featureEntries = {
  "features/layout/index": "src/features/layout/index.ts",
  "features/forms/index": "src/features/forms/index.ts",
  "features/filters/index": "src/features/filters/index.ts",
  "features/media/index": "src/features/media/index.ts",
  "features/auth/index": "src/features/auth/index.ts",
  "features/account/index": "src/features/account/index.ts",
  "features/admin/index": "src/features/admin/index.ts",
  "features/cms/index": "src/features/cms/index.ts",
  "features/blog/index": "src/features/blog/index.ts",
  "features/cart/index": "src/features/cart/index.ts",
  "features/categories/index": "src/features/categories/index.ts",
  "features/checkout/index": "src/features/checkout/index.ts",
  "features/collections/index": "src/features/collections/index.ts",
  "features/consultation/index": "src/features/consultation/index.ts",
  "features/corporate/index": "src/features/corporate/index.ts",
  "features/events/index": "src/features/events/index.ts",
  "features/faq/index": "src/features/faq/index.ts",
  "features/homepage/index": "src/features/homepage/index.ts",
  "features/loyalty/index": "src/features/loyalty/index.ts",
  "features/orders/index": "src/features/orders/index.ts",
  "features/payments/index": "src/features/payments/index.ts",
  "features/products/index": "src/features/products/index.ts",
  "features/promotions/index": "src/features/promotions/index.ts",
  "features/reviews/index": "src/features/reviews/index.ts",
  "features/search/index": "src/features/search/index.ts",
  "features/seller/index": "src/features/seller/index.ts",
  "features/stores/index": "src/features/stores/index.ts",
  "features/wishlist/index": "src/features/wishlist/index.ts",
  "features/auctions/index": "src/features/auctions/index.ts",
  "features/pre-orders/index": "src/features/pre-orders/index.ts",
  "features/before-after/index": "src/features/before-after/index.ts",
  "features/whatsapp-bot/index": "src/features/whatsapp-bot/index.ts",
  "cli/index": "src/cli/index.ts",
};

export default defineConfig({
  entry: {
    ...primitiveEntries,
    ...providerEntries,
    ...featureEntries,
  },
  format: ["esm", "cjs"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  esbuildOptions(options) {
    options.alias = alias;
  },
  external: [
    "react",
    "react-dom",
    "next",
    "next-intl",
    "firebase-admin",
    "resend",
    "razorpay",
    "@upstash/redis",
    "@upstash/ratelimit",
    "@tanstack/react-query",
    "@tanstack/query-core",
  ],
});
