/*
 * GENERATED by scripts/gen-category-models.mjs — do not edit by hand.
 *
 * WHY: the clickable owner linkage. `Owner (Anime)` is 100% populated in the
 *      corpus but it is a SENTENCE — "Tyson Granger (Tyson's 9th and final
 *      bey)" — so it renders as prose and filters nothing. These are the
 *      normalised names as `character`-group features, which makes
 *      "show me every Tyson Granger bey" one click from any listing page.
 *
 * 🛑 A FEATURE and never a category node. A blader crosses every generation —
 *    Tyson owns nine beys spanning Spin Gear, Magnacore, Engine Gear and HMS —
 *    so a tree node would duplicate all nine under a second parent and break
 *    the one-chain-per-product invariant. As a feature it COMPOSES with the
 *    generation tree instead of competing with it: browse Beyblade Original,
 *    then narrow to Tyson's.
 *
 * @tag domain:products
 * @tag layer:seed
 * @tag pattern:generated
 * @tag access:server-only
 * @tag sideEffects:none
 */

/** A blader, and how many canonical beys the corpus attributes to them. */
export interface CharacterSeed {
  /** Without the `feature-` prefix — the factory prepends it. */
  slug: string;
  name: string;
  /** Canonical beys owned. Drives display order; not stored on the row. */
  beyCount: number;
}

export const CHARACTER_SEEDS: CharacterSeed[] = [
  { slug: "blader-tyson-granger", name: "Tyson Granger", beyCount: 9 },
  { slug: "blader-kai-hiwatari", name: "Kai Hiwatari", beyCount: 7 },
  { slug: "blader-daichi-sumeragi", name: "Daichi Sumeragi", beyCount: 6 },
  { slug: "blader-max-tate", name: "Max Tate", beyCount: 6 },
  { slug: "blader-ray-kon", name: "Ray Kon", beyCount: 6 },
  { slug: "blader-shu-kurenai", name: "Shu Kurenai", beyCount: 6 },
  { slug: "blader-gingka-hagane", name: "Gingka Hagane", beyCount: 5 },
  { slug: "blader-lui-shirosagi", name: "Lui Shirosagi", beyCount: 5 },
  { slug: "blader-tala", name: "Tala", beyCount: 5 },
  { slug: "blader-valt-aoi", name: "Valt Aoi", beyCount: 5 },
  { slug: "blader-free-de-la-hoya", name: "Free De La Hoya", beyCount: 4 },
  { slug: "blader-aiger-akabane", name: "Aiger Akabane", beyCount: 3 },
  { slug: "blader-dante-koryu", name: "Dante Koryu", beyCount: 3 },
  { slug: "blader-jaxon-cross", name: "Jaxon Cross", beyCount: 3 },
  { slug: "blader-kenta-yumiya", name: "Kenta Yumiya", beyCount: 3 },
  { slug: "blader-kyoya-tategami", name: "Kyoya Tategami", beyCount: 3 },
  { slug: "blader-multi-nana-iro", name: "Multi Nana-iro", beyCount: 3 },
  { slug: "blader-ryuga", name: "Ryuga", beyCount: 3 },
  { slug: "blader-benkei-hanawa", name: "Benkei Hanawa", beyCount: 2 },
  { slug: "blader-daigo-kurogami", name: "Daigo Kurogami", beyCount: 2 },
  { slug: "blader-damian-hart", name: "Damian Hart", beyCount: 2 },
  { slug: "blader-dashan-wang", name: "Dashan Wang", beyCount: 2 },
  { slug: "blader-delta-zakuro", name: "Delta Zakuro", beyCount: 2 },
  { slug: "blader-dunga", name: "Dunga", beyCount: 2 },
  { slug: "blader-eddy", name: "Eddy", beyCount: 2 },
  { slug: "blader-fumiya-kindo", name: "Fumiya Kindo", beyCount: 2 },
  { slug: "blader-hikaru-hizashi", name: "Hikaru Hizashi", beyCount: 2 },
  { slug: "blader-hyde", name: "Hyde", beyCount: 2 },
  { slug: "blader-jin-of-the-gale", name: "Jin of the Gale", beyCount: 2 },
  { slug: "blader-kira-hayama", name: "Kira Hayama", beyCount: 2 },
  { slug: "blader-lee", name: "Lee", beyCount: 2 },
  { slug: "blader-masamune-kadoya", name: "Masamune Kadoya", beyCount: 2 },
  { slug: "blader-michael-summers", name: "Michael Summers", beyCount: 2 },
  { slug: "blader-miguel", name: "Miguel", beyCount: 2 },
  { slug: "blader-ozuma", name: "Ozuma", beyCount: 2 },
  { slug: "blader-robin-kazami", name: "Robin Kazami", beyCount: 2 },
  { slug: "blader-tsubasa-otori", name: "Tsubasa Otori", beyCount: 2 },
  { slug: "blader-wakiya-murasaki", name: "Wakiya Murasaki", beyCount: 2 },
  { slug: "blader-xander-shakadera", name: "Xander Shakadera", beyCount: 2 },
  { slug: "blader-yu-tendo", name: "Yu Tendo", beyCount: 2 },
  { slug: "blader-aguma", name: "Aguma", beyCount: 1 },
  { slug: "blader-akuya-onizaki", name: "Akuya Onizaki", beyCount: 1 },
  { slug: "blader-anime", name: "Anime", beyCount: 1 },
  { slug: "blader-anime-secondary", name: "Anime-secondary", beyCount: 1 },
  { slug: "blader-blader-dj", name: "Blader DJ", beyCount: 1 },
  { slug: "blader-brooklyn", name: "Brooklyn", beyCount: 1 },
  { slug: "blader-chris", name: "Chris", beyCount: 1 },
  { slug: "blader-claude", name: "Claude", beyCount: 1 },
  { slug: "blader-clio-delon", name: "Clio Delon", beyCount: 1 },
  { slug: "blader-crusher", name: "Crusher", beyCount: 1 },
  { slug: "blader-cycnus", name: "Cycnus", beyCount: 1 },
  { slug: "blader-dan-sodo-and-reiki-sodo", name: "Dan Sodo and Reiki Sodo", beyCount: 1 },
  { slug: "blader-doji", name: "Doji", beyCount: 1 },
  { slug: "blader-faust", name: "Faust", beyCount: 1 },
  { slug: "blader-garland-siebald", name: "Garland Siebald", beyCount: 1 },
  { slug: "blader-gary", name: "Gary", beyCount: 1 },
  { slug: "blader-ginro", name: "Ginro", beyCount: 1 },
  { slug: "blader-hikaru-hasama", name: "Hikaru Hasama", beyCount: 1 },
  { slug: "blader-hokuto", name: "Hokuto", beyCount: 1 },
  { slug: "blader-hyoma", name: "Hyoma", beyCount: 1 },
  { slug: "blader-hyuga-hizashi", name: "Hyuga Hizashi", beyCount: 1 },
  { slug: "blader-ian-papov", name: "Ian Papov", beyCount: 1 },
  { slug: "blader-johnny-mcgregor", name: "Johnny McGregor", beyCount: 1 },
  { slug: "blader-joseph-burton", name: "Joseph Burton", beyCount: 1 },
  { slug: "blader-julia-fernandez", name: "Julia Fernandez", beyCount: 1 },
  { slug: "blader-julian-konzern", name: "Julian Konzern", beyCount: 1 },
  { slug: "blader-karla-konjiki", name: "Karla Konjiki", beyCount: 1 },
  { slug: "blader-ken-midori", name: "Ken Midori", beyCount: 1 },
  { slug: "blader-kenny", name: "Kenny", beyCount: 1 },
  { slug: "blader-kevin", name: "Kevin", beyCount: 1 },
  { slug: "blader-kite-unabara", name: "Kite Unabara", beyCount: 1 },
  { slug: "blader-lain-valhalla", name: "Lain Valhalla", beyCount: 1 },
  { slug: "blader-meiko-myoden", name: "Meiko Myoden", beyCount: 1 },
  { slug: "blader-nile", name: "Nile", beyCount: 1 },
  { slug: "blader-nine-kurosu", name: "Nine Kurosu", beyCount: 1 },
  { slug: "blader-omega-shiroboshi", name: "Omega Shiroboshi", beyCount: 1 },
  { slug: "blader-phi", name: "Phi", beyCount: 1 },
  { slug: "blader-rago", name: "Rago", beyCount: 1 },
  { slug: "blader-reiji-mizuchi", name: "Reiji Mizuchi", beyCount: 1 },
  { slug: "blader-reiyu-kuwabara", name: "Reiyu Kuwabara", beyCount: 1 },
  { slug: "blader-rex-jura", name: "Rex Jura", beyCount: 1 },
  { slug: "blader-rick-anderson", name: "Rick Anderson", beyCount: 1 },
  { slug: "blader-robert-jurgens", name: "Robert Jurgens", beyCount: 1 },
  { slug: "blader-sakyo-kurayami", name: "Sakyo Kurayami", beyCount: 1 },
  { slug: "blader-silas-karlisle", name: "Silas Karlisle", beyCount: 1 },
  { slug: "blader-spencer", name: "Spencer", beyCount: 1 },
  { slug: "blader-teru-saotome", name: "Teru Saotome", beyCount: 1 },
  { slug: "blader-tobio-oike", name: "Tobio Oike", beyCount: 1 },
  { slug: "blader-toby", name: "Toby", beyCount: 1 },
  { slug: "blader-toguro-okunaga", name: "Toguro Okunaga", beyCount: 1 },
  { slug: "blader-yuki-mizusawa", name: "Yuki Mizusawa", beyCount: 1 },
  { slug: "blader-yuni-naniwa", name: "Yuni Naniwa", beyCount: 1 },
  { slug: "blader-zyro-kurogane", name: "Zyro Kurogane", beyCount: 1 },
];

export const CHARACTER_SEED_COUNT = 93;
