/*
 * WHY: Shared tester sandbox — a handful of disposable test products spanning standard,
 *      auction, and pre-order listing types, all owned by store-tester-sandbox, so testers
 *      can exercise buying/bidding/pre-ordering against real code paths. Auto-expires after
 *      7 days (testerSandboxCleanup cascades into any bids on the auction).
 * WHAT: Exports productsTesterSeedData — 2 standard + 1 auction + 1 pre-order product.
 *
 * EXPORTS:
 *   productsTesterSeedData — Array of Partial<ProductDocument> for the seed runner
 *
 * @tag domain:products,tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed-cli.mjs
 * @tag sideEffects:none
 */

import { ProductDocument } from "../../products/schemas/firestore";
import { PRODUCT_FIELDS } from "../../../constants/field-names";
import { buildSearchTokens } from "../../../utils/search-tokens";
import { seedExtMedia } from "../../../seed/_helpers/media";
import { testDataExpiresAt } from "./tester-ttl";

const TESTER_STORE_ID = "store-tester-sandbox";
const TESTER_STORE_NAME = "Tester Sandbox Store";
const GADGETS_CATEGORY_SLUGS = ["category-tester-gadgets", "category-tester-sandbox"];
const GADGETS_CATEGORY_NAMES = ["Test Gadgets", "Tester Sandbox"];
const COLLECTIBLES_CATEGORY_SLUGS = ["category-tester-collectibles", "category-tester-sandbox"];
const COLLECTIBLES_CATEGORY_NAMES = ["Test Collectibles", "Tester Sandbox"];

function withTokens(p: Partial<ProductDocument>): Partial<ProductDocument> {
  return {
    tags: [],
    featured: false,
    isTestData: true,
    testDataExpiresAt: testDataExpiresAt(),
    storeId: TESTER_STORE_ID,
    storeName: TESTER_STORE_NAME,
    ...p,
    searchTokens: buildSearchTokens(p.title, p.description, p.brand, p.brandSlug, p.categoryNames, p.tags),
  };
}

export const productsTesterSeedData: Partial<ProductDocument>[] = [
  withTokens({
    id: "product-tester-standard-1",
    slug: "product-tester-standard-1",
    title: "Test Gadget — Standard Listing #1",
    description: "Disposable test product for the tester QA program. Buy it, review it, wishlist it — it auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 199,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "product-tester-standard-2",
    slug: "product-tester-standard-2",
    title: "Test Collectible — Standard Listing #2",
    description: "Second disposable test product, referenced by the test bundle. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 149,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-2-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-2-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "auction-tester-sandbox-1",
    slug: "auction-tester-sandbox-1",
    title: "Test Auction — Bid Me!",
    description: "Disposable test auction for the tester QA program. Place a bid — it auto-expires in 7 days, cascading to any bids.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    startingBid: 15000,
    currentBid: 15000,
    currency: "INR",
    price: 150,
    stockQuantity: 1,
    availableQuantity: 1,
    auctionEndDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    bidCount: 0,
    bidsHaveStarted: false,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/auction-image-tester-sandbox-1-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/auction-image-tester-sandbox-1-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "auction" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "auction-tester-sandbox-won",
    slug: "auction-tester-sandbox-won",
    title: "Test Auction — Already Won",
    description: "Disposable test auction, already ended and won, paired with a \"won auction\" test order. Auto-expires in 7 days, cascading to its bid.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    startingBid: 8000,
    currentBid: 15000,
    currency: "INR",
    price: 150,
    stockQuantity: 1,
    availableQuantity: 0,
    auctionEndDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    bidCount: 1,
    bidsHaveStarted: true,
    leadingBidderId: "user-tester-qa",
    isSold: true,
    mainImage: seedExtMedia("https://picsum.photos/seed/auction-image-tester-sandbox-won-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/auction-image-tester-sandbox-won-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "auction" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "preorder-tester-sandbox-1",
    slug: "preorder-tester-sandbox-1",
    title: "Test Pre-order — Reserve Me!",
    description: "Disposable test pre-order for the tester QA program. Auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 299,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    images: [seedExtMedia("https://picsum.photos/seed/preorder-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/preorder-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    availableQuantity: 5,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "in_production",
    preOrderDepositPercent: 25,
    preOrderMaxQuantity: 50,
    preOrderCurrentCount: 0,
    preOrderCancellable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "prizedraw-tester-sandbox-1",
    slug: "prizedraw-tester-sandbox-1",
    title: "Test Prize Draw — Reveal Me!",
    description: "Disposable test prize-draw for the tester QA program. Buy an entry, then reveal — auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 50,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "prize-draw" as const,
    images: [seedExtMedia("https://picsum.photos/seed/prizedraw-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 3,
    availableQuantity: 3,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    prizeDrawMode: "reveal" as const,
    pricePerEntry: 50,
    prizeMaxEntries: 3,
    prizeCurrentEntries: 0,
    prizeRevealWindowStart: new Date(),
    prizeRevealWindowEnd: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    prizeRevealStatus: "open" as const,
    prizeRevealDeadlineDays: 7,
    prizeDrawItems: [
      { itemNumber: 1, title: "Test Prize — Grand", description: "Disposable test grand prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-1-20260101/600/600")], condition: "new", estimatedValue: 500, isWon: false },
      { itemNumber: 2, title: "Test Prize — Runner-up", description: "Disposable test runner-up prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-2-20260101/600/600")], condition: "new", estimatedValue: 150, isWon: false },
      { itemNumber: 3, title: "Test Prize — Consolation", description: "Disposable test consolation prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-3-20260101/600/600")], condition: "new", estimatedValue: 20, isWon: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "classified-tester-sandbox-1",
    slug: "classified-tester-sandbox-1",
    title: "Test Classified — Contact Me!",
    description: "Disposable test classified listing for the tester QA program. No checkout — contact the seller. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 250,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.GOOD,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "classified" as const,
    images: [seedExtMedia("https://picsum.photos/seed/classified-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 1,
    availableQuantity: 1,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    classified: {
      meetupArea: { city: "Bengaluru", locality: "Test Locality", pincode: "560001" },
      contactMethod: "both" as const,
      acceptsShipping: false,
      negotiable: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "digitalcode-tester-sandbox-1",
    slug: "digitalcode-tester-sandbox-1",
    title: "Test Digital Code — Auto-Claim!",
    description: "Disposable test digital-code listing for the tester QA program. Auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 99,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "digital-code" as const,
    images: [seedExtMedia("https://picsum.photos/seed/digitalcode-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 10,
    availableQuantity: 10,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 10,
      codesAvailable: 10,
      redemptionInstructions: "Disposable test code — redeem at test-redeem.example for tester QA purposes only.",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "live-tester-sandbox-1",
    slug: "live-tester-sandbox-1",
    title: "Test Live Item — Watch Me!",
    description: "Disposable test live-item listing for the tester QA program. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 1500,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "live" as const,
    images: [seedExtMedia("https://picsum.photos/seed/live-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/live-image-tester-sandbox-1-20260101/900/900"),
    video: { url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" } as unknown as ProductDocument["video"],
    isSold: false,
    stockQuantity: 1,
    availableQuantity: 1,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    liveItem: {
      species: "Test Species",
      ageMonths: 6,
      sex: "n/a" as const,
      careInfo: "Disposable test care info for the tester QA program.",
      transport: { method: "courier" as const, handlingFee: 100, insuranceIncluded: true },
      jurisdictionAllowed: ["IN-KA", "IN-MH"],
      vendorVerified: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "group-tester-sandbox-bundle",
    slug: "group-tester-sandbox-bundle",
    title: "Test Bundle — Standard #1 + Standard #2",
    description: "Disposable test bundle bundling the two tester-sandbox standard products. Auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 329,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "standard" as const,
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 5,
    availableQuantity: 5,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    isGroupParent: true,
    groupId: "group-tester-sandbox-bundle",
    groupTitle: "Tester Sandbox Bundle",
    groupChildSlugs: ["product-tester-standard-1", "product-tester-standard-2"],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
];
