/*
 * WHY: Shared tester sandbox — a handful of disposable test products spanning every listing
 *      type (standard, auction, pre-order, prize-draw, classified, digital-code, live, art,
 *      stickers), all owned by store-tester-sandbox, so testers can exercise buying/bidding/
 *      pre-ordering against real code paths — including navigating every entry of the store
 *      detail page's listing-type dropdown (see StoreNavTabs). Auto-expires after 7 days
 *      (testerSandboxCleanup cascades into any bids on the auction).
 * WHAT: Exports productsTesterSeedData — 2 standard + 4 auction (3 staggered 1h/2h/3h "still
 *       open" cycling fixtures + 1 already-ended "won" fixture) + 1 pre-order + 1 prize-draw +
 *       1 classified + 1 digital-code + 1 live + 1 art + 1 stickers product + 1 product-group
 *       ("Set") parent (product-tester-standard-1/2 are its children, linked via groupId).
 *       The 3 staggered auction ids/end-dates are recomputed on every seed run (including the
 *       testerSandboxRefresh job, every 4h) so testers can watch one actually end mid-session.
 *
 * EXPORTS:
 *   productsTesterSeedData — Array of Partial<ProductDocument> for the seed runner
 *
 * @tag domain:products,tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed-cli.mjs
 * @tag sideEffects:none
 */

import { ProductDocument } from "../../products/schemas/firestore";
import { PRODUCT_FIELDS } from "../../../constants/field-names";
import { buildSearchTokens } from "../../../utils/search-tokens";
import { seedExtMedia } from "../../../seed/_helpers/media";
import { testDataExpiresAt } from "./tester-ttl";

const TESTER_STORE_ID = "store-tester-sandbox";
const TESTER_STORE_NAME = "Tester Sandbox Store";
const TESTER_GROUP_TITLE = "Tester Sandbox Bundle";
const GADGETS_CATEGORY_SLUGS = ["category-tester-gadgets", "category-tester-sandbox"];
const GADGETS_CATEGORY_NAMES = ["Test Gadgets", "Tester Sandbox"];
const COLLECTIBLES_CATEGORY_SLUGS = ["category-tester-collectibles", "category-tester-sandbox"];
const COLLECTIBLES_CATEGORY_NAMES = ["Test Collectibles", "Tester Sandbox"];

function withTokens(p: Partial<ProductDocument>): Partial<ProductDocument> {
  return {
    tags: [],
    featured: false,
    isTestData: true,
    testDataExpiresAt: testDataExpiresAt(),
    storeId: TESTER_STORE_ID,
    storeName: TESTER_STORE_NAME,
    ...p,
    searchTokens: buildSearchTokens(p.title, p.description, p.brand, p.brandSlug, p.categoryNames, p.tags),
  };
}

// Staggered, incrementing-id auction fixtures so testers can watch a live
// auction actually cross its end time within a single sandbox refresh cycle
// (testerSandboxRefresh re-imports this module every 4 hours, recomputing
// these Date.now()-relative offsets fresh each time) instead of the old
// single fixture that always sat 5 days out. A loop (not hand-typed ids)
// avoids id collisions if the stagger list is ever extended.
const AUCTION_CYCLE_STAGGER_HOURS = [1, 2, 3];
const stagedAuctions: Partial<ProductDocument>[] = AUCTION_CYCLE_STAGGER_HOURS.map((hours, i) =>
  withTokens({
    id: `auction-tester-sandbox-cycle-${i + 1}`,
    slug: `auction-tester-sandbox-cycle-${i + 1}`,
    title: `Test Auction — Ends in ~${hours}h`,
    description: `Disposable test auction for the tester QA program, staggered to end roughly ${hours} hour(s) after the last sandbox refresh so testers can watch the end-of-auction flow live. Place a bid — it auto-expires in 7 days, cascading to any bids.`,
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    startingBid: 15000,
    currentBid: 15000,
    currency: "INR",
    price: 150,
    stockQuantity: 1,
    availableQuantity: 1,
    auctionEndDate: new Date(Date.now() + hours * 60 * 60 * 1000),
    bidCount: 0,
    bidsHaveStarted: false,
    isSold: false,
    mainImage: seedExtMedia(`https://picsum.photos/seed/auction-image-tester-sandbox-cycle-${i + 1}-20260101/900/900`),
    images: [seedExtMedia(`https://picsum.photos/seed/auction-image-tester-sandbox-cycle-${i + 1}-20260101/900/900`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "auction" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
);

/**
 * Buy-Now (buyout) fixtures. Four states, because the 2026-08-24 rework made
 * buyout availability depend on `buyNowPrice > currentBid` rather than on
 * "nobody has bid yet" — so the interesting cases are now about PRICE, and
 * three of them were previously unreachable as test data.
 *
 * Every date is Date.now()-relative at module import, per CLAUDE.md's tester
 * fixture standard, so the 4-hour testerSandboxRefresh re-arms them.
 */
const buyoutAuctions: Partial<ProductDocument>[] = [
  {
    key: "buyout",
    title: "Test Auction — Buy It Now available",
    desc: "The clean buyout case. Buy Now is offered, there is plenty of clock, and completing checkout within the hour should close the auction as sold with your bid recorded at the buyout price.",
    currentBid: 8000,
    buyNowPrice: 12000,
    bidCount: 0,
    bidsHaveStarted: false,
    endsInHours: 6,
  },
  {
    key: "buyout-contested",
    title: "Test Auction — Buy It Now with live bidding",
    desc: "Buy Now is STILL offered even though bidding has started, because the buyout price is above the current bid. Buying it out should mark the other bidders lost. This case did not exist before the bidsHaveStarted gate was dropped.",
    currentBid: 9500,
    buyNowPrice: 12000,
    bidCount: 2,
    bidsHaveStarted: true,
    endsInHours: 6,
  },
  {
    key: "buyout-passed",
    title: "Test Auction — bidding passed Buy It Now",
    desc: "Negative control. Bidding has overtaken the buyout price, so Buy Now must appear NOWHERE — no button, no advertised price on the detail page, no Buyout chip on the card.",
    currentBid: 9500,
    buyNowPrice: 9000,
    bidCount: 5,
    bidsHaveStarted: true,
    endsInHours: 6,
  },
  {
    key: "buyout-expiring",
    title: "Test Auction — Buy It Now, ends in ~20 minutes",
    desc: "The buyout hold is clamped to the auction's own end time rather than the full hour. Start a buyout here and DON'T finish checkout: when the clock runs out the buyout must fail and the item must go to the bidding, not to you.",
    currentBid: 3000,
    buyNowPrice: 5000,
    bidCount: 1,
    bidsHaveStarted: true,
    endsInMinutes: 20,
  },
].map((f) =>
  withTokens({
    id: `auction-tester-sandbox-${f.key}`,
    slug: `auction-tester-sandbox-${f.key}`,
    title: f.title,
    description: f.desc,
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    startingBid: 8000,
    currentBid: f.currentBid,
    buyNowPrice: f.buyNowPrice,
    currency: "INR",
    price: f.currentBid,
    stockQuantity: 1,
    availableQuantity: 1,
    auctionEndDate: new Date(
      Date.now() +
        (f.endsInMinutes ? f.endsInMinutes * 60 * 1000 : (f.endsInHours ?? 6) * 60 * 60 * 1000),
    ),
    bidCount: f.bidCount,
    bidsHaveStarted: f.bidsHaveStarted,
    isSold: false,
    mainImage: seedExtMedia(`https://picsum.photos/seed/auction-image-tester-sandbox-${f.key}-20260101/900/900`),
    images: [seedExtMedia(`https://picsum.photos/seed/auction-image-tester-sandbox-${f.key}-20260101/900/900`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "auction" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
);

/**
 * An offerable standard listing, owned by the tester's OWN sandbox store
 * (`withTokens` supplies `storeId: TESTER_STORE_ID`).
 *
 * That ownership is the point: one tester can drive the whole negotiation
 * solo — make the offer at /products/product-tester-offerable as the buyer,
 * then accept/counter/decline it at /store/offers as the seller. The
 * complementary fixture `offer-tester-sandbox-accepted` covers the other half
 * (an already-accepted offer on somebody ELSE's store, so the checkout lane can
 * be exercised without the tester having accepted it themselves).
 */
const offerableProduct: Partial<ProductDocument> = withTokens({
  id: "product-tester-offerable",
  slug: "product-tester-offerable",
  title: "Test Gadget — Accepts Offers",
  description: "Disposable test product with buyer offers enabled. Make an offer below the listed price and watch it appear under My Offers. Minimum accepted offer is 70% of the listed price.",
  categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
  categoryNames: COLLECTIBLES_CATEGORY_NAMES,
  brandSlug: "brand-tester-sandbox",
  brand: "TestBrand",
  price: 2000,
  currency: "INR",
  allowOffers: true,
  minOfferPercent: 70,
  stockQuantity: 5,
  availableQuantity: 5,
  isSold: false,
  mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-offerable-20260101/900/900"),
  images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-offerable-20260101/900/900")],
  status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
  condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
  listingType: "standard" as const,
  customFields: [],
  customSections: [],
  isPromoted: false,
  isOnSale: false,
  createdAt: new Date(),
  updatedAt: new Date(),
});

export const productsTesterSeedData: Partial<ProductDocument>[] = [
  ...stagedAuctions,
  ...buyoutAuctions,
  offerableProduct,
  withTokens({
    id: "product-tester-standard-1",
    slug: "product-tester-standard-1",
    title: "Test Gadget — Standard Listing #1",
    description: "Disposable test product for the tester QA program. Buy it, review it, wishlist it — it auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 199,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    // 18% — contrasts with member #3's 12% so one grouped line spans two rates.
    gstRate: 18 as const,
    hsnCode: "95030090",
    // Child of the "group-tester-sandbox-bundle" product-group ("Set") parent
    // below — findByGroupId() queries products by this field directly, so
    // without it the parent's groupChildSlugs[] mirror is never actually
    // resolvable and ShowGroupSection renders nothing (members.length <= 1).
    groupId: "group-tester-sandbox-bundle",
    groupParentSlug: "group-tester-sandbox-bundle",
    groupTitle: TESTER_GROUP_TITLE,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "product-tester-standard-2",
    slug: "product-tester-standard-2",
    title: "Test Collectible — Standard Listing #2",
    description: "Second disposable test product, referenced by the test bundle. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 149,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-2-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-2-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    gstRate: 18 as const,
    hsnCode: "95030090",
    groupId: "group-tester-sandbox-bundle",
    groupParentSlug: "group-tester-sandbox-bundle",
    groupTitle: TESTER_GROUP_TITLE,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "product-tester-standard-3",
    slug: "product-tester-standard-3",
    title: "Test Sticker Pack — Standard Listing #3",
    description:
      "Third member of the test product group. Carries a DIFFERENT gstRate from its siblings on purpose: it is the only fixture that exercises per-member GST proration on a grouped/bundled cart line, where taxing the whole line at one product's rate would be wrong in both directions. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 99,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-3-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-3-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    // 12% against the siblings' 18% — the whole point of this fixture.
    gstRate: 12 as const,
    hsnCode: "49081000",
    groupId: "group-tester-sandbox-bundle",
    groupParentSlug: "group-tester-sandbox-bundle",
    groupTitle: TESTER_GROUP_TITLE,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  // ── Grouped-cart-line fixtures ───────────────────────────────────────────
  // Each of the three below exists to make ONE picker branch testable by hand.
  // Without them the branch can only be reached by editing data live, which a
  // reseed silently wipes out.
  withTokens({
    id: "product-tester-group-soldout",
    slug: "product-tester-group-soldout",
    title: "Test Part — Sold Out (Group Member)",
    description:
      "A member of the tester product group that is deliberately out of stock. Exists so the group picker's blocked-member branch has real data: it must render a reason chip instead of a +/- stepper, and must not be selectable. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 129,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    isSold: true,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-group-soldout-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-group-soldout-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    gstRate: 18 as const,
    hsnCode: "95030090",
    groupId: "group-tester-sandbox-bundle",
    groupParentSlug: "group-tester-sandbox-bundle",
    groupTitle: TESTER_GROUP_TITLE,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  // A group whose members span TWO stores. `storeId` is the order-splitting key
  // and the key per-store add-ons/coupons/shipping/payout hang off, so such a
  // group can never become one cart line — the picker must stand down to a
  // read-only table rather than offer a button that always fails.
  // `withTokens` spreads `...p` last, so the storeId below overrides the
  // sandbox default on purpose.
  withTokens({
    id: "product-tester-crossstore-a",
    slug: "product-tester-crossstore-a",
    title: "Test Cross-Store Set — Seller A",
    description:
      "Parent of a deliberately CROSS-STORE tester group. Its sibling belongs to a different seller, so the group picker must render read-only with no quantity column and no \"Add selected\" button. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 259,
    currency: "INR",
    stockQuantity: 6,
    availableQuantity: 6,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-crossstore-a-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-crossstore-a-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    gstRate: 18 as const,
    isGroupParent: true,
    groupId: "group-tester-cross-store",
    groupTitle: "Tester Cross-Store Set",
    groupChildSlugs: ["product-tester-crossstore-b"],
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "product-tester-crossstore-b",
    slug: "product-tester-crossstore-b",
    title: "Test Cross-Store Set — Seller B",
    description:
      "Sibling of product-tester-crossstore-a, deliberately owned by a DIFFERENT store so the group spans two sellers. Still isTestData, so filterTestDataForViewer keeps it off that store's public listings for non-testers. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 189,
    currency: "INR",
    stockQuantity: 6,
    availableQuantity: 6,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-crossstore-b-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-crossstore-b-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    gstRate: 12 as const,
    // The whole point of this fixture — a different seller from its sibling.
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    groupId: "group-tester-cross-store",
    groupParentSlug: "product-tester-crossstore-a",
    groupTitle: "Tester Cross-Store Set",
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "product-tester-standard-sold",
    slug: "product-tester-standard-sold",
    title: "Test Collectible — Sold Out (Hidden by Default)",
    description: "Disposable test product deliberately seeded as sold out — exists to verify the public/admin/seller \"Show sold\" toggle actually hides it by default and reveals it when toggled on. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 179,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    isSold: true,
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-sold-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-sold-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "standard" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "auction-tester-sandbox-won",
    slug: "auction-tester-sandbox-won",
    title: "Test Auction — Already Won",
    description: "Disposable test auction, already ended and won, paired with a \"won auction\" test order. Auto-expires in 7 days, cascading to its bid.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    startingBid: 8000,
    currentBid: 15000,
    currency: "INR",
    price: 150,
    stockQuantity: 1,
    availableQuantity: 0,
    auctionEndDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    bidCount: 1,
    bidsHaveStarted: true,
    leadingBidderId: "user-tester-qa",
    isSold: true,
    mainImage: seedExtMedia("https://picsum.photos/seed/auction-image-tester-sandbox-won-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/auction-image-tester-sandbox-won-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "auction" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "preorder-tester-sandbox-1",
    slug: "preorder-tester-sandbox-1",
    title: "Test Pre-order — Reserve Me!",
    description: "Disposable test pre-order for the tester QA program. Auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 299,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    images: [seedExtMedia("https://picsum.photos/seed/preorder-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/preorder-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    // stockQuantity must be set (not just availableQuantity) — the public
    // listing route's default "hide sold" filter is a Firestore inequality
    // on stockQuantity, and Firestore excludes documents missing that field
    // entirely from an inequality query, not just ones where it's 0. Without
    // this the pre-order would be permanently invisible on the default
    // /pre-orders listing (2026-08-19 index-sweep session).
    stockQuantity: 5,
    availableQuantity: 5,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "in_production",
    preOrderDepositPercent: 25,
    preOrderMaxQuantity: 50,
    preOrderCurrentCount: 0,
    preOrderCancellable: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "prizedraw-tester-sandbox-1",
    slug: "prizedraw-tester-sandbox-1",
    title: "Test Prize Draw — Reveal Me!",
    description: "Disposable test prize-draw for the tester QA program. Buy an entry, then reveal — auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 50,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "prize-draw" as const,
    images: [seedExtMedia("https://picsum.photos/seed/prizedraw-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 3,
    availableQuantity: 3,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "instant" as const,
    pricePerEntry: 50,
    prizeMaxEntries: 3,
    prizeCurrentEntries: 0,
    prizeDrawDurationDays: 7,
    prizeRevealWindowStart: new Date(),
    prizeRevealWindowEnd: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    prizeRevealStatus: "open" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Test Prize — Grand", description: "Disposable test grand prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-1-20260101/600/600")], condition: "new", estimatedValue: 500, isWon: false },
      { itemNumber: 2, title: "Test Prize — Runner-up", description: "Disposable test runner-up prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-2-20260101/600/600")], condition: "new", estimatedValue: 150, isWon: false },
      { itemNumber: 3, title: "Test Prize — Consolation", description: "Disposable test consolation prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-3-20260101/600/600")], condition: "new", estimatedValue: 20, isWon: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "prizedraw-tester-sandbox-closed",
    slug: "prizedraw-tester-sandbox-closed",
    title: "Test Prize Draw — Already Closed",
    description: "Disposable test prize-draw, window already closed — exists to verify the admin/seller \"Show closed\" toggle actually hides it by default and reveals it when toggled on. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 50,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "prize-draw" as const,
    images: [seedExtMedia("https://picsum.photos/seed/prizedraw-image-tester-sandbox-closed-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-tester-sandbox-closed-20260101/900/900"),
    isSold: true,
    stockQuantity: 0,
    availableQuantity: 0,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "scheduled" as const,
    pricePerEntry: 50,
    prizeMaxEntries: 3,
    prizeCurrentEntries: 3,
    prizeDrawDurationDays: 13,
    prizeRevealWindowStart: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    prizeRevealWindowEnd: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    prizeRevealStatus: "closed" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Test Prize — Grand", description: "Disposable test grand prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-closed-1-20260101/600/600")], condition: "new", estimatedValue: 500, isWon: true },
      { itemNumber: 2, title: "Test Prize — Runner-up", description: "Disposable test runner-up prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-closed-2-20260101/600/600")], condition: "new", estimatedValue: 150, isWon: true },
      { itemNumber: 3, title: "Test Prize — Consolation", description: "Disposable test consolation prize.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-closed-3-20260101/600/600")], condition: "new", estimatedValue: 20, isWon: true },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "classified-tester-sandbox-1",
    slug: "classified-tester-sandbox-1",
    title: "Test Classified — Contact Me!",
    description: "Disposable test classified listing for the tester QA program. No checkout — make an offer or contact the seller. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 250,
    currency: "INR",
    // Classifieds are the one non-standard type with `canMakeOffer: true`.
    // Until 2026-08-24 the sticky "Make an Offer" CTA on this page only
    // scrolled to the chat box and created no offer at all — this flag is what
    // makes the real form render there.
    allowOffers: true,
    minOfferPercent: 70,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.GOOD,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "classified" as const,
    images: [seedExtMedia("https://picsum.photos/seed/classified-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 1,
    availableQuantity: 1,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    classified: {
      meetupArea: { city: "Bengaluru", locality: "Test Locality", pincode: "560001" },
      contactMethod: "both" as const,
      acceptsShipping: false,
      negotiable: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "digitalcode-tester-sandbox-1",
    slug: "digitalcode-tester-sandbox-1",
    title: "Test Digital Code — Auto-Claim!",
    description: "Disposable test digital-code listing for the tester QA program. Auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 99,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "digital-code" as const,
    images: [seedExtMedia("https://picsum.photos/seed/digitalcode-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-tester-sandbox-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 10,
    availableQuantity: 10,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 10,
      codesAvailable: 10,
      redemptionInstructions: "Disposable test code — redeem at test-redeem.example for tester QA purposes only.",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "live-tester-sandbox-1",
    slug: "live-tester-sandbox-1",
    title: "Test Live Item — Golden Retriever Puppy",
    description: "Disposable test live-item listing for the tester QA program (verifies the mandatory-video rule, gallery video slide, and watermark on a real animal listing). Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 1500,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "live" as const,
    images: [seedExtMedia("https://picsum.photos/seed/live-image-tester-sandbox-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/live-image-tester-sandbox-1-20260101/900/900"),
    // Real, directly-playable dog video (a raw <video> element, not routed through
    // /api/media/ext which is image-only — Root Cause #27) — Wikimedia Commons,
    // CC-BY-SA 4.0, https://commons.wikimedia.org/wiki/File:Slow_motion_of_running_greyhound.webm.
    // Exercises the mandatory-video-for-live rule + gallery video slide + watermark
    // on a genuine "animal actually moving" clip instead of a broken YouTube watch-page URL.
    video: {
      url: "https://upload.wikimedia.org/wikipedia/commons/4/42/Slow_motion_of_running_greyhound.webm", // audit-seed-external-url-ok: raw <video> src, CC-BY-SA 4.0 (Wikimedia Commons)
      thumbnailUrl: seedExtMedia("https://picsum.photos/seed/live-video-thumb-tester-sandbox-1-20260101/800/450"),
      duration: 14,
    },
    isSold: false,
    stockQuantity: 1,
    availableQuantity: 1,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    liveItem: {
      species: "Dog (Golden Retriever)",
      ageMonths: 6,
      sex: "male" as const,
      careInfo: "Disposable test care info for the tester QA program.",
      transport: { method: "courier" as const, handlingFee: 100, insuranceIncluded: true },
      jurisdictionAllowed: ["IN-KA", "IN-MH"],
      vendorVerified: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
  withTokens({
    id: "art-tester-sandbox-1",
    slug: "art-tester-sandbox-1",
    title: "Test Art Print — Frame Me!",
    description: "Disposable test art listing for the tester QA program. Auto-expires in 7 days.",
    categorySlugs: COLLECTIBLES_CATEGORY_SLUGS,
    categoryNames: COLLECTIBLES_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 349,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 5,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/art-image-tester-sandbox-1-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/art-image-tester-sandbox-1-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "art" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "stickers-tester-sandbox-1",
    slug: "stickers-tester-sandbox-1",
    title: "Test Sticker Pack — Peel Me!",
    description: "Disposable test stickers listing for the tester QA program. Auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 79,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 25,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/stickers-image-tester-sandbox-1-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/stickers-image-tester-sandbox-1-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "stickers" as const,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }),
  withTokens({
    id: "group-tester-sandbox-bundle",
    slug: "group-tester-sandbox-bundle",
    // Product-group ("Set") parent — Tier GP, unrelated to the Bundles
    // feature (categoryType:"bundle") despite the legacy "bundle" id/slug.
    // Kept stable rather than renamed since nothing outside this file's
    // internal group wiring depends on the "bundle" name.
    title: "Test Product Set — Standard #1 + Standard #2",
    description: "Disposable test product-group parent linking the two tester-sandbox standard products as a \"Set\". Auto-expires in 7 days.",
    categorySlugs: GADGETS_CATEGORY_SLUGS,
    categoryNames: GADGETS_CATEGORY_NAMES,
    brandSlug: "brand-tester-sandbox",
    brand: "TestBrand",
    price: 329,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "standard" as const,
    images: [seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900")],
    mainImage: seedExtMedia("https://picsum.photos/seed/product-image-tester-standard-1-20260101/900/900"),
    isSold: false,
    stockQuantity: 5,
    availableQuantity: 5,
    customFields: [],
    customSections: [],
    isPromoted: false,
    isOnSale: false,
    isGroupParent: true,
    groupId: "group-tester-sandbox-bundle",
    groupTitle: TESTER_GROUP_TITLE,
    // Parent↔child mirror: every id here must also carry `groupId` on its own
    // document. The pair drifting is Root Cause #42's second instance.
    groupChildSlugs: [
      "product-tester-standard-1",
      "product-tester-standard-2",
      "product-tester-standard-3",
      "product-tester-group-soldout",
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as unknown as Partial<ProductDocument>),
];
