/*
 * WHY: Authored six-part procedures for the account-auth/testing-program checklist page.
 * WHAT: 1 case(s), keyed by full checklist id.
 *
 * Generated by `node tester/scripts/merge-authored.mjs --page account-auth/testing-program`, then
 * reviewed by a human before merge — the review is the gate, not the generation.
 * Hand edits are safe and expected: re-running the merge for this page replaces
 * the file, so re-author only when you mean to discard them.
 *
 * @tag domain:tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed-data/authored/index.ts
 * @tag sideEffects:none
 */

import type { AuthoredCase } from "./_types";

export const authored: Record<string, AuthoredCase> = {
  "checklist-account-auth-testing-program-admin-testing-section": {
    roles: ["admin"],
    startPage: "/admin/dashboard",
    steps: [
      "Sign in as admin@letitrip.in.",
      "Open /admin/dashboard.",
      "Locate the 'Admin Panel' sidebar on the right side of the page.",
      "Click the 'Testing' section heading in the sidebar to expand it.",
      "Locate the 'Test Cases' link in the Testing section.",
      "Locate the 'Results' link in the Testing section.",
    ],
    expectedBehaviour: "The admin sidebar renders a 'Testing' collapsible section containing at least two links: 'Test Cases' (pointing to /admin/tester-checklist) and 'Results' (pointing to /admin/tester-feedback). Both links are clickable and navigate to their respective pages.",
    expectedUiState: "The Testing section is visible in the Admin Panel sidebar. It contains a 'Test Cases' link and a 'Results' link. Both links are present and labelled exactly 'Test Cases' and 'Results'.",
    endResult: "After reload, the sidebar still shows the Testing section with both links. No data is persisted by this case — it is a read-only navigation check.",
  },
};
