/*
 * WHY: Authored six-part procedures for the account-auth/profile-settings checklist page.
 * WHAT: 9 case(s), keyed by full checklist id.
 *
 * Generated by `node tester/scripts/merge-authored.mjs --page account-auth/profile-settings`, then
 * reviewed by a human before merge — the review is the gate, not the generation.
 * Hand edits are safe and expected: re-running the merge for this page replaces
 * the file, so re-author only when you mean to discard them.
 *
 * @tag domain:tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed-data/authored/index.ts
 * @tag sideEffects:none
 */

import type { AuthoredCase } from "./_types";

export const authored: Record<string, AuthoredCase> = {
  "checklist-account-auth-profile-settings-avatar-upload": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/profile.",
      "Click 'Profile Details' to expand the section.",
      "Click 'Edit Profile'.",
      "Click 'Choose image'.",
      "Select a JPG or PNG image file under 10 MB from your local machine.",
      "Click 'Save changes'.",
      "Reload the page.",
      "Click 'Profile Details' to expand the section.",
      "Click 'Edit Profile'.",
    ],
    expectedBehaviour: "The image is uploaded and saved as the user's profile avatar. After reload the new avatar image is shown in the Profile Details area instead of the initial letter placeholder.",
    expectedUiState: "After reload, the Profile Details section shows the uploaded image as the avatar rather than the 'CL' or initial-letter placeholder. The avatar is visible next to 'Edit Profile'.",
    endResult: "After reload, the uploaded avatar image is still displayed. The change survived the page reload.",
  },
  "checklist-account-auth-profile-settings-edit-profile": {
    roles: ["buyer"],
    startPage: "/user/profile",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/profile.",
      "Click 'Profile Details' to expand the section.",
      "Click 'Edit Profile'.",
      "Clear the 'Display name' field and type 'QA Edit Profile account-auth-profile-settings-edit-profile'.",
      "Clear the 'Bio' field and type 'Tester bio update for QA.'.",
      "Click 'Save changes'.",
      "Reload the page.",
      "Click 'Profile Details' to expand the section.",
    ],
    expectedBehaviour: "The save request succeeds and the new display name and bio are persisted to the user's profile record.",
    expectedUiState: "After reload, the Profile Details section shows the display name 'QA Edit Profile account-auth-profile-settings-edit-profile' and the bio 'Tester bio update for QA.' in the edit form.",
    endResult: "After reload, the updated display name and bio are still present in the Edit Profile form. The changes survived the page reload.",
  },
  "checklist-account-auth-profile-settings-hand-mode-persists-reload": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/settings.",
      "Click the 'Appearance' tab.",
      "Toggle the 'Left-hand mode' switch on (so it is enabled).",
      "Reload the page.",
      "Click the 'Appearance' tab.",
      "Sign out.",
      "Sign back in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/settings.",
      "Click the 'Appearance' tab.",
    ],
    expectedBehaviour: "The Left-hand mode preference is saved server-side. After a page reload, and after a sign-out/sign-in cycle, the setting remains on.",
    expectedUiState: "After reload: the 'Left-hand mode' switch on the Appearance tab is still in the on (enabled) position. After sign-out and sign back in: the 'Left-hand mode' switch is still on.",
    endResult: "After sign-out and sign back in, the 'Left-hand mode' switch is still enabled. The preference was persisted across sessions.",
  },
  "checklist-account-auth-profile-settings-hand-mode-toggle-exists": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/settings.",
      "Click the 'Appearance' tab.",
      "Toggle the 'Left-hand mode' switch.",
      "Open /user/profile.",
      "Scroll to the 'Left-hand mode' toggle below the 'Profile Details' section.",
      "Toggle the 'Left-hand mode' switch.",
    ],
    expectedBehaviour: "The 'Left-hand mode' toggle is present on both the Appearance tab of /user/settings and on /user/profile. Toggling it on either page takes effect immediately without a full page reload.",
    expectedUiState: "On /user/settings Appearance tab: a 'Left-hand mode' switch is visible under the Layout heading and toggles on/off. On /user/profile: a 'Left-hand mode' switch with description 'Move drawers, sidebars, and floating buttons to the left side of the screen' is visible and toggles on/off. No page reload occurs when toggling.",
    endResult: "The Left-hand mode switch is present in both locations and responds to interaction without a reload.",
  },
  "checklist-account-auth-profile-settings-notification-prefs": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/settings.",
      "Click the 'Notifications' tab.",
      "Toggle the 'Email' switch off (so it is unchecked).",
      "Toggle the 'Promotions' switch off (so it is unchecked).",
      "Click 'Save preferences'.",
      "Reload the page.",
      "Click the 'Notifications' tab.",
    ],
    expectedBehaviour: "The preference changes are persisted server-side. After reload, the saved state is loaded back and the two changed switches remain in their new positions.",
    expectedUiState: "After reload on the Notifications tab, the 'Email' switch is off (unchecked) and the 'Promotions' switch is off (unchecked). All other switches remain on.",
    endResult: "After reload, the 'Email' and 'Promotions' notification switches are still off. The preferences survived the page reload.",
  },
  "checklist-account-auth-profile-settings-own-public-profile-quick-links": {
    roles: ["buyer"],
    startPage: "/user",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user.",
      "Click the 'My Public Profile' tile in the quick-links grid.",
      "Note the URL and page content, then go back.",
      "Open /user.",
      "In the sidebar cross-dashboard navigation, click 'My Profile'.",
      "Note the URL — this is the edit-profile page, not the public profile; go back.",
      "Open /user/profile.",
      "Click 'Profile Details' to expand the section.",
      "Click 'View Public Profile'.",
      "Note the URL and page content.",
    ],
    expectedBehaviour: "The 'My Public Profile' tile on /user and the 'View Public Profile' link on /user/profile both navigate to the user's own public-facing profile page at /profile/user-yugi-muto. If the profile is set to Private the page still loads for the owner.",
    expectedUiState: "After clicking 'My Public Profile' tile: the browser navigates to /profile/user-yugi-muto showing the public profile page (not the edit page). After clicking 'View Public Profile' from /user/profile: same URL /profile/user-yugi-muto loads. The page shows public profile content, not an edit form.",
    endResult: "Both links correctly resolve to /profile/user-yugi-muto. The public profile page is accessible to the owner regardless of their visibility setting.",
  },
  "checklist-account-auth-profile-settings-password-change-reset-link": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/settings.",
      "Expand the 'Change Password' section.",
      "Click 'Update Password'.",
      "Open the inbox for rehan.sheikh@gmail.com.",
      "Find the password-reset email from LetItRip.",
      "Click the reset link in the email.",
      "Set a new password on the Firebase reset page.",
      "Sign out of LetItRip.",
      "Sign back in using rehan.sheikh@gmail.com and the new password.",
    ],
    expectedBehaviour: "Clicking 'Update Password' sends a Firebase password-reset email to rehan.sheikh@gmail.com. No password change occurs from the Settings page itself. Following the link in the email opens the Firebase reset flow. After setting a new password via that link, the user can sign in with the new password.",
    expectedUiState: "After clicking 'Update Password', a confirmation message appears on screen indicating the reset link was sent to rehan.sheikh@gmail.com. The Settings page does not present a new-password form. The reset email arrives in the inbox. After completing the reset flow the sign-in with the new password succeeds and the user lands on their account dashboard.",
    endResult: "Sign-in with the new password succeeds. The password change only took effect after the email link was followed — not from the Settings page alone.",
  },
  "checklist-account-auth-profile-settings-public-profile-toggle": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /user/profile.",
      "Click 'Profile Details' to expand the section.",
      "Note the current 'Profile visibility' value shown (Public or Private).",
      "Click 'Edit Profile'.",
      "Click the 'Visibility' section to expand it.",
      "Toggle the visibility so it is the opposite of the noted value.",
      "Click 'Save changes'.",
      "Reload the page.",
      "Click 'Profile Details' to expand the section.",
    ],
    expectedBehaviour: "The visibility preference is saved without a page reload. After reload the new visibility value is reflected in the Profile Details section.",
    expectedUiState: "After reload, the 'Profile visibility' line in Profile Details shows the newly saved value (e.g. 'Profile visibility: Private' if it was previously Public).",
    endResult: "After reload, the updated profile visibility value is still displayed. The toggle persisted across a reload.",
  },
  "checklist-account-auth-profile-settings-user-pages-signed-out-redirect": {
    roles: ["guest"],
    startPage: "/user/profile",
    steps: [
      "Open a private/incognito browser window (no active session).",
      "Open /user/profile.",
      "Wait 5 seconds.",
      "Open /user/orders.",
      "Wait 5 seconds.",
      "Open /user/bids.",
      "Wait 5 seconds.",
    ],
    expectedBehaviour: "Each of the three /user/* pages delivers a static shell with no user data, then redirects to the login page client-side. No uid, email, display name, order record, or store id from any real account is ever rendered on screen. The redirect completes; no spinner persists indefinitely.",
    expectedUiState: "For each URL: the page briefly shows the site chrome and a loading state, then navigates to the login page (URL changes to /login or similar). No account data (name, email, order details) is visible at any point. Note whether the loading flash before redirect feels acceptable.",
    endResult: "After all three navigations the browser is on the login page. No user data was exposed.",
  },
};
