/*
 * WHY: Authored six-part procedures for the account-auth/signup-login checklist page.
 * WHAT: 15 case(s), keyed by full checklist id.
 *
 * Generated by `node tester/scripts/merge-authored.mjs --page account-auth/signup-login`, then
 * reviewed by a human before merge — the review is the gate, not the generation.
 * Hand edits are safe and expected: re-running the merge for this page replaces
 * the file, so re-author only when you mean to discard them.
 *
 * @tag domain:tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed-data/authored/index.ts
 * @tag sideEffects:none
 */

import type { AuthoredCase } from "./_types";

export const authored: Record<string, AuthoredCase> = {
  "checklist-account-auth-signup-login-auth-email-links-single-use": {
    roles: ["guest"],
    startPage: "/auth/forgot-password",
    steps: [
      "Open /auth/forgot-password.",
      "Enter vivaan.kapoor@gmail.com in the 'Email address' field.",
      "Click 'Send reset link'.",
      "Open the inbox for vivaan.kapoor@gmail.com, find the reset email, and click the reset link.",
      "Complete the password reset by entering and confirming a new password, then submit.",
      "Copy the reset link URL from the email.",
      "Open the copied reset link URL in the browser a second time.",
      "Separately: register a new account with a real inbox, find the Firebase verification email, click the link once to verify, then click the same link a second time.",
    ],
    expectedBehaviour: "Clicking the reset link a second time does not succeed — Firebase has already consumed the one-time token. A clear, human-readable error is shown with a way to request a fresh link. The same applies to the verification link used twice: the second click shows a clear expired/used message, not a silent success.",
    expectedUiState: "On the second click of the reset link: a readable error message such as 'This link has already been used or has expired' appears, plus a prompt or button to request a new reset link. No blank page and no raw Firebase error code (e.g. 'auth/invalid-action-code') appears. The same readable message style appears on the second click of the verification link.",
    endResult: "No second password change was applied. No second verification event was recorded. The account state after the second link click is identical to what it was after the first successful click.",
  },
  "checklist-account-auth-signup-login-auth-emails-sender-identity-and-inbox": {
    roles: ["guest"],
    startPage: "/auth/register",
    steps: [
      "Open /auth/register.",
      "Register with a real Gmail address you can open — enter QA Sender Test in 'Full name', the Gmail address in 'Email address', TestPass123! as password and confirmation, tick terms, click 'Create account'.",
      "Open the Gmail inbox (check spam and promotions tabs) and locate the verification email.",
      "Note the From name and From address of the verification email.",
      "Open /auth/forgot-password.",
      "Enter the same Gmail address in 'Email address'.",
      "Click 'Send reset link'.",
      "Open the Gmail inbox again and locate the password-reset email.",
      "Note the From name and From address of the reset email.",
      "If you have a non-Gmail address available, repeat both flows (registration and forgot-password) for that address and check its inbox.",
    ],
    expectedBehaviour: "Both the verification email and the password-reset email arrive in the inbox (not spam) within a few minutes. The From name is 'LetItRip' (spelled exactly — not 'Letitrip' or 'LetiTrip'). The From address is the site's configured sender. The link inside each email opens on letitrip.in and completes the flow.",
    expectedUiState: "In the email client: the From field reads 'LetItRip' and the sender domain matches the site's configured address. The email lands in the inbox tab, not spam or promotions.",
    endResult: "Both flows complete: the verification link marks the account verified; the reset link allows a password change. Deliverability holds for both Gmail and non-Gmail if tested on both.",
  },
  "checklist-account-auth-signup-login-email-signup": {
    roles: ["guest"],
    startPage: "/auth/register",
    steps: [
      "Open /auth/register.",
      "Enter QA Signup Tester in the 'Full name' field.",
      "Enter qa-signup-test@mailnull.com in the 'Email address' field.",
      "Enter TestPass123! in the 'Password' field.",
      "Enter TestPass123! in the 'Confirm password' field.",
      "Tick the 'I accept the terms' checkbox.",
      "Click 'Create account'.",
    ],
    expectedBehaviour: "The account is created in Firebase Auth. A verification email is dispatched. The user is signed in and redirected away from /auth/register (typically to / or /user). No duplicate account is created on a second attempt with the same email.",
    expectedUiState: "After clicking 'Create account' the page redirects and the header reflects a logged-in state (profile avatar visible, no 'Sign in' link). A success toast or banner may appear.",
    endResult: "After reloading /user the account exists and the name 'QA Signup Tester' appears in the account section. The email qa-signup-test@mailnull.com is listed as the account email.",
  },
  "checklist-account-auth-signup-login-email-verify": {
    roles: ["guest"],
    startPage: "/auth/login",
    steps: [
      "Register a new account with a real inbox address (one you can open).",
      "Open the inbox and find the verification email from Firebase.",
      "Click the verification link in the email.",
      "After the link processes, open /auth/login and sign in with the new account's credentials.",
    ],
    expectedBehaviour: "Clicking the verification link marks the account as email-verified in Firebase Auth. The user can then sign in without any 'unverified email' warning. The verified state persists.",
    expectedUiState: "After clicking the link the page shows a confirmation (either on the linked page or on /user after signing in). No 'Your email is not verified' banner appears on /user after signing in.",
    endResult: "Reloading /user shows no email-verification warning. The account is fully accessible.",
  },
  "checklist-account-auth-signup-login-forgot-password-no-account-enumeration": {
    roles: ["guest"],
    startPage: "/auth/forgot-password",
    steps: [
      "Open /auth/forgot-password.",
      "Enter nobody-here-12345@example.com in the 'Email address' field.",
      "Click 'Send reset link'.",
    ],
    expectedBehaviour: "The client swallows Firebase's auth/user-not-found error and shows the same generic success message that a real address would produce. No error toast reveals that the address has no account. The response is indistinguishable from a real reset request.",
    expectedUiState: "A success message reads 'If an account exists for that email, a reset link is on its way.' (or equivalent generic wording). No error toast, no 'user not found' text, and no visual difference from the real-address flow.",
    endResult: "No reset email arrives for nobody-here-12345@example.com (confirming no account was created). The page shows only the generic success message.",
  },
  "checklist-account-auth-signup-login-google-link-confirmation-shown": {
    roles: ["buyer"],
    startPage: "/user",
    steps: [
      "Sign in as an account that already has a Google account linked (use an account where the 'Linked Accounts' section already shows Connected — or first link Google via /user/settings as described in the google-link-different-email case).",
      "Open /user.",
    ],
    expectedBehaviour: "The /user dashboard detects the Google account is connected and shows a green confirmation alert — 'Google account connected' with a Connected badge and the linked email. The blue 'Connect your Google account' prompt is absent.",
    expectedUiState: "A green alert region is visible on the /user dashboard containing 'Google account connected' text and a Connected badge with the linked Google email. The 'Connect Google' button inside a blue alert is NOT present.",
    endResult: "Reloading /user still shows the green connected confirmation. The blue 'Connect your Google account' alert does not reappear.",
    needsReview: true,
    reviewNote: "This case requires an account that already has Google linked. The current tester bot (claude-tester@letitrip.in) has Google unlinked. A pre-linked fixture account would make this reliably testable without a manual linking step first.",
  },
  "checklist-account-auth-signup-login-google-link-conflict-rejected": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Prepare two separate accounts: account A (vivaan.kapoor@gmail.com, user-seto-kaiba) and account B (rehan.sheikh@gmail.com, user-yugi-muto), each accessible with a password login.",
      "Link a Google account (email G) to account B via /user/settings > 'Linked Accounts' > 'Connect Google'.",
      "Sign out of account B.",
      "Sign in as account A (vivaan.kapoor@gmail.com).",
      "Open /user/settings.",
      "Click the 'Linked Accounts' accordion.",
      "Click 'Connect Google'.",
      "In the popup, select the same Google account G that is already linked to account B.",
      "Attempt to complete the OAuth flow.",
    ],
    expectedBehaviour: "The system detects the Google account G is already associated with a different account (B) and rejects the linking attempt with a clear error message. Account A is unchanged. No silent merge of accounts A and B occurs.",
    expectedUiState: "An error toast or inline message appears stating something like 'This Google account is already linked to another account'. The 'Linked Accounts' section for account A still shows 'Connect Google' (not Connected).",
    endResult: "After reloading /user/settings account A still has no Google account linked. Account B retains its Google link to G. No duplicate or merged account exists.",
    needsReview: true,
    reviewNote: "This case requires two real accounts and a Google account that can be linked to one of them. The steps as written are the correct procedure but depend on having appropriate test Google credentials.",
  },
  "checklist-account-auth-signup-login-google-link-different-email": {
    roles: ["buyer"],
    startPage: "/user/settings",
    steps: [
      "Sign in as vivaan.kapoor@gmail.com (user-seto-kaiba) with password.",
      "Open /user/settings.",
      "Click the 'Linked Accounts' accordion to expand it.",
      "Click 'Connect Google'.",
      "In the popup, select a Google account whose email is DIFFERENT from vivaan.kapoor@gmail.com.",
      "Complete the OAuth flow and return to the site.",
    ],
    expectedBehaviour: "The Google account with the different email is linked to the current account. No second account is created. The primary login email of the account remains vivaan.kapoor@gmail.com. The account can now sign in with either the password or Google.",
    expectedUiState: "The 'Linked Accounts' section on /user/settings shows 'Google' with a Connected state and displays the linked Google email (the different one). The 'Connect Google' button is replaced by a connected indicator.",
    endResult: "After reloading /user/settings the 'Linked Accounts' accordion shows Google as Connected with the linked email. The account's primary email is still vivaan.kapoor@gmail.com.",
  },
  "checklist-account-auth-signup-login-google-link-existing": {
    roles: ["guest"],
    startPage: "/auth/register",
    steps: [
      "Open /auth/register.",
      "Register a new account using the email address that also belongs to a Google account you control — enter that email in the 'Email address' field, a password of TestPass123!, confirm the password, enter any name, tick the terms checkbox, and click 'Create account'.",
      "After registration succeeds, click 'Log out' (from the sidebar or /user dashboard).",
      "Open /auth/login.",
      "Click 'Sign in with Google'.",
      "In the popup, select the Google account whose email matches the one just registered.",
      "Return to the site after the popup closes.",
    ],
    expectedBehaviour: "The system recognises the Google email matches the existing password account and logs into that same account rather than creating a second one. No explicit merge or linking step is required from the user. Settings > Account tab now shows Google as Connected.",
    expectedUiState: "After the popup closes the user is redirected to / or /user. The header shows the profile avatar for the original account (same name entered at registration). No 'create account' step is presented.",
    endResult: "Reloading /user/settings and opening the 'Linked Accounts' accordion shows 'Google' with a 'Connected' badge or the linked email displayed — not a 'Connect Google' button. Only one account exists for that email, not two.",
  },
  "checklist-account-auth-signup-login-google-oauth": {
    roles: ["guest"],
    startPage: "/auth/login",
    steps: [
      "Open /auth/login.",
      "Click 'Sign in with Google'.",
      "Complete the Google OAuth popup by selecting or signing into a Google account.",
      "Return to the site after the popup closes.",
    ],
    expectedBehaviour: "The OAuth popup opens, the user authenticates with Google, and the popup closes. The site creates or signs into the matching account and establishes a session.",
    expectedUiState: "The page redirects away from /auth/login. The header shows a logged-in profile avatar. No error toast appears.",
    endResult: "Reloading /user shows the user is still signed in. The account exists in the system linked to the Google email.",
  },
  "checklist-account-auth-signup-login-google-popup-blocked-fallback": {
    roles: ["guest"],
    startPage: "/auth/login",
    steps: [
      "Open /auth/login in a browser configured to block popups for this site.",
      "Click 'Sign in with Google'.",
      "If the browser shows a blocked-popup notification, do not unblock it — allow the fallback to activate.",
      "Wait for the site's fallback mechanism (RTDB signal / postMessage) to handle authentication.",
      "Wait up to 30 seconds for the site to respond after the popup was blocked.",
    ],
    expectedBehaviour: "When the popup is blocked, the site detects the block and either opens Google sign-in in a redirect flow or uses the RTDB signal + postMessage fallback. Sign-in completes and a session is established without the user needing to manually unblock popups.",
    expectedUiState: "After the fallback completes the page redirects or updates to show a logged-in state — profile avatar visible in the header, no error toast about the popup.",
    endResult: "Reloading /user shows the user is signed in. The account exists and is linked to the Google email used.",
    needsReview: true,
    reviewNote: "This is a browser-level test requiring popup blocking to be configured. The fallback mechanism (RTDB signal + postMessage) is described in the case label but the exact UI feedback during the fallback is not visible from the current snapshot — the steps as written describe correct tester procedure.",
  },
  "checklist-account-auth-signup-login-login": {
    roles: ["guest"],
    startPage: "/auth/login",
    steps: [
      "Open /auth/login.",
      "Enter vivaan.kapoor@gmail.com in the 'Email address' field.",
      "Enter the password for user-seto-kaiba in the 'Password' field.",
      "Click 'Sign in'.",
    ],
    expectedBehaviour: "Firebase Auth validates the credentials, a session cookie is set, and the user is redirected away from /auth/login.",
    expectedUiState: "The page redirects to / or /user. The header shows a logged-in profile avatar for vivaan.kapoor@gmail.com. No error toast appears.",
    endResult: "Reloading /user shows the user is still signed in as vivaan.kapoor@gmail.com (user-seto-kaiba).",
    needsReview: true,
    reviewNote: "The password for vivaan.kapoor@gmail.com (user-seto-kaiba) is not in the fixture reference. A tester will need the credential from the seed data or a password reset to run this case.",
  },
  "checklist-account-auth-signup-login-logout": {
    roles: ["buyer"],
    startPage: "/auth/login",
    steps: [
      "Sign in as vivaan.kapoor@gmail.com (user-seto-kaiba).",
      "Open /user.",
      "Click 'Log out' in the sidebar.",
    ],
    expectedBehaviour: "The server session is cleared, the Firebase client session is revoked, and the user is redirected to / or /auth/login. Navigating to /user or any protected page should no longer grant access.",
    expectedUiState: "After clicking 'Log out' the page redirects. The header shows no profile avatar — instead showing a guest state (no 'Profile' link, or a 'Sign in' link visible). The /user page redirects to /auth/login when visited as a guest.",
    endResult: "After reload, navigating to /user redirects to /auth/login. The browser holds no active session for vivaan.kapoor@gmail.com.",
  },
  "checklist-account-auth-signup-login-password-reset": {
    roles: ["guest"],
    startPage: "/auth/login",
    steps: [
      "Open /auth/login.",
      "Click 'Forgot password?'.",
      "On /auth/forgot-password, enter vivaan.kapoor@gmail.com in the 'Email address' field.",
      "Click 'Send reset link'.",
      "Open the inbox for vivaan.kapoor@gmail.com and click the password-reset link in the email.",
      "On the reset page, enter a new password and confirm it.",
      "Submit the new password.",
      "Open /auth/login.",
      "Enter vivaan.kapoor@gmail.com and the new password.",
      "Click 'Sign in'.",
    ],
    expectedBehaviour: "Firebase sends a password-reset email. Clicking the link opens a form to set a new password. After setting the new password the account's credentials are updated in Firebase Auth. Sign-in with the new password succeeds.",
    expectedUiState: "After submitting 'Send reset link', the page or a toast shows 'If an account exists for that email, a reset link is on its way.' After completing the reset and signing in, the header shows the logged-in avatar for vivaan.kapoor@gmail.com.",
    endResult: "Reloading /user shows the user is signed in as vivaan.kapoor@gmail.com. The old password no longer works; the new password does.",
  },
  "checklist-account-auth-signup-login-signup-verification-email-arrives": {
    roles: ["guest"],
    startPage: "/auth/register",
    steps: [
      "Open /auth/register.",
      "Enter QA Verify Tester in the 'Full name' field.",
      "Enter a real inbox address you can open (e.g. a Gmail address) in the 'Email address' field.",
      "Enter TestPass123! in the 'Password' field.",
      "Enter TestPass123! in the 'Confirm password' field.",
      "Tick the 'I accept the terms' checkbox.",
      "Click 'Create account'.",
      "Open the inbox (check spam too) for the address entered.",
    ],
    expectedBehaviour: "Firebase Auth sends a verification email to the address used during registration. The email arrives within a few minutes. Its link leads back to the live site and, when clicked, marks the account as verified. The sender is Firebase's configured sender — not a LetItRip branded Resend template — which is expected.",
    expectedUiState: "After clicking 'Create account' a success state appears (redirect to / or /user). In the inbox an email appears from Firebase's sender with a verification link. The link destination is on the live letitrip.in domain.",
    endResult: "After clicking the verification link the account is marked as email-verified. Signing in and reloading /user shows no 'email not verified' warning.",
  },
};
