/*
 * WHY: Authored six-part procedures for the buying/browsing-search checklist page.
 * WHAT: 42 case(s), keyed by full checklist id.
 *
 * Written by hand, case by case, against the label each one states. There is no
 * generator: the authoring scripts were deleted once it was clear they were
 * scaffolding around work that is simply writing.
 *
 * @tag domain:tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed-data/authored/index.ts
 * @tag sideEffects:none
 */

import type { AuthoredCase } from "./_types";

export const authored: Record<string, AuthoredCase> = {
  "checklist-buying-browsing-search-art-stickers-default-not-empty": {
    roles: ["guest"],
    startPage: "/art",
    steps: [
      "Open /art.",
    ],
    expectedBehaviour: "The /art page shows real Art and Sticker items on the Available tab without any filter or toggle needed. No Firestore error toast appears.",
    expectedUiState: "At least one product card is visible. 'No products found' is NOT shown. No toast message mentions a missing index or a Firestore error.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-art-stickers-show-sold-adds-not-reveals": {
    roles: ["guest"],
    startPage: "/art",
    steps: [
      "Open /art.",
      "Count the cards visible on the 'Available' tab.",
      "Click the 'Sold' tab.",
      "Count the cards on that tab.",
      "Click back to the 'Available' tab.",
      "Click 'Filters', tick 'Stickers', click 'Apply'.",
      "Note the count on 'Available'.",
      "Click the 'Sold' tab and note the count.",
    ],
    expectedBehaviour: "The Available tab shows real items without the Sold tab being required. The Sold tab adds sold-out items on top — it is not the only place to see any results.",
    expectedUiState: "Available tab: shows at least one card before any tab-switching. Sold tab: shows 'Beyblade Metal Fight Sticker Sheet (Sold Out)' (sticker-beyblade-metal-fight-sold-out) and/or 'Dragoon Galaxy Turbo — Fan Art Print (Sold Out)' (art-dragoon-galaxy-turbo-print-sold-out). Total cards across both tabs is greater than on Available alone.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-art-stickers-type-chips-narrow": {
    roles: ["guest"],
    startPage: "/art",
    steps: [
      "Open /art.",
      "Click 'Filters'.",
      "Read every checkbox under 'Listing type'.",
      "Tick 'Art' only and click 'Apply'.",
      "Click 'Filters', untick 'Art', tick 'Stickers', click 'Apply'.",
      "Click 'Filters', untick 'Stickers', click 'Apply'.",
    ],
    expectedBehaviour: "The Listing type section on /art shows exactly two checkboxes: Art and Stickers. Each alone narrows the grid to that type and returns at least one result. With neither ticked the grid shows both types.",
    expectedUiState: "Drawer: exactly two Listing type checkboxes — Art and Stickers. Art only: grid shows Art cards only, at least one card present. Stickers only: grid shows Sticker cards only, at least one card present. Neither ticked: grid shows Art and Sticker cards mixed.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-auctions-show-ended-off-shows-live": {
    roles: ["guest"],
    startPage: "/auctions",
    steps: [
      "Open /auctions.",
      "Read the availability tab bar and the grid.",
    ],
    expectedBehaviour: "Live auctions appear on the Available tab, which is selected on arrival. The page is not empty. This case used to start on /products with the Auctions chip ticked; auctions now live only on their own page.",
    expectedUiState: "At least one live auction card is visible (e.g. 'Beyblade Burst B-100 Cho-Z Achilles' or 'Metal Fight Beyblade BB-99 Lightning L-Drago'). The middle tab reads 'Ended' and is NOT selected. The grid is not empty and no error toast appears.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-auctions-show-ended-with-nondefault-sort": {
    roles: ["buyer"],
    startPage: "/auctions",
    steps: [
      "Sign in as a buyer.",
      "Open /auctions.",
      "Open the 'Sort by' dropdown and select 'Highest Current Bid'.",
      "Read the order of the current-bid figures on the cards.",
    ],
    expectedBehaviour: "Sorting by 'Highest Current Bid' on the Available tab still returns only live auctions, ordered by current bid descending, and the grid is not empty. The role is BUYER, not guest: 'Highest Current Bid' is a money sort and is not offered to signed-out visitors, because ordering by bid ranks every hidden amount on the page.",
    expectedUiState: "The grid shows live auction cards whose current-bid figures descend from top-left to bottom-right. No ended auction cards are visible. No 'No products found' message appears.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-browse-categories": {
    roles: ["guest"],
    startPage: "/categories",
    steps: [
      "Open /categories.",
      "Click the 'Beyblade Burst' card.",
    ],
    expectedBehaviour: "The browser navigates to /categories/category-beyblade-burst and returns a listing of products in that category.",
    expectedUiState: "The heading reads 'Beyblade Burst'. At least one product card is visible. The breadcrumb shows 'Home / Categories / Beyblade Burst'.",
    endResult: "Nothing is persisted. Reloading /categories/category-beyblade-burst shows the same category listing.",
  },
  "checklist-buying-browsing-search-card-shows-seller-name": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products in grid view.",
      "Scan the visible cards for the 'by …' line under each title.",
      "Click 'List view' in the toolbar to switch to list mode.",
      "Scan the same cards in list view.",
      "Open /auctions and scan the auction cards for a 'by …' line.",
      "Open /pre-orders and scan the pre-order cards.",
      "Open /prize-draws and scan the prize-draw cards.",
    ],
    expectedBehaviour: "Every listing card on every page carries a 'by <store name>' line. The name is a readable store name, never a raw slug.",
    expectedUiState: "Each card shows a line such as 'by Beyblade Arena' or 'by LetItRip Official'. No card shows a raw slug such as 'by store-beyblade-arena'.",
    endResult: "Nothing is persisted. The store-name line is purely display data.",
  },
  "checklist-buying-browsing-search-compare-custom-fields": {
    roles: ["buyer"],
    startPage: "/products",
    steps: [
      "Sign in as vivaan.kapoor@gmail.com.",
      "Open /products.",
      "Tick the checkbox on 'Beyblade Burst B-97 Spryzen S2 (Video Demo, Wikimedia)' (product-beyblade-burst-spryzen-video-demo).",
      "Tick the checkbox on 'Metal Fight Beyblade BB-118 Dark Bull (Video Demo, YouTube)' (product-beyblade-metal-dark-bull-video-demo).",
      "Click the 'Compare' button in the bulk-action bar.",
    ],
    expectedBehaviour: "A compare view opens that shows both items side by side. Beyond the standard rows (image, price, condition, brand, category, store), any custom spec fields defined on these products (e.g. dimensions, material, edition) appear as additional comparison rows.",
    expectedUiState: "The compare table has columns for each selected product. Standard rows (Price, Condition, Brand, Category, Store) are present. At least one additional custom-spec row is present — it is not limited to only those six standard fields.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-compare-double-row-arrows": {
    roles: ["guest"],
    startPage: "/",
    steps: [
      "Open /.",
      "Scroll to the 'Live Auctions' section.",
    ],
    expectedBehaviour: "The scroll arrows for a double-row section span the full height of the double row.",
    expectedUiState: "The left arrow and right arrow on the 'Live Auctions' strip are tall slivers that run the full combined height of both rows — not small circular buttons positioned at the vertical centre.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-default-listing-not-empty": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products with no filters applied.",
      "Open /auctions with no filters applied.",
      "Open /pre-orders with no filters applied.",
      "Open /art with no filters applied.",
      "Open /prize-draws with no filters applied.",
    ],
    expectedBehaviour: "Every listing page returns real items without any filter or toggle being needed. No page silently returns zero results due to a broken Firestore index.",
    expectedUiState: "Each page shows at least one product card. None of the five pages shows 'No products found' as the default state, and no toast about a missing Firestore index appears.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-filter-drawer-combines-correctly": {
    roles: ["buyer"],
    startPage: "/products",
    steps: [
      "Sign in as a buyer — the Price Range facet is hidden from signed-out visitors.",
      "Open /products.",
      "Note the initial result count.",
      "Click 'Filters'.",
      "Set Price Range minimum to 500 and maximum to 1500.",
      "Tick 'Takara-Tomy' under Brand.",
      "Tick 'Beyblade X' under Category.",
      "Tick 'New' under Condition.",
      "Click 'Apply'.",
      "Note the new result count.",
      "Click 'Filters' and click 'Reset all', then 'Apply'.",
      "Note the result count.",
    ],
    inputs: { priceMin: 500, priceMax: 1500, brand: "Takara-Tomy", category: "Beyblade X", condition: "New" },
    expectedBehaviour: "All four filters apply simultaneously and narrow the results. Every remaining card satisfies all four constraints. Reset all clears all filters and restores the full result count.",
    expectedUiState: "After Apply: count is lower than the initial count; every card shows Takara-Tomy brand, Beyblade X category, New condition, and price between ₹500 and ₹1,500. After Reset all and Apply: count matches the original initial count and mixed types/brands reappear.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-filter-drawer-facets-actually-filter": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Note the result count.",
      "Click 'Filters'.",
      "Expand 'Features' and select one feature option if any are listed.",
      "Click 'Apply'.",
      "Note the new result count and compare to the original.",
      "Click 'Filters' and click 'Reset all', then 'Apply'.",
      "Note the result count returns to the original.",
    ],
    expectedBehaviour: "Selecting a Features value actually narrows the result set (count drops). The grid content changes to match the filter, not just the badge number.",
    expectedUiState: "After selecting a Feature and applying: result count is lower than original, Filters badge increments, and the grid shows only items matching that feature. After Reset all: result count returns to the original count.",
    endResult: "Nothing is persisted to the server.",
    needsReview: true,
    reviewNote: "The 'Tags' and 'Sublisting Type' sections described in the case label were not visible in the drawer during observation — only 'Features' was present. Steps use Features only. Revisit if Tags/Sublisting Type appear on the live site.",
  },
  "checklist-buying-browsing-search-filter-drawer-flips-hand-mode": {
    roles: ["buyer"],
    startPage: "/products",
    steps: [
      "Sign in as vivaan.kapoor@gmail.com.",
      "Open /user/profile and enable 'Left-hand mode' if it is not already enabled.",
      "Open /products.",
      "Click 'Filters'.",
    ],
    expectedBehaviour: "With Left-hand mode ON, the filter drawer opens from the left edge of the screen instead of the right edge.",
    expectedUiState: "The Filters drawer slides in from the left side of the viewport. The drawer heading 'Filters' and filter sections are anchored to the left.",
    endResult: "The Left-hand mode preference persists in the user's profile across sessions.",
  },
  "checklist-buying-browsing-search-filters": {
    roles: ["buyer"],
    startPage: "/products",
    steps: [
      "Sign in as a buyer — the Price Range facet is hidden from signed-out visitors.",
      "Open /products.",
      "Note the result count shown in pagination.",
      "Click 'Filters'.",
      "Under 'Price Range', set minimum to 500 and maximum to 1000.",
      "Under 'Brand', tick 'Takara-Tomy'.",
      "Under 'Condition', tick 'New'.",
      "Click 'Apply'.",
    ],
    expectedBehaviour: "The server re-queries with the price, brand, and condition constraints applied together. The result count drops below the original count.",
    expectedUiState: "Every visible card is priced between ₹500 and ₹1,000, shows the 'Takara-Tomy' brand badge, and is listed as New. The Filters button shows a badge count of 3 or more.",
    endResult: "Nothing is persisted on the server. Reloading the filtered URL shows the same filtered grid.",
  },
  "checklist-buying-browsing-search-free-shipping-toggle-actually-filters": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Note the result count in the pagination bar.",
      "Click 'Filters'.",
      "Toggle 'Free shipping only' ON under the Shipping section.",
      "Click 'Apply'.",
      "Note the new result count.",
      "Scan the visible cards.",
    ],
    expectedBehaviour: "Turning the free shipping toggle on reduces the result count. Every remaining card genuinely offers free shipping.",
    expectedUiState: "The result count is lower than before the toggle. The Filters badge increments. Each visible card shows a free-shipping indicator. No card with a shipping fee is visible.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-grid-follows-sidebar-not-viewport": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products at 1440px wide.",
      "Count the number of cards per row before the sidebar is open.",
      "Click 'Filters' to open the desktop filter sidebar.",
      "Count the number of cards per row while the sidebar is open.",
      "Close the sidebar by clicking 'Filters' again or pressing Escape.",
      "Count the cards per row again.",
    ],
    expectedBehaviour: "Opening the sidebar reduces the card count per row by one because the grid container narrows. Each remaining card stays approximately the same width — the grid is not recalculated against the viewport.",
    expectedUiState: "With sidebar open: one fewer column than without the sidebar. Card widths are visually similar before and after. Closing the sidebar restores the previous column count.",
    endResult: "Nothing is persisted. Layout is purely CSS.",
  },
  "checklist-buying-browsing-search-grid-one-card-per-row-on-phone": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Resize the browser window to 375px wide.",
      "Count how many cards appear side-by-side in the first row.",
      "Resize to 768px wide and count again.",
      "Resize to 1024px wide and count again.",
      "Resize to 1440px wide and count again.",
      "Open /stores and repeat the same four width checks.",
      "Open /blog and repeat the same four width checks.",
    ],
    expectedBehaviour: "At 375px exactly one card fills the row. At 768px two cards share the row. At 1024px and 1440px three or four cards share the row. Cards always fill the available width with no gap on the right.",
    expectedUiState: "375px: 1 card per row, card fills the full content width. 768px: 2 cards per row. 1024px: 3 cards per row. 1440px: 3–4 cards per row. No half-width orphan cards at 375px.",
    endResult: "Nothing is persisted. Layout is purely CSS.",
  },
  "checklist-buying-browsing-search-grid-short-last-row-not-stretched": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products at 1440px wide (3 cards per row at desktop).",
      "Click 'Filters', tick 'Standard' under Listing type, and click 'Apply'.",
      "If the result count is a multiple of 3, additionally tick 'Takara-Tomy' under Brand and click 'Apply' again — repeat until the last row is short (1 or 2 cards, not a full row of 3).",
      "Scroll to the last row of cards.",
    ],
    expectedBehaviour: "The short last row is left-aligned. The lone card is exactly the same width as the cards in the rows above it, with empty space to its right.",
    expectedUiState: "The last-row card(s) have the same width as full-row cards. The remaining column slots are empty whitespace — no card stretches to fill the full row width.",
    endResult: "Nothing is persisted. Layout is purely CSS.",
  },
  "checklist-buying-browsing-search-homepage-event-raffles-section": {
    roles: ["guest"],
    startPage: "/",
    steps: [
      "Open /.",
      "Scroll down looking for a 'Raffles' or 'Spin Wheels' strip.",
      "Open /events in a new tab.",
      "Note which events have a raffle or spin-wheel type and are currently active.",
    ],
    expectedBehaviour: "If any raffle or spin-wheel event is active on /events, the homepage shows a 'Raffles & Spin Wheels' strip containing those events. The strip is absent only when genuinely no raffle event is active.",
    expectedUiState: "The homepage shows a 'Raffles & Spin Wheels' heading with at least one event card beneath it (e.g. 'Daily Beyblade Pull! Spin for a Prize'). The same event must also appear on /events.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-homepage-prize-draws-section": {
    roles: ["guest"],
    startPage: "/",
    steps: [
      "Open /.",
      "Scroll the full homepage from top to bottom.",
    ],
    expectedBehaviour: "Every homepage strip either renders cards or is cleanly absent. No strip is replaced by an error message while the rest of the page loads normally.",
    expectedUiState: "A 'Prize Draws' heading is visible with at least one prize-draw card beneath it (e.g. 'Beyblade Original Vintage Vault — Prize Draw'). No strip shows 'Something went wrong' or a blank gap where cards should be.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-listing-no-missing-message": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open browser DevTools (F12) and go to the Console tab.",
      "Open /products.",
      "Wait for the page to fully load.",
      "Read the console output.",
    ],
    expectedBehaviour: "No 'MISSING_MESSAGE' error is logged. All translation keys resolve to readable labels.",
    expectedUiState: "The Console tab shows no entry matching 'MISSING_MESSAGE: …'. Every visible label on the page is readable text, not a raw key string.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-listing-toggles-persist-across-pagination": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click the 'Sold & Ended' tab.",
      "Click 'Page 2' in the pagination bar.",
      "Read the active tab and the URL.",
    ],
    expectedBehaviour: "Navigating to page 2 while the 'Sold & Ended' tab is active keeps the tab active. Page 2 shows sold and ended items, not available items.",
    expectedUiState: "The 'Sold & Ended' tab remains highlighted after clicking Page 2. The URL contains both the availability and page parameters. The grid on page 2 shows sold/ended items, not available ones.",
    endResult: "Nothing is persisted to the server. State is URL-encoded.",
  },
  "checklist-buying-browsing-search-listing-toolbar-collapsed-on-mobile": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Resize the browser to 375px wide.",
      "Open /products.",
      "Click the 'Show Toolbar' strip.",
      "Open /auctions.",
      "Navigate back to /products.",
      "Resize to 1440px wide.",
      "Open /products.",
    ],
    expectedBehaviour: "At 375px the toolbar opens collapsed to a single strip. Tapping it expands the full search/filter/sort toolbar. After navigating away and back the toolbar stays expanded because the user chose to expand it. At 1440px the toolbar is open by default.",
    expectedUiState: "375px initial: a single 'Show Toolbar' strip is visible; no search box or filter chips are visible above it. After tap: a search field, Filters button, Sort control, and view toggles are all visible. After navigating away and back: toolbar is still expanded. 1440px: toolbar is fully visible without tapping.",
    endResult: "The toolbar expanded/collapsed preference is preserved across navigation within the session but is not persisted to the server.",
  },
  "checklist-buying-browsing-search-listing-toolbar-forced-open-on-selection": {
    roles: ["seller"],
    startPage: "/store/products",
    steps: [
      "Resize the browser to 375px wide.",
      "Open /store/products (the seller's own product listing).",
      "Collapse the toolbar by clicking 'Hide Toolbar' if it is open.",
      "Tick the checkbox on one product card to select it.",
    ],
    expectedBehaviour: "Selecting a row while the toolbar is collapsed forces the toolbar to open so the bulk-action bar becomes visible.",
    expectedUiState: "The toolbar is visible after the checkbox is ticked. The bulk-action bar (with actions such as 'Delete' or 'Publish') is visible and not cut off.",
    endResult: "Nothing is persisted. The forced-open state is UI-only.",
  },
  "checklist-buying-browsing-search-pagination": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Note the current page indicator in the pagination bar (Page 1).",
      "Click the 'Page 2' button in the pagination bar.",
      "Wait for the grid to load.",
      "Click the 'Next page' (›) button.",
      "Click the 'Previous page' (‹) button.",
    ],
    expectedBehaviour: "Each pagination action loads the correct page of results. The URL updates to reflect the page number. The grid is not empty on any valid page.",
    expectedUiState: "After clicking Page 2: the pagination bar highlights Page 2 and the URL contains 'page=2'. After Next: the next page loads with different cards. After Previous: the previous page loads. No page shows 'No products found' unless the total results genuinely fit on one page.",
    endResult: "Nothing is persisted to the server. The page parameter is URL state.",
  },
  "checklist-buying-browsing-search-every-listing-type-reachable-from-nav-or-products": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products and read the main navigation bar.",
      "Click 'Auctions' in the nav and confirm at least one auction card is shown.",
      "Click 'Pre-Orders' in the nav and confirm at least one pre-order card is shown.",
      "Click 'Prize Draws' in the nav and confirm at least one prize-draw card is shown.",
      "Click 'Art & Stickers' in the nav and confirm at least one art or sticker card is shown.",
      "Return to /products, click 'Filters', tick 'Classifieds', click 'Apply', and read the grid.",
      "Click 'Filters', untick 'Classifieds', tick 'Digital Codes', click 'Apply', and read the grid.",
      "Click 'Filters', untick 'Digital Codes', tick 'Live Items', click 'Apply', and read the grid.",
    ],
    expectedBehaviour: "All nine listing types are reachable without typing a URL. Five reach their own page from the main nav; the remaining four — Standard, Classifieds, Digital Codes, Live Items — are reached through the /products Listing type filter, because they have no nav entry of their own.",
    expectedUiState: "Each nav click lands on the matching page with at least one real card: /auctions, /pre-orders, /prize-draws, /art. Each /products filter selection narrows the grid to that type with at least one card and no 'No products found' state — Classifieds shows 'Classified' badges, Digital Codes shows 'Digital Code' badges, Live Items shows 'Live Item' badges.",
    endResult: "Nothing is persisted to the server. A type that can be reached from neither the nav nor the /products filter is the regression this case exists for.",
  },
  "checklist-buying-browsing-search-product-filter-status-labels": {
    roles: ["admin"],
    startPage: "/products",
    steps: [
      "Sign in as admin@letitrip.in.",
      "Open /products.",
      "Click 'Filters'.",
      "Scroll to or expand the 'Status' section in the drawer.",
      "Read every option label under Status.",
    ],
    expectedBehaviour: "Every Status option displays a readable word — Published, Draft, In Review, or Archived — never a raw i18n key.",
    expectedUiState: "The Status section lists labels such as 'Published', 'Draft', 'In Review', 'Archived'. No label reads as a key like 'filters.statusInReview' or 'status.draft'.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-product-type-chip-dedicated-page-link": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click 'Filters'.",
      "Tick only 'Classifieds' under Listing type.",
      "Read the contents of the drawer below the Listing type checkboxes, without pressing Apply.",
      "Click the 'Full Classifieds filters →' link.",
      "Navigate back to /products.",
      "Click 'Filters', untick 'Classifieds', tick only 'Digital Codes', and read for a similar link.",
      "Navigate back to /products.",
      "Click 'Filters', tick 'Classifieds' and 'Digital Codes' both, and read for a link.",
      "Navigate back to /products.",
      "Click 'Filters', untick all, and read for a link.",
      "Click 'Filters', tick only 'Standard', and read for a link.",
    ],
    expectedBehaviour: "When exactly one type that has its own browse page is ticked, a 'Full <type> filters →' link appears in the drawer below the Listing type section (before pressing Apply). The link navigates to that type's dedicated page, which carries facets this generic page cannot. With two types ticked or none ticked, no link appears. Standard is the exception: its 'dedicated page' IS /products, so offering a link would point the page at itself.",
    expectedUiState: "Classifieds only: 'Full Classifieds filters →' link is visible; clicking it lands on /classified. Digital Codes only: 'Full Digital Codes filters →' link is visible. Both ticked: no link visible. None ticked: no link visible. Standard only: NO link is visible — in particular no 'Full Products filters →' link pointing back at /products.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-product-type-chip-drives-sort-options": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Sign in as a buyer (price sorts are hidden from signed-out visitors).",
      "Open /auctions and open the 'Sort by' dropdown; read the available options.",
      "Open /pre-orders and open the 'Sort by' dropdown; read the available options.",
      "Open /products and open the 'Sort by' dropdown; read the available options.",
    ],
    expectedBehaviour: "Each listing type offers the sorts that make sense for it, and only those. An auction sorts by how soon it ends; a pre-order by when it is delivered; the general catalogue by neither, because neither field means anything for a standard product. This used to be exercised by ticking Auctions and Pre-Orders on /products; those types now live only on their own pages, so the contrast is read across pages instead.",
    expectedUiState: "/auctions: the Sort dropdown includes 'Ending Soon'. /pre-orders: it includes 'Earliest Delivery' and does NOT include 'Ending Soon'. /products: it includes neither 'Ending Soon' nor 'Earliest Delivery', offering generic options such as 'Newest First' and the two price sorts.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-product-type-chip-sort-resets-no-empty-page": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products?sort=auctionEndDate:asc directly in the address bar — an auction-only sort that the general catalogue cannot satisfy.",
      "Read the 'Sort by' dropdown and the grid.",
      "Open /products?listingType=auction directly in the address bar.",
      "Read the URL the browser settles on and the page heading.",
    ],
    expectedBehaviour: "A sort or a listing type that /products does not offer must degrade visibly, never silently. An unsupported sort falls back to the default rather than running a query Firestore rejects, which would surface as a bare empty grid with no error. A URL naming only out-of-catalogue types redirects to the page that owns them, rather than quietly showing the whole general catalogue as though the filter had been honoured.",
    expectedUiState: "First URL: the Sort dropdown reads 'Newest First', the grid shows product cards, and there is no 'No products found' state and no error. Second URL: the browser lands on /auctions and the page heading reads Auctions — it does NOT stay on /products showing unfiltered results.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-product-type-chips-cover-all-types": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click 'Filters'.",
      "Count every checkbox under the 'Listing type' heading.",
      "Read each checkbox label.",
    ],
    expectedBehaviour: "Exactly four listing-type checkboxes are present: Standard, Classifieds, Digital Codes, Live Items. Those are the four types with no dedicated entry in the main nav, so /products is their only discovery path. Auctions, Pre-Orders, Prize Draws, Art and Stickers are NOT offered here — each owns a dedicated page reachable from the main nav. No checkbox labelled 'Bundles' is present; a bundle is a category, not a listing type.",
    expectedUiState: "BEFORE: nine checkboxes, including Auctions, Pre-Orders, Prize Draws, Art and Stickers. AFTER: the Listing type section shows exactly four — Standard, Classifieds, Digital Codes, Live Items. No 'Auctions', 'Pre-Orders', 'Prize Draws', 'Art', 'Stickers' or 'Bundles' checkbox is present.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-product-type-chips-multi-select": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click 'Filters'.",
      "Tick 'Classifieds'.",
      "Tick 'Digital Codes' without unticking 'Classifieds'.",
      "Click 'Apply'.",
      "Click 'Filters' again to reopen the drawer.",
      "Read which boxes are ticked.",
      "Click 'Close'.",
      "Untick both 'Classifieds' and 'Digital Codes' in the drawer.",
      "Click 'Apply'.",
    ],
    expectedBehaviour: "Both checkboxes remain ticked after Apply. The grid shows a mix of Classified and Digital Code cards. After unticking both and applying, the grid returns to showing every type the general catalogue spans.",
    expectedUiState: "After first Apply: the Filters badge count is 2; the grid shows cards labelled 'Classified' and 'Digital Code'. Reopening drawer: both Classifieds and Digital Codes are ticked. After second Apply with none ticked: badge count returns to 0 and cards of multiple types reappear.",
    endResult: "Nothing is persisted to the server. Filter state is URL state.",
  },
  "checklist-buying-browsing-search-product-type-chips-none-means-all": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click 'Filters' and confirm no 'Listing type' boxes are ticked.",
      "Click 'Close'.",
      "Scan the badges on the first page of cards.",
    ],
    expectedBehaviour: "With no Listing type filter applied the grid shows every type the GENERAL CATALOGUE spans — not every type in the system. At least two different type badges are visible on the first page, and none of them is a type that owns a dedicated nav page.",
    expectedUiState: "At least two different type badges are visible on page 1, drawn only from Classified / Digital Code / Live Item / no-badge (Standard) — for example a 'Classified' card alongside a 'Digital Code' card. NO 'Auction', 'Pre-Order', 'Prize Draw', 'Art Print' or 'Sticker Sheet' badge appears.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-product-type-filter-counts-in-badge": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click 'Filters'.",
      "Tick 'Classifieds'.",
      "Click 'Apply'.",
      "Note the new number on the Filters badge.",
      "Click 'Filters' again.",
      "Click 'Reset all'.",
      "Click 'Apply'.",
      "Note the Filters badge number and the grid content.",
    ],
    expectedBehaviour: "Ticking one Listing type box and pressing Apply increases the Filters badge by 1. 'Reset all' unticks every type box and restores the badge to 0, and the grid repopulates with every type the general catalogue spans.",
    expectedUiState: "After ticking Classifieds and applying: badge shows 1 (or higher if defaults add to it). After Reset all and Apply: badge shows 0 and the grid contains mixed listing types.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-product-type-filter-lives-in-drawer": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Scan the area between the availability tabs and the product grid for any row of pill chips labelled Standard, Auctions, Pre-Orders, etc.",
      "Click 'Filters' to open the drawer.",
      "Scroll to the top of the drawer and look for a 'Listing type' section.",
    ],
    expectedBehaviour: "No TYPE chip row exists between the tabs and the grid. The listing-type filter is exclusively inside the Filters drawer, under a 'Listing type' heading.",
    expectedUiState: "The area between the 'Available / Sold & Ended / All' tabs and the product grid contains no pill chips for listing type. Inside the Filters drawer a 'Listing type' section appears at the top with checkboxes.",
    endResult: "Nothing is persisted.",
  },
  "checklist-buying-browsing-search-product-type-pending-until-apply": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products with no filters applied.",
      "Note the types of cards visible in the grid.",
      "Click 'Filters'.",
      "Tick 'Classifieds' and watch the grid behind the open drawer.",
      "Click 'Apply'.",
      "Note the grid now.",
      "Click 'Filters' again.",
      "Tick 'Live Items'.",
      "Click the X (Close) button on the drawer — do not click Apply.",
      "Click 'Filters' again to reopen and read which boxes are ticked.",
    ],
    expectedBehaviour: "Ticking a box does not change the grid until Apply is pressed. Closing with X discards pending changes — the grid and the ticked state both revert to what was applied before.",
    expectedUiState: "While drawer is open with Classifieds ticked: grid behind the drawer still shows mixed types. After Apply: grid shows only Classified cards. After ticking Live Items and closing with X: grid still shows only Classified cards (Live Items was discarded). Reopening drawer: only Classifieds is ticked; Live Items is unticked.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-product-type-selection-survives-reload": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click 'Filters', tick 'Classifieds' and 'Live Items', click 'Apply'.",
      "Copy the current URL from the address bar.",
      "Open the copied URL in a new browser tab.",
      "Click 'Filters' in the new tab and read which boxes are ticked.",
      "Close the new tab.",
      "Press the browser Back button in the original tab.",
      "Click 'Filters' in the original tab and read which boxes are ticked.",
    ],
    expectedBehaviour: "The applied listing types are encoded in the URL. Opening the URL in a new tab shows the same filtered grid with Classifieds and Live Items ticked. Pressing Back restores the previous selection.",
    expectedUiState: "New tab: grid shows Classified and Live Item cards; Filters drawer shows Classifieds and Live Items ticked. After Back: the previous filter state (before the Classifieds + Live Items selection) is restored.",
    endResult: "Nothing is persisted to the server. Filter state is URL state.",
  },
  "checklist-buying-browsing-search-product-type-toggles-follow-selection": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products and read the label of the middle availability tab above the grid.",
      "Click that middle tab and read the cards.",
      "Open /auctions and read the label of its middle availability tab.",
      "Click that middle tab and read the cards.",
      "Open /prize-draws and read the label of its middle availability tab.",
    ],
    expectedBehaviour: "The middle availability tab is named for how that listing type stops being available: a product runs out, an auction ends, a prize draw closes. This used to be read by ticking Auctions on /products; auctions now live only on their own page, so the three wordings are read across the three pages.",
    expectedUiState: "/products: the middle tab reads 'Sold'; clicking it shows sold-out product cards. /auctions: it reads 'Ended'; clicking it shows ended auction cards. /prize-draws: it reads 'Closed'. In all three the first tab is 'Available' and is selected on arrival.",
    endResult: "Nothing is persisted to the server.",
  },
  "checklist-buying-browsing-search-search": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products and read the total result count.",
      "Type 'Valkyrie' into the 'Search products...' field.",
      "Click the 'Search' button.",
      "Read the result count and every card title.",
      "Clear the field, type 'zzzznope', and click 'Search'.",
      "Read the result count.",
    ],
    inputs: { matchingQuery: "Valkyrie", nonsenseQuery: "zzzznope" },
    expectedBehaviour:
      "The grid narrows to titles and descriptions matching the term. The nonsense query is the control that proves it is narrowing at all — a search that silently returns everything looks exactly like a working search when the term happens to match most of a small catalogue.",
    expectedUiState:
      "'Valkyrie' returns a smaller count than the unfiltered grid, and every card shown contains the word — 'Beyblade Burst B-01 Valkyrie' and 'Beyblade Burst Valtryek V3 (Sold Out)' style matches. 'zzzznope' returns zero results and an empty state, NOT the full catalogue.",
    expectedData: { nonsenseResultCount: 0 },
    endResult:
      "Nothing persists; the query lives in the URL, so reloading reproduces the same filtered grid.",
  },
  "checklist-buying-browsing-search-search-filter-sort-combo": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Type 'Beyblade' in the search field and click 'Search'.",
      "Click 'Filters', tick 'Classifieds', click 'Apply'.",
      "Open the 'Sort by' dropdown and select 'Name: A–Z'.",
      "Read the URL.",
      "Click 'Page 2' in the pagination bar if available.",
      "Read the URL and note the result count.",
    ],
    inputs: { query: "Beyblade", listingType: "Classifieds", sort: "Name: A–Z" },
    expectedBehaviour: "All three — search query, listing type filter, and sort — stay applied together. Pagination reflects the combined narrowed result count, not the unfiltered total. The sort used here is deliberately a non-money one: price sorts are not offered to signed-out visitors.",
    expectedUiState: "The URL contains the search term, the listing-type parameter, and the sort parameter together. The grid shows only Classified cards whose title includes 'Beyblade', ordered A–Z by title. Page 2 (if navigated) continues this filtered/sorted set, not the unfiltered set.",
    endResult: "Nothing is persisted to the server. State is URL-encoded.",
  },
  "checklist-buying-browsing-search-show-sold-toggle-reveals-items": {
    roles: ["guest"],
    startPage: "/products",
    steps: [
      "Open /products.",
      "Click the 'Sold & Ended' tab.",
      "Scan the grid for 'Beyblade X BX-34 Dran Buster (Sold Out)' (product-beyblade-x-dran-buster-sold-out).",
      "Click the 'Available' tab.",
      "Open /auctions.",
      "Click the 'Ended' tab.",
      "Scan the grid for 'Beyblade Burst B-128 Spriggan Requiem (Ended — Bought Out)' (auction-beyblade-burst-spriggan-requiem-bought-out).",
      "Click the 'Live' tab.",
      "Open /prize-draws.",
      "Click the 'Closed' tab.",
      "Scan the grid for 'Metal Fight Mystery Draw — Ended (Revealed)' (prizedraw-beyblade-metal-closed-revealed).",
      "Click the 'Open' tab.",
    ],
    expectedBehaviour: "The 'Available' / 'Live' / 'Open' tab hides sold-out, ended, and closed items by default. The 'Sold & Ended' / 'Ended' / 'Closed' tab reveals them.",
    expectedUiState: "'Beyblade X BX-34 Dran Buster (Sold Out)' appears on the 'Sold & Ended' tab and is absent on 'Available'. 'Beyblade Burst B-128 Spriggan Requiem (Ended — Bought Out)' appears on 'Ended' and is absent on 'Live'. 'Metal Fight Mystery Draw — Ended (Revealed)' appears on 'Closed' and is absent on 'Open'.",
    endResult: "Nothing is persisted. Tab state is URL state only.",
  },
  "checklist-buying-browsing-search-sort-options-per-listing-type": {
    roles: ["buyer"],
    startPage: "/products",
    steps: [
      "Sign in as a buyer — price sorts are not offered to signed-out visitors.",
      "Open /products with no type filter.",
      "Open the 'Sort by' dropdown and select 'Price low to high'.",
      "Note the order of cards (cheapest first).",
      "Open the 'Sort by' dropdown and select 'Price high to low'.",
      "Note the order of cards (most expensive first).",
      "Open /auctions, open Sort and select 'Ending Soon'.",
      "Note the order of auction cards.",
      "Open /pre-orders, open Sort and select 'Earliest Delivery'.",
      "Note the order of pre-order cards.",
    ],
    expectedBehaviour: "Each sort option genuinely reorders the visible results. Price sorts change the order by price. Ending Soon reorders auctions by end date. Earliest Delivery reorders pre-orders by delivery date. The auction and pre-order legs run on their own pages, because those types are no longer selectable on /products.",
    expectedUiState: "Price low to high: cheapest card first (e.g. ₹149 before ₹1,299). Price high to low: most expensive first. Ending Soon on /auctions: auctions with soonest end date appear first. Earliest Delivery on /pre-orders: pre-orders with earliest expected delivery appear first.",
    endResult: "Nothing is persisted.",
  },
};
