/*
 * WHY: Authored six-part procedures for the buying/buying-checkout checklist page.
 * WHAT: 30 case(s), keyed by full checklist id.
 *
 * Written by hand, case by case, against the label each one states. There is no
 * generator: the authoring scripts were deleted once it was clear they were
 * scaffolding around work that is simply writing.
 *
 * @tag domain:tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed-data/authored/index.ts
 * @tag sideEffects:none
 */

import type { AuthoredCase } from "./_types";

export const authored: Record<string, AuthoredCase> = {
  "checklist-buying-buying-checkout-add-to-cart": {
    roles: ["buyer"],
    startPage: "/products/product-tester-standard-1",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1.",
      "Click 'Add to Cart'.",
      "Open /cart.",
    ],
    inputs: { productId: "product-tester-standard-1", quantity: 1, price: 199 },
    expectedBehaviour: "The item is added to the buyer's cart and persists when the cart page is opened.",
    expectedUiState: "The Cart tab on /cart shows 'Test Gadget — Standard Listing #1' with quantity 1 and price ₹199.00. The cart item count badge in the header has increased.",
    expectedData: { cartLineQuantity: 1, cartLinePrice: 199 },
    endResult: "After reloading /cart, 'Test Gadget — Standard Listing #1' is still listed in the Cart tab.",
  },
  "checklist-buying-buying-checkout-add-to-cart-max-quantity": {
    roles: ["buyer"],
    startPage: "/products/product-tester-standard-1",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1.",
      "Click 'Add to Cart'.",
      "Open /cart.",
      "Click the '+' (Increase quantity) button for 'Test Gadget — Standard Listing #1' repeatedly until it stops incrementing.",
    ],
    inputs: { productId: "product-tester-standard-1", stockQuantity: 10 },
    expectedBehaviour: "The quantity control caps at the listing's available stock and does not allow the buyer to exceed it. A message or disabled state makes the limit clear.",
    expectedUiState: "The '+' (Increase quantity) button becomes disabled or unresponsive once the quantity matches the available stock shown on the product page ('Only 10 left — order soon!'). A message indicating the cap is visible.",
    expectedData: { maxSelectableQuantity: 10 },
    endResult: "After reloading /cart, the quantity shown does not exceed the stock cap that was enforced.",
  },
  "checklist-buying-buying-checkout-add-to-cart-out-of-stock": {
    roles: ["buyer"],
    startPage: "/products/product-beyblade-burst-valtryek-v3-sold-out",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-beyblade-burst-valtryek-v3-sold-out.",
    ],
    expectedBehaviour: "The system prevents the buyer from adding an out-of-stock listing to the cart. No cart mutation occurs.",
    expectedUiState: "The product detail page shows '✗ Out of Stock'. No 'Add to Cart' button is present — the purchase action area is absent or replaced by the out-of-stock indicator.",
    expectedData: { addToCartButtonPresent: false },
    endResult: "After reloading /products/product-beyblade-burst-valtryek-v3-sold-out, the page still shows '✗ Out of Stock' with no 'Add to Cart' button.",
  },
  "checklist-buying-buying-checkout-checkout-back-navigation": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "On Step 1, select the existing address and click 'Continue' to advance to Step 2.",
      "Press the browser back button.",
      "Click 'Continue' again to advance to Step 2.",
      "Click 'Continue to payment' to advance to Step 3.",
      "Press the browser back button again.",
      "Click 'Continue to payment' and complete checkout normally.",
    ],
    expectedBehaviour: "Using the browser back button mid-checkout returns the buyer to the previous step with the cart state intact and does not double-submit or duplicate any order.",
    expectedUiState: "After pressing back from Step 2, Step 1 is shown with the previously selected address still selected. After pressing back from Step 3, Step 2 is shown. The Order Summary consistently shows the correct cart items throughout.",
    expectedData: { ordersCreated: 1 },
    endResult: "Only one order is created at the end. No duplicate orders appear in the buyer's order history.",
  },
  "checklist-buying-buying-checkout-checkout-cash-payment-no-validation-error": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Complete Steps 1 and 2 of checkout.",
      "On Step 3 (Payment), select 'UPI / Cash' (manual payment).",
      "Check the consent checkbox.",
      "Click 'Pay via UPI / Cash'.",
    ],
    inputs: { paymentMethod: "UPI / Cash" },
    expectedBehaviour: "Clicking 'Pay via UPI / Cash' with the consent checkbox checked places the order successfully. No 'Validation failed' error message appears.",
    expectedUiState: "After clicking 'Pay via UPI / Cash', the page transitions to the order confirmation or payment proof upload page. No red error message reading 'Validation failed' or similar is shown.",
    expectedData: { validationErrorShown: false },
    endResult: "An order is created and visible in the buyer's order history. The order has an active 15-minute payment window for proof upload.",
  },
  "checklist-buying-buying-checkout-checkout-flow": {
    roles: ["buyer"],
    startPage: "/products/product-tester-standard-1",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1.",
      "Click 'Add to Cart'.",
      "Open /cart.",
      "Click 'Proceed to checkout'.",
      "On Step 1 (Shipping Address), select the existing address 'Home — 123 Stadium Lane, Vijay Nagar, Indore, Madhya Pradesh 452010'.",
      "Click 'Continue'.",
      "On Step 2 (Add-ons & fees), click 'Continue to payment'.",
      "On Step 3 (Payment), select a payment method and complete the order.",
    ],
    inputs: { productId: "product-tester-standard-1", price: 199 },
    expectedBehaviour: "The three-step checkout flow (Address → Add-ons → Payment) completes without errors, an order is created, and the buyer lands on an order confirmation page.",
    expectedUiState: "Each step advances in sequence: 'Step 1 of 3: Shipping Address', then 'Step 2 of 3: Extras & fees', then the payment step. After completing payment, an order confirmation page is shown with an order number.",
    expectedData: { checkoutStepCount: 3 },
    endResult: "After reloading the order confirmation URL, the order details remain visible and the order status is not cancelled.",
  },
  "checklist-buying-buying-checkout-checkout-manual-payment-consent": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Complete Steps 1 and 2 of checkout.",
      "On Step 3 (Payment), select 'UPI / Cash' (manual payment).",
      "Read the how-it-works guide that appears.",
      "Check the consent checkbox.",
      "Read the state of the 'Pay via UPI / Cash' button.",
    ],
    inputs: { paymentMethod: "UPI / Cash" },
    expectedBehaviour: "Selecting UPI/Cash shows a how-it-works guide covering payment steps, refund summary, and what happens if an item sells out. The 'Pay via UPI / Cash' button is disabled until the consent checkbox is checked.",
    expectedUiState: "A how-it-works guide is visible with sections covering: payment steps, refund policy, and out-of-stock handling. The 'Pay via UPI / Cash' button is greyed out / disabled before the checkbox is checked. After checking the consent checkbox, the button becomes enabled.",
    expectedData: { submitEnabledBeforeConsent: false },
    endResult: "Nothing persists from this step until the button is actually clicked and the order is placed.",
  },
  "checklist-buying-buying-checkout-checkout-mobile-responsive": {
    roles: ["buyer"],
    startPage: "/cart",
    steps: [
      "Resize the browser to a mobile viewport of 390×844 pixels.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart.",
      "Click 'Proceed to checkout'.",
      "Complete Step 1 (address selection) on the mobile viewport.",
      "Complete Step 2 (add-ons) on the mobile viewport.",
      "Reach Step 3 (payment) on the mobile viewport.",
    ],
    inputs: { viewportWidth: 390, viewportHeight: 844 },
    expectedBehaviour: "The full checkout flow is usable on a 390×844 mobile viewport with no horizontal scrolling, no overlapping controls, and all buttons reachable by tap.",
    expectedUiState: "At each step (cart, Step 1, Step 2, Step 3), the layout stacks vertically. The Order Summary panel, address cards, add-on checkboxes, and payment controls are all fully visible and usable without horizontal scrolling. No text is clipped.",
    expectedData: { horizontalScrollPresent: false },
    endResult: "Nothing additional persists from this layout check.",
  },
  "checklist-buying-buying-checkout-checkout-multi-seller-split": {
    roles: ["buyer"],
    startPage: "/cart",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart' (store-tester-sandbox).",
      "Open /products/product-tester-crossstore-b and click 'Add to Cart' (store-beyblade-arena).",
      "Open /cart and confirm the Cart tab shows items from at least two different stores.",
      "Click 'Proceed to checkout'.",
      "Select the existing address and click 'Continue' through each step.",
      "Complete the checkout.",
    ],
    inputs: { storeAProduct: "product-tester-standard-1", storeBProduct: "product-tester-crossstore-b" },
    expectedBehaviour: "The checkout splits items from different sellers into separate orders. The buyer receives one order confirmation per seller rather than a single combined order.",
    expectedUiState: "On the order confirmation page, separate order entries are shown for each seller (store-tester-sandbox and store-beyblade-arena). The subtotals for each order match the items from that seller.",
    expectedData: { orderCount: 2 },
    endResult: "After reloading the order confirmation or order history, two separate orders exist — one from store-tester-sandbox and one from store-beyblade-arena.",
  },
  "checklist-buying-buying-checkout-checkout-order-review": {
    roles: ["buyer"],
    startPage: "/products/product-tester-standard-1",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1.",
      "Click 'Add to Cart'.",
      "Open /cart.",
      "Click 'Proceed to checkout'.",
      "On Step 1, select the existing address 'Home — 123 Stadium Lane, Vijay Nagar, Indore, Madhya Pradesh 452010'.",
      "Click 'Continue'.",
      "On Step 2 (Add-ons & fees), read the Order Summary panel before proceeding.",
    ],
    expectedBehaviour: "The Order Summary panel during checkout accurately reflects the items in the cart, their quantities, the selected shipping address, and a correct total.",
    expectedUiState: "The Order Summary panel shows: 'Shipping to Mock User 3, 123 Stadium Lane, Indore'; Subtotal with the correct item price(s); Platform fee; GST; and a correct Total. The item 'Test Gadget — Standard Listing #1' at ₹199.00 is included.",
    endResult: "Nothing additional persists from this review step. The order is not placed until payment is completed.",
  },
  "checklist-buying-buying-checkout-checkout-order-summary-full-breakdown": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Complete Step 1 (address) and advance to Step 2 (Add-ons & fees).",
      "Check the 'WhatsApp order updates (+₹10.00)' checkbox.",
      "Check the 'Gift wrap (+₹49.00)' checkbox.",
      "Read the Order Summary panel.",
    ],
    expectedBehaviour: "The Order Summary panel on the payment step shows Shipping, individual checked add-on fees (WhatsApp updates and Gift wrap), GST, and Coupon discount (if any) as separate line items — not just Subtotal and Total. The Total updates to include the newly checked add-ons.",
    expectedUiState: "The Order Summary shows individual line items: Subtotal, 'WhatsApp order updates' at ₹10.00, 'Gift wrap' at ₹49.00, Platform fee, GST, and Total. The Total is higher than Subtotal alone and matches Subtotal + add-ons + fees. Unchecked add-ons (Shipment protection) do not appear.",
    endResult: "The Total shown in the Order Summary matches the Total on the order confirmation page after payment is completed.",
  },
  "checklist-buying-buying-checkout-checkout-otp-highvalue": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-beyblade-original-dranzer-s and click 'Add to Cart' — ₹1,499.",
      "Open /products/product-beyblade-original-driger-v and click 'Add to Cart' — ₹1,799.",
      "Open /products/product-beyblade-metal-storm-pegasus and click 'Add to Cart' — ₹1,299.",
      "Open /products/product-beyblade-burst-regalia-genesis and click 'Add to Cart' — ₹1,399.",
      "Open /cart and read the subtotal, which is ₹5,996.",
      "Click 'Proceed to checkout'.",
      "On Step 1, select the existing address and click 'Continue'.",
      "On Step 2, click 'Continue to payment'.",
      "On Step 3, select any non-COD payment method.",
      "Read the payment step for a 'Verify this order' prompt.",
      "Open /cart in another tab, remove the ₹1,399 item so the subtotal is ₹4,597, and run the same checkout to the payment step.",
    ],
    inputs: { otpThreshold: 5000, subtotalAbove: 5996, subtotalBelow: 4597 },
    expectedBehaviour:
      "Above the ₹5,000 threshold and on a non-COD method, checkout inserts an emailed one-time code before payment. Below it, payment proceeds with no OTP at all — which is why the second half matters: a prompt that appears for every cart is not a threshold.",
    expectedUiState:
      "At ₹5,996 a 'Verify this order' prompt appears with a code field and names the masked email it went to. At ₹4,597 no such prompt appears and the payment control is reached directly. A failure to send shows readable English, not a raw provider error code.",
    expectedData: { otpRequiredAbove: true, otpRequiredBelow: false },
    endResult:
      "Entering the correct code completes the order. Three items only add to ₹4,597 — the fourth is what actually crosses the threshold, and an earlier draft of this case stopped at three and could never have triggered the prompt it was checking for.",
  },
  "checklist-buying-buying-checkout-checkout-otp-whatsapp-hidden-without-phone": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123! and confirm Site Settings → Notifications → WhatsApp → 'WhatsApp OTP' is enabled.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /user/addresses and add an address named 'QA Address otp-whatsapp-hidden', 2 Test Road, Mumbai, Maharashtra 400001, leaving the phone field empty.",
      "Add product-beyblade-original-dranzer-s (₹1,499), product-beyblade-original-driger-v (₹1,799), product-beyblade-metal-storm-pegasus (₹1,299) and product-beyblade-burst-regalia-genesis (₹1,399) to the cart, making ₹5,996.",
      "Open /checkout, select 'QA Address otp-whatsapp-hidden' on Step 1, and continue to the payment step.",
      "Select a non-COD payment method.",
      "Read every option offered on the OTP prompt.",
    ],
    inputs: { addressLabel: "QA Address otp-whatsapp-hidden", phone: "", subtotal: 5996 },
    expectedBehaviour:
      "The WhatsApp channel needs three things at once — admin-enabled, real credentials, and a phone number on the SELECTED address. Missing the third hides the option rather than offering it and failing at send time, which would waste the buyer's OTP window on a channel that could never deliver.",
    expectedUiState:
      "The prompt offers email only. There is no 'Send via WhatsApp instead' control, disabled or otherwise, even though the same setting shows one for an address that has a phone.",
    expectedData: { whatsappOptionPresent: false },
    endResult:
      "The order still completes by email OTP. Delete the address afterwards so it does not accumulate across runs.",
  },
  "checklist-buying-buying-checkout-checkout-otp-whatsapp-option": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123! and confirm Site Settings → Notifications → WhatsApp → 'WhatsApp OTP' is enabled with real Meta Cloud API credentials.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /user/addresses and add a phone number to the existing address 'Home — 123 Stadium Lane, Vijay Nagar, Indore, Madhya Pradesh 452010' if it does not already have one.",
      "Add product-beyblade-original-dranzer-s (₹1,499), product-beyblade-original-driger-v (₹1,799), product-beyblade-metal-storm-pegasus (₹1,299) and product-beyblade-burst-regalia-genesis (₹1,399) to the cart, making ₹5,996.",
      "Open /cart and click 'Proceed to checkout'.",
      "Select the address with a phone number on Step 1 and click 'Continue'.",
      "Click 'Continue to payment' on Step 2.",
      "On Step 3, select a non-COD payment method.",
      "Read the default send channel shown on the OTP prompt.",
      "Click 'Send via WhatsApp instead'.",
      "Type the code received on WhatsApp into the OTP field and submit it.",
    ],
    inputs: { subtotal: 5996, defaultChannel: "email", alternateChannel: "WhatsApp" },
    expectedBehaviour:
      "Email is the default channel and WhatsApp is opt-in per attempt. The alternate appears only when the feature is enabled, real Meta credentials are configured, and the selected address carries a phone — the seeded Meta secrets are empty strings rather than placeholders precisely so a missing credential skips cleanly instead of making a billed call that fails.",
    expectedUiState:
      "The prompt first shows a masked email. After 'Send via WhatsApp instead' it shows a masked phone in the shape '+91 ••••••7890'. The code that arrives on WhatsApp is accepted and payment proceeds.",
    expectedData: { defaultChannel: "email" },
    endResult:
      "The order is placed after the WhatsApp code verifies. With no real Meta credentials configured this case is unreachable — answer null rather than reporting the missing option as a bug.",
  },
  "checklist-buying-buying-checkout-checkout-razorpay-charge-includes-shipping": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123! and confirm Site Settings → Payments → Razorpay is enabled and the seller store-beyblade-arena has a configured shipping fee.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-beyblade-burst-valkyrie (price ₹999, store-beyblade-arena) and click 'Add to Cart'.",
      "Complete Steps 1 and 2 of checkout.",
      "On Step 3, select 'Razorpay' (online payment).",
      "Read the amount shown in the Order Summary before clicking the Razorpay pay button.",
      "Click the Razorpay pay button and observe the amount displayed inside the Razorpay checkout modal.",
    ],
    expectedBehaviour: "The amount shown inside the Razorpay checkout modal must exactly match the Total shown in the Order Summary panel, including the seller's shipping fee. No discrepancy between the gateway charge and the recorded order total.",
    expectedUiState: "The Razorpay modal opens and shows a rupee amount that exactly matches the Total in the Order Summary (e.g. if the Order Summary shows ₹1,149.00, the Razorpay modal shows ₹1,149.00 — not ₹999.00 or any other amount).",
    endResult: "After payment, the order confirmation page shows a Total that matches the Razorpay modal amount exactly.",
  },
  "checklist-buying-buying-checkout-emi-checkout-flow": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123! and confirm EMI is enabled in Site Settings → Payments → EMI.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/live-golden-retriever-puppy and click 'Add to Cart' — ₹25,000.",
      "Complete Steps 1 and 2 of checkout.",
      "On Step 3, read the payment methods and select 'EMI'.",
      "Read the tenure options, the token amount and the surcharge.",
      "Select a tenure and place the order.",
      "Open /user/orders and open the order just created.",
      "Open /cart in another tab, replace the item with product-tester-standard-1 (₹199), and reach the payment step again.",
    ],
    inputs: { highValueItem: "live-golden-retriever-puppy", highValuePrice: 25000, lowValuePrice: 199 },
    expectedBehaviour:
      "EMI is offered only above the eligibility threshold and only when the seller has opted in — the site-wide flag alone is not enough. A ₹199 cart must not offer it. The buyer is quoted from the buyer-facing settings, which exclude the platform-versus-seller surcharge split; that figure is server-side only and must never reach the payment step.",
    expectedUiState:
      "At ₹25,000 the payment step lists tenures with a per-instalment amount, a token amount and a surcharge for each. After placing the order its detail page shows the full instalment schedule. At ₹199 no EMI option appears at all.",
    expectedData: { emiOfferedHighValue: true, emiOfferedLowValue: false },
    endResult:
      "The schedule survives a reload of the order page. The low-value half is the real check — an EMI badge on a ₹1,499 product was a live bug caused by reading only the site-wide flag, and a case that only ever tests a large cart passes straight over it.",
  },
  "checklist-buying-buying-checkout-gst-breakdown-display": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123! and verify that Site Settings → Tax → GST is enabled.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "On Step 1, select the existing address 'Home — 123 Stadium Lane, Vijay Nagar, Indore, Madhya Pradesh 452010' and click 'Continue'.",
      "On Step 2, read the Order Summary panel.",
    ],
    inputs: { productId: "product-tester-standard-1", price: 199 },
    expectedBehaviour: "When GST is enabled, the Order Summary shows a GST line item. The breakdown is CGST+SGST when buyer and seller are in the same state, or IGST when they are in different states.",
    expectedUiState: "The Order Summary panel shows a 'GST' line item (e.g. ₹1.80). The label or tooltip distinguishes CGST/SGST from IGST based on buyer vs seller state.",
    endResult: "Nothing additional persists from viewing the GST breakdown.",
  },
  "checklist-buying-buying-checkout-order-confirmation": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Complete the full checkout flow (address → add-ons → payment).",
      "Land on the order confirmation page.",
      "Check the registered email (rehan.sheikh@gmail.com) for a confirmation email.",
    ],
    inputs: { productId: "product-tester-standard-1", price: 199 },
    expectedBehaviour: "The order confirmation page shows correct order details matching what was in the cart. A confirmation email is sent to the buyer's registered address with the same order details.",
    expectedUiState: "The order confirmation page shows: an order number, the item 'Test Gadget — Standard Listing #1' at ₹199.00, the shipping address '123 Stadium Lane, Vijay Nagar, Indore, Madhya Pradesh 452010', and a Total that matches the checkout summary.",
    endResult: "After reloading the order confirmation URL, all details remain visible and the order is not cancelled.",
  },
  "checklist-buying-buying-checkout-out-of-stock-policy-cancel": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123! and set Site Settings → Checkout → Out-of-stock policy to 'Cancel whole order'.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Add product-tester-standard-1 (₹199, stock 10) and product-tester-standard-2 (₹149) to the cart.",
      "While on the checkout payment step (before submitting), have the admin or another session reduce product-tester-standard-1's stock to 0.",
      "Submit the checkout.",
    ],
    inputs: { policy: "Cancel whole order", goesOutOfStock: "product-tester-standard-1" },
    expectedBehaviour: "With the 'cancel whole order' policy, if any item in the batch goes out of stock mid-checkout, the entire checkout is rejected. No order is created and the buyer receives an error.",
    expectedUiState: "After submitting, an error message is shown indicating that an item went out of stock and the entire order was cancelled. No order confirmation page is shown.",
    expectedData: { ordersCreated: 0 },
    endResult: "After reloading /cart, both items are still present in the cart (or the buyer is able to restart the checkout). No order record exists for this attempt.",
  },
  "checklist-buying-buying-checkout-out-of-stock-policy-skip": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123! and set Site Settings → Checkout → Out-of-stock policy to 'Skip unavailable items'.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Add product-tester-standard-1 (₹199, stock 10) and product-tester-standard-2 (₹149) to the cart.",
      "While on the checkout payment step (before submitting), have the admin or another session reduce product-tester-standard-2's stock to 0.",
      "Submit the checkout.",
    ],
    inputs: { policy: "Skip unavailable items", goesOutOfStock: "product-tester-standard-2" },
    expectedBehaviour: "With the 'skip unavailable items' policy, the out-of-stock item is silently dropped and an order is placed for only the still-available item(s). The buyer is informed which item was skipped.",
    expectedUiState: "After submitting, the order confirmation page shows only product-tester-standard-1 (₹199). A notice is shown indicating that product-tester-standard-2 was unavailable and was removed from the order.",
    expectedData: { orderLineCount: 1 },
    endResult: "After reloading the order detail page, only product-tester-standard-1 is listed in the order. product-tester-standard-2 is not included.",
  },
  "checklist-buying-buying-checkout-payment-auto-approve-dispute": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Complete checkout with UPI/Cash payment and upload a valid payment proof.",
      "Wait 2 hours without the admin manually approving the order.",
      "Reload the order detail page after 2 hours.",
      "Click 'Raise a dispute' on the auto-approved order.",
    ],
    inputs: { autoApproveHours: 2 },
    expectedBehaviour: "After 2 hours with no admin action, the order is auto-approved and shows a badge indicating auto-approval. The 'Raise a dispute' button is present and submits successfully.",
    expectedUiState: "The order detail page shows an auto-approved badge (e.g. 'Auto-approved' or similar label). A 'Raise a dispute' button is visible. After clicking it, a dispute form or confirmation appears, and submitting it succeeds without an error.",
    endResult: "After reloading the order detail page, the dispute is recorded and the order status reflects the dispute.",
  },
  "checklist-buying-buying-checkout-payment-method-selection": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "Select the existing address and click 'Continue' through Step 1 and Step 2.",
      "On Step 3 (Payment), read the available payment methods.",
      "Select 'COD' (Cash on Delivery) if available and observe the UI.",
      "Select 'UPI / Cash' (manual payment) and observe the UI.",
      "If Razorpay is listed, select it and observe the UI.",
    ],
    inputs: { productId: "product-tester-standard-1" },
    expectedBehaviour: "Each payment method option can be selected and the UI adapts accordingly — COD shows a COD confirmation, manual payment shows a how-it-works guide and consent checkbox, Razorpay (when enabled) offers to open the payment gateway.",
    expectedUiState: "Step 3 lists the available payment methods as selectable options. Selecting each one changes the lower section of the form to show method-specific instructions or controls. At least COD and UPI/Cash are shown.",
    endResult: "Nothing persists until payment is actually submitted.",
  },
  "checklist-buying-buying-checkout-payment-proof-reupload": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as admin@letitrip.in / TempPass123!.",
      "Locate an existing manual-payment order that has proof submitted and request a proof re-upload from the order management panel.",
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open the order's payment proof page.",
      "Upload a new screenshot file as replacement proof.",
      "Enter a new UTR number.",
      "Check the agreement checkbox and submit.",
    ],
    inputs: { proofFile: "public/test-media/sample-image.png", utr: "QA UTR reupload 552310" },
    expectedBehaviour: "When an admin requests a re-upload, the buyer's payment window is extended and the proof upload form becomes active again. The buyer can submit new proof successfully.",
    expectedUiState: "The payment proof page shows an active upload form (not locked). The countdown reflects the extended deadline. After submitting, a confirmation message appears.",
    endResult: "After reloading the order detail page, the payment proof status shows the newly submitted proof and the re-upload request is resolved.",
  },
  "checklist-buying-buying-checkout-payment-proof-upload": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Complete checkout with 'UPI / Cash' payment — check the consent checkbox and click 'Pay via UPI / Cash'.",
      "On the payment proof page, upload a screenshot file as proof.",
      "Enter a UTR number in the UTR field.",
      "Check the 'mark-as-paid' agreement checkbox.",
      "Click the submit/upload button.",
    ],
    inputs: { proofFile: "public/test-media/sample-image.png", utr: "QA UTR upload 118427" },
    expectedBehaviour: "The payment proof (screenshot file, UTR, and agreement checkbox) is accepted and submitted successfully. The order status updates to reflect that proof has been submitted and is awaiting admin review.",
    expectedUiState: "After submission, a confirmation message appears (e.g. 'Proof submitted' or similar). The upload form is no longer editable or is replaced by a 'proof received' state. The countdown timer is still visible.",
    endResult: "After reloading the order detail page, the payment proof status shows 'submitted' or 'pending review', and the uploaded screenshot is accessible.",
  },
  "checklist-buying-buying-checkout-payment-window-countdown": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "Complete Steps 1 and 2 of checkout.",
      "On Step 3, select 'UPI / Cash' (manual payment).",
      "Check the consent checkbox and click 'Pay via UPI / Cash'.",
      "Wait 3 seconds on the page that loads after clicking 'Pay via UPI / Cash'.",
    ],
    inputs: { paymentWindowMinutes: 15 },
    expectedBehaviour: "After a manual-payment order is placed, the payment proof page shows a countdown timer giving the buyer 15 minutes to upload proof.",
    expectedUiState: "The payment proof page displays a countdown reading approximately '0d 0h 14m Xs' (roughly 15 minutes from placement) and it is visibly ticking down in seconds. A payment proof upload section is also present on the same page.",
    endResult: "After reloading the payment proof page, the countdown continues from where it left off (not reset) and the timer is still counting down toward zero.",
  },
  "checklist-buying-buying-checkout-payment-window-expiry": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Complete checkout with 'UPI / Cash' payment — check the consent checkbox and click 'Pay via UPI / Cash'.",
      "Do not upload any payment proof.",
      "Wait for the 15-minute payment window to expire (or ask the admin to manually expire it via the admin panel).",
      "Reload the order detail page.",
    ],
    inputs: { paymentWindowMinutes: 15 },
    expectedBehaviour: "Once the 15-minute window expires with no proof submitted, the order is automatically cancelled and the item's stock is restored.",
    expectedUiState: "The order detail page shows a cancelled status. The payment proof upload form is no longer available.",
    expectedData: { orderCancelled: true },
    endResult: "After reloading /products/product-tester-standard-1, the stock count reflects the restored item (the stock is back to at least what it was before the order was placed).",
  },
  "checklist-buying-buying-checkout-shipping-address": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "On Step 1 (Shipping Address), click the address card 'Home — 123 Stadium Lane, Vijay Nagar, Indore, Madhya Pradesh 452010' to select it.",
      "Click 'Continue'.",
    ],
    inputs: { addressLabel: "Home" },
    expectedBehaviour: "Selecting an existing address enables the Continue button and passes the address to the next step and the Order Summary.",
    expectedUiState: "After clicking the address card, the Order Summary panel updates to show 'Shipping to Mock User 3, 123 Stadium Lane, Indore' and the 'Continue' button is no longer disabled.",
    endResult: "The selected address is carried into Step 2 and shown in the Order Summary panel throughout the remaining checkout steps.",
  },
  "checklist-buying-buying-checkout-shipping-address-edit": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "On Step 1 (Shipping Address), locate the existing address and click its edit control.",
      "Change the street field from its current value to 'QA Address buying-checkout-shipping-address-edit Updated Street'.",
      "Save the changes.",
      "Select the updated address and click 'Continue'.",
    ],
    inputs: { street: "QA Address shipping-address-edit Updated Street" },
    expectedBehaviour: "The address edit form opens inline, saves successfully, and the updated address is immediately reflected in the address list without leaving the checkout flow.",
    expectedUiState: "After saving, the address list shows the updated street 'QA Address buying-checkout-shipping-address-edit Updated Street'. The Order Summary reflects the updated address when it is selected.",
    endResult: "After reloading /user/addresses or revisiting the checkout, the address retains the updated street value.",
  },
  "checklist-buying-buying-checkout-shipping-address-inline-add": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "On Step 1 (Shipping Address), click '+ Add new address'.",
      "Fill in the address form: Name 'QA Address buying-checkout-shipping-address-inline-add', Street '1 Test Street', City 'Mumbai', State 'Maharashtra', Pincode '400001'.",
      "Save the new address.",
      "Click the newly saved address card 'QA Address buying-checkout-shipping-address-inline-add' in the list.",
      "Click 'Continue'.",
    ],
    inputs: { name: "QA Address shipping-address-inline-add", street: "1 Test Street", city: "Mumbai", state: "Maharashtra", pincode: "400001" },
    expectedBehaviour: "A new address is saved without leaving the checkout flow and is immediately available for selection on Step 1.",
    expectedUiState: "After saving, the address 'QA Address buying-checkout-shipping-address-inline-add, 1 Test Street, Mumbai, Maharashtra 400001' appears in the address list on Step 1 and can be selected. The 'Continue' button becomes enabled once it is selected.",
    endResult: "After completing the checkout, the saved address 'QA Address buying-checkout-shipping-address-inline-add' remains in the buyer's address book.",
  },
  "checklist-buying-buying-checkout-shipping-method-selection": {
    roles: ["buyer"],
    startPage: "/checkout",
    steps: [
      "Sign in as rehan.sheikh@gmail.com / TempPass123!.",
      "Open /products/product-tester-standard-1 and click 'Add to Cart'.",
      "Open /cart and click 'Proceed to checkout'.",
      "On Step 1, select the existing address 'Home — 123 Stadium Lane, Vijay Nagar, Indore, Madhya Pradesh 452010' and click 'Continue'.",
      "On Step 2 (Add-ons & fees), if a shipping method selector is present, select a different shipping method and observe the shipping fee in the Order Summary.",
    ],
    expectedBehaviour: "Changing the shipping method recalculates the shipping fee shown in the Order Summary immediately. The Total updates to include the new fee.",
    expectedUiState: "The Order Summary shows a 'Shipping' line item that updates when a different shipping method is selected. The Total reflects the new shipping fee.",
    endResult: "The shipping fee carried into the payment step matches the method selected on Step 2.",
    needsReview: true,
    reviewNote: "The step 2 add-ons screen did not show a shipping method selector in the session observed — it may only appear when the seller has configured multiple shipping options. Mark as needs-review until confirmed.",
  },
};
