/*
 * WHY: Authored six-part procedures for the buying/buying-coupons checklist page.
 * WHAT: 20 case(s), keyed by full checklist id.
 *
 * Generated by `node tester/scripts/merge-authored.mjs --page buying/buying-coupons`, then
 * reviewed by a human before merge — the review is the gate, not the generation.
 * Hand edits are safe and expected: re-running the merge for this page replaces
 * the file, so re-author only when you mean to discard them.
 *
 * @tag domain:tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed-data/authored/index.ts
 * @tag sideEffects:none
 */

import type { AuthoredCase } from "./_types";

export const authored: Record<string, AuthoredCase> = {
  "checklist-buying-buying-coupons-coupon-all-codes-listed-on-order": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) and product-beyblade-metal-storm-pegasus (₹1,299, Beyblade Arena) to the cart.",
      "Navigate to /checkout, complete all steps, apply ARENA25 and FREESHIP499, and place the order.",
      "Navigate to /user/orders and open the order detail page.",
      "Navigate to the invoice page for the same order.",
    ],
    expectedBehaviour: "Both the order detail page and the invoice page show a separate discount line for each coupon applied — one line naming ARENA25 with its amount, one line naming FREESHIP499. Neither page collapses both into a single generic 'Discount' line.",
    expectedUiState: "Order detail: two distinct discount lines, each identifying the coupon code and amount. Invoice: same two lines present. No single 'Discount (ARENA25)' line that silently omits FREESHIP499.",
    endResult: "The order and invoice records are persisted — a reload shows the same distinct coupon lines.",
  },
  "checklist-buying-buying-coupons-coupon-auction-offer-lane-no-coupon-field": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Navigate to /cart.",
      "Click the 'Won Auctions' tab to switch to the auction lane.",
      "Click 'Proceed to checkout' from the Won Auctions lane.",
      "Scroll to the area where coupons would normally appear (below the address step).",
      "Go back to /cart and click the 'Accepted Offers' tab.",
      "Click 'Proceed to checkout' from the Accepted Offers lane.",
      "Scroll to the area where coupons would normally appear.",
    ],
    expectedBehaviour: "For both the Auction and Offer checkout lanes, the coupon input field and the 'How coupons work' panel are not rendered. An informational banner explains that coupons do not apply because the price is already agreed.",
    expectedUiState: "No coupon input or 'How coupons work' panel is visible on the page. A banner reads approximately 'You're paying for your Auction wins. The price is already agreed, so coupons don't apply and the rest of your cart stays where it is.' (or the Accepted Offers equivalent).",
    endResult: "Nothing to persist — this is a display-only check.",
    needsReview: true,
    reviewNote: "The tester account may not have seeded won auctions or accepted offers. The case needs user-seto-kaiba or another buyer to have a won auction (offer-tester-sandbox-accepted / auction-tester-sandbox-won) accessible in their cart lanes.",
  },
  "checklist-buying-buying-coupons-coupon-category-restriction-accepts-matching-cart": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-metal-storm-pegasus (₹1,299, Metal Fight category) and product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena, Beyblade Burst category) to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type SEALED20 and click 'Apply'.",
    ],
    expectedBehaviour: "SEALED20 is accepted because the cart now contains a Burst-generation item (category-beyblade-burst). The discount is applied only to the Burst item (product-beyblade-burst-regalia-genesis ₹1,399), not to the Metal item (product-beyblade-metal-storm-pegasus).",
    expectedUiState: "SEALED20 appears in the applied-coupons list. The discount amount reflects 20% of ₹1,399 (max ₹1,000) = ₹279.80, not 20% of the combined subtotal. No error message is shown.",
    endResult: "A reload of /checkout shows SEALED20 applied with the Burst-item-only discount amount.",
  },
  "checklist-buying-buying-coupons-coupon-category-restriction-rejects-non-matching-cart": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-metal-storm-pegasus (₹1,299, Beyblade Arena, Metal Fight category) to the cart — this is a Metal-generation item, not Burst or X.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type SEALED20 and click 'Apply'.",
    ],
    expectedBehaviour: "SEALED20 is rejected because it is restricted to category-beyblade-burst and category-beyblade-x, and the cart contains only Metal-generation items. A category-related error message is shown.",
    expectedUiState: "An error message appears indicating the coupon does not apply to the items in the cart (category mismatch). SEALED20 does not appear in the applied-coupons list.",
    endResult: "A reload of /checkout shows SEALED20 absent from the applied-coupons list.",
  },
  "checklist-buying-buying-coupons-coupon-expired-in-cart-dropped-at-placement": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) to the cart.",
      "Navigate to /checkout, complete Step 1 and Step 2.",
      "Apply coupon-tester-sandbox-expired (code TESTEREXPIRED) — note: this coupon is already expired in the seed, so apply a currently-active coupon (ARENA25) instead and have an admin deactivate it mid-session.",
      "Ask an admin to open /admin/coupons, find ARENA25, and set it to inactive.",
      "Without reloading the coupon section, click Place Order.",
      "Navigate to /user/orders and open the new order.",
    ],
    expectedBehaviour: "The order is placed without the ARENA25 discount. The buyer is notified (via a banner, toast, or order note) that ARENA25 was removed because it was no longer valid. The order total reflects the full price without ARENA25.",
    expectedUiState: "The order detail page shows no ARENA25 discount line. A message (on the order page or shown at placement time) explains that ARENA25 was removed before the order was finalised.",
    endResult: "The placed order persists without the ARENA25 discount — a reload of the order detail page confirms the correct total.",
    needsReview: true,
    reviewNote: "This case requires admin cooperation to deactivate a coupon mid-session. The TESTEREXPIRED coupon is already expired at seed time, which could serve as a pre-condition if the checkout doesn't validate on load — the test should apply TESTEREXPIRED if it initially accepts, then place the order. Needs clarification on whether TESTEREXPIRED is accepted at apply-time or only rejected at placement.",
  },
  "checklist-buying-buying-coupons-coupon-help-visible-cart": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399) to the cart and navigate to /cart.",
      "Locate the Order Summary panel on the right side of the page.",
      "Find the collapsed disclosure labelled 'How coupons work' with the sub-label 'Stacking rules'.",
      "Click the 'How coupons work' disclosure header to expand it.",
    ],
    expectedBehaviour: "The panel expands and reveals three sections of text explaining coupon stacking rules: one coupon per store, one platform-wide coupon on top, and a list of reasons a coupon might not apply.",
    expectedUiState: "The 'How coupons work' disclosure is open. Three headings and their bullet lists are visible: 'You can use more than one coupon', 'Where each discount lands', and 'Why a coupon might not apply'. The panel is inside the Order Summary. It was collapsed before the click.",
    endResult: "The panel state is UI-only and does not persist across a reload — the disclosure returns to its collapsed default on the next page load.",
  },
  "checklist-buying-buying-coupons-coupon-help-visible-checkout": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399) to the cart and navigate to /checkout.",
      "Complete Step 1 (Shipping Address) and Step 2 (Shipping Method) to reach the payment/coupon step.",
      "Locate the coupon input field (placeholder 'Coupon code') and the 'How coupons work' panel below it.",
      "Click the 'How coupons work' disclosure header to expand it.",
    ],
    expectedBehaviour: "The checkout coupon panel expands to show the same three sections as the cart panel, plus one additional sentence: 'Coupons are re-checked when you place the order. If one has expired or run out while it sat in your cart, it's removed and your total is recalculated before payment.'",
    expectedUiState: "The 'How coupons work' disclosure is open. The revalidation note is present and is absent from the cart version. The input field with placeholder 'Coupon code' and an 'Apply' button are visible above the panel.",
    endResult: "The panel state is UI-only and does not persist across a reload.",
  },
  "checklist-buying-buying-coupons-coupon-help-visible-listing": {
    role: "buyer",
    startPage: "/promotions",
    steps: [
      "Open /promotions and click the 'Coupons' tab.",
      "Locate the 'How coupons work' disclosure above the coupon grid.",
      "Click the 'How coupons work' header to expand it.",
      "Write down the exact wording of all three sections.",
      "Open /stores/store-beyblade-arena and navigate to its coupons sub-page.",
      "Click the 'How coupons work' header to expand it and compare the wording to what was written in step 4.",
    ],
    expectedBehaviour: "Both the /promotions Coupons tab and the Beyblade Arena store coupons listing show a collapsed 'How coupons work' panel above the coupon grid. The wording in both panels is identical to each other and to the cart panel.",
    expectedUiState: "On both pages the disclosure header reads 'How coupons work' with sub-label 'Stacking rules'. Expanded content has the same three sections ('You can use more than one coupon', 'Where each discount lands', 'Why a coupon might not apply') with identical bullet text on both pages.",
    endResult: "Panel state is UI-only and does not persist across a reload.",
  },
  "checklist-buying-buying-coupons-coupon-min-purchase-uses-eligible-subtotal": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-valkyrie (₹999, Beyblade Arena) to the cart — this is below the ARENA25 minimum of ₹1,000.",
      "Add a LetItRip Official item worth ≥₹900 to the cart so the overall cart total exceeds ₹1,000.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type ARENA25 and click 'Apply'.",
    ],
    expectedBehaviour: "ARENA25 is rejected because the Beyblade Arena eligible subtotal (₹999) is below ARENA25's minimum purchase of ₹1,000 — even though the overall cart total is above ₹1,000. The rejection message is shown.",
    expectedUiState: "An error message appears (mentioning minimum purchase not met). ARENA25 does not appear in the applied-coupons list.",
    endResult: "A reload of /checkout shows ARENA25 absent from the applied-coupons list.",
  },
  "checklist-buying-buying-coupons-coupon-persists-across-reload": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "Apply ARENA25 and FREESHIP499.",
      "Reload the /checkout page.",
      "Navigate to /cart, then navigate back to /checkout.",
    ],
    expectedBehaviour: "After the reload and after the cart round-trip, both ARENA25 and FREESHIP499 are still listed in the applied-coupons section with the same discount amounts as before.",
    expectedUiState: "After step 5: ARENA25 and FREESHIP499 are present in the applied-coupons list with the same amounts. After step 6: navigating back to /checkout still shows both coupons applied.",
    endResult: "Both coupons are persisted server-side — they survive a full page reload and a cart-to-checkout round-trip.",
  },
  "checklist-buying-buying-coupons-coupon-remove-one-of-many": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) and product-beyblade-metal-storm-pegasus (₹1,299, Beyblade Arena) to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "Apply ARENA25, then SEALED20, then FREESHIP499 — three coupons.",
      "Note the discount amount for SEALED20 and the Order Summary total.",
      "Click the remove button next to SEALED20.",
    ],
    expectedBehaviour: "SEALED20 is removed. ARENA25 and FREESHIP499 remain applied. The Order Summary total increases by exactly the amount that SEALED20 was providing. The discount lines update to reflect only the two remaining coupons.",
    expectedUiState: "The applied-coupons list shows ARENA25 and FREESHIP499 only. SEALED20 is gone. The Order Summary 'Coupon discount' line (or equivalent) reflects only ARENA25 + FREESHIP499. The total has increased by the SEALED20 discount amount noted in step 5.",
    endResult: "A reload of /checkout shows ARENA25 and FREESHIP499 applied and SEALED20 absent.",
  },
  "checklist-buying-buying-coupons-coupon-split-across-per-store-orders": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Build a cart with product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) and at least one item from LetItRip Official worth ≥₹500.",
      "Navigate to /checkout, complete all steps, apply ARENA25 and FREESHIP499, and place the order.",
      "Navigate to /user/orders.",
      "Open the Beyblade Arena order detail page.",
      "Open the LetItRip Official order detail page.",
      "Add the coupon discount amounts shown across both orders.",
    ],
    expectedBehaviour: "Two separate orders are created. The Beyblade Arena order shows ARENA25 and its proportional share of FREESHIP499. The LetItRip Official order shows only its proportional share of FREESHIP499 (not ARENA25). The FREESHIP499 shares across both orders add up to the total FREESHIP499 discount shown at checkout.",
    expectedUiState: "Each order detail page lists its coupon discount lines separately. ARENA25 appears only on the Beyblade Arena order. FREESHIP499 appears on both orders as proportional amounts that sum to the checkout total.",
    endResult: "The order records are persisted — a reload of each order detail page shows the same coupon lines.",
  },
  "checklist-buying-buying-coupons-coupon-stack-duplicate-code-rejected": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type ARENA25 and click 'Apply'.",
      "In the coupon input field, type ARENA25 again and click 'Apply'.",
    ],
    expectedBehaviour: "The first ARENA25 application succeeds. The second attempt is rejected with 'Coupon ARENA25 is already applied.' No duplicate row appears in the applied-coupons list.",
    expectedUiState: "ARENA25 appears exactly once in the applied-coupons list. An error message reads 'Coupon ARENA25 is already applied.' (or 'This coupon is already applied.'). The list does not contain two ARENA25 rows.",
    endResult: "A reload of /checkout shows a single ARENA25 entry in the applied-coupons list.",
  },
  "checklist-buying-buying-coupons-coupon-stack-second-global-rejected": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) and product-beyblade-original-driger-v (₹1,799, Beyblade Arena) to the cart so the cart total is ≥₹2,000.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type FREESHIP499 and click 'Apply'.",
      "In the coupon input field, type BLADER50 and click 'Apply'.",
      "Click the remove button next to FREESHIP499 to remove it.",
      "In the coupon input field, type BLADER50 and click 'Apply'.",
    ],
    expectedBehaviour: "FREESHIP499 is accepted first. When BLADER50 is submitted, the system rejects it with 'Only one platform-wide coupon can be applied at a time (FREESHIP499). Remove it first.' After FREESHIP499 is removed, BLADER50 is accepted, confirming the slot frees up.",
    expectedUiState: "Step 5: error reads 'Only one platform-wide coupon can be applied at a time (FREESHIP499). Remove it first.' BLADER50 is absent from the list. Step 7: BLADER50 appears in the applied-coupons list with a discount of ₹500, no error shown.",
    endResult: "A reload of /checkout shows BLADER50 applied and FREESHIP499 absent.",
  },
  "checklist-buying-buying-coupons-coupon-stack-second-store-coupon-rejected": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type ARENA25 and click 'Apply'.",
      "In the coupon input field, type SEALED20 and click 'Apply'.",
    ],
    expectedBehaviour: "ARENA25 is accepted and stays in the applied-coupons list. When SEALED20 is submitted, the system rejects it with the message 'A coupon for this store is already applied (ARENA25). Remove it first.' ARENA25 is not removed or swapped.",
    expectedUiState: "ARENA25 remains in the applied-coupons list. An error message reads 'A coupon for this store is already applied (ARENA25). Remove it first.' SEALED20 does not appear in the applied-coupons list.",
    endResult: "A reload of /checkout shows ARENA25 still applied and SEALED20 absent.",
  },
  "checklist-buying-buying-coupons-coupon-stack-two-stores-plus-global": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) to the cart.",
      "Add a LetItRip Official item worth at least ₹500 to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type ARENA25 and click 'Apply'.",
      "In the coupon input field, type OFFICIAL10 and click 'Apply'.",
      "In the coupon input field, type FREESHIP499 and click 'Apply'.",
    ],
    expectedBehaviour: "All three coupons are accepted. Each appears in the applied-coupons list with its own discount amount. The Order Summary total decreases by the sum of the three discounts.",
    expectedUiState: "Three coupon rows appear above the coupon input: ARENA25 (showing its ₹ discount), OFFICIAL10 (showing its ₹ discount), and FREESHIP499. Each has a remove button. No error message is shown.",
    endResult: "Applied coupons persist across a reload of /checkout — all three codes are still listed with the same amounts.",
  },
  "checklist-buying-buying-coupons-coupon-store-scope-limited-to-its-own-items": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) to the cart.",
      "Add a LetItRip Official item to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "In the coupon input field, type ARENA25 and click 'Apply'.",
      "Note the discount amount shown next to ARENA25.",
      "Return to /cart, remove the LetItRip Official item, and go back to /checkout.",
      "Read the discount amount shown next to ARENA25 again and compare it to step 6.",
    ],
    expectedBehaviour: "The ARENA25 discount amount is calculated from Beyblade Arena items only. Adding or removing LetItRip Official items does not change the ARENA25 discount amount, because ARENA25 only covers Beyblade Arena items.",
    expectedUiState: "The ARENA25 discount row shows the same ₹ amount in both step 6 and step 8 (the LetItRip Official item had no effect on it). The cart total changes when the Official item is removed, but the ARENA25 discount line does not.",
    endResult: "A reload of /checkout still shows ARENA25 with the same discount amount tied to Beyblade Arena items only.",
  },
  "checklist-buying-buying-coupons-coupon-summary-total-matches-sum": {
    role: "buyer",
    startPage: "/cart",
    steps: [
      "Sign in as user-seto-kaiba (vivaan.kapoor@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) and product-beyblade-metal-storm-pegasus (₹1,299, Beyblade Arena) to the cart.",
      "Navigate to /checkout and complete Step 1 and Step 2.",
      "Apply ARENA25 and SEALED20.",
      "In the applied-coupons list, note the individual discount shown next to each coupon.",
      "In the Order Summary, find the total coupon discount line and the final Total line.",
      "Add the two individual coupon amounts together manually.",
    ],
    expectedBehaviour: "The sum of the individual coupon discount amounts equals the coupon discount line in the Order Summary. The Total equals Subtotal minus the coupon discount plus shipping plus fees plus GST.",
    expectedUiState: "Each coupon in the applied-coupons list shows its own '−₹X.XX off' amount. The Order Summary discount line equals the arithmetic sum of those amounts. The Total equals that formula.",
    endResult: "A reload of /checkout shows the same amounts, confirming they are persisted and not display artefacts.",
  },
  "checklist-buying-buying-coupons-coupon-usage-limit-increments-after-order": {
    // Authored as `buyer` starting on /admin/coupons, which audit R10 correctly
    // refused — a buyer is redirected before the case begins. The case is
    // admin-perspective throughout: its own first step signs in as the canTestAdmin
    // account precisely so the usage counter can be read. The substantive ambiguity
    // stays flagged below; only the incoherent role is corrected here.
    role: "admin",
    startPage: "/admin/coupons",
    steps: [
      "Sign in as user-claude-tester (claude-tester@letitrip.in / TempPass123!) who has canTestAdmin.",
      "Open /admin/coupons and find coupon-tester-sandbox-limited (code TESTERLIMITED). Note its current usage count.",
      "Add product-beyblade-burst-regalia-genesis (₹1,399, Beyblade Arena) to the cart, proceed to /checkout, complete all steps, apply TESTERLIMITED, and place the order.",
      "Return to /admin/coupons, find TESTERLIMITED, and check its usage count.",
      "Sign out. Sign in as a second buyer account (user-yugi-muto, rehan.sheikh@gmail.com / TempPass123!).",
      "Add product-beyblade-burst-regalia-genesis to the cart, proceed to /checkout, complete all steps, and attempt to apply TESTERLIMITED.",
    ],
    expectedBehaviour: "After step 3, the TESTERLIMITED usage count in /admin/coupons has increased by 1. In step 6, if TESTERLIMITED has perUserLimit 1 and user-seto-kaiba already used it, the second buyer (user-yugi-muto) who has not used it yet can still apply it. Confirm per-user limit enforcement by trying a second order from the same user.",
    expectedUiState: "Step 4: the usage count shown in /admin/coupons for TESTERLIMITED is one higher than in step 1. Step 6: TESTERLIMITED is either accepted for user-yugi-muto (different user) or rejected with a limit-reached message if that user has also used it.",
    endResult: "The usage count persists in /admin/coupons across page reloads.",
    needsReview: true,
    reviewNote: "TESTERLIMITED seed details (perUserLimit, totalLimit, currentUsage) need checking to confirm which specific limit scenario this case targets — per-user exhaustion vs global exhaustion.",
  },
  "checklist-buying-buying-coupons-coupon-wallet-apply-lands-on-checkout": {
    role: "buyer",
    startPage: "/user/coupons",
    steps: [
      "Sign in as a buyer who has at least one active claimed coupon in /user/coupons.",
      "Open /user/coupons.",
      "Find an active coupon in the list and click its 'Use' button.",
    ],
    expectedBehaviour: "Clicking 'Use' navigates the buyer to /checkout (possibly via /cart). The coupon code is pre-applied in the checkout coupon section. If the coupon cannot apply to the current cart, a reason is displayed rather than failing silently.",
    expectedUiState: "After navigation, /checkout shows the coupon code already listed in the applied-coupons section with its discount amount. If the cart is empty or the coupon is ineligible, an explanatory message is visible.",
    endResult: "The pre-applied coupon persists across a reload of /checkout.",
  },
};
