/*
 * WHY: Authored six-part procedures for the buying/product-detail checklist page.
 * WHAT: 23 case(s), keyed by full checklist id.
 *
 * Generated by `node tester/scripts/merge-authored.mjs --page buying/product-detail`, then
 * reviewed by a human before merge — the review is the gate, not the generation.
 * Hand edits are safe and expected: re-running the merge for this page replaces
 * the file, so re-author only when you mean to discard them.
 *
 * @tag domain:tester
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed-data/authored/index.ts
 * @tag sideEffects:none
 */

import type { AuthoredCase } from "./_types";

export const authored: Record<string, AuthoredCase> = {
  "checklist-buying-product-detail-auction-detail": {
    role: "guest",
    startPage: "/auctions/auction-tester-sandbox-cycle-1",
    steps: [
      "Open /auctions/auction-tester-sandbox-cycle-1.",
      "Wait 3 seconds without interacting.",
    ],
    expectedBehaviour: "The page renders a live auction with a ticking countdown. The seconds digit decrements in real time. Once the end time passes the countdown switches to 'Ended'.",
    expectedUiState: "The heading reads 'Test Auction — Ends in ~1h'. A countdown reading a format like '47m 6s' (or 'Xd Xh Xm Xs') appears directly above or adjacent to the 'Place a bid' button in the info panel. After 3 seconds the seconds digit has decreased. Current bid shows ₹15,000.00. Min increment shows ₹1,000.00. A 'Place a bid' button is present. No 'Add to Cart' button is present.",
    endResult: "Nothing persists — the countdown and bid state are read from the server on each load.",
  },
  "checklist-buying-product-detail-bundle-purchase": {
    role: "buyer",
    startPage: "/bundles/bundle-tester-sandbox",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /bundles/bundle-tester-sandbox.",
      "Click 'Buy now'.",
      "Complete the checkout flow (select address, choose payment method, confirm order).",
      "Open the resulting order detail page.",
    ],
    expectedBehaviour: "Checkout succeeds and a single order is created containing the bundle as one line item named 'Test Bundle', not two separate product lines.",
    expectedUiState: "The order detail page shows a single line item labelled 'Test Bundle' at ₹199.00. It does not show two separate rows for 'Test Gadget — Standard Listing #1' and 'Test Collectible — Standard Listing #2'. The 'What's included' detail may be shown beneath the bundle line, but the line item count is 1.",
    endResult: "Reloading the order page still shows the single 'Test Bundle' line item at ₹199.00.",
  },
  "checklist-buying-product-detail-classified-buy-request-pinned-to-price": {
    role: "buyer",
    startPage: "/classified/classified-beyblade-burst-collection-bengaluru",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /classified/classified-beyblade-burst-collection-bengaluru.",
      "Click 'Request to Buy'.",
      "Inspect the offer amount field in the form that opens.",
      "Using browser DevTools, change the value of the amount field to 3000 (below ₹4,500).",
      "Submit the form.",
    ],
    expectedBehaviour: "The offer amount field is pre-filled at ₹4,500 and is read-only — it cannot be changed by the user. If the value is force-changed via DevTools and submitted, the server rejects it with a clear error message.",
    expectedUiState: "The offer form shows an amount field pre-filled with 4500 (the listed price) that is disabled or read-only. The submit button is labelled 'Request to Buy' or similar. After submitting with the DevTools-modified value, an error message appears: 'This seller is not taking lower offers' or similar — the offer is not created.",
    endResult: "No offer record is created for the lower amount. Reloading the page still shows the 'Request to Buy' button with amount 4500.",
  },
  "checklist-buying-product-detail-classified-full-price-offer-accepted": {
    role: "buyer",
    startPage: "/classified/classified-beyblade-stadium-set",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /classified/classified-beyblade-stadium-set.",
      "Click 'Make Offer'.",
      "Enter 1200 in the offer amount field (exactly the listed price of ₹1,200).",
      "Submit the offer.",
    ],
    expectedBehaviour: "An offer at exactly the listed price on a classified listing is accepted by the server — not rejected. (On a standard /products/… listing the same amount would be rejected with 'use Add to Cart instead', but that rule does not apply to classifieds.)",
    expectedUiState: "After submitting the offer the form closes or shows a success state. A confirmation message appears (e.g. 'Offer sent' or 'Your offer has been submitted'). No error reading 'use Add to Cart instead' or 'Offer must be below the listed price' appears.",
    endResult: "An offer record is created at ₹1,200 for classified-beyblade-stadium-set. Reloading the page reflects the sent offer (e.g. 'Offer pending' state or the offer visible in the buyer's offers list).",
  },
  "checklist-buying-product-detail-classified-offer-is-the-purchase-path": {
    role: "guest",
    startPage: "/classified/classified-beyblade-stadium-set",
    steps: [
      "Open /classified/classified-beyblade-stadium-set.",
      "Note the purchase action button shown.",
      "Open /classified/classified-beyblade-burst-collection-bengaluru.",
      "Note the purchase action button shown.",
    ],
    expectedBehaviour: "Every classified listing shows either a 'Make Offer' or 'Request to Buy' button as the sole purchase action. No classified listing shows 'Add to Cart', 'Buy Now', or a 'Contact Seller' chat button. No listing has an empty purchase panel.",
    expectedUiState: "classified-beyblade-stadium-set: the purchase action button reads 'Make Offer'. A note below it reads 'Offer what you think it's worth — the seller can accept, decline or counter.' classified-beyblade-burst-collection-bengaluru: the purchase action button reads 'Request to Buy'. A note reads 'Send a request to buy and the seller will confirm.' Neither page shows 'Add to Cart' or 'Buy Now'. Neither page shows a blank or missing purchase panel.",
    endResult: "Nothing persists — read-only for a guest.",
  },
  "checklist-buying-product-detail-digitalcode-delivery": {
    role: "buyer",
    startPage: "/digital-codes/digitalcode-tester-sandbox-1",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /digital-codes/digitalcode-tester-sandbox-1.",
      "Click 'Buy Now'.",
      "Complete the checkout flow.",
      "Open the resulting order detail page.",
    ],
    expectedBehaviour: "After payment confirmation the digital code is automatically delivered to the buyer and is visible on the order page — no manual seller action is required.",
    expectedUiState: "The order detail page shows a digital code section with the actual code string (described as 'Disposable test code — redeem at test-redeem.example'). The code is visible and copyable. No 'Pending delivery' or 'Waiting for seller' status is shown.",
    endResult: "Reloading the order page still shows the delivered code.",
  },
  "checklist-buying-product-detail-grouped-listings-carousel-on-detail": {
    role: "guest",
    startPage: "/products/product-tester-standard-1",
    steps: [
      "Open /products/product-tester-standard-1.",
      "Scroll past the description tab and the related-items carousels to look for a horizontal themed carousel titled with the group's theme (e.g. 'From the same set' or the group name).",
      "Click one of the cards in the carousel.",
    ],
    expectedBehaviour: "A 'Grouped listings' themed carousel appears below the main content, distinct from the 'More in this category' / 'More by Brand' carousels. Clicking a card navigates to that item's own detail page.",
    expectedUiState: "A carousel section is visible with a theme-based heading (e.g. 'From the same set', 'Same character', or the group's display name). Each card shows a real product title and image tile — not a placeholder. Clicking a card lands on the corresponding product detail page (e.g. /products/product-tester-standard-2).",
    endResult: "Nothing persists — read-only navigation.",
  },
  "checklist-buying-product-detail-image-gallery": {
    role: "guest",
    startPage: "/auctions/auction-tester-sandbox-cycle-1",
    steps: [
      "Open /auctions/auction-tester-sandbox-cycle-1.",
      "Hard-reload the page (Ctrl+Shift+R / Cmd+Shift+R) three times.",
      "Click the main gallery image to open the lightbox.",
      "Click the rotate control (R button) in the lightbox toolbar.",
      "Click the zoom-in (+) control in the lightbox toolbar.",
      "Close the lightbox.",
    ],
    expectedBehaviour: "Every thumbnail renders its image on each reload without a broken-image icon. The lightbox opens when the main image is clicked, and the rotate and zoom controls respond.",
    expectedUiState: "After each reload every thumbnail in the strip below the main image shows a photo (not a broken icon or grey square). Lightbox: the image is visible, a toolbar with zoom (+/−) and rotate (R) buttons is present. After clicking rotate the image is rotated 90°. After clicking zoom-in the image is enlarged. Closing the lightbox returns to the product page.",
    endResult: "Nothing persists — no user state changes.",
  },
  "checklist-buying-product-detail-image-gallery-thumbnails-not-blank": {
    role: "guest",
    startPage: "/products/product-beyblade-burst-valkyrie",
    steps: [
      "Open /products/product-beyblade-burst-valkyrie.",
      "Look at the strip of small thumbnail buttons below the main gallery image.",
      "Click the second thumbnail button.",
      "Click the third thumbnail button.",
    ],
    expectedBehaviour: "Every mini thumbnail below the main image shows its own photo. Clicking a thumbnail swaps the main image above it.",
    expectedUiState: "The thumbnail strip shows 3 thumbnail buttons. Each thumbnail displays a distinct photo (not an empty bordered square or a grey box). The active thumbnail has an outline/highlight. After clicking the second thumbnail the main image above changes to that image. After clicking the third thumbnail the main image changes again.",
    endResult: "Nothing persists — no state changes.",
  },
  "checklist-buying-product-detail-live-item-detail": {
    role: "guest",
    startPage: "/live/live-tester-sandbox-1",
    steps: [
      "Open /live/live-tester-sandbox-1.",
    ],
    expectedBehaviour: "The live-item detail page loads and displays the livestream/video link correctly.",
    expectedUiState: "Heading reads 'Test Live Item — Golden Retriever Puppy'. A video thumbnail (labelled 'View video') is visible in the gallery thumbnail strip alongside 'View image 1'. Species/breed line reads 'Dog (Golden Retriever) · male · 6mo'. Price shows ₹1,500.00. Delivery restrictions are displayed. An 'Add to Cart' button is present.",
    endResult: "Nothing persists — read-only for a guest.",
  },
  "checklist-buying-product-detail-live-item-video-mandatory": {
    role: "seller",
    startPage: "/store/live/new",
    steps: [
      "Sign in as tyson@beybladearena.in (user-tyson-blader).",
      "Open /store/live/new (the 'List a live item' form).",
      "Fill in all required fields (title, species, price) but leave the Video field empty.",
      "Submit the form.",
      "Now attach a video file to the Video field and re-submit.",
      "After saving, open the public page /live/live-tester-sandbox-1.",
      "Click the 'View video' thumbnail in the gallery strip.",
      "Click the play button in the lightbox.",
    ],
    expectedBehaviour: "Submitting without a video is rejected with a clear validation error. After attaching a video the form saves successfully. On the public detail page the video plays correctly in theater mode. The video thumbnail (poster frame) carries the site watermark.",
    expectedUiState: "Without video: an inline error appears on or near the Video field reading something like 'A video is required for live items' or 'Video is required'. The form does not submit. With video: the form saves and redirects to the listing. Public page /live/live-tester-sandbox-1: the thumbnail strip shows 'View video' with a poster image that has a visible watermark overlay. Clicking it opens the lightbox and the video plays.",
    endResult: "The live listing is saved with the video attached. Reloading /live/live-tester-sandbox-1 shows the video thumbnail in the gallery.",
  },
  "checklist-buying-product-detail-preorder-detail": {
    role: "guest",
    startPage: "/pre-orders/preorder-tester-sandbox-1",
    steps: [
      "Open /pre-orders/preorder-tester-sandbox-1.",
    ],
    expectedBehaviour: "The pre-order detail page renders and shows the estimated ship date.",
    expectedUiState: "Heading reads 'Test Pre-order — Reserve Me!'. A label reading 'Estimated delivery:' is visible with a date value next to it. Price shows ₹299.00. A 'Reserve Now' button is present alongside a note about the 25% deposit (₹74.75). Status badge reads 'In Production'.",
    endResult: "Nothing persists — the page is read-only for a guest.",
  },
  "checklist-buying-product-detail-prizedraw-buy-reveal": {
    role: "buyer",
    startPage: "/prize-draws/prizedraw-tester-sandbox-1",
    steps: [
      "Sign in as rehan.sheikh@gmail.com (user-yugi-muto).",
      "Open /prize-draws/prizedraw-tester-sandbox-1.",
      "Click 'Buy now'.",
      "Complete payment for 1 entry at ₹50.00.",
      "After payment confirmation, open the order or prize-draw page to see the reveal state.",
    ],
    expectedBehaviour: "Payment is confirmed and one entry is assigned to the buyer. Because prizedraw-tester-sandbox-1 is in instant-reveal mode, a prize is immediately assigned and visible. If it were scheduled mode the entry would show a pending state until the draw closes.",
    expectedUiState: "After payment, the prize-draw page or the buyer's order page shows the assigned prize (e.g. 'Test Prize — Grand' or 'Test Prize — Runner-up'). The reveal is displayed immediately (instant mode). No 'pending' spinner or 'draw not yet closed' message appears for this fixture.",
    endResult: "Reloading the order page still shows the purchased entry and the revealed prize.",
  },
  "checklist-buying-product-detail-product-group-set-widget": {
    role: "guest",
    startPage: "/products/product-tester-standard-1",
    steps: [
      "Open /products/product-tester-standard-1.",
      "Scroll down to find the 'Part of / Parts in this group' collapsible panel.",
      "Click the expand arrow/triangle icon on the panel to open it.",
      "Click 'View whole group'.",
      "Open /products/product-tester-standard-2 and repeat: find and expand the same panel.",
      "Open /products/group-tester-sandbox-bundle and check for the panel listing its two members.",
    ],
    expectedBehaviour: "All three pages (group parent and both children) show the group panel. Expanding it reveals the other members. 'View whole group' opens a working modal or drawer.",
    expectedUiState: "The panel is labelled 'Part of / Parts in this group' (or similar). The expand control renders as a recognisable triangle or arrow glyph — not garbled text or a missing icon. After expanding, the panel lists both 'Test Gadget — Standard Listing #1' and 'Test Collectible — Standard Listing #2' with thumbnail images. Clicking 'View whole group' opens a modal or drawer showing both members.",
    endResult: "Nothing persists — read-only panel.",
  },
  "checklist-buying-product-detail-related-listings-sections": {
    role: "guest",
    startPage: "/products/product-beyblade-burst-valkyrie",
    steps: [
      "Open /products/product-beyblade-burst-valkyrie.",
      "Scroll past the description tab to the related-listings carousels below the main content.",
    ],
    expectedBehaviour: "Four separate carousels are rendered below the main product content, each populated with real items.",
    expectedUiState: "Four carousel sections are visible: 'More in this category' (other Beyblade Burst products), 'More by Beyblade' (other Beyblade-brand products), 'You might also like' (shared-tag products), and 'More from Beyblade Arena' (other store listings). Each section contains at least one product card with a real title, image tile, and price — not an empty or loading spinner.",
    endResult: "Nothing persists — read-only page.",
  },
  "checklist-buying-product-detail-seed-images-are-labelled-tiles": {
    role: "guest",
    startPage: "/products",
    steps: [
      "Open /products.",
      "Scroll through the first two rows of product cards.",
    ],
    expectedBehaviour: "Every product image is served from the seedPhoto() host and renders a tile that shows the item's own name as text.",
    expectedUiState: "Each card shows a distinct coloured tile with the product name rendered on it (e.g. 'Dranzer Phoenix', 'Beyblade Burst B-01 Valkyrie'). No card shows a broken-image icon (an icon with torn-paper or alt-text fallback). No two adjacent cards show an identical blank grey square.",
    endResult: "Nothing persists — the images are served on each page load.",
  },
  "checklist-buying-product-detail-standard-detail": {
    role: "guest",
    startPage: "/products/product-tester-standard-1",
    steps: [
      "Open /products/product-tester-standard-1.",
    ],
    expectedBehaviour: "The server returns a 200 response and renders the full product detail page for 'Test Gadget — Standard Listing #1'.",
    expectedUiState: "Heading reads 'Test Gadget — Standard Listing #1'. Price shows ₹199.00. Stock badge reads '✓ In Stock — only 10 left'. 'Buy Now', 'Add to Cart', and 'Add to Wishlist' buttons are visible (disabled for a guest). Category links 'Test Gadgets' and 'Tester Sandbox' and brand link 'TestBrand' appear below the heading. A description paragraph is present. 'Sold by Tester Sandbox Store' with a 'Visit Store →' link is shown.",
    endResult: "Nothing persists — the page is read-only for a guest.",
  },
  "checklist-buying-product-detail-tester-fixtures-hidden-from-the-public": {
    role: "guest",
    startPage: "/products",
    steps: [
      "Open /products in a private/incognito window (not signed in).",
      "Scan all visible product cards on the grid for any card whose title contains the word 'Tester' or whose URL slug contains 'tester'.",
      "Open a new tab and sign in as tester@letitrip.in (user-tester-qa).",
      "In the signed-in tab, open /products.",
      "Scan the grid again for cards whose title contains 'Tester' or whose slug contains 'tester'.",
    ],
    expectedBehaviour: "The public products endpoint filters out tester fixtures for anonymous callers, but includes them for users whose isTester flag is set.",
    expectedUiState: "Private-window grid: no card title contains 'Tester' and no card slug contains 'tester'. Signed-in grid: tester sandbox items (e.g. 'Test Gadget — Standard Listing #1', 'Test Prize Draw — Reveal Me!') are present in the results.",
    endResult: "Nothing persists. The visibility rule is enforced per-request by the server.",
  },
  "checklist-buying-product-detail-unreachable-image-degrades-to-placeholder": {
    role: "guest",
    startPage: "/products",
    steps: [
      "Open /api/media/ext?url=https%3A%2F%2Fexample.invalid%2Fx.png directly in a new browser tab.",
      "Open DevTools → Network, find the request for /api/media/ext?url=…, and inspect its response headers.",
    ],
    expectedBehaviour: "The endpoint returns an SVG placeholder tile (not a 502 error body). The response headers include X-Media-Placeholder: 1 and a short Cache-Control with max-age=60 or similar — not the long TTL used for real images.",
    expectedUiState: "The browser renders an SVG image reading 'Image unavailable' (not a broken-image icon). DevTools shows HTTP 200 (or a 2xx), Content-Type: image/svg+xml, the response header X-Media-Placeholder: 1 is present, and Cache-Control contains max-age=60.",
    endResult: "Nothing persists — this is a read-only endpoint response.",
  },
  "checklist-buying-product-detail-video-lightbox-fullscreen-sizing": {
    role: "guest",
    startPage: "/products/product-beyblade-burst-spryzen-video-demo",
    steps: [
      "Resize the browser window to 375 × 667 (mobile width).",
      "Open /products/product-beyblade-burst-spryzen-video-demo.",
      "Click the 'View video' thumbnail in the strip to open the video lightbox.",
      "Click the expand / Maximize button in the lightbox top bar.",
      "Exit fullscreen by pressing Escape.",
      "Resize the browser to 1280 × 800 (desktop width).",
      "Open /products/product-beyblade-burst-spryzen-video-demo again.",
      "Click the 'View video' thumbnail.",
      "Click the expand button again.",
    ],
    expectedBehaviour: "The lightbox enter-fullscreen button triggers the native Fullscreen API (not just a CSS zoom-reset). The icon swaps to a 'shrink' glyph while fullscreen is active. Pressing Escape exits fullscreen and the icon reverts. The video area has a defined minimum size on both mobile and desktop.",
    expectedUiState: "Mobile: video area is visibly taller than ~150 px — it is not a tiny collapsed box. Desktop: video area is larger still. After clicking expand the browser enters native fullscreen (no browser chrome visible, or the OS fullscreen indicator appears). The expand button icon changes to a shrink/collapse glyph. After Escape the button reverts to the expand icon and the video remains in the lightbox.",
    endResult: "Nothing persists — no state changes.",
  },
  "checklist-buying-product-detail-video-playback": {
    role: "guest",
    startPage: "/products/product-beyblade-original-dragoon-f-video-demo",
    steps: [
      "Open /products/product-beyblade-original-dragoon-f-video-demo.",
      "Click the 'View video' thumbnail button in the thumbnail strip (position 3/3).",
      "Click the play button on the video slide to open the lightbox / theater mode.",
      "Click the rotate (R) button in the lightbox toolbar.",
      "Click the zoom-in (+) button in the lightbox toolbar.",
      "Close the lightbox.",
    ],
    expectedBehaviour: "The video slide opens in theater mode with a native <video> element. The rotate and zoom controls apply to the video element. Closing the lightbox returns to the product page.",
    expectedUiState: "The thumbnail strip shows a 'View video' button with a play-badge poster. Clicking it displays the video in the main gallery area. Opening the lightbox shows the video playing (or paused ready to play) in a theater-mode overlay. The toolbar contains zoom (+/−) and rotate (R) buttons. Clicking rotate rotates the video 90°. Clicking zoom-in enlarges the video.",
    endResult: "Nothing persists — no state changes.",
  },
  "checklist-buying-product-detail-video-playback-youtube": {
    role: "guest",
    startPage: "/products/product-beyblade-metal-dark-bull-video-demo",
    steps: [
      "Open /products/product-beyblade-metal-dark-bull-video-demo.",
      "Click the 'View video' thumbnail in the thumbnail strip.",
      "Click the play button in the video slide / lightbox.",
    ],
    expectedBehaviour: "A YouTube-sourced video is rendered as a youtube-nocookie.com iframe embed, not a raw <video src>. The embedded player loads and plays the video.",
    expectedUiState: "The video slide shows a YouTube-style embed (iframe from youtube-nocookie.com visible in the DOM or DevTools). Clicking play starts the video. No error message reading 'No video with supported format' or 'Video format not supported' is shown.",
    endResult: "Nothing persists — no state changes.",
  },
  "checklist-buying-product-detail-video-real-file-upload": {
    role: "seller",
    startPage: "/store/products",
    steps: [
      "Sign in as tyson@beybladearena.in (user-tyson-blader).",
      "Open /store/products and click 'Edit' on any product (e.g. product-beyblade-burst-valkyrie).",
      "Scroll to the Video field and click the 'Upload' tab (not 'YouTube' or 'External URL').",
      "Upload a real .mp4 video file (any short clip under 50 MB).",
      "Wait for upload to complete.",
      "Open the public product detail page for that product in a new tab.",
      "Click the 'View video' thumbnail in the gallery strip.",
      "Return to the editor and remove the video.",
      "Upload a different .mp4 file.",
      "Save the product.",
    ],
    expectedBehaviour: "After upload a poster/thumbnail frame is auto-captured and displayed. The video plays correctly in the editor preview panel and in the public gallery lightbox. Re-uploading replaces the previous video without an error toast or orphaned files.",
    expectedUiState: "After upload the editor shows a poster thumbnail frame (a static frame from the video). The public product detail page shows a 'View video' thumbnail button in the strip. Clicking it plays the video in the lightbox. No error toast appears. After removing and re-uploading a different file no 'Failed to delete' or similar error appears.",
    endResult: "The product's video field points to the newly uploaded file after saving. Reloading the edit page shows the new video thumbnail.",
  },
};
