/**
 * Anime Figures — Products Seed Data
 * Dragon Ball Z · Naruto · One Piece · My Hero Academia
 * 22 general · 2 auctions · 2 pre-orders = 26 total
 * Seller: Anime Vault India (store-anime-vault-india)
 */

import { getDefaultCurrency } from "./seed-market-config";
import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

const AV = {
  sellerId: "user-anime-vault-owner",
  storeId: "anime-vault-india",
  sellerName: "Anime Vault India",
  sellerEmail: "animevault@letitrip.in",
} as const;

const AF_IMGS = [
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Nendoroid.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Anime_figure.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Action_figure_collection.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Collectible_figurine.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Anime_merchandise.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Figurine.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Plastic_figure.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Dragon_Ball_figure.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Nendoroid_figure.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/PVC_anime_figure.jpg?width=640",
];
const img = (seed: string) => {
  let h = 0; for (const c of seed) h = (h * 31 + c.charCodeAt(0)) & 0x7fff;
  return AF_IMGS[h % AF_IMGS.length];
};

export const animeFiguresSeedData: Partial<ProductDocument>[] = [

  // ── DRAGON BALL Z (8) ────────────────────────────────────────────────────

  {
    id: "product-av-dbz-goku-ultra-instinct-av-1",
    title: "Dragon Ball Z — Goku Ultra Instinct S.H.Figuarts Figure",
    description: "<p>S.H.Figuarts Goku in Ultra Instinct form — the pinnacle of Saiyan power. Includes 3 face plates, multiple hand parts, Ki effect parts, and a Kamehameha wave effect. Highly articulated with 28 points of movement. Premium Bandai release with metallic silver hair coating.</p>",
    slug: "product-dbz-goku-ultra-instinct-shf-figuarts",
    category: "category-anime-dbz",
    subcategory: "S.H.Figuarts",
    brand: "Dragon Ball Z",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage: img("dbz-goku-ultra-instinct"),
    images: [img("dbz-goku-ultra-instinct"), img("dbz-goku-ki-effect")],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
      thumbnailUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Nendoroid.jpg?width=640",
      duration: 15,
    },
    status: "published",
    ...AV,
    featured: true,
    tags: ["dragon ball z", "goku", "ultra instinct", "shf", "figuarts", "bandai"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~14 cm" },
      { name: "Articulation", value: "28 points" },
      { name: "Accessories", value: "3 face plates + Ki effects + Kamehameha" },
    ],
    features: ["28-point articulation", "Metallic silver hair", "Kamehameha effect", "3 swappable face plates"],
    shippingInfo: "Original Bandai box. Padded nationwide delivery.",
    returnPolicy: "10-day returns for factory-sealed items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.9,
    reviewCount: 67,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-av-dbz-vegeta-super-saiyan-av-2",
    title: "Dragon Ball Z — Vegeta Super Saiyan Blue S.H.Figuarts",
    description: "<p>S.H.Figuarts Vegeta in Super Saiyan Blue form — the Prince of all Saiyans at his finest. Includes signature scowl and smirk face plates, Ki blast effect, Final Flash effects. Dynamic pose potential with ball-jointed hips and double-jointed elbows.</p>",
    slug: "product-dbz-vegeta-super-saiyan-blue-shf",
    category: "category-anime-dbz",
    subcategory: "S.H.Figuarts",
    brand: "Dragon Ball Z",
    price: 4499,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 12,
    mainImage: img("dbz-vegeta-ssb"),
    images: [img("dbz-vegeta-ssb")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["dragon ball z", "vegeta", "super saiyan blue", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~14 cm" },
      { name: "Accessories", value: "3 face plates + Final Flash effects" },
    ],
    features: ["Final Flash effect parts", "Blue hair metallic finish", "Multiple hand parts", "Dynamic hip joints"],
    shippingInfo: "Original packaging. Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 44,
    createdAt: daysAgo(85),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-av-dbz-frieza-final-form-av-3",
    title: "Dragon Ball Z — Frieza Final Form S.H.Figuarts",
    description: "<p>S.H.Figuarts Frieza in his iconic Final Form — cold, calculated, and utterly ruthless. Includes Death Beam effect, energy disc effect, and multiple hand parts. Floating hover base included. Spot-on movie proportions with glossy white and purple finish.</p>",
    slug: "product-dbz-frieza-final-form-shf-figuarts",
    category: "category-anime-dbz",
    subcategory: "S.H.Figuarts",
    brand: "Dragon Ball Z",
    price: 3999,
    currency: _CURRENCY,
    stockQuantity: 18,
    availableQuantity: 16,
    mainImage: img("dbz-frieza-final"),
    images: [img("dbz-frieza-final")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["dragon ball z", "frieza", "final form", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~13 cm" },
      { name: "Accessories", value: "Death beam + energy disc effects + hover base" },
    ],
    features: ["Death Beam effect part", "Hover display base", "Glossy white/purple finish", "Energy disc accessory"],
    shippingInfo: "Original box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 31,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-av-dbz-gohan-beast-av-4",
    title: "Dragon Ball Z — Gohan Beast Form Figure (Dragon Ball Super: Super Hero)",
    description: "<p>Gohan Beast from Dragon Ball Super: Super Hero — the most powerful transformation of Gohan's hidden power fully unleashed. Red eyes, white-purple hair, and supreme power level. Includes energy blast effects and multiple face plates.</p>",
    slug: "product-dbz-gohan-beast-super-hero-figure",
    category: "category-anime-dbz",
    subcategory: "Figure",
    brand: "Dragon Ball Z",
    price: 3599,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("dbz-gohan-beast"),
    images: [img("dbz-gohan-beast")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["dragon ball z", "gohan", "beast", "super hero", "figure"],
    specifications: [
      { name: "Height", value: "~15 cm" },
      { name: "Accessories", value: "Energy effects + face plates" },
    ],
    features: ["Beast form exclusive deco", "Red eyes effect", "Energy blast parts", "Display base"],
    shippingInfo: "Original packaging. Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 22,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-av-dbz-broly-dxf-av-5",
    title: "Dragon Ball Z — Broly Legendary Super Saiyan DXF Figure",
    description: "<p>Broly Legendary Super Saiyan — the DXF premium statue from Banpresto. Dynamic stomp pose with massive muscle detail. Glow-in-the-dark Broly Ki aura elements. 24 cm tall centrepiece figure. Perfect for collectors who want scale over articulation.</p>",
    slug: "product-dbz-broly-legendary-ssj-dxf-banpresto",
    category: "category-anime-dbz",
    subcategory: "DXF",
    brand: "Dragon Ball Z",
    price: 2999,
    currency: _CURRENCY,
    stockQuantity: 25,
    availableQuantity: 22,
    mainImage: img("dbz-broly-dxf"),
    images: [img("dbz-broly-dxf"), img("dbz-broly-dxf-side")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["dragon ball z", "broly", "legendary", "dxf", "banpresto", "statue"],
    specifications: [
      { name: "Series", value: "DXF" },
      { name: "Height", value: "~24 cm" },
      { name: "Type", value: "Statue (non-articulated)" },
    ],
    features: ["24 cm tall statue", "Glow-in-dark Ki aura", "Dynamic stomp pose", "Banpresto quality"],
    shippingInfo: "Padded collector box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 55,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-av-dbz-cell-perfect-av-6",
    title: "Dragon Ball Z — Cell Perfect Form S.H.Figuarts",
    description: "<p>S.H.Figuarts Cell in his perfect form — bio-android perfection. Includes taunting, screaming, and power-up face plates. Energy absorption effects and tail parts. Signature green and black deco with detailed bio-organic sculpt.</p>",
    slug: "product-dbz-cell-perfect-form-shf-figuarts",
    category: "category-anime-dbz",
    subcategory: "S.H.Figuarts",
    brand: "Dragon Ball Z",
    price: 4299,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("dbz-cell-perfect"),
    images: [img("dbz-cell-perfect")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["dragon ball z", "cell", "perfect form", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~17 cm" },
      { name: "Accessories", value: "3 face plates + energy absorption effects + tail parts" },
    ],
    features: ["Perfect form deco", "Absorption tail part", "3 expression face plates", "Energy effects"],
    shippingInfo: "Original Bandai box. Padded nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 28,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-av-dbz-beerus-av-7",
    title: "Dragon Ball Z — Beerus God of Destruction S.H.Figuarts",
    description: "<p>S.H.Figuarts Beerus — the God of Destruction in feline form. Delicate sculpt captures his slender yet powerful physique. Includes open hand, pointing hand, and purple energy ball effects. Long flexible tail part. Sitting pose compatible accessory base.</p>",
    slug: "product-dbz-beerus-god-of-destruction-shf",
    category: "category-anime-dbz",
    subcategory: "S.H.Figuarts",
    brand: "Dragon Ball Z",
    price: 3999,
    currency: _CURRENCY,
    stockQuantity: 14,
    availableQuantity: 11,
    mainImage: img("dbz-beerus-gd"),
    images: [img("dbz-beerus-gd")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["dragon ball z", "beerus", "god of destruction", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~16 cm" },
      { name: "Accessories", value: "Energy ball effects + flexible tail" },
    ],
    features: ["Flexible rubber tail", "Purple energy ball effects", "Multiple hand options", "Hakai energy accessory"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 19,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(7),
  },

  {
    id: "product-av-dbz-piccolo-av-8",
    title: "Dragon Ball Z — Piccolo Namekian Warrior S.H.Figuarts",
    description: "<p>S.H.Figuarts Piccolo — the Namekian warrior who became Gohan's mentor. Special beam cannon effect, removable cape and turban, multiple face plates with the iconic narrow-eyed expression. Earring detail and accurate green-purple colour scheme.</p>",
    slug: "product-dbz-piccolo-namekian-warrior-shf",
    category: "category-anime-dbz",
    subcategory: "S.H.Figuarts",
    brand: "Dragon Ball Z",
    price: 3799,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 9,
    mainImage: img("dbz-piccolo-shf"),
    images: [img("dbz-piccolo-shf")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["dragon ball z", "piccolo", "namekian", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~16 cm" },
      { name: "Accessories", value: "Special Beam Cannon effect + removable cape" },
    ],
    features: ["Removable cape and turban", "Special Beam Cannon effect", "3 face plates", "Antenna detail"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 24,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },

  // ── NARUTO (5) ───────────────────────────────────────────────────────────

  {
    id: "product-av-naruto-uzumaki-sage-mode-av-9",
    title: "Naruto Uzumaki — Sage Mode S.H.Figuarts",
    description: "<p>S.H.Figuarts Naruto in Sage Mode — Frog Sage marks fully activated. Includes Rasengan effect, shuriken, multiple hand parts, and 3 face plates. Toad belt rope accessory removable. Accurate orange and black Sage outfit with detailed toad summoning markings.</p>",
    slug: "product-naruto-uzumaki-sage-mode-shf-figuarts",
    category: "category-anime-naruto",
    subcategory: "S.H.Figuarts",
    brand: "Naruto",
    price: 3999,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 17,
    mainImage: img("naruto-sage-mode-shf"),
    images: [img("naruto-sage-mode-shf"), img("naruto-sage-rasengan")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["naruto", "sage mode", "uzumaki", "shf", "figuarts", "rasengan"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~14.5 cm" },
      { name: "Accessories", value: "Rasengan effect + shuriken + 3 face plates" },
    ],
    features: ["Rasengan energy effect", "Sage marks deco", "Shuriken accessories", "Frog toad belt rope"],
    shippingInfo: "Original Bandai box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.8,
    reviewCount: 43,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-av-naruto-sasuke-rinnegan-av-10",
    title: "Naruto — Sasuke Uchiha Rinnegan S.H.Figuarts",
    description: "<p>S.H.Figuarts Sasuke with Rinnegan — the avenger in his most powerful form. Includes Chidori effect, sword Kusanagi, Rinnegan swap eye parts, and 3 face plates. Eternal Mangekyo Sharingan detail. Blue Void Chidori version included.</p>",
    slug: "product-naruto-sasuke-rinnegan-shf-figuarts",
    category: "category-anime-naruto",
    subcategory: "S.H.Figuarts",
    brand: "Naruto",
    price: 4299,
    currency: _CURRENCY,
    stockQuantity: 16,
    availableQuantity: 13,
    mainImage: img("naruto-sasuke-rinnegan"),
    images: [img("naruto-sasuke-rinnegan")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["naruto", "sasuke", "rinnegan", "sharingan", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~14.5 cm" },
      { name: "Accessories", value: "Chidori + Kusanagi sword + eye swap parts" },
    ],
    features: ["Kusanagi sword accessory", "Rinnegan eye swap parts", "Blue Void Chidori effect", "Eternal Mangekyo deco"],
    shippingInfo: "Original Bandai box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 38,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-av-naruto-kakashi-sharingan-av-11",
    title: "Naruto — Kakashi Hatake Sharingan Eye S.H.Figuarts",
    description: "<p>S.H.Figuarts Kakashi Hatake — the Copy Ninja with Sharingan eye revealed. Includes headband up and down versions, Lightning Blade effect, Kunai accessories, and 3 face plates including his lazy expression and serious battle expression.</p>",
    slug: "product-naruto-kakashi-sharingan-shf-figuarts",
    category: "category-anime-naruto",
    subcategory: "S.H.Figuarts",
    brand: "Naruto",
    price: 3799,
    currency: _CURRENCY,
    stockQuantity: 14,
    availableQuantity: 11,
    mainImage: img("naruto-kakashi-shf"),
    images: [img("naruto-kakashi-shf")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["naruto", "kakashi", "sharingan", "copy ninja", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~15 cm" },
      { name: "Accessories", value: "Lightning Blade + Kunai + headband variants" },
    ],
    features: ["Swappable headband (revealed/hidden Sharingan)", "Lightning Blade effect", "Kunai accessories", "Lazy and battle face plates"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 29,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-av-naruto-itachi-anbu-av-12",
    title: "Naruto — Itachi Uchiha ANBU Black Ops Figure",
    description: "<p>Itachi Uchiha in his ANBU Black Ops outfit — the prodigious Uchiha as a child ninja. Crow familiar accessories, Mangekyo Sharingan genjutsu effect, and ANBU mask. Standard and sans-mask head parts. Kunai and shuriken pouch detail.</p>",
    slug: "product-naruto-itachi-uchiha-anbu-figure",
    category: "category-anime-naruto",
    subcategory: "Figure",
    brand: "Naruto",
    price: 3299,
    currency: _CURRENCY,
    stockQuantity: 18,
    availableQuantity: 14,
    mainImage: img("naruto-itachi-anbu"),
    images: [img("naruto-itachi-anbu")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["naruto", "itachi", "anbu", "uchiha", "mangekyo", "figure"],
    specifications: [
      { name: "Height", value: "~16 cm" },
      { name: "Accessories", value: "ANBU mask + crow familiar + Mangekyo effect" },
    ],
    features: ["ANBU mask on/off", "Crow familiar figure", "Mangekyo Sharingan effect", "Twin blade weapons"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 52,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-av-naruto-rock-lee-gates-av-13",
    title: "Naruto — Rock Lee 8 Inner Gates Figure",
    description: "<p>Rock Lee in his famous 8 Inner Gates state — red steaming skin, torn suit, and ultimate power. Includes steam effect parts, multiple fist configurations, and a base recreating the sand arena. Bandai Ichibansho premium sculpt.</p>",
    slug: "product-naruto-rock-lee-8-gates-ichibansho",
    category: "category-anime-naruto",
    subcategory: "Ichibansho",
    brand: "Naruto",
    price: 2799,
    currency: _CURRENCY,
    stockQuantity: 16,
    availableQuantity: 13,
    mainImage: img("naruto-rock-lee-gates"),
    images: [img("naruto-rock-lee-gates")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["naruto", "rock lee", "8 gates", "ichibansho", "bandai"],
    specifications: [
      { name: "Series", value: "Ichibansho" },
      { name: "Height", value: "~17 cm" },
      { name: "Accessories", value: "Steam effects + arena base" },
    ],
    features: ["8 Gates red steam effects", "Arena base", "Torn suit deco", "Premium Ichibansho sculpt"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 17,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(7),
  },

  // ── ONE PIECE (5) ────────────────────────────────────────────────────────

  {
    id: "product-av-op-luffy-gear5-av-14",
    title: "One Piece — Luffy Gear 5 Nika S.H.Figuarts",
    description: "<p>S.H.Figuarts Monkey D. Luffy in Gear 5 Nika form — the Sun God awakened. White hair, hyper-expressive cartoon face plates, cloud accessory, and giant inflated fist effects. The most playful and expressive figure in the Figuarts line. Must-have for One Piece fans.</p>",
    slug: "product-one-piece-luffy-gear5-nika-shf-figuarts",
    category: "category-anime-onepiece",
    subcategory: "S.H.Figuarts",
    brand: "One Piece",
    price: 5499,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 12,
    mainImage: img("onepiece-luffy-gear5"),
    images: [img("onepiece-luffy-gear5"), img("onepiece-luffy-gear5-fist")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["one piece", "luffy", "gear 5", "nika", "sun god", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~15 cm" },
      { name: "Accessories", value: "5 face plates + giant fist + cloud effects" },
    ],
    features: ["Gear 5 white hair", "5 hyper-expressive face plates", "Giant inflated fist effect", "Cloud display base"],
    shippingInfo: "Original Bandai box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(25),
    avgRating: 4.9,
    reviewCount: 78,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-av-op-zoro-enma-av-15",
    title: "One Piece — Roronoa Zoro Three Sword Style Enma Figure",
    description: "<p>Roronoa Zoro wielding Enma — post-Wano arc three-sword style stance. Dramatic three-blade draw pose with Enma's black blade effect. Haramaki detail and scar over eye. Ichibansho Wano Arc release. Premium sculptwork from Bandai Spirits.</p>",
    slug: "product-one-piece-zoro-three-sword-enma-wano",
    category: "category-anime-onepiece",
    subcategory: "Ichibansho",
    brand: "One Piece",
    price: 3799,
    currency: _CURRENCY,
    stockQuantity: 18,
    availableQuantity: 15,
    mainImage: img("onepiece-zoro-enma"),
    images: [img("onepiece-zoro-enma")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["one piece", "zoro", "enma", "three sword style", "wano", "ichibansho"],
    specifications: [
      { name: "Series", value: "Ichibansho Wano" },
      { name: "Height", value: "~19 cm" },
      { name: "Accessories", value: "Enma black blade + haramaki" },
    ],
    features: ["Enma black blade effect", "Three-sword draw pose", "Wano arc outfit", "Scar eye detail"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 45,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-av-op-nami-wano-av-16",
    title: "One Piece — Nami Wano Arc DXF Figure",
    description: "<p>Nami in her Wano Country outfit — the Navigator of the Straw Hats in stunning kimono style. DXF Figure from Banpresto. Clima-Tact weapon pose. Dynamic hair and flower hair accessories. 18 cm premium figure with weather effect diorama base.</p>",
    slug: "product-one-piece-nami-wano-dxf-banpresto",
    category: "category-anime-onepiece",
    subcategory: "DXF",
    brand: "One Piece",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 22,
    availableQuantity: 20,
    mainImage: img("onepiece-nami-wano"),
    images: [img("onepiece-nami-wano")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["one piece", "nami", "wano", "dxf", "banpresto", "kimono"],
    specifications: [
      { name: "Series", value: "DXF" },
      { name: "Height", value: "~18 cm" },
    ],
    features: ["Wano kimono deco", "Clima-Tact pose", "Weather effect base", "Detailed flower accessories"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 29,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-av-op-ace-mera-av-17",
    title: "One Piece — Portgas D. Ace Fire Fist Figure",
    description: "<p>Portgas D. Ace — Fire Fist flaming punch pose from Marineford arc. Detailed flame effect from wrist to elbow. Freckle detail, ASCE tattoo on arm, and iconic open jacket. Bandai Ichibansho premium quality. Tribute figure to the beloved fallen Whitebeard commander.</p>",
    slug: "product-one-piece-ace-fire-fist-marineford-figure",
    category: "category-anime-onepiece",
    subcategory: "Ichibansho",
    brand: "One Piece",
    price: 3299,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 17,
    mainImage: img("onepiece-ace-fist"),
    images: [img("onepiece-ace-fist")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["one piece", "ace", "fire fist", "portgas", "marineford", "figure"],
    specifications: [
      { name: "Series", value: "Ichibansho" },
      { name: "Height", value: "~18 cm" },
      { name: "Accessories", value: "Flame effects + ASCE tattoo detail" },
    ],
    features: ["Fire Fist flame effects", "ASCE tattoo detail", "Open jacket Marineford deco", "Freckle sculpt detail"],
    shippingInfo: "Original packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 61,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-av-op-shanks-haki-av-18",
    title: "One Piece — Red-Haired Shanks Conqueror Haki Figure",
    description: "<p>Red-Haired Shanks unleashing Conqueror Haki — the One Piece protagonist's idol and the most feared Yonko. Haki aura effect envelops him. Black lightning effects, iconic straw hat, and missing left arm. Premium collector's edition with diorama base.</p>",
    slug: "product-one-piece-shanks-conqueror-haki-figure",
    category: "category-anime-onepiece",
    subcategory: "Figure",
    brand: "One Piece",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("onepiece-shanks-haki"),
    images: [img("onepiece-shanks-haki")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["one piece", "shanks", "conqueror haki", "yonko", "figure", "premium"],
    specifications: [
      { name: "Height", value: "~22 cm" },
      { name: "Accessories", value: "Haki lightning effects + diorama base" },
    ],
    features: ["Conqueror Haki black lightning effects", "Iconic straw hat", "Missing arm sculpt accuracy", "Premium diorama base"],
    shippingInfo: "Padded collector box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 149,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(15),
    avgRating: 4.9,
    reviewCount: 34,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(2),
  },

  // ── MY HERO ACADEMIA (4) ─────────────────────────────────────────────────

  {
    id: "product-av-mha-deku-fullcowl-av-19",
    title: "My Hero Academia — Izuku Midoriya Full Cowl S.H.Figuarts",
    description: "<p>S.H.Figuarts Deku in Full Cowl — One For All coursing through his body at full power. Lightning/electric effect parts, Delaware Smash air burst effect, and multiple face plates. Costume Beta outfit with reinforced arms. Essential for any MHA collection.</p>",
    slug: "product-mha-deku-midoriya-full-cowl-shf-figuarts",
    category: "category-anime-mha",
    subcategory: "S.H.Figuarts",
    brand: "My Hero Academia",
    price: 3999,
    currency: _CURRENCY,
    stockQuantity: 18,
    availableQuantity: 15,
    mainImage: img("mha-deku-fullcowl"),
    images: [img("mha-deku-fullcowl"), img("mha-deku-smash")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["my hero academia", "deku", "midoriya", "full cowl", "shf", "figuarts", "one for all"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~14 cm" },
      { name: "Accessories", value: "OFA lightning + Delaware Smash + 3 face plates" },
    ],
    features: ["One For All lightning effects", "Delaware Smash air burst", "Costume Beta accuracy", "3 face plates"],
    shippingInfo: "Original Bandai box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 36,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-av-mha-bakugo-howitzer-av-20",
    title: "My Hero Academia — Katsuki Bakugo Howitzer Impact S.H.Figuarts",
    description: "<p>S.H.Figuarts Bakugo in his Howitzer Impact pose — spinning explosion attack. Explosion effect parts around both arms, angry and grinning face plates, and his iconic grenade-style gauntlets. The most dynamic MHA figure for capturing his combat style.</p>",
    slug: "product-mha-bakugo-howitzer-impact-shf-figuarts",
    category: "category-anime-mha",
    subcategory: "S.H.Figuarts",
    brand: "My Hero Academia",
    price: 4299,
    currency: _CURRENCY,
    stockQuantity: 14,
    availableQuantity: 11,
    mainImage: img("mha-bakugo-howitzer"),
    images: [img("mha-bakugo-howitzer")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["my hero academia", "bakugo", "howitzer impact", "explosion", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~14 cm" },
      { name: "Accessories", value: "Explosion effects + gauntlets + 3 face plates" },
    ],
    features: ["Howitzer explosion effects", "Grenade gauntlets", "Spinning attack pose", "Angry + grinning face plates"],
    shippingInfo: "Original Bandai box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 48,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-av-mha-allmight-toshinori-av-21",
    title: "My Hero Academia — All Might Toshinori True Form Statue",
    description: "<p>All Might in his true form — Toshinori Yagi deflated, frail, yet still smiling. Rare collector's resin statue capturing his iconic weakened state. 20 cm premium cold-cast porcelain. Limited edition with numbered base. Symbol of Peace even in weakness.</p>",
    slug: "product-mha-all-might-toshinori-true-form-statue",
    category: "category-anime-mha",
    subcategory: "Statue",
    brand: "My Hero Academia",
    price: 5999,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 6,
    mainImage: img("mha-allmight-true"),
    images: [img("mha-allmight-true")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["my hero academia", "all might", "toshinori", "true form", "statue", "limited"],
    specifications: [
      { name: "Material", value: "Cold-cast porcelain resin" },
      { name: "Height", value: "~20 cm" },
      { name: "Edition", value: "Limited numbered" },
    ],
    features: ["Limited numbered edition", "Cold-cast porcelain", "True form deflated deco", "Iconic smile sculpt"],
    shippingInfo: "Padded collector box. Insured nationwide.",
    returnPolicy: "10-day returns for factory-sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 199,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.9,
    reviewCount: 23,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-av-mha-todoroki-half-cold-av-22",
    title: "My Hero Academia — Shoto Todoroki Half-Cold Half-Hot S.H.Figuarts",
    description: "<p>S.H.Figuarts Todoroki — left side fire, right side ice. Dual elemental effects for both sides, multiple stern and determined face plates, and ice floor base. Signature half-and-half hair with scar detail. The most visually striking MHA figure available.</p>",
    slug: "product-mha-todoroki-half-cold-hot-shf-figuarts",
    category: "category-anime-mha",
    subcategory: "S.H.Figuarts",
    brand: "My Hero Academia",
    price: 4499,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("mha-todoroki-halfhot"),
    images: [img("mha-todoroki-halfhot")],
    status: "published",
    ...AV,
    featured: false,
    tags: ["my hero academia", "todoroki", "half cold half hot", "fire ice", "shf", "figuarts"],
    specifications: [
      { name: "Series", value: "S.H.Figuarts" },
      { name: "Height", value: "~14.5 cm" },
      { name: "Accessories", value: "Fire + ice effects + ice floor base + 3 face plates" },
    ],
    features: ["Fire and ice dual effects", "Ice floor display base", "Half-and-half hair accuracy", "Scar facial detail"],
    shippingInfo: "Original Bandai box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 41,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(4),
  },

  // ── AUCTION (2) ───────────────────────────────────────────────────────────

  {
    id: "auction-av-dbz-goku-first-edition-graded-av-1",
    title: "AUCTION — Dragon Ball Z Goku First Edition Box Art Figure (1989 Vintage)",
    description: "<p>Vintage 1989 Bandai Dragon Ball Z Goku figure with original box art. First edition Japanese release. Complete with original accessories and instruction sheet. Figure is in C8 condition — light play wear. Box is C7 with shelf wear but intact. Extremely rare in this condition. Certificate from Anime Heritage Japan.</p>",
    slug: "auction-dbz-goku-1989-vintage-bandai-first-ed",
    category: "category-anime-dbz",
    subcategory: "Vintage",
    brand: "Dragon Ball Z",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("dbz-goku-vintage-1989"),
    images: [img("dbz-goku-vintage-1989"), img("dbz-goku-vintage-box"), img("dbz-goku-vintage-accessories")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["dragon ball z", "goku", "vintage", "1989", "auction", "first edition", "bandai"],
    specifications: [
      { name: "Year", value: "1989 (Original Release)" },
      { name: "Series", value: "Dragon Ball Z First Edition" },
      { name: "Figure Condition", value: "C8" },
      { name: "Box Condition", value: "C7" },
      { name: "Authentication", value: "Anime Heritage Japan certified" },
    ],
    features: ["1989 original release", "Complete with accessories", "Original instruction sheet", "Anime Heritage Japan certificate"],
    shippingInfo: "White-glove insured shipping. Museum protective casing.",
    returnPolicy: "No returns on auction wins.",
    condition: "used",
    insurance: true,
    insuranceCost: 999,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(10),
    startingBid: 24999,
    currentBid: 38000,
    bidCount: 14,
    reservePrice: 45000,
    buyNowPrice: 89999,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionOriginalEndDate: daysAhead(10),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(10),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },

  {
    id: "auction-av-onepiece-luffy-gear5-first-print-av-2",
    title: "AUCTION — One Piece Luffy Gear 5 First Print Prototype Sample Figure",
    description: "<p>Extremely rare One Piece Luffy Gear 5 Figuarts first print prototype sample — production test shot before finalised mass production colour. Predominantly white unpainted with prototype blue tack marks. Sealed in original Bandai internal sample bag. Unique and unrepeatable collectible.</p>",
    slug: "auction-onepiece-luffy-gear5-prototype-sample",
    category: "category-anime-onepiece",
    subcategory: "Prototype",
    brand: "One Piece",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("onepiece-luffy-gear5-proto"),
    images: [img("onepiece-luffy-gear5-proto"), img("onepiece-luffy-proto-bag")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["one piece", "luffy", "gear 5", "prototype", "sample", "auction", "rare"],
    specifications: [
      { name: "Type", value: "Production prototype sample" },
      { name: "Condition", value: "Sealed in Bandai internal bag" },
      { name: "Rarity", value: "One of a kind" },
    ],
    features: ["One-of-a-kind prototype", "Sealed in Bandai internal sample bag", "Pre-production colour shot", "Unrepeatable collector item"],
    shippingInfo: "Insured white-glove shipping.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 1499,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(7),
    startingBid: 9999,
    currentBid: 22000,
    bidCount: 9,
    reservePrice: 25000,
    buyNowPrice: 59999,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionOriginalEndDate: daysAhead(7),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(7),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },

  // ── PRE-ORDER (2) ─────────────────────────────────────────────────────────

  {
    id: "preorder-av-dbz-goku-ultra-ego-2026-av-1",
    title: "PRE-ORDER — Dragon Ball Z Goku Ultra Ego 2026 Premium Statue",
    description: "<p>Pre-order the upcoming Goku Ultra Ego premium statue from Tsume Art — 1:6 scale, 35 cm tall, cold-cast resin with hand-painted finish. Limited to 999 pieces worldwide. Only 50 India-allocated units. Expected delivery Q3 2026. Pay 20% now, rest on dispatch.</p>",
    slug: "preorder-dbz-goku-ultra-ego-tsume-art-2026",
    category: "category-anime-dbz",
    subcategory: "Premium Statue",
    brand: "Dragon Ball Z",
    price: 24999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 41,
    mainImage: img("dbz-goku-ultra-ego-preorder"),
    images: [img("dbz-goku-ultra-ego-preorder")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["dragon ball z", "goku", "ultra ego", "tsume art", "pre-order", "2026", "premium statue"],
    specifications: [
      { name: "Scale", value: "1:6" },
      { name: "Height", value: "~35 cm" },
      { name: "Material", value: "Cold-cast resin, hand-painted" },
      { name: "World Limit", value: "999 pieces" },
      { name: "India Allocation", value: "50 units" },
    ],
    features: ["Tsume Art 1:6 scale", "Hand-painted finish", "999 worldwide limited", "35 cm centrepiece"],
    shippingInfo: "Special collector casing. Insured dispatch on Q3 2026 release.",
    returnPolicy: "Pre-orders: cancel before dispatch date. 20% deposit non-refundable.",
    condition: "new",
    insurance: true,
    insuranceCost: 699,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(180),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(90),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },

  {
    id: "preorder-av-mha-allmight-golden-age-2026-av-2",
    title: "PRE-ORDER — My Hero Academia All Might Golden Age Box Set (2026)",
    description: "<p>Reserve the upcoming My Hero Academia All Might Golden Age Box Set — 5 figures spanning his life from young Toshinori to the Symbol of Peace, plus the deflated retirement state. Includes collector artbook and muscle fibres diorama. India pre-order exclusive bonus: All Might enamel pin set.</p>",
    slug: "preorder-mha-all-might-golden-age-box-set-2026",
    category: "category-anime-mha",
    subcategory: "Box Set",
    brand: "My Hero Academia",
    price: 12999,
    currency: _CURRENCY,
    stockQuantity: 30,
    availableQuantity: 24,
    mainImage: img("mha-allmight-golden-age-preorder"),
    images: [img("mha-allmight-golden-age-preorder")],
    status: "published",
    ...AV,
    featured: true,
    tags: ["my hero academia", "all might", "golden age", "box set", "pre-order", "2026", "exclusive"],
    specifications: [
      { name: "Contents", value: "5 figures + artbook + diorama base" },
      { name: "India Bonus", value: "Enamel pin set" },
      { name: "Expected", value: "Q2 2026" },
    ],
    features: ["5-figure life timeline set", "India-exclusive enamel pin bonus", "Collector artbook", "Muscle fibres diorama"],
    shippingInfo: "Special collector packaging. Insured dispatch on Q2 2026 release.",
    returnPolicy: "Pre-orders: cancel before dispatch. Deposit non-refundable.",
    condition: "new",
    insurance: true,
    insuranceCost: 399,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(150),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(75),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
];