/**
 * Beyblade Burst — Products Seed Data
 * 20 general · 2 auctions · 2 pre-orders = 24 total
 * Seller: Bladers Paradise (store-bladers-paradise)
 */

import { getDefaultCurrency } from "./seed-market-config";
import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

const BP = {
  sellerId: "user-bladers-paradise",
  storeId: "store-bladers-paradise",
  sellerName: "Bladers Paradise",
  sellerEmail: "bladers@letitrip.in",
} as const;

const img = (seed: string) => `https://picsum.photos/seed/${seed}/600/600`;

export const beybladeProductsSeedData: Partial<ProductDocument>[] = [

  // ── ATTACK TYPE (6) ──────────────────────────────────────────────────────

  {
    id: "product-bb-valtryek-v5-attack-bp-1",
    title: "Beyblade Burst — Valtryek V5 Attack Type (Rise)",
    description: "<p>Valtryek V5 is one of the most powerful attack-type Beyblades in the Burst Rise series. The five-bladed layer delivers devastating attacks with high burst resistance. Includes launcher and ripcord.</p>",
    slug: "bb-valtryek-v5-attack-rise",
    category: "category-bb-attack-type",
    subcategory: "Burst Rise",
    brand: "Beyblade Burst",
    price: 1299,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 17,
    mainImage: img("bb-valtryek-v5"),
    images: [img("bb-valtryek-v5"), img("bb-valtryek-v5-2")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "valtryek", "v5", "attack", "rise"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Rise" },
      { name: "Type", value: "Attack" },
      { name: "Layer", value: "Victory Valtryek V5" },
      { name: "Forge Disc", value: "10 Glaive" },
      { name: "Performance Tip", value: "Volcanic" },
    ],
    features: ["High burst resistance", "Five-blade attack layer", "Includes launcher + ripcord"],
    shippingInfo: "Padded box. Nationwide delivery.",
    returnPolicy: "7-day returns for unopened items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.7,
    reviewCount: 28,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-bb-spriggan-requiem-attack-bp-2",
    title: "Beyblade Burst — Spriggan Requiem Attack/Stamina (Turbo)",
    description: "<p>Spriggan Requiem from Beyblade Burst Turbo — the mythical dual-spin top that dominated every competition in its era. Spin right for Attack, left for Stamina. Legendary performance.</p>",
    slug: "bb-spriggan-requiem-turbo-attack-stamina",
    category: "category-bb-attack-type",
    subcategory: "Burst Turbo",
    brand: "Beyblade Burst",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 6,
    mainImage: img("bb-spriggan-requiem"),
    images: [img("bb-spriggan-requiem")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "spriggan", "requiem", "turbo", "dual spin", "legendary"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Turbo" },
      { name: "Type", value: "Attack / Stamina (Dual Spin)" },
      { name: "Layer", value: "Spriggan Requiem" },
      { name: "Special Feature", value: "Dual-spin (right/left)" },
    ],
    features: ["Dual spin capability", "Attack + Stamina modes", "Legendary series bey"],
    shippingInfo: "Premium padded box.",
    returnPolicy: "7-day returns unopened.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.9,
    reviewCount: 52,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-bb-cho-z-achilles-attack-bp-3",
    title: "Beyblade Burst — Cho-Z Achilles 00 Dimension Attack",
    description: "<p>Cho-Z Achilles 00 Dimension — the most powerful attack-type in Burst Cho-Z series. Metal-reinforced armor for devastating strikes. Used by Aiger Akabane in the anime.</p>",
    slug: "bb-cho-z-achilles-00-dimension-attack",
    category: "category-bb-attack-type",
    subcategory: "Burst Cho-Z",
    brand: "Beyblade Burst",
    price: 1899,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("bb-achilles-cho-z"),
    images: [img("bb-achilles-cho-z")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "achilles", "cho-z", "attack", "aiger"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Cho-Z" },
      { name: "Type", value: "Attack" },
      { name: "Layer", value: "Cho-Z Achilles" },
      { name: "Chassis", value: "00 Dimension" },
    ],
    features: ["Metal Cho-Z armor", "High power attack", "Anime protagonist bey"],
    shippingInfo: "Padded nationwide delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 34,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-bb-world-spriggan-attack-bp-4",
    title: "Beyblade Burst — World Spriggan Unison' Sword Drift Attack",
    description: "<p>World Spriggan features the unique Unison Driver that switches between Attack and Stamina modes dynamically during battle. A top competitive choice in GT series.</p>",
    slug: "bb-world-spriggan-unison-sword-drift",
    category: "category-bb-attack-type",
    subcategory: "Burst GT",
    brand: "Beyblade Burst",
    price: 2199,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("bb-world-spriggan"),
    images: [img("bb-world-spriggan")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "world spriggan", "gt", "attack", "unison"],
    specifications: [
      { name: "Series", value: "Beyblade Burst GT" },
      { name: "Type", value: "Attack / Stamina (Dynamic)" },
      { name: "Driver", value: "Unison Sword Drift" },
    ],
    features: ["Dynamic mode switch", "Unison driver technology", "GT series champion"],
    shippingInfo: "Padded box.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 22,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-bb-turbo-spryzen-s4-attack-bp-5",
    title: "Beyblade Burst — Turbo Spryzen S4 Tornado Strike Attack",
    description: "<p>Turbo Spryzen S4 — the iconic balance-to-attack Beyblade from Burst Turbo. The tornado-generating performance tip creates spiraling attack patterns that confuse opponents.</p>",
    slug: "bb-turbo-spryzen-s4-tornado-strike",
    category: "category-bb-attack-type",
    subcategory: "Burst Turbo",
    brand: "Beyblade Burst",
    price: 1599,
    currency: _CURRENCY,
    stockQuantity: 14,
    availableQuantity: 12,
    mainImage: img("bb-turbo-spryzen"),
    images: [img("bb-turbo-spryzen")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "spryzen", "turbo", "tornado", "attack"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Turbo" },
      { name: "Type", value: "Attack" },
    ],
    features: ["Tornado Strike performance tip", "Spiral attack pattern"],
    shippingInfo: "Nationwide padded delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 19,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-bb-ultimate-valtryek-v6-attack-bp-6",
    title: "Beyblade Burst — Ultimate Valtryek V6 Volcanic' Attack",
    description: "<p>The ultimate evolution of Valtryek. V6 features enhanced burst resistance and the Volcanic' driver for aggressive close-range attacks. Limited restock — get yours now.</p>",
    slug: "bb-ultimate-valtryek-v6-volcanic-attack",
    category: "category-bb-attack-type",
    subcategory: "Burst Superking",
    brand: "Beyblade Burst",
    price: 1799,
    currency: _CURRENCY,
    stockQuantity: 9,
    availableQuantity: 7,
    mainImage: img("bb-valtryek-v6"),
    images: [img("bb-valtryek-v6")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "valtryek", "v6", "ultimate", "attack"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Superking" },
      { name: "Type", value: "Attack" },
      { name: "Generation", value: "V6 — 6th evolution" },
    ],
    features: ["Enhanced burst resistance", "Volcanic' driver", "6th-gen Valtryek evolution"],
    shippingInfo: "Nationwide delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 15,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(7),
  },

  // ── DEFENSE TYPE (4) ──────────────────────────────────────────────────────

  {
    id: "product-bb-maximum-garuda-g6-defense-bp-7",
    title: "Beyblade Burst — Maximum Garuda G6 Defense",
    description: "<p>Maximum Garuda G6 is a wide, heavy defense-type Beyblade from Burst Rise. The six-wing layer absorbs attacks efficiently, and the heavy disc adds stability under pressure.</p>",
    slug: "bb-maximum-garuda-g6-defense",
    category: "category-bb-defense-type",
    subcategory: "Burst Rise",
    brand: "Beyblade Burst",
    price: 1399,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 13,
    mainImage: img("bb-garuda-g6"),
    images: [img("bb-garuda-g6")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "garuda", "g6", "defense", "rise"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Rise" },
      { name: "Type", value: "Defense" },
      { name: "Layer", value: "Maximum Garuda G6" },
    ],
    features: ["6-wing defense layer", "Heavy metal disc", "High resistance to bursting"],
    shippingInfo: "Padded nationwide delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 20,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-bb-tempest-dragon-defense-bp-8",
    title: "Beyblade Burst — Tempest Dragon Defense (QuadDrive)",
    description: "<p>Tempest Dragon from QuadDrive — the toughest defense bey in the series. The dragon-themed layer has reinforced ridges that deflect attack-type hits and maintain spin momentum.</p>",
    slug: "bb-tempest-dragon-defense-quaddrive",
    category: "category-bb-defense-type",
    subcategory: "Burst QuadDrive",
    brand: "Beyblade Burst",
    price: 1899,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 9,
    mainImage: img("bb-tempest-dragon"),
    images: [img("bb-tempest-dragon")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "tempest dragon", "defense", "quaddrive"],
    specifications: [
      { name: "Series", value: "Beyblade Burst QuadDrive" },
      { name: "Type", value: "Defense" },
    ],
    features: ["Reinforced dragon ridges", "Deflection-optimised shape", "QuadDrive chassis"],
    shippingInfo: "Padded nationwide delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 16,
    createdAt: daysAgo(48),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-bb-balkesh-b3-defense-bp-9",
    title: "Beyblade Burst — Balkesh B3 Iron Defense",
    description: "<p>Balkesh B3 Iron Defense from original Burst series. The bull-horned layer provides excellent self-righting behaviour and burst resistance. A foundational defense-type bey.</p>",
    slug: "bb-balkesh-b3-iron-defense",
    category: "category-bb-defense-type",
    subcategory: "Burst Original",
    brand: "Beyblade Burst",
    price: 999,
    currency: _CURRENCY,
    stockQuantity: 18,
    availableQuantity: 16,
    mainImage: img("bb-balkesh-b3"),
    images: [img("bb-balkesh-b3")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "balkesh", "b3", "defense"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Original" },
      { name: "Type", value: "Defense" },
    ],
    features: ["Bull horn shape", "Burst resistance", "Solid defense profile"],
    shippingInfo: "Nationwide delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.3,
    reviewCount: 11,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },

  {
    id: "product-bb-king-helios-defense-bp-10",
    title: "Beyblade Burst — King Helios Zn Dimension Defense",
    description: "<p>King Helios Zn Dimension from Burst QuadDrive — heavy defense chassis with the King Helios sun-themed layer. Exceptional stability under relentless attack combinations.</p>",
    slug: "bb-king-helios-zn-dimension-defense",
    category: "category-bb-defense-type",
    subcategory: "Burst QuadDrive",
    brand: "Beyblade Burst",
    price: 1699,
    currency: _CURRENCY,
    stockQuantity: 11,
    availableQuantity: 9,
    mainImage: img("bb-king-helios"),
    images: [img("bb-king-helios")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "king helios", "zn", "defense", "quaddrive"],
    specifications: [
      { name: "Series", value: "Beyblade Burst QuadDrive" },
      { name: "Type", value: "Defense" },
      { name: "Chassis", value: "Zn Dimension" },
    ],
    features: ["Sun-themed layer", "High stability chassis", "Heavy defense build"],
    shippingInfo: "Padded nationwide.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 13,
    createdAt: daysAgo(32),
    updatedAt: daysAgo(6),
  },

  // ── STAMINA TYPE (5) ──────────────────────────────────────────────────────

  {
    id: "product-bb-nepstrius-n4-stamina-bp-11",
    title: "Beyblade Burst — Nepstrius N4 Octo' Yard' Stamina",
    description: "<p>Nepstrius N4 is the definitive stamina-type Beyblade from Burst Rise. Low-friction tip and aerodynamic layer allow it to outlast almost any opponent. Tournament pick for stamina bladers.</p>",
    slug: "bb-nepstrius-n4-octo-yard-stamina",
    category: "category-bb-stamina-type",
    subcategory: "Burst Rise",
    brand: "Beyblade Burst",
    price: 1299,
    currency: _CURRENCY,
    stockQuantity: 16,
    availableQuantity: 14,
    mainImage: img("bb-nepstrius-n4"),
    images: [img("bb-nepstrius-n4")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "nepstrius", "n4", "stamina", "rise", "tournament"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Rise" },
      { name: "Type", value: "Stamina" },
      { name: "Performance Tip", value: "Yard' (low friction)" },
    ],
    features: ["Ultra-low friction Yard' tip", "Aerodynamic layer", "Tournament-grade stamina"],
    shippingInfo: "Padded nationwide.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(25),
    avgRating: 4.8,
    reviewCount: 41,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-bb-chaos-hyperion-stamina-bp-12",
    title: "Beyblade Burst — Chaos Hyperion Stamina (Superking)",
    description: "<p>Hyperion Burn from Burst Superking — a fearsome stamina type with the Hyperion sun layer and Burn performance tip. Lights up the stadium with its signature glow effect during battle.</p>",
    slug: "bb-chaos-hyperion-burn-stamina-superking",
    category: "category-bb-stamina-type",
    subcategory: "Burst Superking",
    brand: "Beyblade Burst",
    price: 1799,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("bb-hyperion"),
    images: [img("bb-hyperion")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "hyperion", "stamina", "superking", "glow"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Superking" },
      { name: "Type", value: "Stamina" },
      { name: "Special Feature", value: "LED glow effect" },
    ],
    features: ["LED glow effect during spin", "Aerodynamic Hyperion layer", "Burn tip stamina"],
    shippingInfo: "Padded box nationwide.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 24,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-bb-revive-phoenix-stamina-bp-13",
    title: "Beyblade Burst — Revive Phoenix 10Fr Survive Stamina",
    description: "<p>Revive Phoenix — the legendary stamina-type with the unique 'Survive' performance tip that self-rights when tilted. Near impossible to knock out. A collector icon.</p>",
    slug: "bb-revive-phoenix-10fr-survive-stamina",
    category: "category-bb-stamina-type",
    subcategory: "Burst Evolution",
    brand: "Beyblade Burst",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 7,
    availableQuantity: 5,
    mainImage: img("bb-revive-phoenix"),
    images: [img("bb-revive-phoenix")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "revive phoenix", "stamina", "survive", "legendary"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Evolution" },
      { name: "Type", value: "Stamina" },
      { name: "Performance Tip", value: "Survive (self-righting)" },
    ],
    features: ["Self-righting Survive tip", "Phoenix rebirth mechanic", "Legendary tournament bey"],
    shippingInfo: "Premium padded box.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.9,
    reviewCount: 67,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-bb-air-knight-a5-stamina-bp-14",
    title: "Beyblade Burst — Air Knight A5 Hurricane Hold' Stamina",
    description: "<p>Air Knight A5 from Burst Rise — aerodynamic wing design that channels air flow for maximum spin time. The Hurricane Hold' tip creates a centre-gravity vortex that outlasts all competition.</p>",
    slug: "bb-air-knight-a5-hurricane-hold-stamina",
    category: "category-bb-stamina-type",
    subcategory: "Burst Rise",
    brand: "Beyblade Burst",
    price: 1399,
    currency: _CURRENCY,
    stockQuantity: 13,
    availableQuantity: 11,
    mainImage: img("bb-air-knight"),
    images: [img("bb-air-knight")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "air knight", "a5", "stamina", "rise"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Rise" },
      { name: "Type", value: "Stamina" },
      { name: "Performance Tip", value: "Hurricane Hold'" },
    ],
    features: ["Aerodynamic wing layer", "Hurricane tip for long spin", "Air channel design"],
    shippingInfo: "Nationwide padded delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 18,
    createdAt: daysAgo(42),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-bb-longinus-5-stamina-bp-15",
    title: "Beyblade Burst — Longinus 5 Hell Scythe Stamina",
    description: "<p>Hell Longinus 5 from Burst Cho-Z — a stamina-type with a dual-scythe attack layer that shreds opponents while maintaining extraordinary spin time. The go-to bey of countless champions.</p>",
    slug: "bb-longinus-5-hell-scythe-stamina",
    category: "category-bb-stamina-type",
    subcategory: "Burst Cho-Z",
    brand: "Beyblade Burst",
    price: 1799,
    currency: _CURRENCY,
    stockQuantity: 11,
    availableQuantity: 9,
    mainImage: img("bb-longinus-5"),
    images: [img("bb-longinus-5")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "longinus", "l5", "stamina", "cho-z"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Cho-Z" },
      { name: "Type", value: "Stamina" },
      { name: "Layer", value: "Hell Longinus" },
    ],
    features: ["Dual scythe attack edges", "Stamina-optimised disc", "Cho-Z metal armour"],
    shippingInfo: "Padded nationwide.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 30,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(6),
  },

  // ── BALANCE TYPE (3) ──────────────────────────────────────────────────────

  {
    id: "product-bb-genesis-drago-balance-bp-16",
    title: "Beyblade Burst — Genesis Drago 10*B Assault Balance",
    description: "<p>Genesis Drago from original Burst — the dragon-themed balance-type Beyblade. Versatile performance tip allows aggressive and defensive strategies. Iconic bey of Valt Aoi in the anime.</p>",
    slug: "bb-genesis-drago-10b-assault-balance",
    category: "category-bb-balance-type",
    subcategory: "Burst Original",
    brand: "Beyblade Burst",
    price: 1499,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 13,
    mainImage: img("bb-genesis-drago"),
    images: [img("bb-genesis-drago")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "drago", "genesis", "balance", "valt"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Original" },
      { name: "Type", value: "Balance" },
      { name: "Protagonist", value: "Valt Aoi" },
    ],
    features: ["Versatile balance performance", "Dragon theme", "Iconic anime protagonist bey"],
    shippingInfo: "Nationwide padded delivery.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.7,
    reviewCount: 45,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-bb-turbo-achilles-balance-bp-17",
    title: "Beyblade Burst — Turbo Achilles A4 Xtreme' Revolve' Balance",
    description: "<p>Turbo Achilles A4 from Burst Turbo — a high-performance balance-type with aggressive attack potential and solid stamina. The Xtreme' driver enables burst attacks while Revolve' base sustains spin.</p>",
    slug: "bb-turbo-achilles-a4-xtreme-revolve-balance",
    category: "category-bb-balance-type",
    subcategory: "Burst Turbo",
    brand: "Beyblade Burst",
    price: 1999,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("bb-turbo-achilles"),
    images: [img("bb-turbo-achilles")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "burst", "achilles", "turbo", "balance", "a4"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Turbo" },
      { name: "Type", value: "Balance" },
      { name: "Driver", value: "Xtreme' Revolve'" },
    ],
    features: ["Dual-mode Xtreme' Revolve' tip", "Balance-type versatility", "Attack + Stamina modes"],
    shippingInfo: "Padded box.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 27,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-bb-dead-hades-balance-bp-18",
    title: "Beyblade Burst — Dead Hades 7 Iron Revolve' Balance",
    description: "<p>Dead Hades — the dark balance-type from Burst Evolution. The Iron Disc adds defensive mass while the Revolve' driver enables exceptional stamina. One of the most complete balance beys ever made.</p>",
    slug: "bb-dead-hades-7-iron-revolve-balance",
    category: "category-bb-balance-type",
    subcategory: "Burst Evolution",
    brand: "Beyblade Burst",
    price: 2199,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 6,
    mainImage: img("bb-dead-hades"),
    images: [img("bb-dead-hades")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "dead hades", "balance", "evolution", "iron"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Evolution" },
      { name: "Type", value: "Balance" },
      { name: "Forge Disc", value: "7 Iron" },
    ],
    features: ["7 Iron heavy disc", "Revolve' stamina driver", "Dark Hades theme"],
    shippingInfo: "Premium padded box.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 32,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(5),
  },

  // ── STADIUM & ACCESSORIES (2) ─────────────────────────────────────────────

  {
    id: "product-bb-attack-type-stadium-bp-19",
    title: "Beyblade Burst BeyStadium — Attack Type Stadium",
    description: "<p>The official Burst Attack Type stadium — designed for aggressive attack-type battles. Deep pockets and steep walls amplify bursts and send losers flying. Recommended for competitive play.</p>",
    slug: "bb-burst-beystadium-attack-type",
    category: "category-bb-stadium",
    subcategory: "Stadiums",
    brand: "Beyblade Burst",
    price: 1499,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 17,
    mainImage: img("bb-attack-stadium"),
    images: [img("bb-attack-stadium"), img("bb-attack-stadium-2")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "stadium", "attack type", "beystadium", "accessories"],
    specifications: [
      { name: "Type", value: "Attack Type Stadium" },
      { name: "Series", value: "Beyblade Burst" },
      { name: "Diameter", value: "~48 cm" },
      { name: "Compatible", value: "All Burst series Beyblades" },
    ],
    features: ["Attack-optimised pocket design", "Steep walls for burst activation", "Non-slip base"],
    shippingInfo: "Large flat-pack box. Nationwide delivery.",
    returnPolicy: "7-day returns for damaged/defective items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.6,
    reviewCount: 38,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-bb-gt-stamina-stadium-bp-20",
    title: "Beyblade Burst GT Stamina BeyStadium — Pro Tournament",
    description: "<p>Pro-grade Burst GT Stamina stadium used in official tournaments. Smooth, low-friction surface maximises stamina battles. Extra-deep walls keep beys in play longer. Comes with mesh scoring track.</p>",
    slug: "bb-burst-gt-stamina-stadium-pro-tournament",
    category: "category-bb-stadium",
    subcategory: "Stadiums",
    brand: "Beyblade Burst",
    price: 2299,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("bb-stamina-stadium"),
    images: [img("bb-stamina-stadium")],
    status: "published",
    ...BP,
    featured: false,
    tags: ["beyblade", "stadium", "stamina", "gt", "tournament", "pro"],
    specifications: [
      { name: "Type", value: "Stamina Type Stadium" },
      { name: "Series", value: "Beyblade Burst GT" },
      { name: "Diameter", value: "~56 cm" },
      { name: "Level", value: "Tournament grade" },
    ],
    features: ["Tournament-grade surface", "Low friction base", "Mesh scoring track"],
    shippingInfo: "Large padded box.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 25,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(3),
  },

  // ── AUCTIONS (2) ─────────────────────────────────────────────────────────

  {
    id: "auction-bb-astral-spriggan-rare-bp-1",
    title: "AUCTION — Beyblade Burst QuadDrive Astral Spriggan Rare",
    description: "<p>Astral Spriggan from QuadDrive — the rarest attack-type Beyblade of the series. Limited international release, never made available in India officially. The Giga Driver delivers extreme power bursts. This is a Japan import in original packaging.</p>",
    slug: "auction-bb-astral-spriggan-quaddrive-rare",
    category: "category-bb-attack-type",
    subcategory: "Burst QuadDrive",
    brand: "Beyblade Burst",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("bb-astral-spriggan"),
    images: [img("bb-astral-spriggan")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "astral spriggan", "quaddrive", "rare", "japan import", "auction"],
    specifications: [
      { name: "Series", value: "Beyblade Burst QuadDrive" },
      { name: "Type", value: "Attack" },
      { name: "Origin", value: "Japan import" },
      { name: "Driver", value: "Giga Driver" },
      { name: "Condition", value: "Sealed box" },
    ],
    features: ["Japan exclusive import", "Giga Driver — extreme power", "Sealed original packaging", "Never released in India"],
    shippingInfo: "Insured courier. Padded hard case.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 149,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(6),
    startingBid: 2999,
    currentBid: 3700,
    bidCount: 9,
    reservePrice: 4000,
    buyNowPrice: 7999,
    minBidIncrement: 250,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: daysAhead(6),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(6),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },

  {
    id: "auction-bb-dead-phoenix-limited-bp-2",
    title: "AUCTION — Beyblade Burst Evolution Dead Phoenix Hasbro Limited",
    description: "<p>Dead Phoenix Limited Edition from Hasbro — the alternate Hasbro version of the Revive Phoenix with unique colour scheme and chrome disc. Only 500 units released in India. Original Hasbro packaging, never opened.</p>",
    slug: "auction-bb-dead-phoenix-hasbro-limited",
    category: "category-bb-stamina-type",
    subcategory: "Burst Evolution",
    brand: "Beyblade Burst",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("bb-dead-phoenix"),
    images: [img("bb-dead-phoenix")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "dead phoenix", "limited", "hasbro", "stamina", "auction"],
    specifications: [
      { name: "Series", value: "Beyblade Burst Evolution" },
      { name: "Type", value: "Stamina" },
      { name: "Edition", value: "Hasbro Limited — 500 units" },
      { name: "Disc", value: "Chrome Disc" },
      { name: "Condition", value: "Sealed" },
    ],
    features: ["Limited to 500 India units", "Chrome chrome disc variant", "Hasbro exclusive colour", "Original sealed packaging"],
    shippingInfo: "Insured padded courier.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 99,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(4),
    startingBid: 3499,
    currentBid: 4200,
    bidCount: 12,
    reservePrice: 5000,
    buyNowPrice: 8999,
    minBidIncrement: 250,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: daysAhead(4),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(4),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },

  // ── PRE-ORDERS (2) ───────────────────────────────────────────────────────

  {
    id: "preorder-bb-quaddrive-wave3-2026-bp-1",
    title: "PRE-ORDER — Beyblade Burst QuadDrive Wave 3 2026 (Starter Set)",
    description: "<p>Reserve the upcoming Beyblade Burst QuadDrive Wave 3 2026 Starter Set featuring the new Valtryek and Longinus evolution models. Includes bey, launcher, and exclusive stadium piece. Pre-order for guaranteed day-1 delivery.</p>",
    slug: "preorder-bb-quaddrive-wave3-starter-2026",
    category: "category-bb-attack-type",
    subcategory: "Burst QuadDrive",
    brand: "Beyblade Burst",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 100,
    availableQuantity: 78,
    mainImage: img("bb-quaddrive-wave3"),
    images: [img("bb-quaddrive-wave3")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "quaddrive", "wave 3", "pre-order", "2026"],
    specifications: [
      { name: "Series", value: "Beyblade Burst QuadDrive" },
      { name: "Wave", value: "Wave 3 2026" },
      { name: "Includes", value: "Bey + Launcher + Stadium Piece" },
      { name: "Expected Delivery", value: "Q2 2026" },
    ],
    features: ["Day-1 delivery guarantee", "Exclusive stadium piece", "New Valtryek evolution"],
    shippingInfo: "Dispatched on release. Nationwide tracking.",
    returnPolicy: "Pre-orders: cancel anytime before dispatch.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(90),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(45),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },

  {
    id: "preorder-bb-ultimate-championship-set-2026-bp-2",
    title: "PRE-ORDER — Beyblade Burst Ultimate Championship Set 2026",
    description: "<p>The official 2026 Beyblade Burst Ultimate Championship Set — everything you need to compete. Includes 3 championship-grade beys (Attack/Defense/Stamina), 2 string launchers, metal handle, and pro-grade Attack Type stadium. Pre-order at launch price.</p>",
    slug: "preorder-bb-ultimate-championship-set-2026",
    category: "category-bb-stadium",
    subcategory: "Championship Sets",
    brand: "Beyblade Burst",
    price: 5999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 41,
    mainImage: img("bb-championship-set"),
    images: [img("bb-championship-set")],
    status: "published",
    ...BP,
    featured: true,
    tags: ["beyblade", "burst", "championship", "set", "pre-order", "2026", "tournament"],
    specifications: [
      { name: "Contents", value: "3 Beyblades + 2 Launchers + Stadium" },
      { name: "Launcher Type", value: "String Launcher with Metal Handle" },
      { name: "Stadium", value: "Attack Type (Pro Grade)" },
      { name: "Expected Delivery", value: "Q3 2026" },
    ],
    features: ["3 championship-grade beys", "2 string launchers", "Metal handle included", "Pro Attack stadium"],
    shippingInfo: "Special championship packaging. Nationwide delivery.",
    returnPolicy: "Pre-orders: cancel before dispatch.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(150),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(90),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
];
