/*
 * WHY: Seeds 20 blog posts for LetItRip collectibles marketplace — content/SEO testing across all categories.
 * WHAT: 17 published + 2 draft + 1 archived. Mix of YGO-specific, broader collectibles (Pokémon, Hot Wheels,
 *       Beyblade, Gundam, Funko), marketplace guides, and community stories.
 *
 * EXPORTS:
 *   blogPostsSeedData — Array of Partial<BlogPostDocument> for seed runner
 *
 * @tag domain:blog
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts,SeedPanel
 * @tag sideEffects:none
 */

import type { BlogPostDocument } from "../features/blog/schemas";
import { seedExtMedia } from "./_helpers/media";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const blogPostsSeedData: Partial<BlogPostDocument>[] = [

  // ── GUIDES (6) ────────────────────────────────────────────────────────────

  {
    id: "blog-identify-1st-edition-yugioh",
    title: "How to Identify 1st Edition Yu-Gi-Oh! Cards",
    slug: "identify-1st-edition-yugioh",
    excerpt: "Learn the telltale signs that distinguish a genuine 1st Edition print from Unlimited — from the gold stamp placement to the eye of Anubis hologram.",
    content: `<h2>The Gold Stamp</h2><p>1st Edition Yu-Gi-Oh! cards feature a gold "1st Edition" stamp below the artwork on the left side. On LOB (Legend of Blue Eyes White Dragon) cards from 2002, this stamp is slightly larger than later sets.</p><h2>Eye of Anubis</h2><p>Starting with LOB Unlimited, Konami added the Eye of Anubis hologram to the bottom-right corner. 1st Edition LOB cards do NOT have this hologram — that's actually a sign of authenticity for the earliest prints.</p><h2>Font Differences</h2><p>Compare the font weight of the card name. 1st Edition prints from the early Duel Monsters era often have slightly bolder text than their Unlimited counterparts.</p>`,
    coverImage: { type: "image", url: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"), alt: "Dark Magician card art" },
    category: "guides",
    tags: ["1st-edition", "authentication", "grading", "ygo"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(30),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    authorAvatar: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
    readTimeMinutes: 5,
    views: 4200,
    metaTitle: "How to Identify 1st Edition Yu-Gi-Oh! Cards | LetItRip",
    metaDescription: "Learn how to spot genuine 1st Edition YGO cards — gold stamps, Eye of Anubis, font differences, and more.",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(30),
  },

  {
    id: "blog-psa-vs-bgs-vs-cgc",
    title: "PSA vs BGS vs CGC — Which Grading Service for Your Cards?",
    slug: "psa-vs-bgs-vs-cgc",
    excerpt: "A head-to-head comparison of the three major card grading services and which one commands the highest premiums in the trading card market.",
    content: `<h2>PSA — The Industry Standard</h2><p>PSA (Professional Sports Authenticator) is the most widely recognized grading service. A PSA 10 "Gem Mint" commands the highest resale premiums, especially for vintage cards from any TCG.</p><h2>BGS — The Sub-Grade King</h2><p>Beckett Grading Services provides sub-grades for centering, surface, edges, and corners. A BGS 10 "Pristine" is incredibly rare, and a BGS 10 "Black Label" (all sub-grades 10) is the holy grail.</p><h2>CGC — The Newcomer</h2><p>CGC entered the trading card market more recently. They also offer sub-grades and their slabs have a modern, clean design. CGC is growing in popularity but PSA still dominates resale value.</p><h2>Our Recommendation</h2><p>For investment: PSA 10 commands the highest resale value. For personal collection with detailed condition analysis: BGS. For budget grading: CGC.</p>`,
    coverImage: { type: "image", url: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"), alt: "Exodia the Forbidden One" },
    category: "guides",
    tags: ["grading", "psa", "bgs", "cgc", "trading-cards", "investment"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(25),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    authorAvatar: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
    readTimeMinutes: 7,
    views: 3800,
    metaTitle: "PSA vs BGS vs CGC — Best Card Grading Services | LetItRip",
    metaDescription: "Compare PSA, BGS, and CGC grading services for trading cards — premiums, turnaround, and which to choose.",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(25),
  },

  {
    id: "blog-complete-exodia-guide",
    title: "Complete Exodia Guide — All Printings and Values",
    slug: "complete-exodia-guide",
    excerpt: "Every printing of Exodia the Forbidden One and its four limbs — from the original LOB 1st Edition to the latest reprint, with current market values.",
    content: `<h2>The Original Five</h2><p>Exodia the Forbidden One (33396948), Left Arm (07902349), Right Arm (70903634), Left Leg (44519536), and Right Leg (08124921). Completing the set in your hand is an instant win — and completing a 1st Edition PSA 10 set is the ultimate flex.</p><h2>LOB 1st Edition (2002)</h2><p>The holy grail. Each piece in PSA 10 ranges from ₹3–5 lakh. A complete set? Over ₹20 lakh.</p><h2>Later Printings</h2><p>Unlimited LOB, Retro Pack, Lost Art Promotion, and various structure deck reprints. Values range from ₹500 for common reprints to ₹50,000+ for rare promotional versions.</p>`,
    coverImage: { type: "image", url: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"), alt: "Exodia the Forbidden One" },
    category: "guides",
    tags: ["exodia", "guide", "printings", "values", "ygo"],
    isFeatured: false,
    status: "draft",
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    authorAvatar: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
    readTimeMinutes: 10,
    views: 0,
    metaTitle: "Complete Exodia Guide — All Printings & Values | LetItRip",
    metaDescription: "Every Exodia printing from LOB 1st Edition to modern reprints — market values and collecting tips.",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },

  {
    id: "blog-beginners-guide-hot-wheels-collecting",
    title: "Beginner's Guide to Hot Wheels Collecting in India",
    slug: "beginners-guide-hot-wheels-collecting",
    excerpt: "From mainlines to Super Treasure Hunts — everything you need to know to start your Hot Wheels collection without breaking the bank.",
    content: `<h2>Understanding the Tiers</h2><p><strong>Mainlines</strong> — ₹100–₹200 retail, the backbone of any collection. <strong>Premium</strong> — ₹400–₹600, metal/metal construction with Real Riders rubber tires. <strong>Car Culture</strong> — ₹700–₹1,000, themed sets with premium details. <strong>RLC (Red Line Club)</strong> — membership exclusive, ₹2,000–₹5,000+.</p><h2>Treasure Hunts</h2><p>Regular TH cards have a flame logo. Super Treasure Hunts (STH) have Spectraflame paint + Real Riders — roughly 1 per 15 cases. STHs command ₹2,000–₹10,000+ depending on the casting.</p><h2>Storage Tips</h2><p>Keep carded cars in protector cases. Loose cars in padded compartment boxes. Never store in direct sunlight — Spectraflame paint fades permanently.</p>`,
    category: "guides",
    tags: ["hot-wheels", "diecast", "collecting", "beginners", "treasure-hunt"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(18),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 8,
    views: 3100,
    metaTitle: "Beginner's Guide to Hot Wheels Collecting | LetItRip",
    metaDescription: "Start your Hot Wheels collection in India — mainlines, Treasure Hunts, storage, and where to find rare castings.",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(18),
  },

  {
    id: "blog-gundam-model-kit-grades-explained",
    title: "Gundam Model Kit Grades Explained: HG vs RG vs MG vs PG",
    slug: "gundam-model-kit-grades-explained",
    excerpt: "Not sure which Gundam grade to start with? Here's a detailed breakdown of every Bandai grade — from the beginner-friendly HG to the massive Perfect Grade.",
    content: `<h2>High Grade (HG) — 1/144 Scale</h2><p>The entry point for most builders. ~100 parts, snap-fit (no glue needed), completes in 2–3 hours. ₹800–₹2,000. Great articulation for the price.</p><h2>Real Grade (RG) — 1/144 Scale</h2><p>Master Grade detail at HG size. ~200 parts, pre-colored inner frame. More fragile than HG due to small parts. ₹1,800–₹3,500. The RG Nu Gundam and RG Wing Zero are fan favorites.</p><h2>Master Grade (MG) — 1/100 Scale</h2><p>The collector's standard. ~400 parts, fully detailed inner frame, excellent poseability. ₹3,500–₹8,000. Build time: 6–12 hours. MG Barbatos and MG Freedom 2.0 are top sellers on LetItRip.</p><h2>Perfect Grade (PG) — 1/60 Scale</h2><p>The pinnacle. ~800+ parts, LED-compatible, museum-quality detail. ₹12,000–₹25,000+. Build time: 20–40 hours. A showpiece, not a toy.</p><h2>Other Grades</h2><p><strong>SD</strong> (Super Deformed) — chibi proportions, great for kids. <strong>EG</strong> (Entry Grade) — simplified build, no tools needed. <strong>MGEX</strong> — MG with extreme detail (Unicorn Gundam only). <strong>PG Unleashed</strong> — beyond PG, the ultimate kit.</p>`,
    category: "guides",
    tags: ["gundam", "bandai", "model-kits", "hg", "mg", "rg", "pg"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(12),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 7,
    views: 2600,
    metaTitle: "Gundam Model Kit Grades Explained | LetItRip",
    metaDescription: "HG vs RG vs MG vs PG — understand every Gundam grade before you buy on LetItRip.",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(12),
  },

  {
    id: "blog-beyblade-x-vs-burst-comparison",
    title: "Beyblade X vs Burst: What's Changed and Is It Worth Switching?",
    slug: "beyblade-x-vs-burst-comparison",
    excerpt: "Beyblade X brought a whole new system — Xtreme Dash rails, new launcher, and incompatible parts. Here's whether the upgrade is worth it for Indian bladers.",
    content: `<h2>The Big Changes</h2><p>Beyblade X introduced the <strong>Xtreme Stadium</strong> with dash rails that accelerate beyblades mid-battle. The launcher mechanism is completely redesigned — smoother pull, more consistent spin. Parts are NOT compatible with Burst.</p><h2>Performance Comparison</h2><p>X beyblades spin longer out of the box thanks to better bearing tips. Burst had more customization depth (3 parts vs X's 3-layer system). X battles are faster and more aggressive due to the rail system.</p><h2>Availability in India</h2><p>Takara-Tomy X is available through importers on LetItRip. Hasbro X (budget version) is easier to find in retail stores. For competitive play, always go Takara-Tomy.</p><h2>Verdict</h2><p>If you're starting fresh: go X. If you have a big Burst collection: keep both systems. X stadiums work fine for casual Burst battles too — just no rail acceleration.</p>`,
    category: "guides",
    tags: ["beyblade", "beyblade-x", "burst", "takara-tomy", "comparison"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(8),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 6,
    views: 1900,
    metaTitle: "Beyblade X vs Burst Comparison | LetItRip",
    metaDescription: "Beyblade X vs Burst — what changed, part compatibility, and whether Indian bladers should switch.",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },

  // ── NEWS (4) ──────────────────────────────────────────────────────────────

  {
    id: "blog-top-10-duel-monsters-cards",
    title: "Top 10 Most Valuable Duel Monsters Era Cards",
    slug: "top-10-duel-monsters-cards",
    excerpt: "From the legendary Blue-Eyes White Dragon LOB 1st Edition to the elusive Tournament Black Luster Soldier — these are the cards every collector dreams of.",
    content: `<h2>1. Tournament Black Luster Soldier (2002)</h2><p>The rarest YGO card ever printed. Only one exists in the wild. Estimated value: over ₹70 lakh.</p><h2>2. Blue-Eyes White Dragon LOB 1st Ed PSA 10</h2><p>Seto Kaiba's signature card in gem mint 1st Edition. PSA 10 copies sell for ₹15–25 lakh.</p><h2>3. Dark Magician LOB 1st Ed PSA 10</h2><p>Yugi's signature card. A PSA 10 1st Edition LOB Dark Magician commands ₹8–12 lakh.</p><h2>4. Exodia Complete Set (LOB 1st Ed, all 5 pieces PSA 10)</h2><p>All five Exodia pieces in 1st Edition PSA 10 — virtually impossible to assemble. Set value: over ₹20 lakh.</p><h2>5–10</h2><p>Mirror Force MRD 1st Ed, Change of Heart MRD 1st Ed, Monster Reborn LOB 1st Ed, Pot of Greed LOB 1st Ed, Gate Guardian MRD, and Dark Magician Girl MFC 1st Ed.</p>`,
    coverImage: { type: "image", url: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"), alt: "Blue-Eyes White Dragon" },
    category: "news",
    tags: ["top-10", "duel-monsters", "investment", "rare-cards"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(20),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    authorAvatar: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
    readTimeMinutes: 8,
    views: 6100,
    metaTitle: "Top 10 Most Valuable Duel Monsters Era Cards | LetItRip",
    metaDescription: "The 10 most expensive Yu-Gi-Oh! cards from the original Duel Monsters era.",
    createdAt: daysAgo(22),
    updatedAt: daysAgo(20),
  },

  {
    id: "blog-pokemon-sv-prismatic-evolutions",
    title: "Pokémon SV Prismatic Evolutions: What Indian Collectors Need to Know",
    slug: "pokemon-sv-prismatic-evolutions",
    excerpt: "Prismatic Evolutions is the hottest Pokémon set in 2026 — here's the pull rates, chase cards, and pricing for Indian collectors.",
    content: `<h2>The Chase Cards</h2><p>Prismatic Evolutions features all Eeveelution illustration rares + the Eevee gold star. The <strong>Umbreon illustration rare</strong> is the #1 chase card — commanding ₹40,000+ raw and ₹1.5 lakh+ in PSA 10.</p><h2>Pull Rates</h2><p>Illustration rare: ~1 in 25 packs. Special art rare: ~1 in 50 packs. Gold star: ~1 in 200 packs. The odds are brutal — most collectors buy singles on LetItRip instead of gambling on packs.</p><h2>Indian Market Pricing</h2><p>Booster boxes import at ₹6,000–₹8,000 (vs ₹4,000 US retail). ETBs at ₹4,500–₹6,000. The premium is due to import duties + limited official distribution in India. Pre-order on LetItRip to lock in the lowest price.</p>`,
    category: "news",
    tags: ["pokemon", "prismatic-evolutions", "trading-cards", "pricing", "chase-cards"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(7),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 6,
    views: 5200,
    metaTitle: "Pokémon Prismatic Evolutions — Indian Collector Guide | LetItRip",
    metaDescription: "Pull rates, chase cards, and Indian market pricing for Pokémon SV Prismatic Evolutions.",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },

  {
    id: "blog-funko-pop-india-market-2026",
    title: "The State of Funko Pop Collecting in India — 2026 Edition",
    slug: "funko-pop-india-market-2026",
    excerpt: "Funko Pop has exploded in India. Here's the market landscape — exclusive sourcing, pricing trends, and the most sought-after figures.",
    content: `<h2>Market Growth</h2><p>India's Funko Pop market has grown 3x since 2024, driven by anime Pops (Dragon Ball, Naruto, One Piece, Jujutsu Kaisen) and Marvel/Star Wars crossover appeal. LetItRip now has over 200 Funko listings across 5 verified stores.</p><h2>Exclusive Sourcing</h2><p>Convention exclusives (SDCC, NYCC) are the hardest to source. Indian collectors rely on importers who attend or have proxies at US conventions. Expect a 2–3x markup over US retail. Store exclusives (Hot Topic, BoxLunch, Target) are slightly easier via authorized resellers.</p><h2>Chase Variants</h2><p>Chase Pops (1-in-6 ratio) command a 3–5x premium. Glow-in-the-dark chases and flocked variants are the most popular in the Indian market. Always verify the chase sticker — counterfeits exist.</p><h2>Storage & Display</h2><p>Pop protectors (₹50–₹100 each) are essential. UV-filtering acrylic display cases for grails. Never store in direct sunlight — window box printing fades within months.</p>`,
    category: "news",
    tags: ["funko", "pop", "india", "market-trends", "collecting"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(14),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 7,
    views: 2400,
    metaTitle: "Funko Pop Collecting in India 2026 | LetItRip",
    metaDescription: "The state of Funko Pop collecting in India — exclusives, chase variants, and market trends.",
    createdAt: daysAgo(16),
    updatedAt: daysAgo(14),
  },

  {
    id: "blog-tomica-vs-hot-wheels-india",
    title: "Tomica vs Hot Wheels: The Diecast Battle in India",
    slug: "tomica-vs-hot-wheels-india",
    excerpt: "Two diecast giants go head-to-head. Which one offers better value, detail, and collectibility for Indian enthusiasts?",
    content: `<h2>Scale & Detail</h2><p>Tomica uses variable scale (roughly 1/60–1/64) to keep each model proportionally accurate in the hand. Hot Wheels uses a fixed 1/64 scale. Result: Tomica models look proportionally better; Hot Wheels are more consistent in a display.</p><h2>Build Quality</h2><p>Tomica models have working suspension and opening doors/hoods as standard — even on mainline ₹300 models. Hot Wheels mainlines are simpler (no opening parts) but Hot Wheels Premium (₹500+) matches Tomica quality.</p><h2>JDM & India Market</h2><p>Tomica dominates for JDM collectors (GT-R, Supra, AE86, Civic Type R). Hot Wheels wins for American muscle, European exotics, and fantasy castings. For Indian vehicles, Tomica has released exclusive India models (Maruti Swift, Tata Nexon) — highly collectible.</p><h2>Verdict</h2><p>Both. Seriously — most Indian collectors collect both. Tomica for realistic detail, Hot Wheels for variety and Treasure Hunt thrill.</p>`,
    category: "news",
    tags: ["tomica", "hot-wheels", "diecast", "comparison", "jdm"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(22),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 6,
    views: 1800,
    metaTitle: "Tomica vs Hot Wheels — Diecast Battle in India | LetItRip",
    metaDescription: "Tomica vs Hot Wheels — detail, build quality, and collecting value for Indian diecast enthusiasts.",
    createdAt: daysAgo(24),
    updatedAt: daysAgo(22),
  },

  // ── TIPS (4) ──────────────────────────────────────────────────────────────

  {
    id: "blog-gx-era-hidden-gems",
    title: "GX Era Hidden Gems: Undervalued Cards from Shadow of Infinity",
    slug: "gx-era-hidden-gems",
    excerpt: "The GX era produced some of the most undervalued cards in Yu-Gi-Oh! history. Here are the Shadow of Infinity cards smart collectors are buying now.",
    content: `<h2>Why GX Cards Are Undervalued</h2><p>The GX era (2004–2008) coincided with peak Yu-Gi-Oh! anime popularity but many collectors focus exclusively on the original Duel Monsters era. This creates a pricing gap.</p><h2>Shadow of Infinity Picks</h2><p><strong>Elemental HERO Neos</strong> — Jaden Yuki's signature card. 1st Edition Ultra Rare copies are still affordable at ₹3,000–₹5,000.</p><p><strong>Cyber Dragon</strong> — One of the most competitively impactful cards ever. 1st Edition Ultimate Rare commands ₹8,000–₹12,000.</p><p><strong>Rainbow Dragon</strong> — Jesse Anderson's ace. Low print run makes this a sleeper investment.</p>`,
    coverImage: { type: "image", url: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89943723.jpg"), alt: "Elemental HERO Neos" },
    category: "tips",
    tags: ["gx-era", "hidden-gems", "investment", "ygo"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(15),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    authorAvatar: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
    readTimeMinutes: 6,
    views: 2900,
    metaTitle: "GX Era Hidden Gems — Undervalued YGO Cards | LetItRip",
    metaDescription: "Discover undervalued GX era Yu-Gi-Oh! cards that smart collectors are buying now.",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(15),
  },

  {
    id: "blog-protect-collectibles-indian-climate",
    title: "How to Protect Your Collectibles in India's Climate",
    slug: "protect-collectibles-indian-climate",
    excerpt: "Humidity, dust, and monsoon season are the biggest enemies of collectibles in India. Here's how to keep your cards, figures, and kits safe year-round.",
    content: `<h2>The Humidity Problem</h2><p>India's average humidity is 60–80% — far above the 40–50% ideal for collectibles. Excess moisture causes card warping, sticker lifting on Funko boxes, paint degradation on diecast, and mold growth on cardboard packaging.</p><h2>Essential Gear</h2><p><strong>Silica gel packets</strong> — ₹200 for a 20-pack. Place 2–3 in every storage box. Replace when they turn pink/clear. <strong>Dehumidifier</strong> — ₹3,000–₹8,000 for a 10L/day unit. Essential for display rooms. <strong>UV-filtering display cases</strong> — prevents sunlight fading on Spectraflame (Hot Wheels), holo cards, and figure paint.</p><h2>Monsoon Protocol</h2><p>During June–September: seal all open storage, move ground-level boxes to shelves, check silica gel weekly. If you're in a flood-prone area, consider off-site storage for high-value grails.</p><h2>Card-Specific Tips</h2><p>Double-sleeve valuable cards (penny sleeve + top-loader). Store in a binder with O-ring closure, not D-ring. Keep graded slabs in padded boxes — PSA cases crack if dropped.</p>`,
    category: "tips",
    tags: ["storage", "climate", "humidity", "india", "preservation"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(10),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 7,
    views: 3500,
    metaTitle: "Protect Collectibles in India's Climate | LetItRip",
    metaDescription: "Humidity, dust, and monsoon tips — how to protect your collectibles in Indian weather.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
  },

  {
    id: "blog-selling-tips-letitrip",
    title: "10 Tips to Sell Faster on LetItRip",
    slug: "selling-tips-letitrip",
    excerpt: "From photography to pricing to descriptions — proven tactics to make your listings sell faster on LetItRip.",
    content: `<h2>1. Photograph Everything</h2><p>Front, back, edges, corners, holo pattern. Natural light. White background. Minimum 4 photos per listing.</p><h2>2. Price Competitively</h2><p>Check what similar items sold for on LetItRip in the last 30 days. Price 5–10% below the lowest active listing for a fast sale.</p><h2>3. Write Honest Descriptions</h2><p>State the exact condition. Mention every flaw. Buyers trust sellers who are upfront about imperfections — they'll come back.</p><h2>4. Respond to Offers Within 2 Hours</h2><p>Quick responses convert. Buyers often make offers to multiple sellers — the first response wins.</p><h2>5. Ship the Same Day</h2><p>Buyers who receive fast shipping leave 5-star reviews. 5-star reviews bring more buyers. It's a flywheel.</p><h2>6–10</h2><p>Use accurate category tags. Add a YouTube unboxing link. Offer bundle discounts. Cross-reference to your other listings. Keep your store description updated.</p>`,
    category: "tips",
    tags: ["selling", "tips", "photography", "pricing", "seller-guide"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(5),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 5,
    views: 1600,
    metaTitle: "10 Tips to Sell Faster on LetItRip",
    metaDescription: "Proven selling tactics — photography, pricing, and descriptions that convert on LetItRip.",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },

  {
    id: "blog-one-piece-tcg-india-primer",
    title: "One Piece TCG in India: A Complete Primer",
    slug: "one-piece-tcg-india-primer",
    excerpt: "One Piece Card Game has arrived in India. Here's everything you need to know about the game, the sets, and which cards to collect.",
    content: `<h2>What Is One Piece TCG?</h2><p>Released by Bandai in 2022, the One Piece Card Game has quickly become one of the top 3 trading card games globally. It uses a leader + character + event + stage system, with DON!! cards as the energy resource.</p><h2>Sets Available in India</h2><p>Romance Dawn (OP-01) through Wings of the Captain (OP-06) are available through importers on LetItRip. Expect a 1.5–2x markup over Japanese retail due to import costs.</p><h2>Chase Cards</h2><p>Alternate art leaders and manga art special rares are the most sought-after. <strong>Luffy Gear 5 (OP-05 alt art)</strong> — ₹15,000+. <strong>Shanks alt art (OP-01)</strong> — ₹8,000+. <strong>Nami alt art (OP-01)</strong> — ₹12,000+.</p><h2>Investment Potential</h2><p>One Piece TCG is undervalued compared to Pokémon. Early sets (OP-01, OP-02) are already appreciating. Buy singles of alt art leaders now — the floor is rising.</p>`,
    category: "tips",
    tags: ["one-piece", "bandai", "trading-cards", "primer", "tcg"],
    isFeatured: false,
    status: "draft",
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 8,
    views: 0,
    metaTitle: "One Piece TCG in India — Complete Primer | LetItRip",
    metaDescription: "Everything Indian collectors need to know about One Piece Card Game — sets, chase cards, and investment.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },

  // ── COMMUNITY (3) ─────────────────────────────────────────────────────────

  {
    id: "blog-authenticating-ygo-cards",
    title: "How a Verified Store Authenticates Every Card",
    slug: "authenticating-ygo-cards",
    excerpt: "A behind-the-scenes look at how verified sellers on LetItRip check every trading card before listing — light tests, holo patterns, and weight checks.",
    content: `<h2>The 5-Point Authentication Process</h2><p>Every card listed by top verified stores goes through a rigorous 5-point check:</p><ol><li><strong>Light Test</strong> — Genuine Konami/Pokémon Company cards have a specific opacity when held to light.</li><li><strong>Holo Pattern</strong> — Each rarity has a distinct holographic pattern verified under UV light.</li><li><strong>Weight Check</strong> — A genuine trading card weighs approximately 1.7–1.8 grams.</li><li><strong>Rosette Test</strong> — Under 10x magnification, genuine cards show a rosette dot pattern.</li><li><strong>Edge & Corner Inspection</strong> — Check for trimming, re-cornering, or alteration.</li></ol>`,
    coverImage: { type: "image", url: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/23995346.jpg"), alt: "Card authentication process" },
    category: "community",
    tags: ["authentication", "verification", "counterfeit", "trading-cards"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(10),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 5,
    views: 3400,
    metaTitle: "How Verified Stores Authenticate Cards | LetItRip",
    metaDescription: "The 5-point authentication process used by verified stores to check every trading card on LetItRip.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
  },

  {
    id: "blog-collector-spotlight-mumbai-gundam",
    title: "Collector Spotlight: Building India's Largest Gundam Collection in Mumbai",
    slug: "collector-spotlight-mumbai-gundam",
    excerpt: "Meet Arjun — a Mumbai software engineer with 200+ Gundam kits, a dedicated build room, and a mission to grow India's Gunpla community.",
    content: `<h2>The Collection</h2><p>Arjun started with a single HG RX-78-2 in 2019. Seven years later, his Mumbai apartment has a dedicated room with 200+ built kits across HG, RG, MG, and 3 Perfect Grades. The crown jewel: a painted and weathered PG Unleashed RX-78-2.</p><h2>The Build Process</h2><p>"I spend 2–3 hours every evening after work. It's meditation. The snap-fit assembly, the panel lining, the decals — there's something deeply satisfying about transforming a box of runners into a finished kit."</p><h2>Growing the Community</h2><p>Arjun runs a monthly Mumbai Gunpla meetup with 30+ regular attendees. "When I started, there were maybe 5 Gunpla builders I knew in all of Mumbai. Now there's a real community. LetItRip has helped — having a dedicated marketplace means people can actually find kits without paying 3x import markup."</p><h2>Advice for New Builders</h2><p>"Start with an HG. Don't buy a PG as your first kit — you'll get overwhelmed. Build 10–15 HGs, then try an RG. The skills transfer. And always — always — use a nipper, not scissors."</p>`,
    category: "community",
    tags: ["gundam", "spotlight", "mumbai", "gunpla", "community"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(3),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 6,
    views: 1200,
    metaTitle: "Collector Spotlight: Mumbai Gundam Collection | LetItRip",
    metaDescription: "Meet the Mumbai engineer building India's largest Gundam collection — 200+ kits and growing.",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },

  {
    id: "blog-india-collectibles-market-overview",
    title: "The Indian Collectibles Market in 2026: Where We Stand",
    slug: "india-collectibles-market-overview",
    excerpt: "From trading cards to action figures — a data-driven look at India's growing collectibles scene and what's driving the boom.",
    content: `<h2>The Numbers</h2><p>India's organized collectibles market is estimated at ₹2,500 crore in 2026, up from ₹800 crore in 2022. Trading cards (Pokémon, YGO, One Piece) account for ~40%, followed by action figures (~25%), diecast (~15%), and model kits (~10%).</p><h2>What's Driving Growth</h2><p><strong>Anime streaming</strong> — India is now the #3 market for anime streaming (Crunchyroll, Netflix anime). Fans who watch Dragon Ball, Naruto, and One Piece naturally become collectors. <strong>Social media</strong> — Instagram and YouTube unboxing/pull content drives awareness. <strong>Verified platforms</strong> — LetItRip and similar platforms have made it safe to buy collectibles online, reducing the counterfeit risk that previously kept buyers away.</p><h2>What's Hot in 2026</h2><p>Pokémon cards remain #1 by volume. Yu-Gi-Oh! has the highest average transaction value. Beyblade X is the fastest-growing category. Gundam is niche but intensely loyal. Hot Wheels Super Treasure Hunts are the "gateway drug" for new collectors.</p><h2>What's Next</h2><p>Sports cards (cricket, specifically) are the next frontier. Digital collectibles (graded card NFTs backed by physical) are being explored. LetItRip is building infrastructure for both.</p>`,
    category: "community",
    tags: ["india", "market", "overview", "trends", "2026"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(16),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 8,
    views: 4100,
    metaTitle: "Indian Collectibles Market 2026 | LetItRip",
    metaDescription: "Data-driven overview of India's collectibles market — trading cards, figures, diecast, and what's driving growth.",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(16),
  },

  // ── UPDATES (3) ───────────────────────────────────────────────────────────

  {
    id: "blog-letitrip-escrow-launch",
    title: "LetItRip Now Has Full Escrow Protection — Here's How It Works",
    slug: "letitrip-escrow-launch",
    excerpt: "Every purchase on LetItRip is now protected by escrow. Your payment is held securely until you confirm delivery. Here's what that means for you.",
    content: `<h2>What Changed</h2><p>All payments on LetItRip now go through escrow via Razorpay. This means your money is held by LetItRip — not sent directly to the seller. The seller only gets paid after you confirm delivery (or 7 days pass without a dispute).</p><h2>How It Protects Buyers</h2><p>If the item doesn't arrive, isn't as described, or is counterfeit — you open a dispute and your money is returned. No chasing sellers. No "send money first, trust me bro." Professional marketplace standards.</p><h2>How It Protects Sellers</h2><p>Sellers are protected from fraudulent chargebacks. Once the buyer confirms delivery, the payment is released. If a buyer tries to scam a seller, our mediation team reviews the evidence and rules fairly.</p><h2>UPI / Card / Net Banking</h2><p>Escrow works with all payment methods — UPI (GPay, PhonePe, Paytm), credit/debit cards, and net banking. The checkout experience is the same; the protection is invisible but always active.</p>`,
    category: "updates",
    tags: ["escrow", "launch", "buyer-protection", "razorpay", "feature"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(45),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 4,
    views: 7200,
    metaTitle: "Escrow Protection Now Live on LetItRip",
    metaDescription: "LetItRip's escrow payment system — how it protects buyers and sellers on every transaction.",
    createdAt: daysAgo(48),
    updatedAt: daysAgo(45),
  },

  {
    id: "blog-seller-verification-program",
    title: "Meet Our Verified Seller Program — What It Means for You",
    slug: "seller-verification-program",
    excerpt: "Every seller on LetItRip goes through manual verification. Here's what we check, why it matters, and how to get verified yourself.",
    content: `<h2>What We Verify</h2><p>Every seller application is manually reviewed by our team. We check: government ID (PAN/Aadhaar), store photos (inventory + packaging setup), previous selling history (if any), and a live video call to verify identity.</p><h2>Why It Matters</h2><p>Verified sellers have a 98% positive feedback rate on LetItRip. Unverified platforms see 15–20% dispute rates. Our verification eliminates the vast majority of scams before they happen.</p><h2>The Verified Badge</h2><p>Once approved, your store gets a ✓ Verified badge visible on every listing. Buyers filter by "Verified only" — which means verified sellers get more visibility and more sales.</p><h2>Become a Seller</h2><p>Go to Account → Become a Seller. The process takes ~48 hours. No listing fees, no monthly subscription. You only pay a commission when you make a sale.</p>`,
    category: "updates",
    tags: ["verification", "seller", "trust", "badge", "program"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(35),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 5,
    views: 4800,
    metaTitle: "Verified Seller Program | LetItRip",
    metaDescription: "How LetItRip's seller verification program works — and how to get verified.",
    createdAt: daysAgo(38),
    updatedAt: daysAgo(35),
  },

  {
    id: "blog-auction-feature-launch",
    title: "Live Auctions Are Here — Bid on Rare Collectibles",
    slug: "auction-feature-launch",
    excerpt: "LetItRip now supports live auctions with auto-extend, real-time bidding, and escrow-protected payments. Start bidding today.",
    content: `<h2>How Auctions Work</h2><p>Sellers list items as auctions with a starting bid and optional reserve price. Bidders place bids in real-time. The highest bidder when the auction ends wins the item.</p><h2>Anti-Sniping Protection</h2><p>If a bid is placed in the final 2 minutes, the auction auto-extends by 2 minutes. This prevents last-second sniping and gives every bidder a fair chance.</p><h2>Escrow Protection</h2><p>Won auctions go through the same escrow system as fixed-price purchases. Your money is held until you confirm delivery.</p><h2>What's Being Auctioned</h2><p>Rare 1st Edition cards, convention exclusive figures, vintage Beyblades, limited edition Hot Wheels, and more. Browse the Auctions page to see what's live now.</p>`,
    category: "updates",
    tags: ["auctions", "launch", "feature", "bidding", "auto-extend"],
    isFeatured: false,
    status: "archived",
    publishedAt: daysAgo(60),
    authorId: "user-admin-letitrip",
    authorName: "LetItRip Admin",
    readTimeMinutes: 4,
    views: 5600,
    metaTitle: "Live Auctions Now on LetItRip",
    metaDescription: "Bid on rare collectibles with auto-extend protection and escrow payments on LetItRip.",
    createdAt: daysAgo(65),
    updatedAt: daysAgo(60),
  },
];
