/*
 * WHY: Seeds 20 blog posts for LetItRip collectibles marketplace — content/SEO testing across all categories.
 * WHAT: 17 published + 2 draft + 1 archived. Mix of Beyblade-specific, broader collectibles (Pokémon, Hot Wheels,
 *       Gundam, Funko), marketplace guides, and community stories.
 *
 * EXPORTS:
 *   blogPostsSeedData — Array of Partial<BlogPostDocument> for seed runner
 *
 * @tag domain:blog
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import type { BlogPostDocument } from "../features/blog/schemas";
import { withBlogSearchTxt } from "./_helpers/search-txt-wrappers";
import { seedPhoto } from "./_helpers/media";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const _rawblogPostsSeedData: Partial<BlogPostDocument>[] = [

  // ── GUIDES (6) ────────────────────────────────────────────────────────────

  {
    id: "blog-spot-genuine-takara-tomy-beyblade",
    title: "How to Spot a Genuine Takara-Tomy Beyblade (vs. Counterfeit Clones)",
    slug: "spot-genuine-takara-tomy-beyblade",
    excerpt: "Learn the telltale signs that distinguish a genuine Takara-Tomy Beyblade from a cheap clone — from the laser-etched logo to the weight of the metal driver.",
    content: `<h2>The Laser-Etched Logo</h2><p>Genuine Takara-Tomy Beyblades have a crisp, laser-etched "TAKARA TOMY" logo on the underside of the layer or base. Clones use a shallow, blurry stamp that smudges under a fingernail scratch test.</p><img src="${seedPhoto("blog-content-image-genuine-beyblade-logo-1-20260101", 1000, 600)}" alt="Close-up of the genuine Takara-Tomy laser-etched logo" /><h2>Weight and Balance</h2><p>A genuine metal-fusion driver has a consistent, dense weight — clones often use lighter zinc alloy that feels noticeably hollow. Spin the beyblade on a flat glass surface: a genuine driver spins true with almost no wobble.</p><img src="${seedPhoto("blog-content-image-genuine-beyblade-weight-2-20260101", 1000, 600)}" alt="Weighing a genuine metal-fusion driver on a digital scale" /><h2>Sticker Print Quality</h2><p>Compare the face-bolt sticker under bright light. Genuine stickers have sharp gradient printing and a slightly raised clear-coat finish. Clone stickers are flat-printed and peel at the edges within weeks.</p>`,
    coverImage: { type: "image", url: seedPhoto("blog-cover-genuine-beyblade-20260101", 1200, 630), alt: "Genuine Takara-Tomy Beyblade close-up" },
    category: "guides",
    tags: ["authentication", "takara-tomy", "beyblade", "counterfeit"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(30),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    authorAvatar: seedPhoto("user-avatar-letitrip-admin-20260101", 400, 400),
    readTimeMinutes: 5,
    views: 4200,
    metaTitle: "How to Spot a Genuine Takara-Tomy Beyblade | LetItRip",
    metaDescription: "Learn how to spot genuine Takara-Tomy Beyblades — laser-etched logos, driver weight, sticker quality, and more.",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(30),
  },

  {
    id: "blog-sealed-vs-opened-beyblade-value",
    title: "Sealed vs. Opened — How Condition Affects Beyblade Resale Value",
    slug: "sealed-vs-opened-beyblade-value",
    excerpt: "A head-to-head look at what actually moves the needle on Beyblade resale price — sealed box premiums, tip wear, and launcher grip condition.",
    content: `<h2>Sealed Box — The Investment Grade</h2><p>A factory-sealed box with an unbroken shrink-wrap seal commands the highest resale premiums, especially for discontinued original-series and Metal Fight releases. Collectors treat sealed stock the way trading-card collectors treat unopened booster boxes.</p><img src="${seedPhoto("blog-content-image-sealed-beyblade-box-1-20260101", 1000, 600)}" alt="Factory-sealed Beyblade box with intact shrink wrap" /><h2>Tip Wear — The Sub-Grade That Matters</h2><p>For opened, battled beyblades, tip wear is the single biggest value factor. A sharp, unrounded tip with visible factory grooves grades far higher than a rounded, "sanded" tip from heavy stadium use.</p><h2>Launcher Grip Condition</h2><p>Ripcord launchers with clean, unfrayed grip tape and a tight ratchet mechanism add real value to a bundle. A stripped ratchet or fraying cord is an instant discount flag.</p><h2>Our Recommendation</h2><p>For investment: chase sealed, unopened stock. For a battle-ready collection: prioritize tip sharpness and launcher condition over cosmetic sticker wear.</p>`,
    coverImage: { type: "image", url: seedPhoto("blog-cover-sealed-vs-opened-beyblade-20260101", 1200, 630), alt: "Sealed and opened Beyblade boxes side by side" },
    category: "guides",
    tags: ["condition", "sealed", "tip-wear", "beyblade", "investment"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(25),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    authorAvatar: seedPhoto("user-avatar-letitrip-admin-20260101", 400, 400),
    readTimeMinutes: 7,
    views: 3800,
    metaTitle: "Sealed vs. Opened — Beyblade Condition & Resale Value | LetItRip",
    metaDescription: "What actually affects Beyblade resale value — sealed box premiums, tip wear grading, and launcher condition.",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(25),
  },

  {
    id: "blog-complete-beyblade-x-series-guide",
    title: "Complete Beyblade X Series Guide — Every Wave and Value",
    slug: "complete-beyblade-x-series-guide",
    excerpt: "Every Beyblade X wave released so far — from the BX-01 starter line to the latest BX-08 wave — with current market values.",
    content: `<h2>The Starter Waves</h2><p>BX-01 through BX-04 introduced the core X-series parts — Blade, Ratchet, and Bit — replacing the old layer/disk/driver system entirely. Sealed starters from these early waves are already appreciating.</p><img src="${seedPhoto("blog-content-image-beyblade-x-waves-1-20260101", 1000, 600)}" alt="Beyblade X starter wave lineup" /><h2>BX-05 through BX-08 (2025-2026)</h2><p>The current generation. Each piece in sealed condition ranges from ₹500-₹1,200. A complete wave set? Over ₹8,000.</p><h2>Later Waves</h2><p>Limited convention exclusives, gold-finish promos, and various starter-set reprints. Values range from ₹300 for common reprints to ₹5,000+ for rare promotional versions.</p>`,
    coverImage: { type: "image", url: seedPhoto("blog-cover-beyblade-x-guide-20260101", 1200, 630), alt: "Beyblade X series wave lineup" },
    category: "guides",
    tags: ["beyblade-x", "guide", "waves", "values"],
    isFeatured: false,
    status: "draft",
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    authorAvatar: seedPhoto("user-avatar-letitrip-admin-20260101", 400, 400),
    readTimeMinutes: 10,
    views: 0,
    metaTitle: "Complete Beyblade X Series Guide — Every Wave & Value | LetItRip",
    metaDescription: "Every Beyblade X wave from BX-01 to the latest release — market values and collecting tips.",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },

  {
    id: "blog-beginners-guide-hot-wheels-collecting",
    title: "Beginner's Guide to Hot Wheels Collecting in India",
    slug: "beginners-guide-hot-wheels-collecting",
    excerpt: "From mainlines to Super Treasure Hunts — everything you need to know to start your Hot Wheels collection without breaking the bank.",
    content: `<h2>Understanding the Tiers</h2><p><strong>Mainlines</strong> — ₹100–₹200 retail, the backbone of any collection. <strong>Premium</strong> — ₹400–₹600, metal/metal construction with Real Riders rubber tires. <strong>Car Culture</strong> — ₹700–₹1,000, themed sets with premium details. <strong>RLC (Red Line Club)</strong> — membership exclusive, ₹2,000–₹5,000+.</p><h2>Treasure Hunts</h2><p>Regular TH cards have a flame logo. Super Treasure Hunts (STH) have Spectraflame paint + Real Riders — roughly 1 per 15 cases. STHs command ₹2,000–₹10,000+ depending on the casting.</p><h2>Storage Tips</h2><p>Keep carded cars in protector cases. Loose cars in padded compartment boxes. Never store in direct sunlight — Spectraflame paint fades permanently.</p>`,
    category: "guides",
    tags: ["hot-wheels", "diecast", "collecting", "beginners", "treasure-hunt"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(18),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 8,
    views: 3100,
    metaTitle: "Beginner's Guide to Hot Wheels Collecting | LetItRip",
    metaDescription: "Start your Hot Wheels collection in India — mainlines, Treasure Hunts, storage, and where to find rare castings.",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(18),
  },

  {
    id: "blog-gundam-model-kit-grades-explained",
    title: "Gundam Model Kit Grades Explained: HG vs RG vs MG vs PG",
    slug: "gundam-model-kit-grades-explained",
    excerpt: "Not sure which Gundam grade to start with? Here's a detailed breakdown of every Bandai grade — from the beginner-friendly HG to the massive Perfect Grade.",
    // audit-money-units-ok: prose HTML content — "1/144 Scale"/"1/100 Scale" are model-kit scale ratios, not paise math
    content: `<h2>High Grade (HG) — 1/144 Scale</h2><p>The entry point for most builders. ~100 parts, snap-fit (no glue needed), completes in 2–3 hours. ₹800–₹2,000. Great articulation for the price.</p><h2>Real Grade (RG) — 1/144 Scale</h2><p>Master Grade detail at HG size. ~200 parts, pre-colored inner frame. More fragile than HG due to small parts. ₹1,800–₹3,500. The RG Nu Gundam and RG Wing Zero are fan favorites.</p><h2>Master Grade (MG) — 1/100 Scale</h2><p>The collector's standard. ~400 parts, fully detailed inner frame, excellent poseability. ₹3,500–₹8,000. Build time: 6–12 hours. MG Barbatos and MG Freedom 2.0 are top sellers on LetItRip.</p><h2>Perfect Grade (PG) — 1/60 Scale</h2><p>The pinnacle. ~800+ parts, LED-compatible, museum-quality detail. ₹12,000–₹25,000+. Build time: 20–40 hours. A showpiece, not a toy.</p><h2>Other Grades</h2><p><strong>SD</strong> (Super Deformed) — chibi proportions, great for kids. <strong>EG</strong> (Entry Grade) — simplified build, no tools needed. <strong>MGEX</strong> — MG with extreme detail (Unicorn Gundam only). <strong>PG Unleashed</strong> — beyond PG, the ultimate kit.</p>`,
    category: "guides",
    tags: ["gundam", "bandai", "model-kits", "hg", "mg", "rg", "pg"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(12),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 7,
    views: 2600,
    metaTitle: "Gundam Model Kit Grades Explained | LetItRip",
    metaDescription: "HG vs RG vs MG vs PG — understand every Gundam grade before you buy on LetItRip.",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(12),
  },

  {
    id: "blog-beyblade-x-vs-burst-comparison",
    title: "Beyblade X vs Burst: What's Changed and Is It Worth Switching?",
    slug: "beyblade-x-vs-burst-comparison",
    excerpt: "Beyblade X brought a whole new system — Xtreme Dash rails, new launcher, and incompatible parts. Here's whether the upgrade is worth it for Indian bladers.",
    content: `<h2>The Big Changes</h2><p>Beyblade X introduced the <strong>Xtreme Stadium</strong> with dash rails that accelerate beyblades mid-battle. The launcher mechanism is completely redesigned — smoother pull, more consistent spin. Parts are NOT compatible with Burst.</p><h2>Performance Comparison</h2><p>X beyblades spin longer out of the box thanks to better bearing tips. Burst had more customization depth (3 parts vs X's 3-layer system). X battles are faster and more aggressive due to the rail system.</p><h2>Availability in India</h2><p>Takara-Tomy X is available through importers on LetItRip. Hasbro X (budget version) is easier to find in retail stores. For competitive play, always go Takara-Tomy.</p><h2>Verdict</h2><p>If you're starting fresh: go X. If you have a big Burst collection: keep both systems. X stadiums work fine for casual Burst battles too — just no rail acceleration.</p>`,
    category: "guides",
    tags: ["beyblade", "beyblade-x", "burst", "takara-tomy", "comparison"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(8),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 6,
    views: 1900,
    metaTitle: "Beyblade X vs Burst Comparison | LetItRip",
    metaDescription: "Beyblade X vs Burst — what changed, part compatibility, and whether Indian bladers should switch.",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },

  // ── NEWS (4) ──────────────────────────────────────────────────────────────

  {
    id: "blog-top-10-most-valuable-vintage-beyblades",
    title: "Top 10 Most Valuable Vintage Beyblades",
    slug: "top-10-most-valuable-vintage-beyblades",
    excerpt: "From the legendary original-series Dragoon Storm to the elusive tournament-only L-Drago variants — these are the beyblades every collector dreams of.",
    content: `<h2>1. Tournament-Exclusive Gold Dragoon (2000)</h2><p>The rarest original-series beyblade ever distributed. Only handed out at the Japan national finals. Estimated value: over ₹4 lakh.</p><img src="${seedPhoto("blog-content-image-top10-tournament-gold-1-20260101", 1000, 600)}" alt="Tournament-exclusive gold Dragoon beyblade" /><h2>2. Beyblade Original Dragoon Storm, Sealed</h2><p>Tyson's signature spinner in sealed, factory condition. Sealed copies sell for ₹1.5-2.5 lakh.</p><h2>3. Beyblade Metal Lightning L-Drago, Sealed</h2><p>Kai's iconic rival spinner. A sealed Metal Lightning L-Drago commands ₹80,000-1.2 lakh.</p><h2>4. Complete Original-Series Starter Set (all 5 pieces, sealed)</h2><p>All five original-series starter beyblades still sealed — virtually impossible to assemble. Set value: over ₹6 lakh.</p><img src="${seedPhoto("blog-content-image-top10-starter-set-2-20260101", 1000, 600)}" alt="Complete original-series Beyblade starter set" /><h2>5-10</h2><p>Metal Fusion Storm Pegasus (sealed), Metal Fight Flame Sagittario (sealed), Burst Valkyrie tournament promo, Burst Regalia Genesis limited run, original-series Dranzer S first-print, and Driger V arena-exclusive gold edition.</p>`,
    coverImage: { type: "image", url: seedPhoto("blog-cover-top10-vintage-beyblade-20260101", 1200, 630), alt: "Vintage Beyblade collection" },
    category: "news",
    tags: ["top-10", "vintage", "investment", "rare-beyblades"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(20),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    authorAvatar: seedPhoto("user-avatar-letitrip-admin-20260101", 400, 400),
    readTimeMinutes: 8,
    views: 6100,
    metaTitle: "Top 10 Most Valuable Vintage Beyblades | LetItRip",
    metaDescription: "The 10 most expensive vintage Beyblades from the original series to Metal Fight.",
    createdAt: daysAgo(22),
    updatedAt: daysAgo(20),
  },

  {
    id: "blog-pokemon-sv-prismatic-evolutions",
    title: "Pokémon SV Prismatic Evolutions: What Indian Collectors Need to Know",
    slug: "pokemon-sv-prismatic-evolutions",
    excerpt: "Prismatic Evolutions is the hottest Pokémon set in 2026 — here's the pull rates, chase cards, and pricing for Indian collectors.",
    content: `<h2>The Chase Cards</h2><p>Prismatic Evolutions features all Eeveelution illustration rares + the Eevee gold star. The <strong>Umbreon illustration rare</strong> is the #1 chase card — commanding ₹40,000+ raw and ₹1.5 lakh+ in PSA 10.</p><h2>Pull Rates</h2><p>Illustration rare: ~1 in 25 packs. Special art rare: ~1 in 50 packs. Gold star: ~1 in 200 packs. The odds are brutal — most collectors buy singles on LetItRip instead of gambling on packs.</p><h2>Indian Market Pricing</h2><p>Booster boxes import at ₹6,000–₹8,000 (vs ₹4,000 US retail). ETBs at ₹4,500–₹6,000. The premium is due to import duties + limited official distribution in India. Pre-order on LetItRip to lock in the lowest price.</p>`,
    category: "news",
    tags: ["pokemon", "prismatic-evolutions", "trading-cards", "pricing", "chase-cards"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(7),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 6,
    views: 5200,
    metaTitle: "Pokémon Prismatic Evolutions — Indian Collector Guide | LetItRip",
    metaDescription: "Pull rates, chase cards, and Indian market pricing for Pokémon SV Prismatic Evolutions.",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },

  {
    id: "blog-funko-pop-india-market-2026",
    title: "The State of Funko Pop Collecting in India — 2026 Edition",
    slug: "funko-pop-india-market-2026",
    excerpt: "Funko Pop has exploded in India. Here's the market landscape — exclusive sourcing, pricing trends, and the most sought-after figures.",
    content: `<h2>Market Growth</h2><p>India's Funko Pop market has grown 3x since 2024, driven by anime Pops (Dragon Ball, Naruto, One Piece, Jujutsu Kaisen) and Marvel/Star Wars crossover appeal. LetItRip now has over 200 Funko listings across 5 verified stores.</p><h2>Exclusive Sourcing</h2><p>Convention exclusives (SDCC, NYCC) are the hardest to source. Indian collectors rely on importers who attend or have proxies at US conventions. Expect a 2–3x markup over US retail. Store exclusives (Hot Topic, BoxLunch, Target) are slightly easier via authorized resellers.</p><h2>Chase Variants</h2><p>Chase Pops (1-in-6 ratio) command a 3–5x premium. Glow-in-the-dark chases and flocked variants are the most popular in the Indian market. Always verify the chase sticker — counterfeits exist.</p><h2>Storage & Display</h2><p>Pop protectors (₹50–₹100 each) are essential. UV-filtering acrylic display cases for grails. Never store in direct sunlight — window box printing fades within months.</p>`,
    category: "news",
    tags: ["funko", "pop", "india", "market-trends", "collecting"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(14),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 7,
    views: 2400,
    metaTitle: "Funko Pop Collecting in India 2026 | LetItRip",
    metaDescription: "The state of Funko Pop collecting in India — exclusives, chase variants, and market trends.",
    createdAt: daysAgo(16),
    updatedAt: daysAgo(14),
  },

  {
    id: "blog-tomica-vs-hot-wheels-india",
    title: "Tomica vs Hot Wheels: The Diecast Battle in India",
    slug: "tomica-vs-hot-wheels-india",
    excerpt: "Two diecast giants go head-to-head. Which one offers better value, detail, and collectibility for Indian enthusiasts?",
    content: `<h2>Scale & Detail</h2><p>Tomica uses variable scale (roughly 1/60–1/64) to keep each model proportionally accurate in the hand. Hot Wheels uses a fixed 1/64 scale. Result: Tomica models look proportionally better; Hot Wheels are more consistent in a display.</p><h2>Build Quality</h2><p>Tomica models have working suspension and opening doors/hoods as standard — even on mainline ₹300 models. Hot Wheels mainlines are simpler (no opening parts) but Hot Wheels Premium (₹500+) matches Tomica quality.</p><h2>JDM & India Market</h2><p>Tomica dominates for JDM collectors (GT-R, Supra, AE86, Civic Type R). Hot Wheels wins for American muscle, European exotics, and fantasy castings. For Indian vehicles, Tomica has released exclusive India models (Maruti Swift, Tata Nexon) — highly collectible.</p><h2>Verdict</h2><p>Both. Seriously — most Indian collectors collect both. Tomica for realistic detail, Hot Wheels for variety and Treasure Hunt thrill.</p>`,
    category: "news",
    tags: ["tomica", "hot-wheels", "diecast", "comparison", "jdm"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(22),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 6,
    views: 1800,
    metaTitle: "Tomica vs Hot Wheels — Diecast Battle in India | LetItRip",
    metaDescription: "Tomica vs Hot Wheels — detail, build quality, and collecting value for Indian diecast enthusiasts.",
    createdAt: daysAgo(24),
    updatedAt: daysAgo(22),
  },

  // ── TIPS (4) ──────────────────────────────────────────────────────────────

  {
    id: "blog-metal-fight-hidden-gems",
    title: "Metal Fight Hidden Gems: Undervalued Beyblades from the 2009-2012 Era",
    slug: "metal-fight-hidden-gems",
    excerpt: "The Metal Fight era produced some of the most undervalued beyblades in collecting history. Here are the picks smart collectors are buying now.",
    content: `<h2>Why Metal Fight Beyblades Are Undervalued</h2><p>The Metal Fight era (2009-2012) coincided with peak Beyblade anime popularity but many collectors focus exclusively on the original 1999-2003 series. This creates a pricing gap.</p><img src="${seedPhoto("blog-content-image-metal-fight-gems-1-20260101", 1000, 600)}" alt="Metal Fight era Beyblade lineup" /><h2>Metal Fight Picks</h2><p><strong>Metal Storm Pegasus</strong> — the fan-favorite protagonist spinner. Sealed copies are still affordable at ₹1,500-₹2,500.</p><p><strong>Metal Flame Sagittario</strong> — one of the most competitively impactful attack types ever. Sealed condition commands ₹3,500-₹5,000.</p><p><strong>Rare 4D System variants</strong> — low print run makes these a sleeper investment.</p>`,
    coverImage: { type: "image", url: seedPhoto("blog-cover-metal-fight-gems-20260101", 1200, 630), alt: "Metal Fight Beyblade collection" },
    category: "tips",
    tags: ["metal-fight", "hidden-gems", "investment", "beyblade"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(15),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    authorAvatar: seedPhoto("user-avatar-letitrip-admin-20260101", 400, 400),
    readTimeMinutes: 6,
    views: 2900,
    metaTitle: "Metal Fight Hidden Gems — Undervalued Beyblades | LetItRip",
    metaDescription: "Discover undervalued Metal Fight era Beyblades that smart collectors are buying now.",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(15),
  },

  {
    id: "blog-protect-collectibles-indian-climate",
    title: "How to Protect Your Collectibles in India's Climate",
    slug: "protect-collectibles-indian-climate",
    excerpt: "Humidity, dust, and monsoon season are the biggest enemies of collectibles in India. Here's how to keep your cards, figures, and kits safe year-round.",
    content: `<h2>The Humidity Problem</h2><p>India's average humidity is 60–80% — far above the 40–50% ideal for collectibles. Excess moisture causes card warping, sticker lifting on Funko boxes, paint degradation on diecast, and mold growth on cardboard packaging.</p><h2>Essential Gear</h2><p><strong>Silica gel packets</strong> — ₹200 for a 20-pack. Place 2–3 in every storage box. Replace when they turn pink/clear. <strong>Dehumidifier</strong> — ₹3,000–₹8,000 for a 10L/day unit. Essential for display rooms. <strong>UV-filtering display cases</strong> — prevents sunlight fading on Spectraflame (Hot Wheels), holo cards, and figure paint.</p><h2>Monsoon Protocol</h2><p>During June–September: seal all open storage, move ground-level boxes to shelves, check silica gel weekly. If you're in a flood-prone area, consider off-site storage for high-value grails.</p><h2>Card-Specific Tips</h2><p>Double-sleeve valuable cards (penny sleeve + top-loader). Store in a binder with O-ring closure, not D-ring. Keep graded slabs in padded boxes — PSA cases crack if dropped.</p>`,
    category: "tips",
    tags: ["storage", "climate", "humidity", "india", "preservation"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(10),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 7,
    views: 3500,
    metaTitle: "Protect Collectibles in India's Climate | LetItRip",
    metaDescription: "Humidity, dust, and monsoon tips — how to protect your collectibles in Indian weather.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
  },

  {
    id: "blog-selling-tips-letitrip",
    title: "10 Tips to Sell Faster on LetItRip",
    slug: "selling-tips-letitrip",
    excerpt: "From photography to pricing to descriptions — proven tactics to make your listings sell faster on LetItRip.",
    content: `<h2>1. Photograph Everything</h2><p>Front, back, edges, corners, holo pattern. Natural light. White background. Minimum 4 photos per listing.</p><h2>2. Price Competitively</h2><p>Check what similar items sold for on LetItRip in the last 30 days. Price 5–10% below the lowest active listing for a fast sale.</p><h2>3. Write Honest Descriptions</h2><p>State the exact condition. Mention every flaw. Buyers trust sellers who are upfront about imperfections — they'll come back.</p><h2>4. Respond to Offers Within 2 Hours</h2><p>Quick responses convert. Buyers often make offers to multiple sellers — the first response wins.</p><h2>5. Ship the Same Day</h2><p>Buyers who receive fast shipping leave 5-star reviews. 5-star reviews bring more buyers. It's a flywheel.</p><h2>6–10</h2><p>Use accurate category tags. Add a YouTube unboxing link (see the video above). Offer bundle discounts. Cross-reference to your other listings. Keep your store description updated.</p>`,
    youtubeId: "dQw4w9WgXcQ",
    category: "tips",
    tags: ["selling", "tips", "photography", "pricing", "seller-guide"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(5),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 5,
    views: 1600,
    metaTitle: "10 Tips to Sell Faster on LetItRip",
    metaDescription: "Proven selling tactics — photography, pricing, and descriptions that convert on LetItRip.",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },

  {
    id: "blog-one-piece-tcg-india-primer",
    title: "One Piece TCG in India: A Complete Primer",
    slug: "one-piece-tcg-india-primer",
    excerpt: "One Piece Card Game has arrived in India. Here's everything you need to know about the game, the sets, and which cards to collect.",
    content: `<h2>What Is One Piece TCG?</h2><p>Released by Bandai in 2022, the One Piece Card Game has quickly become one of the top 3 trading card games globally. It uses a leader + character + event + stage system, with DON!! cards as the energy resource.</p><h2>Sets Available in India</h2><p>Romance Dawn (OP-01) through Wings of the Captain (OP-06) are available through importers on LetItRip. Expect a 1.5–2x markup over Japanese retail due to import costs.</p><h2>Chase Cards</h2><p>Alternate art leaders and manga art special rares are the most sought-after. <strong>Luffy Gear 5 (OP-05 alt art)</strong> — ₹15,000+. <strong>Shanks alt art (OP-01)</strong> — ₹8,000+. <strong>Nami alt art (OP-01)</strong> — ₹12,000+.</p><h2>Investment Potential</h2><p>One Piece TCG is undervalued compared to Pokémon. Early sets (OP-01, OP-02) are already appreciating. Buy singles of alt art leaders now — the floor is rising.</p>`,
    category: "tips",
    tags: ["one-piece", "bandai", "trading-cards", "primer", "tcg"],
    isFeatured: false,
    status: "draft",
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 8,
    views: 0,
    metaTitle: "One Piece TCG in India — Complete Primer | LetItRip",
    metaDescription: "Everything Indian collectors need to know about One Piece Card Game — sets, chase cards, and investment.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },

  // ── COMMUNITY (3) ─────────────────────────────────────────────────────────

  {
    id: "blog-authenticating-beyblades",
    title: "How a Verified Store Authenticates Every Beyblade",
    slug: "authenticating-beyblades",
    excerpt: "A behind-the-scenes look at how verified sellers on LetItRip check every beyblade before listing — logo tests, weight checks, and spin-balance inspection.",
    content: `<h2>The 5-Point Authentication Process</h2><p>Every beyblade listed by top verified stores goes through a rigorous 5-point check:</p><ol><li><strong>Logo Test</strong> — Genuine Takara-Tomy pieces have a specific laser-etched depth and clarity when checked under raking light.</li><li><strong>Weight Check</strong> — A genuine metal-fusion driver weighs within a tight factory tolerance verified on a digital scale.</li><li><strong>Spin-Balance Test</strong> — Each layer/driver combo is spin-tested on a flat glass surface; genuine parts spin true with minimal wobble.</li><li><strong>Sticker Print Inspection</strong> — Under 10x magnification, genuine face-bolt stickers show sharp gradient printing and a raised clear-coat.</li><li><strong>Ratchet & Grip Inspection</strong> — Check the launcher for a tight ratchet mechanism and unfrayed grip tape.</li></ol>`,
    coverImage: { type: "image", url: seedPhoto("blog-cover-authenticating-beyblades-20260101", 1200, 630), alt: "Beyblade authentication process" },
    category: "community",
    tags: ["authentication", "verification", "counterfeit", "beyblade"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(10),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 5,
    views: 3400,
    metaTitle: "How Verified Stores Authenticate Beyblades | LetItRip",
    metaDescription: "The 5-point authentication process used by verified stores to check every beyblade on LetItRip.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
  },

  {
    id: "blog-collector-spotlight-mumbai-gundam",
    title: "Collector Spotlight: Building India's Largest Gundam Collection in Mumbai",
    slug: "collector-spotlight-mumbai-gundam",
    excerpt: "Meet Arjun — a Mumbai software engineer with 200+ Gundam kits, a dedicated build room, and a mission to grow India's Gunpla community.",
    content: `<h2>The Collection</h2><p>Arjun started with a single HG RX-78-2 in 2019. Seven years later, his Mumbai apartment has a dedicated room with 200+ built kits across HG, RG, MG, and 3 Perfect Grades. The crown jewel: a painted and weathered PG Unleashed RX-78-2.</p><h2>The Build Process</h2><p>"I spend 2–3 hours every evening after work. It's meditation. The snap-fit assembly, the panel lining, the decals — there's something deeply satisfying about transforming a box of runners into a finished kit."</p><h2>Growing the Community</h2><p>Arjun runs a monthly Mumbai Gunpla meetup with 30+ regular attendees. "When I started, there were maybe 5 Gunpla builders I knew in all of Mumbai. Now there's a real community. LetItRip has helped — having a dedicated marketplace means people can actually find kits without paying 3x import markup."</p><h2>Advice for New Builders</h2><p>"Start with an HG. Don't buy a PG as your first kit — you'll get overwhelmed. Build 10–15 HGs, then try an RG. The skills transfer. And always — always — use a nipper, not scissors."</p>`,
    category: "community",
    tags: ["gundam", "spotlight", "mumbai", "gunpla", "community"],
    isFeatured: true,
    status: "published",
    publishedAt: daysAgo(3),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 6,
    views: 1200,
    metaTitle: "Collector Spotlight: Mumbai Gundam Collection | LetItRip",
    metaDescription: "Meet the Mumbai engineer building India's largest Gundam collection — 200+ kits and growing.",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },

  {
    id: "blog-india-collectibles-market-overview",
    title: "The Indian Collectibles Market in 2026: Where We Stand",
    slug: "india-collectibles-market-overview",
    excerpt: "From trading cards to action figures — a data-driven look at India's growing collectibles scene and what's driving the boom.",
    content: `<h2>The Numbers</h2><p>India's organized collectibles market is estimated at ₹2,500 crore in 2026, up from ₹800 crore in 2022. Trading cards (Pokémon, One Piece) account for ~40%, followed by action figures (~25%), diecast (~15%), and model kits/spinning tops (~10%).</p><h2>What's Driving Growth</h2><p><strong>Anime streaming</strong> — India is now the #3 market for anime streaming (Crunchyroll, Netflix anime). Fans who watch Dragon Ball, Naruto, and One Piece naturally become collectors. <strong>Social media</strong> — Instagram and YouTube unboxing/pull content drives awareness. <strong>Verified platforms</strong> — LetItRip and similar platforms have made it safe to buy collectibles online, reducing the counterfeit risk that previously kept buyers away.</p><h2>What's Hot in 2026</h2><p>Pokémon cards remain #1 by volume. Beyblade X is the fastest-growing category by transaction value. Gundam is niche but intensely loyal. Hot Wheels Super Treasure Hunts are the "gateway drug" for new collectors.</p><h2>What's Next</h2><p>Sports cards (cricket, specifically) are the next frontier. Digital collectibles (graded item NFTs backed by physical) are being explored. LetItRip is building infrastructure for both.</p>`,
    category: "community",
    tags: ["india", "market", "overview", "trends", "2026"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(16),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 8,
    views: 4100,
    metaTitle: "Indian Collectibles Market 2026 | LetItRip",
    metaDescription: "Data-driven overview of India's collectibles market — trading cards, figures, diecast, and what's driving growth.",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(16),
  },

  // ── UPDATES (3) ───────────────────────────────────────────────────────────

  {
    id: "blog-letitrip-escrow-launch",
    title: "LetItRip Now Has Full Escrow Protection — Here's How It Works",
    slug: "letitrip-escrow-launch",
    excerpt: "Every purchase on LetItRip is now protected by escrow. Your payment is held securely until you confirm delivery. Here's what that means for you.",
    content: `<h2>What Changed</h2><p>All payments on LetItRip now go through escrow via Razorpay. This means your money is held by LetItRip — not sent directly to the seller. The seller only gets paid after you confirm delivery (or 7 days pass without a dispute).</p><h2>How It Protects Buyers</h2><p>If the item doesn't arrive, isn't as described, or is counterfeit — you open a dispute and your money is returned. No chasing sellers. No "send money first, trust me bro." Professional marketplace standards.</p><h2>How It Protects Sellers</h2><p>Sellers are protected from fraudulent chargebacks. Once the buyer confirms delivery, the payment is released. If a buyer tries to scam a seller, our mediation team reviews the evidence and rules fairly.</p><h2>UPI / Card / Net Banking</h2><p>Escrow works with all payment methods — UPI (GPay, PhonePe, Paytm), credit/debit cards, and net banking. The checkout experience is the same; the protection is invisible but always active.</p>`,
    category: "updates",
    tags: ["escrow", "launch", "buyer-protection", "razorpay", "feature"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(45),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 4,
    views: 7200,
    metaTitle: "Escrow Protection Now Live on LetItRip",
    metaDescription: "LetItRip's escrow payment system — how it protects buyers and sellers on every transaction.",
    createdAt: daysAgo(48),
    updatedAt: daysAgo(45),
  },

  {
    id: "blog-seller-verification-program",
    title: "Meet Our Verified Seller Program — What It Means for You",
    slug: "seller-verification-program",
    excerpt: "Every seller on LetItRip goes through manual verification. Here's what we check, why it matters, and how to get verified yourself.",
    content: `<h2>What We Verify</h2><p>Every seller application is manually reviewed by our team. We check: government ID (PAN/Aadhaar), store photos (inventory + packaging setup), previous selling history (if any), and a live video call to verify identity.</p><h2>Why It Matters</h2><p>Verified sellers have a 98% positive feedback rate on LetItRip. Unverified platforms see 15–20% dispute rates. Our verification eliminates the vast majority of scams before they happen.</p><h2>The Verified Badge</h2><p>Once approved, your store gets a ✓ Verified badge visible on every listing. Buyers filter by "Verified only" — which means verified sellers get more visibility and more sales.</p><h2>Become a Seller</h2><p>Go to Account → Become a Seller. The process takes ~48 hours. No listing fees, no monthly subscription. You only pay a commission when you make a sale.</p>`,
    category: "updates",
    tags: ["verification", "seller", "trust", "badge", "program"],
    isFeatured: false,
    status: "published",
    publishedAt: daysAgo(35),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 5,
    views: 4800,
    metaTitle: "Verified Seller Program | LetItRip",
    metaDescription: "How LetItRip's seller verification program works — and how to get verified.",
    createdAt: daysAgo(38),
    updatedAt: daysAgo(35),
  },

  {
    id: "blog-auction-feature-launch",
    title: "Live Auctions Are Here — Bid on Rare Collectibles",
    slug: "auction-feature-launch",
    excerpt: "LetItRip now supports live auctions with auto-extend, real-time bidding, and escrow-protected payments. Start bidding today.",
    content: `<h2>How Auctions Work</h2><p>Sellers list items as auctions with a starting bid and optional reserve price. Bidders place bids in real-time. The highest bidder when the auction ends wins the item.</p><h2>Anti-Sniping Protection</h2><p>If a bid is placed in the final 2 minutes, the auction auto-extends by 2 minutes. This prevents last-second sniping and gives every bidder a fair chance.</p><h2>Escrow Protection</h2><p>Won auctions go through the same escrow system as fixed-price purchases. Your money is held until you confirm delivery.</p><h2>What's Being Auctioned</h2><p>Rare 1st Edition cards, convention exclusive figures, vintage Beyblades, limited edition Hot Wheels, and more. Browse the Auctions page to see what's live now.</p>`,
    category: "updates",
    tags: ["auctions", "launch", "feature", "bidding", "auto-extend"],
    isFeatured: false,
    status: "archived",
    publishedAt: daysAgo(60),
    authorId: "user-admin-letitrip",
    authorName: "Mock User 1",
    readTimeMinutes: 4,
    views: 5600,
    metaTitle: "Live Auctions Now on LetItRip",
    metaDescription: "Bid on rare collectibles with auto-extend protection and escrow payments on LetItRip.",
    createdAt: daysAgo(65),
    updatedAt: daysAgo(60),
  },
];

/**
 * Tokens derived here, not per record — see _helpers/search-txt-wrappers.ts for
 * why the wrapper form is what makes omission impossible.
 */
export const blogPostsSeedData: Partial<BlogPostDocument>[] =
  _rawblogPostsSeedData.map(withBlogSearchTxt);
