/**
 * Brands Seed Data
 * Franchise and collectible brands referenced across products and homepage sections.
 */

import type { BrandDocument } from "../features/brands/schemas";

const NOW = new Date();

export const brandsSeedData: BrandDocument[] = [
  {
    id: "brand-hot-wheels",
    name: "Hot Wheels",
    slug: "brand-hot-wheels",
    description: "Iconic die-cast toy car brand by Mattel. Home to thousands of collectible models, themed tracks, and rare treasure hunts.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop",
    website: "https://hotwheels.mattel.com",
    isActive: true,
    displayOrder: 1,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-beyblade",
    name: "Beyblade",
    slug: "brand-beyblade",
    description: "Spinning top battle game franchise by Takara Tomy. Features competitive Burst, X, and classic Metal Fight lines.",
    logoURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1200&h=400&fit=crop",
    website: "https://beyblade.hasbro.com",
    isActive: true,
    displayOrder: 2,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-pokemon",
    name: "Pokémon",
    slug: "brand-pokemon",
    description: "Global media franchise by The Pokémon Company. Covering trading cards, figures, games, and collectibles.",
    logoURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop",
    website: "https://www.pokemon.com",
    isActive: true,
    displayOrder: 3,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-transformers",
    name: "Transformers",
    slug: "brand-transformers",
    description: "Hasbro and Takara Tomy robots-in-disguise franchise. Features Autobots vs Decepticons across multiple generations.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop",
    website: "https://www.hasbro.com/transformers",
    isActive: true,
    displayOrder: 4,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-anime",
    name: "Anime Figures",
    slug: "brand-anime",
    description: "Premium Japanese anime figure collection including Nendoroids, figmas, and scale PVCs from top series.",
    logoURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&h=400&fit=crop",
    isActive: true,
    displayOrder: 5,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-lego",
    name: "LEGO",
    slug: "brand-lego",
    description: "World-famous Danish toy company. Licensed sets including Star Wars, Marvel, Technic, and City themes.",
    logoURL: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=1200&h=400&fit=crop",
    website: "https://www.lego.com",
    isActive: true,
    displayOrder: 6,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-marvel",
    name: "Marvel",
    slug: "brand-marvel",
    description: "Marvel Comics and Studios merchandise — Hasbro Marvel Legends, Funko Pops, and premium statues.",
    logoURL: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=1200&h=400&fit=crop",
    website: "https://www.marvel.com",
    isActive: true,
    displayOrder: 7,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-funko",
    name: "Funko",
    slug: "brand-funko",
    description: "Iconic vinyl figure brand. Pop!, Soda, and Bitty lines across movies, TV, games, anime, and sports.",
    logoURL: "https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1578292992345-7ee038c5fb7c?w=1200&h=400&fit=crop",
    website: "https://funko.com",
    isActive: true,
    displayOrder: 8,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-star-wars",
    name: "Star Wars",
    slug: "brand-star-wars",
    description: "Lucasfilm and Disney's galaxy far far away. Hasbro Black Series, Vintage Collection, and premium collectibles.",
    logoURL: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=1200&h=400&fit=crop",
    website: "https://www.starwars.com",
    isActive: true,
    displayOrder: 9,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-dc",
    name: "DC",
    slug: "brand-dc",
    description: "DC Comics collectibles — McFarlane Toys, NECA, and premium statues featuring Batman, Superman, and Justice League.",
    logoURL: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1200&h=400&fit=crop",
    website: "https://www.dc.com",
    isActive: true,
    displayOrder: 10,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-dragon-ball",
    name: "Dragon Ball",
    slug: "brand-dragon-ball",
    description: "Bandai Namco's Dragon Ball franchise — SH Figuarts, Dragon Stars, Ichibansho, and Master Stars Piece figures.",
    logoURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop",
    isActive: true,
    displayOrder: 11,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-naruto",
    name: "Naruto",
    slug: "brand-naruto",
    description: "Masashi Kishimoto's ninja world — figures, plushies, and collectibles from the Naruto and Boruto universe.",
    logoURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&h=400&fit=crop",
    isActive: true,
    displayOrder: 12,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-one-piece",
    name: "One Piece",
    slug: "brand-one-piece",
    description: "Eiichiro Oda's pirate adventure — premium figures, Figuarts ZERO, and Excellent Model series.",
    logoURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1200&h=400&fit=crop",
    isActive: true,
    displayOrder: 13,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-yugioh",
    name: "Yu-Gi-Oh!",
    slug: "brand-yugioh",
    description: "Konami's iconic trading card game. Booster packs, structure decks, and sealed tournament product.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop",
    website: "https://www.yugioh-card.com",
    isActive: true,
    displayOrder: 14,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "brand-nerf",
    name: "Nerf",
    slug: "brand-nerf",
    description: "Hasbro's foam dart blaster brand — Elite, Rival, Ultra, and Hyper series for all ages.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop",
    website: "https://www.hasbro.com/nerf",
    isActive: true,
    displayOrder: 15,
    productCount: 0,
    createdAt: NOW,
    updatedAt: NOW,
  },
];
