/**
 * Brands Seed Data — Collectibles Edition
 * 13 real brands covering: action figures, trading cards, diecast, spinning tops, model kits.
 * id === slug convention enforced throughout.
 */

import type { BrandDocument } from "../features/brands/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const brandsSeedData: BrandDocument[] = [
  {
    id: "brand-bandai",
    slug: "brand-bandai",
    name: "Bandai",
    description:
      "Japan's leading toy and hobby manufacturer. Home to Gundam plastic model kits (Gunpla), SH Figuarts, Dragon Ball figures, Digimon, Power Rangers, and premium collectibles.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop",
    website: "https://www.bandai.co.jp",
    country: "Japan",
    founded: 1950,
    isActive: true,
    displayOrder: 1,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-hasbro",
    slug: "brand-hasbro",
    name: "Hasbro",
    description:
      "American multinational toy and entertainment company. Makes Transformers, Marvel Legends, Star Wars Black Series, My Little Pony, Nerf, and G.I. Joe collectibles.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop&seed=hasbro",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop&seed=hasbro",
    website: "https://www.hasbro.com",
    country: "USA",
    founded: 1923,
    isActive: true,
    displayOrder: 2,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-takara-tomy",
    slug: "brand-takara-tomy",
    name: "Takara Tomy",
    description:
      "Iconic Japanese toy manufacturer formed by the merger of Takara and Tomy in 2006. Creates Beyblade Burst, Tomica diecast cars, Transformers (Japan), and Zoids.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop",
    website: "https://www.takaratomy.co.jp",
    country: "Japan",
    founded: 2006,
    isActive: true,
    displayOrder: 3,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-mattel",
    slug: "brand-mattel",
    name: "Mattel",
    description:
      "American toy giant behind Hot Wheels, Barbie, Masters of the Universe, UNO, and Fisher-Price. Hot Wheels alone has over 900 vehicle models released annually.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=mattel",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=mattel",
    website: "https://www.mattel.com",
    country: "USA",
    founded: 1945,
    isActive: true,
    displayOrder: 4,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-pokemon-company",
    slug: "brand-pokemon-company",
    name: "The Pokémon Company",
    description:
      "Japanese consortium managing the Pokémon intellectual property. Publishes the Pokémon Trading Card Game (TCG), video games, anime merchandise, and official licensed collectibles worldwide.",
    logoURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop",
    website: "https://www.pokemon.com",
    country: "Japan",
    founded: 1998,
    isActive: true,
    displayOrder: 5,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-konami",
    slug: "brand-konami",
    name: "Konami",
    description:
      "Japanese entertainment conglomerate best known for the Yu-Gi-Oh! Trading Card Game. Also produces Metal Gear, Silent Hill, and Castlevania merchandise and figures.",
    logoURL: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=1200&h=400&fit=crop",
    website: "https://www.konami.com",
    country: "Japan",
    founded: 1969,
    isActive: true,
    displayOrder: 6,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-funko",
    slug: "brand-funko",
    name: "Funko",
    description:
      "American pop-culture collectibles company. Iconic for Funko Pop! vinyl figures spanning thousands of licenses including Marvel, DC, anime, Disney, gaming, sports, and music.",
    logoURL: "https://images.unsplash.com/photo-1578292992345-7ee038c5fb7c?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1578292992345-7ee038c5fb7c?w=1200&h=400&fit=crop",
    website: "https://funko.com",
    country: "USA",
    founded: 1998,
    isActive: true,
    displayOrder: 7,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-neca",
    slug: "brand-neca",
    name: "NECA",
    description:
      "National Entertainment Collectibles Association — American designer and manufacturer of highly detailed action figures. Known for horror icons, Teenage Mutant Ninja Turtles, and video game characters.",
    logoURL: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1200&h=400&fit=crop",
    website: "https://www.necaonline.com",
    country: "USA",
    founded: 1996,
    isActive: true,
    displayOrder: 8,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-mcfarlane",
    slug: "brand-mcfarlane",
    name: "McFarlane Toys",
    description:
      "American action figure company founded by comic artist Todd McFarlane. Official DC Multiverse figures, Warhammer, Spawn, and premium collector statuettes with extraordinary detail.",
    logoURL: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=1200&h=400&fit=crop",
    website: "https://www.mcfarlane.com",
    country: "USA",
    founded: 1994,
    isActive: true,
    displayOrder: 9,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-good-smile",
    slug: "brand-good-smile",
    name: "Good Smile Company",
    description:
      "Japan's premier figure manufacturer. Producer of Nendoroids, figma, and high-end scale PVC figures. Official partner for Fate, Hatsune Miku, Sword Art Online, Re:Zero, and hundreds of anime series.",
    logoURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&h=400&fit=crop",
    website: "https://www.goodsmile.info",
    country: "Japan",
    founded: 2001,
    isActive: true,
    displayOrder: 10,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-hot-wheels",
    slug: "brand-hot-wheels",
    name: "Hot Wheels",
    description:
      "Mattel's iconic 1:64 scale die-cast vehicle brand since 1968. Treasure Hunt, Super Treasure Hunt, Car Culture, RLC exclusives, and track sets. Over 6 billion cars sold worldwide.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=hotwheels",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=hotwheels",
    website: "https://hotwheels.mattel.com",
    country: "USA",
    founded: 1968,
    isActive: true,
    displayOrder: 11,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-tomica",
    slug: "brand-tomica",
    name: "Tomica",
    description:
      "Takara Tomy's 1:64 scale Japanese diecast car series since 1970. Features authentic Japanese vehicles (Toyota, Honda, Nissan), emergency vehicles, and licensed premium Tomica Premium line.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=tomica",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=tomica",
    website: "https://www.takaratomy.co.jp/products/tomica",
    country: "Japan",
    founded: 1970,
    isActive: true,
    displayOrder: 12,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-beyblade",
    slug: "brand-beyblade",
    name: "Beyblade",
    description:
      "Takara Tomy's competitive spinning top battle franchise. Covers classic Metal Fight, Beyblade Burst, Beyblade X, and Hasbro-localized versions. Official tournaments held worldwide including India.",
    logoURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1200&h=400&fit=crop",
    website: "https://beyblade.takaratomy.co.jp",
    country: "Japan",
    founded: 1999,
    isActive: true,
    displayOrder: 13,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },

  // ── Extended brands (P26 expansion) ──────────────────────────────────────────

  {
    id: "brand-kotobukiya",
    slug: "brand-kotobukiya",
    name: "Kotobukiya",
    description:
      "Premium Japanese model kit and figure manufacturer. Famous for Frame Arms Girl, Megami Device, ARTFX statues, and licensed kits from Star Wars, Marvel, and DC. Known for detailed snap-fit kits requiring no glue.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop&seed=kotobukiya",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop&seed=kotobukiya",
    website: "https://www.kotobukiya.co.jp",
    country: "Japan",
    founded: 1947,
    isActive: true,
    displayOrder: 14,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-alter",
    slug: "brand-alter",
    name: "Alter",
    description:
      "High-end Japanese scale figure manufacturer under A+ Corporation. Renowned for exceptional paint quality and sculpt accuracy. Specialises in 1/7 and 1/8 scale anime figures from Re:Zero, Fate, and other popular IPs.",
    logoURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop",
    website: "https://alter-web.jp",
    country: "Japan",
    founded: 2000,
    isActive: true,
    displayOrder: 15,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-max-factory",
    slug: "brand-max-factory",
    name: "Max Factory",
    description:
      "Japanese figure manufacturer known for the figma articulated figure line and figFIX static figures. Partners with Good Smile Company. figma figures are prized for their wide articulation range and interchangeable parts.",
    logoURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop&seed=maxfactory",
    bannerURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop&seed=maxfactory",
    website: "https://www.maxfactory.jp",
    country: "Japan",
    founded: 1987,
    isActive: true,
    displayOrder: 16,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-medicom-toy",
    slug: "brand-medicom-toy",
    name: "Medicom Toy",
    description:
      "Japanese designer toy and collectible figure company. Creator of MAFEX (Miracle Action Figure EX) — highly articulated figures with film-accurate sculpts covering Batman, Spider-Man, and Star Wars. Also produces BE@RBRICK designer toys.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop&seed=medicom",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop&seed=medicom",
    website: "https://www.medicomtoy.co.jp",
    country: "Japan",
    founded: 1996,
    isActive: true,
    displayOrder: 17,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-bushiroad",
    slug: "brand-bushiroad",
    name: "Bushiroad",
    description:
      "Japanese trading card game publisher. Home to One Piece Card Game, Cardfight!! Vanguard, Weiß Schwarz, and Sword Art Online TCG. Growing fast in India's TCG community alongside Pokémon and Yu-Gi-Oh.",
    logoURL: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=1200&h=400&fit=crop",
    website: "https://www.bushiroad.com",
    country: "Japan",
    founded: 2007,
    isActive: true,
    displayOrder: 18,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-panini",
    slug: "brand-panini",
    name: "Panini",
    description:
      "Italian sticker and trading card company with global reach. Official partner for FIFA, NBA, NFL, ICC Cricket, and IPL trading cards. Popular in India for cricket and football card collections.",
    logoURL: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=200&h=200&fit=crop&seed=panini",
    bannerURL: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=1200&h=400&fit=crop&seed=panini",
    website: "https://www.paniniamerica.net",
    country: "Italy",
    founded: 1961,
    isActive: true,
    displayOrder: 19,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-spin-master",
    slug: "brand-spin-master",
    name: "Spin Master",
    description:
      "Canadian toy company known for Bakugan battle planet, Air Hogs, Paw Patrol, and Tech Deck. Bakugan has a dedicated competitive community in India with official tournaments.",
    logoURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=200&h=200&fit=crop&seed=spinmaster",
    bannerURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1200&h=400&fit=crop&seed=spinmaster",
    website: "https://www.spinmaster.com",
    country: "Canada",
    founded: 1994,
    isActive: true,
    displayOrder: 20,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-jakks-pacific",
    slug: "brand-jakks-pacific",
    name: "JAKKS Pacific",
    description:
      "American toy manufacturer producing licensed action figures for Nintendo (World of Nintendo), Disney, and WWE. Affordable 4-inch figure lines popular among budget collectors.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop&seed=jakks",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop&seed=jakks",
    website: "https://www.jakkspacific.com",
    country: "USA",
    founded: 1995,
    isActive: true,
    displayOrder: 21,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-corgi",
    slug: "brand-corgi",
    name: "Corgi",
    description:
      "British diecast vehicle manufacturer with a 70-year heritage. Iconic for James Bond DB5 in gold, aviation models, and classic British cars. Collector grade quality with opening parts and realistic detail.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=corgi",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=corgi",
    website: "https://www.corgi.co.uk",
    country: "UK",
    founded: 1956,
    isActive: true,
    displayOrder: 22,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-matchbox",
    slug: "brand-matchbox",
    name: "Matchbox",
    description:
      "Iconic British diecast toy car brand since 1953, now owned by Mattel. Known for 1:64 scale realistic vehicles. The Moving Parts line features opening hoods and doors. Beloved by Indian collectors for nostalgia value.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=matchbox",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=matchbox",
    website: "https://www.matchbox.com",
    country: "UK",
    founded: 1953,
    isActive: true,
    displayOrder: 23,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-mega-construx",
    slug: "brand-mega-construx",
    name: "Mega Construx",
    description:
      "Mattel's construction toy brand (now marketed as MEGA). Produces detailed building sets for Pokémon, Halo, Call of Duty, and Masters of the Universe. Pokémon MEGA sets are popular gift items for young collectors.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop&seed=mega",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop&seed=mega",
    website: "https://www.mega.us",
    country: "USA",
    founded: 2000,
    isActive: true,
    displayOrder: 24,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-sideshow-collectibles",
    slug: "brand-sideshow-collectibles",
    name: "Sideshow Collectibles",
    description:
      "Premium American collectible statue and figure manufacturer. Known for 1/4 scale and 1/6 scale premium statues for Marvel, DC, Star Wars, and horror franchises. Limited edition runs make these highly sought-after.",
    logoURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop&seed=sideshow",
    bannerURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop&seed=sideshow",
    website: "https://www.sideshowtoy.com",
    country: "USA",
    founded: 1994,
    isActive: true,
    displayOrder: 25,
    productCount: 0,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
  },
];
