/**
 * Brands Seed Data — Collectibles Edition
 * 13 real brands covering: action figures, trading cards, diecast, spinning tops, model kits.
 * id === slug convention enforced throughout.
 */

import type { BrandDocument } from "../features/brands/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const brandsSeedData: BrandDocument[] = [
  {
    id: "brand-bandai",
    slug: "brand-bandai",
    name: "Bandai",
    description:
      "Japan's leading toy and hobby manufacturer. Home to Gundam plastic model kits (Gunpla), SH Figuarts, Dragon Ball figures, Digimon, Power Rangers, and premium collectibles.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop",
    website: "https://www.bandai.co.jp",
    country: "Japan",
    founded: 1950,
    isActive: true,
    displayOrder: 1,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-hasbro",
    slug: "brand-hasbro",
    name: "Hasbro",
    description:
      "American multinational toy and entertainment company. Makes Transformers, Marvel Legends, Star Wars Black Series, My Little Pony, Nerf, and G.I. Joe collectibles.",
    logoURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop&seed=hasbro",
    bannerURL: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop&seed=hasbro",
    website: "https://www.hasbro.com",
    country: "USA",
    founded: 1923,
    isActive: true,
    displayOrder: 2,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-takara-tomy",
    slug: "brand-takara-tomy",
    name: "Takara Tomy",
    description:
      "Iconic Japanese toy manufacturer formed by the merger of Takara and Tomy in 2006. Creates Beyblade Burst, Tomica diecast cars, Transformers (Japan), and Zoids.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop",
    website: "https://www.takaratomy.co.jp",
    country: "Japan",
    founded: 2006,
    isActive: true,
    displayOrder: 3,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-mattel",
    slug: "brand-mattel",
    name: "Mattel",
    description:
      "American toy giant behind Hot Wheels, Barbie, Masters of the Universe, UNO, and Fisher-Price. Hot Wheels alone has over 900 vehicle models released annually.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=mattel",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=mattel",
    website: "https://www.mattel.com",
    country: "USA",
    founded: 1945,
    isActive: true,
    displayOrder: 4,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-pokemon-company",
    slug: "brand-pokemon-company",
    name: "The Pokémon Company",
    description:
      "Japanese consortium managing the Pokémon intellectual property. Publishes the Pokémon Trading Card Game (TCG), video games, anime merchandise, and official licensed collectibles worldwide.",
    logoURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&h=400&fit=crop",
    website: "https://www.pokemon.com",
    country: "Japan",
    founded: 1998,
    isActive: true,
    displayOrder: 5,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-konami",
    slug: "brand-konami",
    name: "Konami",
    description:
      "Japanese entertainment conglomerate best known for the Yu-Gi-Oh! Trading Card Game. Also produces Metal Gear, Silent Hill, and Castlevania merchandise and figures.",
    logoURL: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=1200&h=400&fit=crop",
    website: "https://www.konami.com",
    country: "Japan",
    founded: 1969,
    isActive: true,
    displayOrder: 6,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-funko",
    slug: "brand-funko",
    name: "Funko",
    description:
      "American pop-culture collectibles company. Iconic for Funko Pop! vinyl figures spanning thousands of licenses including Marvel, DC, anime, Disney, gaming, sports, and music.",
    logoURL: "https://images.unsplash.com/photo-1578292992345-7ee038c5fb7c?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1578292992345-7ee038c5fb7c?w=1200&h=400&fit=crop",
    website: "https://funko.com",
    country: "USA",
    founded: 1998,
    isActive: true,
    displayOrder: 7,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-neca",
    slug: "brand-neca",
    name: "NECA",
    description:
      "National Entertainment Collectibles Association — American designer and manufacturer of highly detailed action figures. Known for horror icons, Teenage Mutant Ninja Turtles, and video game characters.",
    logoURL: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=1200&h=400&fit=crop",
    website: "https://www.necaonline.com",
    country: "USA",
    founded: 1996,
    isActive: true,
    displayOrder: 8,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-mcfarlane",
    slug: "brand-mcfarlane",
    name: "McFarlane Toys",
    description:
      "American action figure company founded by comic artist Todd McFarlane. Official DC Multiverse figures, Warhammer, Spawn, and premium collector statuettes with extraordinary detail.",
    logoURL: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=1200&h=400&fit=crop",
    website: "https://www.mcfarlane.com",
    country: "USA",
    founded: 1994,
    isActive: true,
    displayOrder: 9,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-good-smile",
    slug: "brand-good-smile",
    name: "Good Smile Company",
    description:
      "Japan's premier figure manufacturer. Producer of Nendoroids, figma, and high-end scale PVC figures. Official partner for Fate, Hatsune Miku, Sword Art Online, Re:Zero, and hundreds of anime series.",
    logoURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&h=400&fit=crop",
    website: "https://www.goodsmile.info",
    country: "Japan",
    founded: 2001,
    isActive: true,
    displayOrder: 10,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-hot-wheels",
    slug: "brand-hot-wheels",
    name: "Hot Wheels",
    description:
      "Mattel's iconic 1:64 scale die-cast vehicle brand since 1968. Treasure Hunt, Super Treasure Hunt, Car Culture, RLC exclusives, and track sets. Over 6 billion cars sold worldwide.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=hotwheels",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=hotwheels",
    website: "https://hotwheels.mattel.com",
    country: "USA",
    founded: 1968,
    isActive: true,
    displayOrder: 11,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-tomica",
    slug: "brand-tomica",
    name: "Tomica",
    description:
      "Takara Tomy's 1:64 scale Japanese diecast car series since 1970. Features authentic Japanese vehicles (Toyota, Honda, Nissan), emergency vehicles, and licensed premium Tomica Premium line.",
    logoURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=200&h=200&fit=crop&seed=tomica",
    bannerURL: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=1200&h=400&fit=crop&seed=tomica",
    website: "https://www.takaratomy.co.jp/products/tomica",
    country: "Japan",
    founded: 1970,
    isActive: true,
    displayOrder: 12,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
  {
    id: "brand-beyblade",
    slug: "brand-beyblade",
    name: "Beyblade",
    description:
      "Takara Tomy's competitive spinning top battle franchise. Covers classic Metal Fight, Beyblade Burst, Beyblade X, and Hasbro-localized versions. Official tournaments held worldwide including India.",
    logoURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=200&h=200&fit=crop",
    bannerURL: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1200&h=400&fit=crop",
    website: "https://beyblade.takaratomy.co.jp",
    country: "Japan",
    founded: 1999,
    isActive: true,
    displayOrder: 13,
    productCount: 0,
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
  },
];
