/*
 * WHY: Provides the full collectibles marketplace category hierarchy plus brand entries.
 * WHAT: Exports categoriesSeedData combining 55+ categories (6 broad collectibles roots + YGO-specific
 *       sub-roots + leaves), 25 brands (categoryType:"brand"), and empty sublisting/bundle rows.
 *       Products tag BOTH a leaf category AND its root so array-contains queries work at
 *       both levels simultaneously.
 *
 * EXPORTS:
 *   categoriesSeedData — array of Partial<CategoryDocument> for the seed runner
 *
 * @tag domain:categories,brands
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/runner.ts,SeedPanel
 * @tag sideEffects:none
 */

import type { CategoryDocument } from "../features/categories/schemas";
import { CATEGORY_FIELDS } from "../constants/field-names";
import { seedExtMedia } from "./_helpers/media";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const emptyMetrics = {
  productCount: 0,
  productIds: [],
  auctionCount: 0,
  auctionIds: [],
  totalProductCount: 0,
  totalAuctionCount: 0,
  totalItemCount: 0,
  lastUpdated: daysAgo(1),
};

function seedMetrics(productCount: number, auctionCount = 0) {
  return {
    ...emptyMetrics,
    productCount,
    auctionCount,
    totalProductCount: productCount,
    totalAuctionCount: auctionCount,
    totalItemCount: productCount + auctionCount,
  };
}

// ──────────────────────────────────────────────────────────────────────────────
// Categories: 6 broad collectibles roots + YGO-specific sub-hierarchy + leaves
// ──────────────────────────────────────────────────────────────────────────────
const rawCategories: Partial<CategoryDocument>[] = [

  // ── ROOT 1: Singles ────────────────────────────────────────────────────────
  {
    id: "category-singles",
    slug: "category-singles",
    name: "Singles",
    description: "Individual Yu-Gi-Oh! cards — monsters, spells, traps, and extra deck cards sold separately.",
    rootId: "category-singles",
    parentIds: [],
    childrenIds: [
      "category-monster-cards",
      "category-spell-cards",
      "category-trap-cards",
      "category-extra-deck-cards",
    ],
    tier: 0,
    path: "singles",
    order: 1,
    isLeaf: false,
    position: 0,
    subtreeSize: 4,
    metrics: seedMetrics(34, 5),
    isFeatured: true,
    featuredPriority: 1,
    isBrand: false,
    seo: {
      title: "Yu-Gi-Oh! Singles | LetItRip",
      description: "Buy and sell individual Yu-Gi-Oh! cards — monsters, spells, traps, and extra deck cards. 1st Edition, unlimited, and graded slabs.",
      keywords: ["yugioh singles", "ygo cards", "duel monsters", "trading cards india"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
    },
    display: {
      icon: "🃏",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
      color: "#7c3aed",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-monster-cards",
    slug: "category-monster-cards",
    name: "Monster Cards",
    description: "Effect monsters, normal monsters, ritual monsters, and boss monsters from across all YGO eras.",
    rootId: "category-singles",
    parentIds: ["category-singles"],
    childrenIds: [],
    tier: 1,
    path: "singles/monster-cards",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: seedMetrics(17, 4),
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Monster Cards | Yu-Gi-Oh! Singles | LetItRip",
      description: "Shop Yu-Gi-Oh! monster cards — Dark Magician, Blue-Eyes White Dragon, Jinzo, Gate Guardian, and more.",
      keywords: ["monster cards", "dark magician", "blue-eyes white dragon", "yugioh monsters"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
    },
    display: {
      icon: "⚔️",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
      color: "#dc2626",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-spell-cards",
    slug: "category-spell-cards",
    name: "Spell / Magic Cards",
    description: "Spell cards (Magic cards in early printings) — Pot of Greed, Raigeki, Monster Reborn, and more.",
    rootId: "category-singles",
    parentIds: ["category-singles"],
    childrenIds: [],
    tier: 1,
    path: "singles/spell-cards",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: seedMetrics(12, 2),
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Spell Cards | Yu-Gi-Oh! Singles | LetItRip",
      description: "Shop Yu-Gi-Oh! spell cards — Pot of Greed, Raigeki, Monster Reborn, Dark Hole, Change of Heart.",
      keywords: ["spell cards", "magic cards", "pot of greed", "raigeki", "yugioh spells"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/55144522.jpg"),
    },
    display: {
      icon: "✨",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/55144522.jpg"),
      color: "#059669",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-trap-cards",
    slug: "category-trap-cards",
    name: "Trap Cards",
    description: "Trap cards — Mirror Force, Call of the Haunted, Torrential Tribute, and the most sought-after trap staples.",
    rootId: "category-singles",
    parentIds: ["category-singles"],
    childrenIds: [],
    tier: 1,
    path: "singles/trap-cards",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: seedMetrics(3, 1),
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Trap Cards | Yu-Gi-Oh! Singles | LetItRip",
      description: "Shop Yu-Gi-Oh! trap cards — Mirror Force, Torrential Tribute, Call of the Haunted.",
      keywords: ["trap cards", "mirror force", "torrential tribute", "yugioh traps"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/44095762.jpg"),
    },
    display: {
      icon: "🪤",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/44095762.jpg"),
      color: "#9333ea",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-extra-deck-cards",
    slug: "category-extra-deck-cards",
    name: "Extra Deck Cards",
    description: "Fusion, Synchro, and XYZ monsters — Blue-Eyes Ultimate Dragon, Elemental HERO Flame Wingman, Five-Headed Dragon.",
    rootId: "category-singles",
    parentIds: ["category-singles"],
    childrenIds: [],
    tier: 1,
    path: "singles/extra-deck-cards",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: seedMetrics(3),
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Extra Deck Cards | Yu-Gi-Oh! Singles | LetItRip",
      description: "Shop Yu-Gi-Oh! fusion monsters — Blue-Eyes Ultimate Dragon, Elemental HERO Flame Wingman, Five-Headed Dragon.",
      keywords: ["fusion monsters", "extra deck", "blue-eyes ultimate dragon", "yugioh fusion"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/23995346.jpg"),
    },
    display: {
      icon: "🔀",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/23995346.jpg"),
      color: "#ea580c",
      showInMenu: true,
      showInFooter: false,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 2: Sealed Products ────────────────────────────────────────────────
  {
    id: "category-sealed-products",
    slug: "category-sealed-products",
    name: "Sealed Products",
    description: "Factory-sealed Yu-Gi-Oh! product — booster packs, booster boxes, collector tins, and starter/structure decks.",
    rootId: "category-sealed-products",
    parentIds: [],
    childrenIds: [
      "category-booster-packs",
      "category-booster-boxes",
      "category-collector-tins",
      "category-starter-structure",
    ],
    tier: 0,
    path: "sealed-products",
    order: 2,
    isLeaf: false,
    position: 0,
    subtreeSize: 4,
    metrics: seedMetrics(25, 1),
    isFeatured: true,
    featuredPriority: 2,
    isBrand: false,
    seo: {
      title: "Sealed YGO Products | LetItRip",
      description: "Buy factory-sealed Yu-Gi-Oh! booster packs, boxes, tins, and decks. Authentic, unweighed, unopened.",
      keywords: ["sealed yugioh", "booster box", "starter deck", "collector tin", "yugioh sealed"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"),
    },
    display: {
      icon: "📦",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"),
      color: "#2563eb",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-booster-packs",
    slug: "category-booster-packs",
    name: "Booster Packs",
    description: "Individual booster packs — LOB, MRD, PSV, POTD, EEN, and more.",
    rootId: "category-sealed-products",
    parentIds: ["category-sealed-products"],
    childrenIds: [],
    tier: 1,
    path: "sealed-products/booster-packs",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: seedMetrics(3),
    isFeatured: false,
    isBrand: false,
    seo: { title: "Booster Packs | LetItRip", description: "Buy individual YGO booster packs.", keywords: ["booster pack", "yugioh pack"] },
    display: { icon: "🎴", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"), color: "#1d4ed8", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-booster-boxes",
    slug: "category-booster-boxes",
    name: "Booster Boxes",
    description: "Full 24-pack booster boxes — the collector's preferred sealed investment.",
    rootId: "category-sealed-products",
    parentIds: ["category-sealed-products"],
    childrenIds: [],
    tier: 1,
    path: "sealed-products/booster-boxes",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: seedMetrics(4),
    isFeatured: false,
    isBrand: false,
    seo: { title: "Booster Boxes | LetItRip", description: "Buy full YGO booster boxes (24 packs).", keywords: ["booster box", "yugioh box"] },
    display: { icon: "📫", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"), color: "#1e40af", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-collector-tins",
    slug: "category-collector-tins",
    name: "Collector Tins",
    description: "Collector tins containing promo cards and booster packs — 2002, 2004, 2005 series.",
    rootId: "category-sealed-products",
    parentIds: ["category-sealed-products"],
    childrenIds: [],
    tier: 1,
    path: "sealed-products/collector-tins",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: seedMetrics(3),
    isFeatured: false,
    isBrand: false,
    seo: { title: "Collector Tins | LetItRip", description: "Buy YGO collector tins with promo cards.", keywords: ["collector tin", "yugioh tin"] },
    display: { icon: "🗳️", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"), color: "#1e3a8a", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-starter-structure",
    slug: "category-starter-structure",
    name: "Starters & Structure Decks",
    description: "Starter decks and structure decks — Yugi, Kaiba, Joey, and GX starter sets.",
    rootId: "category-sealed-products",
    parentIds: ["category-sealed-products"],
    childrenIds: [],
    tier: 1,
    path: "sealed-products/starter-structure",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: seedMetrics(5),
    isFeatured: false,
    isBrand: false,
    seo: { title: "Starter & Structure Decks | LetItRip", description: "Buy YGO starter and structure decks.", keywords: ["starter deck", "structure deck", "yugioh deck"] },
    display: { icon: "🗂️", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"), color: "#312e81", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 3: Graded Cards ───────────────────────────────────────────────────
  {
    id: "category-graded-cards",
    slug: "category-graded-cards",
    name: "Graded Cards",
    description: "Professionally graded Yu-Gi-Oh! cards in sealed slabs — PSA, BGS, CGC grades from 1 to 10.",
    rootId: "category-graded-cards",
    parentIds: [],
    childrenIds: [
      "category-psa-graded",
      "category-bgs-graded",
      "category-cgc-graded",
      "category-raw-near-mint",
    ],
    tier: 0,
    path: "graded-cards",
    order: 3,
    isLeaf: false,
    position: 0,
    subtreeSize: 4,
    metrics: seedMetrics(1, 6),
    isFeatured: true,
    featuredPriority: 3,
    isBrand: false,
    seo: {
      title: "Graded YGO Cards | LetItRip",
      description: "Buy and sell professionally graded Yu-Gi-Oh! cards in PSA, BGS, and CGC slabs.",
      keywords: ["graded yugioh", "psa yugioh", "bgs yugioh", "cgc yugioh", "graded slab"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
    },
    display: {
      icon: "🏆",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
      color: "#ca8a04",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-psa-graded",
    slug: "category-psa-graded",
    name: "PSA Graded",
    description: "Cards graded by Professional Sports Authenticator (PSA) — grades 1–10.",
    rootId: "category-graded-cards",
    parentIds: ["category-graded-cards"],
    childrenIds: [],
    tier: 1,
    path: "graded-cards/psa-graded",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: seedMetrics(1, 6),
    isFeatured: false,
    isBrand: false,
    seo: { title: "PSA Graded YGO | LetItRip", description: "Shop PSA graded Yu-Gi-Oh! cards.", keywords: ["psa graded", "psa yugioh", "psa slab"] },
    display: { icon: "🔵", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"), color: "#b45309", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-bgs-graded",
    slug: "category-bgs-graded",
    name: "BGS / Beckett Graded",
    description: "Cards graded by Beckett Grading Services (BGS/BCCG) — grades 1–10 with sub-grades.",
    rootId: "category-graded-cards",
    parentIds: ["category-graded-cards"],
    childrenIds: [],
    tier: 1,
    path: "graded-cards/bgs-graded",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "BGS Graded YGO | LetItRip", description: "Shop BGS / Beckett graded Yu-Gi-Oh! cards.", keywords: ["bgs graded", "beckett yugioh", "bgs slab"] },
    display: { icon: "🟡", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/38033121.jpg"), color: "#92400e", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-cgc-graded",
    slug: "category-cgc-graded",
    name: "CGC Graded",
    description: "Cards graded by Certified Guaranty Company (CGC) — grades 1–10.",
    rootId: "category-graded-cards",
    parentIds: ["category-graded-cards"],
    childrenIds: [],
    tier: 1,
    path: "graded-cards/cgc-graded",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "CGC Graded YGO | LetItRip", description: "Shop CGC graded Yu-Gi-Oh! cards.", keywords: ["cgc graded", "cgc yugioh", "cgc slab"] },
    display: { icon: "🟢", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/12580477.jpg"), color: "#78350f", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-raw-near-mint",
    slug: "category-raw-near-mint",
    name: "Raw / Ungraded NM",
    description: "Ungraded Near Mint / Mint condition cards — ready for grading or direct play.",
    rootId: "category-graded-cards",
    parentIds: ["category-graded-cards"],
    childrenIds: [],
    tier: 1,
    path: "graded-cards/raw-near-mint",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Raw NM YGO Cards | LetItRip", description: "Shop ungraded Near Mint Yu-Gi-Oh! cards.", keywords: ["raw nm", "near mint yugioh", "ungraded yugioh"] },
    display: { icon: "📋", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"), color: "#451a03", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 4: Duel Monsters Era ──────────────────────────────────────────────
  {
    id: "category-duel-monsters-era",
    slug: "category-duel-monsters-era",
    name: "Duel Monsters Era",
    description: "Classic Duel Monsters / Season 1 era sets — LOB, MRD, PSV, LON, and the original power cards.",
    rootId: "category-duel-monsters-era",
    parentIds: [],
    childrenIds: [
      "category-legend-of-blue-eyes",
      "category-metal-raiders",
      "category-pharaoh-servant",
      "category-labyrinth-nightmare",
    ],
    tier: 0,
    path: "duel-monsters-era",
    order: 4,
    isLeaf: false,
    position: 0,
    subtreeSize: 4,
    metrics: emptyMetrics,
    isFeatured: true,
    featuredPriority: 4,
    isBrand: false,
    seo: {
      title: "Duel Monsters Era YGO | LetItRip",
      description: "Shop Duel Monsters era (Season 1) Yu-Gi-Oh! cards — LOB, MRD, PSV, LON sets.",
      keywords: ["duel monsters era", "lob yugioh", "legend of blue eyes", "original yugioh"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"),
    },
    display: {
      icon: "⚡",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"),
      color: "#1d4ed8",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-legend-of-blue-eyes",
    slug: "category-legend-of-blue-eyes",
    name: "Legend of Blue Eyes (LOB)",
    description: "Cards from the Legend of Blue Eyes White Dragon set — the first YGO TCG set released in the West.",
    rootId: "category-duel-monsters-era",
    parentIds: ["category-duel-monsters-era"],
    childrenIds: [],
    tier: 1,
    path: "duel-monsters-era/legend-of-blue-eyes",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "LOB Cards | LetItRip", description: "Shop Legend of Blue Eyes White Dragon set cards.", keywords: ["lob", "legend of blue eyes", "lob 1st edition"] },
    display: { icon: "👁️", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"), color: "#1e40af", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-metal-raiders",
    slug: "category-metal-raiders",
    name: "Metal Raiders (MRD)",
    description: "Cards from the Metal Raiders set — Mirror Force, Gate Guardian, Jinzo, and more.",
    rootId: "category-duel-monsters-era",
    parentIds: ["category-duel-monsters-era"],
    childrenIds: [],
    tier: 1,
    path: "duel-monsters-era/metal-raiders",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "MRD Cards | LetItRip", description: "Shop Metal Raiders set cards.", keywords: ["mrd", "metal raiders", "mirror force"] },
    display: { icon: "🔩", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/44095762.jpg"), color: "#1e3a8a", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-pharaoh-servant",
    slug: "category-pharaoh-servant",
    name: "Pharaoh's Servant (PSV)",
    description: "Cards from the Pharaoh's Servant set — Jinzo, MST, and classic PSV staples.",
    rootId: "category-duel-monsters-era",
    parentIds: ["category-duel-monsters-era"],
    childrenIds: [],
    tier: 1,
    path: "duel-monsters-era/pharaoh-servant",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "PSV Cards | LetItRip", description: "Shop Pharaoh's Servant set cards.", keywords: ["psv", "pharaoh servant", "jinzo"] },
    display: { icon: "🪄", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/77585513.jpg"), color: "#312e81", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-labyrinth-nightmare",
    slug: "category-labyrinth-nightmare",
    name: "Labyrinth of Nightmare (LON)",
    description: "Cards from the Labyrinth of Nightmare set — Chaos Emperor Dragon, exchange format staples.",
    rootId: "category-duel-monsters-era",
    parentIds: ["category-duel-monsters-era"],
    childrenIds: [],
    tier: 1,
    path: "duel-monsters-era/labyrinth-nightmare",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "LON Cards | LetItRip", description: "Shop Labyrinth of Nightmare set cards.", keywords: ["lon", "labyrinth of nightmare", "chaos emperor dragon"] },
    display: { icon: "🌀", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/82301904.jpg"), color: "#4c1d95", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 5: GX Era ─────────────────────────────────────────────────────────
  {
    id: "category-gx-era",
    slug: "category-gx-era",
    name: "GX Era",
    description: "Yu-Gi-Oh! GX era sets — Shadow of Infinity, Elemental Energy, Power of the Duelist, Cyberdark Impact.",
    rootId: "category-gx-era",
    parentIds: [],
    childrenIds: [
      "category-shadow-of-infinity",
      "category-elemental-energy",
      "category-power-of-the-duelist",
      "category-cyberdark-impact",
    ],
    tier: 0,
    path: "gx-era",
    order: 5,
    isLeaf: false,
    position: 0,
    subtreeSize: 4,
    metrics: seedMetrics(8, 2),
    isFeatured: true,
    featuredPriority: 5,
    isBrand: false,
    seo: {
      title: "GX Era YGO | LetItRip",
      description: "Shop Yu-Gi-Oh! GX era cards — Elemental HEROes, Destiny HEROes, Cyber Dragon, Rainbow Dragon.",
      keywords: ["yugioh gx", "elemental hero", "cyber dragon", "shadow of infinity", "potd"],
      ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89943723.jpg"),
    },
    display: {
      icon: "🌈",
      coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89943723.jpg"),
      color: "#16a34a",
      showInMenu: true,
      showInFooter: true,
    },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-shadow-of-infinity",
    slug: "category-shadow-of-infinity",
    name: "Shadow of Infinity (SOI)",
    description: "Cards from Shadow of Infinity — Elemental HERO cards and early GX staples.",
    rootId: "category-gx-era",
    parentIds: ["category-gx-era"],
    childrenIds: [],
    tier: 1,
    path: "gx-era/shadow-of-infinity",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "SOI Cards | LetItRip", description: "Shop Shadow of Infinity set cards.", keywords: ["soi", "shadow of infinity", "elemental hero"] },
    display: { icon: "🌑", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89943723.jpg"), color: "#15803d", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-elemental-energy",
    slug: "category-elemental-energy",
    name: "Elemental Energy (EEN)",
    description: "Cards from Elemental Energy — Elemental HERO fusions, Flame Wingman, Thunder Giant.",
    rootId: "category-gx-era",
    parentIds: ["category-gx-era"],
    childrenIds: [],
    tier: 1,
    path: "gx-era/elemental-energy",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "EEN Cards | LetItRip", description: "Shop Elemental Energy set cards.", keywords: ["een", "elemental energy", "flame wingman"] },
    display: { icon: "⚡", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/35809262.jpg"), color: "#166534", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-power-of-the-duelist",
    slug: "category-power-of-the-duelist",
    name: "Power of the Duelist (POTD)",
    description: "Cards from Power of the Duelist — E-HERO Neos, Cyber Dragon, Rainbow Dragon, Neo-Spacians.",
    rootId: "category-gx-era",
    parentIds: ["category-gx-era"],
    childrenIds: [],
    tier: 1,
    path: "gx-era/power-of-the-duelist",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "POTD Cards | LetItRip", description: "Shop Power of the Duelist set cards.", keywords: ["potd", "power of the duelist", "elemental hero neos", "rainbow dragon"] },
    display: { icon: "✊", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89943723.jpg"), color: "#14532d", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-cyberdark-impact",
    slug: "category-cyberdark-impact",
    name: "Cyberdark Impact (CDIP)",
    description: "Cards from Cyberdark Impact — Cyber Dragon evolution line and Destiny HERO cards.",
    rootId: "category-gx-era",
    parentIds: ["category-gx-era"],
    childrenIds: [],
    tier: 1,
    path: "gx-era/cyberdark-impact",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "CDIP Cards | LetItRip", description: "Shop Cyberdark Impact set cards.", keywords: ["cdip", "cyberdark impact", "cyber dragon", "destiny hero"] },
    display: { icon: "🤖", coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/70095154.jpg"), color: "#052e16", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 6: Trading Cards (broad — umbrella for YGO + Pokémon + others) ───
  {
    id: "category-trading-cards",
    slug: "category-trading-cards",
    name: "Trading Cards",
    description: "Collectible trading card games — Pokémon, Yu-Gi-Oh!, One Piece, Dragon Ball, Cardfight!! Vanguard, and more. Singles, sealed product, and graded slabs.",
    rootId: "category-trading-cards",
    parentIds: [],
    childrenIds: ["category-pokemon-tcg", "category-one-piece-tcg", "category-dragon-ball-tcg", "category-cardfight-vanguard"],
    tier: 0,
    path: "trading-cards",
    order: 6,
    isLeaf: false,
    position: 0,
    subtreeSize: 4,
    metrics: seedMetrics(1),
    isFeatured: true,
    featuredPriority: 6,
    isBrand: false,
    seo: { title: "Trading Cards | LetItRip", description: "Buy and sell collectible trading cards — Pokémon, Yu-Gi-Oh!, One Piece TCG and more.", keywords: ["trading cards", "tcg", "collectible cards", "pokemon cards", "yugioh cards"] },
    display: { icon: "🃏", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-trading-cards-20260101/1200/600"), color: "#7c3aed", showInMenu: true, showInFooter: true },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-pokemon-tcg",
    slug: "category-pokemon-tcg",
    name: "Pokémon TCG",
    description: "Pokémon Trading Card Game — booster packs, elite trainer boxes, singles, and graded cards from Base Set to Scarlet & Violet.",
    rootId: "category-trading-cards",
    parentIds: ["category-trading-cards"],
    childrenIds: [],
    tier: 1,
    path: "trading-cards/pokemon-tcg",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: seedMetrics(1),
    isFeatured: true,
    isBrand: false,
    seo: { title: "Pokémon TCG | LetItRip", description: "Buy Pokémon cards — booster packs, ETBs, singles, graded slabs.", keywords: ["pokemon tcg", "pokemon cards", "charizard", "pikachu card"] },
    display: { icon: "⚡", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-pokemon-tcg-20260101/1200/600"), color: "#eab308", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-one-piece-tcg",
    slug: "category-one-piece-tcg",
    name: "One Piece TCG",
    description: "One Piece Card Game by Bandai — booster packs, starter decks, leaders, and special art cards.",
    rootId: "category-trading-cards",
    parentIds: ["category-trading-cards"],
    childrenIds: [],
    tier: 1,
    path: "trading-cards/one-piece-tcg",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "One Piece TCG | LetItRip", description: "Buy One Piece trading cards — booster packs, starter decks, special art.", keywords: ["one piece tcg", "one piece cards", "bandai card game"] },
    display: { icon: "🏴‍☠️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-one-piece-tcg-20260101/1200/600"), color: "#dc2626", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-dragon-ball-tcg",
    slug: "category-dragon-ball-tcg",
    name: "Dragon Ball Super TCG",
    description: "Dragon Ball Super Card Game — booster packs, starter decks, and tournament promos.",
    rootId: "category-trading-cards",
    parentIds: ["category-trading-cards"],
    childrenIds: [],
    tier: 1,
    path: "trading-cards/dragon-ball-tcg",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Dragon Ball Super TCG | LetItRip", description: "Buy Dragon Ball Super trading cards.", keywords: ["dragon ball tcg", "dbs card game", "bandai dragon ball"] },
    display: { icon: "🐉", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-dragon-ball-tcg-20260101/1200/600"), color: "#f97316", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-cardfight-vanguard",
    slug: "category-cardfight-vanguard",
    name: "Cardfight!! Vanguard",
    description: "Cardfight!! Vanguard by Bushiroad — booster packs, trial decks, and premium collection cards.",
    rootId: "category-trading-cards",
    parentIds: ["category-trading-cards"],
    childrenIds: [],
    tier: 1,
    path: "trading-cards/cardfight-vanguard",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Cardfight!! Vanguard | LetItRip", description: "Buy Cardfight!! Vanguard cards by Bushiroad.", keywords: ["cardfight vanguard", "bushiroad tcg", "vanguard cards"] },
    display: { icon: "⚔️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-cardfight-vanguard-20260101/1200/600"), color: "#2563eb", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 7: Action Figures ─────────────────────────────────────────────────
  {
    id: "category-action-figures",
    slug: "category-action-figures",
    name: "Action Figures",
    description: "Collectible action figures — Gundam, Funko Pop, S.H.Figuarts, Nendoroid, Marvel Legends, NECA, McFarlane, and more.",
    rootId: "category-action-figures",
    parentIds: [],
    childrenIds: ["category-gundam-figures", "category-funko-pop", "category-shf-figuarts", "category-nendoroid", "category-marvel-legends"],
    tier: 0,
    path: "action-figures",
    order: 7,
    isLeaf: false,
    position: 0,
    subtreeSize: 5,
    metrics: emptyMetrics,
    isFeatured: true,
    featuredPriority: 7,
    isBrand: false,
    seo: { title: "Action Figures | LetItRip", description: "Buy collectible action figures — anime, Marvel, DC, and more.", keywords: ["action figures", "collectible figures", "anime figures", "funko pop"] },
    display: { icon: "🦸", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-action-figures-20260101/1200/600"), color: "#dc2626", showInMenu: true, showInFooter: true },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-gundam-figures",
    slug: "category-gundam-figures",
    name: "Gundam Figures",
    description: "Pre-built Gundam action figures — Robot Spirits, Metal Build, GFFMC, and Universe series.",
    rootId: "category-action-figures",
    parentIds: ["category-action-figures"],
    childrenIds: [],
    tier: 1,
    path: "action-figures/gundam-figures",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Gundam Figures | LetItRip", description: "Buy Gundam action figures — Robot Spirits, Metal Build.", keywords: ["gundam figures", "robot spirits", "metal build gundam"] },
    display: { icon: "🤖", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-gundam-figures-20260101/1200/600"), color: "#1d4ed8", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-funko-pop",
    slug: "category-funko-pop",
    name: "Funko Pop!",
    description: "Funko Pop! vinyl figures — anime, Marvel, DC, Star Wars, Disney, and exclusive chase variants.",
    rootId: "category-action-figures",
    parentIds: ["category-action-figures"],
    childrenIds: [],
    tier: 1,
    path: "action-figures/funko-pop",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: true,
    isBrand: false,
    seo: { title: "Funko Pop! | LetItRip", description: "Buy Funko Pop! vinyl figures — anime, Marvel, DC, exclusive chases.", keywords: ["funko pop", "pop vinyl", "funko chase", "funko exclusive"] },
    display: { icon: "🎭", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-funko-pop-20260101/1200/600"), color: "#7c3aed", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-shf-figuarts",
    slug: "category-shf-figuarts",
    name: "S.H.Figuarts",
    description: "S.H.Figuarts by Bandai Tamashii Nations — Dragon Ball, Naruto, One Piece, Kamen Rider, and more.",
    rootId: "category-action-figures",
    parentIds: ["category-action-figures"],
    childrenIds: [],
    tier: 1,
    path: "action-figures/shf-figuarts",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "S.H.Figuarts | LetItRip", description: "Buy S.H.Figuarts figures by Tamashii Nations.", keywords: ["sh figuarts", "tamashii nations", "dragon ball figures", "naruto figures"] },
    display: { icon: "💪", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-shf-figuarts-20260101/1200/600"), color: "#0891b2", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-nendoroid",
    slug: "category-nendoroid",
    name: "Nendoroid",
    description: "Nendoroid by Good Smile Company — chibi-style poseable figures with interchangeable face plates and accessories.",
    rootId: "category-action-figures",
    parentIds: ["category-action-figures"],
    childrenIds: [],
    tier: 1,
    path: "action-figures/nendoroid",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Nendoroid | LetItRip", description: "Buy Nendoroid figures by Good Smile Company.", keywords: ["nendoroid", "good smile company", "chibi figure", "nendoroid anime"] },
    display: { icon: "😊", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-nendoroid-20260101/1200/600"), color: "#ec4899", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-marvel-legends",
    slug: "category-marvel-legends",
    name: "Marvel Legends",
    description: "Marvel Legends by Hasbro — 6-inch scale Marvel action figures with Build-A-Figure parts.",
    rootId: "category-action-figures",
    parentIds: ["category-action-figures"],
    childrenIds: [],
    tier: 1,
    path: "action-figures/marvel-legends",
    order: 5,
    isLeaf: true,
    position: 4,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Marvel Legends | LetItRip", description: "Buy Marvel Legends 6-inch figures by Hasbro.", keywords: ["marvel legends", "hasbro marvel", "build a figure", "marvel action figures"] },
    display: { icon: "🦸‍♂️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-marvel-legends-20260101/1200/600"), color: "#b91c1c", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 8: Diecast Vehicles ───────────────────────────────────────────────
  {
    id: "category-diecast-vehicles",
    slug: "category-diecast-vehicles",
    name: "Diecast Vehicles",
    description: "Collectible diecast cars and vehicles — Hot Wheels, Tomica, Matchbox, Maisto, and more.",
    rootId: "category-diecast-vehicles",
    parentIds: [],
    childrenIds: ["category-hot-wheels", "category-tomica", "category-matchbox", "category-maisto"],
    tier: 0,
    path: "diecast-vehicles",
    order: 8,
    isLeaf: false,
    position: 0,
    subtreeSize: 4,
    metrics: seedMetrics(1),
    isFeatured: true,
    featuredPriority: 8,
    isBrand: false,
    seo: { title: "Diecast Vehicles | LetItRip", description: "Buy collectible diecast cars — Hot Wheels, Tomica, Matchbox, Maisto.", keywords: ["diecast vehicles", "hot wheels", "tomica", "diecast cars", "collectible cars"] },
    display: { icon: "🏎️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-diecast-vehicles-20260101/1200/600"), color: "#ea580c", showInMenu: true, showInFooter: true },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-hot-wheels",
    slug: "category-hot-wheels",
    name: "Hot Wheels",
    description: "Hot Wheels by Mattel — mainline, premium, Treasure Hunts, Super Treasure Hunts, RLC exclusives, and vintage Redlines.",
    rootId: "category-diecast-vehicles",
    parentIds: ["category-diecast-vehicles"],
    childrenIds: [],
    tier: 1,
    path: "diecast-vehicles/hot-wheels",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: true,
    isBrand: false,
    seo: { title: "Hot Wheels | LetItRip", description: "Buy Hot Wheels — mainline, premium, Treasure Hunts, vintage Redlines.", keywords: ["hot wheels", "treasure hunt", "super treasure hunt", "hot wheels redline"] },
    display: { icon: "🔥", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-hot-wheels-20260101/1200/600"), color: "#dc2626", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-tomica",
    slug: "category-tomica",
    name: "Tomica",
    description: "Tomica by Takara-Tomy — Japanese diecast cars, premium series, limited editions, and vintage models.",
    rootId: "category-diecast-vehicles",
    parentIds: ["category-diecast-vehicles"],
    childrenIds: [],
    tier: 1,
    path: "diecast-vehicles/tomica",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Tomica | LetItRip", description: "Buy Tomica diecast cars by Takara-Tomy.", keywords: ["tomica", "takara tomy cars", "tomica premium", "japanese diecast"] },
    display: { icon: "🚗", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-tomica-20260101/1200/600"), color: "#0284c7", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-matchbox",
    slug: "category-matchbox",
    name: "Matchbox",
    description: "Matchbox by Mattel — classic diecast cars, adventure sets, and vintage Lesney models.",
    rootId: "category-diecast-vehicles",
    parentIds: ["category-diecast-vehicles"],
    childrenIds: [],
    tier: 1,
    path: "diecast-vehicles/matchbox",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Matchbox | LetItRip", description: "Buy Matchbox diecast cars and vintage Lesney models.", keywords: ["matchbox", "matchbox cars", "lesney", "vintage matchbox"] },
    display: { icon: "📦", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-matchbox-20260101/1200/600"), color: "#16a34a", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-maisto",
    slug: "category-maisto",
    name: "Maisto",
    description: "Maisto diecast models — 1:18 and 1:24 scale licensed replicas of sports cars, muscle cars, and motorcycles.",
    rootId: "category-diecast-vehicles",
    parentIds: ["category-diecast-vehicles"],
    childrenIds: [],
    tier: 1,
    path: "diecast-vehicles/maisto",
    order: 4,
    isLeaf: true,
    position: 3,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Maisto | LetItRip", description: "Buy Maisto diecast models — 1:18 and 1:24 scale replicas.", keywords: ["maisto", "maisto 1 18", "diecast model cars"] },
    display: { icon: "🏁", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-maisto-20260101/1200/600"), color: "#4338ca", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 9: Spinning Tops ─────────────────────────────────────────────────
  {
    id: "category-spinning-tops",
    slug: "category-spinning-tops",
    name: "Spinning Tops",
    description: "Collectible spinning tops and battle systems — Beyblade X, Beyblade Burst, classic Metal Fight, and accessories.",
    rootId: "category-spinning-tops",
    parentIds: [],
    childrenIds: ["category-beyblade-x", "category-beyblade-burst", "category-beyblade-metal"],
    tier: 0,
    path: "spinning-tops",
    order: 9,
    isLeaf: false,
    position: 0,
    subtreeSize: 3,
    metrics: emptyMetrics,
    isFeatured: true,
    featuredPriority: 9,
    isBrand: false,
    seo: { title: "Spinning Tops | LetItRip", description: "Buy Beyblade and spinning tops — X, Burst, Metal Fight, and accessories.", keywords: ["beyblade", "spinning tops", "beyblade x", "beyblade burst"] },
    display: { icon: "🌀", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-spinning-tops-20260101/1200/600"), color: "#0891b2", showInMenu: true, showInFooter: true },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-beyblade-x",
    slug: "category-beyblade-x",
    name: "Beyblade X",
    description: "Beyblade X by Takara-Tomy — the latest generation with Xtreme Gear system, X Dash, and tournament-grade stadiums.",
    rootId: "category-spinning-tops",
    parentIds: ["category-spinning-tops"],
    childrenIds: [],
    tier: 1,
    path: "spinning-tops/beyblade-x",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: true,
    isBrand: false,
    seo: { title: "Beyblade X | LetItRip", description: "Buy Beyblade X tops and stadiums by Takara-Tomy.", keywords: ["beyblade x", "xtreme gear", "beyblade x starter", "takara tomy beyblade"] },
    display: { icon: "💫", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-beyblade-x-20260101/1200/600"), color: "#0d9488", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-beyblade-burst",
    slug: "category-beyblade-burst",
    name: "Beyblade Burst",
    description: "Beyblade Burst by Takara-Tomy/Hasbro — Burst system tops, launchers, and stadiums from all Burst sub-generations.",
    rootId: "category-spinning-tops",
    parentIds: ["category-spinning-tops"],
    childrenIds: [],
    tier: 1,
    path: "spinning-tops/beyblade-burst",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Beyblade Burst | LetItRip", description: "Buy Beyblade Burst tops, launchers, and stadiums.", keywords: ["beyblade burst", "burst system", "beyblade burst pro"] },
    display: { icon: "💥", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-beyblade-burst-20260101/1200/600"), color: "#059669", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-beyblade-metal",
    slug: "category-beyblade-metal",
    name: "Beyblade Metal Fight",
    description: "Classic Beyblade Metal Fight series — Metal Fusion, Metal Masters, Metal Fury, and Zero-G. Highly collectible vintage tops.",
    rootId: "category-spinning-tops",
    parentIds: ["category-spinning-tops"],
    childrenIds: [],
    tier: 1,
    path: "spinning-tops/beyblade-metal",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Beyblade Metal Fight | LetItRip", description: "Buy vintage Beyblade Metal Fight tops — Fusion, Masters, Fury.", keywords: ["beyblade metal fight", "metal fusion", "metal masters", "vintage beyblade"] },
    display: { icon: "⚙️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-beyblade-metal-20260101/1200/600"), color: "#64748b", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 10: Model Kits ────────────────────────────────────────────────────
  {
    id: "category-model-kits",
    slug: "category-model-kits",
    name: "Model Kits",
    description: "Plastic model kits for hobbyists — Gunpla, Frame Arms, 30 Minutes Missions, mecha, and military models.",
    rootId: "category-model-kits",
    parentIds: [],
    childrenIds: ["category-gunpla", "category-frame-arms", "category-30mm"],
    tier: 0,
    path: "model-kits",
    order: 10,
    isLeaf: false,
    position: 0,
    subtreeSize: 3,
    metrics: emptyMetrics,
    isFeatured: true,
    featuredPriority: 10,
    isBrand: false,
    seo: { title: "Model Kits | LetItRip", description: "Buy model kits — Gunpla, Frame Arms, 30 Minutes Missions, and more.", keywords: ["model kits", "gunpla", "plastic model", "bandai model kit"] },
    display: { icon: "🔧", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-model-kits-20260101/1200/600"), color: "#1e40af", showInMenu: true, showInFooter: true },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-gunpla",
    slug: "category-gunpla",
    name: "Gunpla (Gundam Model Kits)",
    description: "Gundam plastic models by Bandai — HG, RG, MG, PG, and SD grades. Japan's #1 hobby export.",
    rootId: "category-model-kits",
    parentIds: ["category-model-kits"],
    childrenIds: [],
    tier: 1,
    path: "model-kits/gunpla",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: true,
    isBrand: false,
    seo: { title: "Gunpla | LetItRip", description: "Buy Gundam model kits — HG, RG, MG, PG grades by Bandai.", keywords: ["gunpla", "gundam model kit", "master grade", "perfect grade", "bandai gunpla"] },
    display: { icon: "🤖", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-gunpla-20260101/1200/600"), color: "#1d4ed8", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-frame-arms",
    slug: "category-frame-arms",
    name: "Frame Arms / Frame Arms Girl",
    description: "Frame Arms by Kotobukiya — customizable mecha model kits and Frame Arms Girl humanoid kits.",
    rootId: "category-model-kits",
    parentIds: ["category-model-kits"],
    childrenIds: [],
    tier: 1,
    path: "model-kits/frame-arms",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Frame Arms | LetItRip", description: "Buy Frame Arms and Frame Arms Girl kits by Kotobukiya.", keywords: ["frame arms", "kotobukiya model kit", "frame arms girl"] },
    display: { icon: "🛡️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-frame-arms-20260101/1200/600"), color: "#4338ca", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-30mm",
    slug: "category-30mm",
    name: "30 Minutes Missions",
    description: "30 Minutes Missions (30MM) by Bandai — beginner-friendly mecha kits designed for 30-minute builds with extensive customization.",
    rootId: "category-model-kits",
    parentIds: ["category-model-kits"],
    childrenIds: [],
    tier: 1,
    path: "model-kits/30mm",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "30 Minutes Missions | LetItRip", description: "Buy 30MM model kits by Bandai — beginner-friendly mecha builds.", keywords: ["30 minutes missions", "30mm", "bandai 30mm", "beginner model kit"] },
    display: { icon: "⏱️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-30mm-20260101/1200/600"), color: "#0f766e", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },

  // ── ROOT 11: Vintage & Rare ────────────────────────────────────────────────
  {
    id: "category-vintage-rare",
    slug: "category-vintage-rare",
    name: "Vintage & Rare",
    description: "Vintage and rare collectibles — retro toys, discontinued figures, first-edition cards, and antique memorabilia.",
    rootId: "category-vintage-rare",
    parentIds: [],
    childrenIds: ["category-retro-toys", "category-vintage-cards", "category-antique-memorabilia"],
    tier: 0,
    path: "vintage-rare",
    order: 11,
    isLeaf: false,
    position: 0,
    subtreeSize: 3,
    metrics: emptyMetrics,
    isFeatured: true,
    featuredPriority: 11,
    isBrand: false,
    seo: { title: "Vintage & Rare | LetItRip", description: "Buy vintage and rare collectibles — retro toys, first-edition cards, discontinued items.", keywords: ["vintage collectibles", "rare toys", "retro toys", "vintage cards", "antique collectibles"] },
    display: { icon: "🏺", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-vintage-rare-20260101/1200/600"), color: "#92400e", showInMenu: true, showInFooter: true },
    isActive: true,
    isSearchable: true,
    showOnHomepage: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-retro-toys",
    slug: "category-retro-toys",
    name: "Retro Toys",
    description: "Vintage and discontinued toys — 80s/90s action figures, original Transformers, G.I. Joe, He-Man, and more.",
    rootId: "category-vintage-rare",
    parentIds: ["category-vintage-rare"],
    childrenIds: [],
    tier: 1,
    path: "vintage-rare/retro-toys",
    order: 1,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Retro Toys | LetItRip", description: "Buy vintage 80s/90s action figures and toys.", keywords: ["retro toys", "vintage action figures", "80s toys", "90s toys"] },
    display: { icon: "🕹️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-retro-toys-20260101/1200/600"), color: "#78350f", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-vintage-cards",
    slug: "category-vintage-cards",
    name: "Vintage Cards",
    description: "Vintage trading cards from pre-2010 — 1st Edition Pokémon Base Set, early YGO, Magic: The Gathering Alpha/Beta, and sports cards.",
    rootId: "category-vintage-rare",
    parentIds: ["category-vintage-rare"],
    childrenIds: [],
    tier: 1,
    path: "vintage-rare/vintage-cards",
    order: 2,
    isLeaf: true,
    position: 1,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Vintage Cards | LetItRip", description: "Buy vintage trading cards — 1st Edition Pokémon, early Yu-Gi-Oh!, classic MTG.", keywords: ["vintage cards", "1st edition pokemon", "alpha beta mtg", "vintage yugioh"] },
    display: { icon: "📜", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-vintage-cards-20260101/1200/600"), color: "#451a03", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "category-antique-memorabilia",
    slug: "category-antique-memorabilia",
    name: "Antique Memorabilia",
    description: "Antique and rare memorabilia — signed merchandise, production proofs, prototype toys, and one-of-a-kind collectibles.",
    rootId: "category-vintage-rare",
    parentIds: ["category-vintage-rare"],
    childrenIds: [],
    tier: 1,
    path: "vintage-rare/antique-memorabilia",
    order: 3,
    isLeaf: true,
    position: 2,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Antique Memorabilia | LetItRip", description: "Buy rare memorabilia — signed items, prototypes, production proofs.", keywords: ["antique memorabilia", "signed collectibles", "prototype toys", "rare memorabilia"] },
    display: { icon: "🖼️", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-antique-memorabilia-20260101/1200/600"), color: "#292524", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  // ── SB-UNI-J: Digital Codes root + leaf ───────────────────────────────────
  {
    id: "category-digital-codes",
    slug: "category-digital-codes",
    name: "Digital Codes",
    description: "Instant-delivery digital redemption codes — game currency, DLC unlocks, subscription passes, and in-app purchases for Yu-Gi-Oh! digital platforms.",
    rootId: "category-digital-codes",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "digital-codes",
    order: 7,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: seedMetrics(5),
    isFeatured: false,
    isBrand: false,
    seo: { title: "Digital Codes | LetItRip", description: "Buy Yu-Gi-Oh! digital codes — Master Duel gems, Duel Links gems, battle passes.", keywords: ["digital codes", "master duel gems", "duel links", "yugioh codes"] },
    display: { icon: "🔑", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-digital-codes-20260101/1200/600"), color: "#1e40af", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  // ── SB-UNI-K: Live Aquatics root + leaf ─────────────────────────────────
  {
    id: "category-live-aquatics",
    slug: "category-live-aquatics",
    name: "Live Aquatics",
    description: "Collectible live aquatic species — koi, bettas, axolotls, shrimp, and other aquarium inhabitants. All vendors verified, CITES-compliant, specialist shipping.",
    rootId: "category-live-aquatics",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "live-aquatics",
    order: 8,
    isLeaf: true,
    position: 0,
    subtreeSize: 0,
    metrics: emptyMetrics,
    isFeatured: false,
    isBrand: false,
    seo: { title: "Live Aquatics | LetItRip", description: "Buy collectible live aquatics — koi, bettas, axolotls. Verified vendors, specialist shipping.", keywords: ["live aquatics", "koi", "betta", "axolotl", "live fish"] },
    display: { icon: "🐟", coverImage: seedExtMedia("https://picsum.photos/seed/category-image-live-aquatics-20260101/1200/600"), color: "#0891b2", showInMenu: true, showInFooter: false },
    isActive: true,
    isSearchable: true,
    showOnHomepage: false,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
];

// ──────────────────────────────────────────────────────────────────────────────
// 25 Brands (SB-UNI-C: brands stored as categoryType:"brand")
// ──────────────────────────────────────────────────────────────────────────────
const brandRows: Partial<CategoryDocument>[] = [
  {
    id: "brand-konami",
    slug: "brand-konami",
    name: "Konami",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japanese entertainment conglomerate and the publisher of the Yu-Gi-Oh! Trading Card Game. Konami holds the master license for YGO and releases all official TCG/OCG product worldwide.",
    brandWebsite: "https://www.konami.com/yugioh",
    brandCountry: "Japan",
    brandFounded: 1969,
    brandBannerImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
    rootId: "brand-konami",
    parentIds: [],
    tier: 0,
    path: "brand-konami",
    isLeaf: true,
    order: 1,
    display: { coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/small/46986414.jpg"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
    seo: { title: "Konami | LetItRip", description: "Official YGO TCG publisher. All Konami Yu-Gi-Oh! cards on LetItRip.", keywords: ["konami", "yugioh publisher", "ygo tcg"] },
  },
  {
    id: "brand-upper-deck",
    slug: "brand-upper-deck",
    name: "Upper Deck Entertainment",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Upper Deck Entertainment was the original North American distributor of Yu-Gi-Oh! TCG (2002–2008). Early LOB, MRD, PSV, and LON printings bear the Upper Deck license. Highly collectible.",
    brandWebsite: "https://www.upperdeck.com",
    brandCountry: "USA",
    brandFounded: 1988,
    brandBannerImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"),
    rootId: "brand-upper-deck",
    parentIds: [],
    tier: 0,
    path: "brand-upper-deck",
    isLeaf: true,
    order: 2,
    display: { coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/small/89631139.jpg"), showInMenu: false, showInFooter: true },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
    seo: { title: "Upper Deck Entertainment | LetItRip", description: "Upper Deck early YGO printings — LOB, MRD, PSV, LON era cards.", keywords: ["upper deck", "upper deck yugioh", "early yugioh"] },
  },
  {
    id: "brand-bandai",
    slug: "brand-bandai",
    name: "Bandai",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japan's leading toy manufacturer. Produced the original Bandai Yu-Gi-Oh! card game (1998) before the Konami TCG launched. Bandai YGO cards are extremely rare collectibles.",
    brandWebsite: "https://www.bandai.co.jp",
    brandCountry: "Japan",
    brandFounded: 1950,
    brandBannerImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/40640057.jpg"),
    rootId: "brand-bandai",
    parentIds: [],
    tier: 0,
    path: "brand-bandai",
    isLeaf: true,
    order: 3,
    display: { coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/small/40640057.jpg"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
    seo: { title: "Bandai | LetItRip", description: "Rare Bandai Yu-Gi-Oh! cards and merchandise.", keywords: ["bandai", "bandai yugioh", "original yugioh cards"] },
  },
  {
    id: "brand-toei-animation",
    slug: "brand-toei-animation",
    name: "Toei Animation",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Toei Animation produced the original 1998 YGO anime series. Toei-licensed merchandise — plushies, figures, and collectibles — are rare and highly sought after by Season 0 collectors.",
    brandWebsite: "https://www.toei-animation.co.jp",
    brandCountry: "Japan",
    brandFounded: 1956,
    brandBannerImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
    rootId: "brand-toei-animation",
    parentIds: [],
    tier: 0,
    path: "brand-toei-animation",
    isLeaf: true,
    order: 4,
    display: { coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/small/46986414.jpg"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
    seo: { title: "Toei Animation | LetItRip", description: "Toei Animation YGO merchandise and collectibles.", keywords: ["toei animation", "yugioh anime merchandise", "season 0"] },
  },
  {
    id: "brand-score-entertainment",
    slug: "brand-score-entertainment",
    name: "Score Entertainment",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Score Entertainment distributed Yu-Gi-Oh! in some international markets during the early 2000s. Score-distributed printings of LOB and MRD are rare alternate editions.",
    brandWebsite: "https://www.score-entertainment.com",
    brandCountry: "USA",
    brandFounded: 1992,
    brandBannerImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"),
    rootId: "brand-score-entertainment",
    parentIds: [],
    tier: 0,
    path: "brand-score-entertainment",
    isLeaf: true,
    order: 5,
    display: { coverImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/small/89631139.jpg"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(400),
    updatedAt: daysAgo(30),
    seo: { title: "Score Entertainment | LetItRip", description: "Score Entertainment distributed YGO printings.", keywords: ["score entertainment", "score yugioh"] },
  },

  // ── Broader collectibles brands ────────────────────────────────────────────
  {
    id: "brand-hasbro",
    slug: "brand-hasbro",
    name: "Hasbro",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "American toy and entertainment giant. Makes Marvel Legends, Transformers, Beyblade (international), Nerf, and more. One of the world's largest toy companies.",
    brandWebsite: "https://www.hasbro.com",
    brandCountry: "USA",
    brandFounded: 1923,
    rootId: "brand-hasbro",
    parentIds: [],
    tier: 0,
    path: "brand-hasbro",
    isLeaf: true,
    order: 6,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-hasbro-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Hasbro | LetItRip", description: "Shop Hasbro collectibles — Marvel Legends, Transformers, Beyblade.", keywords: ["hasbro", "hasbro toys", "marvel legends hasbro"] },
  },
  {
    id: "brand-takara-tomy",
    slug: "brand-takara-tomy",
    name: "Takara-Tomy",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japanese toy company behind Beyblade, Tomica, Transformers (Japan), and Duel Masters. Known for premium quality and Japan-exclusive releases.",
    brandWebsite: "https://www.takaratomy.co.jp",
    brandCountry: "Japan",
    brandFounded: 2006,
    rootId: "brand-takara-tomy",
    parentIds: [],
    tier: 0,
    path: "brand-takara-tomy",
    isLeaf: true,
    order: 7,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-takara-tomy-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Takara-Tomy | LetItRip", description: "Shop Takara-Tomy collectibles — Beyblade, Tomica, Transformers.", keywords: ["takara tomy", "takara tomy beyblade", "tomica takara"] },
  },
  {
    id: "brand-mattel",
    slug: "brand-mattel",
    name: "Mattel",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "American toy corporation — parent of Hot Wheels, Matchbox, Barbie, Masters of the Universe, and UNO.",
    brandWebsite: "https://www.mattel.com",
    brandCountry: "USA",
    brandFounded: 1945,
    rootId: "brand-mattel",
    parentIds: [],
    tier: 0,
    path: "brand-mattel",
    isLeaf: true,
    order: 8,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-mattel-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Mattel | LetItRip", description: "Shop Mattel collectibles — Hot Wheels, Matchbox, Masters of the Universe.", keywords: ["mattel", "hot wheels mattel", "matchbox mattel"] },
  },
  {
    id: "brand-pokemon-company",
    slug: "brand-pokemon-company",
    name: "The Pokémon Company",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Joint venture of Nintendo, Game Freak, and Creatures. Publishes the Pokémon TCG worldwide. Largest trading card game brand by revenue.",
    brandWebsite: "https://www.pokemon.com",
    brandCountry: "Japan",
    brandFounded: 1998,
    rootId: "brand-pokemon-company",
    parentIds: [],
    tier: 0,
    path: "brand-pokemon-company",
    isLeaf: true,
    order: 9,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-pokemon-company-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "The Pokémon Company | LetItRip", description: "Shop Pokémon TCG products from The Pokémon Company.", keywords: ["pokemon company", "pokemon tcg", "pikachu", "charizard"] },
  },
  {
    id: "brand-funko",
    slug: "brand-funko",
    name: "Funko",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "American company known for Funko Pop! vinyl figures. Covers every major IP — anime, Marvel, DC, Disney, Star Wars, and more.",
    brandWebsite: "https://www.funko.com",
    brandCountry: "USA",
    brandFounded: 1998,
    rootId: "brand-funko",
    parentIds: [],
    tier: 0,
    path: "brand-funko",
    isLeaf: true,
    order: 10,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-funko-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Funko | LetItRip", description: "Shop Funko Pop! vinyl figures — anime, Marvel, DC, Star Wars.", keywords: ["funko", "funko pop", "pop vinyl", "funko exclusive"] },
  },
  {
    id: "brand-neca",
    slug: "brand-neca",
    name: "NECA",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "National Entertainment Collectibles Association. Premium 7-inch figures — horror, sci-fi, gaming, and TMNT lines.",
    brandWebsite: "https://www.necaonline.com",
    brandCountry: "USA",
    brandFounded: 1996,
    rootId: "brand-neca",
    parentIds: [],
    tier: 0,
    path: "brand-neca",
    isLeaf: true,
    order: 11,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-neca-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "NECA | LetItRip", description: "Shop NECA figures — horror, sci-fi, TMNT, and gaming collectibles.", keywords: ["neca", "neca figures", "neca tmnt", "neca horror"] },
  },
  {
    id: "brand-mcfarlane",
    slug: "brand-mcfarlane",
    name: "McFarlane Toys",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Founded by Todd McFarlane. Known for hyper-detailed DC Multiverse, Spawn, and sports figures.",
    brandWebsite: "https://mcfarlane.com",
    brandCountry: "USA",
    brandFounded: 1994,
    rootId: "brand-mcfarlane",
    parentIds: [],
    tier: 0,
    path: "brand-mcfarlane",
    isLeaf: true,
    order: 12,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-mcfarlane-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "McFarlane Toys | LetItRip", description: "Shop McFarlane Toys — DC Multiverse, Spawn, and sports figures.", keywords: ["mcfarlane toys", "dc multiverse", "spawn figure", "mcfarlane dc"] },
  },
  {
    id: "brand-good-smile",
    slug: "brand-good-smile",
    name: "Good Smile Company",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japanese figure manufacturer. Makes Nendoroid, figma, and scale figures. The gold standard for anime collectible figures.",
    brandWebsite: "https://www.goodsmile.info",
    brandCountry: "Japan",
    brandFounded: 2001,
    rootId: "brand-good-smile",
    parentIds: [],
    tier: 0,
    path: "brand-good-smile",
    isLeaf: true,
    order: 13,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-good-smile-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Good Smile Company | LetItRip", description: "Shop Good Smile Company — Nendoroid, figma, and scale figures.", keywords: ["good smile company", "nendoroid", "figma", "anime figures"] },
  },
  {
    id: "brand-hot-wheels",
    slug: "brand-hot-wheels",
    name: "Hot Wheels",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Mattel's iconic diecast car brand. Mainline, Premium, Treasure Hunts, Super Treasure Hunts, RLC exclusives, and vintage Redlines.",
    brandWebsite: "https://www.hotwheels.mattel.com",
    brandCountry: "USA",
    brandFounded: 1968,
    rootId: "brand-hot-wheels",
    parentIds: [],
    tier: 0,
    path: "brand-hot-wheels",
    isLeaf: true,
    order: 14,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-hot-wheels-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Hot Wheels | LetItRip", description: "Shop Hot Wheels diecast — mainline, premium, Treasure Hunts, RLC exclusives.", keywords: ["hot wheels", "treasure hunt", "super treasure hunt", "hot wheels premium"] },
  },
  {
    id: "brand-tomica",
    slug: "brand-tomica",
    name: "Tomica",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Takara-Tomy's Japanese diecast car brand. Known for precision JDM models, Premium series, and Limited Vintage Neo line.",
    brandWebsite: "https://www.takaratomy.co.jp/products/tomica",
    brandCountry: "Japan",
    brandFounded: 1970,
    rootId: "brand-tomica",
    parentIds: [],
    tier: 0,
    path: "brand-tomica",
    isLeaf: true,
    order: 15,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-tomica-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Tomica | LetItRip", description: "Shop Tomica diecast — premium Japanese cars and Limited Vintage Neo.", keywords: ["tomica", "tomica premium", "tomica limited vintage", "japanese diecast"] },
  },
  {
    id: "brand-beyblade",
    slug: "brand-beyblade",
    name: "Beyblade",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Spinning top battle franchise by Takara-Tomy (Japan) and Hasbro (international). Covers Metal Fight, Burst, and the latest Beyblade X generation.",
    brandWebsite: "https://beyblade.takaratomy.co.jp",
    brandCountry: "Japan",
    brandFounded: 1999,
    rootId: "brand-beyblade",
    parentIds: [],
    tier: 0,
    path: "brand-beyblade",
    isLeaf: true,
    order: 16,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-beyblade-20260101/800/800"), showInMenu: false, showInFooter: true },
    isFeatured: true,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Beyblade | LetItRip", description: "Shop Beyblade — X, Burst, Metal Fight tops and stadiums.", keywords: ["beyblade", "beyblade x", "beyblade burst", "spinning top battle"] },
  },
  {
    id: "brand-bushiroad",
    slug: "brand-bushiroad",
    name: "Bushiroad",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japanese entertainment company. Publishes Cardfight!! Vanguard, Weiss Schwarz, and Future Card Buddyfight TCGs.",
    brandWebsite: "https://en.bushiroad.com",
    brandCountry: "Japan",
    brandFounded: 2007,
    rootId: "brand-bushiroad",
    parentIds: [],
    tier: 0,
    path: "brand-bushiroad",
    isLeaf: true,
    order: 17,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-bushiroad-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Bushiroad | LetItRip", description: "Shop Bushiroad TCGs — Cardfight!! Vanguard, Weiss Schwarz.", keywords: ["bushiroad", "cardfight vanguard", "weiss schwarz"] },
  },
  {
    id: "brand-bandai-spirits",
    slug: "brand-bandai-spirits",
    name: "Bandai Spirits",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Bandai Namco subsidiary focused on collector-grade products. Makes Gunpla, S.H.Figuarts, Robot Spirits, and Chogokin.",
    brandWebsite: "https://www.bandaispirits.co.jp",
    brandCountry: "Japan",
    brandFounded: 2018,
    rootId: "brand-bandai-spirits",
    parentIds: [],
    tier: 0,
    path: "brand-bandai-spirits",
    isLeaf: true,
    order: 18,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-bandai-spirits-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Bandai Spirits | LetItRip", description: "Shop Bandai Spirits — Gunpla, S.H.Figuarts, Robot Spirits.", keywords: ["bandai spirits", "gunpla bandai", "sh figuarts", "robot spirits"] },
  },
  {
    id: "brand-kotobukiya",
    slug: "brand-kotobukiya",
    name: "Kotobukiya",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japanese manufacturer of model kits and figures. Known for Frame Arms, Bishoujo series, and ARTFX+ statues.",
    brandWebsite: "https://www.kotobukiya.co.jp",
    brandCountry: "Japan",
    brandFounded: 1953,
    rootId: "brand-kotobukiya",
    parentIds: [],
    tier: 0,
    path: "brand-kotobukiya",
    isLeaf: true,
    order: 19,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-kotobukiya-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Kotobukiya | LetItRip", description: "Shop Kotobukiya — Frame Arms, Bishoujo, ARTFX+ statues.", keywords: ["kotobukiya", "frame arms kotobukiya", "artfx", "bishoujo"] },
  },
  {
    id: "brand-megahouse",
    slug: "brand-megahouse",
    name: "MegaHouse",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Bandai Namco subsidiary. Makes Portrait of Pirates (One Piece), Variable Action Heroes, and Lookup chibi figures.",
    brandWebsite: "https://www.megahobby.jp",
    brandCountry: "Japan",
    brandFounded: 1962,
    rootId: "brand-megahouse",
    parentIds: [],
    tier: 0,
    path: "brand-megahouse",
    isLeaf: true,
    order: 20,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-megahouse-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "MegaHouse | LetItRip", description: "Shop MegaHouse — Portrait of Pirates, Variable Action Heroes.", keywords: ["megahouse", "portrait of pirates", "variable action heroes"] },
  },
  {
    id: "brand-tamashii-nations",
    slug: "brand-tamashii-nations",
    name: "Tamashii Nations",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Bandai Spirits' premium collector brand. Produces S.H.Figuarts, Robot Spirits, Chogokin, and FiguartsZERO lines.",
    brandWebsite: "https://tamashiinations.com",
    brandCountry: "Japan",
    brandFounded: 2008,
    rootId: "brand-tamashii-nations",
    parentIds: [],
    tier: 0,
    path: "brand-tamashii-nations",
    isLeaf: true,
    order: 21,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-tamashii-nations-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Tamashii Nations | LetItRip", description: "Shop Tamashii Nations — S.H.Figuarts, Chogokin, Robot Spirits.", keywords: ["tamashii nations", "figuarts", "chogokin", "robot spirits bandai"] },
  },
  {
    id: "brand-kaiyodo",
    slug: "brand-kaiyodo",
    name: "Kaiyodo",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japanese figure company known for Revoltech action figures and museum-quality dinosaur/animal models.",
    brandWebsite: "https://kaiyodo.co.jp",
    brandCountry: "Japan",
    brandFounded: 1964,
    rootId: "brand-kaiyodo",
    parentIds: [],
    tier: 0,
    path: "brand-kaiyodo",
    isLeaf: true,
    order: 22,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-kaiyodo-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Kaiyodo | LetItRip", description: "Shop Kaiyodo — Revoltech figures and museum models.", keywords: ["kaiyodo", "revoltech", "kaiyodo figures"] },
  },
  {
    id: "brand-medicom",
    slug: "brand-medicom",
    name: "Medicom Toy",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Japanese company known for BE@RBRICK, MAFEX action figures, and RAH (Real Action Heroes). Designer toy icons.",
    brandWebsite: "https://www.medicomtoy.co.jp",
    brandCountry: "Japan",
    brandFounded: 1996,
    rootId: "brand-medicom",
    parentIds: [],
    tier: 0,
    path: "brand-medicom",
    isLeaf: true,
    order: 23,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-medicom-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Medicom Toy | LetItRip", description: "Shop Medicom Toy — BE@RBRICK, MAFEX, and RAH figures.", keywords: ["medicom toy", "bearbrick", "mafex", "real action heroes"] },
  },
  {
    id: "brand-spin-master",
    slug: "brand-spin-master",
    name: "Spin Master",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Canadian toy company. Makes Bakugan, PAW Patrol, Monster Jam, and DC Comics figures. Growing collectibles presence in India.",
    brandWebsite: "https://www.spinmaster.com",
    brandCountry: "Canada",
    brandFounded: 1994,
    rootId: "brand-spin-master",
    parentIds: [],
    tier: 0,
    path: "brand-spin-master",
    isLeaf: true,
    order: 24,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-spin-master-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Spin Master | LetItRip", description: "Shop Spin Master — Bakugan, Monster Jam, DC Comics figures.", keywords: ["spin master", "bakugan", "monster jam", "spin master toys"] },
  },
  {
    id: "brand-maisto",
    slug: "brand-maisto",
    name: "Maisto",
    categoryType: CATEGORY_FIELDS.CATEGORY_TYPE_VALUES.BRAND,
    description: "Diecast model manufacturer known for affordable 1:18 and 1:24 scale licensed replicas of sports cars, muscle cars, and motorcycles.",
    brandWebsite: "https://www.maisto.com",
    brandCountry: "USA",
    brandFounded: 1990,
    rootId: "brand-maisto",
    parentIds: [],
    tier: 0,
    path: "brand-maisto",
    isLeaf: true,
    order: 25,
    display: { coverImage: seedExtMedia("https://picsum.photos/seed/brand-logo-maisto-20260101/800/800"), showInMenu: false, showInFooter: false },
    isFeatured: false,
    isBrand: true,
    isActive: true,
    isSearchable: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(300),
    updatedAt: daysAgo(30),
    seo: { title: "Maisto | LetItRip", description: "Shop Maisto diecast models — 1:18 and 1:24 scale replicas.", keywords: ["maisto", "maisto diecast", "maisto 1 18", "diecast model cars"] },
  },
];

// No sublisting or bundle category rows for this seed.
const sublistingRows: Partial<CategoryDocument>[] = [];
const bundleRows: Partial<CategoryDocument>[] = [];

export const categoriesSeedData: Partial<CategoryDocument>[] = [
  ...rawCategories.map((c) => ({ ancestors: [] as any[], ...c, createdByType: "admin" as const })),
  ...sublistingRows.map((s) => ({ ancestors: [] as any[], ...s, createdByType: "admin" as const })),
  ...brandRows.map((b) => ({ ancestors: [] as any[], ...b, createdByType: "admin" as const })),
  ...bundleRows.map((bundle) => ({ ancestors: [] as any[], ...bundle, createdByType: "admin" as const })),
];
