/**
 * Conversations Seed Data â€” Buyer â†” Seller messaging on products.
 * 8 conversations with realistic pre-purchase and post-purchase threads.
 * Covers: availability questions, grading enquiries, shipping queries, offer negotiation,
 * order tracking help, and return requests. Mixed read/unread states.
 */

import type { ConversationDocument } from "../features/messages/schemas/firestore";

const NOW = new Date();
const minsAgo = (n: number) => new Date(NOW.getTime() - n * 60_000);
const hoursAgo = (n: number) => new Date(NOW.getTime() - n * 3_600_000);
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const conversationsSeedData: Partial<ConversationDocument>[] = [
  // â”€â”€ 1. Charizard PSA 9 â€” Pre-purchase grading query â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-charizard-rahul-aryan-001",
    buyerId: "user-rahul-sharma",
    buyerDisplayName: "Rahul Sharma",
    sellerDisplayName: "Aryan Kapoor",
    storeId: "store-pokemon-palace",
    storeName: "PokÃ©mon Palace",
    productId: "auction-pokemon-charizard-base1-psa9",
    productTitle: "PokÃ©mon Base Set Charizard #4 â€” PSA 9",
    messages: [
      {
        id: "msg-001-1",
        senderId: "user-rahul-sharma",
        senderRole: "buyer",
        body: "Hi! Is this PSA 9 a light play or does it have any edge wear? I'm buying for my collection, not resale, so I want to know the centering before I bid.",
        isRead: true,
        sentAt: daysAgo(3),
      },
      {
        id: "msg-001-2",
        senderId: "user-aryan-kapoor",
        senderRole: "seller",
        body: "Hey Rahul! The centering is approximately 55/45 front and 60/40 back â€” well within PSA 9 standards. The slab itself has no cracks. This was submitted by me personally from a sealed WOTC booster. Happy to share full slab photos on WhatsApp if you DM me before bidding.",
        isRead: true,
        sentAt: daysAgo(3),
      },
      {
        id: "msg-001-3",
        senderId: "user-rahul-sharma",
        senderRole: "buyer",
        body: "That sounds great! Can you also confirm the cert number so I can verify on PSA's website?",
        isRead: true,
        sentAt: daysAgo(2),
      },
      {
        id: "msg-001-4",
        senderId: "user-aryan-kapoor",
        senderRole: "seller",
        body: "PSA Cert #: 84729183. You can verify at psacard.com. Grade is confirmed Mint 9. Good luck in the auction!",
        isRead: false,
        sentAt: daysAgo(2),
      },
    ],
    lastMessage: "PSA Cert #: 84729183. You can verify at psacard.com. Grade is confirmed Mint 9. Good luck in the auction!",
    lastMessageAt: daysAgo(2),
    unreadBuyer: 1,
    unreadSeller: 0,
    status: "active",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },

  // â”€â”€ 2. Hot Wheels STH â€” Availability + bundle query â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-hotwheels-priya-vikram-002",
    buyerId: "user-priya-patel",
    buyerDisplayName: "Priya Patel",
    sellerDisplayName: "Vikram Mehta",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    productId: "product-hot-wheels-super-th-bone-shaker",
    productTitle: "Hot Wheels Super Treasure Hunt â€” Bone Shaker",
    messages: [
      {
        id: "msg-002-1",
        senderId: "user-priya-patel",
        senderRole: "buyer",
        body: "Do you have more than 1 STH Bone Shaker? I'm looking to buy 3 for gifts. Also, do you combine shipping?",
        isRead: true,
        sentAt: hoursAgo(18),
      },
      {
        id: "msg-002-2",
        senderId: "user-vikram-mehta",
        senderRole: "seller",
        body: "Hi Priya! I only have 1 of this particular STH, but I do have 2x STH Twin Mill and 1x STH Deora III. All fresh from retail, blisterchecked. For 3+ cars I can do combined shipping in a single rigid box â€” saves you ~â‚¹80. Let me know which you want!",
        isRead: true,
        sentAt: hoursAgo(16),
      },
      {
        id: "msg-002-3",
        senderId: "user-priya-patel",
        senderRole: "buyer",
        body: "I'll take 1 Bone Shaker + 2 Twin Mills. Can you create a bundle listing or do I just add all 3 to cart separately?",
        isRead: false,
        sentAt: hoursAgo(12),
      },
    ],
    lastMessage: "I'll take 1 Bone Shaker + 2 Twin Mills. Can you create a bundle listing or do I just add all 3 to cart separately?",
    lastMessageAt: hoursAgo(12),
    unreadBuyer: 0,
    unreadSeller: 1,
    status: "active",
    createdAt: hoursAgo(18),
    updatedAt: hoursAgo(12),
  },

  // â”€â”€ 3. Beyblade X â€” Combo & authenticity check â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-beyblade-arjun-rohit-003",
    buyerId: "user-arjun-singh",
    buyerDisplayName: "Arjun Singh",
    sellerDisplayName: "Rohit Joshi",
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    productId: "product-beyblade-x-bx01-dran-sword",
    productTitle: "Beyblade X BX-01 Dran Sword",
    messages: [
      {
        id: "msg-003-1",
        senderId: "user-arjun-singh",
        senderRole: "buyer",
        body: "Is this official Takara Tomy or the Hasbro version? My son specifically wants the TT Japan release.",
        isRead: true,
        sentAt: daysAgo(1),
      },
      {
        id: "msg-003-2",
        senderId: "user-rohit-joshi",
        senderRole: "seller",
        body: "100% Takara Tomy Japan release. All my stock is direct import â€” no Hasbro, no knockoffs. The Japanese box has 'TAKARA TOMY' printed on the back spine and the QR code resolves to the official TT website. I can send unboxing photos before I ship if you want extra assurance.",
        isRead: true,
        sentAt: daysAgo(1),
      },
      {
        id: "msg-003-3",
        senderId: "user-arjun-singh",
        senderRole: "buyer",
        body: "Perfect, that's exactly what I needed to know. Placing the order now. Do you ship to Chandigarh?",
        isRead: true,
        sentAt: daysAgo(1),
      },
      {
        id: "msg-003-4",
        senderId: "user-rohit-joshi",
        senderRole: "seller",
        body: "Yes, I ship pan-India via Shiprocket. Chandigarh is 4â€“5 business days. Order placed â€” I'll dispatch tomorrow and share tracking once it's picked up.",
        isRead: true,
        sentAt: hoursAgo(22),
      },
    ],
    lastMessage: "Yes, I ship pan-India via Shiprocket. Chandigarh is 4â€“5 business days. Order placed â€” I'll dispatch tomorrow and share tracking once it's picked up.",
    lastMessageAt: hoursAgo(22),
    unreadBuyer: 0,
    unreadSeller: 0,
    status: "active",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(22),
  },

  // â”€â”€ 4. Yu-Gi-Oh! Singles â€” Post-purchase shipping delay â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-yugioh-sneha-nisha-004",
    buyerId: "user-sneha-kumar",
    buyerDisplayName: "Sneha Kumar",
    sellerDisplayName: "Nisha Reddy",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    productId: "product-yugioh-25th-tin",
    productTitle: "Yu-Gi-Oh! 25th Anniversary Tin",
    messages: [
      {
        id: "msg-004-1",
        senderId: "user-sneha-kumar",
        senderRole: "buyer",
        body: "Hi Nisha, I ordered the 25th Anniversary Tin 3 days ago. The tracking shows it's still at the dispatch hub in Hyderabad. Is there a delay?",
        isRead: true,
        sentAt: daysAgo(2),
      },
      {
        id: "msg-004-2",
        senderId: "user-nisha-reddy",
        senderRole: "seller",
        body: "Hi Sneha, apologies for the delay! There was a Diwali backlog at the courier facility â€” they've confirmed it will leave Hyderabad tonight. Updated tracking should show movement tomorrow morning. If it doesn't arrive by end of week, I'll initiate a replacement. Very sorry for the inconvenience!",
        isRead: true,
        sentAt: daysAgo(2),
      },
      {
        id: "msg-004-3",
        senderId: "user-sneha-kumar",
        senderRole: "buyer",
        body: "Thanks for the quick update, I appreciate it! I'll keep an eye on the tracking.",
        isRead: true,
        sentAt: daysAgo(1),
      },
    ],
    lastMessage: "Thanks for the quick update, I appreciate it! I'll keep an eye on the tracking.",
    lastMessageAt: daysAgo(1),
    unreadBuyer: 0,
    unreadSeller: 0,
    status: "active",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },

  // â”€â”€ 5. Nendoroid â€” Return request negotiation â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-nendo-kartik-priya-005",
    buyerId: "user-kartik-nair",
    buyerDisplayName: "Kartik Nair",
    sellerDisplayName: "Priya Singh",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    productId: "product-nendoroid-rem-rezero",
    productTitle: "Nendoroid Rem â€” Re:Zero #663",
    messages: [
      {
        id: "msg-005-1",
        senderId: "user-kartik-nair",
        senderRole: "buyer",
        body: "Hi, I received the Rem Nendoroid today but the hair accessory part is broken â€” it looks like it was cracked during shipping. Can I return it?",
        isRead: true,
        sentAt: minsAgo(180),
      },
      {
        id: "msg-005-2",
        senderId: "user-priya-singh",
        senderRole: "seller",
        body: "Oh no, I'm so sorry about that! Can you send me photos of the damage? The nendoroid was in perfect condition when I packed it â€” I double-boxed it with bubble wrap. If it was damaged in transit I can file a claim with the courier and either send a replacement part or issue a partial refund. Please don't ship it back yet until we figure out the best resolution.",
        isRead: true,
        sentAt: minsAgo(150),
      },
      {
        id: "msg-005-3",
        senderId: "user-kartik-nair",
        senderRole: "buyer",
        body: "Photos sent to your WhatsApp. The maid headband part snapped in two. The figure itself is fine. A replacement part or partial refund would be great â€” full return seems excessive for one small part.",
        isRead: false,
        sentAt: minsAgo(90),
      },
    ],
    lastMessage: "Photos sent to your WhatsApp. The maid headband part snapped in two. The figure itself is fine. A replacement part or partial refund would be great â€” full return seems excessive for one small part.",
    lastMessageAt: minsAgo(90),
    unreadBuyer: 0,
    unreadSeller: 1,
    status: "active",
    createdAt: minsAgo(180),
    updatedAt: minsAgo(90),
  },

  // â”€â”€ 6. Gundam PG â€” Pre-purchase spec check â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-gundam-divya-priya-006",
    buyerId: "user-divya-menon",
    buyerDisplayName: "Divya Menon",
    sellerDisplayName: "Priya Singh",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    productId: "product-gundam-rx78-mg",
    productTitle: "Gundam RX-78-2 MG 1/100 Ver. 3.0",
    messages: [
      {
        id: "msg-006-1",
        senderId: "user-divya-menon",
        senderRole: "buyer",
        body: "Is this the Ver. 3.0 or the 2.0? The listing says Ver. 3.0 but I want to double check. Also, is it the Japanese release or the global Bandai Spirits release?",
        isRead: true,
        sentAt: daysAgo(4),
      },
      {
        id: "msg-006-2",
        senderId: "user-priya-singh",
        senderRole: "seller",
        body: "Confirmed: this is the Ver. 3.0 â€” you can identify it by the full inner frame and the improved waist joint. Japanese release by Bandai Spirits (the successor brand to Bandai Hobby). Box is entirely in Japanese with the 'Bandai Spirits' logo on the bottom right. Instructions are in Japanese but the build sequence is identical to global releases.",
        isRead: true,
        sentAt: daysAgo(4),
      },
      {
        id: "msg-006-3",
        senderId: "user-divya-menon",
        senderRole: "buyer",
        body: "Perfect! That's the one I want. Placing the order now. Is there any risk of duty/customs charge since it's a Japan import?",
        isRead: true,
        sentAt: daysAgo(3),
      },
      {
        id: "msg-006-4",
        senderId: "user-priya-singh",
        senderRole: "seller",
        body: "This stock was already imported to India â€” I hold it domestically in Mumbai. You won't pay any customs. Delivery is via standard domestic courier, 3â€“5 business days.",
        isRead: true,
        sentAt: daysAgo(3),
      },
    ],
    lastMessage: "This stock was already imported to India â€” I hold it domestically in Mumbai. You won't pay any customs. Delivery is via standard domestic courier, 3â€“5 business days.",
    lastMessageAt: daysAgo(3),
    unreadBuyer: 0,
    unreadSeller: 0,
    status: "active",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
  },

  // â”€â”€ 7. Vintage Hot Wheels â€” Offer negotiation â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-vintage-hw-ankit-vikram-007",
    buyerId: "user-ankit-gupta",
    buyerDisplayName: "Ankit Gupta",
    sellerDisplayName: "Vikram Mehta",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    productId: "product-hot-wheels-redline-banana-1968",
    productTitle: "Hot Wheels Redline 1968 Custom Camaro (Banana Yellow)",
    messages: [
      {
        id: "msg-007-1",
        senderId: "user-ankit-gupta",
        senderRole: "buyer",
        body: "Would you take â‚¹10,000 for the Banana Yellow Camaro? I see it's listed at â‚¹12,999.",
        isRead: true,
        sentAt: daysAgo(6),
      },
      {
        id: "msg-007-2",
        senderId: "user-vikram-mehta",
        senderRole: "seller",
        body: "Hi Ankit! I paid â‚¹9,500 to source this from a Tokyo flea market including import costs, so â‚¹10,000 doesn't leave me much margin. Best I can do is â‚¹11,500 â€” that's a â‚¹1,500 discount and I'll cover shipping. The car is unplayed, original wheels, and the button pops correctly â€” it's a genuine 1968 US card.",
        isRead: true,
        sentAt: daysAgo(6),
      },
      {
        id: "msg-007-3",
        senderId: "user-ankit-gupta",
        senderRole: "buyer",
        body: "Fair enough â€” deal at â‚¹11,500 with free shipping. Can you create a custom listing or should I use the Make Offer feature?",
        isRead: true,
        sentAt: daysAgo(5),
      },
      {
        id: "msg-007-4",
        senderId: "user-vikram-mehta",
        senderRole: "seller",
        body: "I've updated the listing price to â‚¹11,500 for you. Add to cart now and use coupon DIECAST10 for the remainder of the discount. Will dispatch day after tomorrow.",
        isRead: true,
        sentAt: daysAgo(5),
      },
    ],
    lastMessage: "I've updated the listing price to â‚¹11,500 for you. Add to cart now and use coupon DIECAST10 for the remainder of the discount. Will dispatch day after tomorrow.",
    lastMessageAt: daysAgo(5),
    unreadBuyer: 0,
    unreadSeller: 0,
    status: "archived",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },

  // â”€â”€ 8. PokÃ©mon Booster Box â€” Bulk order query â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: "conv-bulkorder-rahul-aryan-008",
    buyerId: "user-rahul-sharma",
    buyerDisplayName: "Rahul Sharma",
    sellerDisplayName: "Aryan Kapoor",
    storeId: "store-pokemon-palace",
    storeName: "PokÃ©mon Palace",
    productId: "product-pokemon-151-booster-box",
    productTitle: "PokÃ©mon TCG: Scarlet & Violet 151 Booster Box",
    messages: [
      {
        id: "msg-008-1",
        senderId: "user-rahul-sharma",
        senderRole: "buyer",
        body: "Do you have 3 booster boxes of 151? Planning to run a draft with my local game store.",
        isRead: true,
        sentAt: minsAgo(240),
      },
      {
        id: "msg-008-2",
        senderId: "user-aryan-kapoor",
        senderRole: "seller",
        body: "Yes! I have 5 sealed boxes in stock. For 3+ boxes I can do â‚¹12,999 per box (saving â‚¹2,000 per box vs list price) + free shipping in a sturdy reinforced outer carton. All boxes are factory-sealed with intact shrinkwrap.",
        isRead: false,
        sentAt: minsAgo(200),
      },
    ],
    lastMessage: "Yes! I have 5 sealed boxes in stock. For 3+ boxes I can do â‚¹12,999 per box (saving â‚¹2,000 per box vs list price) + free shipping in a sturdy reinforced outer carton. All boxes are factory-sealed with intact shrinkwrap.",
    lastMessageAt: minsAgo(200),
    unreadBuyer: 1,
    unreadSeller: 0,
    status: "active",
    createdAt: minsAgo(240),
    updatedAt: minsAgo(200),
  },

  // â"€â"€ 9. Admin as buyer â€" MAFEX Miles Morales post-purchase tracking query â"€â"€
  {
    id: "conv-mafex-admin-priya-009",
    buyerId: "user-admin-letitrip",
    buyerDisplayName: "LetItRip Admin",
    sellerDisplayName: "Priya Anand",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    productId: "product-mafex-miles-morales-spiderman",
    productTitle: "MAFEX No.240: Miles Morales Spider-Man (Across the Spider-Verse)",
    messages: [
      {
        id: "msg-009-1",
        senderId: "user-admin-letitrip",
        senderRole: "buyer",
        body: "Hi! My order for MAFEX Miles Morales shipped 2 days ago - tracking shows it left your city but has not updated since. Can you check with Shiprocket?",
        isRead: true,
        sentAt: daysAgo(3),
      },
      {
        id: "msg-009-2",
        senderId: "user-priya-anand",
        senderRole: "seller",
        body: "Hi! Yes, I raised a ticket with Shiprocket about that. They confirmed it is in transit at the Mumbai sorting facility - tracking updates can lag by 24-48 hours. Should arrive tomorrow or day after. Apologies for the delay in the scan!",
        isRead: true,
        sentAt: daysAgo(3),
      },
      {
        id: "msg-009-3",
        senderId: "user-admin-letitrip",
        senderRole: "buyer",
        body: "Thanks for following up. Will keep an eye on it. The figure is for a platform demo so I do need it by Friday - hope it clears in time.",
        isRead: true,
        sentAt: daysAgo(2),
      },
      {
        id: "msg-009-4",
        senderId: "user-priya-anand",
        senderRole: "seller",
        body: "Completely understand. I have asked Shiprocket to flag it for priority delivery. If it does not arrive by Thursday let me know and I will arrange a direct courier at no extra charge.",
        isRead: false,
        sentAt: daysAgo(2),
      },
    ],
    lastMessage: "Completely understand. I have asked Shiprocket to flag it for priority delivery. If it does not arrive by Thursday let me know and I will arrange a direct courier at no extra charge.",
    lastMessageAt: daysAgo(2),
    unreadBuyer: 1,
    unreadSeller: 0,
    status: "active",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
];
