/**
 * Cosplay & Prop Accessories â€” Products Seed Data
 * Replica Props · Wearables · Cosplay Gear
 * 14 general · 1 auction · 1 pre-order = 16 total
 * Seller: CosPlay India Hub (store-cosplay-india-hub)
 */

import { getDefaultCurrency } from "./seed-market-config";
import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

const CP = {
  sellerId: "user-cosplay-india-owner",
  storeId: "cosplay-india-hub",
  sellerName: "CosPlay India Hub",
  sellerEmail: "cosplay@letitrip.in",
} as const;

const CP_IMGS = [
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Cosplay.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Anime_cosplay.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Cosplay_convention.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Anime_Expo_cosplay.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Cosplay_costume.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Convention_cosplay.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Anime_costume.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Cosplay_accessories.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Prop_replica.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Costume_prop.jpg?width=640",
];
const img = (seed: string) => {
  let h = 0; for (const c of seed) h = (h * 31 + c.charCodeAt(0)) & 0x7fff;
  return CP_IMGS[h % CP_IMGS.length];
};

export const cosplayAccessoriesSeedData: Partial<ProductDocument>[] = [

  // â”€â”€ REPLICA PROPS (5) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "product-cp-naruto-headband-konoha-cp-1",
    title: "Naruto Konoha Headband â€” Metal Plate Cosplay Replica",
    description: "<p>High-quality Naruto Leaf Village (Konoha) headband with zinc alloy metal plate and adjustable black cloth band. Accurate Konoha spiral leaf engraving. Fits all head sizes. Used by cosplayers across conventions. Comes with authentication card and display stand.</p>",
    slug: "product-naruto-konoha-headband-metal-cosplay-replica",
    category: "category-cosplay-props",
    subcategory: "Headbands",
    brand: "Naruto",
    price: 599,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 48,
    mainImage: img("naruto-headband-konoha"),
    images: [img("naruto-headband-konoha"), img("naruto-headband-back")],
    status: "published",
    ...CP,
    featured: true,
    tags: ["naruto", "konoha", "headband", "cosplay", "replica", "metal plate", "leaf village"],
    specifications: [
      { name: "Material", value: "Zinc alloy plate + cloth band" },
      { name: "Band Length", value: "Adjustable 40â€“60 cm" },
      { name: "Plate Size", value: "11 cm Ã— 5 cm" },
    ],
    features: ["Zinc alloy metal plate", "Accurate Konoha engraving", "Adjustable band", "Display stand included"],
    shippingInfo: "Padded envelope. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.8,
    reviewCount: 82,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-cp-dbz-scouter-green-cp-2",
    title: "Dragon Ball Z Scouter â€” Green Lens Replica (Wearable)",
    description: "<p>Wearable Dragon Ball Z Scouter in green â€” the power level reading device worn by Vegeta and Frieza's forces. Hard plastic frame with tinted green acrylic lens. Right-ear mount with elastic head strap. LED backlight effect optional model. It's over 9000!</p>",
    slug: "product-dbz-scouter-green-lens-wearable-replica",
    category: "category-cosplay-props",
    subcategory: "Wearable Props",
    brand: "Dragon Ball Z",
    price: 999,
    currency: _CURRENCY,
    stockQuantity: 35,
    availableQuantity: 32,
    mainImage: img("dbz-scouter-green"),
    images: [img("dbz-scouter-green"), img("dbz-scouter-worn")],
    status: "published",
    ...CP,
    featured: true,
    tags: ["dragon ball z", "scouter", "green", "cosplay", "wearable", "vegeta", "replica"],
    specifications: [
      { name: "Lens Colour", value: "Green tinted acrylic" },
      { name: "Mount", value: "Right ear with head strap" },
      { name: "LED", value: "Optional LED backlight version" },
    ],
    features: ["Wearable right-ear mount", "Tinted green acrylic lens", "Optional LED light", "Adjustable head strap"],
    shippingInfo: "Padded box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 47,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-cp-onepiece-straw-hat-replica-cp-3",
    title: "One Piece Luffy Straw Hat â€” Official Wearable Replica",
    description: "<p>Official Bandai-licensed wearable Luffy Straw Hat replica from One Piece. Woven natural straw with red band detail. One size fits most adults. The iconic accessory that defines the series â€” perfect for conventions, photoshoots, and display. Comes in official branded bag.</p>",
    slug: "product-one-piece-luffy-straw-hat-official-wearable",
    category: "category-cosplay-props",
    subcategory: "Hats & Accessories",
    brand: "One Piece",
    price: 1299,
    currency: _CURRENCY,
    stockQuantity: 40,
    availableQuantity: 37,
    mainImage: img("onepiece-straw-hat"),
    images: [img("onepiece-straw-hat"), img("onepiece-straw-hat-back")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["one piece", "luffy", "straw hat", "cosplay", "wearable", "official", "bandai"],
    specifications: [
      { name: "Material", value: "Natural woven straw" },
      { name: "Size", value: "One size fits most" },
      { name: "Detail", value: "Red band" },
      { name: "License", value: "Bandai official" },
    ],
    features: ["Official Bandai license", "Natural woven straw", "Red band detail", "Convention ready"],
    shippingInfo: "Original branded bag. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 61,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-cp-mha-deku-gloves-replica-cp-4",
    title: "My Hero Academia â€” Deku Hero Costume Gloves (Knuckle Guards)",
    description: "<p>Deku's iconic hero costume gloves with knuckle reinforcement guards. Heavyweight polyester outer with neoprene padding on knuckles. Beta and Gamma costume variants available. Adjustable wrist strap. Great for cosplay photography or convention wear.</p>",
    slug: "product-mha-deku-hero-gloves-knuckle-guards-cosplay",
    category: "category-cosplay-props",
    subcategory: "Wearable Props",
    brand: "My Hero Academia",
    price: 1499,
    currency: _CURRENCY,
    stockQuantity: 28,
    availableQuantity: 25,
    mainImage: img("mha-deku-gloves"),
    images: [img("mha-deku-gloves"), img("mha-deku-gloves-detail")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["my hero academia", "deku", "midoriya", "gloves", "cosplay", "hero costume"],
    specifications: [
      { name: "Material", value: "Polyester + neoprene knuckle pad" },
      { name: "Variants", value: "Beta and Gamma costume" },
      { name: "Sizing", value: "S/M/L/XL" },
    ],
    features: ["Neoprene knuckle guards", "Beta/Gamma variants", "Adjustable wrist strap", "Photography quality"],
    shippingInfo: "Padded envelope. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 29,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-cp-demon-slayer-nichirin-blade-cp-5",
    title: "Demon Slayer â€” Tanjiro Nichirin Blade Cosplay Prop",
    description: "<p>Tanjiro's iconic Nichirin Blade cosplay prop â€” black turning red gradient blade in EVA foam safe material. 90 cm total length including handle. Detailed tsuba guard, handle wrapping, and flame gradient tip. Safe for convention carry. Includes blade bag for transport.</p>",
    slug: "product-demon-slayer-tanjiro-nichirin-blade-eva-foam",
    category: "category-cosplay-props",
    subcategory: "Prop Weapons",
    brand: "Demon Slayer",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 22,
    availableQuantity: 19,
    mainImage: img("demonslayer-nichirin-blade"),
    images: [img("demonslayer-nichirin-blade"), img("demonslayer-nichirin-handle")],
    status: "published",
    ...CP,
    featured: true,
    tags: ["demon slayer", "tanjiro", "nichirin blade", "cosplay", "prop", "eva foam", "sword"],
    specifications: [
      { name: "Material", value: "EVA foam (convention safe)" },
      { name: "Total Length", value: "90 cm" },
      { name: "Blade Gradient", value: "Black to red flame tip" },
    ],
    features: ["EVA foam convention-safe", "90 cm full length", "Flame gradient blade", "Blade transport bag"],
    shippingInfo: "Long prop bag. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.7,
    reviewCount: 38,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(3),
  },

  // â”€â”€ TCG & CARD ACCESSORIES (5) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "product-cp-ultra-pro-card-sleeves-clear-cp-6",
    title: "Ultra PRO Platinum Card Sleeves â€” Perfect Clear (100 pack)",
    description: "<p>Ultra PRO Platinum series card sleeves â€” 100 pack of perfect clear standard size. Acid-free, archival quality. Ideal for grading candidates and tournament play. 66mm Ã— 91mm standard TCG size. UV protection coating. No-stick interior, smooth shuffle.</p>",
    slug: "product-ultra-pro-platinum-card-sleeves-clear-100pack",
    category: "category-tcg-accessories",
    subcategory: "Card Sleeves",
    brand: "Ultra PRO",
    price: 499,
    currency: _CURRENCY,
    stockQuantity: 100,
    availableQuantity: 97,
    mainImage: img("ultrapro-platinum-sleeves"),
    images: [img("ultrapro-platinum-sleeves")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["ultra pro", "card sleeves", "platinum", "clear", "100 pack", "tcg", "pokemon"],
    specifications: [
      { name: "Size", value: "66 Ã— 91 mm (Standard)" },
      { name: "Quantity", value: "100 sleeves" },
      { name: "Material", value: "Acid-free archival" },
    ],
    features: ["Acid-free archival", "UV protection", "Smooth no-stick interior", "Tournament legal"],
    shippingInfo: "Padded envelope. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 124,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(1),
  },

  {
    id: "product-cp-bcw-toploader-card-holder-cp-7",
    title: "BCW Toploaders â€” 3 Ã— 4 Rigid Card Holders (25 pack)",
    description: "<p>BCW 3Ã—4 inch rigid toploaders â€” industry-standard hard card protectors for grading candidates and display. 35pt thickness for standard cards. Each toploader has a sliding lip for safe card insert. Ideal for PSA/BGS grading submissions or display.</p>",
    slug: "product-bcw-3x4-toploader-card-holders-25pack",
    category: "category-tcg-accessories",
    subcategory: "Toploaders",
    brand: "BCW",
    price: 349,
    currency: _CURRENCY,
    stockQuantity: 80,
    availableQuantity: 77,
    mainImage: img("bcw-toploader-25pack"),
    images: [img("bcw-toploader-25pack")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["bcw", "toploader", "card holder", "3x4", "25 pack", "grading", "psa"],
    specifications: [
      { name: "Size", value: "3 Ã— 4 inches" },
      { name: "Thickness", value: "35pt" },
      { name: "Quantity", value: "25 per pack" },
    ],
    features: ["Industry standard 35pt", "Sliding lip design", "PSA/BGS submission ready", "Rigid hard case"],
    shippingInfo: "Padded envelope. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 89,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-cp-pokemon-binder-9pocket-cp-8",
    title: "Pokemon TCG â€” 9-Pocket Premium Binder (Pikachu Edition, 360 cards)",
    description: "<p>Premium 360-card Pikachu-themed 9-pocket binder for Pokemon TCG collection storage. Clear PVC pockets with side-loading to prevent card fall. Hardcover with Pikachu artwork on front and back. Spine label window. Includes 40 double-sided pages = 360 card capacity.</p>",
    slug: "product-pokemon-tcg-9pocket-binder-pikachu-360cards",
    category: "category-tcg-accessories",
    subcategory: "Binders",
    brand: "Pokemon",
    price: 1299,
    currency: _CURRENCY,
    stockQuantity: 45,
    availableQuantity: 42,
    mainImage: img("pokemon-binder-pikachu"),
    images: [img("pokemon-binder-pikachu"), img("pokemon-binder-inside")],
    status: "published",
    ...CP,
    featured: true,
    tags: ["pokemon", "binder", "9 pocket", "pikachu", "360 cards", "tcg", "collection"],
    specifications: [
      { name: "Capacity", value: "360 cards (40 double-sided pages)" },
      { name: "Pocket Config", value: "9-pocket side-loading" },
      { name: "Artwork", value: "Pikachu front and back" },
    ],
    features: ["360 card capacity", "Side-loading pockets", "Hardcover protection", "Pikachu themed artwork"],
    shippingInfo: "Padded packaging. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(25),
    avgRating: 4.8,
    reviewCount: 67,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-cp-display-case-acrylic-single-cp-9",
    title: "Acrylic Display Case â€” Single Card UV-Block (Graded/Raw)",
    description: "<p>Premium UV-blocking acrylic single card display case â€” for raw or graded cards (PSA slab compatible). Magnetic sealed lid with foam insert. UV-protection acrylic blocks 98% of UV rays. Perfect for displaying your most prized card on a desk or shelf.</p>",
    slug: "product-acrylic-display-case-single-card-uv-block",
    category: "category-tcg-accessories",
    subcategory: "Display Cases",
    brand: "Generic",
    price: 799,
    currency: _CURRENCY,
    stockQuantity: 60,
    availableQuantity: 55,
    mainImage: img("acrylic-card-display"),
    images: [img("acrylic-card-display"), img("acrylic-card-display-open")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["acrylic", "display case", "card", "uv block", "psa", "graded", "raw"],
    specifications: [
      { name: "UV Protection", value: "98% UV blocking" },
      { name: "Closure", value: "Magnetic sealed lid" },
      { name: "Compatibility", value: "Raw cards + PSA slabs" },
    ],
    features: ["98% UV blocking", "Magnetic sealed closure", "PSA slab compatible", "Foam insert"],
    shippingInfo: "Bubble wrapped. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 43,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-cp-card-grading-kit-bundle-cp-10",
    title: "Card Grading Submission Kit â€” Complete Bundle (PSA/BGS Ready)",
    description: "<p>Complete card grading submission kit for PSA, BGS, or CGC. Includes 20 toploaders, 50 card sleeves, 10 foam inserts, 20 packing bubbles, and step-by-step guide PDF. Everything you need to safely ship your most valuable cards for professional grading. Secure your investment correctly.</p>",
    slug: "product-card-grading-submission-kit-psa-bgs-ready",
    category: "category-tcg-accessories",
    subcategory: "Grading Supplies",
    brand: "Generic",
    price: 999,
    currency: _CURRENCY,
    stockQuantity: 40,
    availableQuantity: 38,
    mainImage: img("grading-kit-bundle"),
    images: [img("grading-kit-bundle"), img("grading-kit-contents")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["grading", "psa", "bgs", "cgc", "submission kit", "toploaders", "card protection"],
    specifications: [
      { name: "Contents", value: "20 toploaders + 50 sleeves + 10 foam inserts + 20 bubbles + guide" },
    ],
    features: ["PSA/BGS/CGC compatible", "Complete kit", "Submission guide PDF", "Professional packing materials"],
    shippingInfo: "Padded envelope. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 55,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(5),
  },

  // â”€â”€ COLLECTOR DISPLAY (4) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "product-cp-acrylic-figure-display-cp-11",
    title: "Acrylic Figure Display Case â€” 3-Tier Rotating (Dustproof)",
    description: "<p>Premium 3-tier rotating acrylic figure display case â€” holds up to 9 medium figures or 18 small nendoroids. Motorised 360Â° rotation (USB powered). Dust-proof clear acrylic panels. LED strip lighting inside each tier. Perfect for S.H.Figuarts, Nendoroids, and Funko Pops.</p>",
    slug: "product-acrylic-figure-display-3tier-rotating-led",
    category: "category-cosplay-props",
    subcategory: "Display Cases",
    brand: "Generic",
    price: 3999,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 17,
    mainImage: img("figure-display-3tier"),
    images: [img("figure-display-3tier"), img("figure-display-led-on")],
    status: "published",
    ...CP,
    featured: true,
    tags: ["display case", "acrylic", "rotating", "led", "figure", "nendoroid", "figuarts"],
    specifications: [
      { name: "Tiers", value: "3" },
      { name: "Rotation", value: "360Â° motorised" },
      { name: "Power", value: "USB-powered" },
      { name: "Lighting", value: "LED strip per tier" },
    ],
    features: ["Motorised 360Â° rotation", "LED lighting per tier", "Dustproof acrylic", "Holds 9+ medium figures"],
    shippingInfo: "Padded rigid box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.7,
    reviewCount: 31,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-cp-funko-pop-protector-cp-12",
    title: "Funko Pop Protector â€” Hard Stack Premium (Standard Size, 10-pack)",
    description: "<p>Premium hard stack Funko Pop protectors â€” standard box size 10-pack. 0.5mm PET clear plastic, UV blocking. Tab-lock system that doesn't need tape. Fits all standard 6-inch Funko Pop boxes. Stack-compatible design. Protect your collection without opening boxes.</p>",
    slug: "product-funko-pop-hard-stack-protector-10pack-standard",
    category: "category-cosplay-props",
    subcategory: "Display Accessories",
    brand: "Generic",
    price: 899,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 47,
    mainImage: img("funko-pop-protectors"),
    images: [img("funko-pop-protectors")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["funko pop", "protector", "hard stack", "standard size", "10 pack", "uv blocking"],
    specifications: [
      { name: "Material", value: "0.5mm PET clear" },
      { name: "Quantity", value: "10 per pack" },
      { name: "Closure", value: "Tab-lock (no tape)" },
      { name: "Fits", value: "Standard 6-inch Funko boxes" },
    ],
    features: ["0.5mm thick PET", "UV blocking", "Tab-lock no tape", "Stack compatible"],
    shippingInfo: "Flat-pack envelope. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 78,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-cp-floating-shelves-collectibles-cp-13",
    title: "Floating Wall Shelf Set â€” Collector's Edition (3-shelf, Black)",
    description: "<p>Collectibles floating wall shelf set â€” 3 shelves in matte black finish. Each shelf holds up to 5kg. Adjustable LED strip channels on back. Perfect for anime figures, Funko Pops, LEGO sets, and car models. Heavy-duty wall anchors included. Easy 20-minute installation.</p>",
    slug: "product-floating-wall-shelves-collectors-3shelf-black",
    category: "category-cosplay-props",
    subcategory: "Display Furniture",
    brand: "Generic",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 12,
    mainImage: img("floating-shelves-black"),
    images: [img("floating-shelves-black"), img("floating-shelves-installed")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["floating shelves", "wall shelf", "collectibles", "display", "black", "3 shelf"],
    specifications: [
      { name: "Quantity", value: "3 shelves" },
      { name: "Finish", value: "Matte black" },
      { name: "Load", value: "5 kg per shelf" },
      { name: "LED", value: "Back channel for LED strip" },
    ],
    features: ["5kg load per shelf", "LED channel back", "Heavy-duty anchors", "20-minute install"],
    shippingInfo: "Boxed flat-pack. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 22,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-cp-enamel-pin-set-anime-cp-14",
    title: "Anime Enamel Pin Set â€” 10-pack (Mixed Characters, Hard Enamel)",
    description: "<p>Collector's anime enamel pin set â€” 10 hard enamel pins featuring characters from Dragon Ball Z, Naruto, One Piece, and My Hero Academia. 2.5 cm average size, butterfly clutch backs. Perfect for jackets, bags, and display boards. Gold metal border on all pins. Gift-boxed.</p>",
    slug: "product-anime-enamel-pin-set-10pack-mixed-dbz-naruto",
    category: "category-cosplay-props",
    subcategory: "Enamel Pins",
    brand: "Generic",
    price: 999,
    currency: _CURRENCY,
    stockQuantity: 60,
    availableQuantity: 56,
    mainImage: img("anime-enamel-pins"),
    images: [img("anime-enamel-pins"), img("anime-enamel-pins-close")],
    status: "published",
    ...CP,
    featured: false,
    tags: ["enamel pins", "anime", "dbz", "naruto", "one piece", "mha", "10 pack", "hard enamel"],
    specifications: [
      { name: "Quantity", value: "10 pins" },
      { name: "Size", value: "~2.5 cm average" },
      { name: "Type", value: "Hard enamel, gold border" },
      { name: "Closure", value: "Butterfly clutch" },
    ],
    features: ["10 mixed character pins", "Hard enamel gold border", "Butterfly clutch backs", "Gift boxed"],
    shippingInfo: "Gift box, padded envelope. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 93,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(3),
  },

  // â”€â”€ AUCTION (1) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "auction-cp-signed-dbz-cell-game-art-cp-1",
    title: "AUCTION â€” Dragon Ball Z Cell Game Original Cel Art (Signed, 1992)",
    description: "<p>Original Dragon Ball Z animation cel from the Cell Game saga â€” frame #247 from episode 177. Hand-painted on acetate, mounted on original background watercolour. Authentication letter from Toei Animation licensed archives. Signed by the lead animator in Japanese. Framed in archival UV glass frame.</p>",
    slug: "auction-dbz-cell-game-original-cel-art-1992",
    category: "category-cosplay-props",
    subcategory: "Original Art",
    brand: "Dragon Ball Z",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("dbz-cel-art-auction"),
    images: [img("dbz-cel-art-auction"), img("dbz-cel-art-frame"), img("dbz-cel-art-signature")],
    status: "published",
    ...CP,
    featured: true,
    tags: ["dragon ball z", "cel art", "original", "animation", "1992", "auction", "signed", "toei"],
    specifications: [
      { name: "Type", value: "Original animation cel on acetate" },
      { name: "Episode", value: "177 â€” Cell Game Saga, Frame #247" },
      { name: "Year", value: "1992" },
      { name: "Authentication", value: "Toei Animation licensed archives" },
      { name: "Signature", value: "Lead animator (Japanese)" },
    ],
    features: ["Original 1992 Toei cel", "Toei authentication letter", "Signed by lead animator", "UV archival glass frame"],
    shippingInfo: "White-glove framed art shipping. Insured nationwide.",
    returnPolicy: "No returns on auction wins.",
    condition: "used",
    insurance: true,
    insuranceCost: 1499,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(14),
    startingBid: 14999,
    currentBid: 26000,
    bidCount: 8,
    reservePrice: 30000,
    buyNowPrice: 74999,
    minBidIncrement: 2000,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionOriginalEndDate: daysAhead(14),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },

  // â”€â”€ PRE-ORDER (1) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "preorder-cp-anime-india-expo-bundle-2026-cp-1",
    title: "PRE-ORDER â€” Anime India Expo 2026 Collector Bundle (Limited)",
    description: "<p>Pre-order the exclusive Anime India Expo 2026 Collector Bundle â€” includes 3 signed art prints, 5 exclusive convention enamel pins, 1 limited-run figure (character TBA at expo), and VIP expo pass. India's biggest anime convention returns in Feb 2026. Only 200 bundles available India-wide.</p>",
    slug: "preorder-anime-india-expo-2026-collector-bundle",
    category: "category-cosplay-props",
    subcategory: "Convention Bundles",
    brand: "Generic",
    price: 5999,
    currency: _CURRENCY,
    stockQuantity: 200,
    availableQuantity: 176,
    mainImage: img("anime-expo-2026-bundle"),
    images: [img("anime-expo-2026-bundle")],
    status: "published",
    ...CP,
    featured: true,
    tags: ["anime", "expo", "india", "2026", "convention", "pre-order", "bundle", "vip"],
    specifications: [
      { name: "Contents", value: "3 signed prints + 5 pins + 1 figure + VIP pass" },
      { name: "Total Available", value: "200 bundles" },
      { name: "Date", value: "Feb 2026" },
    ],
    features: ["VIP expo pass", "3 signed art prints", "5 exclusive pins", "Limited figure (TBA)"],
    shippingInfo: "Pickup at expo or shipped post-event.",
    returnPolicy: "Non-refundable after booking. Transferable.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(270),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(120),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
];