/*
 * WHY: Seeds 55 FAQs for LetItRip collectibles marketplace — covers general platform, shipping,
 *      returns, payments, auctions, pre-orders, product info, account/security, scam awareness.
 * WHAT: Mix of broad collectibles marketplace FAQs + category-specific FAQs (trading cards, action figures,
 *       diecast, Beyblade, model kits, grading, authenticity, bundles, prize draws).
 *
 * EXPORTS:
 *   faqSeedData — Array of Partial<FAQDocument> for seed runner
 *
 * @tag domain:faqs
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts,SeedPanel
 * @tag sideEffects:none
 */

import type { FAQDocument } from "../features/faq/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const html = (text: string) => ({ text, format: "html" as const });
const makeStats = (views = 0, helpful = 0) => ({ views, helpful, notHelpful: 0 });

export const faqSeedData: Partial<FAQDocument>[] = [

  // ── GENERAL (10) ────────────────────────────────────────────────────────────

  {
    id: "faq-what-is-letitrip",
    question: "What is LetItRip?",
    answer: html(`<p><strong>LetItRip</strong> is India's largest collectibles marketplace — trading cards (Pokémon, Yu-Gi-Oh!, One Piece), action figures (Bandai, McFarlane, Good Smile), diecast vehicles (Hot Wheels, Tomica), Beyblades, model kits (Gundam, Zoids), and vintage/rare collectibles. Every seller is manually verified before they can list.</p><p>LetItRip is a <strong>platform</strong> that connects buyers with independent sellers. We handle payments, escrow, and dispute mediation — but we are not the seller. Each store has its own shipping, return, and authenticity policies.</p>`),
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: true,
    order: 1,
    priority: 10,
    tags: ["about", "letitrip", "platform", "marketplace", "collectibles"],
    relatedFAQs: ["faq-is-letitrip-safe", "faq-how-does-letitrip-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(8200, 410),
    seo: { slug: "faq-what-is-letitrip", metaTitle: "What is LetItRip? India's Collectibles Marketplace", metaDescription: "LetItRip is India's verified collectibles marketplace for trading cards, action figures, diecast vehicles, and more." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
  },
  {
    id: "faq-is-letitrip-safe",
    question: "Is LetItRip safe to buy from?",
    answer: html(`<p>Yes. All sellers are verified before they can list. Payments go through secure escrow — sellers only get paid after you confirm delivery. If something goes wrong, our support team mediates the dispute.</p>`),
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 9,
    tags: ["safety", "escrow", "trust"],
    relatedFAQs: ["faq-what-is-letitrip", "faq-what-is-escrow"],
    stats: makeStats(5400, 270),
    seo: { slug: "faq-is-letitrip-safe", metaTitle: "Is LetItRip Safe?", metaDescription: "Learn about LetItRip's seller verification, payment escrow, and buyer protection." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-how-does-letitrip-work",
    question: "How does buying on LetItRip work?",
    answer: html(`<p>Browse verified stores, add items to your cart, and checkout with Razorpay (UPI, cards, net banking). Your payment is held in escrow until you confirm delivery. Sellers ship directly to you — check each store's shipping policy for timelines.</p>`),
    category: "general",
    showOnHomepage: true,
    showInFooter: true,
    isPinned: false,
    order: 3,
    priority: 8,
    tags: ["buying", "checkout", "how-it-works"],
    relatedFAQs: ["faq-what-is-escrow", "faq-payment-methods"],
    stats: makeStats(4100, 205),
    seo: { slug: "faq-how-does-letitrip-work", metaTitle: "How Does LetItRip Work?", metaDescription: "Step-by-step guide to buying collectibles on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(110),
    updatedAt: daysAgo(8),
  },
  {
    id: "faq-how-to-sell-on-letitrip",
    question: "How do I become a seller on LetItRip?",
    answer: html(`<p>Go to your Account → Become a Seller. Fill in your store details, upload verification documents, and submit for review. Our team typically approves sellers within 48 hours. Once approved, you can start listing immediately.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 4,
    priority: 7,
    tags: ["seller", "registration", "store"],
    relatedFAQs: ["faq-seller-fees", "faq-seller-payout-schedule"],
    stats: makeStats(3200, 160),
    seo: { slug: "faq-how-to-sell-on-letitrip", metaTitle: "How to Sell on LetItRip", metaDescription: "Become a verified seller on India's largest collectibles marketplace." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(15),
  },
  {
    id: "faq-what-categories-available",
    question: "What types of collectibles can I find on LetItRip?",
    answer: html(`<p>LetItRip covers six major categories: <strong>Trading Cards</strong> (Pokémon, Yu-Gi-Oh!, One Piece, Dragon Ball), <strong>Action Figures</strong> (Bandai, McFarlane, Good Smile, NECA, Funko Pop), <strong>Diecast Vehicles</strong> (Hot Wheels, Tomica, Matchbox), <strong>Spinning Tops</strong> (Beyblade X, Burst, Metal Saga), <strong>Model Kits</strong> (Gundam, Zoids, Evangelion), and <strong>Vintage & Rare</strong> collectibles. Each category has subcategories for easy browsing.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["categories", "products", "collectibles"],
    relatedFAQs: ["faq-what-is-letitrip"],
    stats: makeStats(2800, 140),
    seo: { slug: "faq-what-categories-available", metaTitle: "What Collectibles Are on LetItRip?", metaDescription: "Browse trading cards, action figures, diecast, Beyblades, model kits, and vintage collectibles." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(95),
    updatedAt: daysAgo(20),
  },
  {
    id: "faq-make-an-offer",
    question: "Can I negotiate the price with a seller?",
    answer: html(`<p>Yes! Most listings have a "Make an Offer" button. Submit your offer and the seller can accept, counter, or decline. If accepted, the item is locked at the agreed price for 24 hours so you can complete checkout.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 6,
    tags: ["offer", "negotiation", "price"],
    relatedFAQs: ["faq-how-does-letitrip-work"],
    stats: makeStats(2500, 125),
    seo: { slug: "faq-make-an-offer", metaTitle: "Make an Offer on LetItRip", metaDescription: "Negotiate prices with sellers on India's collectibles marketplace." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(14),
  },
  {
    id: "faq-what-is-escrow",
    question: "What is escrow and how does it protect me?",
    answer: html(`<p>Escrow means your payment is held by LetItRip — not sent directly to the seller. The seller ships the item, you receive it, and only when you confirm delivery (or 7 days pass without a dispute) does the seller get paid. This protects both buyers and sellers from fraud.</p>`),
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 9,
    tags: ["escrow", "trust", "buyer-protection"],
    relatedFAQs: ["faq-is-letitrip-safe", "faq-payment-methods"],
    stats: makeStats(4300, 215),
    seo: { slug: "faq-what-is-escrow", metaTitle: "How Escrow Works on LetItRip", metaDescription: "Understand how escrow protects your collectibles purchases." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(108),
    updatedAt: daysAgo(8),
  },
  {
    id: "faq-wishlists-and-alerts",
    question: "Can I save items and get notified about price drops?",
    answer: html(`<p>Yes! Add any listing to your Wishlist (up to 20 items). You'll receive notifications when a wishlisted item drops in price, gets relisted, or when similar items appear. Your recently viewed items are also saved in your browsing history (up to 50).</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 5,
    tags: ["wishlist", "alerts", "price-drop", "history"],
    relatedFAQs: ["faq-how-does-letitrip-work"],
    stats: makeStats(1800, 90),
    seo: { slug: "faq-wishlists-and-alerts", metaTitle: "Wishlists & Price Alerts", metaDescription: "Save items and get price drop alerts on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(8),
  },
  {
    id: "faq-bundles-and-deals",
    question: "What are bundles and how do they save me money?",
    answer: html(`<p>Bundles are curated sets of related collectibles sold at a discount. For example, a complete Beyblade starter set or a sealed Pokémon booster box + sleeves + playmat combo. Sellers create bundles to offer savings on grouped items — look for the savings badge on each bundle listing.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 5,
    tags: ["bundles", "deals", "savings"],
    relatedFAQs: ["faq-what-categories-available"],
    stats: makeStats(1400, 70),
    seo: { slug: "faq-bundles-and-deals", metaTitle: "Bundles & Deals on LetItRip", metaDescription: "Save money on curated collectible bundles on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "faq-prize-draws-how-they-work",
    question: "How do prize draws and spin wheels work?",
    answer: html(`<p>LetItRip runs community prize draws tied to events. Enter eligible events for a chance to win rare collectibles. Some events feature a spin wheel — spin for instant prizes like discount coupons or free shipping. Winners are selected using cryptographically random selection. Check the Events page for active draws.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 10,
    priority: 5,
    tags: ["prize-draw", "spin-wheel", "events", "raffle"],
    relatedFAQs: ["faq-community-events"],
    stats: makeStats(1100, 55),
    seo: { slug: "faq-prize-draws-how-they-work", metaTitle: "Prize Draws & Spin Wheels", metaDescription: "Enter prize draws and spin wheels to win rare collectibles on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(3),
  },

  // ── SHIPPING & DELIVERY (7) ────────────────────────────────────────────────

  {
    id: "faq-how-long-does-shipping-take",
    question: "How long does shipping take?",
    answer: html(`<p>Shipping timelines depend on the seller's location and chosen courier. Most sellers ship within 1–3 business days. Domestic delivery typically takes 3–7 business days. Check each store's shipping policy for specifics.</p>`),
    category: "shipping_delivery",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 11,
    priority: 9,
    tags: ["shipping", "delivery", "timeline"],
    relatedFAQs: ["faq-track-my-order", "faq-how-are-cards-packaged"],
    stats: makeStats(6100, 305),
    seo: { slug: "faq-how-long-does-shipping-take", metaTitle: "Shipping Times on LetItRip", metaDescription: "Typical shipping timelines for collectibles orders on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(115),
    updatedAt: daysAgo(7),
  },
  {
    id: "faq-how-are-cards-packaged",
    question: "How are collectibles packaged for shipping?",
    answer: html(`<p>All verified sellers follow category-specific packaging standards: <strong>Trading cards</strong> — penny sleeves + top-loaders, rigid mailers. <strong>Action figures</strong> — bubble wrap, double-boxed for mint-in-box items. <strong>Diecast/Beyblade</strong> — foam inserts, padded boxes. <strong>Graded slabs</strong> — padded fitted boxes. If an item arrives damaged due to poor packaging, open a dispute and our team will mediate.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 12,
    priority: 7,
    tags: ["packaging", "shipping", "protection"],
    relatedFAQs: ["faq-damaged-in-transit"],
    stats: makeStats(3400, 170),
    seo: { slug: "faq-how-are-cards-packaged", metaTitle: "Packaging Standards for Collectibles", metaDescription: "How sellers package collectibles for safe delivery on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(110),
    updatedAt: daysAgo(12),
  },
  {
    id: "faq-free-shipping-available",
    question: "Is free shipping available?",
    answer: html(`<p>Many sellers offer free shipping on orders above a certain amount. Look for the "Free Shipping" badge on product listings. You can also use the FREESHIP999 coupon for free shipping on orders ₹999+.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 13,
    priority: 6,
    tags: ["free-shipping", "coupons"],
    relatedFAQs: ["faq-coupons-and-discounts"],
    stats: makeStats(2900, 145),
    seo: { slug: "faq-free-shipping-available", metaTitle: "Free Shipping on LetItRip", metaDescription: "How to get free shipping on your collectibles orders." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(14),
  },
  {
    id: "faq-international-shipping",
    question: "Do you ship internationally?",
    answer: html(`<p>LetItRip currently operates within India only. International shipping is not supported at this time. We're working on expanding to more countries — stay tuned!</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 14,
    priority: 5,
    tags: ["international", "shipping"],
    relatedFAQs: [],
    stats: makeStats(1800, 90),
    seo: { slug: "faq-international-shipping", metaTitle: "International Shipping", metaDescription: "LetItRip currently ships within India only." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(30),
  },
  {
    id: "faq-track-my-order",
    question: "How do I track my order?",
    answer: html(`<p>Once your seller ships the order, you'll receive a tracking number via email and in-app notification. Go to Account → My Orders → click the order to see real-time tracking. Most sellers use Shiprocket for automated tracking updates.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 15,
    priority: 8,
    tags: ["tracking", "orders", "shiprocket"],
    relatedFAQs: ["faq-how-long-does-shipping-take"],
    stats: makeStats(4500, 225),
    seo: { slug: "faq-track-my-order", metaTitle: "Track Your Order", metaDescription: "How to track your collectibles order on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(105),
    updatedAt: daysAgo(9),
  },
  {
    id: "faq-shipping-for-large-items",
    question: "How are large items like statues and display cases shipped?",
    answer: html(`<p>Oversized items (large action figures, resin statues, display shelves) are shipped via specialist couriers with additional insurance. Sellers may charge a higher shipping fee for fragile oversized items. Delivery timelines for these may be 5–10 business days depending on location.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 16,
    priority: 5,
    tags: ["large-items", "shipping", "statues", "insurance"],
    relatedFAQs: ["faq-how-are-cards-packaged"],
    stats: makeStats(900, 45),
    seo: { slug: "faq-shipping-for-large-items", metaTitle: "Shipping Large Collectibles", metaDescription: "How oversized items like statues and display cases are shipped on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-shiprocket-auto-tracking",
    question: "What is Shiprocket and how does auto-tracking work?",
    answer: html(`<p>Shiprocket is our integrated courier partner. When a seller marks your order as shipped with Shiprocket, tracking is automatically created — you'll get real-time SMS and email updates at every milestone (picked up, in transit, out for delivery, delivered). No manual tracking number entry needed.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 17,
    priority: 6,
    tags: ["shiprocket", "tracking", "automation"],
    relatedFAQs: ["faq-track-my-order"],
    stats: makeStats(1500, 75),
    seo: { slug: "faq-shiprocket-auto-tracking", metaTitle: "Shiprocket Auto-Tracking", metaDescription: "How Shiprocket auto-tracking works for your LetItRip orders." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },

  // ── RETURNS & REFUNDS (7) ─────────────────────────────────────────────────

  {
    id: "faq-return-policy",
    question: "What is LetItRip's return policy?",
    answer: html(`<p>Each store sets its own return policy. Most stores accept returns within 7 days for items not as described. Graded cards (PSA/BGS/CGC) and sealed products are typically final sale. Always check the store's return policy before purchasing. If a seller doesn't honor their policy, open a support ticket and we'll mediate.</p>`),
    category: "returns_refunds",
    showOnHomepage: true,
    showInFooter: true,
    isPinned: false,
    order: 18,
    priority: 9,
    tags: ["returns", "refunds", "policy"],
    relatedFAQs: ["faq-how-to-request-refund", "faq-counterfeit-guarantee"],
    stats: makeStats(5800, 290),
    seo: { slug: "faq-return-policy", metaTitle: "Return Policy on LetItRip", metaDescription: "Understand return policies for collectibles purchases on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(115),
    updatedAt: daysAgo(6),
  },
  {
    id: "faq-how-to-request-refund",
    question: "How do I request a refund?",
    answer: html(`<p>Go to Account → My Orders → select the order → Request Refund. Describe the issue and upload photos if the item is damaged or not as described. The seller has 48 hours to respond. If they don't, LetItRip support will step in.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 19,
    priority: 8,
    tags: ["refund", "dispute", "support"],
    relatedFAQs: ["faq-return-policy", "faq-refund-timeline"],
    stats: makeStats(3700, 185),
    seo: { slug: "faq-how-to-request-refund", metaTitle: "Request a Refund", metaDescription: "How to request a refund for your LetItRip order." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(11),
  },
  {
    id: "faq-card-not-as-described",
    question: "What if the item I received doesn't match the listing?",
    answer: html(`<p>If the condition, edition, brand, or any detail doesn't match what was listed, you're eligible for a full refund. Take clear photos of the item next to the listing screenshots, then open a dispute through Account → My Orders. Our team reviews disputes within 24 hours.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 20,
    priority: 7,
    tags: ["dispute", "condition", "mismatch"],
    relatedFAQs: ["faq-how-to-request-refund"],
    stats: makeStats(2600, 130),
    seo: { slug: "faq-card-not-as-described", metaTitle: "Item Not as Described", metaDescription: "What to do if your collectible doesn't match the listing on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(18),
  },
  {
    id: "faq-refund-timeline",
    question: "How long do refunds take?",
    answer: html(`<p>Once a refund is approved, it's processed within 3–5 business days. UPI refunds are typically faster (1–2 days). Card and net banking refunds may take up to 7 business days depending on your bank.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 21,
    priority: 6,
    tags: ["refund", "timeline", "processing"],
    relatedFAQs: ["faq-how-to-request-refund"],
    stats: makeStats(2100, 105),
    seo: { slug: "faq-refund-timeline", metaTitle: "Refund Processing Time", metaDescription: "How long refunds take on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(22),
  },
  {
    id: "faq-damaged-in-transit",
    question: "What if my item is damaged during shipping?",
    answer: html(`<p>If an item arrives damaged due to poor packaging or courier handling, take photos immediately — before removing the item from the mailer. Open a dispute with the photos attached. Sellers are responsible for packaging quality; LetItRip will mediate if the seller disputes your claim.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 22,
    priority: 7,
    tags: ["damaged", "shipping", "dispute"],
    relatedFAQs: ["faq-how-are-cards-packaged", "faq-how-to-request-refund"],
    stats: makeStats(1900, 95),
    seo: { slug: "faq-damaged-in-transit", metaTitle: "Item Damaged in Transit", metaDescription: "What to do if your collectible arrives damaged." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(25),
  },
  {
    id: "faq-counterfeit-guarantee",
    question: "What if I receive a counterfeit item?",
    answer: html(`<p>LetItRip has a <strong>zero-tolerance counterfeit policy</strong>. If you receive a counterfeit item, open a dispute with photo evidence. You'll receive a full refund and the seller's account will be reviewed for suspension. For high-value items, we recommend buying graded/certified products which come with third-party authentication.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 23,
    priority: 9,
    tags: ["counterfeit", "fake", "authenticity", "guarantee"],
    relatedFAQs: ["faq-return-policy", "faq-how-to-verify-authenticity"],
    stats: makeStats(3600, 180),
    seo: { slug: "faq-counterfeit-guarantee", metaTitle: "Counterfeit Protection on LetItRip", metaDescription: "Zero-tolerance counterfeit policy with full refund guarantee." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(7),
  },
  {
    id: "faq-partial-refund",
    question: "Can I get a partial refund instead of a full return?",
    answer: html(`<p>Yes — if the item is mostly as described but has a minor discrepancy (e.g., slightly different condition grade, missing an accessory), you can negotiate a partial refund with the seller through the dispute system. Both parties must agree to the partial refund amount before it's processed.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 24,
    priority: 5,
    tags: ["partial-refund", "negotiation", "dispute"],
    relatedFAQs: ["faq-how-to-request-refund"],
    stats: makeStats(800, 40),
    seo: { slug: "faq-partial-refund", metaTitle: "Partial Refunds on LetItRip", metaDescription: "How partial refunds work on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(10),
  },

  // ── ORDERS & PAYMENT (7) ──────────────────────────────────────────────────

  {
    id: "faq-payment-methods",
    question: "What payment methods are accepted?",
    answer: html(`<p>LetItRip accepts UPI (GPay, PhonePe, Paytm), credit/debit cards, net banking, and wallets via Razorpay. All payments are processed through secure escrow — the seller only receives funds after you confirm delivery.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 25,
    priority: 8,
    tags: ["payment", "upi", "razorpay", "escrow"],
    relatedFAQs: ["faq-what-is-escrow"],
    stats: makeStats(5100, 255),
    seo: { slug: "faq-payment-methods", metaTitle: "Payment Methods on LetItRip", metaDescription: "UPI, cards, net banking — all payment options on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(110),
    updatedAt: daysAgo(6),
  },
  {
    id: "faq-coupons-and-discounts",
    question: "How do I use coupons and discount codes?",
    answer: html(`<p>Enter your coupon code at checkout in the "Apply Coupon" field. Coupons may be platform-wide (from LetItRip) or store-specific (from individual sellers). Some coupons have minimum order requirements, expiry dates, or per-user limits. You cannot stack multiple coupons on a single order unless the coupon explicitly allows it.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 26,
    priority: 6,
    tags: ["coupons", "discount", "promo-code"],
    relatedFAQs: ["faq-free-shipping-available"],
    stats: makeStats(2200, 110),
    seo: { slug: "faq-coupons-and-discounts", metaTitle: "Using Coupons on LetItRip", metaDescription: "How to apply coupons and discount codes on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(75),
    updatedAt: daysAgo(12),
  },
  {
    id: "faq-order-cancellation",
    question: "Can I cancel an order after placing it?",
    answer: html(`<p>You can cancel an order if the seller hasn't shipped yet. Go to Account → My Orders → Cancel Order. Once the seller marks the order as shipped, cancellation is no longer available — you'll need to wait for delivery and then request a return if needed.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 27,
    priority: 7,
    tags: ["cancel", "order", "pre-shipment"],
    relatedFAQs: ["faq-how-to-request-refund"],
    stats: makeStats(2800, 140),
    seo: { slug: "faq-order-cancellation", metaTitle: "Cancel an Order on LetItRip", metaDescription: "How to cancel an order before it ships." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-seller-fees",
    question: "What fees does LetItRip charge sellers?",
    answer: html(`<p>LetItRip charges a platform commission on each sale (percentage varies by category). There are no listing fees or monthly subscription charges. Payout processing fees depend on your payout method (UPI is free, bank transfer has a small fee). Check the Seller Dashboard for current fee schedules.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 28,
    priority: 6,
    tags: ["fees", "seller", "commission"],
    relatedFAQs: ["faq-seller-payout-schedule"],
    stats: makeStats(1600, 80),
    seo: { slug: "faq-seller-fees", metaTitle: "Seller Fees on LetItRip", metaDescription: "Platform commission and fee structure for sellers on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(70),
    updatedAt: daysAgo(15),
  },
  {
    id: "faq-seller-payout-schedule",
    question: "When do sellers get paid?",
    answer: html(`<p>Payouts are released after the buyer confirms delivery (or after 7 days with no dispute). Payout batches are processed weekly. You can view payout status and history in your Seller Dashboard → Payouts. The payout amount reflects the sale price minus platform commission and any refund deductions.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 29,
    priority: 6,
    tags: ["payout", "seller", "payment-schedule"],
    relatedFAQs: ["faq-seller-fees"],
    stats: makeStats(1300, 65),
    seo: { slug: "faq-seller-payout-schedule", metaTitle: "Seller Payout Schedule", metaDescription: "When and how sellers receive payouts on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(65),
    updatedAt: daysAgo(12),
  },
  {
    id: "faq-payment-failed",
    question: "My payment failed but money was deducted — what do I do?",
    answer: html(`<p>If your payment fails but the amount is deducted, it's usually a temporary hold by your bank. The amount is auto-reversed within 24–48 hours. If it doesn't reverse after 48 hours, contact your bank with the transaction ID (available in your Razorpay receipt email) or reach out to LetItRip support.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 30,
    priority: 8,
    tags: ["payment-failed", "bank-hold", "razorpay"],
    relatedFAQs: ["faq-payment-methods"],
    stats: makeStats(3200, 160),
    seo: { slug: "faq-payment-failed", metaTitle: "Payment Failed but Money Deducted", metaDescription: "What to do when payment fails but bank deducts the amount." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(55),
    updatedAt: daysAgo(5),
  },
  {
    id: "faq-gst-invoice",
    question: "Do I get a GST invoice for my purchase?",
    answer: html(`<p>Yes — invoices are auto-generated for every order. Go to Account → My Orders → click the order → Download Invoice. Sellers who are GST-registered include GST details on the invoice. For bulk/business purchases, contact the seller directly to arrange GST billing.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 31,
    priority: 5,
    tags: ["gst", "invoice", "tax"],
    relatedFAQs: [],
    stats: makeStats(900, 45),
    seo: { slug: "faq-gst-invoice", metaTitle: "GST Invoice on LetItRip", metaDescription: "How to get a GST invoice for your LetItRip purchase." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
  },

  // ── PRODUCT INFORMATION (8) ───────────────────────────────────────────────

  {
    id: "faq-how-to-verify-authenticity",
    question: "How can I verify if a collectible is authentic?",
    answer: html(`<p>Look for these trust signals on LetItRip: <strong>Verified Seller</strong> badge (store has passed manual review), <strong>Graded</strong> badge (PSA/BGS/CGC certified with certificate number), <strong>Sealed</strong> badge (factory-sealed product). For ungraded items, check the seller's photo quality and description detail. If in doubt, message the seller before purchasing.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 32,
    priority: 8,
    tags: ["authentication", "verification", "trust"],
    relatedFAQs: ["faq-counterfeit-guarantee", "faq-psa-vs-bgs-vs-cgc"],
    stats: makeStats(3800, 190),
    seo: { slug: "faq-how-to-verify-authenticity", metaTitle: "Verify Collectible Authenticity", metaDescription: "How to verify if a collectible is authentic on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(15),
  },
  {
    id: "faq-psa-vs-bgs-vs-cgc",
    question: "What's the difference between PSA, BGS, and CGC grading?",
    answer: html(`<p><strong>PSA</strong> (Professional Sports Authenticator) uses a 1–10 scale and is the most widely recognized for trading cards. <strong>BGS</strong> (Beckett Grading Services) uses sub-grades for centering, surface, edges, and corners — a BGS 10 "Pristine" or "Black Label" is the highest standard. <strong>CGC</strong> (Certified Guaranty Company) is newer to cards but growing in popularity, also uses sub-grades. All three are trusted; PSA tends to command the highest resale premiums.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 33,
    priority: 7,
    tags: ["grading", "psa", "bgs", "cgc", "trading-cards"],
    relatedFAQs: ["faq-how-to-verify-authenticity"],
    stats: makeStats(4600, 230),
    seo: { slug: "faq-psa-vs-bgs-vs-cgc", metaTitle: "PSA vs BGS vs CGC Grading", metaDescription: "Compare PSA, BGS, and CGC grading services for trading cards." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-how-to-verify-1st-edition",
    question: "How do I know if a Yu-Gi-Oh! card is 1st Edition?",
    answer: html(`<p>1st Edition cards have a gold "1st Edition" stamp below the card artwork on the left side. On older cards (LOB, MRD era), the stamp is more prominent. Unlimited prints lack this stamp. For graded cards, the PSA/BGS/CGC label will indicate "1ST EDITION" in the certification details.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 34,
    priority: 6,
    tags: ["authentication", "1st-edition", "ygo", "grading"],
    relatedFAQs: ["faq-psa-vs-bgs-vs-cgc"],
    stats: makeStats(3800, 190),
    seo: { slug: "faq-how-to-verify-1st-edition", metaTitle: "Identify 1st Edition YGO Cards", metaDescription: "How to verify if your Yu-Gi-Oh! card is a genuine 1st Edition." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(15),
  },
  {
    id: "faq-condition-grading-guide",
    question: "What do condition grades like NM, LP, MP mean?",
    answer: html(`<p>Sellers use standard condition grades for ungraded items: <strong>NM</strong> (Near Mint) — virtually perfect, minimal handling wear. <strong>LP</strong> (Lightly Played) — minor edge wear, small scratches. <strong>MP</strong> (Moderately Played) — visible wear, light creasing. <strong>HP</strong> (Heavily Played) — significant wear, creases, whitening. <strong>Sealed</strong> — factory sealed, never opened. Always check the seller's photos for the actual condition.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 35,
    priority: 7,
    tags: ["condition", "grading", "nm", "lp", "mp"],
    relatedFAQs: ["faq-how-to-verify-authenticity"],
    stats: makeStats(2900, 145),
    seo: { slug: "faq-condition-grading-guide", metaTitle: "Condition Grading Guide", metaDescription: "What NM, LP, MP condition grades mean for collectibles on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(70),
    updatedAt: daysAgo(12),
  },
  {
    id: "faq-beyblade-compatibility",
    question: "Are Beyblade parts compatible across different series?",
    answer: html(`<p><strong>Beyblade X</strong> parts are NOT compatible with Burst or older systems — different launcher and layer design. <strong>Burst</strong> layers, discs, and drivers are cross-compatible within the Burst line (standard, superking, dynamite battle, BU). <strong>Metal Saga</strong> (Metal Fusion/Masters/Fury) parts interchange within that line. Always check the listing's "Compatible System" tag before purchasing.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 36,
    priority: 6,
    tags: ["beyblade", "compatibility", "parts", "spinning-tops"],
    relatedFAQs: ["faq-what-categories-available"],
    stats: makeStats(1600, 80),
    seo: { slug: "faq-beyblade-compatibility", metaTitle: "Beyblade Part Compatibility", metaDescription: "Which Beyblade parts are compatible across series — X, Burst, and Metal Saga." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(8),
  },
  {
    id: "faq-hot-wheels-treasure-hunt",
    question: "How do I identify Hot Wheels Treasure Hunts and Supers?",
    answer: html(`<p><strong>Regular Treasure Hunts</strong> have a small flame logo on the card. <strong>Super Treasure Hunts (STH)</strong> have Spectraflame paint (metallic/candy-colored), Real Riders rubber tires, and a "TH" logo somewhere on the car. STHs are rare (1 in ~15 cases) and command premium prices. Sellers on LetItRip mark STHs with a "Super Treasure Hunt" badge.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 37,
    priority: 6,
    tags: ["hot-wheels", "treasure-hunt", "sth", "diecast"],
    relatedFAQs: ["faq-what-categories-available"],
    stats: makeStats(2100, 105),
    seo: { slug: "faq-hot-wheels-treasure-hunt", metaTitle: "Hot Wheels Treasure Hunt Guide", metaDescription: "How to identify regular and Super Treasure Hunt Hot Wheels." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-funko-pop-exclusives",
    question: "Are Funko Pop exclusives available on LetItRip?",
    answer: html(`<p>Yes — verified sellers list convention exclusives (SDCC, NYCC, Funko Fair), store exclusives (Amazon, Hot Topic, BoxLunch), and chase variants. Look for the "Exclusive" or "Chase" badge on listings. All Funko Pops include the pop number and series in the listing title for easy search.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 38,
    priority: 5,
    tags: ["funko", "pop", "exclusive", "chase", "action-figures"],
    relatedFAQs: ["faq-what-categories-available"],
    stats: makeStats(1300, 65),
    seo: { slug: "faq-funko-pop-exclusives", metaTitle: "Funko Pop Exclusives on LetItRip", metaDescription: "Find convention and store exclusive Funko Pops on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(7),
  },
  {
    id: "faq-gundam-grade-differences",
    question: "What's the difference between HG, MG, RG, and PG Gundam kits?",
    answer: html(`<p><strong>HG</strong> (High Grade, 1/144) — beginner-friendly, ~100 parts. <strong>RG</strong> (Real Grade, 1/144) — high detail at small scale, ~200 parts. <strong>MG</strong> (Master Grade, 1/100) — detailed inner frame, ~400 parts, intermediate. <strong>PG</strong> (Perfect Grade, 1/60) — premium, ~800+ parts, LED-ready. All Bandai kits on LetItRip list the grade, scale, and part count in the product details.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 39,
    priority: 5,
    tags: ["gundam", "model-kits", "bandai", "hg", "mg", "rg", "pg"],
    relatedFAQs: ["faq-what-categories-available"],
    stats: makeStats(1700, 85),
    seo: { slug: "faq-gundam-grade-differences", metaTitle: "Gundam Kit Grades Explained", metaDescription: "HG vs MG vs RG vs PG — understand Gundam model kit grades on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },

  // ── AUCTIONS (5) ──────────────────────────────────────────────────────────

  {
    id: "faq-how-does-bidding-work",
    question: "How does bidding work on LetItRip?",
    answer: html(`<p>Place a bid on any active auction listing. You'll be notified if you're outbid. When the auction ends, the highest bidder wins. Some auctions have a Buy It Now (BIN) price — you can skip bidding and purchase immediately at the BIN price. Auctions auto-extend by 2 minutes if a bid is placed in the final 2 minutes to prevent sniping.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 40,
    priority: 8,
    tags: ["auction", "bidding", "bin", "auto-extend"],
    relatedFAQs: ["faq-auction-ending-rules", "faq-can-i-cancel-bid"],
    stats: makeStats(4200, 210),
    seo: { slug: "faq-how-does-bidding-work", metaTitle: "How Bidding Works", metaDescription: "Learn how to bid on collectibles auctions on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(105),
    updatedAt: daysAgo(8),
  },
  {
    id: "faq-auction-ending-rules",
    question: "What happens when an auction ends?",
    answer: html(`<p>The highest bidder wins. You'll receive a notification and the item is added to your checkout. You have 48 hours to complete payment. If you don't pay within 48 hours, the auction may be offered to the next highest bidder.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 41,
    priority: 7,
    tags: ["auction", "winning", "payment"],
    relatedFAQs: ["faq-how-does-bidding-work"],
    stats: makeStats(3100, 155),
    seo: { slug: "faq-auction-ending-rules", metaTitle: "Auction Ending Rules", metaDescription: "What happens when you win a collectibles auction on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(12),
  },
  {
    id: "faq-can-i-cancel-bid",
    question: "Can I cancel a bid?",
    answer: html(`<p>Bids are binding. Once placed, a bid cannot be cancelled except in exceptional circumstances (e.g., the seller significantly changed the listing description after your bid). Contact support if you believe your case qualifies.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 42,
    priority: 6,
    tags: ["auction", "cancel-bid"],
    relatedFAQs: ["faq-how-does-bidding-work"],
    stats: makeStats(2400, 120),
    seo: { slug: "faq-can-i-cancel-bid", metaTitle: "Can I Cancel a Bid?", metaDescription: "Understanding bid cancellation on LetItRip auctions." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(95),
    updatedAt: daysAgo(20),
  },
  {
    id: "faq-auction-reserve-price",
    question: "What is a reserve price on auctions?",
    answer: html(`<p>Some sellers set a hidden reserve price — the minimum they'll accept. If bidding doesn't reach the reserve, the auction ends without a winner. You'll see "Reserve not met" during the auction. There's no way to see the reserve price, but you can ask the seller via messages if they're willing to share a hint.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 43,
    priority: 5,
    tags: ["auction", "reserve-price"],
    relatedFAQs: ["faq-how-does-bidding-work"],
    stats: makeStats(1200, 60),
    seo: { slug: "faq-auction-reserve-price", metaTitle: "Auction Reserve Price", metaDescription: "What reserve prices mean on LetItRip auctions." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-auction-bid-increment",
    question: "What are the minimum bid increments?",
    answer: html(`<p>Bid increments are automatic and scale with the current price: ₹10 increments up to ₹500, ₹25 up to ₹2,000, ₹50 up to ₹5,000, ₹100 up to ₹20,000, and ₹500 above ₹20,000. You can always bid more than the minimum increment.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 44,
    priority: 5,
    tags: ["auction", "bid-increment", "pricing"],
    relatedFAQs: ["faq-how-does-bidding-work"],
    stats: makeStats(1000, 50),
    seo: { slug: "faq-auction-bid-increment", metaTitle: "Auction Bid Increments", metaDescription: "Minimum bid increment rules on LetItRip auctions." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(8),
  },

  // ── PRE-ORDERS (3) ────────────────────────────────────────────────────────

  {
    id: "faq-pre-orders-how-they-work",
    question: "How do pre-orders work?",
    answer: html(`<p>Pre-orders let you reserve upcoming products with a deposit (typically 20–30% of the retail price). When the product releases and ships, you pay the remaining balance. If the seller cancels the pre-order, you receive a full refund of your deposit. Pre-orders are available for upcoming trading card sets, action figure releases, and model kit drops.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 45,
    priority: 7,
    tags: ["pre-order", "deposit", "reservation"],
    relatedFAQs: ["faq-pre-order-release-delay"],
    stats: makeStats(2200, 110),
    seo: { slug: "faq-pre-orders-how-they-work", metaTitle: "Pre-Orders on LetItRip", metaDescription: "Reserve upcoming collectibles with a deposit on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(82),
    updatedAt: daysAgo(16),
  },
  {
    id: "faq-pre-order-release-delay",
    question: "What happens if a pre-order product is delayed?",
    answer: html(`<p>Manufacturers sometimes delay release dates. The seller will update the expected ship date on the listing and you'll receive a notification. If the delay is more than 60 days past the original date, you can cancel for a full deposit refund. You are never charged the remaining balance until the product actually ships.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 46,
    priority: 6,
    tags: ["pre-order", "delay", "refund"],
    relatedFAQs: ["faq-pre-orders-how-they-work"],
    stats: makeStats(1100, 55),
    seo: { slug: "faq-pre-order-release-delay", metaTitle: "Pre-Order Delay Policy", metaDescription: "What happens when a pre-order is delayed on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(12),
  },
  {
    id: "faq-pre-order-cancel",
    question: "Can I cancel a pre-order?",
    answer: html(`<p>You can cancel a pre-order any time before the seller marks it as shipped. Your deposit is refunded within 3–5 business days. Once the product ships and the remaining balance is charged, standard return policies apply.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 47,
    priority: 5,
    tags: ["pre-order", "cancel", "deposit-refund"],
    relatedFAQs: ["faq-pre-orders-how-they-work"],
    stats: makeStats(800, 40),
    seo: { slug: "faq-pre-order-cancel", metaTitle: "Cancel a Pre-Order", metaDescription: "How to cancel a pre-order and get your deposit back on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(55),
    updatedAt: daysAgo(10),
  },

  // ── ACCOUNT & SECURITY (4) ────────────────────────────────────────────────

  {
    id: "faq-how-to-create-account",
    question: "How do I create a LetItRip account?",
    answer: html(`<p>Sign up with your Google account (one-tap) or email. Google sign-up is recommended — it's faster and more secure. After sign-up, complete your profile with a display name and optional avatar. You can start browsing and buying immediately.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 48,
    priority: 7,
    tags: ["account", "sign-up", "google", "registration"],
    relatedFAQs: ["faq-how-to-sell-on-letitrip"],
    stats: makeStats(2600, 130),
    seo: { slug: "faq-how-to-create-account", metaTitle: "Create a LetItRip Account", metaDescription: "How to sign up for a LetItRip account with Google or email." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(100),
    updatedAt: daysAgo(15),
  },
  {
    id: "faq-account-security-tips",
    question: "How do I keep my account secure?",
    answer: html(`<p>Use Google sign-in for the strongest security. Never share your login credentials. If you signed up with email, use a strong unique password. LetItRip will never ask for your password via email or chat. If you notice suspicious activity, go to Account → Sessions to see active devices and revoke any you don't recognize.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 49,
    priority: 8,
    tags: ["security", "password", "sessions", "account"],
    relatedFAQs: ["faq-how-to-create-account"],
    stats: makeStats(1500, 75),
    seo: { slug: "faq-account-security-tips", metaTitle: "Account Security on LetItRip", metaDescription: "Tips to keep your LetItRip account secure." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-delete-my-account",
    question: "Can I delete my LetItRip account?",
    answer: html(`<p>Yes — go to Account → Settings → Delete Account. This permanently removes your profile, addresses, and browsing history. Open orders will still be fulfilled. If you're a seller with active listings, you must close your store first. Account deletion is irreversible.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 50,
    priority: 5,
    tags: ["delete-account", "privacy", "data"],
    relatedFAQs: ["faq-account-security-tips"],
    stats: makeStats(600, 30),
    seo: { slug: "faq-delete-my-account", metaTitle: "Delete Your LetItRip Account", metaDescription: "How to permanently delete your LetItRip account." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(20),
  },
  {
    id: "faq-notification-preferences",
    question: "How do I manage my notifications?",
    answer: html(`<p>Go to Account → Settings → Notification Preferences. You can toggle each notification type (order updates, auction alerts, price drops, community events) per channel — in-app, email, and WhatsApp. High-priority notifications (order shipped, auction won) are always sent in-app and cannot be fully disabled.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 51,
    priority: 5,
    tags: ["notifications", "settings", "preferences", "whatsapp", "email"],
    relatedFAQs: [],
    stats: makeStats(700, 35),
    seo: { slug: "faq-notification-preferences", metaTitle: "Notification Preferences", metaDescription: "Manage your notification preferences on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },

  // ── SCAM AWARENESS (4) ────────────────────────────────────────────────────

  {
    id: "faq-spot-a-scam-listing",
    question: "How do I spot a scam listing?",
    answer: html(`<p>Red flags: price too good to be true, stock photos instead of actual product photos, brand-new account with no reviews, pressure to pay outside LetItRip ("DM me on WhatsApp for discount"), and vague descriptions. LetItRip's verified seller program eliminates most scams, but always check the seller's reviews and store age before high-value purchases.</p>`),
    category: "scam_awareness",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 52,
    priority: 8,
    tags: ["scam", "fraud", "red-flags", "safety"],
    relatedFAQs: ["faq-report-a-scammer", "faq-counterfeit-guarantee"],
    stats: makeStats(2800, 140),
    seo: { slug: "faq-spot-a-scam-listing", metaTitle: "Spot a Scam Listing", metaDescription: "How to identify scam listings on collectibles marketplaces." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(70),
    updatedAt: daysAgo(8),
  },
  {
    id: "faq-report-a-scammer",
    question: "How do I report a scammer?",
    answer: html(`<p>Click the "Report" button on any listing or store page. Select the issue type (counterfeit, misleading description, off-platform payment request, etc.) and provide evidence. Our moderation team reviews reports within 24 hours. Confirmed scammers are permanently banned and added to our public scam registry.</p>`),
    category: "scam_awareness",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 53,
    priority: 7,
    tags: ["report", "scammer", "moderation"],
    relatedFAQs: ["faq-spot-a-scam-listing"],
    stats: makeStats(1800, 90),
    seo: { slug: "faq-report-a-scammer", metaTitle: "Report a Scammer", metaDescription: "How to report a scammer on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(65),
    updatedAt: daysAgo(10),
  },
  {
    id: "faq-off-platform-payment-warning",
    question: "Should I ever pay outside of LetItRip?",
    answer: html(`<p><strong>Never.</strong> Any seller asking you to pay via UPI, bank transfer, or any method outside of LetItRip checkout is violating our terms. Off-platform payments have zero buyer protection — no escrow, no dispute mediation, no refund guarantee. Report the seller immediately.</p>`),
    category: "scam_awareness",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: true,
    order: 54,
    priority: 10,
    tags: ["off-platform", "payment", "safety", "warning"],
    relatedFAQs: ["faq-spot-a-scam-listing", "faq-what-is-escrow"],
    stats: makeStats(3200, 160),
    seo: { slug: "faq-off-platform-payment-warning", metaTitle: "Never Pay Off-Platform", metaDescription: "Why you should never pay outside of LetItRip's secure checkout." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: "faq-community-events",
    question: "What community events does LetItRip run?",
    answer: html(`<p>LetItRip runs regular community events: <strong>Polls</strong> (vote on upcoming features), <strong>Sales</strong> (platform-wide discount events), <strong>Raffles</strong> (win rare collectibles), <strong>Spin Wheels</strong> (instant coupon prizes), and <strong>Surveys</strong> (share feedback, earn rewards). Check the Events page for current and upcoming events.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 55,
    priority: 6,
    tags: ["events", "community", "raffle", "poll", "spin-wheel"],
    relatedFAQs: ["faq-prize-draws-how-they-work"],
    stats: makeStats(1400, 70),
    seo: { slug: "faq-community-events", metaTitle: "Community Events on LetItRip", metaDescription: "Polls, raffles, spin wheels, and sales events on LetItRip." },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(6),
  },
];
