/**
 * FAQ Seed Data — LetItRip Collectibles Platform
 * 53 FAQs across 7 categories. faq- prefix, id === slug.
 *
 * Homepage FAQs (showOnHomepage: true): 8 — shown expanded by default for SEO.
 * Footer FAQs (showInFooter: true): 5 — linked from the site footer.
 *
 * Platform tone:
 *  - Shipping timelines and return policies are set by individual stores.
 *    Buyers must check each store's About page for their specific rules.
 *  - LetItRip is a marketplace platform. We verify sellers and mediate
 *    disputes, but we are not the seller and cannot guarantee every
 *    transaction. Buying collectibles carries inherent risk.
 */

import type { FAQDocument } from "../features/faq/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const html = (text: string) => ({ text, format: "html" as const });
const makeStats = (views = 0, helpful = 0) => ({ views, helpful, notHelpful: 0 });

export const faqSeedData: Partial<FAQDocument>[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // GENERAL (10 FAQs)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "faq-what-is-letitrip",
    question: "What is LetItRip?",
    answer: html(`<p><strong>LetItRip</strong> is India's dedicated collectibles marketplace where verified sellers list Pokémon TCG cards, Hot Wheels diecast, Beyblade X tops, anime figures, Gunpla model kits, and rare vintage toys. Every seller on LetItRip is manually reviewed before they can list — so you're always browsing verified inventory.</p><p>LetItRip is a <strong>platform</strong> that connects buyers with independent sellers. We handle payments, escrow, and dispute mediation — but we are not the seller. Each store on LetItRip is an independent business with its own shipping, return, and authenticity policies. Always read a store's About page before you buy.</p>`),
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: true,
    order: 1,
    priority: 10,
    tags: ["about", "letitrip", "platform", "marketplace"],
    relatedFAQs: ["faq-is-letitrip-safe-to-use", "faq-how-does-letitrip-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(8200, 410),
    seo: {
      slug: "faq-what-is-letitrip",
      metaTitle: "What is LetItRip? India's Collectibles Marketplace",
      metaDescription: "LetItRip is India's verified collectibles marketplace for Pokémon TCG, Hot Wheels, Beyblade X, anime figures, and more.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-is-letitrip-safe-to-use",
    question: "Is LetItRip safe to buy and sell on?",
    answer: html(`<p>LetItRip takes safety seriously, but like any marketplace, buying and selling collectibles carries <strong>inherent risk</strong> — and we want you to be informed before you transact.</p><p><strong>What LetItRip does to protect you:</strong></p><ul><li><strong>Seller verification</strong> — every store is manually reviewed. Sellers must submit ID and business details before going live.</li><li><strong>Escrow payments</strong> — your money is held by Razorpay and only released to the seller after you confirm delivery or after 5 days of confirmed delivery without a dispute.</li><li><strong>Dispute mediation</strong> — if something goes wrong, raise a dispute within 5 days of delivery and our team will review and mediate.</li><li><strong>Counterfeit policy</strong> — confirmed counterfeit items result in a full refund and seller suspension.</li></ul><p><strong>What LetItRip cannot guarantee:</strong></p><ul><li>We are a <strong>platform</strong>, not the seller. Each store is an independent business. We do not inspect or hold physical inventory.</li><li>Shipping timelines and return windows are set by each store — they vary and are not guaranteed by LetItRip.</li><li>Graded slabs (PSA, BGS, CGC) are verified by third-party grading companies — we do not re-grade on your behalf.</li></ul><p>Our advice: read each store's About page before buying, check reviews, and use the escrow window to inspect your item before confirming delivery.</p>`),
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: true,
    order: 2,
    priority: 10,
    tags: ["safety", "trust", "risk", "platform", "escrow"],
    relatedFAQs: ["faq-what-is-letitrip", "faq-does-letitrip-guarantee-returns", "faq-how-does-escrow-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(6100, 290),
    seo: {
      slug: "faq-is-letitrip-safe-to-use",
      metaTitle: "Is LetItRip Safe? Buyer & Seller Protection Explained",
      metaDescription: "LetItRip verifies sellers, holds payments in escrow, and mediates disputes — but we're a platform, not the seller. Learn what's covered.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(4),
  },

  {
    id: "faq-how-does-letitrip-work",
    question: "How does LetItRip work?",
    answer: html(`<p>LetItRip works like a curated collectibles bazaar — sellers set up stores, list their items, and buyers browse and purchase with escrow-backed payments.</p><ol><li><strong>Browse</strong> — search by category (Pokémon, Hot Wheels, Beyblade X, etc.), filter by condition, price, and seller rating.</li><li><strong>Buy securely</strong> — checkout with UPI, card, or COD. Payment goes into escrow — not to the seller yet.</li><li><strong>Seller dispatches</strong> — the seller ships within their stated timeline (check their About page).</li><li><strong>Confirm receipt</strong> — once your item arrives, inspect it, then click "Confirm Delivery". Payment is released to the seller.</li><li><strong>Dispute window</strong> — if anything is wrong, raise a dispute within 5 days of delivery. Do not confirm delivery if you haven't inspected the item.</li></ol><p>For auctions and pre-orders, the flow has extra steps — see the auction and pre-order FAQ sections for details.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 8,
    tags: ["how-to", "buying", "process"],
    relatedFAQs: ["faq-what-is-letitrip", "faq-is-letitrip-safe-to-use"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(4200, 195),
    seo: { slug: "faq-how-does-letitrip-work" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-what-collectibles-can-i-buy",
    question: "What types of collectibles can I buy on LetItRip?",
    answer: html(`<p>LetItRip covers six major collectibles categories:</p><ul><li><strong>Trading Cards</strong> — Pokémon TCG (sealed boxes, ETBs, raw singles, graded slabs), Yu-Gi-Oh!, Dragon Ball Super Card Game, One Piece</li><li><strong>Diecast Vehicles</strong> — Hot Wheels (mainline, Car Culture, premium, RLC), Tomica, Matchbox, Majorette</li><li><strong>Spinning Tops</strong> — Beyblade X (official Takara Tomy imports), Beyblade Burst, Metal Fight</li><li><strong>Action Figures</strong> — Nendoroids, figma, S.H.Figuarts, Funko Pop, NECA, McFarlane</li><li><strong>Model Kits</strong> — Gunpla (HG, MG, RG, PG, SD), Kotobukiya, Hasegawa</li><li><strong>Vintage & Rare</strong> — WOTC-era Pokémon, original Base Set, vintage Hot Wheels Redlines, vintage action figures</li></ul><p>New categories are added based on community demand. If you collect something not listed here, email us at <strong>support@letitrip.in</strong> — we're always expanding.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 7,
    tags: ["categories", "pokemon", "hot-wheels", "beyblade", "gunpla", "anime"],
    relatedFAQs: ["faq-what-is-letitrip"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3100, 142),
    seo: { slug: "faq-what-collectibles-can-i-buy" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(7),
  },

  {
    id: "faq-how-does-bidding-work",
    question: "How does bidding work on LetItRip auctions?",
    answer: html(`<p>LetItRip auctions use a <strong>timed open-bid system</strong>:</p><ol><li>Each auction has a starting bid, optional reserve price, and a closing time.</li><li>Click "Place Bid" and enter an amount at least ₹50 (or the stated minimum increment) above the current bid.</li><li>If you are outbid, you receive an instant notification via app, email, and WhatsApp.</li><li>The highest bidder at closing time wins.</li><li>An <strong>auto-extend rule</strong> applies: if a bid is placed in the final 5 minutes, the auction extends by 5 more minutes. This prevents last-second sniping.</li></ol><p><strong>Reserve price:</strong> if set, the auction only closes as a confirmed sale if the reserve is met. If not, the seller may contact the highest bidder to negotiate directly.</p><p><strong>Important:</strong> All bids are binding. You cannot retract a bid once placed — see the bid retraction FAQ for the only exception.</p>`),
    category: "general",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: true,
    order: 5,
    priority: 10,
    tags: ["auction", "bidding", "how-to"],
    relatedFAQs: ["faq-what-happens-when-i-win-an-auction", "faq-can-i-retract-a-bid"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(6200, 310),
    seo: {
      slug: "faq-how-does-bidding-work",
      metaTitle: "How Do Auctions Work on LetItRip?",
      metaDescription: "LetItRip uses a timed open-bid system with auto-extend. Learn how to bid on rare collectibles.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(3),
  },

  {
    id: "faq-what-happens-when-i-win-an-auction",
    question: "What happens when I win an auction?",
    answer: html(`<p>When you win an auction you receive an instant notification and email with the final amount. Next steps:</p><ol><li>You have <strong>24 hours</strong> to complete payment. The order appears in My Account → Orders with status "Pending Payment".</li><li>After payment, the seller dispatches within their stated timeline (check their store About page — each seller sets their own dispatch window).</li><li>If you do not pay within 24 hours, the win may be offered to the next-highest bidder and your account receives a non-payment strike. Three strikes result in a 30-day auction ban.</li></ol><p><strong>High-value auctions</strong> (above ₹50,000) require a refundable ₹5,000 deposit at time of bidding. This is deducted from the final amount at checkout.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 8,
    tags: ["auction", "winning", "payment"],
    relatedFAQs: ["faq-how-does-bidding-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3800, 172),
    seo: { slug: "faq-what-happens-when-i-win-an-auction" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(4),
  },

  {
    id: "faq-can-i-retract-a-bid",
    question: "Can I retract a bid once placed?",
    answer: html(`<p><strong>Bid retraction is not allowed</strong> on LetItRip. All bids are binding commitments. This protects sellers from price manipulation.</p><p><strong>Exception:</strong> if a seller materially edits the item description or images after you have already bid (for example, adding undisclosed damage), contact LetItRip support with the edit timestamp and evidence. We can void your bid within 1 hour of the edit. Sellers who make material post-bid edits face penalties.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 6,
    tags: ["auction", "bid", "retract"],
    relatedFAQs: ["faq-how-does-bidding-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1900, 82),
    seo: { slug: "faq-can-i-retract-a-bid" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-what-is-a-reserve-price",
    question: "What is a reserve price in an auction?",
    answer: html(`<p>A <strong>reserve price</strong> is the minimum amount a seller is willing to accept. It is kept secret from bidders — the listing shows "Reserve not met" or "Reserve met" as bids come in.</p><p>If the final bid does not meet the reserve, the seller is not obligated to sell. They may contact the highest bidder through LetItRip messaging to negotiate a private sale. Sellers use reserve prices mainly on high-value items such as PSA 9/10 slabs or rare vintage collectibles.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 5,
    tags: ["auction", "reserve", "price"],
    relatedFAQs: ["faq-how-does-bidding-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1400, 61),
    seo: { slug: "faq-what-is-a-reserve-price" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(7),
  },

  {
    id: "faq-how-do-i-report-a-fake-item",
    question: "How do I report a fake or counterfeit item?",
    answer: html(`<p>If you receive an item you believe is counterfeit, act immediately:</p><ol><li><strong>Do not confirm delivery</strong> — this keeps your escrow window open.</li><li>Go to My Account → Orders → "Report Issue" and select "Counterfeit / Not as described".</li><li>Upload clear photographs of the item, packaging, and any authentication markings alongside genuine reference images if possible.</li><li>LetItRip will place the payment on hold and open an investigation within 24 hours.</li></ol><p>If confirmed counterfeit, you receive a <strong>full refund</strong> and the seller's store is suspended pending review. We have a zero-tolerance policy for fakes.</p><p>You can also report a suspicious listing before purchasing — use the "Report Listing" flag on any product page. Our team reviews flagged listings within 12 hours.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 9,
    priority: 8,
    tags: ["fake", "counterfeit", "report", "authenticity"],
    relatedFAQs: ["faq-is-letitrip-safe-to-use", "faq-how-to-spot-fake-pokemon-cards-authentication"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2800, 198),
    seo: { slug: "faq-how-do-i-report-a-fake-item" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(87),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-do-i-contact-support",
    question: "How do I contact LetItRip support?",
    answer: html(`<p>You can reach LetItRip support through the following channels:</p><ul><li><strong>Email</strong>: support@letitrip.in — we respond within 24 hours (48 hours on weekends)</li><li><strong>Order disputes</strong>: My Account → Orders → "Report Issue" — fastest route for transaction problems as it attaches order context automatically</li><li><strong>WhatsApp community</strong>: join our collectors group for community help and informal guidance</li></ul><p>For <strong>urgent issues</strong> (payment held, suspected fraud, counterfeit item), use the in-order dispute form — it escalates to our priority queue and is reviewed within 4 hours during business hours (Mon–Sat, 10am–7pm IST).</p><p>We do not offer phone support at this time. All formal resolutions are handled in writing so there is a clear record.</p>`),
    category: "general",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 10,
    priority: 7,
    tags: ["support", "contact", "help"],
    relatedFAQs: ["faq-how-to-raise-a-dispute"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3400, 156),
    seo: { slug: "faq-how-do-i-contact-support" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(86),
    updatedAt: daysAgo(4),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SHIPPING & DELIVERY (7 FAQs)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "faq-how-long-does-shipping-take",
    question: "How long does shipping take?",
    answer: html(`<p><strong>Important: shipping timelines are set by each individual store on LetItRip, not by the platform.</strong> Before buying, visit the store's About page (click the store name on any listing) to read their specific dispatch and delivery commitments.</p><p>As a general guide, most verified stores on LetItRip ship as follows:</p><ul><li><strong>Metro cities</strong> (Mumbai, Delhi, Bengaluru, Hyderabad, Pune, Chennai): 2–4 business days</li><li><strong>Tier-2 cities and standard pin codes</strong>: 3–7 business days</li><li><strong>Remote pin codes</strong>: 7–14 business days</li></ul><p>These are typical ranges only — your seller's stated policy takes precedence. Sellers must dispatch within their stated window after payment is confirmed; you receive a tracking link via email and WhatsApp once dispatched. If your order hasn't moved within the seller's stated dispatch window, raise an issue through My Account → Orders.</p>`),
    category: "shipping_delivery",
    showOnHomepage: true,
    showInFooter: true,
    isPinned: true,
    order: 1,
    priority: 10,
    tags: ["shipping", "delivery", "timeline"],
    relatedFAQs: ["faq-how-do-i-find-store-shipping-policy", "faq-how-to-track-my-order"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3200, 148),
    seo: {
      slug: "faq-how-long-does-shipping-take",
      metaTitle: "How Long Does Shipping Take on LetItRip?",
      metaDescription: "Shipping timelines on LetItRip are set by each store. Check the store's About page for exact timelines.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-do-i-find-store-shipping-policy",
    question: "Where can I find a store's shipping policy?",
    answer: html(`<p>Every store on LetItRip sets its own shipping rules — dispatch windows, carriers used, packaging standards, and whether they offer express options. To find a specific store's policy:</p><ol><li>Open any listing from that store and click the <strong>store name</strong> near the seller details.</li><li>On the store page, click the <strong>About</strong> tab.</li><li>Scroll to the Shipping & Dispatch section.</li></ol><p>Alternatively, the store's policy is shown on the checkout page under "Shipping" before you confirm payment.</p><p><strong>LetItRip strongly recommends reading a store's shipping policy before purchasing</strong>, especially for high-value items or time-sensitive orders (e.g., gifts, tournament deadlines). Stores are independent businesses and their policies vary.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 9,
    tags: ["shipping", "store-policy", "about-page"],
    relatedFAQs: ["faq-how-long-does-shipping-take", "faq-does-letitrip-guarantee-returns"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1800, 96),
    seo: { slug: "faq-how-do-i-find-store-shipping-policy" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(4),
  },

  {
    id: "faq-do-you-offer-free-shipping",
    question: "Do you offer free shipping?",
    answer: html(`<p>Free shipping availability depends on the <strong>individual store</strong> — LetItRip does not set a platform-wide free shipping threshold. Each seller decides their own shipping charges and free-shipping conditions.</p><p>Many stores on LetItRip offer free standard shipping on orders above a certain value (commonly ₹499–₹999). Look for the <strong>"Free Shipping"</strong> badge on product listings, or check the store's About page for their shipping rates.</p><p>At checkout, shipping costs are shown before you confirm payment so there are no surprises.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 7,
    tags: ["shipping", "free-shipping"],
    relatedFAQs: ["faq-how-long-does-shipping-take", "faq-how-do-i-find-store-shipping-policy"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2100, 94),
    seo: { slug: "faq-do-you-offer-free-shipping" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(8),
  },

  {
    id: "faq-how-to-track-my-order",
    question: "How do I track my order?",
    answer: html(`<p>Once your order is dispatched you receive a <strong>tracking link</strong> via email and WhatsApp. You can also track directly from your account: go to My Account → Orders and click <strong>"Track"</strong> next to any shipped order.</p><p>LetItRip supports tracking from Shiprocket, India Post, Delhivery, Ekart, and DTDC. If your tracking link does not update within 24 hours of the dispatch notification, message the seller through the order chat — sellers are required to respond within 12 hours. If they do not, raise an issue through My Account → Orders.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 7,
    tags: ["tracking", "order", "shipment"],
    relatedFAQs: ["faq-how-long-does-shipping-take"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1750, 78),
    seo: { slug: "faq-how-to-track-my-order" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },

  {
    id: "faq-do-you-ship-internationally",
    question: "Do you ship internationally?",
    answer: html(`<p>LetItRip currently serves delivery addresses within <strong>India only</strong>. International shipping is on our roadmap.</p><p>If you are an NRI wanting to send a gift to an Indian address, that works fine — enter the Indian delivery address at checkout. For international inquiries or high-value cross-border auction arrangements, email <strong>support@letitrip.in</strong> — we handle these on a case-by-case basis.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 5,
    tags: ["international", "shipping"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(980, 41),
    seo: { slug: "faq-do-you-ship-internationally" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(15),
  },

  {
    id: "faq-what-happens-if-item-damaged-in-transit",
    question: "What happens if my item is damaged in transit?",
    answer: html(`<p>If your item arrives damaged, <strong>photograph everything before unwrapping further</strong> — the outer box, inner packaging, and the damage on the item itself. Then:</p><ol><li>Go to My Account → Orders → <strong>"Report Issue"</strong> within 48 hours of delivery.</li><li>Select "Item damaged in transit" and upload your photographs.</li><li>Do <strong>not</strong> confirm delivery until the dispute is resolved — confirming delivery releases payment to the seller.</li></ol><p>LetItRip will mediate between you and the seller. Most verified sellers carry basic transit insurance; items valued above ₹5,000 are automatically insured at declared value through our shipping partners.</p><p><strong>Note:</strong> packaging standards are set by each seller — LetItRip does not pack or handle physical items. Sellers who repeatedly dispatch inadequately packaged items lose their verified status.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 6,
    tags: ["damaged", "transit", "insurance"],
    relatedFAQs: ["faq-what-is-the-return-policy", "faq-how-to-raise-a-dispute"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1340, 72),
    seo: { slug: "faq-what-happens-if-item-damaged-in-transit" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(8),
  },

  {
    id: "faq-can-i-change-delivery-address-after-order",
    question: "Can I change my delivery address after placing an order?",
    answer: html(`<p>Address changes after checkout depend on the order status:</p><ul><li><strong>Before dispatch ("Confirmed" or "Processing")</strong>: message the seller directly through the order chat and request the change. Most sellers will accommodate this if they haven't packed yet.</li><li><strong>After dispatch ("Shipped")</strong>: the parcel is already in the carrier's network. You will need to contact the carrier (using the tracking number) to request an address redirect — this is carrier-dependent and not guaranteed.</li></ul><p>LetItRip cannot modify a shipping label once created. Always double-check your delivery address at checkout.</p>`),
    category: "shipping_delivery",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 5,
    tags: ["address", "delivery", "change"],
    relatedFAQs: ["faq-can-i-cancel-my-order"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(890, 38),
    seo: { slug: "faq-can-i-change-delivery-address-after-order" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(82),
    updatedAt: daysAgo(9),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // RETURNS & REFUNDS (6 FAQs)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "faq-what-is-the-return-policy",
    question: "What is the return policy on LetItRip?",
    answer: html(`<p><strong>Return policies on LetItRip are set by individual stores — LetItRip does not impose a platform-wide return window.</strong> Before purchasing, always visit the store's About page to read their specific return rules. Return policies vary significantly between sellers and product types.</p><p>Common patterns among verified stores:</p><ul><li><strong>Sealed products</strong> (booster boxes, ETBs, sealed figures): 7-day return if factory seal is intact and item is in original condition.</li><li><strong>Graded slabs</strong>: 3-day return if the slab arrived cracked or the case is damaged (not for grading disagreements).</li><li><strong>Singles and loose items</strong>: 3-day return if the item is materially different from its description or photographs.</li><li><strong>Opened product</strong>: No returns in most cases — contents cannot be re-verified once opened.</li></ul><p>To initiate a return: My Account → Orders → <strong>"Return Item"</strong>. The seller must respond within 3 business days. LetItRip holds payment in escrow and mediates if the seller is unresponsive or disputes the return. Note that LetItRip's ability to force a refund is limited if the item is within the seller's stated non-returnable policy — we strongly encourage checking before you buy.</p>`),
    category: "returns_refunds",
    showOnHomepage: true,
    showInFooter: true,
    isPinned: true,
    order: 1,
    priority: 9,
    tags: ["returns", "refunds", "policy"],
    relatedFAQs: ["faq-does-letitrip-guarantee-returns", "faq-how-long-does-refund-take", "faq-what-if-seller-refuses-return"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(4100, 204),
    seo: {
      slug: "faq-what-is-the-return-policy",
      metaTitle: "Return Policy on LetItRip — What Buyers Should Know",
      metaDescription: "Return policies are set by each store on LetItRip, not the platform. Read the store's About page before buying.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(4),
  },

  {
    id: "faq-does-letitrip-guarantee-returns",
    question: "Does LetItRip guarantee refunds or returns?",
    answer: html(`<p><strong>LetItRip is a marketplace platform — we are not the seller and cannot guarantee a refund in every situation.</strong> Here is an honest breakdown of what we can and cannot do:</p><p><strong>What LetItRip will do:</strong></p><ul><li>Hold your payment in escrow and only release it after you confirm delivery or after 5 days of confirmed delivery without a dispute.</li><li>Mediate disputes between you and the seller — our team reviews evidence and makes a recommendation.</li><li>Issue a full refund if an item is confirmed counterfeit, or if the seller does not respond within the required window.</li><li>Apply platform penalties (including suspension) to sellers who repeatedly fail buyers.</li></ul><p><strong>What LetItRip cannot guarantee:</strong></p><ul><li>A refund if the item matches the seller's listing description but you changed your mind (buyer's remorse).</li><li>A return if the seller's stated policy does not cover your situation and there is no material listing error.</li><li>Recovery of funds after you have confirmed delivery — confirming delivery releases escrow and closes the dispute window.</li></ul><p>Our best advice: read the store's return policy before buying, inspect every item before confirming delivery, and raise disputes promptly (within 5 days of delivery).</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 9,
    tags: ["returns", "guarantee", "platform", "risk", "escrow"],
    relatedFAQs: ["faq-is-letitrip-safe-to-use", "faq-what-is-the-return-policy", "faq-how-to-raise-a-dispute"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2900, 164),
    seo: { slug: "faq-does-letitrip-guarantee-returns" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(3),
  },

  {
    id: "faq-what-if-seller-refuses-return",
    question: "What if the seller refuses my return request?",
    answer: html(`<p>If a seller declines your return and you believe the refusal is unjustified, escalate to LetItRip:</p><ol><li>Go to My Account → Orders → <strong>"Escalate to LetItRip"</strong> (appears after seller declines).</li><li>Provide your evidence — photographs, the original listing description, and chat history with the seller.</li><li>LetItRip's team reviews within 48 hours and issues a binding decision.</li></ol><p><strong>Outcomes LetItRip can enforce:</strong></p><ul><li>Full or partial refund if the item does not match its description or is counterfeit.</li><li>Return at seller's cost if we determine the seller is at fault.</li></ul><p><strong>Outcomes outside LetItRip's control:</strong></p><ul><li>If the item accurately matches the listing and the seller's stated return policy does not cover your situation, we cannot override the seller's policy. This is why reading store policies before buying is so important.</li></ul><p>LetItRip will always try to find a fair resolution, but we are a platform — not an insurer.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 8,
    tags: ["returns", "dispute", "seller-refusal"],
    relatedFAQs: ["faq-does-letitrip-guarantee-returns", "faq-how-to-raise-a-dispute"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2100, 118),
    seo: { slug: "faq-what-if-seller-refuses-return" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(86),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-long-does-refund-take",
    question: "How long does a refund take?",
    answer: html(`<p>Once a return is approved and the item (where applicable) is received back by the seller, refunds are processed within:</p><ul><li><strong>UPI and bank transfer</strong>: 2–3 business days</li><li><strong>Razorpay (card/net banking/wallet)</strong>: 5–7 business days (subject to your bank's processing time)</li><li><strong>COD orders</strong>: refunded as LetItRip wallet credit, or by bank transfer (takes 3–5 days and requires bank details verification)</li></ul><p>If a refund is not received within 10 business days of approval, contact <strong>support@letitrip.in</strong> with your order ID — we escalate within 24 hours.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 7,
    tags: ["refund", "timeline", "payment"],
    relatedFAQs: ["faq-what-is-the-return-policy"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2800, 132),
    seo: { slug: "faq-how-long-does-refund-take" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(8),
  },

  {
    id: "faq-can-i-cancel-my-order",
    question: "Can I cancel my order?",
    answer: html(`<p>You can cancel an order <strong>before the seller dispatches it</strong>. Once dispatched, cancellation converts to a return request (subject to the seller's return policy).</p><p>To cancel: My Account → Orders → <strong>"Cancel Order"</strong>. A full refund is issued immediately if cancelled pre-dispatch. If the seller has already packed (status "Processing"), they may charge a restocking fee at their discretion — this is shown before you confirm the cancellation.</p><p><strong>Auction wins and pre-order deposits are non-refundable</strong> once the auction has closed or the pre-order window has ended. These are binding commitments — see the relevant FAQ sections for details.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["cancel", "order"],
    relatedFAQs: ["faq-how-long-does-refund-take"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3200, 148),
    seo: { slug: "faq-can-i-cancel-my-order" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-to-raise-a-dispute",
    question: "How do I raise a dispute on LetItRip?",
    answer: html(`<p>The dispute window is open for <strong>5 days after confirmed delivery</strong>. Do not confirm delivery until you have inspected the item — confirming delivery closes the dispute window and releases payment to the seller.</p><p>To raise a dispute:</p><ol><li>Go to My Account → Orders → find the relevant order.</li><li>Click <strong>"Report Issue"</strong>.</li><li>Select the issue type (Not as described / Counterfeit / Damaged / Not received).</li><li>Upload supporting evidence (photos, screenshots of the original listing).</li><li>Submit — the seller is notified and has 48 hours to respond.</li></ol><p>If the seller does not respond or the dispute is not resolved within 5 business days, click "Escalate to LetItRip" for platform review. We issue a binding decision within 48 hours of escalation.</p>`),
    category: "returns_refunds",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 8,
    tags: ["dispute", "report", "issue"],
    relatedFAQs: ["faq-does-letitrip-guarantee-returns", "faq-what-if-seller-refuses-return"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2400, 126),
    seo: { slug: "faq-how-to-raise-a-dispute" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(4),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ORDERS & PAYMENT (8 FAQs)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "faq-what-payment-methods-are-accepted",
    question: "What payment methods does LetItRip accept?",
    answer: html(`<p>LetItRip accepts all major Indian payment methods via Razorpay:</p><ul><li><strong>UPI</strong> — Google Pay, PhonePe, Paytm, BHIM, any UPI-enabled app</li><li><strong>Debit/Credit Cards</strong> — Visa, Mastercard, RuPay, Amex</li><li><strong>Net Banking</strong> — all major Indian banks</li><li><strong>EMI</strong> — 0% on Bajaj Finserv and select bank cards for orders above ₹3,000</li><li><strong>Cash on Delivery (COD)</strong> — for orders up to ₹10,000 (requires a 20% online deposit at checkout)</li></ul><p>All payments are processed via Razorpay (PCI-DSS Level 1 compliant). LetItRip never stores your card details.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: true,
    order: 1,
    priority: 10,
    tags: ["payment", "upi", "card", "cod"],
    relatedFAQs: ["faq-is-it-safe-to-pay-on-letitrip", "faq-is-cod-available"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(5100, 248),
    seo: { slug: "faq-what-payment-methods-are-accepted" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-does-escrow-work",
    question: "How does escrow payment work on LetItRip?",
    answer: html(`<p>Escrow is the core of LetItRip's buyer protection. Here is exactly how it works:</p><ol><li><strong>You pay at checkout</strong> — funds go to Razorpay's secure escrow. The seller does not receive them yet.</li><li><strong>Seller dispatches</strong> — once you have paid, the seller ships within their stated window.</li><li><strong>You inspect and confirm</strong> — when the item arrives, inspect it carefully. If everything is correct, click "Confirm Delivery" in My Account → Orders. This releases the payment to the seller.</li><li><strong>Auto-release</strong> — if you do not take action within 5 days of the courier marking the shipment as delivered, the payment is automatically released to the seller.</li></ol><p><strong>Critical:</strong> Do not click "Confirm Delivery" unless you are satisfied. Once confirmed, the escrow window closes and LetItRip's ability to hold funds is limited. For disputes, act within 5 days of delivery.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 9,
    tags: ["escrow", "payment", "protection"],
    relatedFAQs: ["faq-is-letitrip-safe-to-use", "faq-how-to-raise-a-dispute"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3600, 192),
    seo: { slug: "faq-how-does-escrow-work" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(4),
  },

  {
    id: "faq-is-it-safe-to-pay-on-letitrip",
    question: "Is it safe to pay on LetItRip?",
    answer: html(`<p>Yes — LetItRip uses an <strong>escrow model</strong> via Razorpay (PCI-DSS Level 1). Your payment is held securely and only released to the seller after you confirm delivery or after 5 days of confirmed delivery without a dispute.</p><p>LetItRip is registered under the Indian IT Act and complies with Consumer Protection (E-Commerce) Rules 2020. Our platform fee (shown transparently at checkout) is the only charge — no hidden fees.</p><p>That said, <strong>your vigilance matters too</strong>: inspect every item before confirming delivery, raise disputes within the 5-day window, and never pay outside the LetItRip platform (e.g., UPI to a seller's personal number). LetItRip cannot protect payments made outside our checkout.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 8,
    tags: ["payment", "security", "escrow", "safe"],
    relatedFAQs: ["faq-how-does-escrow-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2400, 108),
    seo: { slug: "faq-is-it-safe-to-pay-on-letitrip" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-what-are-letitrip-platform-fees",
    question: "What are LetItRip's fees for buyers and sellers?",
    answer: html(`<p><strong>For buyers:</strong> LetItRip charges no additional fee to buyers. The price you see is the price you pay (plus any shipping set by the seller). Payment processing fees are absorbed by the platform.</p><p><strong>For sellers:</strong> LetItRip charges a commission on successful sales:</p><ul><li><strong>Standard listings</strong>: 5% platform fee + 2.36% Razorpay processing (total ~7.36%)</li><li><strong>Auction listings</strong>: 5% platform fee + 2.36% Razorpay processing on the final hammer price</li><li><strong>Pre-order listings</strong>: 5% platform fee on the total order value at fulfilment</li></ul><p>There are no listing fees — you only pay when you sell. Promoted listings (optional) are charged separately at a flat rate set during promotion setup.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 7,
    tags: ["fees", "commission", "platform-fee", "sellers"],
    relatedFAQs: ["faq-how-do-seller-payouts-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2200, 98),
    seo: { slug: "faq-what-are-letitrip-platform-fees" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(87),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-is-cod-available",
    question: "Is Cash on Delivery (COD) available?",
    answer: html(`<p>COD is available on LetItRip for orders up to <strong>₹10,000</strong>, subject to the seller enabling it for their store. Not all stores offer COD — check the payment options on the checkout page for the specific seller.</p><p>COD requires a <strong>20% online deposit</strong> at checkout to confirm the order. The remaining 80% is paid to the delivery agent on delivery. If you refuse delivery, the 20% deposit is non-refundable (it covers the seller's reverse-logistics cost).</p><p>COD is not available for auction wins or pre-orders — these require full online payment.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["cod", "cash-on-delivery", "payment"],
    relatedFAQs: ["faq-what-payment-methods-are-accepted"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1700, 74),
    seo: { slug: "faq-is-cod-available" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(86),
    updatedAt: daysAgo(7),
  },

  {
    id: "faq-can-i-use-multiple-coupons",
    question: "Can I use multiple coupon codes on one order?",
    answer: html(`<p>Yes — LetItRip supports stacking one <strong>platform coupon</strong> (issued by LetItRip) and one <strong>seller coupon</strong> (issued by the store) on the same order. Two platform coupons cannot be stacked — the higher-value one is applied automatically.</p><p>Coupon restrictions (minimum order value, applicable categories, first-order only) still apply per coupon. Check the coupon's terms at checkout before assuming it applies to your order.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 6,
    tags: ["coupon", "discount"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1900, 82),
    seo: { slug: "faq-can-i-use-multiple-coupons" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-why-was-my-payment-declined",
    question: "Why was my payment declined?",
    answer: html(`<p>Common causes:</p><ul><li><strong>Insufficient funds</strong> in your bank account or UPI-linked account</li><li><strong>Daily UPI limit exceeded</strong> — UPI has a ₹1 lakh/day limit per bank</li><li><strong>Card not enabled for online/international transactions</strong> — enable via your bank's mobile app</li><li><strong>Bank 2FA failed</strong> — wrong OTP or OTP expired</li><li><strong>VPN active</strong> — Razorpay may block payments from VPN IPs as a fraud precaution</li></ul><p>Try a different payment method or browser. The Razorpay error code shown at checkout identifies the exact cause. Contact <strong>support@letitrip.in</strong> with the error code for faster resolution.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 7,
    tags: ["payment", "declined", "error"],
    relatedFAQs: ["faq-what-payment-methods-are-accepted"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2100, 92),
    seo: { slug: "faq-why-was-my-payment-declined" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(9),
  },

  {
    id: "faq-gst-invoice-for-my-order",
    question: "Can I get a GST invoice for my order?",
    answer: html(`<p>GST invoices are issued by individual sellers. Enter your <strong>GSTIN</strong> in the Billing Details section at checkout. The seller generates a GST-compliant invoice downloadable from My Account → Orders → <strong>"Download Invoice"</strong> once the order is confirmed.</p><p>Not all sellers are GST-registered — sellers with turnover below ₹40 lakh are exempt. LetItRip's platform fee (if applicable) is always GST-inclusive at 18%, and a receipt is in your account.</p>`),
    category: "orders_payment",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 5,
    tags: ["gst", "invoice", "billing"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1100, 48),
    seo: { slug: "faq-gst-invoice-for-my-order" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(10),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PRODUCT INFORMATION (8 FAQs)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "faq-how-do-pre-orders-work",
    question: "How do pre-orders work on LetItRip?",
    answer: html(`<p>Pre-orders let you reserve upcoming collectibles before they arrive in India:</p><ol><li>Browse pre-order listings — each shows an estimated delivery window (e.g., "Shipping in 45–60 days").</li><li>Pay a <strong>deposit</strong> (typically 20–30% of the total price) to secure your unit.</li><li>The remaining balance is charged automatically when the item is ready to ship.</li><li>If the seller cancels the pre-order, your deposit is refunded in full within 5 business days.</li></ol><p>Pre-orders are available for Beyblade X new releases, Pokémon booster boxes, S.H.Figuarts, Nendoroids, and Hot Wheels RLC exclusives. <strong>Estimated delivery windows are set by sellers</strong> — delays are possible (see the pre-order delay FAQ).</p>`),
    category: "product_information",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: true,
    order: 1,
    priority: 10,
    tags: ["pre-order", "deposit", "how-to"],
    relatedFAQs: ["faq-can-i-cancel-a-pre-order", "faq-what-if-preorder-delayed"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(4700, 224),
    seo: {
      slug: "faq-how-do-pre-orders-work",
      metaTitle: "How Do Pre-Orders Work on LetItRip?",
      metaDescription: "Pre-orders on LetItRip let you reserve upcoming Pokémon, Beyblade X, and anime figures with a deposit.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },

  {
    id: "faq-can-i-cancel-a-pre-order",
    question: "Can I cancel a pre-order?",
    answer: html(`<p>You can cancel a pre-order <strong>before the seller marks it "In Production"</strong> — your deposit is fully refunded within 5 business days. After "In Production" status, cancellation may result in the deposit being forfeited (this is disclosed on the listing before you pay).</p><p>If the estimated delivery date shifts by more than 60 days, LetItRip gives you a 7-day window to cancel with a full deposit refund regardless of production status.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 8,
    tags: ["pre-order", "cancel", "deposit"],
    relatedFAQs: ["faq-how-do-pre-orders-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2900, 134),
    seo: { slug: "faq-can-i-cancel-a-pre-order" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-what-if-preorder-delayed",
    question: "What if my pre-order is delayed?",
    answer: html(`<p>Collectibles pre-orders frequently experience delays due to production issues, customs clearance, or distributor problems — this is normal in the hobby. LetItRip's policy:</p><ul><li><strong>Minor delay (under 30 days)</strong>: seller updates the date and notifies you. No action required unless you want to cancel.</li><li><strong>Major delay (30–60 days)</strong>: LetItRip sends a notification. You have 7 days to cancel with a full deposit refund.</li><li><strong>Excessive delay (over 60 days)</strong>: LetItRip may initiate a full refund if the seller cannot provide a confirmed new date within 14 days.</li></ul><p>Track your pre-order's current status in My Account → Orders.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 7,
    tags: ["pre-order", "delay"],
    relatedFAQs: ["faq-how-do-pre-orders-work", "faq-can-i-cancel-a-pre-order"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2100, 94),
    seo: { slug: "faq-what-if-preorder-delayed" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(7),
  },

  {
    id: "faq-are-preorder-products-authentic",
    question: "Are pre-order products guaranteed to be authentic?",
    answer: html(`<p>All pre-orders on LetItRip must be from <strong>verified sellers</strong> sourcing directly from official distributors or brand-authorised retailers. Every pre-order listing must include proof of distributor agreement reviewed by LetItRip before going live.</p><p>For pre-orders above ₹10,000, sellers must provide a distributor invoice at dispatch. Confirmed counterfeit = full refund + immediate seller suspension.</p><p>That said, LetItRip does not physically inspect pre-order stock before dispatch. We rely on seller documentation and post-delivery buyer reporting. If you receive something that appears non-authentic, raise a dispute immediately — do not confirm delivery.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 6,
    tags: ["pre-order", "authentic", "verified"],
    relatedFAQs: ["faq-how-do-i-report-a-fake-item"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1500, 66),
    seo: { slug: "faq-are-preorder-products-authentic" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(82),
    updatedAt: daysAgo(9),
  },

  {
    id: "faq-what-condition-grades-does-letitrip-use",
    question: "What item condition grades does LetItRip use?",
    answer: html(`<p>All listings on LetItRip must disclose item condition using our standard grading scale:</p><ul><li><strong>Mint / Brand New (M)</strong> — factory sealed or never used, no imperfections</li><li><strong>Near Mint (NM)</strong> — opened but essentially perfect; minimal handling, no visible wear</li><li><strong>Lightly Played (LP)</strong> — minor wear visible under close inspection; no creases, scratches, or heavy marks</li><li><strong>Moderately Played (MP)</strong> — visible wear, minor scratches or edge wear; still functional/displayable</li><li><strong>Heavily Played (HP)</strong> — significant wear; creases, heavy edge wear, or discolouration present</li><li><strong>Damaged (D)</strong> — major defects; cracks, tears, or heavy damage disclosed in listing</li></ul><p>For graded cards or figures, the grade is set by the grading company (PSA, BGS, CGC, AFA) — not by LetItRip or the seller. Grading disputes must be raised with the grading company directly.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 7,
    tags: ["condition", "grading", "near-mint"],
    relatedFAQs: ["faq-what-is-a-graded-slab-psa-bgs"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1800, 84),
    seo: { slug: "faq-what-condition-grades-does-letitrip-use" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(84),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-what-is-a-graded-slab-psa-bgs",
    question: "What is a graded card or slab (PSA, BGS, CGC)?",
    answer: html(`<p>A <strong>graded slab</strong> is a trading card that has been professionally authenticated and graded by a third-party grading company and encapsulated in a tamper-evident hard plastic case.</p><p>The major grading companies:</p><ul><li><strong>PSA (Professional Sports Authenticator)</strong> — the most recognised. Grades on a 1–10 scale. PSA 10 = Gem Mint (the highest).</li><li><strong>BGS (Beckett Grading Services)</strong> — also 1–10, with sub-grades for centering, corners, edges, and surface. BGS 9.5 "Gem Mint" is highly sought after.</li><li><strong>CGC (Certified Guaranty Company)</strong> — originally a comics grader, now popular for Pokémon. CGC 10 = Pristine.</li></ul><p>On LetItRip, all graded slab listings must display the cert/certificate number so buyers can verify the grade on the grading company's website before purchasing. If a slab arrives with a cracked case or mismatched cert number, raise a dispute immediately.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 7,
    tags: ["graded-slab", "psa", "bgs", "cgc", "pokemon", "authentication"],
    relatedFAQs: ["faq-what-condition-grades-does-letitrip-use", "faq-how-to-spot-fake-pokemon-cards-authentication"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2400, 114),
    seo: { slug: "faq-what-is-a-graded-slab-psa-bgs" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(83),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-to-spot-fake-pokemon-cards-authentication",
    question: "How do I spot fake Pokémon cards and authenticate collectibles?",
    answer: html(`<p>Counterfeit collectibles are a real risk in secondary markets. Here's how to protect yourself on LetItRip and in general:</p><p><strong>Pokémon Cards:</strong></p><ul><li><strong>Light test</strong> — hold the card up to a bright light. Genuine cards have a black layer in the middle that blocks most light; fakes are often lighter or fully translucent.</li><li><strong>Bend test</strong> — real cards have a slight snap and return to shape. Fakes feel flimsy or don't snap back. (Only do this on cards you already own.)</li><li><strong>Print quality</strong> — genuine cards have sharp, fine printing; fakes often show dot patterns, blurry text, or washed-out colours.</li><li><strong>Rip test</strong> — genuine cards have a distinctive black inner layer. Never do this to a card you're buying — ask the seller for a light test video.</li></ul><p><strong>Graded Slabs:</strong></p><ul><li>Verify the cert number on PSA's, BGS's, or CGC's official website before paying.</li><li>Inspect the slab for tampering — the label should be sealed inside with no gaps.</li></ul><p><strong>Hot Wheels Redlines / Vintage:</strong></p><ul><li>Repainted castings are common — look for matching wheel colours, original tampos (decals), and period-correct packaging.</li></ul><p>If you're unsure about a listing, ask the seller for additional photos or a video authentication. Sellers on LetItRip are required to respond to authentication requests within 24 hours.</p>`),
    category: "product_information",
    showOnHomepage: true,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 8,
    tags: ["fake", "counterfeit", "pokemon", "authentication", "graded-slab"],
    relatedFAQs: ["faq-how-do-i-report-a-fake-item", "faq-what-is-a-graded-slab-psa-bgs"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(5200, 278),
    seo: {
      slug: "faq-how-to-spot-fake-pokemon-cards-authentication",
      metaTitle: "How to Spot Fake Pokémon Cards and Authenticate Collectibles",
      metaDescription: "Light test, print quality, graded slab cert checks — a buyer's guide to authenticating Pokémon cards, slabs, and collectibles.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(3),
  },

  {
    id: "faq-what-is-beyblade-x",
    question: "What is Beyblade X and where can I buy it in India?",
    answer: html(`<p><strong>Beyblade X</strong> is the latest generation of Beyblade, launched by Takara Tomy in Japan in 2023. It features a new "X" gear system inside the bit — when activated, the top accelerates and launches out of the stadium for dramatic finishes. Beyblade X tops are officially called <em>Beys</em> and require an XStadium for correct play.</p><p>On LetItRip, verified sellers import official Takara Tomy Beyblade X products directly from Japan. You can buy:</p><ul><li>Individual tops (Dran Sword, Hells Scythe, Knight Shield, and more)</li><li>Launchers and cords</li><li>XStadiums (full-size and compact)</li><li>Booster and starter sets</li></ul><p>Browse the <strong>Beyblade X category</strong> on LetItRip and filter by seller rating to find trusted importers. Always confirm you are buying official Takara Tomy product — cheap Chinese counterfeits are common and do not perform correctly.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 8,
    priority: 6,
    tags: ["beyblade-x", "takara-tomy", "spinning-tops", "india"],
    relatedFAQs: ["faq-how-do-i-report-a-fake-item"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3800, 178),
    seo: {
      slug: "faq-what-is-beyblade-x",
      metaTitle: "What is Beyblade X? Buy Official Takara Tomy in India",
      metaDescription: "Beyblade X is the latest Beyblade generation. Buy official Takara Tomy imports in India on LetItRip.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(78),
    updatedAt: daysAgo(4),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ACCOUNT & SECURITY (7 FAQs)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "faq-how-do-i-create-an-account",
    question: "How do I create a LetItRip account?",
    answer: html(`<p>Creating a LetItRip account is free and takes under a minute:</p><ol><li>Click <strong>Sign Up</strong> on any page.</li><li>Enter your email address and create a password, or sign up with Google.</li><li>Verify your email address — we send a verification link immediately.</li><li>Complete your profile (display name, optional phone number for WhatsApp updates).</li></ol><p>You can browse and wishlist items without an account, but you need an account to buy, bid, or sell. Phone verification is required for COD orders and bidding on auctions above ₹5,000.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 1,
    priority: 8,
    tags: ["account", "sign-up", "register"],
    relatedFAQs: ["faq-how-do-i-become-a-verified-seller"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2200, 98),
    seo: { slug: "faq-how-do-i-create-an-account" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-how-do-i-become-a-verified-seller",
    question: "How do I become a verified seller on LetItRip?",
    answer: html(`<p>Selling on LetItRip requires manual verification — we review every store before approval. To apply:</p><ol><li>Go to My Account → <strong>Become a Seller</strong>.</li><li>Fill in your store details: store name, category, bio, and shipping policy.</li><li>Complete KYC: submit a government-issued ID (Aadhaar, PAN, or passport) and a selfie for identity verification.</li><li>Provide bank account or UPI details for payouts.</li><li>Our team reviews your application within 2–3 business days and approves or requests more information.</li></ol><p>Approval criteria include: valid KYC documents, a credible store description, and no history of fraudulent activity on LetItRip or associated platforms. Individual sellers and small businesses are both welcome.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: true,
    isPinned: false,
    order: 2,
    priority: 9,
    tags: ["seller", "verification", "kyc", "store"],
    relatedFAQs: ["faq-what-is-kyc-verification", "faq-how-do-seller-payouts-work"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(3100, 148),
    seo: {
      slug: "faq-how-do-i-become-a-verified-seller",
      metaTitle: "How to Become a Verified Seller on LetItRip",
      metaDescription: "Apply to sell collectibles on LetItRip. Manual KYC verification and 2–3 day approval for Indian sellers.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(87),
    updatedAt: daysAgo(4),
  },

  {
    id: "faq-what-is-kyc-verification",
    question: "What is KYC verification and why is it required?",
    answer: html(`<p>KYC (Know Your Customer) is a mandatory identity verification process required by Indian financial regulations for any platform that processes payments. LetItRip requires KYC for sellers (to enable payouts) and for buyers making high-value purchases or COD orders above ₹5,000.</p><p><strong>What KYC involves:</strong></p><ul><li>A government-issued photo ID (Aadhaar card, PAN card, or passport)</li><li>A selfie for liveness verification</li><li>Bank account or UPI details (sellers only, for payouts)</li></ul><p>Your KYC data is stored encrypted and is never shared with sellers, buyers, or third parties beyond what is required by law. LetItRip uses a DPDP-compliant document verification partner.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 7,
    tags: ["kyc", "verification", "identity", "aadhaar"],
    relatedFAQs: ["faq-how-do-i-become-a-verified-seller"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1900, 88),
    seo: { slug: "faq-what-is-kyc-verification" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(86),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-do-i-reset-my-password",
    question: "How do I reset my password?",
    answer: html(`<p>On the login page, click <strong>"Forgot Password"</strong> and enter your registered email address. We send a password reset link immediately — it expires in 1 hour.</p><p>If you signed up with Google and don't have a password, use the "Continue with Google" button — there is no separate LetItRip password to reset.</p><p>If you no longer have access to your registered email, contact <strong>support@letitrip.in</strong> with your registered phone number for account recovery.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 6,
    tags: ["password", "reset", "login"],
    relatedFAQs: ["faq-how-do-i-protect-my-account"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1400, 64),
    seo: { slug: "faq-how-do-i-reset-my-password" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(85),
    updatedAt: daysAgo(7),
  },

  {
    id: "faq-can-i-have-multiple-accounts",
    question: "Can I have multiple LetItRip accounts?",
    answer: html(`<p><strong>No.</strong> LetItRip permits one account per individual. Operating multiple buyer or seller accounts (for example, to bypass a suspension, accumulate separate feedback, or exploit welcome offers) is a violation of our Terms of Service and will result in all associated accounts being permanently banned.</p><p>If you are a business with multiple trading entities, contact <strong>support@letitrip.in</strong> before creating a second store — we have a process for multi-brand sellers under a single verified identity.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 5,
    tags: ["account", "multiple", "ban"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(820, 36),
    seo: { slug: "faq-can-i-have-multiple-accounts" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(84),
    updatedAt: daysAgo(8),
  },

  {
    id: "faq-how-do-i-delete-my-account",
    question: "How do I delete my LetItRip account?",
    answer: html(`<p>You can request account deletion from My Account → Settings → <strong>"Delete Account"</strong>. Before deletion:</p><ul><li>All open orders must be completed or cancelled.</li><li>Any active listings must be closed.</li><li>Any pending seller payouts will be processed before the account is removed.</li></ul><p>Account deletion is <strong>permanent and irreversible</strong> — your order history, reviews, and profile data will be removed within 30 days in accordance with DPDP regulations. If you only want to take a break, you can deactivate your account instead (My Account → Settings → "Deactivate Account") — this hides your profile and listings without deleting data.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 5,
    tags: ["delete", "account", "privacy"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(740, 32),
    seo: { slug: "faq-how-do-i-delete-my-account" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(82),
    updatedAt: daysAgo(9),
  },

  {
    id: "faq-how-do-i-protect-my-account",
    question: "How do I keep my LetItRip account secure?",
    answer: html(`<p>Best practices for account security on LetItRip:</p><ul><li><strong>Use a strong, unique password</strong> — don't reuse passwords from other sites.</li><li><strong>Enable 2-Step Verification</strong> (2FA) in My Account → Settings → Security. We support SMS OTP and authenticator apps.</li><li><strong>Never share your login details</strong> — LetItRip support will never ask for your password.</li><li><strong>Watch for phishing</strong> — all official LetItRip emails come from @letitrip.in. Be suspicious of any message asking you to click a payment link outside the platform.</li><li><strong>Never pay outside LetItRip</strong> — if a seller asks you to UPI them directly or use a third-party app, report it immediately. Off-platform payments are not covered by escrow.</li></ul><p>If you suspect your account has been compromised, change your password immediately and contact <strong>support@letitrip.in</strong>.</p>`),
    category: "account_security",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 7,
    tags: ["security", "2fa", "phishing", "password"],
    relatedFAQs: ["faq-how-do-i-reset-my-password"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1200, 56),
    seo: { slug: "faq-how-do-i-protect-my-account" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(81),
    updatedAt: daysAgo(6),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TECHNICAL SUPPORT (7 FAQs)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "faq-app-not-loading",
    question: "The LetItRip website or app is not loading — what should I do?",
    answer: html(`<p>Try these steps in order:</p><ol><li><strong>Refresh the page</strong> and wait 10 seconds — brief server timeouts are usually self-resolving.</li><li><strong>Clear your browser cache</strong> (Ctrl+Shift+R on desktop; Safari → Settings → Clear History on iOS).</li><li><strong>Check your internet connection</strong> — try loading another website or switching between WiFi and mobile data.</li><li><strong>Disable browser extensions</strong> — ad blockers occasionally interfere with our checkout flow.</li><li><strong>Try a different browser</strong> — LetItRip works best on Chrome, Firefox, and Safari (latest versions).</li></ol><p>If the issue persists, check our status page or email <strong>support@letitrip.in</strong> describing the error (screenshot if possible) and your browser/device details.</p>`),
    category: "technical_support",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 1,
    priority: 7,
    tags: ["app", "loading", "technical", "browser"],
    relatedFAQs: ["faq-how-do-i-contact-support"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1100, 48),
    seo: { slug: "faq-app-not-loading" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(80),
    updatedAt: daysAgo(7),
  },

  {
    id: "faq-why-was-my-listing-rejected",
    question: "Why was my listing rejected?",
    answer: html(`<p>Listings are reviewed before going live. Common rejection reasons:</p><ul><li><strong>Insufficient photographs</strong> — all listings require at least 3 photos from different angles; condition flaws must be photographed and disclosed.</li><li><strong>Missing or incomplete condition disclosure</strong> — every item's condition grade must be explicitly stated.</li><li><strong>Prohibited items</strong> — bootlegs, unlicensed proxies, opened-and-resealed products (without disclosure), and items with removed serial stickers are not permitted.</li><li><strong>Misleading title or description</strong> — using brand names inaccurately (e.g., listing a non-Nintendo product as "official Nintendo").</li><li><strong>Price below platform minimum</strong> — listings must meet a minimum price threshold to cover payment processing costs.</li></ul><p>Rejection emails include the specific reason. Fix the issue and resubmit — resubmissions are reviewed within 12 hours. If you believe the rejection was in error, email <strong>support@letitrip.in</strong> with your listing ID.</p>`),
    category: "technical_support",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 2,
    priority: 7,
    tags: ["listing", "rejected", "seller"],
    relatedFAQs: ["faq-can-i-edit-a-listing-after-publishing"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1600, 72),
    seo: { slug: "faq-why-was-my-listing-rejected" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(79),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-how-do-i-upload-product-images",
    question: "What are the image requirements for listings?",
    answer: html(`<p>Image requirements for all LetItRip listings:</p><ul><li><strong>Minimum 3 photos</strong> — front, back, and at least one close-up of condition-relevant areas</li><li><strong>Format</strong>: JPG or PNG, minimum 800×800px, maximum 20MB per image</li><li><strong>Background</strong>: clean, neutral background preferred (white or grey); avoid busy backgrounds that obscure the item</li><li><strong>No watermarks or stock photos</strong> — all photos must be of the actual item you are selling</li><li><strong>Condition flaws must be photographed</strong> — any scratches, dents, creases, or missing parts must appear in at least one photo; failure to disclose is grounds for a refund and listing removal</li></ul><p>Listings with more photos (6–10) statistically sell faster and receive fewer disputes. Use natural lighting where possible.</p>`),
    category: "technical_support",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 3,
    priority: 6,
    tags: ["images", "listing", "seller", "photos"],
    relatedFAQs: ["faq-why-was-my-listing-rejected"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1300, 58),
    seo: { slug: "faq-how-do-i-upload-product-images" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(78),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-why-is-my-account-suspended",
    question: "Why has my account been suspended?",
    answer: html(`<p>Accounts are suspended automatically or manually for the following reasons:</p><ul><li><strong>Seller</strong>: multiple confirmed counterfeit reports, 3+ non-dispatch strikes, sustained negative buyer feedback below 3.0 stars, or a chargeback ratio above platform limits</li><li><strong>Buyer</strong>: 3+ non-payment strikes on won auctions, confirmed fraudulent returns, or off-platform payment solicitation</li><li><strong>Both</strong>: KYC documents found to be fraudulent, multiple account creation, or a court or regulatory order</li></ul><p>You will receive an email explaining the suspension reason. To appeal: reply to the suspension email with your explanation and any supporting evidence. Appeals are reviewed within 5 business days. If your suspension was triggered automatically (e.g., by a fraud algorithm), many are reversed on review.</p>`),
    category: "technical_support",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 4,
    priority: 6,
    tags: ["suspension", "account", "ban"],
    relatedFAQs: ["faq-how-do-i-contact-support"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(980, 44),
    seo: { slug: "faq-why-is-my-account-suspended" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(77),
    updatedAt: daysAgo(7),
  },

  {
    id: "faq-how-to-leave-a-review",
    question: "How do I leave a review for a seller?",
    answer: html(`<p>Reviews can be left after confirmed delivery. Go to My Account → Orders → find the completed order → click <strong>"Leave Review"</strong>.</p><p>Review guidelines:</p><ul><li>Rate on a <strong>1–5 star scale</strong> covering item accuracy, packaging quality, and shipping speed</li><li>Write a brief title and a description of your experience</li><li>You can add up to 5 photos (great for showing item condition on arrival)</li><li>Reviews must be based on your actual purchase — reviews that are abusive, off-topic, or clearly fake will be removed</li></ul><p>Sellers can post a single public reply to any review. LetItRip does not allow sellers to request review removal except in cases of policy violation. Your review helps other collectors make informed decisions.</p>`),
    category: "technical_support",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 5,
    priority: 6,
    tags: ["review", "feedback", "seller-rating"],
    relatedFAQs: [],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1500, 66),
    seo: { slug: "faq-how-to-leave-a-review" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(76),
    updatedAt: daysAgo(5),
  },

  {
    id: "faq-can-i-edit-a-listing-after-publishing",
    question: "Can I edit a listing after it has been published?",
    answer: html(`<p>Yes, with restrictions:</p><ul><li><strong>Standard listings with no pending orders</strong>: price, description, images, and condition can be edited. Edits go through a quick re-review (usually within 2 hours).</li><li><strong>Listings with active bids (auctions)</strong>: <strong>material edits are not permitted</strong> once bidding has started. You may only update minor typos or add supplementary photos. Any edit that materially changes the item description (condition, contents, authenticity) after bids are placed is a policy violation and buyers may be entitled to bid retraction.</li><li><strong>Sold or completed listings</strong>: cannot be edited.</li></ul><p>Always ensure your listing is accurate and complete before publishing to avoid disputes.</p>`),
    category: "technical_support",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 6,
    priority: 6,
    tags: ["listing", "edit", "seller"],
    relatedFAQs: ["faq-can-i-retract-a-bid"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(1200, 54),
    seo: { slug: "faq-can-i-edit-a-listing-after-publishing" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(75),
    updatedAt: daysAgo(6),
  },

  {
    id: "faq-how-do-seller-payouts-work",
    question: "How do seller payouts work on LetItRip?",
    answer: html(`<p>Seller payouts are processed on a <strong>weekly cycle</strong> (every Monday for orders confirmed the previous week):</p><ol><li>Buyer confirms delivery (or 5-day auto-release triggers).</li><li>LetItRip deducts the platform fee (5%) and Razorpay processing fee (~2.36%).</li><li>The net amount is credited to your registered bank account or UPI ID.</li><li>Payout appears in My Store → Payouts with a breakdown per order.</li></ol><p>First-time sellers have a 7-day holding period after their first confirmed sale before payout is initiated — this is a fraud prevention measure and is lifted automatically after your first successful payout.</p><p>If a payout is delayed beyond 5 business days from the expected date, contact <strong>support@letitrip.in</strong> with your store ID and the affected payout period.</p>`),
    category: "technical_support",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 7,
    priority: 7,
    tags: ["payout", "seller", "earnings", "bank"],
    relatedFAQs: ["faq-what-are-letitrip-platform-fees", "faq-how-do-i-become-a-verified-seller"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(2600, 122),
    seo: { slug: "faq-how-do-seller-payouts-work" },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(74),
    updatedAt: daysAgo(4),
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUNDLES + PRIZE DRAWS (SB5-B — 6 FAQs)
  // ══════════════════════════════════════════════════════════════════════════
  // Filed under `product_information` because the schema enum doesn't carry
  // a dedicated "listings" bucket. Tags identify the surface — clients can
  // filter on tag instead.

  {
    id: "faq-what-is-bundle",
    question: "What is a bundle on LetItRip?",
    answer: html(`<p>A <strong>bundle</strong> is a curated multi-product listing — 3 to 16 individual items grouped under one fixed price. Sellers use bundles to ship combos that work together: starter packs, themed sets, multi-card lots, or "buy the whole collection" deals. Each item in a bundle must be in the seller's catalogue first; bundles never invent new SKUs.</p><p>Bundles are always one of two listing kinds: <strong>standard bundles</strong> (every item ships immediately) or <strong>pre-order bundles</strong> (every item is upcoming). Auctions and prize draws cannot be bundled — the price-discovery mechanics don't compose.</p><p>When any item inside a bundle sells through another channel, the bundle automatically flips to <em>out of stock</em> — you'll never end up with a half-fulfilled bundle.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 30,
    priority: 6,
    tags: ["bundle", "listings", "multi-item"],
    relatedFAQs: ["faq-how-create-bundle", "faq-what-is-prize-draw"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(0, 0),
    seo: {
      slug: "faq-what-is-bundle",
      metaTitle: "What is a bundle? — LetItRip",
      metaDescription: "Bundles group 3–16 items into one fixed-price listing. Standard or pre-order, never auctions or prize draws.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },

  {
    id: "faq-how-create-bundle",
    question: "How do I create a bundle?",
    answer: html(`<p>From your store dashboard, open <strong>Listings → Bundles → New bundle</strong>. Steps:</p><ol><li>Title + description for the bundle.</li><li>Pick 3–16 items from your catalogue using the inline picker. All items must share the same listing type (all standard, or all pre-order).</li><li>Set the bundle price — usually lower than the sum of the individual prices.</li><li>(Optional) Set a per-customer limit if you want to cap repeat purchases.</li><li>Save as <em>Draft</em> to keep iterating, or <em>Published</em> to make it live.</li></ol><p>Once published the bundle appears at <code>/bundles/{your-slug}</code> and in the public bundle list. Every product inside the bundle automatically picks up a "In bundle: …" badge linking back to the bundle.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 31,
    priority: 5,
    tags: ["bundle", "seller", "create-listing"],
    relatedFAQs: ["faq-what-is-bundle"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(0, 0),
    seo: {
      slug: "faq-how-create-bundle",
      metaTitle: "How to create a bundle — LetItRip seller guide",
      metaDescription: "Step-by-step: pick 3–16 items, set the bundle price, publish. Standard or pre-order only.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },

  {
    id: "faq-what-is-prize-draw",
    question: "What is a prize draw?",
    answer: html(`<p>A <strong>prize draw</strong> is a single listing with a fixed pool of distinct items (called a <em>collage</em>) where each paid entry wins exactly one item from the pool at random. The seller sets the price per entry, the maximum number of entries, and a fixed reveal window during which winners discover which item they won.</p><p>Prize draws differ from raffles in that <strong>every paid entry wins</strong> — the only randomness is which item from the pool you get. The pool is finite: once an item is won, it's removed for everyone else. If the pool is exhausted before all entries reveal, the remaining entries are auto-refunded.</p><p>Prize draw payments are <strong>non-refundable</strong> once the reveal window opens (subject to the pool-exhaustion fallback). You'll see an explicit consent prompt at checkout.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 32,
    priority: 7,
    tags: ["prize-draw", "listings", "non-refundable"],
    relatedFAQs: [
      "faq-prize-draw-fairness",
      "faq-prize-draw-refund",
      "faq-prize-draw-reveal",
    ],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(0, 0),
    seo: {
      slug: "faq-what-is-prize-draw",
      metaTitle: "What is a prize draw? — LetItRip",
      metaDescription: "Each paid entry wins one item from the seller's pool at random. Finite pool, fixed reveal window, non-refundable.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },

  {
    id: "faq-prize-draw-fairness",
    question: "How does LetItRip make prize draws fair?",
    answer: html(`<p>Two guarantees underpin every prize draw:</p><ol><li><strong>Cryptographic randomness.</strong> The winning item is selected by <code>crypto.randomInt()</code> over the current pool of unwon items at the exact moment you click <em>Reveal My Prize</em>. The seller cannot influence which item you receive.</li><li><strong>Open source RNG code.</strong> Every prize draw links to the exact Git commit of the reveal API that ran on your entry. Click <em>View RNG Source Code</em> on the prize draw detail page to inspect the code yourself.</li></ol><p>The pool is finite — once an item is won, it's removed for everyone else. If the pool is exhausted before all entries reveal (rare; usually means the seller mispriced entries vs pool size), the remaining entries are auto-refunded and notified.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 33,
    priority: 7,
    tags: ["prize-draw", "fairness", "randomness", "rng", "open-source"],
    relatedFAQs: ["faq-what-is-prize-draw", "faq-prize-draw-refund"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(0, 0),
    seo: {
      slug: "faq-prize-draw-fairness",
      metaTitle: "Are prize draws fair? — LetItRip RNG explained",
      metaDescription: "crypto.randomInt over the live pool, source-code linked per draw. Pool exhaustion auto-refunds.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },

  {
    id: "faq-prize-draw-refund",
    question: "Can I get a refund on a prize draw entry?",
    answer: html(`<p>Prize draw entries are <strong>non-refundable once the reveal window opens</strong>. You'll see an explicit consent dialog at checkout — your "Enter Draw" click is the binding action.</p><p>The exceptions, all automatic:</p><ul><li><strong>Pool exhausted before you reveal.</strong> If every item in the pool is won before you click <em>Reveal My Prize</em>, your entry is auto-refunded in full and you're notified.</li><li><strong>Reveal deadline missed.</strong> If you don't reveal within the deadline (default 3 days after the reveal window opens), the system auto-refunds and the item returns to the pool.</li><li><strong>Draw cancelled by the seller.</strong> Sellers may cancel a draw before the reveal window opens — every paid entry is auto-refunded.</li></ul><p>Refunds reverse via Razorpay to your original payment method within 5–7 business days (UPI: 1–2 business days).</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 34,
    priority: 7,
    tags: ["prize-draw", "refund", "non-refundable", "policy"],
    relatedFAQs: ["faq-what-is-prize-draw", "faq-prize-draw-reveal"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(0, 0),
    seo: {
      slug: "faq-prize-draw-refund",
      metaTitle: "Prize draw refund policy — LetItRip",
      metaDescription: "Non-refundable once reveal opens. Pool exhaustion, missed deadlines, and cancellations auto-refund.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },

  {
    id: "faq-prize-draw-reveal",
    question: "How does prize draw reveal work?",
    answer: html(`<p>After you pay for a prize draw entry, the system places your order. You then wait for the reveal to do anything:</p><ol><li><strong>Reveal window opens.</strong> The seller publishes a fixed window (e.g. "Reveal opens June 15, closes June 22"). You get an in-app + email notification when it opens.</li><li><strong>Click "Reveal My Prize".</strong> On your order detail page, click <em>Reveal My Prize</em>. The system picks one of the still-available items at random, marks it as won, and shows you the result with a card-flip animation.</li><li><strong>Reveal deadline.</strong> You have until the deadline (default 3 days after window open, capped at window close) to reveal. Miss the deadline → auto-refund + item goes back into the pool.</li><li><strong>Seller ships.</strong> The seller dispatches your revealed item within their stated timeline. Tracking appears on the order detail page as usual.</li></ol><p>You can re-open the order detail page to see your won item any time — the reveal is permanent.</p>`),
    category: "product_information",
    showOnHomepage: false,
    showInFooter: false,
    isPinned: false,
    order: 35,
    priority: 6,
    tags: ["prize-draw", "reveal", "deadline", "shipping"],
    relatedFAQs: ["faq-what-is-prize-draw", "faq-prize-draw-refund"],
    useSiteSettings: true,
    variables: {},
    stats: makeStats(0, 0),
    seo: {
      slug: "faq-prize-draw-reveal",
      metaTitle: "How to reveal a prize draw entry — LetItRip",
      metaDescription: "Reveal window opens, click 'Reveal My Prize', seller ships. Miss the deadline → auto-refund.",
    },
    isActive: true,
    createdBy: "user-admin-letitrip",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
];
