/**
 * Hot Wheels — Products Seed Data
 * 30 general · 3 auctions · 2 pre-orders = 35 total
 * Seller: Speed King Diecast (store-speed-king-diecast)
 */

import { getDefaultCurrency } from "./seed-market-config";
import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

const SK = {
  storeId: "store-speed-king-diecast",
  storeName: "Speed King Diecast",
} as const;

const HW_IMGS = [
  "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/HotWheels.svg/640px-HotWheels.svg.png",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Die-cast_toy_automobiles.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Toy_Cars_Hot_Wheels.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Matchbox_cars.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hot_Wheels_-_Twin_Mill.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Diecast_toy_car.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Toy_car.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hot_Wheels_cars_collection.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Miniature_diecast_car.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hot_Wheels_Deora_II.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Diecast_model_car.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Toy_sports_car.jpg?width=640",
];
const img = (seed: string) => {
  let h = 0; for (const c of seed) h = (h * 31 + c.charCodeAt(0)) & 0x7fff;
  return HW_IMGS[h % HW_IMGS.length];
};

export const hotWheelsProductsSeedData: Partial<ProductDocument>[] = [

  // ── BASIC MAINLINE CARS (15) ──────────────────────────────────────────────

  {
    id: "product-hw-corvette-zr1-2019-basic-sk-1",
    title: "Hot Wheels 2019 Corvette ZR1 — Mainline (Red)",
    description: "<p>The iconic 2019 Corvette ZR1 in Hot Wheels scale. Vivid red finish with detailed tampo print. A must-have for American muscle collectors.</p>",
    slug: "product-hw-2019-corvette-zr1-red-mainline",
    category: "category-hw-basic-cars",
    subcategory: "American Muscle",
    brand: "Hot Wheels",
    price: 199,
    currency: _CURRENCY,
    stockQuantity: 30,
    availableQuantity: 24,
    mainImage: img("hw-corvette-zr1"),
    images: [img("hw-corvette-zr1"), img("hw-corvette-zr1-2")],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
      thumbnailUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hot_Wheels_Deora_II.jpg?width=640",
      duration: 47,
    },
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "corvette", "mainline", "american muscle", "red"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Mainline 2024" },
      { name: "Material", value: "Die-cast zinc alloy" },
      { name: "Tyre", value: "Plastic" },
      { name: "Colour", value: "Red with Black Tampo" },
    ],
    features: ["Opening hood detail", "Free-rolling plastic wheels", "Blister-card packaged"],
    shippingInfo: "Bubble-packed in rigid box. PAN India delivery.",
    returnPolicy: "10-day returns for damaged or wrong item.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.6,
    reviewCount: 14,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-67-camaro-blue-basic-sk-2",
    title: "Hot Wheels '67 Camaro — Mainline (Metallic Blue)",
    description: "<p>Classic 1967 Chevrolet Camaro in Hot Wheels 1:64 scale. Striking metallic blue finish with chrome bumpers.</p>",
    slug: "product-hw-67-camaro-metallic-blue",
    category: "category-hw-basic-cars",
    subcategory: "Classic American",
    brand: "Hot Wheels",
    price: 179,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 18,
    mainImage: img("hw-67-camaro"),
    images: [img("hw-67-camaro")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "camaro", "67", "classic", "muscle car"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Year", value: "1967" },
      { name: "Material", value: "Die-cast zinc alloy" },
    ],
    features: ["Detailed interior", "Chrome accents"],
    shippingInfo: "Bubble-packed. Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 9,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-hw-twin-mill-classic-basic-sk-3",
    title: "Hot Wheels Twin Mill — Classic Redline Replica",
    description: "<p>The legendary Twin Mill — one of the most iconic original Hot Wheels designs ever created. Dual-engine supercar in eye-catching orange with tampo details.</p>",
    slug: "product-hw-twin-mill-classic-redline",
    category: "category-hw-basic-cars",
    subcategory: "Originals",
    brand: "Hot Wheels",
    price: 249,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 11,
    mainImage: img("hw-twin-mill"),
    images: [img("hw-twin-mill")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "twin mill", "classic", "original", "iconic"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Design", value: "Original Hot Wheels Design" },
      { name: "Series", value: "Nostalgia Collection" },
    ],
    features: ["Twin engine design", "Iconic stripe tampo", "Collector packaging"],
    shippingInfo: "Collector-grade packaging. Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.8,
    reviewCount: 22,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-bone-shaker-skull-basic-sk-4",
    title: "Hot Wheels Bone Shaker — Skull Edition (Black)",
    description: "<p>Bone Shaker is one of Hot Wheels' most popular original designs. The skull and engine exposed front makes this an instant classic. Black variant with chrome details.</p>",
    slug: "product-hw-bone-shaker-skull-black",
    category: "category-hw-basic-cars",
    subcategory: "Originals",
    brand: "Hot Wheels",
    price: 199,
    currency: _CURRENCY,
    stockQuantity: 25,
    availableQuantity: 20,
    mainImage: img("hw-bone-shaker"),
    images: [img("hw-bone-shaker")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "bone shaker", "skull", "original design"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Type", value: "Original Design" },
    ],
    features: ["Skull front detail", "Exposed hot rod engine"],
    shippingInfo: "Nationwide delivery with tracking.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.4,
    reviewCount: 7,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-hw-toyota-ae86-jdm-basic-sk-5",
    title: "Hot Wheels Toyota AE86 Corolla — JDM Edition (White)",
    description: "<p>The legendary Toyota AE86 Trueno in white with Initial D-inspired livery. One of the most beloved JDM icons in Hot Wheels form. Extremely popular — limited stock.</p>",
    slug: "product-hw-toyota-ae86-corolla-jdm-white",
    category: "category-hw-basic-cars",
    subcategory: "JDM",
    brand: "Hot Wheels",
    price: 299,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 7,
    mainImage: img("hw-ae86"),
    images: [img("hw-ae86"), img("hw-ae86-2")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "ae86", "toyota", "jdm", "initial d", "trueno"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Origin", value: "Japan" },
      { name: "Series", value: "JDM Masters" },
    ],
    features: ["Iconic panda white paint", "JDM hood script tampo", "Real rubber tyres"],
    shippingInfo: "Premium padded packaging.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(15),
    avgRating: 4.9,
    reviewCount: 31,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },

  {
    id: "product-hw-ford-gt-lm-racing-basic-sk-6",
    title: "Hot Wheels Ford GT Le Mans — Racing Livery",
    description: "<p>Ford GT in full Le Mans racing livery — the car that beat Ferrari at the 1966 24 Hours of Le Mans. Stunning Gulf Oil colours in 1:64 scale.</p>",
    slug: "product-hw-ford-gt-le-mans-racing",
    category: "category-hw-basic-cars",
    subcategory: "Racing",
    brand: "Hot Wheels",
    price: 229,
    currency: _CURRENCY,
    stockQuantity: 18,
    availableQuantity: 15,
    mainImage: img("hw-ford-gt-lm"),
    images: [img("hw-ford-gt-lm")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "ford gt", "le mans", "racing", "gulf"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Racing Circuit" },
      { name: "Livery", value: "Gulf Oil Le Mans" },
    ],
    features: ["Race number tampo", "Gulf Oil blue and orange"],
    shippingInfo: "Bubble-packed nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 11,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-hw-lamborghini-huracan-yellow-basic-sk-7",
    title: "Hot Wheels Lamborghini HuracÃ¡n LP 610-4 (Yellow)",
    description: "<p>The Lamborghini HuracÃ¡n in the classic Giallo Belenus yellow. Sharp angles and supercar stance make this one of the best modern Hot Wheels castings.</p>",
    slug: "product-hw-lamborghini-huracan-yellow",
    category: "category-hw-basic-cars",
    subcategory: "Supercars",
    brand: "Hot Wheels",
    price: 249,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("hw-huracan"),
    images: [img("hw-huracan")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "lamborghini", "huracan", "supercar", "yellow"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Brand", value: "Lamborghini" },
      { name: "Model", value: "HuracÃ¡n LP 610-4" },
    ],
    features: ["Official Lamborghini licensing", "Detailed interior"],
    shippingInfo: "Padded box nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 8,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(7),
  },

  {
    id: "product-hw-dodge-challenger-hellcat-basic-sk-8",
    title: "Hot Wheels Dodge Challenger SRT Hellcat (Dark Purple)",
    description: "<p>The Dodge Challenger SRT Hellcat — 707 bhp of raw American muscle in 1:64 form. Dark purple with subtle flame tampo.</p>",
    slug: "product-hw-dodge-challenger-hellcat-purple",
    category: "category-hw-basic-cars",
    subcategory: "American Muscle",
    brand: "Hot Wheels",
    price: 199,
    currency: _CURRENCY,
    stockQuantity: 22,
    availableQuantity: 19,
    mainImage: img("hw-challenger"),
    images: [img("hw-challenger")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "dodge", "challenger", "hellcat", "muscle car"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Engine", value: "Supercharged 6.2L Hemi" },
    ],
    features: ["Chrome wheels", "SRT badging"],
    shippingInfo: "Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 6,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(8),
  },

  {
    id: "product-hw-deora-iii-surf-basic-sk-9",
    title: "Hot Wheels Deora III — Surf Van (Teal)",
    description: "<p>The Deora III continues the legendary Deora lineage. Part van, part hot rod, all Cool. The surfboard detail and teal finish make this a showpiece.</p>",
    slug: "product-hw-deora-iii-surf-van-teal",
    category: "category-hw-basic-cars",
    subcategory: "Originals",
    brand: "Hot Wheels",
    price: 229,
    currency: _CURRENCY,
    stockQuantity: 14,
    availableQuantity: 12,
    mainImage: img("hw-deora-iii"),
    images: [img("hw-deora-iii")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "deora", "surf van", "original", "cool"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Originals" },
    ],
    features: ["Surfboard side detail", "Teal metal-flake finish"],
    shippingInfo: "Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.4,
    reviewCount: 5,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(9),
  },

  {
    id: "product-hw-nissan-gtr-r35-basic-sk-10",
    title: "Hot Wheels Nissan GT-R R35 (Midnight Purple)",
    description: "<p>The Nissan GT-R R35 — Godzilla in midnight purple. Sharp casting with all GT-R detail lines reproduced perfectly in 1:64 scale.</p>",
    slug: "product-hw-nissan-gtr-r35-midnight-purple",
    category: "category-hw-basic-cars",
    subcategory: "JDM",
    brand: "Hot Wheels",
    price: 249,
    currency: _CURRENCY,
    stockQuantity: 16,
    availableQuantity: 13,
    mainImage: img("hw-gtr"),
    images: [img("hw-gtr")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "nissan", "gtr", "r35", "godzilla", "jdm"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Engine", value: "3.8L Twin Turbo V6" },
      { name: "Origin", value: "Japan" },
    ],
    features: ["GT-R script tampo", "Detailed interior"],
    shippingInfo: "Padded nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 13,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-ferrari-488-gt3-basic-sk-11",
    title: "Hot Wheels Ferrari 488 GT3 — Race Edition",
    description: "<p>Ferrari 488 GT3 in full race livery. Official Ferrari licensed casting in 1:64 with race number tampo and GT3 body kit details.</p>",
    slug: "product-hw-ferrari-488-gt3-race",
    category: "category-hw-basic-cars",
    subcategory: "Supercars",
    brand: "Hot Wheels",
    price: 299,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 6,
    mainImage: img("hw-ferrari-488"),
    images: [img("hw-ferrari-488")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "ferrari", "488", "gt3", "racing"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Brand", value: "Ferrari" },
      { name: "Series", value: "Speed Machines" },
    ],
    features: ["Official Ferrari licensing", "Race livery tampo"],
    shippingInfo: "Premium padded packaging.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 19,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-porsche-911-gt3-basic-sk-12",
    title: "Hot Wheels Porsche 911 GT3 RS — White",
    description: "<p>Porsche 911 GT3 RS in white with distinctive GT3 RS wing. Official Porsche licensed. One of the cleanest castings in the current lineup.</p>",
    slug: "product-hw-porsche-911-gt3-rs-white",
    category: "category-hw-basic-cars",
    subcategory: "Supercars",
    brand: "Hot Wheels",
    price: 279,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("hw-porsche-911"),
    images: [img("hw-porsche-911")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "porsche", "911", "gt3", "rs"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Brand", value: "Porsche" },
    ],
    features: ["Giant rear wing", "GT3 RS badging"],
    shippingInfo: "Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 10,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-hw-bmw-m3-e30-basic-sk-13",
    title: "Hot Wheels BMW M3 E30 — Touring Car (Red)",
    description: "<p>The iconic BMW E30 M3 in touring car spec — red with white BBS-style wheels. One of the most wanted JDM/Euro castings from Hot Wheels.</p>",
    slug: "product-hw-bmw-m3-e30-touring-red",
    category: "category-hw-basic-cars",
    subcategory: "Euro",
    brand: "Hot Wheels",
    price: 279,
    currency: _CURRENCY,
    stockQuantity: 9,
    availableQuantity: 7,
    mainImage: img("hw-bmw-e30"),
    images: [img("hw-bmw-e30")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "bmw", "m3", "e30", "touring", "euro"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Year", value: "1987" },
      { name: "Series", value: "Car Culture Boulevard" },
    ],
    features: ["BBS-style wheels", "Race livery tampo"],
    shippingInfo: "Premium padded box.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(25),
    avgRating: 4.9,
    reviewCount: 27,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },

  {
    id: "product-hw-subaru-wrx-sti-basic-sk-14",
    title: "Hot Wheels Subaru WRX STI — Rally Edition (Blue)",
    description: "<p>Subaru WRX STI in iconic blue with rally decals. Full rally livery tampo with WRC mudflaps. Real Riders rubber tyres included.</p>",
    slug: "product-hw-subaru-wrx-sti-rally-blue",
    category: "category-hw-basic-cars",
    subcategory: "JDM",
    brand: "Hot Wheels",
    price: 319,
    currency: _CURRENCY,
    stockQuantity: 11,
    availableQuantity: 9,
    mainImage: img("hw-subaru-wrx"),
    images: [img("hw-subaru-wrx")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "subaru", "wrx", "sti", "rally", "wrc"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Car Culture Rally Legends" },
      { name: "Wheels", value: "Real Riders rubber" },
    ],
    features: ["Full rally livery tampo", "Real rubber tyres"],
    shippingInfo: "Premium padded shipping.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 16,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-datsun-240z-classic-basic-sk-15",
    title: "Hot Wheels Datsun 240Z — JDM Classic (Orange)",
    description: "<p>The timeless Datsun 240Z in classic orange. A beloved JDM grand tourer that defined a generation. This casting is one of Hot Wheels' most lauded.</p>",
    slug: "product-hw-datsun-240z-jdm-orange",
    category: "category-hw-basic-cars",
    subcategory: "JDM",
    brand: "Hot Wheels",
    price: 249,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 13,
    mainImage: img("hw-datsun-240z"),
    images: [img("hw-datsun-240z")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "datsun", "240z", "jdm", "classic", "s30"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Year", value: "1970" },
      { name: "Origin", value: "Japan" },
    ],
    features: ["Classic Z profile", "Period-correct tampo"],
    shippingInfo: "Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 12,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },

  // ── PREMIUM CARS (10) ─────────────────────────────────────────────────────

  {
    id: "product-hw-car-culture-boulevard-pack-premium-sk-16",
    title: "Hot Wheels Car Culture Boulevard — Wave 5 (5-pack)",
    description: "<p>Hot Wheels Car Culture Boulevard Wave 5 — premium 5-car assortment featuring Real Riders rubber tyres and premium packaging. Includes BMW 2002, Honda S2000, Mini Cooper, Mazda MX-5, and Alfa Romeo Spider.</p>",
    slug: "product-hw-car-culture-boulevard-wave5-5pack",
    category: "category-hw-premium",
    subcategory: "Car Culture",
    brand: "Hot Wheels",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 6,
    mainImage: img("hw-boulevard-5pack"),
    images: [img("hw-boulevard-5pack"), img("hw-boulevard-2")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "car culture", "boulevard", "premium", "5-pack", "real riders"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Car Culture Boulevard" },
      { name: "Wheels", value: "Real Riders rubber" },
      { name: "Count", value: "5 cars" },
    ],
    features: ["Real rubber tyres on all 5 cars", "Premium card packaging", "Collector-grade details"],
    shippingInfo: "Boxed in rigid carton for protection.",
    returnPolicy: "10-day returns for sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 99,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.9,
    reviewCount: 38,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-japan-historics-3-premium-sk-17",
    title: "Hot Wheels Car Culture Japan Historics 3 (5-pack)",
    description: "<p>Car Culture Japan Historics 3 — 5 iconic Japanese cars from the 70s and 80s. Features Mazda Cosmo, Honda N600, Toyota Celica, Datsun 510, and Nissan Skyline C210. All with Real Riders rubber tyres.</p>",
    slug: "product-hw-car-culture-japan-historics-3-5pack",
    category: "category-hw-premium",
    subcategory: "Car Culture",
    brand: "Hot Wheels",
    price: 2799,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 4,
    mainImage: img("hw-japan-historics"),
    images: [img("hw-japan-historics")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "car culture", "japan historics", "jdm", "premium"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Car Culture Japan Historics 3" },
      { name: "Wheels", value: "Real Riders" },
      { name: "Count", value: "5 cars" },
    ],
    features: ["5 iconic JDM models", "Real Riders tyres", "Premium sealed packaging"],
    shippingInfo: "Rigid box, premium shipping.",
    returnPolicy: "10-day sealed returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 99,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 45,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-hw-pop-culture-tmnt-5pack-premium-sk-18",
    title: "Hot Wheels Pop Culture TMNT Ninja Turtles 5-pack",
    description: "<p>Hot Wheels meets the Teenage Mutant Ninja Turtles! 5 unique cars themed after Leonardo, Donatello, Raphael, Michelangelo, and Master Splinter. A perfect collector crossover.</p>",
    slug: "product-hw-pop-culture-tmnt-5pack",
    category: "category-hw-premium",
    subcategory: "Pop Culture",
    brand: "Hot Wheels",
    price: 2999,
    currency: _CURRENCY,
    stockQuantity: 7,
    availableQuantity: 5,
    mainImage: img("hw-tmnt-pack"),
    images: [img("hw-tmnt-pack")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "tmnt", "ninja turtles", "pop culture", "collector"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Pop Culture TMNT" },
      { name: "Count", value: "5 cars" },
    ],
    features: ["Themed TMNT graphics", "5 unique character cars", "Gift-ready packaging"],
    shippingInfo: "Gift-boxed packaging.",
    returnPolicy: "10-day returns for sealed items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 29,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-hw-nostalgia-mcdonalds-5pack-premium-sk-19",
    title: "Hot Wheels Pop Culture McDonald's 5-pack",
    description: "<p>Hot Wheels Ã— McDonald's crossover pack. 5 cars dressed in iconic McDonald's livery including the Arches Hauler, Happy Meal Bus, and more. A nostalgia bomb for collectors.</p>",
    slug: "product-hw-pop-culture-mcdonalds-5pack",
    category: "category-hw-premium",
    subcategory: "Pop Culture",
    brand: "Hot Wheels",
    price: 2799,
    currency: _CURRENCY,
    stockQuantity: 6,
    availableQuantity: 4,
    mainImage: img("hw-mcdonalds-pack"),
    images: [img("hw-mcdonalds-pack")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "mcdonalds", "pop culture", "nostalgia", "collector pack"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Pop Culture McDonald's" },
      { name: "Count", value: "5 cars" },
    ],
    features: ["Official McDonald's licensing", "5 unique liveries"],
    shippingInfo: "Gift-boxed.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 17,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-hw-real-riders-trucks-pack-premium-sk-20",
    title: "Hot Wheels Real Riders Trucks Series — Wave 1 (5-pack)",
    description: "<p>5 premium 1:64 scale trucks with Real Riders rubber tyres. Includes Chevy Silverado, Ford F-150 Raptor, Ram 1500 TRX, Toyota Tundra, and GMC Sierra. Off-road details throughout.</p>",
    slug: "product-hw-real-riders-trucks-series-wave1",
    category: "category-hw-premium",
    subcategory: "Real Riders",
    brand: "Hot Wheels",
    price: 3299,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 3,
    mainImage: img("hw-trucks-pack"),
    images: [img("hw-trucks-pack")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "trucks", "real riders", "off-road", "premium"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Real Riders Trucks" },
      { name: "Wheels", value: "Real Riders" },
    ],
    features: ["5 premium truck castings", "Real Riders rubber tyres", "Off-road detail tampos"],
    shippingInfo: "Rigid box nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 21,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(7),
  },

  // ── TRACK SETS (5) ────────────────────────────────────────────────────────

  {
    id: "product-hw-loop-launch-track-set-sk-21",
    title: "Hot Wheels Loop & Launch Track Set — Triple Loop",
    description: "<p>Three vertigo-inducing loops in one set! Launcher-powered track with triple loop, crash zone, and finish line. Works with all standard Hot Wheels mainline cars. Recommended age 5+.</p>",
    slug: "product-hw-loop-launch-triple-loop-track-set",
    category: "category-hw-track-sets",
    subcategory: "Track Sets",
    brand: "Hot Wheels",
    price: 1799,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("hw-loop-track"),
    images: [img("hw-loop-track"), img("hw-loop-track-2")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "track set", "loop", "triple loop", "playset"],
    specifications: [
      { name: "Track Length", value: "~3.5 m" },
      { name: "Loops", value: "3" },
      { name: "Compatible Cars", value: "All standard Hot Wheels 1:64" },
      { name: "Includes", value: "1 car" },
      { name: "Age", value: "5+" },
    ],
    features: ["Triple loop system", "Speed launcher included", "Crash-zone finale"],
    shippingInfo: "Boxed in manufacturer packaging.",
    returnPolicy: "10-day returns for damaged/defective items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 33,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(8),
  },

  {
    id: "product-hw-city-ultimate-garage-track-sk-22",
    title: "Hot Wheels City Ultimate Garage — 5-Level Playset",
    description: "<p>The ultimate Hot Wheels garage! 5-level parking structure with loop, elevator, car wash, and service station. Stores over 90 cars. A centrepiece for any collection or playroom.</p>",
    slug: "product-hw-city-ultimate-garage-5-level",
    category: "category-hw-track-sets",
    subcategory: "Playsets",
    brand: "Hot Wheels",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 4,
    mainImage: img("hw-ultimate-garage"),
    images: [img("hw-ultimate-garage")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "garage", "playset", "city", "ultimate garage"],
    specifications: [
      { name: "Levels", value: "5" },
      { name: "Car Capacity", value: "90+ cars" },
      { name: "Height", value: "~60 cm" },
      { name: "Includes", value: "2 cars + accessories" },
    ],
    features: ["5-level structure", "Working elevator", "Car wash feature", "Gas station"],
    shippingInfo: "Large box. Nationwide delivery.",
    returnPolicy: "7-day returns for sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 149,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.7,
    reviewCount: 42,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-hw-monster-trucks-jump-track-sk-23",
    title: "Hot Wheels Monster Trucks Jump Track — Epic Crash",
    description: "<p>Monster Trucks themed jump and crash track. Launch your 1:64 monster truck over cars and obstacles, smash the crash zone, then do it all again. Includes 1 Monster Truck and 2 crash cars.</p>",
    slug: "product-hw-monster-trucks-jump-crash-track",
    category: "category-hw-track-sets",
    subcategory: "Monster Trucks",
    brand: "Hot Wheels",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 7,
    mainImage: img("hw-monster-jump"),
    images: [img("hw-monster-jump")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "monster trucks", "jump", "crash", "track"],
    specifications: [
      { name: "Compatible", value: "Hot Wheels Monster Trucks 1:64" },
      { name: "Includes", value: "1 Monster Truck + 2 cars" },
    ],
    features: ["Jump ramp", "Crash zone", "Monster Truck included"],
    shippingInfo: "Boxed with padding.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.4,
    reviewCount: 18,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(9),
  },

  {
    id: "product-hw-mega-hauler-truck-track-sk-24",
    title: "Hot Wheels Mega Hauler Transport Truck",
    description: "<p>Massive die-cast and plastic semi-truck that carries 25 Hot Wheels cars. Includes ramp for easy loading and unloading. Perfect for collectors who need mobile storage.</p>",
    slug: "product-hw-mega-hauler-transport-truck",
    category: "category-hw-track-sets",
    subcategory: "Playsets",
    brand: "Hot Wheels",
    price: 1999,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("hw-mega-hauler"),
    images: [img("hw-mega-hauler")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "hauler", "truck", "transport", "storage"],
    specifications: [
      { name: "Car Capacity", value: "25 cars" },
      { name: "Includes", value: "1 car" },
    ],
    features: ["25-car capacity", "Loading ramp", "Die-cast cab"],
    shippingInfo: "Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 25,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
  },

  {
    id: "product-hw-racing-circuit-10pack-sk-25",
    title: "Hot Wheels Racing Circuit — 10-car Collector Pack",
    description: "<p>10 racing-themed Hot Wheels cars in collector blister packaging. Mix of Formula-style, GT racers, and touring cars — all with racing liveries. Great value collector set.</p>",
    slug: "product-hw-racing-circuit-10car-pack",
    category: "category-hw-track-sets",
    subcategory: "Collector Sets",
    brand: "Hot Wheels",
    price: 1599,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("hw-racing-10pack"),
    images: [img("hw-racing-10pack")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "racing", "10-pack", "collector", "assorted"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Count", value: "10 cars" },
      { name: "Series", value: "Racing Circuit" },
    ],
    features: ["10 racing-livery cars", "Collector blister packaging"],
    shippingInfo: "Boxed for protection.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.3,
    reviewCount: 14,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(11),
  },

  // ── TREASURE HUNT (5) ─────────────────────────────────────────────────────

  {
    id: "product-hw-th-charger-orange-th-sk-26",
    title: "Hot Wheels Treasure Hunt Dodge Charger R/T (2024 #TH1)",
    description: "<p>Official 2024 Treasure Hunt — Dodge Charger R/T with the distinctive TH logo, green flame tampo, and specialised Real Riders tyres. Much harder to find than mainline. Original blister card, unopened.</p>",
    slug: "product-hw-treasure-hunt-dodge-charger-rt-2024",
    category: "category-hw-treasure-hunt",
    subcategory: "Treasure Hunt",
    brand: "Hot Wheels",
    price: 1299,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 2,
    mainImage: img("hw-th-charger"),
    images: [img("hw-th-charger")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "treasure hunt", "dodge charger", "th", "rare"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "2024 Treasure Hunt" },
      { name: "Wheels", value: "Real Riders" },
      { name: "Condition", value: "Sealed card" },
    ],
    features: ["Official TH marking", "Green flame tampo", "Real Riders rubber tyres"],
    shippingInfo: "Hard case protected shipping.",
    returnPolicy: "No returns on sealed collectibles.",
    condition: "new",
    insurance: true,
    insuranceCost: 49,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    avgRating: 4.8,
    reviewCount: 9,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-th-shelby-gt500-th-sk-27",
    title: "Hot Wheels Treasure Hunt Ford Shelby GT500 (2024 #TH7)",
    description: "<p>2024 Treasure Hunt Ford Shelby GT500 with TH script, specialised wheels, and Shelby GT500 livery tampo. Hunted in stores worldwide — authentic card, acquired directly from Case C assortment.</p>",
    slug: "product-hw-treasure-hunt-shelby-gt500-2024",
    category: "category-hw-treasure-hunt",
    subcategory: "Treasure Hunt",
    brand: "Hot Wheels",
    price: 1499,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 2,
    mainImage: img("hw-th-gt500"),
    images: [img("hw-th-gt500")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "treasure hunt", "shelby", "gt500", "th", "rare"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "2024 Treasure Hunt" },
    ],
    features: ["TH marking with Shelby branding", "Specialised wheels"],
    shippingInfo: "Rigid protective packaging.",
    returnPolicy: "No returns on sealed collectibles.",
    condition: "new",
    insurance: true,
    insuranceCost: 49,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 7,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-th-bmw-m5-th-sk-28",
    title: "Hot Wheels Treasure Hunt BMW M5 E60 (2024 #TH12)",
    description: "<p>2024 Treasure Hunt BMW M5 E60 — a collector holy grail for BMW fans. TH logo, Real Riders, and authentic M-stripe tampo. Stored sealed since case opening.</p>",
    slug: "product-hw-treasure-hunt-bmw-m5-e60-2024",
    category: "category-hw-treasure-hunt",
    subcategory: "Treasure Hunt",
    brand: "Hot Wheels",
    price: 1799,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 1,
    mainImage: img("hw-th-bmw-m5"),
    images: [img("hw-th-bmw-m5")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "treasure hunt", "bmw", "m5", "e60", "th"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "2024 Treasure Hunt" },
      { name: "Wheels", value: "Real Riders" },
    ],
    features: ["TH marking", "M stripe livery", "Real Riders"],
    shippingInfo: "Hard case + bubble wrap.",
    returnPolicy: "No returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 59,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    avgRating: 5.0,
    reviewCount: 5,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
  },

  {
    id: "product-hw-th-acura-nsx-th-sk-29",
    title: "Hot Wheels Treasure Hunt Acura NSX GT3 (2024 #TH15)",
    description: "<p>Acura NSX GT3 as a 2024 Treasure Hunt. Special blue and yellow livery with TH designation and Real Riders wheels. A much-sought JDM TH.</p>",
    slug: "product-hw-treasure-hunt-acura-nsx-gt3-2024",
    category: "category-hw-treasure-hunt",
    subcategory: "Treasure Hunt",
    brand: "Hot Wheels",
    price: 1599,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("hw-th-nsx"),
    images: [img("hw-th-nsx")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "treasure hunt", "acura", "nsx", "gt3", "th"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "2024 Treasure Hunt" },
    ],
    features: ["TH designation", "NSX GT3 body kit"],
    shippingInfo: "Protected hard case.",
    returnPolicy: "No returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 49,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 4,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-th-porsche-914-th-sk-30",
    title: "Hot Wheels Treasure Hunt Porsche 914 (2024 #TH18)",
    description: "<p>Rare 2024 TH Porsche 914 — a vintage mid-engine Porsche in treasure hunt spec. Includes TH flame graphics and Real Riders. Perfect for Euro-car collectors.</p>",
    slug: "product-hw-treasure-hunt-porsche-914-2024",
    category: "category-hw-treasure-hunt",
    subcategory: "Treasure Hunt",
    brand: "Hot Wheels",
    price: 1399,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 1,
    mainImage: img("hw-th-porsche914"),
    images: [img("hw-th-porsche914")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["hot wheels", "treasure hunt", "porsche", "914", "vintage"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "2024 Treasure Hunt" },
    ],
    features: ["TH flame graphics", "Real Riders"],
    shippingInfo: "Hard case protected.",
    returnPolicy: "No returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 49,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 3,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },

  // ── AUCTIONS (3) ─────────────────────────────────────────────────────────

  {
    id: "auction-hw-sth-gto-judge-70-auction-sk-1",
    title: "AUCTION — Hot Wheels Super Treasure Hunt '70 Pontiac GTO 'The Judge'",
    description: "<p>Extremely rare 2022 Super Treasure Hunt '70 Pontiac GTO The Judge. Spectraflame orange paint, Real Riders premium rubber tyres, and the coveted $TH designation. Only found in 1 of every 72 cases worldwide. Stored sealed since case opening — perfect for grading.</p>",
    slug: "auction-hw-sth-pontiac-gto-judge-2022",
    category: "category-hw-treasure-hunt",
    subcategory: "Super Treasure Hunt",
    brand: "Hot Wheels",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("hw-sth-gto-judge"),
    images: [img("hw-sth-gto-judge"), img("hw-sth-gto-back")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "super treasure hunt", "sth", "pontiac", "gto", "the judge", "rare", "auction"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Type", value: "Super Treasure Hunt ($TH)" },
      { name: "Finish", value: "Spectraflame Orange" },
      { name: "Wheels", value: "Real Riders Premium" },
      { name: "Condition", value: "Sealed Card — Near Mint" },
      { name: "Year", value: "2022 Series" },
    ],
    features: ["Spectraflame metallic finish", "Premium Real Riders rubber tyres", "$TH Super designation", "1 in 72 case rarity"],
    shippingInfo: "Hard acrylic case + insured courier.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 299,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(8),
    startingBid: 4999,
    currentBid: 6500,
    bidCount: 11,
    reservePrice: 7000,
    buyNowPrice: 14999,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: daysAhead(8),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(8),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },

  {
    id: "auction-hw-rlc-twin-mill-redline-auction-sk-2",
    title: "AUCTION — Hot Wheels RLC Exclusive Twin Mill Redline Club",
    description: "<p>Hot Wheels Redline Club (RLC) exclusive Twin Mill — only available to RLC members for a limited window. Red enamel paint with authentic redline wire wheels, metal base, and collector tin packaging. Never opened — original shrink wrap intact.</p>",
    slug: "auction-hw-rlc-twin-mill-redline-club",
    category: "category-hw-premium",
    subcategory: "RLC Exclusive",
    brand: "Hot Wheels",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("hw-rlc-twin-mill"),
    images: [img("hw-rlc-twin-mill")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "rlc", "redline club", "twin mill", "exclusive", "auction"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Redline Club (RLC) Exclusive" },
      { name: "Wheels", value: "Authentic Wire Redlines" },
      { name: "Condition", value: "Factory sealed in tin" },
    ],
    features: ["RLC members-only model", "Authentic redline wire wheels", "Metal base", "Original collector tin"],
    shippingInfo: "Insured courier. Hard case + padded box.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 499,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(5),
    startingBid: 7999,
    currentBid: 9500,
    bidCount: 8,
    reservePrice: 10000,
    buyNowPrice: 19999,
    minBidIncrement: 500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: daysAhead(5),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(5),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
  },

  {
    id: "auction-hw-countach-118-scale-auction-sk-3",
    title: "AUCTION — Hot Wheels Lamborghini Countach 1:18 Elite Edition",
    description: "<p>Ultra-rare Hot Wheels 1:18 Elite Edition Lamborghini Countach LP5000S QV in Bianco Polo White. Full die-cast metal body with opening doors, hood, and engine cover. Limited to 2,500 units worldwide. Certificate of authenticity included.</p>",
    slug: "auction-hw-lamborghini-countach-118-elite",
    category: "category-hw-premium",
    subcategory: "Elite 1:18",
    brand: "Hot Wheels",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("hw-countach-118"),
    images: [img("hw-countach-118")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "lamborghini", "countach", "1:18", "elite", "auction", "limited"],
    specifications: [
      { name: "Scale", value: "1:18" },
      { name: "Series", value: "Elite Edition" },
      { name: "Material", value: "Full die-cast metal" },
      { name: "Limited Edition", value: "2,500 units worldwide" },
      { name: "Opening Parts", value: "Doors, Hood, Engine Cover" },
    ],
    features: ["Full die-cast 1:18 scale", "Opening doors, hood and engine cover", "Certificate of authenticity", "Display base included"],
    shippingInfo: "Insured heavyweight courier. Rigid outer box + foam interior.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 799,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(10),
    startingBid: 14999,
    currentBid: 18500,
    bidCount: 15,
    reservePrice: 20000,
    buyNowPrice: 34999,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: daysAhead(10),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(10),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },

  // ── PRE-ORDERS (2) ───────────────────────────────────────────────────────

  {
    id: "preorder-hw-car-culture-wave4-2026-sk-1",
    title: "PRE-ORDER — Hot Wheels Car Culture Wave 4 2026 (5-pack)",
    description: "<p>Reserve the highly anticipated Car Culture Wave 4 2026 — featuring 5 premium cars with Real Riders and premium detailing. Exact models TBA; historically Wave 4 features European grand tourers and JDM icons. Pre-order now to guarantee your set at launch price.</p>",
    slug: "preorder-hw-car-culture-wave4-2026",
    category: "category-hw-premium",
    subcategory: "Car Culture",
    brand: "Hot Wheels",
    price: 2999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 43,
    mainImage: img("hw-cc-wave4-preorder"),
    images: [img("hw-cc-wave4-preorder")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "car culture", "pre-order", "2026", "premium", "real riders"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Car Culture Wave 4 2026" },
      { name: "Wheels", value: "Real Riders (expected)" },
      { name: "Count", value: "5 cars" },
      { name: "Expected Delivery", value: "Q3 2026" },
    ],
    features: ["5 premium cars", "Real Riders rubber tyres", "Pre-order launch price guarantee"],
    shippingInfo: "Dispatched on release day. Tracking provided.",
    returnPolicy: "Pre-orders: cancel anytime before dispatch.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(120),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(60),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },

  {
    id: "preorder-hw-legends-tour-winner-2026-sk-2",
    title: "PRE-ORDER — Hot Wheels Legends Tour 2026 Winner Edition",
    description: "<p>The Hot Wheels Legends Tour crowns the best modified car in India each year and immortalises it as a 1:64 die-cast. Pre-order the 2026 Indian Legends Tour winner — model to be announced after the tour finale. Previous winners have been Bajaj, Ambassador, and Premier Padmini customs.</p>",
    slug: "preorder-hw-legends-tour-india-winner-2026",
    category: "category-hw-premium",
    subcategory: "Legends Tour",
    brand: "Hot Wheels",
    price: 3499,
    currency: _CURRENCY,
    stockQuantity: 100,
    availableQuantity: 87,
    mainImage: img("hw-legends-tour"),
    images: [img("hw-legends-tour")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["hot wheels", "legends tour", "india", "pre-order", "custom", "winner"],
    specifications: [
      { name: "Scale", value: "1:64" },
      { name: "Series", value: "Legends Tour India 2026" },
      { name: "Model", value: "TBA — 2026 Tour Winner" },
      { name: "Certificate", value: "Included" },
    ],
    features: ["Limited to 5,000 units", "Certificate of authenticity", "Tour winner story booklet"],
    shippingInfo: "Special edition packaging. Dispatched upon release.",
    returnPolicy: "Pre-orders: cancel before dispatch.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(180),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(90),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },

  // ── ADDITIONAL MAINLINE (16 more) ─────────────────────────────────────────

  {
    id: "product-hw-dodge-challenger-hellcat-sk-36",
    title: "Hot Wheels Dodge Challenger SRT Hellcat — Mainline (Purple)",
    slug: "product-hw-dodge-challenger-srt-hellcat-purple",
    description: "<p>Dodge Challenger SRT Hellcat in Hot Wheels Mainline — 707HP muscle car in deep purple with aggressive tampo. A crowd favourite for American muscle collectors.</p>",
    category: "category-hw-basic-cars", subcategory: "American Muscle", brand: "Hot Wheels",
    price: 199, currency: _CURRENCY, stockQuantity: 28, availableQuantity: 22,
    mainImage: img("hw-challenger-hellcat-purple"), images: [img("hw-challenger-hellcat-purple")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "dodge challenger", "hellcat", "purple", "mainline"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Mainline" }],
    features: ["707HP Hellcat tampo", "Purple metallic finish", "Real Riders compatible"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.5, reviewCount: 19, createdAt: daysAgo(20), updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-ford-gt40-le-mans-sk-37",
    title: "Hot Wheels Ford GT40 Le Mans 1966 — Car Culture",
    slug: "product-hw-ford-gt40-lemans-1966-car-culture",
    description: "<p>Ford GT40 from the 1966 Le Mans — the car that beat Ferrari. Car Culture premium series with Real Riders tyres and detailed livery. Gulf Oil racing colours.</p>",
    category: "category-hw-premium", subcategory: "Car Culture", brand: "Hot Wheels",
    price: 699, currency: _CURRENCY, stockQuantity: 18, availableQuantity: 14,
    mainImage: img("hw-gt40-lemans"), images: [img("hw-gt40-lemans")],
    status: "published", ...SK, featured: true, tags: ["hot wheels", "ford gt40", "le mans", "1966", "car culture", "gulf oil"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Car Culture" }, { name: "Tyres", value: "Real Riders" }],
    features: ["Real Riders tyres", "Gulf Oil livery", "Detailed engine bay"], shippingInfo: "Blister pack protection.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.8, reviewCount: 31, createdAt: daysAgo(25), updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-lamborghini-countach-white-sk-38",
    title: "Hot Wheels Lamborghini Countach LP400S — Mainline (White)",
    slug: "product-hw-lamborghini-countach-lp400s-white",
    description: "<p>Lamborghini Countach LP400S in pearl white — the poster car of the 80s in Hot Wheels scale. Mainline series. Opening scissor doors modelled in the tampo art.</p>",
    category: "category-hw-basic-cars", subcategory: "Supercars", brand: "Hot Wheels",
    price: 199, currency: _CURRENCY, stockQuantity: 25, availableQuantity: 21,
    mainImage: img("hw-countach-white"), images: [img("hw-countach-white")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "lamborghini", "countach", "lp400s", "white", "mainline"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Mainline" }],
    features: ["Pearl white Countach", "LP400S livery", "Iconic 80s supercar"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.7, reviewCount: 23, createdAt: daysAgo(18), updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-porsche-911-gt3-rs-sk-39",
    title: "Hot Wheels Porsche 911 GT3 RS — Car Culture (Orange)",
    slug: "product-hw-porsche-911-gt3-rs-orange-car-culture",
    description: "<p>Porsche 911 GT3 RS in hot orange — Car Culture premium with Real Riders and detailed GT3 RS aero. Black cage interior detail. The benchmark track Porsche in 1:64 scale.</p>",
    category: "category-hw-premium", subcategory: "Car Culture", brand: "Hot Wheels",
    price: 699, currency: _CURRENCY, stockQuantity: 20, availableQuantity: 16,
    mainImage: img("hw-porsche-911-gt3-rs"), images: [img("hw-porsche-911-gt3-rs")],
    status: "published", ...SK, featured: true, tags: ["hot wheels", "porsche", "911 gt3 rs", "orange", "car culture", "real riders"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Car Culture" }, { name: "Tyres", value: "Real Riders" }],
    features: ["Real Riders tyres", "GT3 RS orange livery", "Cage interior detail"], shippingInfo: "Blister pack.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.8, reviewCount: 28, createdAt: daysAgo(22), updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-nissan-gtr-r35-blue-sk-40",
    title: "Hot Wheels Nissan GT-R R35 — Premium (Pearl Blue)",
    slug: "product-hw-nissan-gtr-r35-pearl-blue-premium",
    description: "<p>Nissan GT-R R35 in pearl blue — premium Hot Wheels with die-cast body and Real Riders. Godzilla in miniature. Detailed front bumper and rear diffuser aero kit.</p>",
    category: "category-hw-premium", subcategory: "JDM", brand: "Hot Wheels",
    price: 499, currency: _CURRENCY, stockQuantity: 22, availableQuantity: 18,
    mainImage: img("hw-nissan-gtr-r35"), images: [img("hw-nissan-gtr-r35")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "nissan gt-r", "r35", "pearl blue", "jdm", "premium"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Premium" }],
    features: ["Pearl blue GT-R", "Real Riders tyres", "Aero kit detail"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.6, reviewCount: 17, createdAt: daysAgo(28), updatedAt: daysAgo(4),
  },

  {
    id: "product-hw-bmw-m3-e30-white-sk-41",
    title: "Hot Wheels BMW M3 E30 — Car Culture (White DTM)",
    slug: "product-hw-bmw-m3-e30-white-dtm-car-culture",
    description: "<p>BMW M3 E30 in white DTM racing livery — Car Culture Touring Cars series. Real Riders, accurate DTM wing, and sponsor tampo. The original touring car legend.</p>",
    category: "category-hw-premium", subcategory: "Car Culture", brand: "Hot Wheels",
    price: 699, currency: _CURRENCY, stockQuantity: 15, availableQuantity: 12,
    mainImage: img("hw-bmw-m3-e30-white"), images: [img("hw-bmw-m3-e30-white")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "bmw m3", "e30", "dtm", "white", "car culture", "touring"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Car Culture Touring" }, { name: "Tyres", value: "Real Riders" }],
    features: ["DTM livery", "E30 wing detail", "Real Riders"], shippingInfo: "Blister pack.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.7, reviewCount: 21, createdAt: daysAgo(30), updatedAt: daysAgo(5),
  },

  {
    id: "product-hw-mazda-rx7-fd-red-sk-42",
    title: "Hot Wheels Mazda RX-7 FD — Mainline (Red)",
    slug: "product-hw-mazda-rx7-fd-red-mainline",
    description: "<p>Mazda RX-7 FD in vivid red — the rotary icon in Hot Wheels scale. One of the most beloved JDM cars in the Hot Wheels lineup. Great for JDM collections and track play.</p>",
    category: "category-hw-basic-cars", subcategory: "JDM", brand: "Hot Wheels",
    price: 199, currency: _CURRENCY, stockQuantity: 30, availableQuantity: 26,
    mainImage: img("hw-rx7-fd-red"), images: [img("hw-rx7-fd-red")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "mazda", "rx7", "fd", "red", "jdm", "mainline"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Mainline" }],
    features: ["RX-7 FD body", "Red finish", "JDM classic"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.7, reviewCount: 34, createdAt: daysAgo(15), updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-toyota-supra-a90-orange-sk-43",
    title: "Hot Wheels Toyota GR Supra A90 — Mainline (Orange)",
    slug: "product-hw-toyota-gr-supra-a90-orange-mainline",
    description: "<p>Toyota GR Supra A90 in vivid orange — the new-generation Supra in Hot Wheels. Mainline series with accurate body kit and twin exhaust detail. Perfect for modern JDM shelf.</p>",
    category: "category-hw-basic-cars", subcategory: "JDM", brand: "Hot Wheels",
    price: 199, currency: _CURRENCY, stockQuantity: 28, availableQuantity: 25,
    mainImage: img("hw-supra-a90-orange"), images: [img("hw-supra-a90-orange")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "toyota", "supra", "a90", "gr supra", "orange", "jdm"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Mainline" }],
    features: ["GR Supra A90 body", "Orange finish", "Twin exhaust detail"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.6, reviewCount: 26, createdAt: daysAgo(12), updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-f1-mercedes-w11-sk-44",
    title: "Hot Wheels Mercedes F1 W11 — Collector (2020 Lewis Hamilton Championship)",
    slug: "product-hw-f1-mercedes-w11-2020-hamilton",
    description: "<p>Mercedes F1 W11 from Lewis Hamilton's 2020 World Championship — 7-time champion's car in 1:64 premium. Silver arrows livery with BLM livery version. Detailed front wing and Halo. Limited collector edition.</p>",
    category: "category-hw-premium", subcategory: "F1", brand: "Hot Wheels",
    price: 899, currency: _CURRENCY, stockQuantity: 12, availableQuantity: 9,
    mainImage: img("hw-f1-mercedes-w11"), images: [img("hw-f1-mercedes-w11")],
    status: "published", ...SK, featured: true, tags: ["hot wheels", "f1", "mercedes", "w11", "lewis hamilton", "2020", "premium"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Collector" }, { name: "Year", value: "2020" }],
    features: ["2020 Championship livery", "BLM black livery", "Halo detail", "Real Riders"], shippingInfo: "Blister pack protection.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.9, reviewCount: 45, createdAt: daysAgo(40), updatedAt: daysAgo(4),
  },

  {
    id: "product-hw-batmobile-89-tim-burton-sk-45",
    title: "Hot Wheels Batman Batmobile 1989 — Tim Burton Film Car",
    slug: "product-hw-batmobile-1989-tim-burton-batman",
    description: "<p>Tim Burton's 1989 Batman Batmobile in Hot Wheels — the most iconic movie car ever. Die-cast body with jet afterburner and bat fin detail. Entertainment series. Black matte finish with chrome trim.</p>",
    category: "category-hw-entertainment", subcategory: "Movie Cars", brand: "Hot Wheels",
    price: 499, currency: _CURRENCY, stockQuantity: 20, availableQuantity: 16,
    mainImage: img("hw-batmobile-89"), images: [img("hw-batmobile-89")],
    status: "published", ...SK, featured: true, tags: ["hot wheels", "batman", "batmobile", "1989", "tim burton", "entertainment"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Entertainment" }],
    features: ["1989 Burton Batmobile", "Black matte finish", "Bat fin detail", "Afterburner sculpt"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.8, reviewCount: 39, createdAt: daysAgo(35), updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-dodge-viper-gts-r-sk-46",
    title: "Hot Wheels Dodge Viper GTS-R — Racing (Blue/White Stripe)",
    slug: "product-hw-dodge-viper-gts-r-racing-blue-white",
    description: "<p>Dodge Viper GTS-R in classic blue with white racing stripe — Car Culture track version. Real Riders with racing slick profile. GTS-R aero bodykit. The racing icon that conquered Le Mans GT class.</p>",
    category: "category-hw-premium", subcategory: "Car Culture", brand: "Hot Wheels",
    price: 699, currency: _CURRENCY, stockQuantity: 18, availableQuantity: 14,
    mainImage: img("hw-viper-gts-r"), images: [img("hw-viper-gts-r")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "dodge viper", "gts-r", "racing", "blue white", "le mans"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Car Culture" }, { name: "Tyres", value: "Real Riders" }],
    features: ["GTS-R blue/white livery", "Real Riders slicks", "GT racing aero"], shippingInfo: "Blister pack.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.6, reviewCount: 14, createdAt: daysAgo(28), updatedAt: daysAgo(5),
  },

  {
    id: "product-hw-mclaren-p1-yellow-sk-47",
    title: "Hot Wheels McLaren P1 — Mainline (Volcano Yellow)",
    slug: "product-hw-mclaren-p1-volcano-yellow-mainline",
    description: "<p>McLaren P1 in Volcano Yellow — the British hybrid hypercar in Hot Wheels. Mainline series with detailed front splitter and rear diffuser. One of the fastest-selling Hot Wheels in the supercar category.</p>",
    category: "category-hw-basic-cars", subcategory: "Supercars", brand: "Hot Wheels",
    price: 199, currency: _CURRENCY, stockQuantity: 25, availableQuantity: 20,
    mainImage: img("hw-mclaren-p1-yellow"), images: [img("hw-mclaren-p1-yellow")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "mclaren p1", "yellow", "hypercar", "mainline"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Mainline" }],
    features: ["P1 body", "Volcano Yellow", "Detailed diffuser"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.6, reviewCount: 22, createdAt: daysAgo(16), updatedAt: daysAgo(2),
  },

  {
    id: "product-hw-subaru-impreza-wrc-sk-48",
    title: "Hot Wheels Subaru Impreza WRC — Rally (McRae 1997 Livery)",
    slug: "product-hw-subaru-impreza-wrc-mcrae-1997",
    description: "<p>Subaru Impreza WRC in Colin McRae's iconic 1997 livery — blue/gold Subaru rally legend. Car Culture Rally series with Real Riders. One of the most popular rally liveries of all time.</p>",
    category: "category-hw-premium", subcategory: "Rally", brand: "Hot Wheels",
    price: 699, currency: _CURRENCY, stockQuantity: 15, availableQuantity: 11,
    mainImage: img("hw-subaru-impreza-wrc"), images: [img("hw-subaru-impreza-wrc")],
    status: "published", ...SK, featured: true, tags: ["hot wheels", "subaru impreza", "wrc", "rally", "mcrae", "1997", "blue gold"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Car Culture Rally" }, { name: "Tyres", value: "Real Riders" }],
    features: ["McRae 1997 livery", "Real Riders", "WRC bodykit detail"], shippingInfo: "Blister pack.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.8, reviewCount: 29, createdAt: daysAgo(32), updatedAt: daysAgo(4),
  },

  {
    id: "product-hw-honda-nsx-type-r-sk-49",
    title: "Hot Wheels Honda NSX Type R — Premium (Championship White)",
    slug: "product-hw-honda-nsx-type-r-championship-white",
    description: "<p>Honda NSX Type R in Championship White — the lightweight Japanese sports car legend. Premium Hot Wheels with Real Riders and detailed Type R wing. Red tow hook and red badge detail.</p>",
    category: "category-hw-premium", subcategory: "JDM", brand: "Hot Wheels",
    price: 499, currency: _CURRENCY, stockQuantity: 18, availableQuantity: 14,
    mainImage: img("hw-honda-nsx-type-r"), images: [img("hw-honda-nsx-type-r")],
    status: "published", ...SK, featured: false, tags: ["hot wheels", "honda nsx", "type r", "championship white", "jdm", "premium"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Premium" }],
    features: ["Type R white", "Real Riders", "Red tow hook detail"], shippingInfo: "Bubble wrapped.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.7, reviewCount: 19, createdAt: daysAgo(24), updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-delorean-back-future-sk-50",
    title: "Hot Wheels DeLorean Time Machine — Back to the Future (2015 Hover Mode)",
    slug: "product-hw-delorean-back-to-future-2015-hover",
    description: "<p>DeLorean Time Machine in 2015 hover mode from Back to the Future Part II — Entertainment series. Deployed hover wheels, Mr Fusion, and flux capacitor detail. One of the most sought-after entertainment Hot Wheels. Includes display stand for hover effect.</p>",
    category: "category-hw-entertainment", subcategory: "Movie Cars", brand: "Hot Wheels",
    price: 599, currency: _CURRENCY, stockQuantity: 14, availableQuantity: 10,
    mainImage: img("hw-delorean-hover"), images: [img("hw-delorean-hover")],
    status: "published", ...SK, featured: true, tags: ["hot wheels", "delorean", "back to the future", "2015", "hover mode", "entertainment"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Entertainment" }, { name: "Mode", value: "2015 Hover" }],
    features: ["2015 hover wheels deployed", "Mr Fusion detail", "Flux capacitor tampo", "Hover display stand"], shippingInfo: "Blister pack.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.9, reviewCount: 53, createdAt: daysAgo(45), updatedAt: daysAgo(3),
  },

  {
    id: "product-hw-ferrari-sf90-spider-sk-51",
    title: "Hot Wheels Ferrari SF90 Spider — Premium Collector",
    slug: "product-hw-ferrari-sf90-spider-premium",
    description: "<p>Ferrari SF90 Spider in Ferrari rosso red — premium Hot Wheels with Real Riders and detailed PHEV hybrid components visible. One of the most powerful road Ferraris ever made in 1:64 scale.</p>",
    category: "category-hw-premium", subcategory: "Supercars", brand: "Hot Wheels",
    price: 799, currency: _CURRENCY, stockQuantity: 12, availableQuantity: 9,
    mainImage: img("hw-ferrari-sf90-spider"), images: [img("hw-ferrari-sf90-spider")],
    status: "published", ...SK, featured: true, tags: ["hot wheels", "ferrari", "sf90 spider", "premium", "rosso"],
    specifications: [{ name: "Scale", value: "1:64" }, { name: "Series", value: "Premium" }, { name: "Tyres", value: "Real Riders" }],
    features: ["SF90 hybrid detail", "Rosso Ferrari red", "Real Riders", "Spider open roof"], shippingInfo: "Blister pack.", returnPolicy: "10-day returns.",
    condition: "new", insurance: false, shippingPaidBy: "seller", isAuction: false, isPreOrder: false,
    avgRating: 4.8, reviewCount: 24, createdAt: daysAgo(20), updatedAt: daysAgo(2),
  },
];