/**
 * LetItRip Official Store — Products Seed Data
 * Platform-curated multi-franchise listings: graded slabs, sealed bundles, accessories
 * 8 general · 1 auction · 1 pre-order · 1 OOS = 11 total
 * Seller: LetItRip Official Store (letitrip-official) — admin@letitrip.in
 */

import { getDefaultCurrency } from "./seed-market-config";
import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

const LR = {
  storeId: "store-letitrip-official",
  storeName: "LetItRip Official Store",
} as const;

export const letitripOfficialSeedData: Partial<ProductDocument>[] = [

  // ── GRADED SLABS (2) ──────────────────────────────────────────────────────

  {
    id: "product-lr-psa9-charizard-base1-4-official-1",
    title: "Charizard Base Set #4 — PSA 9 MINT Graded Slab",
    description: "<p>PSA 9 MINT Charizard from the original Pokémon Base Set (Unlimited). Centering within PSA grade bands, sharp corners, clean holo surface. Authentication label included. Comes in protective PSA slab box with foam insert.</p>",
    slug: "charizard-base1-4-psa9-mint-graded-slab-official",
    category: "category-pokemon-cards",
    subcategory: "Graded",
    brand: "Pokémon TCG",
    price: 189999,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://images.pokemontcg.io/base1/4_hires.png",
    images: ["https://images.pokemontcg.io/base1/4_hires.png"],
    status: "published",
    ...LR,
    featured: true,
    isPromoted: true,
    promotionEndDate: daysAhead(60),
    tags: ["charizard", "psa9", "graded", "base set", "holo rare", "mint"],
    specifications: [
      { name: "Grade", value: "PSA 9 MINT" },
      { name: "Set", value: "Base Set (Unlimited)" },
      { name: "Card Number", value: "#4/102" },
      { name: "Rarity", value: "Holo Rare" },
    ],
    features: ["PSA 9 MINT grade", "Authentication label", "Foam-protected slab box", "Platform-authenticated"],
    shippingInfo: "Double-sealed with insurance. Nationwide.",
    returnPolicy: "Full refund within 7 days for any authenticity concern.",
    condition: "graded",
    insurance: true,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 5.0,
    reviewCount: 3,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-lr-psa8-mewtwo-base1-10-official-1",
    title: "Mewtwo Base Set #10 — PSA 8 NM-MT Graded Slab",
    description: "<p>PSA 8 NM-MT Mewtwo from the original Pokémon Base Set (Unlimited). Light surface scuff visible under direct light — within PSA 8 tolerances. Psychic holo shimmer fully intact. Perfect centrepiece for a Psychic-type graded binder.</p>",
    slug: "mewtwo-base1-10-psa8-nm-mt-graded-slab-official",
    category: "category-pokemon-cards",
    subcategory: "Graded",
    brand: "Pokémon TCG",
    price: 39999,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://images.pokemontcg.io/base1/10_hires.png",
    images: ["https://images.pokemontcg.io/base1/10_hires.png"],
    status: "published",
    ...LR,
    featured: false,
    tags: ["mewtwo", "psa8", "graded", "base set", "holo rare", "psychic"],
    specifications: [
      { name: "Grade", value: "PSA 8 NM-MT" },
      { name: "Set", value: "Base Set (Unlimited)" },
      { name: "Card Number", value: "#10/102" },
      { name: "Rarity", value: "Holo Rare" },
    ],
    features: ["PSA 8 NM-MT grade", "Authentication label", "Platform-authenticated"],
    shippingInfo: "Double-sealed with insurance. Nationwide.",
    returnPolicy: "Full refund within 7 days for any authenticity concern.",
    condition: "graded",
    insurance: true,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 2,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(3),
  },

  // ── SEALED BUNDLES (2) ────────────────────────────────────────────────────

  {
    id: "product-lr-multi-franchise-collector-bundle-official-1",
    title: "Multi-Franchise Collector Starter Bundle — Pokémon + Hot Wheels + Beyblade",
    description: "<p>The ultimate cross-franchise starter bundle, curated by the LetItRip team. Includes: 1 Pokémon Base Set booster pack (factory sealed), 1 Hot Wheels Car Culture Premium 5-pack (sealed), and 1 Beyblade Burst QuadDrive top + launcher set. All items are factory sealed and authenticated.</p>",
    slug: "multi-franchise-collector-starter-bundle-official",
    category: "category-sealed-products",
    subcategory: "Bundles",
    brand: "LetItRip",
    price: 2999,
    currency: _CURRENCY,
    stockQuantity: 30,
    availableQuantity: 28,
    mainImage: "https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/9/9f/Hot_Wheels_Modellauto.jpg",
    ],
    status: "published",
    ...LR,
    featured: true,
    isPromoted: true,
    promotionEndDate: daysAhead(45),
    tags: ["bundle", "starter", "pokemon", "hot wheels", "beyblade", "sealed", "multi-franchise"],
    specifications: [
      { name: "Contents", value: "1× Pokémon booster pack + 1× HW Car Culture 5-pack + 1× Beyblade set" },
      { name: "Condition", value: "Factory sealed — all items" },
    ],
    features: ["Factory sealed", "Platform authenticated", "3 franchises in 1 box", "Gift-ready packaging"],
    shippingInfo: "Bubble-wrapped box. Nationwide.",
    returnPolicy: "7-day returns on sealed bundles — seal must be intact.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 11,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },

  {
    id: "product-lr-pokemon-base-set-booster-box-official-1",
    title: "Pokémon Base Set Unlimited Booster Box — 36-Pack Sealed",
    description: "<p>Factory-sealed Pokémon Base Set Unlimited 36-booster-pack display box. All 36 packs are original print-run, sealed, and unweighed. Authenticated by the LetItRip grading team. This is the crown jewel of any sealed collection. Sold as-is — the platform does not guarantee specific pulls.</p>",
    slug: "pokemon-base-set-unlimited-booster-box-36-pack-sealed-official",
    category: "category-sealed-products",
    subcategory: "Booster Boxes",
    brand: "Pokémon TCG",
    price: 349999,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 2,
    mainImage: "https://images.pokemontcg.io/base1/4_hires.png",
    images: ["https://images.pokemontcg.io/base1/4_hires.png"],
    status: "published",
    ...LR,
    featured: true,
    tags: ["booster box", "base set", "sealed", "unlimited", "36 packs", "investment"],
    specifications: [
      { name: "Set", value: "Base Set (Unlimited)" },
      { name: "Packs", value: "36 booster packs" },
      { name: "Condition", value: "Factory sealed, authenticated" },
    ],
    features: ["Factory sealed", "Authenticated by LetItRip team", "Unweighed packs", "Investment-grade"],
    shippingInfo: "Double-boxed with corner protectors and full insurance. Nationwide.",
    returnPolicy: "7-day returns — seal must be intact for return eligibility.",
    condition: "new",
    insurance: true,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 5.0,
    reviewCount: 1,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(5),
  },

  // ── ACCESSORIES (3) ───────────────────────────────────────────────────────

  {
    id: "product-lr-premium-toploader-bundle-100pk-official-1",
    title: "Premium Hard Toploaders 100-Pack — 35PT Standard",
    description: "<p>LetItRip Official premium 35-point rigid toploaders — the standard for PSA/BGS submission and everyday storage. Crystal-clear UV-resistant PVC. Snug fit for standard Pokémon, Magic, and sports cards. Anti-static interior prevents surface scuffs.</p>",
    slug: "premium-toploaders-100-pack-35pt-standard-official",
    category: "category-accessories",
    subcategory: "Toploaders",
    brand: "LetItRip",
    price: 449,
    currency: _CURRENCY,
    stockQuantity: 200,
    availableQuantity: 195,
    mainImage: "https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg"],
    status: "published",
    ...LR,
    featured: false,
    tags: ["toploaders", "35pt", "card protection", "accessories", "storage", "psa submission"],
    specifications: [
      { name: "Thickness", value: "35 point (standard)" },
      { name: "Quantity", value: "100 per pack" },
      { name: "Material", value: "UV-resistant PVC" },
      { name: "Fit", value: "Standard cards (63×88 mm)" },
    ],
    features: ["Crystal-clear UV-resistant PVC", "Anti-static interior", "PSA/BGS submission safe", "Standard card fit"],
    shippingInfo: "Padded envelope. Nationwide.",
    returnPolicy: "10-day returns on sealed packs.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 34,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-lr-9-pocket-premium-binder-400-official-1",
    title: "Premium 9-Pocket Card Binder — 400 Cards, Side-Load",
    description: "<p>LetItRip Official 400-card side-loading 9-pocket binder with padded hardcover, elastic strap closure, and label pockets on each page. No-PVC, acid-free pages protect your collection. Compatible with Pokémon, Magic, and all standard trading cards. Available in black.</p>",
    slug: "premium-9-pocket-card-binder-400-side-load-official",
    category: "category-accessories",
    subcategory: "Binders",
    brand: "LetItRip",
    price: 699,
    currency: _CURRENCY,
    stockQuantity: 80,
    availableQuantity: 76,
    mainImage: "https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg"],
    status: "published",
    ...LR,
    featured: false,
    tags: ["binder", "9 pocket", "card storage", "400 cards", "side-load", "accessories"],
    specifications: [
      { name: "Capacity", value: "400 cards (9-pocket pages)" },
      { name: "Loading Style", value: "Side-load (no drop-out)" },
      { name: "Pages", value: "No-PVC, acid-free" },
      { name: "Closure", value: "Elastic strap" },
    ],
    features: ["Side-load pages", "No-PVC acid-free", "Padded hardcover", "Label pockets on each page"],
    shippingInfo: "Bubble-wrapped. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 18,
    createdAt: daysAgo(110),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-lr-card-sleeves-perfect-fit-200pk-official-1",
    title: "Perfect Fit Inner Sleeves 200-Pack — Crystal Clear",
    description: "<p>LetItRip Official crystal-clear perfect-fit inner sleeves (64×89 mm) — ideal as a double-sleeve inner layer or standalone protection for PSA submissions. Non-glare surface. Fits snugly without air pockets. Pairs with standard outer sleeves.</p>",
    slug: "perfect-fit-inner-sleeves-200-pack-crystal-clear-official",
    category: "category-accessories",
    subcategory: "Sleeves",
    brand: "LetItRip",
    price: 299,
    currency: _CURRENCY,
    stockQuantity: 300,
    availableQuantity: 290,
    mainImage: "https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg",
    images: ["https://upload.wikimedia.org/wikipedia/commons/3/31/Pyrkon_2022_Pokemon_Trading_Card_Game.jpg"],
    status: "published",
    ...LR,
    featured: false,
    tags: ["sleeves", "perfect fit", "inner sleeve", "double sleeve", "psa", "crystal clear"],
    specifications: [
      { name: "Size", value: "64 × 89 mm (perfect fit)" },
      { name: "Quantity", value: "200 per pack" },
      { name: "Surface", value: "Non-glare crystal clear" },
    ],
    features: ["Crystal clear non-glare", "PSA submission compatible", "Double-sleeve inner layer", "Air-free snug fit"],
    shippingInfo: "Padded envelope. Nationwide.",
    returnPolicy: "10-day returns on sealed packs.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 25,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(7),
  },

  // ── AUCTION (1) ───────────────────────────────────────────────────────────

  {
    id: "auction-lr-psa10-pikachu-base1-58-official-auction-1",
    title: "Pikachu Base Set #58 — PSA 10 GEM MINT (AUCTION)",
    description: "<p>Extremely rare PSA 10 GEM MINT Pikachu from Pokémon Base Set (Unlimited). One of only ~230 copies graded PSA 10 worldwide. Perfect centering, flawless corners, and mirror-clean surface. A once-in-a-generation auction from the LetItRip platform collection.</p>",
    slug: "pikachu-base1-58-psa10-gem-mint-auction-official",
    category: "category-pokemon-cards",
    subcategory: "Graded",
    brand: "Pokémon TCG",
    price: 49999,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: "https://images.pokemontcg.io/base1/58_hires.png",
    images: ["https://images.pokemontcg.io/base1/58_hires.png"],
    status: "published",
    ...LR,
    featured: true,
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    tags: ["pikachu", "psa10", "gem mint", "base set", "auction", "graded", "ultra rare"],
    specifications: [
      { name: "Grade", value: "PSA 10 GEM MINT" },
      { name: "Set", value: "Base Set (Unlimited)" },
      { name: "Card Number", value: "#58/102" },
      { name: "Rarity", value: "Common (but PSA 10 is extraordinarily rare)" },
    ],
    features: ["PSA 10 GEM MINT", "~230 copies graded worldwide", "Platform-authenticated", "Secure escrow checkout"],
    shippingInfo: "Insured overnight delivery upon auction close.",
    returnPolicy: "All auction sales final — platform guarantee on authenticity.",
    condition: "graded",
    insurance: true,
    shippingPaidBy: "seller",
    isAuction: true,
    startingBid: 49999,
    auctionEndDate: daysAhead(7),
    isPreOrder: false,
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },

  // ── PRE-ORDER (1) ─────────────────────────────────────────────────────────

  {
    id: "product-lr-pokemon-sv-prismatic-evolutions-box-preorder-official-1",
    title: "Pokémon SV Prismatic Evolutions Elite Trainer Box — Pre-Order",
    description: "<p>Pre-order the upcoming Pokémon Scarlet & Violet Prismatic Evolutions Elite Trainer Box. Includes 9 booster packs, 65 card sleeves (Eevee design), 45 Energy cards, 6 damage-counter dice, and a player's guide. Expected dispatch within 3 days of official India release. Limited allocation — reserve now.</p>",
    slug: "pokemon-sv-prismatic-evolutions-elite-trainer-box-preorder-official",
    category: "category-sealed-products",
    subcategory: "Elite Trainer Box",
    brand: "Pokémon TCG",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage: "https://images.pokemontcg.io/base1/4_hires.png",
    images: ["https://images.pokemontcg.io/base1/4_hires.png"],
    status: "published",
    ...LR,
    featured: false,
    tags: ["pre-order", "prismatic evolutions", "etb", "elite trainer box", "scarlet violet", "sealed"],
    specifications: [
      { name: "Set", value: "Scarlet & Violet — Prismatic Evolutions" },
      { name: "Contents", value: "9 booster packs + accessories" },
      { name: "Sleeve Design", value: "Eevee Prismatic Evolutions" },
    ],
    features: ["9 booster packs", "65 card sleeves", "Damage dice included", "Limited platform allocation"],
    shippingInfo: "Dispatched within 3 days of India release.",
    returnPolicy: "Cancellable before dispatch. No returns on sealed after delivery.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(45),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },

  // ── OUT OF STOCK (1) ─────────────────────────────────────────────────────

  {
    id: "product-lr-psa10-blastoise-base1-2-official-oos-1",
    title: "Blastoise Base Set #2 — PSA 10 GEM MINT (Out of Stock)",
    description: "<p>PSA 10 GEM MINT Blastoise from Pokémon Base Set (Unlimited) — sold out. One of the rarest graded Base Set cards available. Join the waitlist to be notified when stock is sourced again.</p>",
    slug: "blastoise-base1-2-psa10-gem-mint-official-oos",
    category: "category-pokemon-cards",
    subcategory: "Graded",
    brand: "Pokémon TCG",
    price: 249999,
    currency: _CURRENCY,
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage: "https://images.pokemontcg.io/base1/2_hires.png",
    images: ["https://images.pokemontcg.io/base1/2_hires.png"],
    status: "published",
    ...LR,
    featured: false,
    tags: ["blastoise", "psa10", "gem mint", "base set", "graded", "out of stock"],
    specifications: [
      { name: "Grade", value: "PSA 10 GEM MINT" },
      { name: "Set", value: "Base Set (Unlimited)" },
      { name: "Card Number", value: "#2/102" },
    ],
    features: ["PSA 10 GEM MINT", "Platform-authenticated", "Waitlist available"],
    shippingInfo: "Nationwide with full insurance when back in stock.",
    returnPolicy: "7-day returns for authenticity concerns.",
    condition: "graded",
    insurance: true,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 5.0,
    reviewCount: 2,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(10),
  },
];
