/*
 * WHY: Seeds notifications for the Beyblade collectibles marketplace — covers all notification types across 3 users.
 * WHAT: 23 notifications (10 Rehan, 8 Tyson, 5 Admin). Mix of read/unread, all notification types.
 *
 * EXPORTS:
 *   notificationsSeedData — Array of Partial<NotificationDocument> for seed runner
 *
 * @tag domain:notifications
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import type { NotificationDocument } from "../features/admin/schemas";
import { NOTIFICATION_FIELDS } from "../features/admin/schemas";
import { ROUTES } from "../next/routing/route-map";

const NOW = new Date();
const hoursAgo = (n: number) => new Date(NOW.getTime() - n * 3_600_000);
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const notificationsSeedData: Partial<NotificationDocument>[] = [
  // ── Rehan's notifications (10) — buyer-focused ────────────────────────────

  {
    id: "notif-yugi-outbid-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_OUTBID,
    priority: "high",
    title: "You've been outbid!",
    message: "Someone placed a higher bid on Beyblade Original Dragoon Storm. Current bid: ₹4,500.",
    actionUrl: "/auctions/auction-beyblade-original-dragoon-storm",
    actionLabel: "Place New Bid",
    isRead: false,
    relatedId: "auction-beyblade-original-dragoon-storm",
    relatedType: "product",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: "notif-yugi-shipped-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_SHIPPED,
    priority: "normal",
    title: "Your order has shipped!",
    message: "Order #order-1-20260515-abc123 — Beyblade Original Dranzer S is on its way. Track your shipment.",
    actionUrl: "/user/orders/order-1-20260515-abc123",
    actionLabel: "Track Order",
    isRead: false,
    relatedId: "order-1-20260515-abc123",
    relatedType: "order",
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: "notif-yugi-delivered-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_DELIVERED,
    priority: "normal",
    title: "Order delivered!",
    message: "Order #order-2-20260510-def456 has been delivered. Please confirm receipt and leave a review.",
    actionUrl: "/user/orders/order-2-20260510-def456",
    actionLabel: "Confirm & Review",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "order-2-20260510-def456",
    relatedType: "order",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-yugi-price-drop-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRODUCT_AVAILABLE,
    priority: "normal",
    title: "Price drop on your wishlist item!",
    message: "Beyblade Metal Storm Pegasus dropped from ₹1,999 to ₹1,699. Get it before it's gone.",
    actionUrl: "/products/product-beyblade-metal-storm-pegasus",
    actionLabel: "View Product",
    isRead: false,
    relatedId: "product-beyblade-metal-storm-pegasus",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-yugi-auction-won-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_WON,
    priority: "high",
    title: "Congratulations! You won the auction!",
    message: "You won the Beyblade Metal Lightning L-Drago auction for ₹5,200. Complete payment within 48 hours.",
    actionUrl: "/auctions/auction-beyblade-metal-lightning-l-drago",
    actionLabel: "Pay Now",
    isRead: true,
    readAt: daysAgo(3),
    relatedId: "auction-beyblade-metal-lightning-l-drago",
    relatedType: "product",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: "notif-yugi-raffle-win-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "high",
    title: "You won the Original Series Raffle!",
    message: "Congratulations! You've been selected as the winner of the Complete Original Series Collectors Set raffle.",
    actionUrl: "/events/event-won-original-set-raffle",
    actionLabel: "View Details",
    isRead: true,
    readAt: daysAgo(4),
    relatedId: "event-won-original-set-raffle",
    relatedType: "product",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "notif-yugi-review-approved-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REVIEW_APPROVED,
    priority: "low",
    title: "Your review was published",
    message: "Your review for Beyblade Original Dranzer S has been approved and is now live.",
    isRead: true,
    readAt: daysAgo(6),
    relatedId: "review-1",
    relatedType: "review",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
  },
  {
    id: "notif-yugi-welcome-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip, Rehan!",
    message: "Your account is ready. Start browsing verified Beyblade collectibles from sellers across India.",
    actionUrl: String(ROUTES.PUBLIC.PRODUCTS),
    actionLabel: "Start Shopping",
    isRead: true,
    readAt: daysAgo(30),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "notif-yugi-offer-received-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_RECEIVED,
    priority: "normal",
    title: "Counter-offer on your Burst Valkyrie bid",
    message: "Beyblade Arena countered your offer of ₹1,200 with ₹1,450 for Beyblade Burst Valkyrie.",
    actionUrl: "/user/offers",
    actionLabel: "View Offer",
    isRead: false,
    relatedId: "product-beyblade-burst-valkyrie",
    relatedType: "product",
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: "notif-yugi-new-listing-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRODUCT_AVAILABLE,
    priority: "normal",
    title: "New listing from Beyblade Arena!",
    message: "Beyblade Arena just listed a Beyblade X Wizard Arrow.",
    actionUrl: "/products/product-beyblade-x-wizard-arrow",
    actionLabel: "View",
    isRead: false,
    relatedId: "product-beyblade-x-wizard-arrow",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // ── Tyson's notifications (8) — seller-focused (Beyblade Arena) ───────────

  {
    id: "notif-kaiba-new-order-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_PLACED,
    priority: "high",
    title: "New order received!",
    message: "Mock User 3 ordered Beyblade Original Dranzer S. Ship within 3 business days.",
    actionUrl: "/store/orders",
    actionLabel: "View Order",
    isRead: false,
    relatedId: "order-1-20260515-abc123",
    relatedType: "order",
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
  {
    id: "notif-kaiba-new-review-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REVIEW_APPROVED,
    priority: "normal",
    title: "New 5-star review!",
    message: "Mock User 3 left a 5-star review: 'Excellent quality and fast shipping!'",
    actionUrl: "/store/reviews",
    actionLabel: "View Review",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "review-1",
    relatedType: "review",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-kaiba-new-bid-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "New bid on your auction",
    message: "Mock User 3 bid ₹4,200 on Beyblade Original Dragoon Storm.",
    actionUrl: "/store/products/auction-beyblade-original-dragoon-storm",
    actionLabel: "View Auction",
    isRead: false,
    relatedId: "auction-beyblade-original-dragoon-storm",
    relatedType: "bid",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: "notif-kaiba-payout-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "normal",
    title: "Payout processed",
    message: "₹9,800 has been transferred to your UPI account for April orders.",
    actionUrl: "/store/payouts",
    actionLabel: "View Payout",
    isRead: true,
    readAt: daysAgo(3),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: "notif-kaiba-bid-received-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "New bid on Metal Lightning L-Drago",
    message: "Mock User 1 bid ₹5,000 on Beyblade Metal Lightning L-Drago.",
    actionUrl: "/store/products/auction-beyblade-metal-lightning-l-drago",
    actionLabel: "View",
    isRead: false,
    relatedId: "auction-beyblade-metal-lightning-l-drago",
    relatedType: "bid",
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: "notif-kaiba-offer-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_RECEIVED,
    priority: "normal",
    title: "New offer on Burst Valkyrie",
    message: "Mock User 3 made an offer of ₹1,200 for Beyblade Burst Valkyrie.",
    actionUrl: "/store/offers",
    actionLabel: "Respond",
    isRead: false,
    relatedId: "product-beyblade-burst-valkyrie",
    relatedType: "offer",
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(10),
  },
  {
    id: "notif-kaiba-welcome-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip, Tyson!",
    message: "Your store Beyblade Arena is now live. Start listing beyblades.",
    isRead: true,
    readAt: daysAgo(30),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "notif-kaiba-order-cancelled-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_CANCELLED,
    priority: "high",
    title: "Order cancelled",
    message: "Order #order-8-20260501-xyz789 was cancelled by the buyer.",
    actionUrl: "/store/orders",
    actionLabel: "View",
    isRead: true,
    readAt: daysAgo(7),
    relatedId: "order-8-20260501-xyz789",
    relatedType: "order",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },

  // ── Admin's notifications (5) — buyer + system ────────────────────────────

  {
    id: "notif-admin-shipped-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_SHIPPED,
    priority: "normal",
    title: "Your order has shipped!",
    message: "Order from Beyblade Arena — Beyblade Metal Flame Sagittario is on its way.",
    actionUrl: "/user/orders",
    actionLabel: "Track",
    isRead: false,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: "notif-admin-bid-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "Your bid was placed",
    message: "You bid ₹5,000 on Beyblade Metal Lightning L-Drago.",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "auction-beyblade-metal-lightning-l-drago",
    relatedType: "bid",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-admin-delivered-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_DELIVERED,
    priority: "normal",
    title: "Order delivered",
    message: "Your order of Beyblade X Knife Shinobi has been delivered.",
    isRead: true,
    readAt: daysAgo(5),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
  {
    id: "notif-admin-system-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "low",
    title: "Seed data loaded successfully",
    message: "All 26 collections seeded. Verify data in the admin panel.",
    actionUrl: "/admin/dashboard",
    actionLabel: "Admin Dashboard",
    isRead: true,
    readAt: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: "notif-admin-welcome-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to Mock User 1!",
    message: "Your admin account is active. Manage stores, products, and site settings.",
    isRead: true,
    readAt: daysAgo(60),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },

  // -- Coverage fixtures (16) - one per type that had none --------------------
  //
  // W19 gave every notification type a real email template and a resolved
  // actionUrl. 12 of the 28 types were seeded; the other 16 had NO fixture at
  // all, so a tester could not see 16 of those templates or verify where they
  // land. Each of these exists to make one template and one resolver branch
  // reachable.
  //
  // `actionUrl` is deliberately OMITTED on all but one: it is now resolved
  // from relatedType + relatedId inside sendNotification, and hardcoding one
  // here would seed data that no longer matches what the code produces -
  // which is exactly how a fixture stops being a test.
  {
    id: "notif-yugi-order-confirmed-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_CONFIRMED,
    priority: "normal",
    title: "Order confirmed",
    message: "Your order is confirmed and the seller is preparing it for dispatch.",
    isRead: false,
    relatedId: "order-2-20260819-a1b2c3",
    relatedType: "order",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "notif-yugi-bid-lost-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_LOST,
    priority: "normal",
    title: "This auction closed without you",
    message: "Beyblade Original Dragoon Storm sold to another bidder at Rs 5,200.",
    isRead: false,
    relatedId: "auction-beyblade-original-dragoon-storm",
    relatedType: "bid",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    // Seller-facing - the ONE fixture proving TYPE_AUDIENCE routes auction_ended to /store rather than /user.
    id: "notif-tyson-auction-ended-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.AUCTION_ENDED,
    priority: "normal",
    title: "Your auction ended with no winner",
    message: "The highest bid did not meet your reserve price. The listing has been archived.",
    isRead: false,
    relatedId: "auction-beyblade-lord-spryzen-ended-unsold",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-yugi-review-replied-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REVIEW_REPLIED,
    priority: "low",
    title: "The seller replied to your review",
    message: "Beyblade Arena responded to your review of Beyblade X Dran Sword.",
    isRead: false,
    relatedId: "review-dran-sword-yugi-20260819",
    relatedType: "review",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    // No relatedId on purpose - this fixture proves a promotion renders WITHOUT a CTA button rather than linking to the dashboard the reader is already on.
    id: "notif-yugi-promotion-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PROMOTION,
    priority: "low",
    title: "25% off at Beyblade Arena",
    message: "Use code ARENA25 on your next order. Ends Sunday.",
    isRead: false,
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(20),
  },
  {
    id: "notif-yugi-account-action-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ACCOUNT_ACTION,
    priority: "high",
    title: "Your account details were updated",
    message: "Your delivery address was changed. If this wasn't you, contact support immediately.",
    isRead: false,
    relatedId: "user-yugi-muto",
    relatedType: "user",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: "notif-yugi-offer-responded-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_RESPONDED,
    priority: "high",
    title: "The seller countered your offer",
    message: "Beyblade Arena countered at Rs 3,800 on Metal Storm Pegasus.",
    isRead: false,
    relatedId: "offer-metal-storm-pegasus-yugi-20260819-countered",
    relatedType: "offer",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "notif-yugi-offer-expired-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_EXPIRED,
    priority: "normal",
    title: "Your offer expired",
    message: "The seller did not respond within 48 hours. You can make a new offer.",
    isRead: false,
    relatedId: "offer-kaiba-x-wizard-arrow-expired",
    relatedType: "offer",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: "notif-yugi-offer-counter-accepted-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_COUNTER_ACCEPTED,
    priority: "high",
    title: "Your counter-offer was accepted",
    message: "Complete checkout within 24 hours to secure it at Rs 3,500.",
    isRead: false,
    relatedId: "offer-metal-storm-pegasus-yugi-20260819-countered",
    relatedType: "offer",
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: "notif-yugi-refund-initiated-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REFUND_INITIATED,
    priority: "high",
    title: "Refund on its way",
    message: "Rs 1,499 is being returned to your original payment method. Allow 5-7 working days.",
    isRead: false,
    relatedId: "order-1-20260812-r3f4nd",
    relatedType: "order",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: "notif-yugi-prize-won-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRIZE_WON,
    priority: "high",
    title: "You won a prize",
    message: "Your entry in the Beyblade Vault draw won slot #14. Reveal it within 7 days.",
    isRead: false,
    relatedId: "prizedraw-beyblade-vault-closed-pending-reveal",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-kaiba-prize-reveal-expired-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRIZE_REVEAL_EXPIRED,
    priority: "normal",
    title: "Your prize reveal window closed",
    message: "The 7-day reveal window passed and your entry was refunded.",
    isRead: false,
    relatedId: "prizedraw-beyblade-vault-closed-pending-reveal",
    relatedType: "product",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: "notif-yugi-emi-due-soon-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.EMI_INSTALLMENT_DUE_SOON,
    priority: "normal",
    title: "EMI installment due in 3 days",
    message: "Installment 2 of 6 (Rs 1,250) is due on the 29th.",
    isRead: false,
    relatedId: "order-3-20260801-em1pay",
    relatedType: "order",
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: "notif-kaiba-emi-overdue-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.EMI_INSTALLMENT_OVERDUE,
    priority: "high",
    title: "EMI installment overdue",
    message: "Installment 3 of 6 (Rs 1,250) was due on the 20th. Pay now to avoid a late fee.",
    isRead: false,
    relatedId: "order-3-20260801-em1pay",
    relatedType: "order",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "notif-tester-catalogue-stale-001",
    userId: "user-tester-qa",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.CATALOGUE_IMAGES_STALE,
    priority: "normal",
    title: "Refresh your catalogue photos",
    message: "Photos for your vintage Dragoon are getting old - refresh them within 14 days or you won't be able to list it.",
    isRead: false,
    relatedId: "mycatalog-user-tester-qa-vintage-dragoon",
    relatedType: "catalogueItem",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    // The ONE fixture keeping an explicit actionUrl, and it earns it: the buyer
    // must land on the proof-UPLOAD page, which relatedType:"order" cannot
    // express. This is the case the caller-wins rule exists for.
    id: "notif-yugi-payment-review-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PAYMENT_REVIEW,
    priority: "high",
    title: "Please re-upload your payment proof",
    message: "The screenshot you uploaded was unreadable. Upload a clearer one within 2 hours.",
    isRead: false,
    actionUrl: "/user/orders/order-4-20260825-upiman/payment",
    actionLabel: "Re-upload proof",
    relatedId: "order-4-20260825-upiman",
    relatedType: "order",
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
];
