/*
 * WHY: Seeds notifications for YGO marketplace — covers all notification types across 3 users.
 * WHAT: 23 notifications (10 Yugi, 8 Kaiba, 5 Admin). Mix of read/unread, all notification types.
 *
 * EXPORTS:
 *   notificationsSeedData — Array of Partial<NotificationDocument> for seed runner
 *
 * @tag domain:notifications
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts,SeedPanel
 * @tag sideEffects:none
 */

import type { NotificationDocument } from "../features/admin/schemas";
import { NOTIFICATION_FIELDS } from "../features/admin/schemas";

const NOW = new Date();
const hoursAgo = (n: number) => new Date(NOW.getTime() - n * 3_600_000);
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const notificationsSeedData: Partial<NotificationDocument>[] = [
  // ── Yugi's notifications (10) — buyer-focused ─────────────────────────────

  {
    id: "notif-yugi-outbid-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_OUTBID,
    priority: "high",
    title: "You've been outbid!",
    message: "Someone placed a higher bid on Blue-Eyes White Dragon LOB 1st Ed PSA 10. Current bid: ₹1,50,000.",
    actionUrl: "/auctions/auction-blue-eyes-lob-1st-psa10",
    actionLabel: "Place New Bid",
    isRead: false,
    relatedId: "auction-blue-eyes-lob-1st-psa10",
    relatedType: "product",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: "notif-yugi-shipped-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_SHIPPED,
    priority: "normal",
    title: "Your order has shipped!",
    message: "Order #order-1-20260515-abc123 — Dark Magician LOB is on its way. Track your shipment.",
    actionUrl: "/user/orders/order-1-20260515-abc123",
    actionLabel: "Track Order",
    isRead: false,
    relatedId: "order-1-20260515-abc123",
    relatedType: "order",
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: "notif-yugi-delivered-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_DELIVERED,
    priority: "normal",
    title: "Order delivered!",
    message: "Order #order-2-20260510-def456 has been delivered. Please confirm receipt and leave a review.",
    actionUrl: "/user/orders/order-2-20260510-def456",
    actionLabel: "Confirm & Review",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "order-2-20260510-def456",
    relatedType: "order",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-yugi-price-drop-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRODUCT_AVAILABLE,
    priority: "normal",
    title: "Price drop on your wishlist item!",
    message: "Pot of Greed LOB dropped from ₹14,999 to ₹12,999. Get it before it's gone.",
    actionUrl: "/products/product-pot-of-greed-lob",
    actionLabel: "View Product",
    isRead: false,
    relatedId: "product-pot-of-greed-lob",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-yugi-auction-won-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_WON,
    priority: "high",
    title: "Congratulations! You won the auction!",
    message: "You won the Mirror Force MRD 1st Ed auction for ₹15,000. Complete payment within 48 hours.",
    actionUrl: "/auctions/auction-mirror-force-mrd-1st-psa10",
    actionLabel: "Pay Now",
    isRead: true,
    readAt: daysAgo(3),
    relatedId: "auction-mirror-force-mrd-1st-psa10",
    relatedType: "product",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: "notif-yugi-raffle-win-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "high",
    title: "You won the LOB 1st Edition Raffle!",
    message: "Congratulations! You've been selected as the winner of the Complete LOB 1st Edition Set raffle.",
    actionUrl: "/events/event-won-complete-lob-raffle",
    actionLabel: "View Details",
    isRead: true,
    readAt: daysAgo(4),
    relatedId: "event-won-complete-lob-raffle",
    relatedType: "product",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "notif-yugi-review-approved-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REVIEW_APPROVED,
    priority: "low",
    title: "Your review was published",
    message: "Your review for Dark Magician LOB 1st Edition has been approved and is now live.",
    isRead: true,
    readAt: daysAgo(6),
    relatedId: "review-1",
    relatedType: "review",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
  },
  {
    id: "notif-yugi-welcome-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip, Yugi!",
    message: "Your account is ready. Start browsing verified Yu-Gi-Oh! cards from sellers across India.",
    actionUrl: "/products",
    actionLabel: "Start Shopping",
    isRead: true,
    readAt: daysAgo(30),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "notif-yugi-offer-received-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_RECEIVED,
    priority: "normal",
    title: "Counter-offer on your Dark Magician Girl bid",
    message: "Kaiba Corp countered your offer of ₹7,500 with ₹8,200 for Dark Magician Girl IOC.",
    actionUrl: "/user/offers",
    actionLabel: "View Offer",
    isRead: false,
    relatedId: "product-dark-magician-girl-ioc",
    relatedType: "product",
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: "notif-yugi-new-listing-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRODUCT_AVAILABLE,
    priority: "normal",
    title: "New listing from Kaiba Corp!",
    message: "Kaiba Corp Card Vault just listed a Rainbow Dragon POTD 1st Edition.",
    actionUrl: "/products/product-rainbow-dragon",
    actionLabel: "View",
    isRead: false,
    relatedId: "product-rainbow-dragon",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // ── Kaiba's notifications (8) — seller-focused ────────────────────────────

  {
    id: "notif-kaiba-new-order-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_PLACED,
    priority: "high",
    title: "New order received!",
    message: "Yugi Muto ordered Dark Magician LOB 1st Edition. Ship within 3 business days.",
    actionUrl: "/store/orders",
    actionLabel: "View Order",
    isRead: false,
    relatedId: "order-1-20260515-abc123",
    relatedType: "order",
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
  {
    id: "notif-kaiba-new-review-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REVIEW_APPROVED,
    priority: "normal",
    title: "New 5-star review!",
    message: "Yugi Muto left a 5-star review: 'Excellent quality and fast shipping!'",
    actionUrl: "/store/reviews",
    actionLabel: "View Review",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "review-1",
    relatedType: "review",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-kaiba-new-bid-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "New bid on your auction",
    message: "Yugi Muto bid ₹1,25,000 on Blue-Eyes White Dragon LOB 1st Ed PSA 10.",
    actionUrl: "/store/products/auction-blue-eyes-lob-1st-psa10",
    actionLabel: "View Auction",
    isRead: false,
    relatedId: "auction-blue-eyes-lob-1st-psa10",
    relatedType: "bid",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: "notif-kaiba-payout-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "normal",
    title: "Payout processed",
    message: "₹45,000 has been transferred to your UPI account for May orders.",
    actionUrl: "/store/payouts",
    actionLabel: "View Payout",
    isRead: true,
    readAt: daysAgo(3),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: "notif-kaiba-bid-received-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "New bid on Exodia Complete Set",
    message: "LetItRip Admin bid ₹2,00,000 on Exodia Complete Set PSA 9.",
    actionUrl: "/store/products/auction-exodia-complete-set-psa9",
    actionLabel: "View",
    isRead: false,
    relatedId: "auction-exodia-complete-set-psa9",
    relatedType: "bid",
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: "notif-kaiba-offer-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_RECEIVED,
    priority: "normal",
    title: "New offer on Dark Magician Girl",
    message: "Yugi Muto made an offer of ₹7,500 for Dark Magician Girl IOC.",
    actionUrl: "/store/offers",
    actionLabel: "Respond",
    isRead: false,
    relatedId: "product-dark-magician-girl-ioc",
    relatedType: "offer",
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(10),
  },
  {
    id: "notif-kaiba-welcome-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip, Kaiba!",
    message: "Your store Kaiba Corp Card Vault is now live. Start listing cards.",
    isRead: true,
    readAt: daysAgo(30),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "notif-kaiba-order-cancelled-001",
    userId: "user-seto-kaiba",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_CANCELLED,
    priority: "high",
    title: "Order cancelled",
    message: "Order #order-8-20260501-xyz789 was cancelled by the buyer.",
    actionUrl: "/store/orders",
    actionLabel: "View",
    isRead: true,
    readAt: daysAgo(7),
    relatedId: "order-8-20260501-xyz789",
    relatedType: "order",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },

  // ── Admin's notifications (5) — buyer + system ────────────────────────────

  {
    id: "notif-admin-shipped-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_SHIPPED,
    priority: "normal",
    title: "Your order has shipped!",
    message: "Order from Kaiba Corp — Chaos Emperor Dragon is on its way.",
    actionUrl: "/user/orders",
    actionLabel: "Track",
    isRead: false,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: "notif-admin-bid-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "Your bid was placed",
    message: "You bid ₹2,00,000 on Exodia Complete Set PSA 9.",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "auction-exodia-complete-set-psa9",
    relatedType: "bid",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-admin-delivered-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_DELIVERED,
    priority: "normal",
    title: "Order delivered",
    message: "Your order of Raigeki LOB has been delivered.",
    isRead: true,
    readAt: daysAgo(5),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
  {
    id: "notif-admin-system-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "low",
    title: "Seed data loaded successfully",
    message: "All 26 collections seeded. Verify data in the admin panel.",
    actionUrl: "/admin/dashboard",
    actionLabel: "Admin Dashboard",
    isRead: true,
    readAt: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: "notif-admin-welcome-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip Admin!",
    message: "Your admin account is active. Manage stores, products, and site settings.",
    isRead: true,
    readAt: daysAgo(60),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },
];
