/*
 * WHY: Seeds notifications for the Beyblade collectibles marketplace — covers all notification types across 3 users.
 * WHAT: 23 notifications (10 Rehan, 8 Tyson, 5 Admin). Mix of read/unread, all notification types.
 *
 * EXPORTS:
 *   notificationsSeedData — Array of Partial<NotificationDocument> for seed runner
 *
 * @tag domain:notifications
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import type { NotificationDocument } from "../features/admin/schemas";
import { NOTIFICATION_FIELDS } from "../features/admin/schemas";
import { ROUTES } from "../next/routing/route-map";

const NOW = new Date();
const hoursAgo = (n: number) => new Date(NOW.getTime() - n * 3_600_000);
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const notificationsSeedData: Partial<NotificationDocument>[] = [
  // ── Rehan's notifications (10) — buyer-focused ────────────────────────────

  {
    id: "notif-yugi-outbid-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_OUTBID,
    priority: "high",
    title: "You've been outbid!",
    message: "Someone placed a higher bid on Beyblade Original Dragoon Storm. Current bid: ₹4,500.",
    actionUrl: "/auctions/auction-beyblade-original-dragoon-storm",
    actionLabel: "Place New Bid",
    isRead: false,
    relatedId: "auction-beyblade-original-dragoon-storm",
    relatedType: "product",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: "notif-yugi-shipped-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_SHIPPED,
    priority: "normal",
    title: "Your order has shipped!",
    message: "Order #order-1-20260515-abc123 — Beyblade Original Dranzer S is on its way. Track your shipment.",
    actionUrl: "/user/orders/order-1-20260515-abc123",
    actionLabel: "Track Order",
    isRead: false,
    relatedId: "order-1-20260515-abc123",
    relatedType: "order",
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: "notif-yugi-delivered-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_DELIVERED,
    priority: "normal",
    title: "Order delivered!",
    message: "Order #order-2-20260510-def456 has been delivered. Please confirm receipt and leave a review.",
    actionUrl: "/user/orders/order-2-20260510-def456",
    actionLabel: "Confirm & Review",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "order-2-20260510-def456",
    relatedType: "order",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-yugi-price-drop-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRODUCT_AVAILABLE,
    priority: "normal",
    title: "Price drop on your wishlist item!",
    message: "Beyblade Metal Storm Pegasus dropped from ₹1,999 to ₹1,699. Get it before it's gone.",
    actionUrl: "/products/product-beyblade-metal-storm-pegasus",
    actionLabel: "View Product",
    isRead: false,
    relatedId: "product-beyblade-metal-storm-pegasus",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-yugi-auction-won-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_WON,
    priority: "high",
    title: "Congratulations! You won the auction!",
    message: "You won the Beyblade Metal Lightning L-Drago auction for ₹5,200. Complete payment within 48 hours.",
    actionUrl: "/auctions/auction-beyblade-metal-lightning-l-drago",
    actionLabel: "Pay Now",
    isRead: true,
    readAt: daysAgo(3),
    relatedId: "auction-beyblade-metal-lightning-l-drago",
    relatedType: "product",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: "notif-yugi-raffle-win-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "high",
    title: "You won the Original Series Raffle!",
    message: "Congratulations! You've been selected as the winner of the Complete Original Series Collectors Set raffle.",
    actionUrl: "/events/event-won-original-set-raffle",
    actionLabel: "View Details",
    isRead: true,
    readAt: daysAgo(4),
    relatedId: "event-won-original-set-raffle",
    relatedType: "product",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: "notif-yugi-review-approved-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REVIEW_APPROVED,
    priority: "low",
    title: "Your review was published",
    message: "Your review for Beyblade Original Dranzer S has been approved and is now live.",
    isRead: true,
    readAt: daysAgo(6),
    relatedId: "review-1",
    relatedType: "review",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
  },
  {
    id: "notif-yugi-welcome-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip, Rehan!",
    message: "Your account is ready. Start browsing verified Beyblade collectibles from sellers across India.",
    actionUrl: String(ROUTES.PUBLIC.PRODUCTS),
    actionLabel: "Start Shopping",
    isRead: true,
    readAt: daysAgo(30),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "notif-yugi-offer-received-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_RECEIVED,
    priority: "normal",
    title: "Counter-offer on your Burst Valkyrie bid",
    message: "Beyblade Arena countered your offer of ₹1,200 with ₹1,450 for Beyblade Burst Valkyrie.",
    actionUrl: "/user/offers",
    actionLabel: "View Offer",
    isRead: false,
    relatedId: "product-beyblade-burst-valkyrie",
    relatedType: "product",
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: "notif-yugi-new-listing-001",
    userId: "user-yugi-muto",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.PRODUCT_AVAILABLE,
    priority: "normal",
    title: "New listing from Beyblade Arena!",
    message: "Beyblade Arena just listed a Beyblade X Wizard Arrow.",
    actionUrl: "/products/product-beyblade-x-wizard-arrow",
    actionLabel: "View",
    isRead: false,
    relatedId: "product-beyblade-x-wizard-arrow",
    relatedType: "product",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // ── Tyson's notifications (8) — seller-focused (Beyblade Arena) ───────────

  {
    id: "notif-kaiba-new-order-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_PLACED,
    priority: "high",
    title: "New order received!",
    message: "Rehan Sheikh ordered Beyblade Original Dranzer S. Ship within 3 business days.",
    actionUrl: "/store/orders",
    actionLabel: "View Order",
    isRead: false,
    relatedId: "order-1-20260515-abc123",
    relatedType: "order",
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
  {
    id: "notif-kaiba-new-review-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.REVIEW_APPROVED,
    priority: "normal",
    title: "New 5-star review!",
    message: "Rehan Sheikh left a 5-star review: 'Excellent quality and fast shipping!'",
    actionUrl: "/store/reviews",
    actionLabel: "View Review",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "review-1",
    relatedType: "review",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-kaiba-new-bid-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "New bid on your auction",
    message: "Rehan Sheikh bid ₹4,200 on Beyblade Original Dragoon Storm.",
    actionUrl: "/store/products/auction-beyblade-original-dragoon-storm",
    actionLabel: "View Auction",
    isRead: false,
    relatedId: "auction-beyblade-original-dragoon-storm",
    relatedType: "bid",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: "notif-kaiba-payout-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "normal",
    title: "Payout processed",
    message: "₹9,800 has been transferred to your UPI account for April orders.",
    actionUrl: "/store/payouts",
    actionLabel: "View Payout",
    isRead: true,
    readAt: daysAgo(3),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: "notif-kaiba-bid-received-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "New bid on Metal Lightning L-Drago",
    message: "LetItRip Admin bid ₹5,000 on Beyblade Metal Lightning L-Drago.",
    actionUrl: "/store/products/auction-beyblade-metal-lightning-l-drago",
    actionLabel: "View",
    isRead: false,
    relatedId: "auction-beyblade-metal-lightning-l-drago",
    relatedType: "bid",
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
  {
    id: "notif-kaiba-offer-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.OFFER_RECEIVED,
    priority: "normal",
    title: "New offer on Burst Valkyrie",
    message: "Rehan Sheikh made an offer of ₹1,200 for Beyblade Burst Valkyrie.",
    actionUrl: "/store/offers",
    actionLabel: "Respond",
    isRead: false,
    relatedId: "product-beyblade-burst-valkyrie",
    relatedType: "offer",
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(10),
  },
  {
    id: "notif-kaiba-welcome-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip, Tyson!",
    message: "Your store Beyblade Arena is now live. Start listing beyblades.",
    isRead: true,
    readAt: daysAgo(30),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "notif-kaiba-order-cancelled-001",
    userId: "user-tyson-blader",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_CANCELLED,
    priority: "high",
    title: "Order cancelled",
    message: "Order #order-8-20260501-xyz789 was cancelled by the buyer.",
    actionUrl: "/store/orders",
    actionLabel: "View",
    isRead: true,
    readAt: daysAgo(7),
    relatedId: "order-8-20260501-xyz789",
    relatedType: "order",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
  },

  // ── Admin's notifications (5) — buyer + system ────────────────────────────

  {
    id: "notif-admin-shipped-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_SHIPPED,
    priority: "normal",
    title: "Your order has shipped!",
    message: "Order from Beyblade Arena — Beyblade Metal Flame Sagittario is on its way.",
    actionUrl: "/user/orders",
    actionLabel: "Track",
    isRead: false,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
  {
    id: "notif-admin-bid-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.BID_PLACED,
    priority: "normal",
    title: "Your bid was placed",
    message: "You bid ₹5,000 on Beyblade Metal Lightning L-Drago.",
    isRead: true,
    readAt: daysAgo(1),
    relatedId: "auction-beyblade-metal-lightning-l-drago",
    relatedType: "bid",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "notif-admin-delivered-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.ORDER_DELIVERED,
    priority: "normal",
    title: "Order delivered",
    message: "Your order of Beyblade X Knife Shinobi has been delivered.",
    isRead: true,
    readAt: daysAgo(5),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
  },
  {
    id: "notif-admin-system-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.SYSTEM,
    priority: "low",
    title: "Seed data loaded successfully",
    message: "All 26 collections seeded. Verify data in the admin panel.",
    actionUrl: "/admin/dashboard",
    actionLabel: "Admin Dashboard",
    isRead: true,
    readAt: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: "notif-admin-welcome-001",
    userId: "user-admin-letitrip",
    type: NOTIFICATION_FIELDS.TYPE_VALUES.WELCOME,
    priority: "normal",
    title: "Welcome to LetItRip Admin!",
    message: "Your admin account is active. Manage stores, products, and site settings.",
    isRead: true,
    readAt: daysAgo(60),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },
];
