/**
 * Offers Seed Data — 12 offers across all statuses.
 *
 * Covers: pending (×3), accepted (×1), declined (×2), countered (×2),
 *         expired (×2), withdrawn (×1), paid (×2).
 * Admin as buyer: 1 pending (Hot Wheels Banana Camaro) + 1 paid (ALTER Rem Wedding).
 * Paid offers link to order-admin-043-alter-rem-offer and order-arjun-044-bx01-offer.
 */

import type { OfferDocument } from "../features/seller/schemas/firestore";
import { OfferStatusValues } from "../features/seller/schemas/firestore";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysFromNow = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

export const offersSeedData: Partial<OfferDocument>[] = [
  // ── 1. PENDING — admin as buyer — Hot Wheels Banana Camaro Redline ─────────
  {
    id: "offer-admin-hw-banana-pending",
    productId: "product-hot-wheels-redline-banana-1968",
    productTitle: "Hot Wheels 1968 Redline Banana Camaro (Custom)",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    buyerUid: "user-admin-letitrip",
    buyerName: "LetItRip Admin",
    buyerEmail: "admin@letitrip.in",
    listedPrice: 1299900,
    offerAmount: 999900,
    currency: "INR",
    status: OfferStatusValues.PENDING,
    buyerNote: "Interested in this piece. Would you accept Rs 9,999?",
    expiresAt: daysFromNow(3),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // ── 2. PAID — admin as buyer — ALTER Rem Wedding (order placed) ───────────
  {
    id: "offer-admin-alter-rem-paid",
    productId: "product-alter-rem-wedding-scale",
    productTitle: "ALTER: Re:ZERO — Rem (Wedding Ver.) 1/7 Scale Figure",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    buyerUid: "user-admin-letitrip",
    buyerName: "LetItRip Admin",
    buyerEmail: "admin@letitrip.in",
    listedPrice: 1299900,
    offerAmount: 1099900,
    lockedPrice: 1099900,
    currency: "INR",
    status: OfferStatusValues.PAID,
    buyerNote: "Would you accept Rs 10,999 for this?",
    sellerNote: "Accepted. Thank you!",
    expiresAt: daysAgo(3),
    acceptedAt: daysAgo(12),
    respondedAt: daysAgo(12),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(11),
  },

  // ── 3. PENDING — Rahul — Charizard ex SIR from pokemon-palace ────────────
  {
    id: "offer-rahul-charizard-sar-pending",
    productId: "product-pokemon-charizard-ex-sar-sv",
    productTitle: "Pokemon TCG: Charizard ex Special Illustration Rare (SV3)",
    storeId: "store-pokemon-palace",
    storeName: "Pokemon Palace",
    buyerUid: "user-rahul-sharma",
    buyerName: "Rahul Sharma",
    buyerEmail: "rahul.sharma@gmail.com",
    listedPrice: 349900,
    offerAmount: 280000,
    currency: "INR",
    status: OfferStatusValues.PENDING,
    buyerNote: "Can you do Rs 2,800 for this card?",
    expiresAt: daysFromNow(5),
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },

  // ── 4. DECLINED — Priya — MAFEX Miles Morales from letitrip-official ───────
  {
    id: "offer-priya-mafex-miles-declined",
    productId: "product-mafex-miles-morales-spiderman",
    productTitle: "MAFEX No.240: Miles Morales Spider-Man",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    buyerUid: "user-priya-patel",
    buyerName: "Priya Patel",
    buyerEmail: "priya.patel@gmail.com",
    listedPrice: 849900,
    offerAmount: 650000,
    currency: "INR",
    status: OfferStatusValues.DECLINED,
    buyerNote: "Offering Rs 6,500 — slightly above my budget.",
    sellerNote: "Sorry, we cannot go below Rs 7,999 for this item.",
    expiresAt: daysAgo(5),
    respondedAt: daysAgo(8),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },

  // ── 5. COUNTERED — Arjun — SHF Goku Ultra Instinct from letitrip-official ──
  {
    id: "offer-arjun-shf-goku-countered",
    productId: "product-shf-goku-ultra-instinct",
    productTitle: "S.H.Figuarts Goku Ultra Instinct -Sign-",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    buyerUid: "user-arjun-singh",
    buyerName: "Arjun Singh",
    buyerEmail: "arjun.singh@gmail.com",
    listedPrice: 699900,
    offerAmount: 549900,
    counterAmount: 649900,
    currency: "INR",
    status: OfferStatusValues.COUNTERED,
    buyerNote: "Rs 5,499 — will you take it?",
    sellerNote: "We can do Rs 6,499 as our best price.",
    expiresAt: daysFromNow(2),
    respondedAt: daysAgo(1),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },

  // ── 6. EXPIRED — Neha — Blue-Eyes LOB from cardgame-hub ──────────────────
  {
    id: "offer-neha-blue-eyes-expired",
    productId: "product-yugioh-blue-eyes-lob-nm",
    productTitle: "Yu-Gi-Oh! Blue-Eyes White Dragon LOB 1st Edition (NM)",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    buyerUid: "user-neha-gupta",
    buyerName: "Neha Gupta",
    buyerEmail: "neha.gupta@gmail.com",
    listedPrice: 299900,
    offerAmount: 220000,
    currency: "INR",
    status: OfferStatusValues.EXPIRED,
    buyerNote: "I can offer Rs 2,200. Let me know.",
    expiresAt: daysAgo(2),
    createdAt: daysAgo(9),
    updatedAt: daysAgo(2),
  },

  // ── 7. WITHDRAWN — Vikram — Twin Mill 1970 Redline from vintage-vault ──────
  {
    id: "offer-vikram-twin-mill-withdrawn",
    productId: "product-hot-wheels-twin-mill-1970-redline",
    productTitle: "Hot Wheels Vintage: Twin Mill I 1970 Redline (Brown, Near Mint)",
    storeId: "store-vintage-vault",
    storeName: "Vintage Vault",
    buyerUid: "user-vikram-rao",
    buyerName: "Vikram Rao",
    buyerEmail: "vikram.rao@gmail.com",
    listedPrice: 699900,
    offerAmount: 549900,
    currency: "INR",
    status: OfferStatusValues.WITHDRAWN,
    buyerNote: "Offering Rs 5,499 for the Twin Mill.",
    expiresAt: daysAgo(3),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },

  // ── 8. PAID — Arjun — BX-01 Dran Sword from beyblade-arena (offer order) ───
  {
    id: "offer-arjun-bx01-paid",
    productId: "product-beyblade-x-bx01-dran-sword-starter-pack",
    productTitle: "Beyblade X: BX-01 Dran Sword 3-60F Starter Pack",
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    buyerUid: "user-arjun-singh",
    buyerName: "Arjun Singh",
    buyerEmail: "arjun.singh@gmail.com",
    listedPrice: 159900,
    offerAmount: 129900,
    lockedPrice: 129900,
    currency: "INR",
    status: OfferStatusValues.PAID,
    buyerNote: "Rs 1,299 for the BX-01 starter — deal?",
    sellerNote: "Sure, accepted!",
    expiresAt: daysAgo(10),
    acceptedAt: daysAgo(20),
    respondedAt: daysAgo(20),
    createdAt: daysAgo(22),
    updatedAt: daysAgo(19),
  },

  // ── 9. ACCEPTED — Pooja — GSC Aqua 1/7 from tokyo-toys (pending payment) ───
  {
    id: "offer-pooja-gsc-aqua-accepted",
    productId: "product-gsc-aqua-konosuba-scale",
    productTitle: "Good Smile Company: KonoSuba — Aqua 1/7 Scale Figure",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    buyerUid: "user-pooja-sharma",
    buyerName: "Pooja Sharma",
    buyerEmail: "pooja.sharma@gmail.com",
    listedPrice: 899900,
    offerAmount: 749900,
    lockedPrice: 749900,
    currency: "INR",
    status: OfferStatusValues.ACCEPTED,
    buyerNote: "Rs 7,499 final offer on the Aqua figure.",
    sellerNote: "Accepted! Please complete payment within 24 hours.",
    expiresAt: daysFromNow(1),
    acceptedAt: daysAgo(0),
    respondedAt: daysAgo(0),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },

  // ── 10. DECLINED — Meera — PG Unleashed RX-78-2 from gundam-galaxy ─────────
  {
    id: "offer-meera-pg-rx78-declined",
    productId: "product-pg-unleashed-rx78-2",
    productTitle: "Bandai PG Unleashed 1/60: RX-78-2 Gundam",
    storeId: "store-gundam-galaxy",
    storeName: "Gundam Galaxy",
    buyerUid: "user-meera-nair",
    buyerName: "Meera Nair",
    buyerEmail: "meera.nair@gmail.com",
    listedPrice: 2499900,
    offerAmount: 1999900,
    currency: "INR",
    status: OfferStatusValues.DECLINED,
    buyerNote: "Rs 19,999 — this is a big spend, would you consider it?",
    sellerNote: "Unfortunately we cannot discount below Rs 22,999 for this kit.",
    expiresAt: daysAgo(1),
    respondedAt: daysAgo(3),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },

  // ── 11. COUNTERED — Rohit — OP-05 Booster Box from cardgame-hub ─────────────
  {
    id: "offer-rohit-op05-countered",
    productId: "product-onepiece-op05-booster-box",
    productTitle: "One Piece Card Game: OP-05 Awakening of the New Era Booster Box",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    buyerUid: "user-rohit-verma",
    buyerName: "Rohit Verma",
    buyerEmail: "rohit.verma@gmail.com",
    listedPrice: 499900,
    offerAmount: 399900,
    counterAmount: 449900,
    currency: "INR",
    status: OfferStatusValues.COUNTERED,
    buyerNote: "Can you do Rs 3,999 for the OP-05 box?",
    sellerNote: "Best we can do is Rs 4,499 — final price.",
    expiresAt: daysFromNow(1),
    respondedAt: daysAgo(1),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },

  // ── 12. EXPIRED — Kavya — Nendoroid Rem from letitrip-official ───────────
  {
    id: "offer-kavya-nendo-rem-expired",
    productId: "product-nendoroid-rem-rezero",
    productTitle: "Nendoroid: Re:ZERO — Rem #663",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    buyerUid: "user-kavya-nair",
    buyerName: "Kavya Nair",
    buyerEmail: "kavya.nair@gmail.com",
    listedPrice: 399900,
    offerAmount: 329900,
    currency: "INR",
    status: OfferStatusValues.EXPIRED,
    buyerNote: "Rs 3,299 for the Nendoroid Rem — is this okay?",
    expiresAt: daysAgo(3),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
];
