/**
 * Orders Seed Data — LetItRip Collectibles Platform
 * 10 orders in all status states (pending, processing, shipped, delivered,
 * cancelled, refunded, return_requested). Buyer/seller IDs from P15.
 * order- prefix (system IDs, not slug-based).
 */

import type { OrderDocument } from "../features/orders/schemas";
import {
  OrderStatusValues,
  PaymentStatusValues,
  PaymentMethodValues,
} from "../features/orders/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const ordersSeedData: Partial<OrderDocument>[] = [
  // ── 1. DELIVERED ─────────────────────────────────────────────────────────
  {
    id: "order-rahul-001-pokemon-etb",
    productId: "product-pokemon-sv-etb",
    productTitle: "Pokémon Scarlet & Violet Paldean Fates Elite Trainer Box",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    userEmail: "rahul.sharma@gmail.com",
    sellerId: "user-aryan-kapoor",
    sellerName: "Aryan Kapoor",
    items: [
      {
        productId: "product-pokemon-sv-etb",
        productTitle: "Pokémon Scarlet & Violet Paldean Fates Elite Trainer Box",
        quantity: 1,
        unitPrice: 449900,
        totalPrice: 449900,
      },
    ],
    quantity: 1,
    unitPrice: 449900,
    totalPrice: 449900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_001_demo",
    shippingAddress: "204 Koramangala 5th Block, Bengaluru, Karnataka 560095",
    trackingNumber: "DTDC987654321IN",
    shippingCarrier: "DTDC",
    trackingUrl: "https://www.dtdc.in/tracking",
    shippingFee: 4900,
    platformFee: 22495,
    orderDate: daysAgo(28),
    shippingDate: daysAgo(26),
    deliveryDate: daysAgo(23),
    payoutStatus: "paid",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(23),
  },

  // ── 2. DELIVERED ─────────────────────────────────────────────────────────
  {
    id: "order-priya-002-nendoroid-rem",
    productId: "product-nendoroid-rem-rezero",
    productTitle: "Nendoroid Rem (Re:Zero) — Good Smile Company",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    userEmail: "priya.patel@gmail.com",
    sellerId: "user-admin-letitrip",
    sellerName: "LetItRip Admin",
    items: [
      {
        productId: "product-nendoroid-rem-rezero",
        productTitle: "Nendoroid Rem (Re:Zero) — Good Smile Company",
        quantity: 1,
        unitPrice: 499900,
        totalPrice: 499900,
      },
    ],
    quantity: 1,
    unitPrice: 499900,
    totalPrice: 499900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "12 Satellite Road, Ahmedabad, Gujarat 380015",
    trackingNumber: "SHR556677889",
    shippingCarrier: "Shiprocket",
    shippingFee: 0,
    platformFee: 24995,
    orderDate: daysAgo(21),
    shippingDate: daysAgo(19),
    deliveryDate: daysAgo(16),
    payoutStatus: "paid",
    createdAt: daysAgo(21),
    updatedAt: daysAgo(16),
  },

  // ── 3. SHIPPED ────────────────────────────────────────────────────────────
  {
    id: "order-arjun-003-gundam-rx78",
    productId: "product-gundam-rx78-mg",
    productTitle: "MG 1/100 RX-78-2 Gundam Ver. 3.0",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    userEmail: "arjun.singh@gmail.com",
    sellerId: "user-admin-letitrip",
    sellerName: "LetItRip Admin",
    items: [
      {
        productId: "product-gundam-rx78-mg",
        productTitle: "MG 1/100 RX-78-2 Gundam Ver. 3.0",
        quantity: 1,
        unitPrice: 299900,
        totalPrice: 299900,
      },
    ],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_003_demo",
    shippingAddress: "7 Tonk Road, Jaipur, Rajasthan 302001",
    trackingNumber: "EKART4412238871",
    shippingCarrier: "Ekart",
    trackingUrl: "https://ekartlogistics.com/shipmenttrack",
    shippingFee: 0,
    platformFee: 14995,
    orderDate: daysAgo(7),
    shippingDate: daysAgo(5),
    payoutStatus: "eligible",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },

  // ── 4. SHIPPED ────────────────────────────────────────────────────────────
  {
    id: "order-meera-004-beyblade-bx01",
    productId: "product-beyblade-x-bx01-dran-sword",
    productTitle: "Beyblade X BX-01 Dran Sword 4-60F Starter Set",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    userEmail: "meera.nair@gmail.com",
    sellerId: "user-rohit-joshi",
    sellerName: "Rohit Joshi",
    items: [
      {
        productId: "product-beyblade-x-bx01-dran-sword",
        productTitle: "Beyblade X BX-01 Dran Sword 4-60F Starter Set",
        quantity: 2,
        unitPrice: 199900,
        totalPrice: 399800,
      },
    ],
    quantity: 2,
    unitPrice: 199900,
    totalPrice: 399800,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_004_demo",
    shippingAddress: "Flat 8B, Marine Lines, Mumbai, Maharashtra 400002",
    trackingNumber: "IP123456789IN",
    shippingCarrier: "India Post",
    shippingFee: 4900,
    platformFee: 19990,
    orderDate: daysAgo(5),
    shippingDate: daysAgo(3),
    payoutStatus: "eligible",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },

  // ── 5. PROCESSING ────────────────────────────────────────────────────────
  {
    id: "order-rahul-005-tomica-datsun",
    productId: "product-tomica-limited-datsun",
    productTitle: "Tomica Limited Vintage Datsun Bluebird 1600SSS (1969)",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    userEmail: "rahul.sharma@gmail.com",
    sellerId: "user-vikram-mehta",
    sellerName: "Vikram Mehta",
    items: [
      {
        productId: "product-tomica-limited-datsun",
        productTitle: "Tomica Limited Vintage Datsun Bluebird 1600SSS (1969)",
        quantity: 1,
        unitPrice: 299900,
        totalPrice: 299900,
      },
    ],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.PROCESSING,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "204 Koramangala 5th Block, Bengaluru, Karnataka 560095",
    shippingFee: 0,
    platformFee: 14995,
    orderDate: daysAgo(2),
    payoutStatus: "eligible",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },

  // ── 6. PENDING (awaiting payment) ────────────────────────────────────────
  {
    id: "order-priya-006-yugioh-tin",
    productId: "product-yugioh-25th-tin",
    productTitle: "Yu-Gi-Oh! 25th Anniversary Tin: Dueling Heroes",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    userEmail: "priya.patel@gmail.com",
    sellerId: "user-nisha-reddy",
    sellerName: "Nisha Reddy",
    items: [
      {
        productId: "product-yugioh-25th-tin",
        productTitle: "Yu-Gi-Oh! 25th Anniversary Tin: Dueling Heroes",
        quantity: 1,
        unitPrice: 299900,
        totalPrice: 299900,
      },
    ],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.PENDING,
    paymentStatus: PaymentStatusValues.PENDING,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    shippingAddress: "12 Satellite Road, Ahmedabad, Gujarat 380015",
    shippingFee: 4900,
    platformFee: 14995,
    orderDate: daysAgo(0),
    payoutStatus: "eligible",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },

  // ── 7. CANCELLED (buyer-initiated pre-dispatch) ───────────────────────────
  {
    id: "order-arjun-007-funko-naruto",
    productId: "product-funko-pop-naruto-sage",
    productTitle: "Funko Pop! Naruto Sage Mode #932",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    userEmail: "arjun.singh@gmail.com",
    sellerId: "user-admin-letitrip",
    sellerName: "LetItRip Admin",
    items: [
      {
        productId: "product-funko-pop-naruto-sage",
        productTitle: "Funko Pop! Naruto Sage Mode #932",
        quantity: 1,
        unitPrice: 149900,
        totalPrice: 149900,
      },
    ],
    quantity: 1,
    unitPrice: 149900,
    totalPrice: 149900,
    currency: "INR",
    status: OrderStatusValues.CANCELLED,
    paymentStatus: PaymentStatusValues.REFUNDED,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_007_demo",
    shippingAddress: "7 Tonk Road, Jaipur, Rajasthan 302001",
    shippingFee: 0,
    platformFee: 0,
    orderDate: daysAgo(15),
    cancellationDate: daysAgo(14),
    cancellationReason: "Changed mind — found the item locally",
    refundAmount: 149900,
    refundStatus: "completed",
    refundNote: "Full refund issued — item was not yet dispatched",
    payoutStatus: "eligible",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(13),
  },

  // ── 8. REFUNDED (post-delivery dispute resolved) ──────────────────────────
  {
    id: "order-meera-008-hot-wheels-banana",
    productId: "product-hot-wheels-redline-banana-1968",
    productTitle: "Hot Wheels 1968 Redline Banana Camaro (Custom)",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    userEmail: "meera.nair@gmail.com",
    sellerId: "user-vikram-mehta",
    sellerName: "Vikram Mehta",
    items: [
      {
        productId: "product-hot-wheels-redline-banana-1968",
        productTitle: "Hot Wheels 1968 Redline Banana Camaro (Custom)",
        quantity: 1,
        unitPrice: 1299900,
        totalPrice: 1299900,
      },
    ],
    quantity: 1,
    unitPrice: 1299900,
    totalPrice: 1299900,
    currency: "INR",
    status: OrderStatusValues.REFUNDED,
    paymentStatus: PaymentStatusValues.REFUNDED,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_008_demo",
    shippingAddress: "Flat 8B, Marine Lines, Mumbai, Maharashtra 400002",
    trackingNumber: "DELHIVERY778899001",
    shippingCarrier: "Delhivery",
    shippingFee: 0,
    platformFee: 0,
    orderDate: daysAgo(35),
    shippingDate: daysAgo(33),
    deliveryDate: daysAgo(30),
    refundAmount: 1299900,
    refundStatus: "completed",
    refundNote: "Car not Redline era — post-1977 baseplate found after delivery. Full refund issued after dispute mediation.",
    payoutStatus: "eligible",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(25),
  },

  // ── 9. RETURN REQUESTED (under review) ───────────────────────────────────
  {
    id: "order-rahul-009-beyblade-burst",
    productId: "product-beyblade-burst-b200-valkyrie",
    productTitle: "Beyblade Burst B-200 Brave Valkyrie Evolution",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    userEmail: "rahul.sharma@gmail.com",
    sellerId: "user-rohit-joshi",
    sellerName: "Rohit Joshi",
    items: [
      {
        productId: "product-beyblade-burst-b200-valkyrie",
        productTitle: "Beyblade Burst B-200 Brave Valkyrie Evolution",
        quantity: 1,
        unitPrice: 249900,
        totalPrice: 249900,
      },
    ],
    quantity: 1,
    unitPrice: 249900,
    totalPrice: 249900,
    currency: "INR",
    status: OrderStatusValues.RETURN_REQUESTED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "204 Koramangala 5th Block, Bengaluru, Karnataka 560095",
    trackingNumber: "SHR112233445",
    shippingCarrier: "Shiprocket",
    shippingFee: 0,
    platformFee: 12495,
    orderDate: daysAgo(10),
    shippingDate: daysAgo(8),
    deliveryDate: daysAgo(5),
    notes: "Buyer reports Beyblade passport QR doesn't scan — suspects bootleg despite listing claiming official Takara Tomy. Dispute under investigation.",
    payoutStatus: "eligible",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },

  // ── 10. DELIVERED with coupon ─────────────────────────────────────────────
  {
    id: "order-priya-010-shf-goku",
    productId: "product-shf-goku-ultra-instinct",
    productTitle: "S.H.Figuarts Goku Ultra Instinct -Sign-",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    userEmail: "priya.patel@gmail.com",
    sellerId: "user-admin-letitrip",
    sellerName: "LetItRip Admin",
    items: [
      {
        productId: "product-shf-goku-ultra-instinct",
        productTitle: "S.H.Figuarts Goku Ultra Instinct -Sign-",
        quantity: 1,
        unitPrice: 699900,
        totalPrice: 699900,
      },
    ],
    quantity: 1,
    unitPrice: 699900,
    totalPrice: 649900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_010_demo",
    couponCode: "WELCOME10",
    couponDiscount: 50000,
    appliedDiscounts: [
      {
        code: "WELCOME10",
        couponId: "coupon-welcome10",
        type: "coupon",
        discountAmount: 50000,
        scope: "admin",
      },
    ],
    shippingAddress: "12 Satellite Road, Ahmedabad, Gujarat 380015",
    trackingNumber: "DTDC556677889",
    shippingCarrier: "DTDC",
    shippingFee: 0,
    platformFee: 32495,
    orderDate: daysAgo(18),
    shippingDate: daysAgo(16),
    deliveryDate: daysAgo(13),
    payoutStatus: "paid",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(13),
  },
];
