/**
 * Orders Seed Data — LetItRip Collectibles Platform
 * 10 orders in all status states (pending, processing, shipped, delivered,
 * cancelled, refunded, return_requested). Buyer/seller IDs from P15.
 * order- prefix (system IDs, not slug-based).
 */

import type { OrderDocument } from "../features/orders/schemas";
import {
  OrderStatusValues,
  PaymentStatusValues,
  PaymentMethodValues,
} from "../features/orders/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const ordersSeedData: Partial<OrderDocument>[] = [
  // ── 1. DELIVERED ─────────────────────────────────────────────────────────
  {
    id: "order-rahul-001-pokemon-etb",
    productId: "product-pokemon-sv-etb",
    productTitle: "Pokémon Scarlet & Violet Paldean Fates Elite Trainer Box",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    userEmail: "rahul.sharma@gmail.com",
    storeId: "store-pokemon-palace",
    storeName: "Pokémon Palace",
    items: [
      {
        productId: "product-pokemon-sv-etb",
        productTitle: "Pokémon Scarlet & Violet Paldean Fates Elite Trainer Box",
        quantity: 1,
        unitPrice: 449900,
        totalPrice: 449900,
      },
    ],
    quantity: 1,
    unitPrice: 449900,
    totalPrice: 449900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_001_demo",
    shippingAddress: "204 Koramangala 5th Block, Bengaluru, Karnataka 560095",
    trackingNumber: "DTDC987654321IN",
    shippingCarrier: "DTDC",
    trackingUrl: "https://www.dtdc.in/tracking",
    shippingFee: 4900,
    platformFee: 22495,
    orderDate: daysAgo(28),
    shippingDate: daysAgo(26),
    deliveryDate: daysAgo(23),
    payoutStatus: "paid",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(23),
  },

  // ── 2. DELIVERED ─────────────────────────────────────────────────────────
  {
    id: "order-priya-002-nendoroid-rem",
    productId: "product-nendoroid-rem-rezero",
    productTitle: "Nendoroid Rem (Re:Zero) — Good Smile Company",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    userEmail: "priya.patel@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [
      {
        productId: "product-nendoroid-rem-rezero",
        productTitle: "Nendoroid Rem (Re:Zero) — Good Smile Company",
        quantity: 1,
        unitPrice: 499900,
        totalPrice: 499900,
      },
    ],
    quantity: 1,
    unitPrice: 499900,
    totalPrice: 499900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "12 Satellite Road, Ahmedabad, Gujarat 380015",
    trackingNumber: "SHR556677889",
    shippingCarrier: "Shiprocket",
    shippingFee: 0,
    platformFee: 24995,
    orderDate: daysAgo(21),
    shippingDate: daysAgo(19),
    deliveryDate: daysAgo(16),
    payoutStatus: "paid",
    createdAt: daysAgo(21),
    updatedAt: daysAgo(16),
  },

  // ── 3. SHIPPED ────────────────────────────────────────────────────────────
  {
    id: "order-arjun-003-gundam-rx78",
    productId: "product-gundam-rx78-mg",
    productTitle: "MG 1/100 RX-78-2 Gundam Ver. 3.0",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    userEmail: "arjun.singh@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [
      {
        productId: "product-gundam-rx78-mg",
        productTitle: "MG 1/100 RX-78-2 Gundam Ver. 3.0",
        quantity: 1,
        unitPrice: 299900,
        totalPrice: 299900,
      },
    ],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_003_demo",
    shippingAddress: "7 Tonk Road, Jaipur, Rajasthan 302001",
    trackingNumber: "EKART4412238871",
    shippingCarrier: "Ekart",
    trackingUrl: "https://ekartlogistics.com/shipmenttrack",
    shippingFee: 0,
    platformFee: 14995,
    orderDate: daysAgo(7),
    shippingDate: daysAgo(5),
    payoutStatus: "eligible",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },

  // ── 4. SHIPPED ────────────────────────────────────────────────────────────
  {
    id: "order-meera-004-beyblade-bx01",
    productId: "product-beyblade-x-bx01-dran-sword",
    productTitle: "Beyblade X BX-01 Dran Sword 4-60F Starter Set",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    userEmail: "meera.nair@gmail.com",
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    items: [
      {
        productId: "product-beyblade-x-bx01-dran-sword",
        productTitle: "Beyblade X BX-01 Dran Sword 4-60F Starter Set",
        quantity: 2,
        unitPrice: 199900,
        totalPrice: 399800,
      },
    ],
    quantity: 2,
    unitPrice: 199900,
    totalPrice: 399800,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_004_demo",
    shippingAddress: "Flat 8B, Marine Lines, Mumbai, Maharashtra 400002",
    trackingNumber: "IP123456789IN",
    shippingCarrier: "India Post",
    shippingFee: 4900,
    platformFee: 19990,
    orderDate: daysAgo(5),
    shippingDate: daysAgo(3),
    payoutStatus: "eligible",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },

  // ── 5. PROCESSING ────────────────────────────────────────────────────────
  {
    id: "order-rahul-005-tomica-datsun",
    productId: "product-tomica-limited-datsun",
    productTitle: "Tomica Limited Vintage Datsun Bluebird 1600SSS (1969)",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    userEmail: "rahul.sharma@gmail.com",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    items: [
      {
        productId: "product-tomica-limited-datsun",
        productTitle: "Tomica Limited Vintage Datsun Bluebird 1600SSS (1969)",
        quantity: 1,
        unitPrice: 299900,
        totalPrice: 299900,
      },
    ],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.PROCESSING,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "204 Koramangala 5th Block, Bengaluru, Karnataka 560095",
    shippingFee: 0,
    platformFee: 14995,
    orderDate: daysAgo(2),
    payoutStatus: "eligible",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },

  // ── 6. PENDING (awaiting payment) ────────────────────────────────────────
  {
    id: "order-priya-006-yugioh-tin",
    productId: "product-yugioh-25th-tin",
    productTitle: "Yu-Gi-Oh! 25th Anniversary Tin: Dueling Heroes",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    userEmail: "priya.patel@gmail.com",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    items: [
      {
        productId: "product-yugioh-25th-tin",
        productTitle: "Yu-Gi-Oh! 25th Anniversary Tin: Dueling Heroes",
        quantity: 1,
        unitPrice: 299900,
        totalPrice: 299900,
      },
    ],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.PENDING,
    paymentStatus: PaymentStatusValues.PENDING,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    shippingAddress: "12 Satellite Road, Ahmedabad, Gujarat 380015",
    shippingFee: 4900,
    platformFee: 14995,
    orderDate: daysAgo(0),
    payoutStatus: "eligible",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },

  // ── 7. CANCELLED (buyer-initiated pre-dispatch) ───────────────────────────
  {
    id: "order-arjun-007-funko-naruto",
    productId: "product-funko-pop-naruto-sage",
    productTitle: "Funko Pop! Naruto Sage Mode #932",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    userEmail: "arjun.singh@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [
      {
        productId: "product-funko-pop-naruto-sage",
        productTitle: "Funko Pop! Naruto Sage Mode #932",
        quantity: 1,
        unitPrice: 149900,
        totalPrice: 149900,
      },
    ],
    quantity: 1,
    unitPrice: 149900,
    totalPrice: 149900,
    currency: "INR",
    status: OrderStatusValues.CANCELLED,
    paymentStatus: PaymentStatusValues.REFUNDED,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_007_demo",
    shippingAddress: "7 Tonk Road, Jaipur, Rajasthan 302001",
    shippingFee: 0,
    platformFee: 0,
    orderDate: daysAgo(15),
    cancellationDate: daysAgo(14),
    cancellationReason: "Changed mind — found the item locally",
    refundAmount: 149900,
    refundStatus: "completed",
    refundNote: "Full refund issued — item was not yet dispatched",
    payoutStatus: "eligible",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(13),
  },

  // ── 8. REFUNDED (post-delivery dispute resolved) ──────────────────────────
  {
    id: "order-meera-008-hot-wheels-banana",
    productId: "product-hot-wheels-redline-banana-1968",
    productTitle: "Hot Wheels 1968 Redline Banana Camaro (Custom)",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    userEmail: "meera.nair@gmail.com",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    items: [
      {
        productId: "product-hot-wheels-redline-banana-1968",
        productTitle: "Hot Wheels 1968 Redline Banana Camaro (Custom)",
        quantity: 1,
        unitPrice: 1299900,
        totalPrice: 1299900,
      },
    ],
    quantity: 1,
    unitPrice: 1299900,
    totalPrice: 1299900,
    currency: "INR",
    status: OrderStatusValues.REFUNDED,
    paymentStatus: PaymentStatusValues.REFUNDED,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_008_demo",
    shippingAddress: "Flat 8B, Marine Lines, Mumbai, Maharashtra 400002",
    trackingNumber: "DELHIVERY778899001",
    shippingCarrier: "Delhivery",
    shippingFee: 0,
    platformFee: 0,
    orderDate: daysAgo(35),
    shippingDate: daysAgo(33),
    deliveryDate: daysAgo(30),
    refundAmount: 1299900,
    refundStatus: "completed",
    refundNote: "Car not Redline era — post-1977 baseplate found after delivery. Full refund issued after dispute mediation.",
    payoutStatus: "eligible",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(25),
  },

  // ── 9. RETURN REQUESTED (under review) ───────────────────────────────────
  {
    id: "order-rahul-009-beyblade-burst",
    productId: "product-beyblade-burst-b200-valkyrie",
    productTitle: "Beyblade Burst B-200 Brave Valkyrie Evolution",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    userEmail: "rahul.sharma@gmail.com",
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    items: [
      {
        productId: "product-beyblade-burst-b200-valkyrie",
        productTitle: "Beyblade Burst B-200 Brave Valkyrie Evolution",
        quantity: 1,
        unitPrice: 249900,
        totalPrice: 249900,
      },
    ],
    quantity: 1,
    unitPrice: 249900,
    totalPrice: 249900,
    currency: "INR",
    status: OrderStatusValues.RETURN_REQUESTED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "204 Koramangala 5th Block, Bengaluru, Karnataka 560095",
    trackingNumber: "SHR112233445",
    shippingCarrier: "Shiprocket",
    shippingFee: 0,
    platformFee: 12495,
    orderDate: daysAgo(10),
    shippingDate: daysAgo(8),
    deliveryDate: daysAgo(5),
    notes: "Buyer reports Beyblade passport QR doesn't scan — suspects bootleg despite listing claiming official Takara Tomy. Dispute under investigation.",
    payoutStatus: "eligible",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },

  // ── 10. DELIVERED with coupon ─────────────────────────────────────────────
  {
    id: "order-priya-010-shf-goku",
    productId: "product-shf-goku-ultra-instinct",
    productTitle: "S.H.Figuarts Goku Ultra Instinct -Sign-",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    userEmail: "priya.patel@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [
      {
        productId: "product-shf-goku-ultra-instinct",
        productTitle: "S.H.Figuarts Goku Ultra Instinct -Sign-",
        quantity: 1,
        unitPrice: 699900,
        totalPrice: 699900,
      },
    ],
    quantity: 1,
    unitPrice: 699900,
    totalPrice: 649900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_010_demo",
    couponCode: "WELCOME10",
    couponDiscount: 50000,
    appliedDiscounts: [
      {
        code: "WELCOME10",
        couponId: "coupon-welcome10",
        type: "coupon",
        discountAmount: 50000,
        scope: "admin",
      },
    ],
    shippingAddress: "12 Satellite Road, Ahmedabad, Gujarat 380015",
    trackingNumber: "DTDC556677889",
    shippingCarrier: "DTDC",
    shippingFee: 0,
    platformFee: 32495,
    orderDate: daysAgo(18),
    shippingDate: daysAgo(16),
    deliveryDate: daysAgo(13),
    payoutStatus: "paid",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(13),
  },

  // ── 11. DELIVERED — Anjali / Pokemon 151 ETB ─────────────────────────────
  {
    id: "order-anjali-011-151-etb",
    productId: "product-pokemon-151-etb",
    productTitle: "Pokémon TCG: Scarlet & Violet — 151 Elite Trainer Box",
    userId: "user-anjali-verma",
    userName: "Anjali Verma",
    userEmail: "anjali.verma@gmail.com",
    storeId: "store-pokemon-palace",
    storeName: "Pokémon Palace",
    items: [{ productId: "product-pokemon-151-etb", productTitle: "Pokémon TCG: SV 151 ETB", quantity: 1, unitPrice: 549900, totalPrice: 549900 }],
    quantity: 1,
    unitPrice: 549900,
    totalPrice: 549900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_011_demo",
    shippingAddress: "45 Janakpuri, New Delhi 110058",
    trackingNumber: "BLUE112233445",
    shippingCarrier: "Bluedart",
    shippingFee: 0,
    platformFee: 27495,
    orderDate: daysAgo(35),
    shippingDate: daysAgo(33),
    deliveryDate: daysAgo(30),
    payoutStatus: "paid",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(30),
  },

  // ── 12. DELIVERED — Rohit / OP-06 Booster Box ────────────────────────────
  {
    id: "order-rohit-012-op06-box",
    productId: "product-onepiece-op06-booster-box",
    productTitle: "One Piece Card Game: OP-06 Wings of the Captain Booster Box",
    userId: "user-rohit-verma",
    userName: "Rohit Verma",
    userEmail: "rohit.verma@gmail.com",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    items: [{ productId: "product-onepiece-op06-booster-box", productTitle: "OP-06 Wings of the Captain Booster Box", quantity: 1, unitPrice: 549900, totalPrice: 549900 }],
    quantity: 1,
    unitPrice: 549900,
    totalPrice: 549900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "67 Dwarka Sector 10, New Delhi 110075",
    trackingNumber: "EKART778899001",
    shippingCarrier: "Ekart",
    shippingFee: 4900,
    platformFee: 27495,
    orderDate: daysAgo(32),
    shippingDate: daysAgo(30),
    deliveryDate: daysAgo(27),
    payoutStatus: "paid",
    createdAt: daysAgo(32),
    updatedAt: daysAgo(27),
  },

  // ── 13. DELIVERED — Pooja / Alter Rem Wedding ─────────────────────────────
  {
    id: "order-pooja-013-alter-rem",
    productId: "product-alter-rem-wedding-scale",
    productTitle: "ALTER: Re:ZERO — Rem (Wedding Ver.) 1/7 Scale Figure",
    userId: "user-pooja-sharma",
    userName: "Pooja Sharma",
    userEmail: "pooja.sharma@gmail.com",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    items: [{ productId: "product-alter-rem-wedding-scale", productTitle: "ALTER Rem Wedding Ver. 1/7", quantity: 1, unitPrice: 1299900, totalPrice: 1299900 }],
    quantity: 1,
    unitPrice: 1299900,
    totalPrice: 1299900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_013_demo",
    shippingAddress: "202 Bandra West, Mumbai, Maharashtra 400050",
    trackingNumber: "SHPR334455667",
    shippingCarrier: "Shiprocket",
    shippingFee: 0,
    platformFee: 64995,
    orderDate: daysAgo(40),
    shippingDate: daysAgo(38),
    deliveryDate: daysAgo(34),
    payoutStatus: "paid",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(34),
  },

  // ── 14. DELIVERED — Kiran / PG Unleashed RX-78-2 ─────────────────────────
  {
    id: "order-kiran-014-pg-rx78",
    productId: "product-pg-unleashed-rx78-2",
    productTitle: "Bandai PG Unleashed 1/60: RX-78-2 Gundam",
    userId: "user-kiran-reddy",
    userName: "Kiran Reddy",
    userEmail: "kiran.reddy@gmail.com",
    storeId: "store-gundam-galaxy",
    storeName: "Gundam Galaxy",
    items: [{ productId: "product-pg-unleashed-rx78-2", productTitle: "PG Unleashed RX-78-2 Gundam", quantity: 1, unitPrice: 2499900, totalPrice: 2499900 }],
    quantity: 1,
    unitPrice: 2499900,
    totalPrice: 2499900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_014_demo",
    shippingAddress: "18 Kondapur, Hyderabad, Telangana 500084",
    trackingNumber: "BLUE889900112",
    shippingCarrier: "Bluedart",
    shippingFee: 0,
    platformFee: 124995,
    orderDate: daysAgo(45),
    shippingDate: daysAgo(43),
    deliveryDate: daysAgo(39),
    payoutStatus: "paid",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(39),
  },

  // ── 15. DELIVERED — Naman / Surging Sparks Booster Box ───────────────────
  {
    id: "order-naman-015-surging-sparks",
    productId: "product-pokemon-surging-sparks-booster",
    productTitle: "Pokémon TCG: Surging Sparks Booster Box (36 Packs)",
    userId: "user-naman-gupta",
    userName: "Naman Gupta",
    userEmail: "naman.gupta@gmail.com",
    storeId: "store-pokemon-palace",
    storeName: "Pokémon Palace",
    items: [{ productId: "product-pokemon-surging-sparks-booster", productTitle: "Surging Sparks Booster Box 36-pack", quantity: 1, unitPrice: 1299900, totalPrice: 1299900 }],
    quantity: 1,
    unitPrice: 1299900,
    totalPrice: 1299900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_015_demo",
    shippingAddress: "44 Sector 17, Chandigarh 160017",
    trackingNumber: "DTDC223344556",
    shippingCarrier: "DTDC",
    shippingFee: 0,
    platformFee: 64995,
    orderDate: daysAgo(38),
    shippingDate: daysAgo(36),
    deliveryDate: daysAgo(33),
    payoutStatus: "paid",
    createdAt: daysAgo(38),
    updatedAt: daysAgo(33),
  },

  // ── 16. SHIPPED — Preeti / BX-01 Dran Sword ──────────────────────────────
  {
    id: "order-preeti-016-dran-sword",
    productId: "product-beyblade-x-bx01-dran-sword-starter-pack",
    productTitle: "Beyblade X: BX-01 Dran Sword 3-60F — Starter Pack",
    userId: "user-preeti-joshi",
    userName: "Preeti Joshi",
    userEmail: "preeti.joshi@gmail.com",
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    items: [{ productId: "product-beyblade-x-bx01-dran-sword-starter-pack", productTitle: "BX-01 Dran Sword Starter Pack", quantity: 2, unitPrice: 159900, totalPrice: 319800 }],
    quantity: 2,
    unitPrice: 159900,
    totalPrice: 319800,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "7 MP Nagar Zone 2, Bhopal, Madhya Pradesh 462011",
    trackingNumber: "EKART556677890",
    shippingCarrier: "Ekart",
    shippingFee: 4900,
    platformFee: 15990,
    orderDate: daysAgo(5),
    shippingDate: daysAgo(3),
    payoutStatus: "eligible",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },

  // ── 17. SHIPPED — Varun / figma Makima ───────────────────────────────────
  {
    id: "order-varun-017-figma-makima",
    productId: "product-figma-makima-chainsaw-man",
    productTitle: "figma: Chainsaw Man — Makima",
    userId: "user-varun-bhat",
    userName: "Varun Bhat",
    userEmail: "varun.bhat@gmail.com",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    items: [{ productId: "product-figma-makima-chainsaw-man", productTitle: "figma Makima (Chainsaw Man)", quantity: 1, unitPrice: 679900, totalPrice: 679900 }],
    quantity: 1,
    unitPrice: 679900,
    totalPrice: 679900,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_017_demo",
    shippingAddress: "3 Light House Hill, Mangalore, Karnataka 575001",
    trackingNumber: "SHPR667788901",
    shippingCarrier: "Shiprocket",
    shippingFee: 4900,
    platformFee: 33995,
    orderDate: daysAgo(4),
    shippingDate: daysAgo(2),
    payoutStatus: "eligible",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
  },

  // ── 18. SHIPPED — Rahul / Charizard ex SAR ───────────────────────────────
  {
    id: "order-rahul-018-charizard-sar",
    productId: "product-pokemon-charizard-ex-sar-sv",
    productTitle: "Pokémon TCG: Charizard ex — Special Illustration Rare (SV3)",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    userEmail: "rahul.sharma@gmail.com",
    storeId: "store-pokemon-palace",
    storeName: "Pokémon Palace",
    items: [{ productId: "product-pokemon-charizard-ex-sar-sv", productTitle: "Charizard ex SIR (Obsidian Flames)", quantity: 1, unitPrice: 349900, totalPrice: 349900 }],
    quantity: 1,
    unitPrice: 349900,
    totalPrice: 349900,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_018_demo",
    shippingAddress: "204 Koramangala 5th Block, Bengaluru, Karnataka 560095",
    trackingNumber: "BLUE445566778",
    shippingCarrier: "Bluedart",
    shippingFee: 0,
    platformFee: 17495,
    orderDate: daysAgo(3),
    shippingDate: daysAgo(1),
    payoutStatus: "eligible",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },

  // ── 19. PROCESSING — Priya / MG Nu Gundam Ver Ka ─────────────────────────
  {
    id: "order-priya-019-mg-nu-gundam",
    productId: "product-mg-nu-gundam-ver-ka",
    productTitle: "Bandai MG 1/100: RX-93 Nu Gundam (Ver. Ka)",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    userEmail: "priya.patel@gmail.com",
    storeId: "store-gundam-galaxy",
    storeName: "Gundam Galaxy",
    items: [{ productId: "product-mg-nu-gundam-ver-ka", productTitle: "MG Nu Gundam Ver. Ka 1/100", quantity: 1, unitPrice: 749900, totalPrice: 749900 }],
    quantity: 1,
    unitPrice: 749900,
    totalPrice: 749900,
    currency: "INR",
    status: OrderStatusValues.PROCESSING,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_019_demo",
    shippingAddress: "12 Satellite Road, Ahmedabad, Gujarat 380015",
    shippingFee: 0,
    platformFee: 37495,
    orderDate: daysAgo(2),
    payoutStatus: "eligible",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },

  // ── 20. PROCESSING — Arjun / MAFEX Miles Morales ─────────────────────────
  {
    id: "order-arjun-020-mafex-miles",
    productId: "product-mafex-miles-morales-spiderman",
    productTitle: "MAFEX No.240: Miles Morales Spider-Man",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    userEmail: "arjun.singh@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [{ productId: "product-mafex-miles-morales-spiderman", productTitle: "MAFEX Miles Morales #240", quantity: 1, unitPrice: 849900, totalPrice: 849900 }],
    quantity: 1,
    unitPrice: 849900,
    totalPrice: 849900,
    currency: "INR",
    status: OrderStatusValues.PROCESSING,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "78 Indiranagar 100 Ft Road, Bengaluru 560038",
    shippingFee: 0,
    platformFee: 42495,
    orderDate: daysAgo(1),
    payoutStatus: "eligible",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // ── 21. PROCESSING — Neha / Blue-Eyes LOB NM ─────────────────────────────
  {
    id: "order-neha-021-blue-eyes-lob",
    productId: "product-yugioh-blue-eyes-lob-nm",
    productTitle: "Yu-Gi-Oh! Blue-Eyes White Dragon — LOB 1st Edition (NM)",
    userId: "user-neha-gupta",
    userName: "Neha Gupta",
    userEmail: "neha.gupta@gmail.com",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    items: [{ productId: "product-yugioh-blue-eyes-lob-nm", productTitle: "BEWD LOB 1st Edition NM", quantity: 1, unitPrice: 299900, totalPrice: 299900 }],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.PROCESSING,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_021_demo",
    shippingAddress: "33 Lajpat Nagar 4, New Delhi 110024",
    shippingFee: 0,
    platformFee: 14995,
    orderDate: daysAgo(1),
    payoutStatus: "eligible",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },

  // ── 22. PENDING — Vikram / Corgi DB5 Bond ────────────────────────────────
  {
    id: "order-vikram-022-corgi-db5",
    productId: "product-corgi-aston-martin-db5",
    productTitle: "Corgi: Aston Martin DB5 — James Bond 007 Edition",
    userId: "user-vikram-rao",
    userName: "Vikram Rao",
    userEmail: "vikram.rao@gmail.com",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    items: [{ productId: "product-corgi-aston-martin-db5", productTitle: "Corgi Aston Martin DB5 Bond 007", quantity: 1, unitPrice: 299900, totalPrice: 299900 }],
    quantity: 1,
    unitPrice: 299900,
    totalPrice: 299900,
    currency: "INR",
    status: OrderStatusValues.PENDING,
    paymentStatus: PaymentStatusValues.PENDING,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    shippingAddress: "55 Jubilee Hills Road 10, Hyderabad 500033",
    shippingFee: 4900,
    platformFee: 14995,
    orderDate: daysAgo(0),
    payoutStatus: "eligible",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },

  // ── 23. PENDING — Ananya / HG Aerial Rebuild ─────────────────────────────
  {
    id: "order-ananya-023-hg-aerial",
    productId: "product-hg-aerial-rebuild-gundam",
    productTitle: "Bandai HG 1/144: Gundam Aerial Rebuild",
    userId: "user-ananya-krishna",
    userName: "Ananya Krishna",
    userEmail: "ananya.krishna@gmail.com",
    storeId: "store-gundam-galaxy",
    storeName: "Gundam Galaxy",
    items: [
      { productId: "product-hg-aerial-rebuild-gundam", productTitle: "HG Aerial Rebuild", quantity: 1, unitPrice: 249900, totalPrice: 249900 },
      { productId: "product-hg-calibarn-witch-mercury", productTitle: "HG Calibarn", quantity: 1, unitPrice: 279900, totalPrice: 279900 },
    ],
    quantity: 2,
    unitPrice: 264900,
    totalPrice: 529800,
    currency: "INR",
    status: OrderStatusValues.PENDING,
    paymentStatus: PaymentStatusValues.PENDING,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "9 Koramangala 3rd Block, Bengaluru 560034",
    shippingFee: 0,
    platformFee: 26490,
    orderDate: daysAgo(0),
    payoutStatus: "eligible",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },

  // ── 24. RETURN_REQUESTED — Siddharth / Nendoroid Zero Two ────────────────
  {
    id: "order-siddharth-024-nendo-zero-two",
    productId: "product-nendoroid-zero-two-darling",
    productTitle: "Nendoroid: DARLING in the FRANXX — Zero Two #952",
    userId: "user-siddharth-mehta",
    userName: "Siddharth Mehta",
    userEmail: "siddharth.mehta@gmail.com",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    items: [{ productId: "product-nendoroid-zero-two-darling", productTitle: "Nendoroid Zero Two #952", quantity: 1, unitPrice: 479900, totalPrice: 479900 }],
    quantity: 1,
    unitPrice: 479900,
    totalPrice: 479900,
    currency: "INR",
    status: OrderStatusValues.RETURN_REQUESTED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_024_demo",
    shippingAddress: "14 Powai Lake Road, Mumbai 400076",
    trackingNumber: "EKART990011223",
    shippingCarrier: "Ekart",
    shippingFee: 0,
    platformFee: 23995,
    orderDate: daysAgo(20),
    shippingDate: daysAgo(18),
    deliveryDate: daysAgo(15),
    payoutStatus: "eligible",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(8),
  },

  // ── 25. CANCELLED — Kavya / RLC Porsche 918 ──────────────────────────────
  {
    id: "order-kavya-025-rlc-porsche",
    productId: "product-hot-wheels-rlc-porsche-918",
    productTitle: "Hot Wheels RLC Exclusive: Porsche 918 Spyder — Spectraflame White",
    userId: "user-kavya-nair",
    userName: "Kavya Nair",
    userEmail: "kavya.nair@gmail.com",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    items: [{ productId: "product-hot-wheels-rlc-porsche-918", productTitle: "HW RLC Porsche 918 Spectraflame White", quantity: 1, unitPrice: 349900, totalPrice: 349900 }],
    quantity: 1,
    unitPrice: 349900,
    totalPrice: 349900,
    currency: "INR",
    status: OrderStatusValues.CANCELLED,
    paymentStatus: PaymentStatusValues.REFUNDED,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_025_demo",
    shippingAddress: "22 MG Road, Ernakulam, Kerala 682016",
    shippingFee: 0,
    platformFee: 0,
    orderDate: daysAgo(12),
    payoutStatus: "eligible",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
  },

  // ── 26. CANCELLED — Rohan / MTG Duskmourn Box ────────────────────────────
  {
    id: "order-rohan-026-mtg-duskmourn",
    productId: "product-mtg-duskmourn-booster-box",
    productTitle: "Magic: The Gathering — Duskmourn: House of Horror Play Booster Box",
    userId: "user-rohan-joshi",
    userName: "Rohan Joshi",
    userEmail: "rohan.joshi@gmail.com",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    items: [{ productId: "product-mtg-duskmourn-booster-box", productTitle: "MTG Duskmourn Play Booster Box", quantity: 1, unitPrice: 599900, totalPrice: 599900 }],
    quantity: 1,
    unitPrice: 599900,
    totalPrice: 599900,
    currency: "INR",
    status: OrderStatusValues.CANCELLED,
    paymentStatus: PaymentStatusValues.REFUNDED,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "5 Vile Parle West, Mumbai 400056",
    shippingFee: 0,
    platformFee: 0,
    orderDate: daysAgo(9),
    payoutStatus: "eligible",
    createdAt: daysAgo(9),
    updatedAt: daysAgo(8),
  },

  // ── 27. REFUNDED — Divya / SHF Ultra Instinct Goku ──────────────────────
  {
    id: "order-divya-027-shf-goku",
    productId: "product-shf-ultra-instinct-goku",
    productTitle: "S.H.Figuarts: Dragon Ball Super — Ultra Instinct Goku",
    userId: "user-divya-reddy",
    userName: "Divya Reddy",
    userEmail: "divya.reddy@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [{ productId: "product-shf-ultra-instinct-goku", productTitle: "S.H.Figuarts Ultra Instinct Goku 2nd Release", quantity: 1, unitPrice: 649900, totalPrice: 649900 }],
    quantity: 1,
    unitPrice: 649900,
    totalPrice: 649900,
    currency: "INR",
    status: OrderStatusValues.REFUNDED,
    paymentStatus: PaymentStatusValues.REFUNDED,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_027_demo",
    shippingAddress: "88 Jubilee Hills, Hyderabad 500033",
    trackingNumber: "BLUE334455669",
    shippingCarrier: "Bluedart",
    shippingFee: 0,
    platformFee: 0,
    orderDate: daysAgo(25),
    shippingDate: daysAgo(23),
    deliveryDate: daysAgo(20),
    payoutStatus: "eligible",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(12),
  },

  // ── 28. DELIVERED — Anjali / Tomica Land Cruiser 300 ─────────────────────
  {
    id: "order-anjali-028-tomica-lc300",
    productId: "product-tomica-land-cruiser-300",
    productTitle: "Tomica: Toyota Land Cruiser 300 (No. 107)",
    userId: "user-anjali-verma",
    userName: "Anjali Verma",
    userEmail: "anjali.verma@gmail.com",
    storeId: "store-diecast-depot",
    storeName: "Diecast Depot",
    items: [
      { productId: "product-tomica-land-cruiser-300", productTitle: "Tomica Toyota Land Cruiser 300", quantity: 3, unitPrice: 59900, totalPrice: 179700 },
    ],
    quantity: 3,
    unitPrice: 59900,
    totalPrice: 179700,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "45 Janakpuri, New Delhi 110058",
    trackingNumber: "EKART112233445",
    shippingCarrier: "Ekart",
    shippingFee: 4900,
    platformFee: 8985,
    orderDate: daysAgo(22),
    shippingDate: daysAgo(20),
    deliveryDate: daysAgo(17),
    payoutStatus: "paid",
    createdAt: daysAgo(22),
    updatedAt: daysAgo(17),
  },

  // ── 29. DELIVERED — Naman / figma Link TotK ──────────────────────────────
  {
    id: "order-naman-029-figma-link",
    productId: "product-figma-link-totk",
    productTitle: "figma: The Legend of Zelda: Tears of the Kingdom — Link",
    userId: "user-naman-gupta",
    userName: "Naman Gupta",
    userEmail: "naman.gupta@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [{ productId: "product-figma-link-totk", productTitle: "figma Link Tears of the Kingdom", quantity: 1, unitPrice: 699900, totalPrice: 699900 }],
    quantity: 1,
    unitPrice: 699900,
    totalPrice: 699900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_029_demo",
    shippingAddress: "44 Sector 17, Chandigarh 160017",
    trackingNumber: "SHPR778899012",
    shippingCarrier: "Shiprocket",
    shippingFee: 0,
    platformFee: 34995,
    orderDate: daysAgo(50),
    shippingDate: daysAgo(48),
    deliveryDate: daysAgo(44),
    payoutStatus: "paid",
    createdAt: daysAgo(50),
    updatedAt: daysAgo(44),
  },

  // ── 30. SHIPPED — Kiran / MG Strike Freedom ──────────────────────────────
  {
    id: "order-kiran-030-mg-strike-freedom",
    productId: "product-mg-strike-freedom-gundam",
    productTitle: "Bandai MG 1/100: Strike Freedom Gundam (Full Burst Mode)",
    userId: "user-kiran-reddy",
    userName: "Kiran Reddy",
    userEmail: "kiran.reddy@gmail.com",
    storeId: "store-gundam-galaxy",
    storeName: "Gundam Galaxy",
    items: [{ productId: "product-mg-strike-freedom-gundam", productTitle: "MG Strike Freedom Full Burst Mode", quantity: 1, unitPrice: 699900, totalPrice: 699900 }],
    quantity: 1,
    unitPrice: 699900,
    totalPrice: 699900,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_030_demo",
    shippingAddress: "18 Kondapur, Hyderabad, Telangana 500084",
    trackingNumber: "BLUE556677889",
    shippingCarrier: "Bluedart",
    shippingFee: 0,
    platformFee: 34995,
    orderDate: daysAgo(6),
    shippingDate: daysAgo(4),
    payoutStatus: "eligible",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
  },

  // ── 31. DELIVERED — Pooja / Nendoroid Miku V4X ───────────────────────────
  {
    id: "order-pooja-031-nendo-miku",
    productId: "product-nendoroid-hatsune-miku-v4x",
    productTitle: "Nendoroid: Hatsune Miku V4X — Good Smile Company",
    userId: "user-pooja-sharma",
    userName: "Pooja Sharma",
    userEmail: "pooja.sharma@gmail.com",
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    items: [{ productId: "product-nendoroid-hatsune-miku-v4x", productTitle: "Nendoroid Hatsune Miku V4X", quantity: 1, unitPrice: 499900, totalPrice: 499900 }],
    quantity: 1,
    unitPrice: 499900,
    totalPrice: 499900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "202 Bandra West, Mumbai 400050",
    trackingNumber: "EKART667788902",
    shippingCarrier: "Ekart",
    shippingFee: 0,
    platformFee: 24995,
    orderDate: daysAgo(42),
    shippingDate: daysAgo(40),
    deliveryDate: daysAgo(37),
    payoutStatus: "paid",
    createdAt: daysAgo(42),
    updatedAt: daysAgo(37),
  },

  // ── 32. DELIVERED — Rohit / OP-05 Booster Box ────────────────────────────
  {
    id: "order-rohit-032-op05-box",
    productId: "product-onepiece-op05-booster-box",
    productTitle: "One Piece Card Game: OP-05 Awakening of the New Era Booster Box",
    userId: "user-rohit-verma",
    userName: "Rohit Verma",
    userEmail: "rohit.verma@gmail.com",
    storeId: "store-cardgame-hub",
    storeName: "CardGame Hub",
    items: [{ productId: "product-onepiece-op05-booster-box", productTitle: "OP-05 Booster Box", quantity: 1, unitPrice: 499900, totalPrice: 499900 }],
    quantity: 1,
    unitPrice: 499900,
    totalPrice: 499900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_032_demo",
    shippingAddress: "67 Dwarka Sector 10, New Delhi 110075",
    trackingNumber: "DTDC334455668",
    shippingCarrier: "DTDC",
    shippingFee: 4900,
    platformFee: 24995,
    orderDate: daysAgo(55),
    shippingDate: daysAgo(53),
    deliveryDate: daysAgo(50),
    payoutStatus: "paid",
    createdAt: daysAgo(55),
    updatedAt: daysAgo(50),
  },

  // ── 33. DELIVERED — Preeti / BX-07 + BX-09 Bundle ───────────────────────
  {
    id: "order-preeti-033-beyblade-bundle",
    productId: "product-beyblade-x-bx07-hells-chain",
    productTitle: "Beyblade X: BX-07 Hells Chain + BX-09 Rd Dragon",
    userId: "user-preeti-joshi",
    userName: "Preeti Joshi",
    userEmail: "preeti.joshi@gmail.com",
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    items: [
      { productId: "product-beyblade-x-bx07-hells-chain", productTitle: "BX-07 Hells Chain", quantity: 1, unitPrice: 139900, totalPrice: 139900 },
      { productId: "product-beyblade-x-bx09-rd-dragon", productTitle: "BX-09 Rd Dragon", quantity: 1, unitPrice: 149900, totalPrice: 149900 },
    ],
    quantity: 2,
    unitPrice: 144900,
    totalPrice: 289800,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.UPI_MANUAL,
    shippingAddress: "7 MP Nagar Zone 2, Bhopal 462011",
    trackingNumber: "SHPR889900123",
    shippingCarrier: "Shiprocket",
    shippingFee: 0,
    platformFee: 14490,
    orderDate: daysAgo(60),
    shippingDate: daysAgo(58),
    deliveryDate: daysAgo(55),
    payoutStatus: "paid",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(55),
  },

  // ── 34. SHIPPED — Vikram / Twin Mill 1970 Redline ────────────────────────
  {
    id: "order-vikram-034-twin-mill-redline",
    productId: "product-hot-wheels-twin-mill-1970-redline",
    productTitle: "Hot Wheels Vintage: Twin Mill I — 1970 Redline (Brown, Near Mint)",
    userId: "user-vikram-rao",
    userName: "Vikram Rao",
    userEmail: "vikram.rao@gmail.com",
    storeId: "store-vintage-vault",
    storeName: "Vintage Vault",
    items: [{ productId: "product-hot-wheels-twin-mill-1970-redline", productTitle: "Hot Wheels Twin Mill I 1970 Redline Brown NM", quantity: 1, unitPrice: 699900, totalPrice: 699900 }],
    quantity: 1,
    unitPrice: 699900,
    totalPrice: 699900,
    currency: "INR",
    status: OrderStatusValues.SHIPPED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_034_demo",
    shippingAddress: "55 Jubilee Hills Road 10, Hyderabad 500033",
    trackingNumber: "BLUE112233446",
    shippingCarrier: "Bluedart",
    shippingFee: 0,
    platformFee: 34995,
    orderDate: daysAgo(5),
    shippingDate: daysAgo(3),
    payoutStatus: "eligible",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },

  // ── 35. DELIVERED — Ananya / GSC Aqua 1/7 Scale ──────────────────────────
  {
    id: "order-ananya-035-gsc-aqua",
    productId: "product-gsc-aqua-konosuba-scale",
    productTitle: "Good Smile Company: KonoSuba — Aqua 1/7 Scale Figure",
    userId: "user-ananya-krishna",
    userName: "Ananya Krishna",
    userEmail: "ananya.krishna@gmail.com",
    storeId: "store-tokyo-toys-india",
    storeName: "Tokyo Toys India",
    items: [{ productId: "product-gsc-aqua-konosuba-scale", productTitle: "GSC Aqua 1/7 Scale KonoSuba", quantity: 1, unitPrice: 899900, totalPrice: 899900 }],
    quantity: 1,
    unitPrice: 899900,
    totalPrice: 899900,
    currency: "INR",
    status: OrderStatusValues.DELIVERED,
    paymentStatus: PaymentStatusValues.PAID,
    paymentMethod: PaymentMethodValues.RAZORPAY,
    paymentId: "pay_razorpay_035_demo",
    shippingAddress: "9 Koramangala 3rd Block, Bengaluru 560034",
    trackingNumber: "EKART001122334",
    shippingCarrier: "Ekart",
    shippingFee: 0,
    platformFee: 44995,
    orderDate: daysAgo(65),
    shippingDate: daysAgo(63),
    deliveryDate: daysAgo(59),
    payoutStatus: "paid",
    createdAt: daysAgo(65),
    updatedAt: daysAgo(59),
  },
];
