import { getDefaultCurrency } from "./seed-market-config";

/**
 * Pokemon Base Set 151 — Products Seed Data
 *
 * Cards use real pokemontcg.io image URLs.
 * Image URL pattern:  https://images.pokemontcg.io/base1/{number}_hires.png
 * Base Set card numbers: 1–102 (1–16 holo rare, 17–64 non-holo / uncommon, 65–102 common / energy)
 */

import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

function toRichTextDoc(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return value;

  // Keep existing rich values unchanged (HTML or serialized ProseMirror docs).
  if (/<\/?[a-z][\s\S]*>/i.test(trimmed)) return value;
  try {
    const parsed = JSON.parse(trimmed) as { type?: string };
    if (parsed?.type === "doc") return value;
  } catch {
    // Not JSON, continue conversion.
  }

  return JSON.stringify({
    type: "doc",
    content: [
      {
        type: "paragraph",
        content: [{ type: "text", text: value }],
      },
    ],
  });
}

function withRichTextDescription(
  item: Partial<ProductDocument>,
): Partial<ProductDocument> {
  if (typeof item.description !== "string") return item;
  return {
    ...item,
    description: toRichTextDoc(item.description),
  };
}

// Seller shortcuts
const MISTY = {
  sellerId: "user-misty-water-gym-misty",
  storeId: "store-mistys-water-cards",
  sellerName: "Misty's Water Cards",
  sellerEmail: "misty@letitrip.in",
} as const;

const SURGE = {
  sellerId: "user-lt-surge-electric-surge",
  storeId: "store-surges-electric-emporium",
  sellerName: "Surge's Electric Emporium",
  sellerEmail: "surge@letitrip.in",
} as const;

const BLAINE = {
  sellerId: "user-blaine-fire-gym-blaine",
  storeId: "store-blaines-fire-shoppe",
  sellerName: "Blaine's Fire Shoppe",
  sellerEmail: "blaine@letitrip.in",
} as const;

// Helper — pokemontcg.io Base Set card image
const cardImg = (num: number) =>
  `https://images.pokemontcg.io/base1/${num}_hires.png`;

export const pokemonProductsSeedData: Partial<ProductDocument>[] = [
  // ════════════════════════════════════════════════════════════
  // HOLO RARE SINGLES (cards 1–16)
  // ════════════════════════════════════════════════════════════

  // #4 — Charizard (the crown jewel)
  {
    id: "product-charizard-base1-4-holo-rare-fire-blaine-1",
    title: "Charizard — Base Set #4 Holo Rare (Near Mint)",
    description:
      "The most iconic card in Pokémon history. First-edition Base Set Charizard in Near Mint condition. " +
      "Lightly played centering, no scratches on holo surface. Comes in a hard sleeve and top-loader.",
    slug: "charizard-base1-4-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Fire",
    brand: "Wizards of the Coast",
    price: 89999,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: cardImg(4),
    images: [cardImg(4)],
    status: "published",
    ...BLAINE,
    featured: true,
    tags: ["charizard", "holo-rare", "base-set", "fire", "1st-edition"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "4/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: [
      "Original print run",
      "Shadowless border",
      "Hard sleeve included",
    ],
    shippingInfo: "Shipped in bubble mailer with rigid top-loader.",
    returnPolicy: "3-day returns. Card must be in same condition.",
    condition: "new",
    insurance: true,
    insuranceCost: 2999,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 5.0,
    reviewCount: 3,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },

  // #2 — Blastoise
  {
    id: "product-blastoise-base1-2-holo-rare-water-misty-1",
    title: "Blastoise — Base Set #2 Holo Rare (Near Mint)",
    description:
      "Blastoise Holo Rare from the original Pokémon Base Set. Near Mint, light play centering. " +
      "A must-have Water-type collectible.",
    slug: "blastoise-base1-2-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Water",
    brand: "Wizards of the Coast",
    price: 34999,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 2,
    mainImage: cardImg(2),
    images: [cardImg(2)],
    status: "published",
    ...MISTY,
    featured: true,
    tags: ["blastoise", "holo-rare", "base-set", "water"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "2/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Classic holo shimmer", "Ships in top-loader"],
    shippingInfo: "Shipped with tracking in rigid top-loader.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 999,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    avgRating: 4.8,
    reviewCount: 5,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(3),
  },

  // #15 — Venusaur
  {
    id: "product-venusaur-base1-15-holo-rare-grass-blaine-1",
    title: "Venusaur — Base Set #15 Holo Rare (Lightly Played)",
    description:
      "Venusaur Holo Rare from Base Set. Lightly Played — minor corner wear, holo surface pristine.",
    slug: "venusaur-base1-15-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Grass",
    brand: "Wizards of the Coast",
    price: 14999,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: cardImg(15),
    images: [cardImg(15)],
    status: "published",
    ...BLAINE,
    featured: false,
    tags: ["venusaur", "holo-rare", "base-set", "grass"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "15/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Lightly Played" },
      { name: "Language", value: "English" },
    ],
    features: ["Full holo artwork", "Ships in sleeve + top-loader"],
    shippingInfo: "Tracked shipment.",
    returnPolicy: "No returns on Lightly Played.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.5,
    reviewCount: 2,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(7),
  },

  // #10 — Mewtwo
  {
    id: "product-mewtwo-base1-10-holo-rare-psychic-surge-1",
    title: "Mewtwo — Base Set #10 Holo Rare (Near Mint)",
    description:
      "The Genetic Pokémon. Mewtwo Holo Rare from the original Base Set in Near Mint condition.",
    slug: "mewtwo-base1-10-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Psychic",
    brand: "Wizards of the Coast",
    price: 19999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 3,
    mainImage: cardImg(10),
    images: [cardImg(10)],
    status: "published",
    ...SURGE,
    featured: true,
    tags: ["mewtwo", "holo-rare", "base-set", "psychic"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "10/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Near Mint condition", "Individually sleeved"],
    shippingInfo: "Flat-rate shipping with tracking.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(7),
    avgRating: 4.9,
    reviewCount: 7,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(1),
  },

  // #16 — Zapdos
  {
    id: "product-zapdos-base1-16-holo-rare-electric-surge-1",
    title: "Zapdos — Base Set #16 Holo Rare (Near Mint)",
    description:
      "Zapdos Holo Rare from Base Set. One of the three legendary birds — this one is pure Electric.",
    slug: "zapdos-base1-16-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Electric",
    brand: "Wizards of the Coast",
    price: 12999,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 2,
    mainImage: cardImg(16),
    images: [cardImg(16)],
    status: "published",
    ...SURGE,
    featured: false,
    tags: ["zapdos", "holo-rare", "base-set", "electric", "legendary"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "16/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Thunderbolt 100 damage artwork", "Top-loader shipped"],
    shippingInfo: "Tracked shipping.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.7,
    reviewCount: 4,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },

  // #3 — Chansey
  {
    id: "product-chansey-base1-3-holo-rare-colorless-misty-1",
    title: "Chansey — Base Set #3 Holo Rare (Near Mint)",
    description:
      "Chansey with 120 HP — the tankiest Base Set card. Holo Rare, Near Mint.",
    slug: "chansey-base1-3-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Colorless",
    brand: "Wizards of the Coast",
    price: 7999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 3,
    mainImage: cardImg(3),
    images: [cardImg(3)],
    status: "published",
    ...MISTY,
    featured: false,
    tags: ["chansey", "holo-rare", "base-set", "colorless"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "3/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Highest HP in Base Set", "Ships in top-loader"],
    shippingInfo: "Tracked shipment.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.6,
    reviewCount: 2,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(8),
  },

  // #6 — Gyarados
  {
    id: "product-gyarados-base1-6-holo-rare-water-misty-1",
    title: "Gyarados — Base Set #6 Holo Rare (Near Mint)",
    description:
      "The fearsome sea serpent. Gyarados Holo Rare from Base Set, Near Mint.",
    slug: "gyarados-base1-6-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Water",
    brand: "Wizards of the Coast",
    price: 9999,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 2,
    mainImage: cardImg(6),
    images: [cardImg(6)],
    status: "published",
    ...MISTY,
    featured: false,
    tags: ["gyarados", "holo-rare", "base-set", "water"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "6/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Dragon-type art on Water card", "Top-loader shipped"],
    shippingInfo: "Ships tracked.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.7,
    reviewCount: 3,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(6),
  },

  // #9 — Magneton
  {
    id: "product-magneton-base1-9-holo-rare-electric-surge-1",
    title: "Magneton — Base Set #9 Holo Rare (Lightly Played)",
    description:
      "Magneton Holo Rare, Lightly Played. Light whitening on corners, holo face clean.",
    slug: "magneton-base1-9-holo-rare",
    category: "category-holo-rare-rarity",
    subcategory: "Electric",
    brand: "Wizards of the Coast",
    price: 4499,
    currency: _CURRENCY,
    stockQuantity: 4,
    availableQuantity: 4,
    mainImage: cardImg(9),
    images: [cardImg(9)],
    status: "published",
    ...SURGE,
    featured: false,
    tags: ["magneton", "holo-rare", "base-set", "electric"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "9/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Condition", value: "Lightly Played" },
      { name: "Language", value: "English" },
    ],
    features: ["Holo pattern visible", "Penny sleeved"],
    shippingInfo: "Bubble mailer with tracking.",
    returnPolicy: "No returns LP cards.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.4,
    reviewCount: 1,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(9),
  },

  // ════════════════════════════════════════════════════════════
  // NON-HOLO RARE SINGLES
  // ════════════════════════════════════════════════════════════

  // #17 — Beedrill
  {
    id: "product-beedrill-base1-17-non-holo-rare-grass-blaine-1",
    title: "Beedrill — Base Set #17 Non-Holo Rare (Near Mint)",
    description:
      "Beedrill Non-Holo Rare. A Grass-type attacker classic from the original Base Set.",
    slug: "beedrill-base1-17-non-holo-rare",
    category: "category-non-holo-rare-rarity",
    subcategory: "Grass",
    brand: "Wizards of the Coast",
    price: 1299,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 8,
    mainImage: cardImg(17),
    images: [cardImg(17)],
    status: "published",
    ...BLAINE,
    featured: false,
    tags: ["beedrill", "non-holo-rare", "base-set", "grass"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "17/102" },
      { name: "Rarity", value: "Non-Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Ships in penny sleeve"],
    shippingInfo: "PWE or tracked bubble mailer.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.3,
    reviewCount: 1,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(10),
  },

  // #19 — Dugtrio
  {
    id: "product-dugtrio-base1-19-non-holo-rare-fighting-misty-1",
    title: "Dugtrio — Base Set #19 Non-Holo Rare (Near Mint)",
    description:
      "Dugtrio Non-Holo Rare from Base Set. Subsonic move artwork is iconic.",
    slug: "dugtrio-base1-19-non-holo-rare",
    category: "category-non-holo-rare-rarity",
    subcategory: "Fighting",
    brand: "Wizards of the Coast",
    price: 1199,
    currency: _CURRENCY,
    stockQuantity: 6,
    availableQuantity: 6,
    mainImage: cardImg(19),
    images: [cardImg(19)],
    status: "published",
    ...MISTY,
    featured: false,
    tags: ["dugtrio", "non-holo-rare", "base-set", "fighting"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "19/102" },
      { name: "Rarity", value: "Non-Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Clean copy"],
    shippingInfo: "Tracked shipping.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.2,
    reviewCount: 1,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(8),
  },

  // #24 — Haunter
  {
    id: "product-haunter-base1-24-non-holo-rare-psychic-surge-1",
    title: "Haunter — Base Set #24 Non-Holo Rare (Near Mint)",
    description:
      "Haunter Non-Holo Rare. A beloved Psychic-type card with the classic Lick attack.",
    slug: "haunter-base1-24-non-holo-rare",
    category: "category-non-holo-rare-rarity",
    subcategory: "Psychic",
    brand: "Wizards of the Coast",
    price: 1499,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 5,
    mainImage: cardImg(24),
    images: [cardImg(24)],
    status: "published",
    ...SURGE,
    featured: false,
    tags: ["haunter", "non-holo-rare", "base-set", "psychic"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "24/102" },
      { name: "Rarity", value: "Non-Holo Rare" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Classic tongue-out artwork", "Penny sleeved"],
    shippingInfo: "Tracked bubble mailer.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.5,
    reviewCount: 2,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(7),
  },

  // ════════════════════════════════════════════════════════════
  // UNCOMMON SINGLES
  // ════════════════════════════════════════════════════════════

  // #35 — Clefairy
  {
    id: "product-clefairy-base1-35-uncommon-colorless-misty-1",
    title: "Clefairy — Base Set #35 Uncommon (Near Mint)",
    description:
      "Clefairy Uncommon from Base Set. Uses Metronome — a nostalgic fan favourite.",
    slug: "clefairy-base1-35-uncommon",
    category: "category-uncommon-rarity",
    subcategory: "Colorless",
    brand: "Wizards of the Coast",
    price: 799,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 12,
    mainImage: cardImg(35),
    images: [cardImg(35)],
    status: "published",
    ...MISTY,
    featured: false,
    tags: ["clefairy", "uncommon", "base-set", "colorless"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "35/102" },
      { name: "Rarity", value: "Uncommon" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Penny sleeved"],
    shippingInfo: "PWE with tracking.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.4,
    reviewCount: 2,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(5),
  },

  // #40 — Growlithe
  {
    id: "product-growlithe-base1-40-uncommon-fire-blaine-1",
    title: "Growlithe — Base Set #40 Uncommon (Near Mint)",
    description:
      "Growlithe Uncommon from Base Set. A loyal Fire-type favourite.",
    slug: "growlithe-base1-40-uncommon",
    category: "category-uncommon-rarity",
    subcategory: "Fire",
    brand: "Wizards of the Coast",
    price: 699,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 15,
    mainImage: cardImg(40),
    images: [cardImg(40)],
    status: "published",
    ...BLAINE,
    featured: false,
    tags: ["growlithe", "uncommon", "base-set", "fire"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "40/102" },
      { name: "Rarity", value: "Uncommon" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Cheap filler for Fire decks"],
    shippingInfo: "PWE shipping.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.2,
    reviewCount: 1,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(4),
  },

  // #52 — Pikachu
  {
    id: "product-pikachu-base1-58-common-electric-surge-1",
    title: "Pikachu — Base Set #58 Common (Near Mint)",
    description:
      "The Pokémon mascot himself. Base Set Pikachu, Common, Near Mint — yellow cheeks version.",
    slug: "pikachu-base1-58-common",
    category: "category-common-rarity",
    subcategory: "Electric",
    brand: "Wizards of the Coast",
    price: 1999,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 20,
    mainImage: cardImg(58),
    images: [cardImg(58)],
    status: "published",
    ...SURGE,
    featured: true,
    tags: ["pikachu", "common", "base-set", "electric", "yellow-cheeks"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "58/102" },
      { name: "Rarity", value: "Common" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
      { name: "Variant", value: "Yellow Cheeks" },
    ],
    features: ["Mascot card", "Yellow cheeks variant", "Penny sleeved"],
    shippingInfo: "Tracked bubble mailer.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(21),
    avgRating: 4.9,
    reviewCount: 10,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(1),
  },

  // ════════════════════════════════════════════════════════════
  // TRAINER CARDS
  // ════════════════════════════════════════════════════════════

  // #88 — Professor Oak
  {
    id: "product-professor-oak-base1-88-uncommon-trainer-surge-1",
    title: "Professor Oak — Base Set #88 Trainer (Near Mint)",
    description:
      "Draw 7 cards. Professor Oak is one of the most powerful Trainer cards ever printed. Near Mint copy.",
    slug: "professor-oak-base1-88-trainer",
    category: "category-trainer-type-card-type",
    subcategory: "Trainer",
    brand: "Wizards of the Coast",
    price: 2499,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 10,
    mainImage: cardImg(88),
    images: [cardImg(88)],
    status: "published",
    ...SURGE,
    featured: true,
    tags: ["professor-oak", "trainer", "base-set", "draw"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "88/102" },
      { name: "Rarity", value: "Uncommon" },
      { name: "Card Type", value: "Trainer" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Staple competitive card", "Draw 7"],
    shippingInfo: "Tracked shipping.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.8,
    reviewCount: 6,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(5),
  },

  // #91 — Energy Retrieval
  {
    id: "product-energy-retrieval-base1-91-common-trainer-misty-1",
    title: "Energy Retrieval — Base Set #91 Trainer (Near Mint)",
    description:
      "Return 2 Basic Energy from discard to hand. A staple in Water decks. Near Mint.",
    slug: "energy-retrieval-base1-91-trainer",
    category: "category-trainer-type-card-type",
    subcategory: "Trainer",
    brand: "Wizards of the Coast",
    price: 599,
    currency: _CURRENCY,
    stockQuantity: 25,
    availableQuantity: 25,
    mainImage: cardImg(91),
    images: [cardImg(91)],
    status: "published",
    ...MISTY,
    featured: false,
    tags: ["energy-retrieval", "trainer", "base-set"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "91/102" },
      { name: "Rarity", value: "Common" },
      { name: "Card Type", value: "Trainer" },
      { name: "Condition", value: "Near Mint" },
      { name: "Language", value: "English" },
    ],
    features: ["Deck staple", "Shipped in PWE"],
    shippingInfo: "PWE or tracked.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.3,
    reviewCount: 2,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(6),
  },

  // ════════════════════════════════════════════════════════════
  // ENERGY CARDS
  // ════════════════════════════════════════════════════════════

  // #99 — Water Energy (x10 lot)
  {
    id: "product-water-energy-base1-99-common-energy-misty-lot",
    title: "Water Energy — Base Set #99 x10 Lot (Near Mint)",
    description:
      "10× Water Energy from the original Base Set. Near Mint. Perfect for deck building.",
    slug: "water-energy-base1-99-x10-lot",
    category: "category-energy-type-card-type",
    subcategory: "Water",
    brand: "Wizards of the Coast",
    price: 999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage: cardImg(99),
    images: [cardImg(99)],
    status: "published",
    ...MISTY,
    featured: false,
    tags: ["water-energy", "energy", "base-set", "lot"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "99/102" },
      { name: "Rarity", value: "Common" },
      { name: "Card Type", value: "Basic Energy" },
      { name: "Condition", value: "Near Mint" },
      { name: "Quantity", value: "10 cards" },
      { name: "Language", value: "English" },
    ],
    features: ["10 cards per order", "Ideal for Blastoise/Lapras decks"],
    shippingInfo: "Shipped in team bag in bubble mailer.",
    returnPolicy: "No returns on bulk lots.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.6,
    reviewCount: 4,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(3),
  },

  // #100 — Fire Energy (x10 lot)
  {
    id: "product-fire-energy-base1-100-common-energy-blaine-lot",
    title: "Fire Energy — Base Set #100 x10 Lot (Near Mint)",
    description:
      "10× Fire Energy from Base Set. Perfect for Charizard and Arcanine decks.",
    slug: "fire-energy-base1-100-x10-lot",
    category: "category-energy-type-card-type",
    subcategory: "Fire",
    brand: "Wizards of the Coast",
    price: 999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage: cardImg(100),
    images: [cardImg(100)],
    status: "published",
    ...BLAINE,
    featured: false,
    tags: ["fire-energy", "energy", "base-set", "lot"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "100/102" },
      { name: "Rarity", value: "Common" },
      { name: "Card Type", value: "Basic Energy" },
      { name: "Condition", value: "Near Mint" },
      { name: "Quantity", value: "10 cards" },
      { name: "Language", value: "English" },
    ],
    features: ["10 cards per order", "Ideal for Charizard/Arcanine decks"],
    shippingInfo: "Bubble mailer.",
    returnPolicy: "No returns on bulk lots.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.5,
    reviewCount: 3,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(2),
  },

  // #101 — Lightning Energy (x10 lot)
  {
    id: "product-lightning-energy-base1-101-common-energy-surge-lot",
    title: "Lightning Energy — Base Set #101 x10 Lot (Near Mint)",
    description:
      "10× Lightning (Electric) Energy from Base Set. Fuel for Pikachu, Raichu, and Zapdos.",
    slug: "lightning-energy-base1-101-x10-lot",
    category: "category-energy-type-card-type",
    subcategory: "Electric",
    brand: "Wizards of the Coast",
    price: 999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 50,
    mainImage: cardImg(101),
    images: [cardImg(101)],
    status: "published",
    ...SURGE,
    featured: false,
    tags: ["lightning-energy", "energy", "base-set", "lot", "electric"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "101/102" },
      { name: "Rarity", value: "Common" },
      { name: "Card Type", value: "Basic Energy" },
      { name: "Condition", value: "Near Mint" },
      { name: "Quantity", value: "10 cards" },
      { name: "Language", value: "English" },
    ],
    features: ["10 cards per order"],
    shippingInfo: "Bubble mailer.",
    returnPolicy: "No returns on bulk lots.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.5,
    reviewCount: 2,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
  },

  // ════════════════════════════════════════════════════════════
  // SEALED PRODUCTS
  // ════════════════════════════════════════════════════════════

  // Booster Pack
  {
    id: "product-base-set-booster-pack-sealed-blaine-1",
    title: "Pokémon Base Set Booster Pack (Sealed, Random Art)",
    description:
      "Sealed Pokémon TCG Base Set booster pack with 11 cards and one guaranteed rare. " +
      "Perfect for vintage collectors searching for authentic Base Set pack openings and long-term sealed investments.",
    slug: "pokemon-tcg-base-set-sealed-booster-pack-random-art",
    category: "category-sealed-products",
    subcategory: "Booster Pack",
    brand: "Wizards of the Coast",
    price: 12999,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 10,
    mainImage: cardImg(4),
    images: [cardImg(4), cardImg(2), cardImg(15)],
    status: "published",
    ...BLAINE,
    featured: true,
    tags: ["sealed", "booster-pack", "base-set"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Product Type", value: "Booster Pack" },
      { name: "Cards per Pack", value: "11" },
      { name: "Condition", value: "Sealed" },
    ],
    features: ["Factory sealed", "11 cards per pack", "1 guaranteed rare"],
    shippingInfo: "Bubble wrapped and shipped in rigid box.",
    returnPolicy: "No returns on opened sealed product.",
    condition: "new",
    insurance: true,
    insuranceCost: 499,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    avgRating: 4.8,
    reviewCount: 8,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(2),
  },

  // Theme Deck — Zap! (Raichu / Electric)
  {
    id: "product-zap-theme-deck-sealed-surge-1",
    title: "Pokémon Base Set 'Zap!' Theme Deck (Sealed)",
    description:
      "Factory-sealed Pokémon Base Set Zap! Theme Deck featuring Electric-type strategy cards led by Raichu. " +
      "Ideal for collectors who want original sealed WOTC era deck products.",
    slug: "pokemon-base-set-zap-theme-deck-sealed-raichu",
    category: "category-sealed-products",
    subcategory: "Theme Deck",
    brand: "Wizards of the Coast",
    price: 18999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 3,
    mainImage: cardImg(14),
    images: [cardImg(14), cardImg(16), cardImg(58)],
    status: "published",
    ...SURGE,
    featured: false,
    tags: ["sealed", "theme-deck", "base-set", "electric", "raichu"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Product Type", value: "Theme Deck" },
      { name: "Deck Name", value: "Zap!" },
      { name: "Condition", value: "Sealed" },
    ],
    features: ["Factory sealed", "30-card pre-built deck", "Electric strategy"],
    shippingInfo: "Rigid box mailer with bubble wrap.",
    returnPolicy: "No returns on opened sealed product.",
    condition: "new",
    insurance: true,
    insuranceCost: 699,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.7,
    reviewCount: 3,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(4),
  },

  // ════════════════════════════════════════════════════════════
  // ACCESSORIES
  // ════════════════════════════════════════════════════════════

  {
    id: "product-pokemon-card-sleeves-standard-blaine-1",
    title: "Pokémon-Art Card Sleeves (100-pack, Pikachu)",
    description:
      "100 standard-size card sleeves featuring Pikachu artwork. Compatible with all Base Set singles.",
    slug: "pokemon-pikachu-card-sleeves-100pack",
    category: "category-accessories",
    subcategory: "Card Sleeves",
    brand: "Ultra PRO",
    price: 699,
    currency: _CURRENCY,
    stockQuantity: 100,
    availableQuantity: 100,
    mainImage: "https://images.pokemontcg.io/base1/58_hires.png",
    images: ["https://images.pokemontcg.io/base1/58_hires.png"],
    status: "published",
    ...BLAINE,
    featured: false,
    tags: ["sleeves", "accessories", "pikachu", "ultra-pro"],
    specifications: [
      { name: "Brand", value: "Ultra PRO" },
      { name: "Quantity", value: "100 sleeves" },
      { name: "Size", value: "Standard (66 × 91 mm)" },
      { name: "Art", value: "Pikachu" },
    ],
    features: ["Acid-free", "Archival quality", "Fits Base Set cards"],
    shippingInfo: "Small parcel shipping.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.6,
    reviewCount: 5,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-pokemon-9-pocket-binder-misty-1",
    title: "Pokémon 9-Pocket Binder (360 cards, Charizard Cover)",
    description:
      "9-pocket binder for storing and displaying up to 360 Pokémon cards. Charizard cover art.",
    slug: "pokemon-charizard-9-pocket-binder",
    category: "category-accessories",
    subcategory: "Binder",
    brand: "Ultra PRO",
    price: 1499,
    currency: _CURRENCY,
    stockQuantity: 30,
    availableQuantity: 30,
    mainImage: "https://images.pokemontcg.io/base1/4_hires.png",
    images: ["https://images.pokemontcg.io/base1/4_hires.png"],
    status: "published",
    ...MISTY,
    featured: false,
    tags: ["binder", "accessories", "charizard", "storage"],
    specifications: [
      { name: "Brand", value: "Ultra PRO" },
      { name: "Capacity", value: "360 cards" },
      { name: "Pockets per Page", value: "9" },
      { name: "Art", value: "Charizard" },
    ],
    features: ["360-card capacity", "Side-loading pockets", "Lay-flat design"],
    shippingInfo: "Shipped in box.",
    returnPolicy: "7-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPromoted: false,
    avgRating: 4.7,
    reviewCount: 7,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },

  // ════════════════════════════════════════════════════════════
  // AUCTION LISTINGS
  // ════════════════════════════════════════════════════════════

  // Auction: 1st Edition Charizard
  {
    id: "auction-charizard-1st-ed-base1-4-fire-blaine-auction-1",
    title: "1st Edition Charizard — Base Set #4 Holo (AUCTION, PSA 7)",
    description:
      "Ultra-rare 1st Edition Charizard from Base Set, PSA-graded 7 (Near Mint). This is your chance to own the holy grail.",
    slug: "auction-charizard-1st-ed-psa7",
    category: "category-holo-rare-rarity",
    subcategory: "Fire",
    brand: "Wizards of the Coast",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: cardImg(4),
    images: [cardImg(4)],
    status: "published",
    ...BLAINE,
    featured: true,
    tags: [
      "charizard",
      "1st-edition",
      "holo-rare",
      "base-set",
      "fire",
      "auction",
      "psa",
    ],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "4/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Edition", value: "1st Edition" },
      { name: "Grade", value: "PSA 7" },
      { name: "Language", value: "English" },
    ],
    features: [
      "PSA graded slab",
      "1st Edition stamp",
      "The most iconic card in TCG history",
    ],
    shippingInfo: "Insured courier with tracking.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 4999,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(7),
    startingBid: 299999,
    currentBid: 349999,
    bidCount: 14,
    reservePrice: 350000,
    buyNowPrice: 699999,
    minBidIncrement: 5000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: daysAhead(7),
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: daysAhead(7),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
  },

  // Auction: Mewtwo PSA 9
  {
    id: "auction-mewtwo-base1-10-psychic-surge-auction-1",
    title: "Mewtwo — Base Set #10 Holo (AUCTION, PSA 9)",
    description:
      "PSA-graded 9 (Mint) Mewtwo Holo from Base Set. A landmark Psychic-type collector piece.",
    slug: "auction-mewtwo-psa9",
    category: "category-holo-rare-rarity",
    subcategory: "Psychic",
    brand: "Wizards of the Coast",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: cardImg(10),
    images: [cardImg(10)],
    status: "published",
    ...SURGE,
    featured: true,
    tags: ["mewtwo", "holo-rare", "base-set", "psychic", "auction", "psa"],
    specifications: [
      { name: "Set", value: "Base Set" },
      { name: "Card Number", value: "10/102" },
      { name: "Rarity", value: "Holo Rare" },
      { name: "Grade", value: "PSA 9" },
      { name: "Language", value: "English" },
    ],
    features: ["PSA 9 Mint slab", "Psychic powerhouse"],
    shippingInfo: "Insured courier.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 2999,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(5),
    startingBid: 49999,
    currentBid: 54999,
    bidCount: 6,
    reservePrice: 55000,
    buyNowPrice: 99999,
    minBidIncrement: 2500,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionOriginalEndDate: daysAhead(5),
    auctionShippingPaidBy: "winner",
    isPromoted: true,
    promotionEndDate: daysAhead(5),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
  },
].map((item) => withRichTextDescription(item as Partial<ProductDocument>));
