import { getDefaultPhonePrefix } from "./seed-market-config";

/**
 * Multi-Franchise Collectibles — Users Seed Data
 * 1 admin + 5 sellers (store-permitted) + 10 active buyers + 2 banned = 18 users
 */

import type { UserDocument } from "../features/auth/schemas";

const _phonePrefix = getDefaultPhonePrefix();

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const emptyStats = { totalOrders: 0, auctionsWon: 0, itemsSold: 0, reviewsCount: 0 };

export const pokemonUsersSeedData: Partial<UserDocument>[] = [

  // ─── ADMIN ──────────────────────────────────────────────────────────────────
  {
    uid: "user-admin-user-admin",
    email: "admin@letitrip.in",
    phoneNumber: `${_phonePrefix}9876543210`,
    phoneVerified: true,
    displayName: "Admin User",
    photoURL: null,
    avatarMetadata: null,
    role: "admin",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
    publicProfile: {
      isPublic: false, showEmail: false, showPhone: false,
      showOrders: false, showWishlist: false,
      bio: "System Administrator",
    },
    stats: emptyStats,
    metadata: { lastSignInTime: daysAgo(1), creationTime: daysAgo(365).toISOString(), loginCount: 200 },
  },

  // ─── SELLERS ────────────────────────────────────────────────────────────────

  // 1. Misty — Water-type Pokémon cards
  {
    uid: "user-misty-water-gym-misty",
    email: "misty@letitrip.in",
    phoneNumber: `${_phonePrefix}9000000001`,
    phoneVerified: true,
    displayName: "Misty (Water Gym)",
    photoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
    storeId: "store-mistys-water-cards",
    storeSlug: "mistys-water-cards",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true, showEmail: true, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Cerulean City Gym Leader. I specialise in Water-type Pokémon cards from the original Base Set.",
      storeName: "Misty's Water Cards",
      storeDescription: "The best source for Water-type Base Set singles — Blastoise, Lapras, Starmie and more.",
      storeLogoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png",
      storeBannerURL: "https://images.pokemontcg.io/base1/2_hires.png",
      storeReturnPolicy: "7-day returns on all NM cards.",
      storeShippingPolicy: "Ships in top-loaders with tracking.",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 45, reviewsCount: 12 },
    metadata: { lastSignInTime: daysAgo(2), creationTime: daysAgo(180).toISOString(), loginCount: 89 },
  },

  // 2. Lt. Surge — Electric-type Pokémon cards
  {
    uid: "user-lt-surge-electric-surge",
    email: "surge@letitrip.in",
    phoneNumber: `${_phonePrefix}9000000002`,
    phoneVerified: true,
    displayName: "Lt. Surge (Electric Gym)",
    photoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(3),
    storeId: "store-surges-electric-emporium",
    storeSlug: "surges-electric-emporium",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true, showEmail: true, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Vermilion City Gym Leader. Electric-type specialists — Pikachu, Raichu, Zapdos.",
      storeName: "Surge's Electric Emporium",
      storeDescription: "Vermilion City's Electric-type marketplace for Pikachu, Raichu and Zapdos collectors.",
      storeLogoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
      storeBannerURL: "https://images.pokemontcg.io/base1/16_hires.png",
      storeReturnPolicy: "7-day returns.",
      storeShippingPolicy: "Ships with bubble wrap and tracking.",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 70, reviewsCount: 22 },
    metadata: { lastSignInTime: daysAgo(3), creationTime: daysAgo(200).toISOString(), loginCount: 120 },
  },

  // 3. Blaine — Fire-type Pokémon cards
  {
    uid: "user-blaine-fire-gym-blaine",
    email: "blaine@letitrip.in",
    phoneNumber: `${_phonePrefix}9000000003`,
    phoneVerified: true,
    displayName: "Blaine (Fire Gym)",
    photoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(220),
    updatedAt: daysAgo(1),
    storeId: "store-blaines-fire-shoppe",
    storeSlug: "blaines-fire-shoppe",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true, showEmail: true, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Cinnabar Island Gym Leader. Fire-type specialist — Charizard, Arcanine, Moltres.",
      storeName: "Blaine's Fire Shoppe",
      storeDescription: "Cinnabar Island's premier Fire-type card shop. Charizard, Ninetales, Moltres.",
      storeLogoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
      storeBannerURL: "https://images.pokemontcg.io/base1/4_hires.png",
      storeReturnPolicy: "3-day returns. Card must be in same condition.",
      storeShippingPolicy: "Shipped in rigid top-loader + bubble mailer with insurance.",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 38, reviewsCount: 15 },
    metadata: { lastSignInTime: daysAgo(1), creationTime: daysAgo(220).toISOString(), loginCount: 95 },
  },

  // 4. Speed King — Hot Wheels + Transformers
  {
    uid: "user-speed-king-diecast",
    email: "speedking@letitrip.in",
    phoneNumber: `${_phonePrefix}9000000004`,
    phoneVerified: true,
    displayName: "Speed King Diecast",
    photoURL: "https://picsum.photos/seed/speedking-avatar/200/200",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
    storeId: "store-speed-king-diecast",
    storeSlug: "speed-king-diecast",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true, showEmail: true, showPhone: false, showOrders: false, showWishlist: true,
      bio: "India's largest Hot Wheels collector and reseller. Treasure Hunts, Car Culture, and Transformers.",
      storeName: "Speed King Diecast",
      storeDescription: "Premium Hot Wheels and Transformers collectibles — Treasure Hunts, Car Culture, and G1 figures.",
      storeLogoURL: "https://picsum.photos/seed/speedking-logo/200/200",
      storeBannerURL: "https://picsum.photos/seed/speedking-banner/1200/400",
      storeReturnPolicy: "10-day hassle-free returns on all sealed items.",
      storeShippingPolicy: "Bubble-packed in rigid box. PAN India delivery with tracking.",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 215, reviewsCount: 67 },
    metadata: { lastSignInTime: daysAgo(1), creationTime: daysAgo(90).toISOString(), loginCount: 310 },
  },

  // 5. Bladers Paradise — Beyblade Burst + Transformers
  {
    uid: "user-bladers-paradise",
    email: "bladers@letitrip.in",
    phoneNumber: `${_phonePrefix}9000000005`,
    phoneVerified: true,
    displayName: "Bladers Paradise",
    photoURL: "https://picsum.photos/seed/bladers-avatar/200/200",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(2),
    storeId: "store-bladers-paradise",
    storeSlug: "bladers-paradise",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true, showEmail: true, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Beyblade Burst specialist. Attack, Defense, Stamina and Balance types — all series.",
      storeName: "Bladers Paradise",
      storeDescription: "Your one-stop shop for Beyblade Burst tops, stadiums, launchers, and accessories.",
      storeLogoURL: "https://picsum.photos/seed/bladers-logo/200/200",
      storeBannerURL: "https://picsum.photos/seed/bladers-banner/1200/400",
      storeReturnPolicy: "7-day returns for unopened items.",
      storeShippingPolicy: "Padded boxes, nationwide delivery in 3–5 business days.",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 143, reviewsCount: 48 },
    metadata: { lastSignInTime: daysAgo(2), creationTime: daysAgo(120).toISOString(), loginCount: 178 },
  },

  // ─── ACTIVE BUYERS (10) ─────────────────────────────────────────────────────

  {
    uid: "user-ash-ketchum-buyer",
    email: "ash.ketchum@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000001`,
    phoneVerified: false,
    displayName: "Ash Ketchum",
    photoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Pokémon Master in training. Collecting every holo rare from Base Set 151.",
    },
    stats: { totalOrders: 8, auctionsWon: 2, itemsSold: 0, reviewsCount: 5 },
    metadata: { lastSignInTime: daysAgo(5), creationTime: daysAgo(120).toISOString(), loginCount: 34 },
  },

  {
    uid: "user-brock-pewter-buyer",
    email: "brock.pewter@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000002`,
    phoneVerified: true,
    displayName: "Brock Pewter",
    photoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(95),
    updatedAt: daysAgo(8),
    publicProfile: {
      isPublic: false, showEmail: false, showPhone: false, showOrders: false, showWishlist: false,
      bio: "Rock-type trainer looking for Onix and Geodude singles.",
    },
    stats: { totalOrders: 4, auctionsWon: 0, itemsSold: 0, reviewsCount: 2 },
    metadata: { lastSignInTime: daysAgo(8), creationTime: daysAgo(95).toISOString(), loginCount: 18 },
  },

  {
    uid: "user-gary-oak-buyer",
    email: "gary.oak@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000003`,
    phoneVerified: true,
    displayName: "Gary Oak",
    photoURL: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: true, showWishlist: true,
      bio: "Smell ya later! Collecting PSA 10 graded Base Set Holo Rares.",
    },
    stats: { totalOrders: 22, auctionsWon: 5, itemsSold: 0, reviewsCount: 18 },
    metadata: { lastSignInTime: daysAgo(3), creationTime: daysAgo(150).toISOString(), loginCount: 87 },
  },

  {
    uid: "user-dawn-sinnoh-buyer",
    email: "dawn.sinnoh@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000004`,
    phoneVerified: false,
    displayName: "Dawn (Sinnoh)",
    photoURL: "https://picsum.photos/seed/dawn-avatar/200/200",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(12),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Pokémon Coordinator and Hot Wheels collector — especially Japanese exclusives.",
    },
    stats: { totalOrders: 6, auctionsWon: 1, itemsSold: 0, reviewsCount: 3 },
    metadata: { lastSignInTime: daysAgo(12), creationTime: daysAgo(60).toISOString(), loginCount: 22 },
  },

  {
    uid: "user-may-hoenn-buyer",
    email: "may.hoenn@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000005`,
    phoneVerified: true,
    displayName: "May (Hoenn)",
    photoURL: "https://picsum.photos/seed/may-avatar/200/200",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(7),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Hoenn Coordinator. Building a complete Grass-type Base Set collection.",
    },
    stats: { totalOrders: 11, auctionsWon: 0, itemsSold: 0, reviewsCount: 7 },
    metadata: { lastSignInTime: daysAgo(7), creationTime: daysAgo(75).toISOString(), loginCount: 41 },
  },

  {
    uid: "user-wheels-king-hw",
    email: "wheels.king@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000006`,
    phoneVerified: true,
    displayName: "Wheels King",
    photoURL: "https://picsum.photos/seed/wheelsking-avatar/200/200",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Hardcore Hot Wheels Super Treasure Hunt hunter. 500+ in collection.",
    },
    stats: { totalOrders: 31, auctionsWon: 7, itemsSold: 0, reviewsCount: 24 },
    metadata: { lastSignInTime: daysAgo(2), creationTime: daysAgo(45).toISOString(), loginCount: 156 },
  },

  {
    uid: "user-metal-hiro-beyblade",
    email: "metal.hiro@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000007`,
    phoneVerified: true,
    displayName: "Metal Hiro",
    photoURL: "https://picsum.photos/seed/metalhiro-avatar/200/200",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(4),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Beyblade Burst GT champion. Let it rip! Collecting all limited edition tops.",
    },
    stats: { totalOrders: 14, auctionsWon: 3, itemsSold: 0, reviewsCount: 11 },
    metadata: { lastSignInTime: daysAgo(4), creationTime: daysAgo(30).toISOString(), loginCount: 67 },
  },

  {
    uid: "user-optimus-collector",
    email: "optimus.collector@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000008`,
    phoneVerified: false,
    displayName: "Optimus Collector",
    photoURL: "https://picsum.photos/seed/optimus-avatar/200/200",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(9),
    publicProfile: {
      isPublic: false, showEmail: false, showPhone: false, showOrders: false, showWishlist: false,
      bio: "G1 Transformers purist. Looking for MISB 1984 originals.",
    },
    stats: { totalOrders: 9, auctionsWon: 4, itemsSold: 0, reviewsCount: 6 },
    metadata: { lastSignInTime: daysAgo(9), creationTime: daysAgo(55).toISOString(), loginCount: 29 },
  },

  {
    uid: "user-riku-beyblade-fan",
    email: "riku.blader@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000009`,
    phoneVerified: true,
    displayName: "Riku Blader",
    photoURL: "https://picsum.photos/seed/riku-avatar/200/200",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(6),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Stamina-type Beyblade expert. Longinus and Neptune main.",
    },
    stats: { totalOrders: 7, auctionsWon: 1, itemsSold: 0, reviewsCount: 5 },
    metadata: { lastSignInTime: daysAgo(6), creationTime: daysAgo(40).toISOString(), loginCount: 33 },
  },

  {
    uid: "user-priya-collector",
    email: "priya.collector@letitrip.in",
    phoneNumber: `${_phonePrefix}9100000010`,
    phoneVerified: true,
    displayName: "Priya Collector",
    photoURL: "https://picsum.photos/seed/priya-avatar/200/200",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    createdAt: daysAgo(85),
    updatedAt: daysAgo(14),
    publicProfile: {
      isPublic: true, showEmail: false, showPhone: false, showOrders: false, showWishlist: true,
      bio: "Multi-hobby collector — Pokémon, Hot Wheels, and Transformers. PSA grader too.",
    },
    stats: { totalOrders: 18, auctionsWon: 2, itemsSold: 0, reviewsCount: 14 },
    metadata: { lastSignInTime: daysAgo(14), creationTime: daysAgo(85).toISOString(), loginCount: 62 },
  },

  // ─── BANNED USERS (2) ───────────────────────────────────────────────────────

  {
    uid: "user-banned-scammer-001",
    email: "fake.seller.banned@example.com",
    phoneNumber: `${_phonePrefix}9999000001`,
    phoneVerified: false,
    displayName: "Banned User 001",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: false,
    disabled: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(30),
    publicProfile: {
      isPublic: false, showEmail: false, showPhone: false, showOrders: false, showWishlist: false,
      bio: "",
    },
    stats: emptyStats,
    metadata: { lastSignInTime: daysAgo(31), creationTime: daysAgo(90).toISOString(), loginCount: 12 },
  },

  {
    uid: "user-banned-fraud-002",
    email: "fraud.buyer.banned@example.com",
    phoneNumber: `${_phonePrefix}9999000002`,
    phoneVerified: false,
    displayName: "Banned User 002",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: false,
    disabled: true,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(15),
    publicProfile: {
      isPublic: false, showEmail: false, showPhone: false, showOrders: false, showWishlist: false,
      bio: "",
    },
    stats: emptyStats,
    metadata: { lastSignInTime: daysAgo(16), creationTime: daysAgo(60).toISOString(), loginCount: 8 },
  },
];
