/**
 * Pokemon Base Set 151 — Categories Seed Data
 *
 * Hierarchy:
 *   Pokémon Cards (root)
 *     ├- Card Type (tier 1)
 *     │    ├- Pokémon Cards (leaf)
 *     │    ├- Trainer Cards (leaf)
 *     │    └- Energy Cards (leaf)
 *     ├- Element Type (tier 1)
 *     │    ├- Water (leaf)
 *     │    ├- Electric (leaf)
 *     │    ├- Fire (leaf)
 *     │    ├- Grass (leaf)
 *     │    ├- Psychic (leaf)
 *     │    ├- Fighting (leaf)
 *     │    └- Colorless (leaf)
 *     ├- Rarity (tier 1)
 *     │    ├- Holographic Rare (leaf)
 *     │    ├- Non-Holo Rare (leaf)
 *     │    ├- Uncommon (leaf)
 *     │    └- Common (leaf)
 *   Sealed Products (root, leaf)
 *   Accessories (root, leaf)
 */

import type { CategoryDocument } from "../features/categories/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const ADMIN = "user-admin-user-admin";

export const pokemonCategoriesSeedData: Partial<CategoryDocument>[] = [
  // -- ROOT: Pokémon Cards -----------------------------------------------------
  {
    id: "category-pokemon-cards",
    name: "Pokémon Cards",
    slug: "pokemon-cards",
    description:
      "Original Pokémon Base Set 151 cards — singles, lots, and graded copies",
    rootId: "category-pokemon-cards",
    parentIds: [],
    childrenIds: [
      "category-card-type-pokemon-cards",
      "category-element-type-pokemon-cards",
      "category-rarity-pokemon-cards",
    ],
    tier: 0,
    path: "pokemon-cards",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 60,
      totalAuctionCount: 5,
      totalItemCount: 65,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 1,
    isBrand: false,
    seo: {
      title: "Pokémon Cards — Base Set 151 | LetItRip",
      description:
        "Buy and sell original Pokémon Base Set 151 singles, holos, and sealed packs.",
      keywords: ["pokemon cards", "base set", "151", "charizard", "pikachu"],
    },
    display: {
      showInFooter: true,
      icon: "🃏",
      coverImage: "https://images.pokemontcg.io/base1/logo.png",
      color: "#FFCB05",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- TIER 1: Card Type -------------------------------------------------------
  {
    id: "category-card-type-pokemon-cards",
    name: "Card Type",
    slug: "card-type",
    description: "Filter by Pokémon, Trainer, or Energy",
    rootId: "category-pokemon-cards",
    parentIds: ["category-pokemon-cards"],
    childrenIds: [
      "category-pokemon-type-card-type",
      "category-trainer-type-card-type",
      "category-energy-type-card-type",
    ],
    tier: 1,
    path: "pokemon-cards/card-type",
    order: 1,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 40,
      totalAuctionCount: 3,
      totalItemCount: 43,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Card Type — Pokémon Base Set 151",
      description: "Shop by Pokémon, Trainer, or Energy card type.",
      keywords: ["pokemon card type", "trainer card", "energy card"],
    },
    display: { showInFooter: false, icon: "🎴", showInMenu: true },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Pokémon-type cards ------------------------------------------------
  {
    id: "category-pokemon-type-card-type",
    name: "Pokémon Cards",
    slug: "pokemon-type",
    description: "Individual creature cards — the core of the Base Set",
    rootId: "category-pokemon-cards",
    parentIds: ["category-card-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/card-type/pokemon-type",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 30,
      productIds: [],
      auctionCount: 3,
      auctionIds: [],
      totalProductCount: 30,
      totalAuctionCount: 3,
      totalItemCount: 33,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 2,
    isBrand: false,
    seo: {
      title: "Pokémon Cards — Base Set Singles",
      description: "Shop all 102 Pokémon Base Set creature singles.",
      keywords: [
        "pokemon singles",
        "base set pokemon",
        "charizard",
        "blastoise",
      ],
    },
    display: {
      showInFooter: false,
      icon: "⚡",
      coverImage: "https://images.pokemontcg.io/base1/4_hires.png",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      { id: "category-card-type-pokemon-cards", name: "Card Type", tier: 1 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Trainer cards -----------------------------------------------------
  {
    id: "category-trainer-type-card-type",
    name: "Trainer Cards",
    slug: "trainer-type",
    description: "Supporter, Item, and Stadium trainer cards from Base Set",
    rootId: "category-pokemon-cards",
    parentIds: ["category-card-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/card-type/trainer-type",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 8,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 8,
      totalAuctionCount: 0,
      totalItemCount: 8,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Trainer Cards — Base Set",
      description:
        "Professor Oak, Bill, Energy Retrieval and more Base Set trainer cards.",
      keywords: ["trainer cards", "professor oak", "bill", "pokemon trainer"],
    },
    display: {
      showInFooter: false,
      icon: "🧑‍🏫",
      coverImage: "https://images.pokemontcg.io/base1/88_hires.png",
      showInMenu: true,
    },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      { id: "category-card-type-pokemon-cards", name: "Card Type", tier: 1 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Energy cards ------------------------------------------------------
  {
    id: "category-energy-type-card-type",
    name: "Energy Cards",
    slug: "energy-type",
    description:
      "Basic Energy cards — Water, Fire, Electric, Grass, Psychic, Fighting",
    rootId: "category-pokemon-cards",
    parentIds: ["category-card-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/card-type/energy-type",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 6,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 6,
      totalAuctionCount: 0,
      totalItemCount: 6,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Energy Cards — Base Set",
      description: "All basic energy types from the original Pokémon Base Set.",
      keywords: [
        "energy cards",
        "water energy",
        "fire energy",
        "pokemon energy",
      ],
    },
    display: {
      showInFooter: false,
      icon: "⚡",
      coverImage: "https://images.pokemontcg.io/base1/99_hires.png",
      showInMenu: true,
    },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      { id: "category-card-type-pokemon-cards", name: "Card Type", tier: 1 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- TIER 1: Element Type ----------------------------------------------------
  {
    id: "category-element-type-pokemon-cards",
    name: "Element Type",
    slug: "element-type",
    description: "Browse cards by elemental type",
    rootId: "category-pokemon-cards",
    parentIds: ["category-pokemon-cards"],
    childrenIds: [
      "category-water-element-type",
      "category-electric-element-type",
      "category-fire-element-type",
      "category-grass-element-type",
      "category-psychic-element-type",
      "category-fighting-element-type",
      "category-colorless-element-type",
    ],
    tier: 1,
    path: "pokemon-cards/element-type",
    order: 2,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 35,
      totalAuctionCount: 2,
      totalItemCount: 37,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Element Types — Pokémon Base Set",
      description: "Water, Electric, Fire, Grass, Psychic, Fighting, Colorless",
      keywords: [
        "pokemon element",
        "type",
        "water pokemon",
        "electric pokemon",
      ],
    },
    display: { showInFooter: true, icon: "🌊", showInMenu: true },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Water -------------------------------------------------------------
  {
    id: "category-water-element-type",
    name: "Water",
    slug: "water",
    description:
      "Water-type Pokémon cards — Squirtle, Blastoise, Lapras, Starmie and more",
    rootId: "category-pokemon-cards",
    parentIds: ["category-element-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/element-type/water",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 6,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 6,
      totalAuctionCount: 0,
      totalItemCount: 6,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 3,
    isBrand: false,
    seo: {
      title: "Water-type Pokémon Cards — Base Set",
      description:
        "Blastoise, Squirtle, Lapras, Starmie and all Base Set Water types.",
      keywords: ["water pokemon", "blastoise", "squirtle"],
    },
    display: {
      showInFooter: false,
      icon: "💧",
      coverImage: "https://images.pokemontcg.io/base1/2_hires.png",
      color: "#6DB6D4",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      {
        id: "category-element-type-pokemon-cards",
        name: "Element Type",
        tier: 1,
      },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Electric ----------------------------------------------------------
  {
    id: "category-electric-element-type",
    name: "Electric",
    slug: "electric",
    description:
      "Electric-type Pokémon cards — Pikachu, Raichu, Zapdos, Electabuzz and more",
    rootId: "category-pokemon-cards",
    parentIds: ["category-element-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/element-type/electric",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 5,
      productIds: [],
      auctionCount: 1,
      auctionIds: [],
      totalProductCount: 5,
      totalAuctionCount: 1,
      totalItemCount: 6,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 4,
    isBrand: false,
    seo: {
      title: "Electric-type Pokémon Cards — Base Set",
      description: "Pikachu, Raichu, Zapdos and all Base Set Electric types.",
      keywords: ["electric pokemon", "pikachu", "zapdos"],
    },
    display: {
      showInFooter: false,
      icon: "⚡",
      coverImage: "https://images.pokemontcg.io/base1/16_hires.png",
      color: "#F7D02C",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      {
        id: "category-element-type-pokemon-cards",
        name: "Element Type",
        tier: 1,
      },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Fire --------------------------------------------------------------
  {
    id: "category-fire-element-type",
    name: "Fire",
    slug: "fire",
    description:
      "Fire-type Pokémon cards — Charizard, Arcanine, Ninetales, Magmar and more",
    rootId: "category-pokemon-cards",
    parentIds: ["category-element-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/element-type/fire",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 7,
      productIds: [],
      auctionCount: 2,
      auctionIds: [],
      totalProductCount: 7,
      totalAuctionCount: 2,
      totalItemCount: 9,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 2,
    isBrand: false,
    seo: {
      title: "Fire-type Pokémon Cards — Base Set",
      description:
        "Charizard, Arcanine, Ninetales and all Base Set Fire types.",
      keywords: ["fire pokemon", "charizard", "arcanine"],
    },
    display: {
      showInFooter: false,
      icon: "🔥",
      coverImage: "https://images.pokemontcg.io/base1/4_hires.png",
      color: "#EE8130",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      {
        id: "category-element-type-pokemon-cards",
        name: "Element Type",
        tier: 1,
      },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Grass -------------------------------------------------------------
  {
    id: "category-grass-element-type",
    name: "Grass",
    slug: "grass",
    description:
      "Grass-type Pokémon cards — Bulbasaur, Venusaur, Scyther, Pinsir and more",
    rootId: "category-pokemon-cards",
    parentIds: ["category-element-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/element-type/grass",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 6,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 6,
      totalAuctionCount: 0,
      totalItemCount: 6,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Grass-type Pokémon Cards — Base Set",
      description: "Venusaur, Bulbasaur, Scyther and all Base Set Grass types.",
      keywords: ["grass pokemon", "venusaur", "bulbasaur"],
    },
    display: {
      showInFooter: false,
      icon: "🌿",
      coverImage: "https://images.pokemontcg.io/base1/15_hires.png",
      color: "#7AC74C",
      showInMenu: true,
    },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      {
        id: "category-element-type-pokemon-cards",
        name: "Element Type",
        tier: 1,
      },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Psychic -----------------------------------------------------------
  {
    id: "category-psychic-element-type",
    name: "Psychic",
    slug: "psychic",
    description:
      "Psychic-type Pokémon cards — Mewtwo, Jynx, Haunter, Gengar and more",
    rootId: "category-pokemon-cards",
    parentIds: ["category-element-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/element-type/psychic",
    order: 5,
    isLeaf: true,
    metrics: {
      productCount: 5,
      productIds: [],
      auctionCount: 1,
      auctionIds: [],
      totalProductCount: 5,
      totalAuctionCount: 1,
      totalItemCount: 6,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 5,
    isBrand: false,
    seo: {
      title: "Psychic-type Pokémon Cards — Base Set",
      description: "Mewtwo, Gengar, Jynx and all Base Set Psychic types.",
      keywords: ["psychic pokemon", "mewtwo", "gengar"],
    },
    display: {
      showInFooter: false,
      icon: "🔮",
      coverImage: "https://images.pokemontcg.io/base1/10_hires.png",
      color: "#F95587",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      {
        id: "category-element-type-pokemon-cards",
        name: "Element Type",
        tier: 1,
      },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Fighting ----------------------------------------------------------
  {
    id: "category-fighting-element-type",
    name: "Fighting",
    slug: "fighting",
    description:
      "Fighting-type Pokémon cards — Machamp, Hitmonchan, Hitmonlee and more",
    rootId: "category-pokemon-cards",
    parentIds: ["category-element-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/element-type/fighting",
    order: 6,
    isLeaf: true,
    metrics: {
      productCount: 4,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 4,
      totalAuctionCount: 0,
      totalItemCount: 4,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Fighting-type Pokémon Cards — Base Set",
      description: "Machamp, Hitmonchan and all Base Set Fighting types.",
      keywords: ["fighting pokemon", "machamp", "hitmonchan"],
    },
    display: {
      showInFooter: false,
      icon: "🥊",
      coverImage: "https://images.pokemontcg.io/base1/8_hires.png",
      color: "#C22E28",
      showInMenu: true,
    },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      {
        id: "category-element-type-pokemon-cards",
        name: "Element Type",
        tier: 1,
      },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Colorless ---------------------------------------------------------
  {
    id: "category-colorless-element-type",
    name: "Colorless",
    slug: "colorless",
    description:
      "Colorless-type Pokémon cards — Snorlax, Clefable, Chansey and more",
    rootId: "category-pokemon-cards",
    parentIds: ["category-element-type-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/element-type/colorless",
    order: 7,
    isLeaf: true,
    metrics: {
      productCount: 5,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 5,
      totalAuctionCount: 0,
      totalItemCount: 5,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Colorless Pokémon Cards — Base Set",
      description:
        "Snorlax, Clefable, Chansey and all Colorless Base Set cards.",
      keywords: ["colorless pokemon", "snorlax", "chansey"],
    },
    display: {
      showInFooter: false,
      icon: "🤍",
      coverImage: "https://images.pokemontcg.io/base1/3_hires.png",
      showInMenu: true,
    },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      {
        id: "category-element-type-pokemon-cards",
        name: "Element Type",
        tier: 1,
      },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- TIER 1: Rarity ----------------------------------------------------------
  {
    id: "category-rarity-pokemon-cards",
    name: "Rarity",
    slug: "rarity",
    description:
      "Browse by card rarity — Holo Rare, Non-Holo Rare, Uncommon, Common",
    rootId: "category-pokemon-cards",
    parentIds: ["category-pokemon-cards"],
    childrenIds: [
      "category-holo-rare-rarity",
      "category-non-holo-rare-rarity",
      "category-uncommon-rarity",
      "category-common-rarity",
    ],
    tier: 1,
    path: "pokemon-cards/rarity",
    order: 3,
    isLeaf: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 40,
      totalAuctionCount: 4,
      totalItemCount: 44,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Card Rarity — Base Set",
      description:
        "Holo Rare, Non-Holo Rare, Uncommon and Common Base Set cards.",
      keywords: ["pokemon rarity", "holo rare", "common pokemon"],
    },
    display: { showInFooter: true, icon: "⭐", showInMenu: true },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Holo Rare ---------------------------------------------------------
  {
    id: "category-holo-rare-rarity",
    name: "Holographic Rare",
    slug: "holo-rare",
    description:
      "Shiny holographic Rare cards — the most sought-after Base Set singles",
    rootId: "category-pokemon-cards",
    parentIds: ["category-rarity-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/rarity/holo-rare",
    order: 1,
    isLeaf: true,
    metrics: {
      productCount: 16,
      productIds: [],
      auctionCount: 4,
      auctionIds: [],
      totalProductCount: 16,
      totalAuctionCount: 4,
      totalItemCount: 20,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 1,
    isBrand: false,
    seo: {
      title: "Holo Rare Pokémon Cards — Base Set",
      description: "All 16 Holo Rare cards from the original Pokémon Base Set.",
      keywords: ["holo rare", "holographic pokemon", "charizard holo"],
    },
    display: {
      showInFooter: true,
      icon: "✨",
      coverImage: "https://images.pokemontcg.io/base1/4_hires.png",
      color: "#FFD700",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      { id: "category-rarity-pokemon-cards", name: "Rarity", tier: 1 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Non-Holo Rare -----------------------------------------------------
  {
    id: "category-non-holo-rare-rarity",
    name: "Non-Holo Rare",
    slug: "non-holo-rare",
    description: "Rare cards without the holographic pattern",
    rootId: "category-pokemon-cards",
    parentIds: ["category-rarity-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/rarity/non-holo-rare",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 10,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 10,
      totalAuctionCount: 0,
      totalItemCount: 10,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Non-Holo Rare Pokémon Cards — Base Set",
      description: "Rare but non-holographic Base Set singles.",
      keywords: ["non holo rare", "rare pokemon cards"],
    },
    display: { showInFooter: false, icon: "🌟", showInMenu: true },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      { id: "category-rarity-pokemon-cards", name: "Rarity", tier: 1 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Uncommon ----------------------------------------------------------
  {
    id: "category-uncommon-rarity",
    name: "Uncommon",
    slug: "uncommon",
    description: "Uncommon Base Set cards — great for deck building",
    rootId: "category-pokemon-cards",
    parentIds: ["category-rarity-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/rarity/uncommon",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 8,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 8,
      totalAuctionCount: 0,
      totalItemCount: 8,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Uncommon Pokémon Cards — Base Set",
      description: "Base Set uncommon singles for collectors and players.",
      keywords: ["uncommon pokemon", "base set uncommon"],
    },
    display: { showInFooter: false, icon: "🔵", showInMenu: true },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      { id: "category-rarity-pokemon-cards", name: "Rarity", tier: 1 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- LEAF: Common ------------------------------------------------------------
  {
    id: "category-common-rarity",
    name: "Common",
    slug: "common",
    description: "Common Base Set cards — affordable starters and bulk lots",
    rootId: "category-pokemon-cards",
    parentIds: ["category-rarity-pokemon-cards"],
    childrenIds: [],
    tier: 2,
    path: "pokemon-cards/rarity/common",
    order: 4,
    isLeaf: true,
    metrics: {
      productCount: 12,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 12,
      totalAuctionCount: 0,
      totalItemCount: 12,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Common Pokémon Cards — Base Set",
      description: "Base Set common singles, great for bulk collectors.",
      keywords: ["common pokemon", "base set common", "pokemon bulk"],
    },
    display: { showInFooter: false, icon: "⚪", showInMenu: true },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [
      { id: "category-pokemon-cards", name: "Pokémon Cards", tier: 0 },
      { id: "category-rarity-pokemon-cards", name: "Rarity", tier: 1 },
    ],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- ROOT: Sealed Products ---------------------------------------------------
  {
    id: "category-sealed-products",
    name: "Sealed Products",
    slug: "sealed-products",
    description:
      "Factory-sealed Pokémon TCG products — booster packs, theme decks, booster boxes",
    rootId: "category-sealed-products",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "sealed-products",
    order: 2,
    isLeaf: true,
    metrics: {
      productCount: 6,
      productIds: [],
      auctionCount: 1,
      auctionIds: [],
      totalProductCount: 6,
      totalAuctionCount: 1,
      totalItemCount: 7,
      lastUpdated: daysAgo(1),
    },
    isFeatured: true,
    featuredPriority: 6,
    isBrand: false,
    seo: {
      title: "Sealed Pokémon Products | LetItRip",
      description:
        "Booster packs, theme decks, display boxes — all sealed Base Set products.",
      keywords: ["sealed pokemon", "booster pack", "theme deck"],
    },
    display: {
      showInFooter: true,
      icon: "📦",
      coverImage: "https://images.pokemontcg.io/base1/logo.png",
      color: "#2563EB",
      showInMenu: true,
    },
    showOnHomepage: true,
    isActive: true,
    isSearchable: true,
    ancestors: [],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- ROOT: Accessories -------------------------------------------------------
  {
    id: "category-accessories",
    name: "Accessories",
    slug: "accessories",
    description:
      "Card sleeves, deck boxes, binders, playmats and other TCG accessories",
    rootId: "category-accessories",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "accessories",
    order: 3,
    isLeaf: true,
    metrics: {
      productCount: 4,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 4,
      totalAuctionCount: 0,
      totalItemCount: 4,
      lastUpdated: daysAgo(1),
    },
    isFeatured: false,
    isBrand: false,
    seo: {
      title: "Pokémon TCG Accessories | LetItRip",
      description:
        "Card sleeves, binders, playmats and deck boxes for Pokémon TCG collectors.",
      keywords: ["pokemon accessories", "card sleeves", "deck box", "binder"],
    },
    display: { showInFooter: true, icon: "🎒", showInMenu: true },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  // -- BRANDS ------------------------------------------------------------------
  {
    id: "category-brand-wizards",
    name: "Wizards of the Coast",
    slug: "brand-wizards",
    description: "Original Base Set publisher",
    rootId: "category-brand-wizards",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand-wizards",
    order: 10,
    isLeaf: true,
    isBrand: true,
    isFeatured: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(1),
    },
    seo: {
      title: "Wizards of the Coast Pokémon Cards",
      description: "Original Base Set cards published by Wizards of the Coast.",
      keywords: ["wizards of the coast", "wotc pokemon"],
    },
    display: { showInFooter: false, showInMenu: false },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  {
    id: "category-brand-tpci",
    name: "The Pokémon Company",
    slug: "brand-pokemon-company",
    description: "Official Pokémon Trading Card Game publisher",
    rootId: "category-brand-tpci",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand-pokemon-company",
    order: 11,
    isLeaf: true,
    isBrand: true,
    isFeatured: true,
    featuredPriority: 1,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(1),
    },
    seo: {
      title: "The Pokémon Company | LetItRip",
      description: "Official Pokémon TCG cards published by The Pokémon Company International.",
      keywords: ["pokemon company", "tpci", "official pokemon cards"],
    },
    display: {
      showInFooter: false,
      showInMenu: false,
      icon: "https://images.pokemontcg.io/base1/logo.png",
    },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },

  {
    id: "category-brand-nintendo",
    name: "Nintendo",
    slug: "brand-nintendo",
    description: "Nintendo-licensed Pokémon card products and accessories",
    rootId: "category-brand-nintendo",
    parentIds: [],
    childrenIds: [],
    tier: 0,
    path: "brand-nintendo",
    order: 12,
    isLeaf: true,
    isBrand: true,
    isFeatured: false,
    metrics: {
      productCount: 0,
      productIds: [],
      auctionCount: 0,
      auctionIds: [],
      totalProductCount: 0,
      totalAuctionCount: 0,
      totalItemCount: 0,
      lastUpdated: daysAgo(1),
    },
    seo: {
      title: "Nintendo Pokémon Products | LetItRip",
      description: "Nintendo-licensed Pokémon collectibles and accessories.",
      keywords: ["nintendo pokemon", "nintendo licensed"],
    },
    display: {
      showInFooter: false,
      showInMenu: false,
    },
    showOnHomepage: false,
    isActive: true,
    isSearchable: true,
    ancestors: [],
    createdBy: ADMIN,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
];
