/**
 * Product Features Seed Data
 *
 * 10 platform-scope feature flags available to every store. Store-scope custom
 * features are not seeded — sellers create their own via /store/[slug]/features.
 *
 * id === slug, prefix: feature-
 */

import type { ProductFeatureDocument } from "../features/products/schemas/product-features";

const NOW = new Date("2026-05-11T00:00:00.000Z");
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const productFeaturesSeedData: ProductFeatureDocument[] = [
  {
    id: "feature-free-shipping",
    slug: "feature-free-shipping",
    label: "Free Shipping",
    description: "Shipping is included in the listed price.",
    icon: "truck",
    iconColor: "--appkit-color-primary",
    category: "shipping",
    scope: "platform",
    productTypes: ["all"],
    isActive: true,
    displayOrder: 10,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-verified-seller",
    slug: "feature-verified-seller",
    label: "Verified Seller",
    description:
      "Sold by a LetItRip verified seller — identity and address confirmed.",
    icon: "badge-check",
    iconColor: "--appkit-color-primary",
    category: "seller",
    scope: "platform",
    productTypes: ["all"],
    isActive: true,
    displayOrder: 20,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-accept-returns",
    slug: "feature-accept-returns",
    label: "Returns Accepted",
    description: "Eligible for return within the platform return window.",
    icon: "refresh-ccw",
    iconColor: "--appkit-color-secondary",
    category: "platform",
    scope: "platform",
    productTypes: ["all"],
    isActive: true,
    displayOrder: 30,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-condition-new",
    slug: "feature-condition-new",
    label: "Brand New",
    description: "Factory-sealed or unopened, in original packaging.",
    icon: "sparkles",
    iconColor: "--appkit-color-primary",
    category: "condition",
    scope: "platform",
    productTypes: ["all"],
    isActive: true,
    displayOrder: 40,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-condition-used",
    slug: "feature-condition-used",
    label: "Pre-owned",
    description: "Used item — see listing description for condition details.",
    icon: "package",
    iconColor: "--appkit-color-secondary",
    category: "condition",
    scope: "platform",
    productTypes: ["all"],
    isActive: true,
    displayOrder: 50,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-featured",
    slug: "feature-featured",
    label: "Featured",
    description: "Hand-picked by the LetItRip editorial team.",
    icon: "star",
    iconColor: "--appkit-color-primary",
    category: "platform",
    scope: "platform",
    productTypes: ["all"],
    isActive: true,
    displayOrder: 60,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-promoted",
    slug: "feature-promoted",
    label: "Promoted",
    description: "Boosted placement — seller has promoted this listing.",
    icon: "megaphone",
    iconColor: "--appkit-color-secondary",
    category: "platform",
    scope: "platform",
    productTypes: ["all"],
    isActive: true,
    displayOrder: 70,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-auction-winner-badge",
    slug: "feature-auction-winner-badge",
    label: "Winner Badge",
    description:
      "Winners of this auction receive a special badge on their profile.",
    icon: "trophy",
    iconColor: "--appkit-color-primary",
    category: "auction",
    scope: "platform",
    productTypes: ["auction"],
    isActive: true,
    displayOrder: 80,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-shipping-paid-by-seller",
    slug: "feature-shipping-paid-by-seller",
    label: "Seller Pays Shipping",
    description:
      "Seller covers all shipping costs on this auction — winner pays only the bid.",
    icon: "package-check",
    iconColor: "--appkit-color-primary",
    category: "shipping",
    scope: "platform",
    productTypes: ["auction"],
    isActive: true,
    displayOrder: 90,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "feature-preorder-confirmed",
    slug: "feature-preorder-confirmed",
    label: "Pre-order Confirmed",
    description:
      "Production and delivery dates are confirmed by the manufacturer.",
    icon: "calendar-check",
    iconColor: "--appkit-color-primary",
    category: "preorder",
    scope: "platform",
    productTypes: ["preorder"],
    isActive: true,
    displayOrder: 100,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
];
