/*
 * WHY: Seeds a Beyblade classifieds catalog with real geographic and meta-field variety.
 *      The original 1-fixture file only ever exercised one city (Mumbai), one
 *      `contactMethod` ("both"), and always `acceptsShipping:false`/`negotiable:true` —
 *      no variety to exercise the classifieds filter UI or the contact-method-specific
 *      copy on the detail page (see CLAUDE.md seed-data blandness sweep, 2026-08-20).
 * WHAT: Exports 7 classified listings on Beyblade Arena — local meetups across 5 Indian
 *       cities, covering all 3 contactMethod values and both true/false states of
 *       acceptsShipping/negotiable.
 *
 * EXPORTS:
 *   productsClassifiedsSeedData — Array of 7 Partial<ProductDocument> with listingType:"classified"
 *
 * @tag domain:products,classifieds
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTokens } from "../utils/search-tokens";
import { seedExtMedia } from "./_helpers/media";

export const productsClassifiedsSeedData: Partial<ProductDocument>[] = [
  {
    id: "classified-beyblade-stadium-set",
    slug: "classified-beyblade-stadium-set",
    title: "Used Beyblade Stadium Set — Local Pickup Only",
    description: "Well-loved Beyblade stadium with 6 tops and 2 launchers, sold as-is. Meet up locally — price is negotiable.",
    categorySlugs: ["category-spinning-tops"],
    categoryNames: ["Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 1200,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-stadium-set-1-20260101/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-stadium-set-1-20260101/900/900"),
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-stadium-set-2-20260101/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    listingType: "classified" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    classified: {
      meetupArea: { city: "Mumbai", locality: "Andheri West", pincode: "400058" },
      contactMethod: "both" as const,
      acceptsShipping: false,
      negotiable: true,
    },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["classified", "local-pickup"],
    createdAt: new Date("2026-05-05"),
    updatedAt: new Date("2026-05-05"),
    searchTokens: buildSearchTokens(
      "Used Beyblade Stadium Set — Local Pickup Only",
      "Well-loved Beyblade stadium with 6 tops and 2 launchers.",
      "Beyblade",
      "brand-beyblade",
      ["Spinning Tops"],
      ["classified", "local-pickup"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "classified-beyblade-burst-collection-bengaluru",
    slug: "classified-beyblade-burst-collection-bengaluru",
    title: "Beyblade Burst Collection (12 Tops) — Bengaluru",
    description: "Downsizing my Burst collection — 12 tops in good condition, fixed price, will also ship nationwide if you'd rather not meet up.",
    categorySlugs: ["category-beyblade-burst", "category-spinning-tops"],
    categoryNames: ["Beyblade Burst", "Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 4500,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-burst-bengaluru-1-20260813/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-burst-bengaluru-1-20260813/900/900"),
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-burst-bengaluru-2-20260813/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.GOOD,
    listingType: "classified" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    classified: {
      meetupArea: { city: "Bengaluru", locality: "Koramangala", pincode: "560034" },
      contactMethod: "chat" as const,
      acceptsShipping: true,
      negotiable: false,
    },
    customFields: [{ key: "Item Count", type: "number", value: "12" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["classified", "bulk-lot"],
    createdAt: new Date("2026-08-13"),
    updatedAt: new Date("2026-08-13"),
    searchTokens: buildSearchTokens(
      "Beyblade Burst Collection (12 Tops) — Bengaluru",
      "Downsizing my Burst collection, fixed price, ships nationwide.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Burst", "Spinning Tops"],
      ["classified", "bulk-lot"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "classified-beyblade-x-starter-pune",
    slug: "classified-beyblade-x-starter-pune",
    title: "Beyblade X Starter Pack — Pune, Phone Contact Only",
    description: "Barely used Beyblade X starter pack, selling because I upgraded to a full set. Call or WhatsApp only, no chat.",
    categorySlugs: ["category-beyblade-x", "category-spinning-tops"],
    categoryNames: ["Beyblade X", "Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 650,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-x-pune-1-20260814/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-x-pune-1-20260814/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.LIKE_NEW,
    listingType: "classified" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    classified: {
      meetupArea: { city: "Pune", locality: "Kothrud", pincode: "411038" },
      contactMethod: "phone" as const,
      acceptsShipping: false,
      negotiable: true,
    },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["classified", "local-pickup", "starter-set"],
    createdAt: new Date("2026-08-14"),
    updatedAt: new Date("2026-08-14"),
    searchTokens: buildSearchTokens(
      "Beyblade X Starter Pack — Pune, Phone Contact Only",
      "Barely used Beyblade X starter pack, phone/WhatsApp only.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["classified", "local-pickup", "starter-set"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "classified-beyblade-metal-vintage-delhi",
    slug: "classified-beyblade-metal-vintage-delhi",
    title: "Vintage Metal Fight Lot (5 Tops) — Delhi NCR",
    description: "A well-preserved 5-top Metal Fight lot from a long-time collector. Firm price, ships anywhere in India.",
    categorySlugs: ["category-beyblade-metal", "category-spinning-tops"],
    categoryNames: ["Beyblade Metal Fight", "Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 3200,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-metal-delhi-1-20260815/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-metal-delhi-1-20260815/900/900"),
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-metal-delhi-2-20260815/900/900"),
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-metal-delhi-3-20260815/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.GOOD,
    listingType: "classified" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    classified: {
      meetupArea: { city: "New Delhi", locality: "Rajouri Garden", pincode: "110027" },
      contactMethod: "both" as const,
      acceptsShipping: true,
      negotiable: false,
    },
    customFields: [{ key: "Item Count", type: "number", value: "5" }],
    customSections: [
      {
        id: "collector-notes",
        title: "Collector's Notes",
        text: "All 5 tops have been kept in a display case since purchase — minor shelf wear only, no chips or cracks on any layer/energy ring.",
      },
    ],
    featured: true,
    isPromoted: false,
    isOnSale: false,
    tags: ["classified", "bulk-lot", "vintage-collectible"],
    createdAt: new Date("2026-08-15"),
    updatedAt: new Date("2026-08-16"),
    searchTokens: buildSearchTokens(
      "Vintage Metal Fight Lot (5 Tops) — Delhi NCR",
      "Well-preserved 5-top Metal Fight lot, firm price, ships anywhere.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade Metal Fight", "Spinning Tops"],
      ["classified", "bulk-lot", "vintage-collectible"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "classified-beyblade-original-grail-chennai",
    slug: "classified-beyblade-original-grail-chennai",
    title: "Original Series Grail Piece — Chennai, Meet Up Only",
    description: "A genuine original-series grail piece, only selling to a local buyer I can meet in person to verify authenticity together.",
    categorySlugs: ["category-beyblade-original", "category-spinning-tops"],
    categoryNames: ["Beyblade Original", "Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 8000,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-original-chennai-1-20260816/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-original-chennai-1-20260816/900/900"),
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-original-chennai-2-20260816/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.LIKE_NEW,
    listingType: "classified" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    classified: {
      meetupArea: { city: "Chennai", locality: "T. Nagar", pincode: "600017" },
      contactMethod: "chat" as const,
      acceptsShipping: false,
      negotiable: false,
    },
    customFields: [{ key: "Authenticity Verified", type: "boolean", value: "true" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["classified", "vintage-collectible", "local-pickup"],
    createdAt: new Date("2026-08-16"),
    updatedAt: new Date("2026-08-16"),
    searchTokens: buildSearchTokens(
      "Original Series Grail Piece — Chennai, Meet Up Only",
      "Genuine original-series grail piece, local meetup verification only.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Original", "Spinning Tops"],
      ["classified", "vintage-collectible", "local-pickup"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "classified-beyblade-x-tournament-kit-hyderabad",
    slug: "classified-beyblade-x-tournament-kit-hyderabad",
    title: "Tournament-Ready Beyblade X Kit — Hyderabad",
    description: "Complete tournament-legal kit including 3 tops, stadium, and a scorecard pad from our last local meetup event.",
    categorySlugs: ["category-beyblade-x", "category-spinning-tops"],
    categoryNames: ["Beyblade X", "Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 2400,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-x-hyderabad-1-20260817/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-x-hyderabad-1-20260817/900/900"),
      seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-x-hyderabad-2-20260817/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.GOOD,
    listingType: "classified" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    classified: {
      meetupArea: { city: "Hyderabad", locality: "Banjara Hills", pincode: "500034" },
      contactMethod: "phone" as const,
      acceptsShipping: true,
      negotiable: true,
    },
    customFields: [{ key: "Tournament Legal", type: "boolean", value: "true" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["classified", "tournament-grade"],
    createdAt: new Date("2026-08-17"),
    updatedAt: new Date("2026-08-17"),
    searchTokens: buildSearchTokens(
      "Tournament-Ready Beyblade X Kit — Hyderabad",
      "Complete tournament-legal kit including stadium and scorecard pad.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["classified", "tournament-grade"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "classified-beyblade-burst-parts-mumbai",
    slug: "classified-beyblade-burst-parts-mumbai",
    title: "Spare Burst Parts Bundle — Mumbai, Ships Too",
    description: "Assorted spare Burst layers, discs, and drivers cleared out from my parts box. Happy to meet locally or ship.",
    categorySlugs: ["category-beyblade-burst", "category-spinning-tops"],
    categoryNames: ["Beyblade Burst", "Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 450,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-burst-mumbai-1-20260818/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/classified-image-beyblade-burst-mumbai-1-20260818/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    listingType: "classified" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    classified: {
      meetupArea: { city: "Mumbai", locality: "Powai", pincode: "400076" },
      contactMethod: "both" as const,
      acceptsShipping: true,
      negotiable: true,
    },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["classified", "spare-parts"],
    createdAt: new Date("2026-08-18"),
    updatedAt: new Date("2026-08-18"),
    searchTokens: buildSearchTokens(
      "Spare Burst Parts Bundle — Mumbai, Ships Too",
      "Assorted spare Burst layers, discs, and drivers.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Burst", "Spinning Tops"],
      ["classified", "spare-parts"],
    ),
  } as unknown as Partial<ProductDocument>,
];
