/*
 * WHY: Seeds a Beyblade digital-code catalog with real pool/redemption variety. The
 *      original 1-fixture file only ever exercised `codeDeliveryMethod:"auto-claim"` with
 *      `codesAvailable === codePoolSize` (i.e. no fixture ever showed a partially-redeemed
 *      or sold-out pool, and `manual-email` delivery was never exercised at all) — see
 *      CLAUDE.md seed-data blandness sweep, 2026-08-20 session.
 * WHAT: Exports 8 digital-code listings on Beyblade Arena — mixed auto-claim/manual-email
 *       delivery, partially-redeemed and fully-sold-out pools, and expiring codes.
 *
 * EXPORTS:
 *   productsDigitalCodesSeedData — Array of 8 Partial<ProductDocument> with listingType:"digital-code"
 *
 * @tag domain:products,digital-codes
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { withProductSearchTxt } from "./_helpers/product-search-txt";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTxt } from "../utils/search-txt";
import { seedExtMedia } from "./_helpers/media";

const _rawproductsDigitalCodesSeedData: Partial<ProductDocument>[] = [
  {
    id: "digitalcode-beyblade-x-app-starter-pack",
    slug: "digitalcode-beyblade-x-app-starter-pack",
    title: "Beyblade X App — Starter Pack Code",
    description: "Digital redemption code for the Beyblade X companion app's Starter Pack — instantly unlocks 5 exclusive digital tops.",
    categorySlugs: ["category-x-boosters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Boosters","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 199,
    currency: "INR",
    stockQuantity: 25,
    availableQuantity: 25,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-starter-1-20260101/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-starter-1-20260101/900/900"),
      seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-starter-2-20260101/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 25,
      codesAvailable: 25,
      redemptionInstructions: "Open the Beyblade X app, go to Settings → Redeem Code, and paste your code to unlock the Starter Pack instantly.",
    },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["digital-code", "app-content"],
    createdAt: new Date("2026-05-06"),
    updatedAt: new Date("2026-05-06"),
    searchTxt: buildSearchTxt([
      "Beyblade X App — Starter Pack Code",
      "Digital redemption code for the Beyblade X companion app.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["digital-code", "app-content"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "digitalcode-beyblade-x-app-legendary-pack",
    slug: "digitalcode-beyblade-x-app-legendary-pack",
    title: "Beyblade X App — Legendary Pack Code (Partially Claimed)",
    description: "Unlocks 3 legendary digital tops in the companion app. Popular pack — most of the batch has already been claimed.",
    categorySlugs: ["category-x-starters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Starter Sets","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 349,
    currency: "INR",
    stockQuantity: 40,
    availableQuantity: 6,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-legendary-1-20260814/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-legendary-1-20260814/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 40,
      codesAvailable: 6,
      redemptionInstructions: "Open the Beyblade X app, go to Settings → Redeem Code, and paste your code to unlock the Legendary Pack instantly.",
      expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    },
    customFields: [],
    customSections: [],
    featured: true,
    isPromoted: true,
    isOnSale: false,
    tags: ["digital-code", "app-content"],
    createdAt: new Date("2026-08-14"),
    updatedAt: new Date("2026-08-19"),
    searchTxt: buildSearchTxt([
      "Beyblade X App — Legendary Pack Code (Partially Claimed)",
      "Unlocks 3 legendary digital tops, most of the batch already claimed.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["digital-code", "app-content"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "digitalcode-beyblade-burst-app-sold-out",
    slug: "digitalcode-beyblade-burst-app-sold-out",
    title: "Beyblade Burst App — Anniversary Pack Code (Sold Out)",
    description: "Limited-run anniversary code pack for the Beyblade Burst app — every code in this batch has been claimed.",
    categorySlugs: ["category-burst-classic","category-burst-tops","category-beyblade-burst","category-spinning-tops"],
    categoryNames: ["Burst Classic","Burst Tops","Beyblade Burst","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 299,
    currency: "INR",
    // `stockQuantity: 15` / `isSold: false` until 2026-08-24, contradicting
    // both `availableQuantity: 0` and the drained `codesAvailable` below.
    // digital-code's own config comment claimed stockQuantity mirrors the pool
    // count; this fixture is the proof it does not, which is why the per-type
    // predicate reads the nested pool counter rather than trusting the mirror.
    stockQuantity: 0,
    availableQuantity: 0,
    isSold: true,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-burst-sold-out-1-20260810/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-burst-sold-out-1-20260810/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 15,
      codesAvailable: 0,
      redemptionInstructions: "Open the Beyblade Burst app, go to Settings → Redeem Code, and paste your code to unlock the Anniversary Pack.",
    },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["digital-code", "app-content", "limited-run"],
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date("2026-08-10"),
    searchTxt: buildSearchTxt([
      "Beyblade Burst App — Anniversary Pack Code (Sold Out)",
      "Limited-run anniversary code pack, every code claimed.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Burst", "Spinning Tops"],
      ["digital-code", "app-content", "limited-run"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "digitalcode-beyblade-x-manual-tournament-pass",
    slug: "digitalcode-beyblade-x-manual-tournament-pass",
    title: "Beyblade X Regional Tournament — Digital Entry Pass",
    description: "Digital entry pass for the next regional tournament, emailed manually by the organizer within 24 hours of purchase.",
    categorySlugs: ["category-x-boosters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Boosters","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 499,
    currency: "INR",
    stockQuantity: 50,
    availableQuantity: 32,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-tournament-1-20260815/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-tournament-1-20260815/900/900"),
      seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-tournament-2-20260815/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "manual-email" as const,
      codePoolSize: 50,
      codesAvailable: 32,
      redemptionInstructions: "Your tournament entry pass will be emailed within 24 hours of purchase. Check your spam folder if it doesn't arrive.",
      expiresAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    },
    customFields: [{ key: "Manual Fulfillment", type: "boolean", value: "true" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["digital-code", "tournament-grade"],
    createdAt: new Date("2026-08-15"),
    updatedAt: new Date("2026-08-15"),
    searchTxt: buildSearchTxt([
      "Beyblade X Regional Tournament — Digital Entry Pass",
      "Digital entry pass, emailed manually by the organizer.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["digital-code", "tournament-grade"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "digitalcode-beyblade-metal-app-classic-pack",
    slug: "digitalcode-beyblade-metal-app-classic-pack",
    title: "Beyblade Metal Fight App — Classic Pack Code",
    description: "Unlocks the Metal Fight classic-era top roster in the companion app — Storm Pegasus, Lightning L-Drago, and more.",
    categorySlugs: ["category-metal-fury","category-metal-tops","category-beyblade-metal","category-spinning-tops"],
    categoryNames: ["Metal Fury","Metal Fight Tops","Beyblade Metal Fight","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 249,
    currency: "INR",
    stockQuantity: 30,
    availableQuantity: 30,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-metal-classic-1-20260816/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-metal-classic-1-20260816/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 30,
      codesAvailable: 30,
      redemptionInstructions: "Open the Beyblade Metal Fight app, go to Settings → Redeem Code, and paste your code to unlock the Classic Pack instantly.",
    },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["digital-code", "app-content"],
    createdAt: new Date("2026-08-16"),
    updatedAt: new Date("2026-08-16"),
    searchTxt: buildSearchTxt([
      "Beyblade Metal Fight App — Classic Pack Code",
      "Unlocks the Metal Fight classic-era top roster.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade Metal Fight", "Spinning Tops"],
      ["digital-code", "app-content"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "digitalcode-beyblade-burst-app-avatar-skins",
    slug: "digitalcode-beyblade-burst-app-avatar-skins",
    title: "Beyblade Burst App — Avatar Skin Bundle Code",
    description: "Cosmetic-only code bundle — unlocks 8 exclusive player avatar skins in the Beyblade Burst app, no gameplay advantage.",
    categorySlugs: ["category-burst-cho-z","category-burst-tops","category-beyblade-burst","category-spinning-tops"],
    categoryNames: ["Cho-Z","Burst Tops","Beyblade Burst","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 149,
    currency: "INR",
    stockQuantity: 60,
    availableQuantity: 41,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-burst-avatar-1-20260817/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-burst-avatar-1-20260817/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 60,
      codesAvailable: 41,
      redemptionInstructions: "Open the Beyblade Burst app, go to Settings → Redeem Code, and paste your code to unlock all 8 avatar skins instantly.",
    },
    customFields: [{ key: "Cosmetic Only", type: "boolean", value: "true" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: true,
    tags: ["digital-code", "app-content", "cosmetic"],
    createdAt: new Date("2026-08-17"),
    updatedAt: new Date("2026-08-19"),
    searchTxt: buildSearchTxt([
      "Beyblade Burst App — Avatar Skin Bundle Code",
      "Cosmetic-only code bundle, 8 exclusive player avatar skins.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Burst", "Spinning Tops"],
      ["digital-code", "app-content", "cosmetic"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "digitalcode-beyblade-x-manual-coaching-session",
    slug: "digitalcode-beyblade-x-manual-coaching-session",
    title: "1-on-1 Beyblade X Coaching Session — Digital Booking Code",
    description: "Redeem this code for a 30-minute 1-on-1 video coaching session with a tournament-ranked Beyblade X player. Booking link emailed manually.",
    categorySlugs: ["category-x-starters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Starter Sets","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 799,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 3,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-coaching-1-20260818/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-coaching-1-20260818/900/900"),
      seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-coaching-2-20260818/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "manual-email" as const,
      codePoolSize: 10,
      codesAvailable: 3,
      redemptionInstructions: "Your booking link and coach's availability calendar will be emailed within 24 hours of purchase.",
      expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    },
    customFields: [
      { key: "Session Length", type: "text", value: "30 minutes" },
      { key: "Manual Fulfillment", type: "boolean", value: "true" },
    ],
    customSections: [],
    featured: true,
    isPromoted: false,
    isOnSale: false,
    tags: ["digital-code", "coaching"],
    createdAt: new Date("2026-08-18"),
    updatedAt: new Date("2026-08-18"),
    searchTxt: buildSearchTxt([
      "1-on-1 Beyblade X Coaching Session — Digital Booking Code",
      "30-minute 1-on-1 video coaching session, booking link emailed manually.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["digital-code", "coaching"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    // Pool drained, but `stockQuantity: 5` and `isSold: false`.
    //
    // The NESTED-field fixture: the only row that fails purely on
    // `digitalCode.codesAvailable`. The old related-items predicate read
    // `row.codesAvailable` at the TOP level, which is undefined on every
    // document, so its digital-code branch had never once fired. Without a
    // fixture in this exact shape that bug is untestable.
    id: "digitalcode-beyblade-x-app-launch-codes-depleted",
    slug: "digitalcode-beyblade-x-app-launch-codes-depleted",
    title: "Beyblade X App — Launch Bonus Code (Pool Empty)",
    description: "Launch-bonus codes for the Beyblade X app. Every code in the pool has been claimed; restock pending.",
    categorySlugs: ["category-x-boosters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Boosters","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 399,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 5,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-depleted-1-20260824/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/digitalcode-image-beyblade-x-depleted-1-20260824/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "digital-code" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    digitalCode: {
      codeDeliveryMethod: "auto-claim" as const,
      codePoolSize: 30,
      codesAvailable: 0,
      redemptionInstructions: "Open the Beyblade X app, tap Settings → Redeem, and paste your code.",
    },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["digital-code"],
    createdAt: new Date("2026-08-24"),
    updatedAt: new Date("2026-08-24"),
  },
];

/**
 * Every record gains `searchTxt` here rather than inline, so a fixture added at
 * the bottom of the array cannot ship without it — which is exactly how the
 * sold/depleted fixture in this file ended up unsearchable.
 */
export const productsDigitalCodesSeedData: Partial<ProductDocument>[] =
  _rawproductsDigitalCodesSeedData.map(withProductSearchTxt);
