/*
 * WHY: Real (non-tester-sandbox) prize-draw listings so testers and shoppers can exercise
 *      both automatic-reveal modes ("instant" and "scheduled") against permanent catalog
 *      content, not just the disposable 7-day tester sandbox item. Previously an empty
 *      stub — "out of scope for the minimal Beyblade-focused demo catalog" — now populated
 *      with two platform-run mystery-box draws, on-theme for the spinning-tops catalog.
 * WHAT: Exports 7 prize-draw listings (classic reveal mode) run by the platform's own
 *       store, letitrip-official — one "instant" mode (4 prizes), one "scheduled" mode
 *       (2 prizes, small pool for easy manual sellout testing).
 *
 * EXPORTS:
 *   productsPrizeDrawsSeedData — Array of 7 Partial<ProductDocument> with listingType:"prize-draw"
 *
 * @tag domain:products,prize-draws
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTokens } from "../utils/search-tokens";
import { seedExtMedia } from "./_helpers/media";

export const productsPrizeDrawsSeedData: Partial<ProductDocument>[] = [
  {
    id: "prizedraw-beyblade-mystery-box",
    slug: "prizedraw-beyblade-mystery-box",
    title: "Beyblade Mystery Box — Prize Draw",
    description: "Buy an entry for ₹99 and reveal your prize instantly — win anything from a rare limited-edition Beyblade down to a spare launcher grip. 4 prizes available, revealed on a first-come basis.",
    categorySlugs: ["category-storage-cases","category-gear-storage","category-battle-gear","category-spinning-tops"],
    categoryNames: ["Cases & Trays","Storage & Care","Battle Gear","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 99,
    currency: "INR",
    stockQuantity: 4,
    availableQuantity: 4,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-mystery-box-1-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-mystery-box-1-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "prize-draw" as const,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "instant" as const,
    pricePerEntry: 99,
    prizeMaxEntries: 4,
    prizeCurrentEntries: 0,
    prizeDrawDurationDays: 7,
    prizeRevealWindowStart: new Date("2026-05-01"),
    prizeRevealWindowEnd: new Date("2026-05-08"),
    prizeRevealStatus: "open" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Limited-Edition Gold Dranzer S", description: "Rare gold-finish collector's edition.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-beyblade-1-20260101/600/600")], condition: "new", estimatedValue: 3499, isWon: false },
      { itemNumber: 2, title: "Beyblade X Starter Set", description: "Full starter set with stadium.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-beyblade-2-20260101/600/600")], condition: "new", estimatedValue: 1999, isWon: false },
      { itemNumber: 3, title: "Spare Parts Bundle", description: "Assorted spare tips, rings, and drivers.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-beyblade-3-20260101/600/600")], condition: "new", estimatedValue: 399, isWon: false },
      { itemNumber: 4, title: "Spare Launcher Grip", description: "Standard replacement launcher grip.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-beyblade-4-20260101/600/600")], condition: "new", estimatedValue: 149, isWon: false },
    ],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: true,
    isOnSale: false,
    tags: ["prize-draw", "mystery-box"],
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-01"),
    searchTokens: buildSearchTokens(
      "Beyblade Mystery Box — Prize Draw",
      "Buy an entry and reveal your prize instantly.",
      "Beyblade",
      "brand-beyblade",
      ["Spinning Tops"],
      ["prize-draw", "mystery-box"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "prizedraw-beyblade-scheduled-demo",
    slug: "prizedraw-beyblade-scheduled-demo",
    title: "Beyblade Champion's Draw — Prize Draw",
    description: "Two entries, two prizes — the winners are revealed automatically the moment the draw closes (3 days) or sells out, whichever comes first.",
    categorySlugs: ["category-stadiums-standard","category-gear-stadiums","category-battle-gear","category-spinning-tops"],
    categoryNames: ["Standard Stadiums","Stadiums","Battle Gear","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 149,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-scheduled-1-20260101/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-scheduled-1-20260101/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "prize-draw" as const,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "scheduled" as const,
    pricePerEntry: 149,
    prizeMaxEntries: 2,
    prizeCurrentEntries: 0,
    prizeDrawDurationDays: 3,
    prizeRevealWindowStart: new Date("2026-05-01"),
    prizeRevealWindowEnd: new Date("2026-05-04"),
    prizeRevealStatus: "open" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Beyblade X Champion Set", description: "Tournament-grade champion set.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-beyblade-scheduled-1-20260101/600/600")], condition: "new", estimatedValue: 2499, isWon: false },
      { itemNumber: 2, title: "Spare Tip Multipack", description: "Assorted performance tips.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-beyblade-scheduled-2-20260101/600/600")], condition: "new", estimatedValue: 299, isWon: false },
    ],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["prize-draw", "mystery-box"],
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-01"),
    searchTokens: buildSearchTokens(
      "Beyblade Champion's Draw — Prize Draw",
      "Two entries, two prizes, revealed automatically at close or sellout.",
      "Beyblade",
      "brand-beyblade",
      ["Spinning Tops"],
      ["prize-draw", "mystery-box"],
    ),
  } as unknown as Partial<ProductDocument>,

  // --- Partially sold: prizeCurrentEntries > 0, main seed never exercised this before ---
  {
    id: "prizedraw-beyblade-x-legendary-vault",
    slug: "prizedraw-beyblade-x-legendary-vault",
    title: "Beyblade X Legendary Vault — Prize Draw",
    description: "6 entries, 6 prizes ranging from a legendary chase top to spare parts — over half the draw is already sold, don't miss the remaining slots.",
    categorySlugs: ["category-x-starters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Starter Sets","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 199,
    currency: "INR",
    stockQuantity: 6,
    availableQuantity: 2,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-x-legendary-vault-1-20260815/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-x-legendary-vault-1-20260815/900/900"),
      seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-x-legendary-vault-2-20260815/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "prize-draw" as const,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "instant" as const,
    pricePerEntry: 199,
    prizeMaxEntries: 6,
    prizeCurrentEntries: 4,
    prizeDrawDurationDays: 10,
    prizeRevealWindowStart: new Date("2026-08-15"),
    prizeRevealWindowEnd: new Date("2026-08-25"),
    prizeRevealStatus: "open" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Legendary Wizard Fafnir (Chase Top)", description: "The grand-prize chase top for this draw.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-legendary-vault-1-20260815/600/600"), seedExtMedia("https://picsum.photos/seed/prizedraw-item-legendary-vault-1b-20260815/600/600")], condition: "new", estimatedValue: 4999, isWon: false },
      { itemNumber: 2, title: "Beyblade X Starter Set", description: "Full starter set with launcher.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-legendary-vault-2-20260815/600/600")], condition: "new", estimatedValue: 1299, isWon: false },
      { itemNumber: 3, title: "Xtreme Gear Stadium", description: "Official X-format battle stadium.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-legendary-vault-3-20260815/600/600")], condition: "new", estimatedValue: 999, isWon: false },
      { itemNumber: 4, title: "Ratchet & Bit Multipack", description: "Assorted performance ratchets and bits.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-legendary-vault-4-20260815/600/600")], condition: "new", estimatedValue: 599, isWon: false },
      { itemNumber: 5, title: "Carry Case", description: "6-slot hard-shell carry case.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-legendary-vault-5-20260815/600/600")], condition: "new", estimatedValue: 349, isWon: false },
      { itemNumber: 6, title: "Spare Launcher Grip", description: "Standard replacement launcher grip.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-legendary-vault-6-20260815/600/600")], condition: "new", estimatedValue: 149, isWon: false },
    ],
    customFields: [],
    customSections: [],
    featured: true,
    isPromoted: true,
    isOnSale: false,
    tags: ["prize-draw", "mystery-box", "chase-top"],
    createdAt: new Date("2026-08-15"),
    updatedAt: new Date("2026-08-19"),
    searchTokens: buildSearchTokens(
      "Beyblade X Legendary Vault — Prize Draw",
      "6 entries, 6 prizes, over half already sold.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["prize-draw", "mystery-box", "chase-top"],
    ),
  } as unknown as Partial<ProductDocument>,

  // --- Closed + revealed: real winners, isWon:true — permanent-catalog example (previously only in tester sandbox) ---
  {
    id: "prizedraw-beyblade-metal-closed-revealed",
    slug: "prizedraw-beyblade-metal-closed-revealed",
    title: "Metal Fight Mystery Draw — Ended (Revealed)",
    description: "This draw has closed and every prize has been revealed to its winner. Browse the results below.",
    categorySlugs: ["category-metal-fusion","category-metal-tops","category-beyblade-metal","category-spinning-tops"],
    categoryNames: ["Metal Fusion","Metal Fight Tops","Beyblade Metal Fight","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 129,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 0,
    isSold: true,
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-metal-closed-1-20260805/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-metal-closed-1-20260805/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "prize-draw" as const,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "instant" as const,
    pricePerEntry: 129,
    prizeMaxEntries: 3,
    prizeCurrentEntries: 3,
    prizeDrawDurationDays: 7,
    prizeRevealWindowStart: new Date("2026-08-05"),
    prizeRevealWindowEnd: new Date("2026-08-12"),
    prizeRevealStatus: "closed" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Lightning L-Drago 100HF/S", description: "Metal Fury era attack top.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-metal-closed-1-20260805/600/600")], condition: "new", estimatedValue: 2299, isWon: true, wonByOrderId: "order-1-20260812-a1b2c3" },
      { itemNumber: 2, title: "Storm Pegasus 105RF", description: "Metal Fusion era attack top.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-metal-closed-2-20260805/600/600")], condition: "new", estimatedValue: 1299, isWon: true, wonByOrderId: "order-1-20260812-d4e5f6" },
      { itemNumber: 3, title: "Spare Parts Bundle", description: "Assorted spare tips and rings.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-metal-closed-3-20260805/600/600")], condition: "new", estimatedValue: 399, isWon: true, wonByOrderId: "order-1-20260812-g7h8i9" },
    ],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["prize-draw", "mystery-box"],
    createdAt: new Date("2026-08-05"),
    updatedAt: new Date("2026-08-12"),
    searchTokens: buildSearchTokens(
      "Metal Fight Mystery Draw — Ended (Revealed)",
      "This draw has closed and every prize has been revealed.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade Metal Fight", "Spinning Tops"],
      ["prize-draw", "mystery-box"],
    ),
  } as unknown as Partial<ProductDocument>,

  // --- Nearly sold out, scheduled reveal ---
  {
    id: "prizedraw-beyblade-burst-collectors-draw",
    slug: "prizedraw-beyblade-burst-collectors-draw",
    title: "Beyblade Burst Collector's Draw — Almost Sold Out",
    description: "Only 1 entry left — 4 of 5 slots are already claimed for this Burst-generation collector's draw. Winners revealed the moment the draw closes.",
    categorySlugs: ["category-burst-cho-z","category-burst-tops","category-beyblade-burst","category-spinning-tops"],
    categoryNames: ["Cho-Z","Burst Tops","Beyblade Burst","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 179,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 1,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-burst-collectors-1-20260817/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-burst-collectors-1-20260817/900/900"),
      seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-burst-collectors-2-20260817/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "prize-draw" as const,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "scheduled" as const,
    pricePerEntry: 179,
    prizeMaxEntries: 5,
    prizeCurrentEntries: 4,
    prizeDrawDurationDays: 4,
    prizeRevealWindowStart: new Date("2026-08-17"),
    prizeRevealWindowEnd: new Date("2026-08-21"),
    prizeRevealStatus: "open" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Cho-Z Achilles.Ow.Zn'", description: "Super Zeta stamina-type top.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-burst-collectors-1-20260817/600/600")], condition: "new", estimatedValue: 1799, isWon: false },
      { itemNumber: 2, title: "Regalia Genesis.Zt", description: "Attack-type top with switch launcher compatibility.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-burst-collectors-2-20260817/600/600")], condition: "new", estimatedValue: 1399, isWon: false },
      { itemNumber: 3, title: "Union Achilles Cover Change", description: "Stamina-type with cover-change layer.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-burst-collectors-3-20260817/600/600")], condition: "new", estimatedValue: 1099, isWon: false },
      { itemNumber: 4, title: "Beystadium Attack Type", description: "Compact battle stadium.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-burst-collectors-4-20260817/600/600")], condition: "new", estimatedValue: 699, isWon: false },
      { itemNumber: 5, title: "Spare Driver Multipack", description: "Assorted performance drivers.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-burst-collectors-5-20260817/600/600")], condition: "new", estimatedValue: 349, isWon: false },
    ],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["prize-draw", "mystery-box"],
    createdAt: new Date("2026-08-17"),
    updatedAt: new Date("2026-08-19"),
    searchTokens: buildSearchTokens(
      "Beyblade Burst Collector's Draw — Almost Sold Out",
      "Only 1 entry left, 4 of 5 slots already claimed.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Burst", "Spinning Tops"],
      ["prize-draw", "mystery-box"],
    ),
  } as unknown as Partial<ProductDocument>,

  // --- High-value vintage vault, multi-image collage per prize ---
  {
    id: "prizedraw-beyblade-original-vintage-vault",
    slug: "prizedraw-beyblade-original-vintage-vault",
    title: "Beyblade Original Vintage Vault — Prize Draw",
    description: "A high-value original-series vault — 3 entries, each prize photographed from multiple angles so you know exactly what you might win.",
    categorySlugs: ["category-original-plastic-gen","category-original-tops","category-beyblade-original","category-spinning-tops"],
    categoryNames: ["Plastic Generation","Original Tops","Beyblade Original","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 299,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-original-vault-1-20260818/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-original-vault-1-20260818/900/900"),
      seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-original-vault-2-20260818/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "prize-draw" as const,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "instant" as const,
    pricePerEntry: 299,
    prizeMaxEntries: 3,
    prizeCurrentEntries: 0,
    prizeDrawDurationDays: 14,
    prizeRevealWindowStart: new Date("2026-08-18"),
    prizeRevealWindowEnd: new Date("2026-09-01"),
    prizeRevealStatus: "open" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Sealed Dragoon Storm (Grail Piece)", description: "Sealed, unopened — the rarest prize in this vault.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-original-vault-1a-20260818/600/600"), seedExtMedia("https://picsum.photos/seed/prizedraw-item-original-vault-1b-20260818/600/600"), seedExtMedia("https://picsum.photos/seed/prizedraw-item-original-vault-1c-20260818/600/600")], condition: "new", estimatedValue: 5999, isWon: false },
      { itemNumber: 2, title: "Seaborg 2000 (Defense)", description: "Rare original-series defense-type top.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-original-vault-2a-20260818/600/600"), seedExtMedia("https://picsum.photos/seed/prizedraw-item-original-vault-2b-20260818/600/600")], condition: "good", estimatedValue: 3499, isWon: false },
      { itemNumber: 3, title: "Original-Series Launcher Set", description: "Complete launcher + ripcord set.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-original-vault-3-20260818/600/600")], condition: "new", estimatedValue: 599, isWon: false },
    ],
    customFields: [{ key: "Authenticity Verified", type: "boolean", value: "true" }],
    customSections: [],
    featured: true,
    isPromoted: false,
    isOnSale: false,
    tags: ["prize-draw", "mystery-box", "vintage-collectible"],
    createdAt: new Date("2026-08-18"),
    updatedAt: new Date("2026-08-18"),
    searchTokens: buildSearchTokens(
      "Beyblade Original Vintage Vault — Prize Draw",
      "High-value original-series vault, multi-angle photos per prize.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Original", "Spinning Tops"],
      ["prize-draw", "mystery-box", "vintage-collectible"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    // Closed, but with slots still unsold and `isSold: false`.
    //
    // This is the fixture that proves the prize-draw branch reads
    // `prizeRevealStatus`. The other closed draw has availableQuantity 0 AND
    // isSold true, so it is caught by the shared base check and would still
    // look correct even if the type-specific rule were deleted.
    id: "prizedraw-beyblade-x-vault-closed-pending-reveal",
    slug: "prizedraw-beyblade-x-vault-closed-pending-reveal",
    title: "Beyblade X Vault Draw — Closed Early",
    description: "The seller closed this draw before every slot sold. Remaining entries were refunded; no further entries are accepted.",
    categorySlugs: ["category-x-boosters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Boosters","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 249,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 3,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-x-vault-closed-1-20260824/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/prizedraw-image-beyblade-x-vault-closed-1-20260824/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "prize-draw" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    prizeDrawMode: "reveal" as const,
    prizeRevealMode: "instant" as const,
    pricePerEntry: 249,
    prizeMaxEntries: 5,
    prizeCurrentEntries: 2,
    prizeDrawDurationDays: 7,
    prizeRevealWindowStart: new Date("2026-08-17"),
    prizeRevealWindowEnd: new Date("2026-08-24"),
    prizeRevealStatus: "closed" as const,
    prizeDrawItems: [
      { itemNumber: 1, title: "Dran Sword 3-60F", description: "Beyblade X starter attack top.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-x-vault-1-20260824/600/600")], condition: "new", estimatedValue: 1499, isWon: false },
      { itemNumber: 2, title: "Hells Scythe 4-60T", description: "Beyblade X defence top.", images: [seedExtMedia("https://picsum.photos/seed/prizedraw-item-x-vault-2-20260824/600/600")], condition: "new", estimatedValue: 1499, isWon: false },
    ],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["prize-draw"],
    createdAt: new Date("2026-08-17"),
    updatedAt: new Date("2026-08-24"),
  },
];
