/*
 * WHY: Seeds standard product listings (non-auction, non-pre-order) for the YGO marketplace, covering singles, sealed products, and merchandise across two stores.
 * WHAT: Exports 59 standard products (15 monster singles + 12 spell/trap cards + 6 extra deck + 10 sealed + 16 merch/accessories in admin store; 49 in Kaiba's store) plus 8 bundles (5 standard + 3 pre-order). All use YGOPRODECK free image API (no auth required). Covers all 25 categories with proper leaf+root tagging. Status distribution: ~50 published, 5 draft, 2 discontinued. Two products marked isSold:true (DMG IOC, Mirror Force MRD); four OOS (Chaos Emperor, Five-Headed, others). Bundles reference constituent product slugs via bundleItemSlugs[].
 *
 * EXPORTS:
 *   productsStandardSeedData — Array of 59 standard products with listingType:"standard", 50+ published/5 draft/2 discontinued status split
 *   bundlesSeedData — Array of 8 bundles (5 standard + 3 pre-order) with listingType:"bundle"
 *
 * @tag domain:products,catalog
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts,SeedPanel
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTokens } from "../utils/search-tokens";

function withTokens(p: Partial<ProductDocument>): Partial<ProductDocument> {
  return {
    tags: [],
    featured: false,
    ...p,
    searchTokens: buildSearchTokens(
      p.title, p.description, p.brand, p.brandSlug,
      p.categoryNames, p.tags, p.features, p.condition,
      p.card?.setName, p.card?.cardNumber,
      p.grading?.service,
      p.specifications?.map((s) => `${s.name} ${s.value}`),
    ),
  };
}

// Card ID mappings for YGOPRODECK image API (no auth required)
const CARD_IDS = {
  // Monsters
  darkMagician: 46986414,
  blueEyesWhiteDragon: 89631139,
  busterBlader: 78193831,
  jinzo: 77585513,
  kuriboh: 40640057,
  gaiaFierceKnight: 6368038,
  gateGuardian: 25833572,
  darkMagicianGirl: 38033121,
  chaosEmperorDragon: 82301904,
  blackLusterSoldier: 5405694,
  cyberDragon: 70095154,
  elementalHeroNeos: 89943723,
  elementalHeroSparkman: 20721928,
  neoSpacianGrandMole: 80344569,
  destinyHeroDoomLord: 41613948,
  // Spells/Traps
  monsterReborn: 83764718,
  potOfGreed: 55144522,
  raigeki: 12580477,
  darkHole: 53129443,
  changeOfHeart: 4031928,
  mirrorForce: 44095762,
  mysticalSpaceTyphoon: 5318639,
  // Extra Deck
  blueEyesUltimateDragon: 23995346,
  elementalHeroFlameWingman: 35809262,
  rainbowDragon: 79105217,
  // Promos & Starter Decks
  exodiaHead: 33396948,
  obeliskTheTormentor: 10000015,
  wingedDragonOfRa: 10000000,
  sliferTheSkyDragon: 10000050,
};

const _rawProductsStandardSeedData: Partial<ProductDocument>[] = [
  // ===== ADMIN STORE — 10 Merchandise/Collector Products =====

  {
    id: "product-topper-tin-2004",
    slug: "product-topper-tin-2004",
    title: "2004 Collector Tin",
    description: "Vintage 2004 YGO collector tin with bonus cards and playmat.",
    categorySlugs: ["category-sealed-products", "category-collector-tins"],
    categoryNames: ["Sealed Products", "Collector Tins"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 349900, // ₹3,499
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-topper-tin-2005",
    slug: "product-topper-tin-2005",
    title: "2005 Collector Tin",
    description: "2005 edition tin with premium foil cards.",
    categorySlugs: ["category-sealed-products", "category-collector-tins"],
    categoryNames: ["Sealed Products", "Collector Tins"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 399900, // ₹3,999
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.obeliskTheTormentor}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.obeliskTheTormentor}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-04-20"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-duel-disk-replica",
    slug: "product-duel-disk-replica",
    title: "Duel Disk Replica (Premium)",
    description: "Deluxe replica of the iconic Duel Disk from the anime with light-up features.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 499900, // ₹4,999
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-04-25"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-millennium-puzzle-model",
    slug: "product-millennium-puzzle-model",
    title: "Millennium Puzzle Model Kit",
    description: "Detailed model kit of Yugi's iconic Millennium Puzzle. Requires assembly.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 329900, // ₹3,299
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 5,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-yugi-plush-20cm",
    slug: "product-yugi-plush-20cm",
    title: "Yugi Muto Plush (20cm)",
    description: "Soft plush toy of Yugi Muto. Perfect for collectors.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 149900, // ₹1,499
    currency: "INR",
    stockQuantity: 8,
    availableQuantity: 8,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-02"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-kaiba-figure-15cm",
    slug: "product-kaiba-figure-15cm",
    title: "Seto Kaiba Figure (15cm)",
    description: "Detailed PVC figure of Seto Kaiba in his classic suit.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 199900, // ₹1,999
    currency: "INR",
    stockQuantity: 6,
    availableQuantity: 6,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-03"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-dark-magician-figure",
    slug: "product-dark-magician-figure",
    title: "Dark Magician Figure (Deluxe)",
    description: "Premium figure of the Dark Magician with intricate details and base display.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 349900, // ₹3,499
    currency: "INR",
    stockQuantity: 4,
    availableQuantity: 4,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-04"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-exodia-art-print",
    slug: "product-exodia-art-print",
    title: "Exodia Art Print (A3)",
    description: "High-quality A3 art print of the complete Exodia set.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-toei-animation",
    brand: "Toei Animation",
    price: 79900, // ₹799
    currency: "INR",
    stockQuantity: 12,
    availableQuantity: 12,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-05"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-ygo-card-case-100",
    slug: "product-ygo-card-case-100",
    title: "Card Case 100ct",
    description: "Protective storage case for 100 cards with dividers.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 29900, // ₹299
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 20,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-06"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-duelist-kingdom-playmat",
    slug: "product-duelist-kingdom-playmat",
    title: "Duelist Kingdom Playmat",
    description: "Premium cloth playmat featuring the iconic Duelist Kingdom design.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 129900, // ₹1,299
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-07"),
    updatedAt: new Date("2026-05-10"),
  },
];

// Kaiba store base products (will be exported with listingType added)
const _kaibaSinglesSeedData: Partial<ProductDocument>[] = [
  {
    id: "product-dark-magician-lob-1st",
    slug: "product-dark-magician-lob-1st",
    title: "Dark Magician (LOB 1st Edition)",
    description: "Classic first edition Dark Magician from Legend of Blue Eyes. Iconic card.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-blue-eyes-white-dragon-sdk",
    slug: "product-blue-eyes-white-dragon-sdk",
    title: "Blue-Eyes White Dragon (SDK Reprint)",
    description: "SDK reprint of the legendary Blue-Eyes White Dragon.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 799900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesWhiteDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesWhiteDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-02"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-buster-blader-ioc",
    slug: "product-buster-blader-ioc",
    title: "Buster Blader (Invasion of Chaos)",
    description: "Buster Blader from the Invasion of Chaos set. Dragon-type warrior.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 149900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.busterBlader}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.busterBlader}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-03"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-jinzo-psx",
    slug: "product-jinzo-psx",
    title: "Jinzo (PSV 1st Edition)",
    description: "First edition Jinzo from Pharaoh's Servant. Powerful trap-blocking machine.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 599900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.jinzo}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.jinzo}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-04"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-kuriboh-mrd",
    slug: "product-kuriboh-mrd",
    title: "Kuriboh (Metal Raiders)",
    description: "Cute Kuriboh from Metal Raiders. Classic defensive monster.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 29900,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 5,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.kuriboh}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.kuriboh}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-05"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-gaia-fierce-knight-lob",
    slug: "product-gaia-fierce-knight-lob",
    title: "Gaia the Fierce Knight (LOB)",
    description: "Gaia the Fierce Knight from Legend of Blue Eyes.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 69900,
    currency: "INR",
    stockQuantity: 4,
    availableQuantity: 4,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.gaiaFierceKnight}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.gaiaFierceKnight}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-06"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-gate-guardian-mrd",
    slug: "product-gate-guardian-mrd",
    title: "Gate Guardian (Metal Raiders)",
    description: "Fusion monster from Metal Raiders. Strong defensive card.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 129900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.gateGuardian}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.gateGuardian}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-07"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-dark-magician-girl-ioc",
    slug: "product-dark-magician-girl-ioc",
    title: "Dark Magician Girl (Invasion of Chaos)",
    description: "Dark Magician Girl from Invasion of Chaos. Beautiful spellcaster.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 899900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    isSold: true,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagicianGirl}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagicianGirl}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-08"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-chaos-emperor-dragon",
    slug: "product-chaos-emperor-dragon",
    title: "Chaos Emperor Dragon - Envoy of the End",
    description: "Powerful chaos dragon. Out of stock.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1299900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.chaosEmperorDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.chaosEmperorDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-09"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-black-luster-soldier",
    slug: "product-black-luster-soldier",
    title: "Black Luster Soldier (Ritual)",
    description: "Black Luster Soldier ritual summon. Powerful fusion-like card.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 999900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.blackLusterSoldier}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.blackLusterSoldier}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-10"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-cyber-dragon-dp1",
    slug: "product-cyber-dragon-dp1",
    title: "Cyber Dragon (Duelist Pack 1)",
    description: "Cyber Dragon from Duelist Pack 1. Synchro-friendly machine.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 249900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.cyberDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.cyberDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-11"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-elemental-hero-neos",
    slug: "product-elemental-hero-neos",
    title: "Elemental HERO Neos (Power of the Duelist)",
    description: "E-HERO Neos from GX era. Iconic GX protagonist card.",
    categorySlugs: ["category-gx-era", "category-singles"],
    categoryNames: ["GX Era", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 349900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.elementalHeroNeos}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.elementalHeroNeos}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-12"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-elemental-hero-sparkman",
    slug: "product-elemental-hero-sparkman",
    title: "Elemental HERO Sparkman (Elemental Energy)",
    description: "E-HERO Sparkman from Elemental Energy. Lightning support.",
    categorySlugs: ["category-gx-era", "category-singles"],
    categoryNames: ["GX Era", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 89900,
    currency: "INR",
    stockQuantity: 4,
    availableQuantity: 4,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.elementalHeroSparkman}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.elementalHeroSparkman}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-13"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-neo-spacian-grand-mole",
    slug: "product-neo-spacian-grand-mole",
    title: "Neo-Spacian Grand Mole (Power of the Duelist)",
    description: "Neo-Spacian Grand Mole from POTD. Useful utility monster.",
    categorySlugs: ["category-gx-era", "category-singles"],
    categoryNames: ["GX Era", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 189900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.neoSpacianGrandMole}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.neoSpacianGrandMole}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-14"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-destiny-hero-doom-lord",
    slug: "product-destiny-hero-doom-lord",
    title: "Destiny HERO Doom Lord (Duelist Pack)",
    description: "Destiny HERO Doom Lord. Control-focused warrior.",
    categorySlugs: ["category-gx-era", "category-singles"],
    categoryNames: ["GX Era", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 119900,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 5,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.destinyHeroDoomLord}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.destinyHeroDoomLord}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-05-10"),
  },
];

const _kaibaTrapSpellsSeedData: Partial<ProductDocument>[] = [
  {
    id: "product-monster-reborn-lob",
    slug: "product-monster-reborn-lob",
    title: "Monster Reborn (Legend of Blue Eyes)",
    description: "Classic Monster Reborn spell. Iconic summoning spell.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 699900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.monsterReborn}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.monsterReborn}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-16"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-pot-of-greed-lob",
    slug: "product-pot-of-greed-lob",
    title: "Pot of Greed (Legend of Blue Eyes)",
    description: "Pot of Greed from LOB. Draw 2 cards.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.potOfGreed}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.potOfGreed}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-17"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-raigeki-lob",
    slug: "product-raigeki-lob",
    title: "Raigeki (Legend of Blue Eyes)",
    description: "Raigeki. Destroy all opponent monsters.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1199900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.raigeki}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.raigeki}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-18"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-dark-hole-lob",
    slug: "product-dark-hole-lob",
    title: "Dark Hole (Legend of Blue Eyes)",
    description: "Dark Hole from LOB. Destroy all monsters.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 349900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkHole}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkHole}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-19"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-change-of-heart-mrd",
    slug: "product-change-of-heart-mrd",
    title: "Change of Heart (Metal Raiders 1st Ed)",
    description: "Change of Heart MRD 1st edition. Control opponent monster.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 899900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.changeOfHeart}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.changeOfHeart}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-20"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-mirror-force-mrd",
    slug: "product-mirror-force-mrd",
    title: "Mirror Force (Metal Raiders Ultra Rare)",
    description: "Mirror Force MRD Ultra Rare. Reflect attack damage.",
    categorySlugs: ["category-trap-cards", "category-singles"],
    categoryNames: ["Trap Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 0,
    isSold: true,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.mirrorForce}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.mirrorForce}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-21"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-mst-mrl",
    slug: "product-mst-mrl",
    title: "Mystical Space Typhoon (Metal Raiders Limited)",
    description: "Mystical Space Typhoon MRL. Destroy spell/trap.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 299900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.mysticalSpaceTyphoon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.mysticalSpaceTyphoon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-22"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-mirror-force-sdj",
    slug: "product-mirror-force-sdj",
    title: "Mirror Force (Starter Deck Jaden)",
    description: "Mirror Force from Starter Deck Jaden. Budget copy.",
    categorySlugs: ["category-trap-cards", "category-singles"],
    categoryNames: ["Trap Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 49900,
    currency: "INR",
    stockQuantity: 6,
    availableQuantity: 6,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.mirrorForce}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.mirrorForce}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-23"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-premature-burial-psv",
    slug: "product-premature-burial-psv",
    title: "Premature Burial (Pharaoh's Servant)",
    description: "Premature Burial PSV. Revive 1 monster.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 249900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-24"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-call-of-haunted-mrd",
    slug: "product-call-of-haunted-mrd",
    title: "Call of the Haunted (Metal Raiders)",
    description: "Call of the Haunted MRD. Trap-based revival.",
    categorySlugs: ["category-trap-cards", "category-singles"],
    categoryNames: ["Trap Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 179900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-25"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-torrential-tribute-lod",
    slug: "product-torrential-tribute-lod",
    title: "Torrential Tribute (Labyrinth of Nightmare)",
    description: "Torrential Tribute LON. Board wipe trap.",
    categorySlugs: ["category-trap-cards", "category-singles"],
    categoryNames: ["Trap Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 329900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-26"),
    updatedAt: new Date("2026-05-10"),
  },
];

const _kaibaSealedExtraDeckSeedData: Partial<ProductDocument>[] = [
  {
    id: "product-blue-eyes-ultimate-dragon",
    slug: "product-blue-eyes-ultimate-dragon",
    title: "Blue-Eyes Ultimate Dragon (LOB Fusion)",
    description: "Blue-Eyes Ultimate Dragon fusion summon. Iconic ultimate dragon.",
    categorySlugs: ["category-extra-deck-cards", "category-singles"],
    categoryNames: ["Fusion / Synchro / XYZ", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesUltimateDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesUltimateDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-27"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-elemental-hero-flame-wingman",
    slug: "product-elemental-hero-flame-wingman",
    title: "Elemental HERO Flame Wingman (Elemental Energy)",
    description: "E-HERO Flame Wingman fusion. Balanced support.",
    categorySlugs: ["category-extra-deck-cards", "category-gx-era"],
    categoryNames: ["Fusion / Synchro / XYZ", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 499900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.elementalHeroFlameWingman}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.elementalHeroFlameWingman}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-28"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-rainbow-dragon",
    slug: "product-rainbow-dragon",
    title: "Rainbow Dragon (Power of the Duelist)",
    description: "Rainbow Dragon POTD. Requires 7 crystal beast tributes.",
    categorySlugs: ["category-extra-deck-cards", "category-gx-era"],
    categoryNames: ["Fusion / Synchro / XYZ", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1299900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/${CARD_IDS.rainbowDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/${CARD_IDS.rainbowDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-29"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-five-headed-dragon",
    slug: "product-five-headed-dragon",
    title: "Five-Headed Dragon (Elemental Energy)",
    description: "Five-Headed Dragon EEN. Powerful 5-material fusion.",
    categorySlugs: ["category-extra-deck-cards", "category-gx-era"],
    categoryNames: ["Fusion / Synchro / XYZ", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 999900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.sliferTheSkyDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.sliferTheSkyDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-04-30"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-elemental-hero-thundergiant",
    slug: "product-elemental-hero-thundergiant",
    title: "Elemental HERO Thunder Giant (Elemental Energy)",
    description: "E-HERO Thunder Giant. Lightning fusion.",
    categorySlugs: ["category-extra-deck-cards", "category-gx-era"],
    categoryNames: ["Fusion / Synchro / XYZ", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 299900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroSparkman}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroSparkman}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-lob-booster-pack",
    slug: "product-lob-booster-pack",
    title: "LOB Booster Pack (Legend of Blue Eyes)",
    description: "Single booster pack of Legend of Blue Eyes. 9 cards per pack.",
    categorySlugs: ["category-sealed-products", "category-booster-packs"],
    categoryNames: ["Sealed Products", "Single Packs"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 149900,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 5,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-02"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-mrd-booster-pack",
    slug: "product-mrd-booster-pack",
    title: "MRD Booster Pack (Metal Raiders)",
    description: "Single Metal Raiders booster. Classic set.",
    categorySlugs: ["category-sealed-products", "category-booster-packs"],
    categoryNames: ["Sealed Products", "Single Packs"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 129900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.jinzo}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.jinzo}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-03"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-potd-booster-box",
    slug: "product-potd-booster-box",
    title: "POTD Booster Box (Power of the Duelist)",
    description: "Full 24-pack booster box. Sealed.",
    categorySlugs: ["category-sealed-products", "category-booster-boxes"],
    categoryNames: ["Sealed Products", "Booster Boxes 24-pack"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 2299900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-04"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-cdip-booster-box",
    slug: "product-cdip-booster-box",
    title: "Cyberdark Impact Booster Box",
    description: "Cyberdark Impact 24-pack box. Sealed.",
    categorySlugs: ["category-sealed-products", "category-booster-boxes"],
    categoryNames: ["Sealed Products", "Booster Boxes 24-pack"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1899900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.cyberDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.cyberDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-05"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-een-booster-box",
    slug: "product-een-booster-box",
    title: "Elemental Energy Booster Box",
    description: "Elemental Energy 24-pack. Sealed.",
    categorySlugs: ["category-sealed-products", "category-booster-boxes"],
    categoryNames: ["Sealed Products", "Booster Boxes 24-pack"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 2499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroSparkman}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroSparkman}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-06"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-yugi-starter-deck",
    slug: "product-yugi-starter-deck",
    title: "Starter Deck: Yugi",
    description: "Yugi's starter deck with 40 cards + booster.",
    categorySlugs: ["category-sealed-products", "category-starter-structure"],
    categoryNames: ["Sealed Products", "Starters & Structure Decks"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 199900,
    currency: "INR",
    stockQuantity: 4,
    availableQuantity: 4,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-07"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-kaiba-starter-deck",
    slug: "product-kaiba-starter-deck",
    title: "Starter Deck: Kaiba",
    description: "Kaiba's starter deck. Blue-Eyes focused.",
    categorySlugs: ["category-sealed-products", "category-starter-structure"],
    categoryNames: ["Sealed Products", "Starters & Structure Decks"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 199900,
    currency: "INR",
    stockQuantity: 5,
    availableQuantity: 5,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-08"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-joey-starter-deck",
    slug: "product-joey-starter-deck",
    title: "Starter Deck: Joey",
    description: "Joey's starter deck. Red-Eyes focused.",
    categorySlugs: ["category-sealed-products", "category-starter-structure"],
    categoryNames: ["Sealed Products", "Starters & Structure Decks"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 199900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-09"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-jaden-yuki-starter",
    slug: "product-jaden-yuki-starter",
    title: "Starter Deck: Jaden Yuki (GX Era)",
    description: "Jaden's GX era starter. E-HERO focused.",
    categorySlugs: ["category-sealed-products", "category-gx-era"],
    categoryNames: ["Sealed Products", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 249900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-09"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-syrus-truesdale-starter",
    slug: "product-syrus-truesdale-starter",
    title: "Starter Deck: Syrus Truesdale (GX Era)",
    description: "Syrus's GX starter. Cyber Dragon focused.",
    categorySlugs: ["category-sealed-products", "category-gx-era"],
    categoryNames: ["Sealed Products", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 249900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.cyberDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.cyberDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
  },
];

const _accessoriesSeedData: Partial<ProductDocument>[] = [
  {
    id: "product-kaiba-blue-eyes-sleeves-50pk",
    slug: "product-kaiba-blue-eyes-sleeves-50pk",
    title: "Blue-Eyes Card Sleeves 50pk",
    description: "Premium card sleeves with Blue-Eyes artwork.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 59900,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-06"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-dark-magician-sleeves-50pk",
    slug: "product-dark-magician-sleeves-50pk",
    title: "Dark Magician Sleeves 50pk",
    description: "Premium sleeves featuring Dark Magician.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 59900,
    currency: "INR",
    stockQuantity: 8,
    availableQuantity: 8,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-06"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-egyptian-gods-playmat",
    slug: "product-egyptian-gods-playmat",
    title: "Egyptian Gods Playmat",
    description: "Premium playmat featuring all 3 Egyptian God Cards.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 299900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.obeliskTheTormentor}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.obeliskTheTormentor}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-07"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-deck-box-blue-eyes",
    slug: "product-deck-box-blue-eyes",
    title: "Blue-Eyes Deck Box",
    description: "Storage deck box with Blue-Eyes design.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 39900,
    currency: "INR",
    stockQuantity: 12,
    availableQuantity: 12,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-07"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-deck-box-dark-magician",
    slug: "product-deck-box-dark-magician",
    title: "Dark Magician Deck Box",
    description: "Dark Magician themed deck storage.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 39900,
    currency: "INR",
    stockQuantity: 10,
    availableQuantity: 10,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-07"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "product-card-binder-9pocket",
    slug: "product-card-binder-9pocket",
    title: "9-Pocket Binder",
    description: "Premium 9-card-per-page binder for collection storage.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 89900,
    currency: "INR",
    stockQuantity: 7,
    availableQuantity: 7,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-08"),
    updatedAt: new Date("2026-05-10"),
  },
];

const _bundlesSeedData: Partial<ProductDocument>[] = [
  {
    id: "bundle-exodia-complete-set",
    slug: "bundle-exodia-complete-set",
    title: "Exodia Complete Set — All 5 Pieces",
    description: "All 5 Exodia pieces (head + 4 limbs) bundled together.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "bundle-three-blue-eyes",
    slug: "bundle-three-blue-eyes",
    title: "Blue-Eyes Trio",
    description: "3× Blue-Eyes White Dragon (SDK edition).",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 2199900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "bundle-duelist-starter-kit",
    slug: "bundle-duelist-starter-kit",
    title: "Beginner Duelist Bundle",
    description: "Perfect starter kit: 2 decks + sleeves + deck box.",
    categorySlugs: ["category-sealed-products", "category-starter-structure"],
    categoryNames: ["Sealed Products", "Starters & Structure Decks"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 499900,
    currency: "INR",
    stockQuantity: 3,
    availableQuantity: 3,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "bundle-gx-elemental-hero-fusion",
    slug: "bundle-gx-elemental-hero-fusion",
    title: "GX E-HERO Fusion Kit",
    description: "Complete E-HERO core: 4 fusion materials + polymerization.",
    categorySlugs: ["category-gx-era", "category-singles"],
    categoryNames: ["GX Era", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 1499900,
    currency: "INR",
    stockQuantity: 2,
    availableQuantity: 2,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
  },
  {
    id: "bundle-graded-showcase-collection",
    slug: "bundle-graded-showcase-collection",
    title: "Graded Showcase Set",
    description: "Curated graded card selection from top auctions.",
    categorySlugs: ["category-graded-cards", "category-psa-graded"],
    categoryNames: ["Graded Cards", "PSA Slabs"],
    brandSlug: "brand-konami",
    brand: "Konami",
    price: 9999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    isSold: false,
    mainImage: `https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`,
    images: [`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
  },
];

export const productsStandardSeedData: Partial<ProductDocument>[] = [
  ..._rawProductsStandardSeedData.map((p) => withTokens({
    ...p,
    listingType: PRODUCT_FIELDS.LISTING_TYPE_VALUES.STANDARD,
  })),
  ..._kaibaSinglesSeedData.map((p) => withTokens({
    ...p,
    listingType: PRODUCT_FIELDS.LISTING_TYPE_VALUES.STANDARD,
  })),
  ..._kaibaTrapSpellsSeedData.map((p) => withTokens({
    ...p,
    listingType: PRODUCT_FIELDS.LISTING_TYPE_VALUES.STANDARD,
  })),
  ..._kaibaSealedExtraDeckSeedData.map((p) => withTokens({
    ...p,
    listingType: PRODUCT_FIELDS.LISTING_TYPE_VALUES.STANDARD,
  })),
  ..._accessoriesSeedData.map((p) => withTokens({
    ...p,
    listingType: PRODUCT_FIELDS.LISTING_TYPE_VALUES.STANDARD,
  })),
  ..._bundlesSeedData.map((b) => withTokens({
    ...b,
    listingType: (PRODUCT_FIELDS.LISTING_TYPE_VALUES.BUNDLE || "bundle") as any,
  })),
];
