/**
 * Auctions Seed Data — Collectibles Edition
 * 6 auctions in all lifecycle states: active-ending-soon, active×2,
 * upcoming, ended (winner), ended (settled).
 * Stored as ProductDocument with isAuction: true.
 * id === slug convention enforced throughout.
 * Prices in INR paise (₹1 = 100 paise).
 */

import type { ProductDocument } from "../features/products/schemas";

const NOW = new Date();
const hoursAhead = (h: number) =>
  new Date(NOW.getTime() + h * 3_600_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const hoursAgo = (h: number) =>
  new Date(NOW.getTime() - h * 3_600_000);

export const productsAuctionsSeedData: Partial<ProductDocument>[] = [
  // ── 1. ACTIVE — ending in 12h (Charizard Base Set #4 PSA 9) ───────────────
  {
    id: "auction-pokemon-charizard-base1-psa9",
    slug: "auction-pokemon-charizard-base1-psa9",
    title:
      "Pokémon Base Set 1st Edition Charizard #4 Holo — PSA 9 MINT (AUCTION)",
    description:
      "An absolutely pristine 1st Edition Base Set Charizard #4 graded PSA 9 MINT — one of the most iconic and sought-after Pokémon cards in existence. The 1st Edition stamp on the left of the artwork, shadow-less frame, and deep crimson fire breath in perfect registration. PSA 9 MINT has four sharp corners, bright lustre, no visible surface scratches, well-centered image. Certificate number visible on slab. This is auction lot 1 of 1 — once this card is gone, there is no re-stock. A generational collectible.",
    category: "category-vintage-tcg",
    brand: "brand-pokemon-company",
    isAuction: true,
    auctionEndDate: hoursAhead(12),
    startingBid: 9999900,
    currentBid: 29999900,
    bidCount: 6,
    reservePrice: 25000000,
    minBidIncrement: 500000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 9999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-aryan-kapoor",
    sellerName: "Aryan Kapoor",
    sellerEmail: "aryan@pokemonpalace.in",
    storeId: "store-pokemon-palace",
    featured: true,
    isPromoted: true,
    tags: [
      "pokemon",
      "charizard",
      "base-set",
      "1st-edition",
      "psa-9",
      "graded",
      "vintage",
      "auction",
    ],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Charizard #4 Holo — Base Set 1st Edition" },
      { name: "Grade", value: "PSA 9 MINT" },
      { name: "Print", value: "1st Edition (stamped)" },
      { name: "Language", value: "English" },
      { name: "Year", value: "1999" },
      { name: "Reserve Price", value: "₹2,50,000" },
    ],
    features: [
      "PSA 9 MINT — 4 sharp corners, bright lustre",
      "1st Edition stamp — most valuable print run",
      "Certificate number confirmed — not a fake slab",
      "Reserve price set at ₹2,50,000",
      "Auto-extend: 5 minutes if bid in final 5 min",
    ],
    shippingInfo:
      "Winner-paid insured shipping via Blue Dart courier. Double-boxed with foam, PSA slab protector, and tamper-evident seal.",
    returnPolicy:
      "No returns on auction lots. Verified photos and PSA certificate provided before shipping. Any dispute about card grade handled via PSA directly.",
    insurance: true,
    insuranceCost: 100000,
    createdAt: daysAgo(14),
    updatedAt: hoursAgo(2),
  },

  // ── 2. ACTIVE — ending in 48h (Exodia 1st Edition LOB PSA 8) ──────────────
  {
    id: "auction-yugioh-lob1-exodia-1st-psa8",
    slug: "auction-yugioh-lob1-exodia-1st-psa8",
    title:
      "Yu-Gi-Oh! Exodia the Forbidden One — LOB-000 1st Edition PSA 8 NM-MT (AUCTION)",
    description:
      "Ultra-rare 1st Edition Exodia the Forbidden One from the original Legend of Blue Eyes White Dragon set (LOB-000), graded PSA 8 Near Mint to Mint. Exodia is one of the most iconic and mythological cards in all of Yu-Gi-Oh — the card that ends the game instantly when all five Exodia pieces are assembled. This 1st Edition LOB-000 printing is the most desirable version, identifiable by the 1st Edition stamp in the lower left of the card frame. PSA 8 NM-MT: four nearly perfect corners, excellent surface, minimal wear. A tournament legend in slab form.",
    category: "category-vintage-tcg",
    brand: "brand-konami",
    isAuction: true,
    auctionEndDate: hoursAhead(48),
    startingBid: 1499900,
    currentBid: 4999900,
    bidCount: 5,
    reservePrice: 4000000,
    minBidIncrement: 250000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 1499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-nisha-reddy",
    sellerName: "Nisha Reddy",
    sellerEmail: "nisha@cardgamehub.in",
    storeId: "store-cardgame-hub",
    featured: true,
    isPromoted: false,
    tags: [
      "yugioh",
      "exodia",
      "lob",
      "1st-edition",
      "psa-8",
      "graded",
      "vintage",
      "auction",
    ],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Exodia the Forbidden One — LOB-000" },
      { name: "Grade", value: "PSA 8 NM-MT" },
      { name: "Print", value: "1st Edition" },
      { name: "Language", value: "English" },
      { name: "Year", value: "2002" },
      { name: "Reserve Price", value: "₹40,000" },
    ],
    features: [
      "PSA 8 NM-MT — nearly perfect condition",
      "1st Edition LOB-000 — rarest print",
      "Exodia — most legendary card in the game",
      "Reserve met — guaranteed to sell",
      "WCS 2022 qualifier-sourced — tournament provenance",
    ],
    shippingInfo:
      "Winner-paid insured shipping. PSA slab shipped in foam-lined rigid mailer via Blue Dart.",
    returnPolicy:
      "No returns on auction lots. Slab photos provided before shipping.",
    insurance: true,
    insuranceCost: 20000,
    createdAt: daysAgo(7),
    updatedAt: hoursAgo(6),
  },

  // ── 3. ACTIVE — ending in 6h (Hot Wheels Redline Pink Camaro 1967) ─────────
  {
    id: "auction-hot-wheels-redline-camaro-pink",
    slug: "auction-hot-wheels-redline-camaro-pink",
    title:
      "Hot Wheels Redline 1967 Custom Camaro — Spectraflame Pink (Vintage, AUCTION)",
    description:
      "Extremely rare 1967 Hot Wheels Redline Custom Camaro in Spectraflame Pink — one of the most sought-after Redline colourways among serious diecast collectors. The Spectraflame Pink finish has a characteristic metallic candy-pink lustre that was only produced for a very limited run. This example is in Very Good (VG) condition: strong pink spectraflame with minor surface abrasion on the hood, red-line tyres intact, all four wheels spin freely. Sourced from a Japan Redline collector who acquired it at a 1980s Tokyo toy show. No repaints, no replaced parts. Accompanied by a collector's provenance letter.",
    category: "category-hot-wheels",
    brand: "brand-hot-wheels",
    isAuction: true,
    auctionEndDate: hoursAhead(6),
    startingBid: 499900,
    currentBid: 1299900,
    bidCount: 4,
    reservePrice: 1000000,
    minBidIncrement: 100000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-vikram-mehta",
    sellerName: "Vikram Mehta",
    sellerEmail: "vikram@diecastdepot.in",
    storeId: "store-diecast-depot",
    featured: false,
    isPromoted: true,
    tags: [
      "hot-wheels",
      "redline",
      "1967",
      "camaro",
      "pink",
      "spectraflame",
      "vintage",
      "rare",
      "auction",
    ],
    condition: "used",
    specifications: [
      { name: "Year", value: "1967" },
      { name: "Scale", value: "1:64" },
      { name: "Colour", value: "Spectraflame Pink" },
      { name: "Wheels", value: "Redline" },
      { name: "Condition Grade", value: "Very Good (VG)" },
      { name: "Reserve Price", value: "₹10,000" },
    ],
    features: [
      "Spectraflame Pink — rarest Camaro Redline colourway",
      "Japan collector provenance — Tokyo toy show 1980s",
      "Original — no repaints, no replaced parts",
      "Collector's provenance letter included",
      "Reserve met — guaranteed to sell",
    ],
    shippingInfo:
      "Winner-paid insured shipping. Bubble-wrapped in rigid foam-lined mailer.",
    returnPolicy:
      "No returns on auction lots. Detailed photos taken before shipping for reference.",
    insurance: true,
    insuranceCost: 5000,
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(1),
  },

  // ── 4. UPCOMING — starts in 72h (Beyblade Metal Fusion BB-10 Signed) ───────
  {
    id: "auction-beyblade-metal-fusion-signed",
    slug: "auction-beyblade-metal-fusion-signed",
    title:
      "Beyblade Metal Fusion BB-10 Storm Pegasus — Factory Sealed + Signed by Voice Actor (UPCOMING AUCTION)",
    description:
      "Extraordinary lot: a factory-sealed Beyblade Metal Fusion BB-10 Storm Pegasus Starter Set, signed on the outer box by the Japanese voice actor for Ginga Hagane (Kei Shindo), with certificate of authenticity. BB-10 Storm Pegasus is the iconic starting Beyblade for the Metal Fusion series, and factory-sealed examples are increasingly rare as most were opened immediately. The signature was obtained at WonFes 2019 and is accompanied by a photograph of the signing session. Opening bid at ₹2,999 — no reserve. This auction starts in 72 hours.",
    category: "category-beyblade-classic",
    brand: "brand-beyblade",
    isAuction: true,
    auctionEndDate: daysAhead(7),
    startingBid: 299900,
    currentBid: 0,
    bidCount: 0,
    reservePrice: 0,
    minBidIncrement: 50000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 299900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=800&fit=crop",
    ],
    status: "published",
    sellerId: "user-rohit-joshi",
    sellerName: "Rohit Joshi",
    sellerEmail: "rohit@beyladearena.in",
    storeId: "store-beyblade-arena",
    featured: false,
    isPromoted: false,
    tags: [
      "beyblade",
      "metal-fusion",
      "bb-10",
      "storm-pegasus",
      "signed",
      "factory-sealed",
      "vintage",
      "upcoming-auction",
    ],
    condition: "new",
    specifications: [
      { name: "Product", value: "BB-10 Storm Pegasus Starter Set" },
      { name: "Generation", value: "Metal Fusion (2008)" },
      { name: "Condition", value: "Factory sealed" },
      { name: "Signature", value: "Kei Shindo (Japanese VA — Ginga Hagane)" },
      { name: "Event", value: "Wonder Festival 2019" },
      { name: "Reserve", value: "No reserve — sells at any price" },
    ],
    features: [
      "Factory-sealed BB-10 — rare to find sealed",
      "Signed by Japanese voice actor at WonFes 2019",
      "Certificate of authenticity + signing photo",
      "No reserve — auction opens to all bids",
      "Auction starts in 72 hours — set a reminder",
    ],
    shippingInfo:
      "Winner-paid insured shipping. Foam-lined rigid mailer, tamper-evident seal.",
    returnPolicy:
      "No returns on auction lots. All details disclosed upfront — no hidden flaws.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },

  // ── 5. ENDED — 7 days ago, winner declared (Gundam PG Strike Freedom) ──────
  {
    id: "auction-gundam-pg-strike-freedom-box",
    slug: "auction-gundam-pg-strike-freedom-box",
    title:
      "Bandai Gunpla PG 1/60 Strike Freedom Gundam — Factory Sealed (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — This auction has ended. Final winning bid: ₹29,999. A factory-sealed Bandai Perfect Grade 1/60 Strike Freedom Gundam — Bandai's magnum opus kit, widely regarded as the most complex and visually stunning Gunpla ever produced. The PG 1/60 stands 37 cm tall assembled, features 500+ parts, full LED lighting system runner (sold separately), internal frame with gold-plated parts, wing of light effect set, and METEOR unit attachment. The winner has been notified and shipment is being arranged.",
    category: "category-gunpla",
    brand: "brand-bandai",
    isAuction: true,
    auctionEndDate: daysAgo(7),
    startingBid: 999900,
    currentBid: 2999900,
    bidCount: 6,
    reservePrice: 2500000,
    minBidIncrement: 250000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 999900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1657664072470-99b02c2143f2?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1657664072470-99b02c2143f2?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=800&h=800&fit=crop",
    ],
    status: "sold",
    sellerId: "user-admin-letitrip",
    sellerName: "LetItRip Admin",
    sellerEmail: "admin@letitrip.in",
    storeId: "store-letitrip-official",
    featured: false,
    isPromoted: false,
    tags: [
      "gunpla",
      "perfect-grade",
      "strike-freedom",
      "bandai",
      "factory-sealed",
      "auction",
      "ended",
    ],
    condition: "new",
    specifications: [
      { name: "Grade", value: "Perfect Grade (PG)" },
      { name: "Scale", value: "1/60" },
      { name: "Height assembled", value: "~37 cm", unit: "cm" },
      { name: "Parts", value: "500+" },
      { name: "Final Bid", value: "₹29,999" },
      { name: "Status", value: "Auction ended — winner notified" },
    ],
    features: [
      "PG 1/60 Strike Freedom — most complex PG ever",
      "500+ parts — internal gold frame",
      "Wing of Light effect set included",
      "METEOR unit attachment",
      "Factory sealed — auction now closed",
    ],
    shippingInfo: "Shipping arranged with winner. Auction closed.",
    returnPolicy: "Auction ended. No returns.",
    createdAt: daysAgo(21),
    updatedAt: daysAgo(7),
  },

  // ── 6. ENDED — 30 days ago (Bandai DBZ Bulma Vintage) ─────────────────────
  {
    id: "auction-bandai-dbz-bulma-vintage",
    slug: "auction-bandai-dbz-bulma-vintage",
    title:
      "Bandai Dragon Ball Z Bulma Vintage Figure — 1989 First-Run (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — This auction has ended. Final winning bid: ₹7,999. A rare 1989 first-run Bandai Dragon Ball Z Bulma figure from the original Bandai Japanese toy line, released to coincide with the DBZ anime broadcast. This early figure has the original Bandai stamp on the base, painted hair and face details accurate to the original 1989 anime character sheet, and all original accessories. Condition is Good (G) — honest display wear, original paint throughout, no missing parts. Sourced from a Tokyo toy collector through the 2024 Japan trip.",
    category: "category-vintage-figures",
    brand: "brand-bandai",
    isAuction: true,
    auctionEndDate: daysAgo(30),
    startingBid: 299900,
    currentBid: 799900,
    bidCount: 5,
    reservePrice: 0,
    minBidIncrement: 50000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 299900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1560762484-813fc97650a0?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
    ],
    status: "sold",
    sellerId: "user-vikram-mehta",
    sellerName: "Vikram Mehta",
    sellerEmail: "vikram@diecastdepot.in",
    storeId: "store-diecast-depot",
    featured: false,
    isPromoted: false,
    tags: [
      "bandai",
      "dragon-ball-z",
      "dbz",
      "bulma",
      "1989",
      "vintage",
      "figure",
      "auction",
      "ended",
    ],
    condition: "used",
    specifications: [
      { name: "Character", value: "Bulma" },
      { name: "Series", value: "Dragon Ball Z" },
      { name: "Year", value: "1989 (first-run)" },
      { name: "Manufacturer", value: "Bandai Japan" },
      { name: "Condition Grade", value: "Good (G) — original paint" },
      { name: "Final Bid", value: "₹7,999" },
    ],
    features: [
      "1989 first-run Bandai DBZ figure",
      "Original Bandai Japan stamp on base",
      "All original accessories — no missing parts",
      "Tokyo collector provenance (2024 Japan trip)",
      "Auction closed — 30 days ago",
    ],
    shippingInfo: "Shipped to winner. Auction completed and settled.",
    returnPolicy: "Auction ended. No returns.",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(30),
  },
];
