/*
 * WHY: Seeds auction listings for the YGO marketplace, providing high-value graded cards and collectibles with dynamic bidding mechanics.
 * WHAT: Exports 20 active/ended auctions (16 Kaiba + 4 Admin store). Each auction includes starting bid, buy-it-now price, grading info (PSA/BGS/CGC or raw), status flags (active/sold/draft), and bid history counts. All use YGOPRODECK images. Status distribution: 14 active (published), 4 sold (ended), 2 draft (upcoming).
 *
 * EXPORTS:
 *   productsAuctionsSeedData — Array of 20 auction products with listingType:"auction"
 *
 * @tag domain:auctions,products
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts,SeedPanel
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTokens } from "../utils/search-tokens";
import { seedExtMedia } from "./_helpers/media";

function withTokens(p: Partial<ProductDocument>): Partial<ProductDocument> {
  return {
    tags: [],
    featured: false,
    price: p.startingBid ?? 0,
    stockQuantity: 1,
    availableQuantity: p.isSold ? 0 : 1,
    ...p,
    searchTokens: buildSearchTokens(
      p.title, p.description, p.brand, p.brandSlug,
      p.categoryNames, p.tags, p.features, p.condition,
      p.card?.setName, p.card?.cardNumber,
      p.grading?.service,
      p.specifications?.map((s) => `${s.name} ${s.value}`),
    ),
  };
}

const CARD_IDS = {
  darkMagician: 46986414,
  blueEyesWhiteDragon: 89631139,
  darkMagicianGirl: 38033121,
  chaosEmperorDragon: 82301904,
  potOfGreed: 55144522,
  raigeki: 12580477,
  mirrorForce: 44095762,
  monsterReborn: 83764718,
  changeOfHeart: 4031928,
  blueEyesUltimateDragon: 23995346,
  rainbowDragon: 79105217,
  exodiaHead: 33396948,
  jinzo: 77585513,
  gateGuardian: 25833572,
  elementalHeroNeos: 89943723,
};

const _kaibaAuctionsSeedData: Partial<ProductDocument>[] = [
  {
    id: "auction-psa10-blue-eyes-lob",
    slug: "auction-psa10-blue-eyes-lob",
    title: "Blue-Eyes White Dragon (LOB PSA 10)",
    description: "First Edition Blue-Eyes White Dragon LOB in PSA 10 gem mint condition. Ultra rare.",
    categorySlugs: ["category-graded-cards", "category-psa-graded"],
    categoryNames: ["Graded Cards", "PSA Slabs"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 4999900, // ₹49,999
    buyItNowPriceInPaise: 9999900, // ₹99,999
    currentBid: 7999900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // +3 days
    bidCount: 8,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesWhiteDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesWhiteDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: {
      service: "PSA",
      grade: 10,
      certNumber: "PSA-YGO-112233",
    },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-18"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-psa9-dark-magician-lob",
    slug: "auction-psa9-dark-magician-lob",
    title: "Dark Magician (LOB PSA 9)",
    description: "First Edition Dark Magician LOB in PSA 9 mint condition.",
    categorySlugs: ["category-graded-cards", "category-psa-graded"],
    categoryNames: ["Graded Cards", "PSA Slabs"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 2999900,
    buyItNowPriceInPaise: 5999900,
    currentBid: 4499900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    bidCount: 6,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 9, certNumber: "PSA-YGO-334455" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-17"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-1st-ed-pot-of-greed",
    slug: "auction-1st-ed-pot-of-greed",
    title: "Pot of Greed (LOB 1st Edition)",
    description: "1st Edition Pot of Greed from LOB. Raw, near mint condition.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 1499900,
    buyItNowPriceInPaise: 2999900,
    currentBid: 2299900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    bidCount: 4,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.potOfGreed}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.potOfGreed}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-19"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-psa9-chaos-emperor",
    slug: "auction-psa9-chaos-emperor",
    title: "Chaos Emperor Dragon (IOC PSA 9)",
    description: "Chaos Emperor Dragon IOC in PSA 9 condition. Powerful card.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 999900,
    buyItNowPriceInPaise: 1999900,
    currentBid: 1599900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    bidCount: 5,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.chaosEmperorDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.chaosEmperorDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 9, certNumber: "PSA-YGO-556677" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-14"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-1st-ed-mirror-force",
    slug: "auction-1st-ed-mirror-force",
    title: "Mirror Force (MRD 1st Edition)",
    description: "1st Edition Mirror Force from Metal Raiders.",
    categorySlugs: ["category-trap-cards", "category-singles"],
    categoryNames: ["Trap Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 799900,
    buyItNowPriceInPaise: 1499900,
    currentBid: 1199900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    bidCount: 3,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.mirrorForce}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.mirrorForce}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-18"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-bgs95-dark-magician-girl",
    slug: "auction-bgs95-dark-magician-girl",
    title: "Dark Magician Girl (IOC BGS 9.5)",
    description: "Dark Magician Girl IOC in BGS 9.5 condition. Gorgeous card.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 3499900,
    buyItNowPriceInPaise: 6999900,
    currentBid: 5499900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    bidCount: 7,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagicianGirl}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagicianGirl}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "BGS", grade: 9.5, certNumber: "BGS-YGO-778899" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-16"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-raw-lob-complete-set",
    slug: "auction-raw-lob-complete-set",
    title: "LOB Complete Set (Raw NM)",
    description: "All cards from Legend of Blue Eyes set in near mint raw condition. Complete collection.",
    categorySlugs: ["category-singles"],
    categoryNames: ["Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 4999900,
    buyItNowPriceInPaise: 8999900,
    currentBid: 7499900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    bidCount: 6,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-11"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-psa8-monster-reborn",
    slug: "auction-psa8-monster-reborn",
    title: "Monster Reborn (LOB PSA 8)",
    description: "Monster Reborn LOB in PSA 8 very good condition.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 399900,
    buyItNowPriceInPaise: 799900,
    currentBid: 599900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    bidCount: 2,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.monsterReborn}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.monsterReborn}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 8, certNumber: "PSA-YGO-990011" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-19"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-cgc10-raigeki",
    slug: "auction-cgc10-raigeki",
    title: "Raigeki (LOB CGC 10)",
    description: "Raigeki LOB in CGC 10 pristine condition. Extremely rare.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 999900,
    buyItNowPriceInPaise: 1999900,
    currentBid: 1699900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    bidCount: 4,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.raigeki}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.raigeki}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "CGC", grade: 10, certNumber: "CGC-YGO-221133" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-17"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-1st-ed-black-luster-soldier",
    slug: "auction-1st-ed-black-luster-soldier",
    title: "Black Luster Soldier (RL 1st Edition)",
    description: "1st Edition Black Luster Soldier from Ritual summon era.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 1499900,
    buyItNowPriceInPaise: 2999900,
    currentBid: 2499900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    bidCount: 5,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-13"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-psa9-five-headed-dragon",
    slug: "auction-psa9-five-headed-dragon",
    title: "Five-Headed Dragon (EEN PSA 9)",
    description: "Five-Headed Dragon from Elemental Energy in PSA 9 condition.",
    categorySlugs: ["category-extra-deck-cards", "category-gx-era"],
    categoryNames: ["Fusion / Synchro / XYZ", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 699900,
    buyItNowPriceInPaise: 1299900,
    currentBid: 999900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    bidCount: 3,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.rainbowDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.rainbowDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 9, certNumber: "PSA-YGO-332244" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-18"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-psa10-rainbow-dragon",
    slug: "auction-psa10-rainbow-dragon",
    title: "Rainbow Dragon (POTD PSA 10)",
    description: "Rainbow Dragon Power of the Duelist in PSA 10 gem mint condition.",
    categorySlugs: ["category-extra-deck-cards", "category-gx-era"],
    categoryNames: ["Fusion / Synchro / XYZ", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 1999900,
    buyItNowPriceInPaise: 3999900,
    currentBid: 3199900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    bidCount: 6,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.rainbowDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.rainbowDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 10, certNumber: "PSA-YGO-443355" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-15"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-raw-jaden-starter-sealed",
    slug: "auction-raw-jaden-starter-sealed",
    title: "Jaden Yuki Starter Deck (SEALED 2006)",
    description: "Factory sealed Jaden Yuki Starter Deck from 2006. Vintage collectible.",
    categorySlugs: ["category-sealed-products", "category-gx-era"],
    categoryNames: ["Sealed Products", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 799900,
    buyItNowPriceInPaise: 1499900,
    currentBid: 1199900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    bidCount: 2,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-19"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-psa8-change-of-heart",
    slug: "auction-psa8-change-of-heart",
    title: "Change of Heart (MRD 1st Ed PSA 8)",
    description: "Change of Heart Metal Raiders 1st Edition in PSA 8 very good condition.",
    categorySlugs: ["category-spell-cards", "category-singles"],
    categoryNames: ["Spell / Magic Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 599900,
    buyItNowPriceInPaise: 1199900,
    currentBid: 899900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    bidCount: 3,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.changeOfHeart}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.changeOfHeart}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 8, certNumber: "PSA-YGO-554466" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-16"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-ended-psa10-exodia",
    slug: "auction-ended-psa10-exodia",
    title: "Exodia Complete Set (PSA 10 ENDED)",
    description: "Complete Exodia set all pieces PSA 10. Auction ended — winner announced.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 999900,
    currentBid: 8999900, // Final winning bid
    currency: "INR",
    auctionEndDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // -2 days (ended)
    bidCount: 12,
    bidsHaveStarted: true,
    isSold: true,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 10, certNumber: "PSA-YGO-665577" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-06"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-ended-bgs10-jinzo",
    slug: "auction-ended-bgs10-jinzo",
    title: "Jinzo (PSV BGS 10 ENDED)",
    description: "Jinzo PSV in BGS 10 pristine condition. Auction ended.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 499900,
    currentBid: 3499900, // Final winning bid
    currency: "INR",
    auctionEndDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // -3 days
    bidCount: 8,
    bidsHaveStarted: true,
    isSold: true,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.darkMagician}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "BGS", grade: 10, certNumber: "BGS-YGO-776688" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-08"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-ended-raw-sdk-kaiba",
    slug: "auction-ended-raw-sdk-kaiba",
    title: "SDK Kaiba Deck (SEALED ENDED)",
    description: "SDK Kaiba Starter Deck sealed. Vintage auction concluded.",
    categorySlugs: ["category-sealed-products"],
    categoryNames: ["Sealed Products"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 299900,
    currentBid: 1699900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // -5 days
    bidCount: 6,
    bidsHaveStarted: true,
    isSold: true,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.blueEyesWhiteDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-02"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-ended-psa9-gate-guardian",
    slug: "auction-ended-psa9-gate-guardian",
    title: "Gate Guardian (MRD PSA 9 ENDED)",
    description: "Gate Guardian Metal Raiders PSA 9. Completed auction.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 399900,
    currentBid: 1299900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // -7 days
    bidCount: 5,
    bidsHaveStarted: true,
    isSold: true,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.gateGuardian}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.gateGuardian}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "PSA", grade: 9, certNumber: "PSA-YGO-887799" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-upcoming-gx-promo-set",
    slug: "auction-upcoming-gx-promo-set",
    title: "GX Promo Set (UPCOMING)",
    description: "Special GX era promotional card set. Auction starts soon.",
    categorySlugs: ["category-gx-era", "category-singles"],
    categoryNames: ["GX Era", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 999900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // +14 days
    bidCount: 0,
    bidsHaveStarted: false,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.elementalHeroNeos}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-20"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-upcoming-duelist-league",
    slug: "auction-upcoming-duelist-league",
    title: "Duelist League Promo (UPCOMING)",
    description: "Duelist League promotional cards from tournament. Coming soon.",
    categorySlugs: ["category-singles"],
    categoryNames: ["Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 499900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000), // +21 days
    bidCount: 0,
    bidsHaveStarted: false,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.DRAFT,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-20"),
    updatedAt: new Date("2026-05-21"),
  },
];

const _adminAuctionsSeedData: Partial<ProductDocument>[] = [
  {
    id: "auction-admin-ra-authentic-card",
    slug: "auction-admin-ra-authentic-card",
    title: "The Winged Dragon of Ra — God Card (Authentic)",
    description: "Authentic God Card Ra from official release. Museum-quality collectible.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 1999900,
    buyItNowPriceInPaise: 3999900,
    currentBid: 3199900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    bidCount: 4,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-15"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-admin-obelisk-authentic",
    slug: "auction-admin-obelisk-authentic",
    title: "Obelisk the Tormentor — Limited Edition",
    description: "Limited edition Obelisk God Card. Certified original.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 2499900,
    buyItNowPriceInPaise: 4999900,
    currentBid: 3899900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    bidCount: 5,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-12"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-admin-exodia-leg-set",
    slug: "auction-admin-exodia-leg-set",
    title: "Exodia Limb Set (4 pieces, 1st Ed)",
    description: "All 4 limbs of Exodia in 1st Edition condition. Rare collector set.",
    categorySlugs: ["category-monster-cards", "category-singles"],
    categoryNames: ["Monster Cards", "Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 799900,
    buyItNowPriceInPaise: 1499900,
    currentBid: 1099900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    bidCount: 3,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.exodiaHead}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-18"),
    updatedAt: new Date("2026-05-21"),
  },
  {
    id: "auction-admin-ended-yugi-promo",
    slug: "auction-admin-ended-yugi-promo",
    title: "Yugi Muto Promo Card (ENDED)",
    description: "Exclusive Yugi Muto promo card. Auction completed.",
    categorySlugs: ["category-singles"],
    categoryNames: ["Singles"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 299900,
    currentBid: 899900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // -4 days
    bidCount: 4,
    bidsHaveStarted: true,
    isSold: true,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/cropped/${CARD_IDS.darkMagician}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-letitrip-official",
    storeName: "LetItRip Official",
    createdAt: new Date("2026-05-05"),
    updatedAt: new Date("2026-05-21"),
  },
  // ===== Category-coverage backfill (BGS / CGC / Raw NM / set-specific era tags) =====
  {
    id: "auction-bgs-blue-eyes-sdk",
    slug: "auction-bgs-blue-eyes-sdk",
    title: "Blue-Eyes White Dragon (SDK BGS 9.5)",
    description: "Starter Deck Kaiba Blue-Eyes White Dragon graded BGS 9.5 (Gem Mint).",
    categorySlugs: ["category-graded-cards", "category-bgs-graded", "category-duel-monsters-era"],
    categoryNames: ["Graded Cards", "BGS Slabs", "Duel Monsters Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 1899900,
    buyItNowPriceInPaise: 3499900,
    currentBid: 2399900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    bidCount: 5,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesWhiteDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.blueEyesWhiteDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "BGS", grade: 9.5, certNumber: "BGS-YGO-557788" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-20"),
    updatedAt: new Date("2026-05-22"),
  },
  {
    id: "auction-cgc-jinzo-psv",
    slug: "auction-cgc-jinzo-psv",
    title: "Jinzo (PSV 1st Ed CGC 9)",
    description: "Pharaoh's Servant 1st Edition Jinzo graded CGC 9 (Mint).",
    categorySlugs: ["category-graded-cards", "category-cgc-graded", "category-pharaoh-servant", "category-duel-monsters-era"],
    categoryNames: ["Graded Cards", "CGC Slabs", "Pharaoh's Servant", "Duel Monsters Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 1199900,
    buyItNowPriceInPaise: 2299900,
    currentBid: 1599900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    bidCount: 3,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.jinzo}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.jinzo}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    grading: { service: "CGC", grade: 9, certNumber: "CGC-YGO-220033" },
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-19"),
    updatedAt: new Date("2026-05-22"),
  },
  {
    id: "auction-raw-nm-gate-guardian-mrd",
    slug: "auction-raw-nm-gate-guardian-mrd",
    title: "Gate Guardian (MRD 1st Ed, Raw NM)",
    description: "Metal Raiders 1st Edition Gate Guardian, ungraded, certified near-mint by independent reviewer.",
    categorySlugs: ["category-monster-cards", "category-singles", "category-raw-near-mint", "category-metal-raiders", "category-duel-monsters-era"],
    categoryNames: ["Monster Cards", "Singles", "Raw NM", "Metal Raiders", "Duel Monsters Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 499900,
    buyItNowPriceInPaise: 999900,
    currentBid: 699900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    bidCount: 2,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.gateGuardian}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.gateGuardian}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-18"),
    updatedAt: new Date("2026-05-22"),
  },
  {
    id: "auction-soi-rainbow-dragon",
    slug: "auction-soi-rainbow-dragon",
    title: "Rainbow Dragon (SOI 1st Ed)",
    description: "Shadow of Infinity 1st Edition Rainbow Dragon. GX-era ultimate beast.",
    categorySlugs: ["category-extra-deck-cards", "category-singles", "category-shadow-of-infinity", "category-gx-era"],
    categoryNames: ["Extra Deck Cards", "Singles", "Shadow of Infinity", "GX Era"],
    brandSlug: "brand-konami",
    brand: "Konami",
    startingBid: 799900,
    buyItNowPriceInPaise: 1599900,
    currentBid: 1099900,
    currency: "INR",
    auctionEndDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
    bidCount: 4,
    bidsHaveStarted: true,
    isSold: false,
    mainImage: seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.rainbowDragon}.jpg`),
    images: [seedExtMedia(`https://images.ygoprodeck.com/images/cards/${CARD_IDS.rainbowDragon}.jpg`)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.USED,
    storeId: "store-kaiba-corp-cards",
    storeName: "Kaiba Corp Card Vault",
    createdAt: new Date("2026-05-17"),
    updatedAt: new Date("2026-05-22"),
  },
];

export const productsAuctionsSeedData: Partial<ProductDocument>[] = [
  ..._kaibaAuctionsSeedData.map((a) => withTokens({
    ...a,
    listingType: PRODUCT_FIELDS.LISTING_TYPE_VALUES.AUCTION,
  })),
  ..._adminAuctionsSeedData.map((a) => withTokens({
    ...a,
    listingType: PRODUCT_FIELDS.LISTING_TYPE_VALUES.AUCTION,
  })),
];
