/*
 * WHY: `listingType: "art"` shares ProductPrintMeta (size/material/finish/editionSize)
 *      with "stickers" — both printed-only physical goods. Previously left as an empty
 *      stub with the note "out of scope for the minimal Beyblade-focused demo catalog,"
 *      but unlike "live," art prints fit the Beyblade theme naturally as fan-art (see
 *      CLAUDE.md seed-data blandness sweep, 2026-08-20 session).
 * WHAT: Exports 6 Beyblade fan-art print listings on Beyblade Arena, varying size,
 *       material, finish, and edition size (including one open-edition, no editionSize).
 *
 * EXPORTS:
 *   productsArtSeedData — Array of 6 Partial<ProductDocument> with listingType:"art"
 *
 * @tag domain:products,art
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTxt } from "../utils/search-txt";
import { seedPhoto } from "./_helpers/media";

export const productsArtSeedData: Partial<ProductDocument>[] = [
  {
    id: "art-dranzer-phoenix-poster",
    slug: "art-dranzer-phoenix-poster",
    title: "Dranzer Phoenix Rising — Fan Art Poster",
    description: "A vibrant fan-art poster of Dranzer erupting in phoenix flame, hand-illustrated and giclée-printed on matte photo paper.",
    categorySlugs: ["category-stadiums-standard","category-gear-stadiums","category-battle-gear","category-spinning-tops"],
    categoryNames: ["Standard Stadiums","Stadiums","Battle Gear","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 599,
    currency: "INR",
    stockQuantity: 20,
    availableQuantity: 20,
    isSold: false,
    mainImage: seedPhoto("art-image-dranzer-phoenix-1-20260817", 900, 900),
    images: [
      seedPhoto("art-image-dranzer-phoenix-1-20260817", 900, 900),
      seedPhoto("art-image-dranzer-phoenix-2-20260817", 900, 900),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "art" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "12x18 in", material: "Matte photo paper", finish: "Matte" },
    customFields: [],
    customSections: [],
    featured: true,
    isPromoted: false,
    isOnSale: false,
    tags: ["fan-art", "poster"],
    createdAt: new Date("2026-08-17"),
    updatedAt: new Date("2026-08-17"),
    searchTxt: buildSearchTxt([
      "Dranzer Phoenix Rising — Fan Art Poster",
      "Vibrant fan-art poster of Dranzer erupting in phoenix flame.",
      "Beyblade",
      "brand-beyblade",
      ["Spinning Tops"],
      ["fan-art", "poster"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "art-valkyrie-holographic-print",
    slug: "art-valkyrie-holographic-print",
    title: "Beyblade Burst Valkyrie — Holographic Art Print (Limited /100)",
    description: "A limited-edition holographic art print of Valkyrie mid-battle, numbered out of 100. Ships in a rigid mailer to prevent bending.",
    categorySlugs: ["category-burst-classic","category-burst-tops","category-beyblade-burst","category-spinning-tops"],
    categoryNames: ["Burst Classic","Burst Tops","Beyblade Burst","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 1299,
    currency: "INR",
    stockQuantity: 100,
    availableQuantity: 37,
    isSold: false,
    mainImage: seedPhoto("art-image-valkyrie-holo-1-20260818", 900, 900),
    images: [
      seedPhoto("art-image-valkyrie-holo-1-20260818", 900, 900),
      seedPhoto("art-image-valkyrie-holo-2-20260818", 900, 900),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "art" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "8x10 in", material: "Holographic cardstock", finish: "Holographic", editionSize: 100 },
    customFields: [{ key: "Numbered Edition", type: "boolean", value: "true" }],
    customSections: [],
    featured: true,
    isPromoted: true,
    isOnSale: false,
    tags: ["fan-art", "limited-run"],
    createdAt: new Date("2026-08-18"),
    updatedAt: new Date("2026-08-19"),
    searchTxt: buildSearchTxt([
      "Beyblade Burst Valkyrie — Holographic Art Print (Limited /100)",
      "Limited-edition holographic art print of Valkyrie, numbered out of 100.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Burst", "Spinning Tops"],
      ["fan-art", "limited-run"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "art-beyblade-x-lineup-canvas",
    slug: "art-beyblade-x-lineup-canvas",
    title: "Beyblade X Full Lineup — Canvas Print",
    description: "A gallery-style canvas print featuring the full current Beyblade X roster in battle formation. Stretched and ready to hang.",
    categorySlugs: ["category-x-starters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Starter Sets","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 2499,
    currency: "INR",
    stockQuantity: 15,
    availableQuantity: 15,
    isSold: false,
    mainImage: seedPhoto("art-image-x-lineup-canvas-1-20260819", 900, 900),
    images: [seedPhoto("art-image-x-lineup-canvas-1-20260819", 900, 900)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "art" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "16x20 in", material: "Canvas", finish: "Matte" },
    customFields: [],
    customSections: [
      {
        id: "care-instructions",
        title: "Care Instructions",
        text: "Wipe with a dry microfiber cloth only. Keep out of direct sunlight to preserve color vibrancy over time.",
      },
    ],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["fan-art", "canvas"],
    createdAt: new Date("2026-08-19"),
    updatedAt: new Date("2026-08-19"),
    searchTxt: buildSearchTxt([
      "Beyblade X Full Lineup — Canvas Print",
      "Gallery-style canvas print featuring the full current Beyblade X roster.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["fan-art", "canvas"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "art-metal-fight-vintage-poster",
    slug: "art-metal-fight-vintage-poster",
    title: "Metal Fight Beyblade — Vintage-Style Poster (Open Edition)",
    description: "A retro-styled poster celebrating the Metal Fight era, printed on demand — open edition, no print run limit.",
    categorySlugs: ["category-metal-fusion","category-metal-tops","category-beyblade-metal","category-spinning-tops"],
    categoryNames: ["Metal Fusion","Metal Fight Tops","Beyblade Metal Fight","Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 449,
    currency: "INR",
    stockQuantity: 999,
    availableQuantity: 999,
    isSold: false,
    mainImage: seedPhoto("art-image-metal-vintage-1-20260819", 900, 900),
    images: [seedPhoto("art-image-metal-vintage-1-20260819", 900, 900)],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "art" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "11x17 in", material: "Matte photo paper", finish: "Matte" },
    customFields: [{ key: "Print on Demand", type: "boolean", value: "true" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["fan-art", "poster", "vintage-collectible"],
    createdAt: new Date("2026-08-19"),
    updatedAt: new Date("2026-08-19"),
    searchTxt: buildSearchTxt([
      "Metal Fight Beyblade — Vintage-Style Poster (Open Edition)",
      "Retro-styled poster celebrating the Metal Fight era, open edition.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade Metal Fight", "Spinning Tops"],
      ["fan-art", "poster", "vintage-collectible"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    id: "art-original-series-anniversary-print",
    slug: "art-original-series-anniversary-print",
    title: "Original Series 25th Anniversary — Glossy Art Print",
    description: "A commemorative glossy print marking 25 years of the original Beyblade series, featuring Dragoon, Dranzer, Driger, and Draciel together.",
    categorySlugs: ["category-original-plastic-gen","category-original-tops","category-beyblade-original","category-spinning-tops"],
    categoryNames: ["Plastic Generation","Original Tops","Beyblade Original","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 899,
    currency: "INR",
    stockQuantity: 250,
    availableQuantity: 180,
    isSold: false,
    mainImage: seedPhoto("art-image-original-anniversary-1-20260819", 900, 900),
    images: [
      seedPhoto("art-image-original-anniversary-1-20260819", 900, 900),
      seedPhoto("art-image-original-anniversary-2-20260819", 900, 900),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "art" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "12x18 in", material: "Glossy photo paper", finish: "Glossy", editionSize: 250 },
    customFields: [{ key: "Anniversary Edition", type: "boolean", value: "true" }],
    customSections: [],
    featured: true,
    isPromoted: false,
    isOnSale: false,
    tags: ["fan-art", "vintage-collectible", "limited-run"],
    createdAt: new Date("2026-08-19"),
    updatedAt: new Date("2026-08-19"),
    searchTxt: buildSearchTxt([
      "Original Series 25th Anniversary — Glossy Art Print",
      "Commemorative glossy print marking 25 years of the original Beyblade series.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Original", "Spinning Tops"],
      ["fan-art", "vintage-collectible", "limited-run"],
    ]),
  } as unknown as Partial<ProductDocument>,
  {
    // Sold-out fixture. The canonical unavailable shape for a stock-only type:
    // isSold + both quantities zeroed, and status STILL published — an
    // archived row is hidden by the status filter before the availability
    // predicate ever runs, so it would prove nothing.
    id: "art-dragoon-galaxy-turbo-print-sold-out",
    slug: "art-dragoon-galaxy-turbo-print-sold-out",
    title: "Dragoon Galaxy Turbo — Fan Art Print (Sold Out)",
    description: "A sold-out run of the Dragoon Galaxy Turbo fan-art print. Every copy of this edition has shipped.",
    categorySlugs: ["category-original-hms","category-original-tops","category-beyblade-original","category-spinning-tops"],
    categoryNames: ["Heavy Metal System","Original Tops","Beyblade Original","Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 749,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    isSold: true,
    mainImage: seedPhoto("art-image-dragoon-galaxy-sold-out-1-20260824", 900, 900),
    images: [
      seedPhoto("art-image-dragoon-galaxy-sold-out-1-20260824", 900, 900),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "art" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "18x24 in", material: "Archival cotton rag", finish: "Matte", editionSize: 40 },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["fan-art", "poster", "sold-out"],
    createdAt: new Date("2026-08-24"),
    updatedAt: new Date("2026-08-24"),
    searchTxt: buildSearchTxt([
      "Dragoon Galaxy Turbo — Fan Art Print (Sold Out)",
      "A sold-out run of the Dragoon Galaxy Turbo fan-art print.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Original", "Spinning Tops"],
      ["fan-art", "poster", "sold-out"],
    ]),
  } as unknown as Partial<ProductDocument>,
];
