/**
 * Auctions Seed Data — Collectibles Edition
 * 6 auctions in all lifecycle states: active-ending-soon, active×2,
 * upcoming, ended (winner), ended (settled).
 * Stored as ProductDocument with isAuction: true.
 * id === slug convention enforced throughout.
 * Prices in INR paise (₹1 = 100 paise).
 */

import type { ProductDocument } from "../features/products/schemas";

const NOW = new Date();
const hoursAhead = (h: number) =>
  new Date(NOW.getTime() + h * 3_600_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const hoursAgo = (h: number) =>
  new Date(NOW.getTime() - h * 3_600_000);

const _rawProductsAuctionsSeedData: Partial<ProductDocument>[] = [
  // ── 1. ACTIVE — ending in 12h (Charizard Base Set #4 PSA 9) ───────────────
  {
    id: "auction-pokemon-charizard-base1-psa9",
    slug: "auction-pokemon-charizard-base1-psa9",
    title:
      "Pokémon Base Set 1st Edition Charizard #4 Holo — PSA 9 MINT (AUCTION)",
    description:
      "An absolutely pristine 1st Edition Base Set Charizard #4 graded PSA 9 MINT — one of the most iconic and sought-after Pokémon cards in existence. The 1st Edition stamp on the left of the artwork, shadow-less frame, and deep crimson fire breath in perfect registration. PSA 9 MINT has four sharp corners, bright lustre, no visible surface scratches, well-centered image. Certificate number visible on slab. This is auction lot 1 of 1 — once this card is gone, there is no re-stock. A generational collectible.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "The Pokémon Company",
    brandSlug: "brand-pokemon-company",
    isAuction: true,
    auctionEndDate: hoursAhead(12),
    startingBid: 9999900,
    currentBid: 29999900,
    bidCount: 6,
    reservePrice: 25000000,
    minBidIncrement: 500000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 9999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Pokémon Palace",
    storeId: "store-pokemon-palace",
    featured: true,
    isPromoted: true,
    tags: [
      "pokemon",
      "charizard",
      "base-set",
      "1st-edition",
      "psa-9",
      "graded",
      "vintage",
      "auction",
    ],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Charizard #4 Holo — Base Set 1st Edition" },
      { name: "Grade", value: "PSA 9 MINT" },
      { name: "Print", value: "1st Edition (stamped)" },
      { name: "Language", value: "English" },
      { name: "Year", value: "1999" },
      { name: "Reserve Price", value: "₹2,50,000" },
    ],
    features: [
      "PSA 9 MINT — 4 sharp corners, bright lustre",
      "1st Edition stamp — most valuable print run",
      "Certificate number confirmed — not a fake slab",
      "Reserve price set at ₹2,50,000",
      "Auto-extend: 5 minutes if bid in final 5 min",
    ],
    shippingInfo:
      "Winner-paid insured shipping via Blue Dart courier. Double-boxed with foam, PSA slab protector, and tamper-evident seal.",
    returnPolicy:
      "No returns on auction lots. Verified photos and PSA certificate provided before shipping. Any dispute about card grade handled via PSA directly.",
    insurance: true,
    insuranceCost: 100000,
    createdAt: daysAgo(14),
    updatedAt: hoursAgo(2),
  },

  // ── 2. ACTIVE — ending in 48h (Exodia 1st Edition LOB PSA 8) ──────────────
  {
    id: "auction-yugioh-lob1-exodia-1st-psa8",
    slug: "auction-yugioh-lob1-exodia-1st-psa8",
    title:
      "Yu-Gi-Oh! Exodia the Forbidden One — LOB-000 1st Edition PSA 8 NM-MT (AUCTION)",
    description:
      "Ultra-rare 1st Edition Exodia the Forbidden One from the original Legend of Blue Eyes White Dragon set (LOB-000), graded PSA 8 Near Mint to Mint. Exodia is one of the most iconic and mythological cards in all of Yu-Gi-Oh — the card that ends the game instantly when all five Exodia pieces are assembled. This 1st Edition LOB-000 printing is the most desirable version, identifiable by the 1st Edition stamp in the lower left of the card frame. PSA 8 NM-MT: four nearly perfect corners, excellent surface, minimal wear. A tournament legend in slab form.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "Konami",
    brandSlug: "brand-konami",
    isAuction: true,
    auctionEndDate: hoursAhead(48),
    startingBid: 1499900,
    currentBid: 4999900,
    bidCount: 5,
    reservePrice: 4000000,
    minBidIncrement: 250000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 1499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "CardGame Hub",
    storeId: "store-cardgame-hub",
    featured: true,
    isPromoted: false,
    tags: [
      "yugioh",
      "exodia",
      "lob",
      "1st-edition",
      "psa-8",
      "graded",
      "vintage",
      "auction",
    ],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Exodia the Forbidden One — LOB-000" },
      { name: "Grade", value: "PSA 8 NM-MT" },
      { name: "Print", value: "1st Edition" },
      { name: "Language", value: "English" },
      { name: "Year", value: "2002" },
      { name: "Reserve Price", value: "₹40,000" },
    ],
    features: [
      "PSA 8 NM-MT — nearly perfect condition",
      "1st Edition LOB-000 — rarest print",
      "Exodia — most legendary card in the game",
      "Reserve met — guaranteed to sell",
      "WCS 2022 qualifier-sourced — tournament provenance",
    ],
    shippingInfo:
      "Winner-paid insured shipping. PSA slab shipped in foam-lined rigid mailer via Blue Dart.",
    returnPolicy:
      "No returns on auction lots. Slab photos provided before shipping.",
    insurance: true,
    insuranceCost: 20000,
    createdAt: daysAgo(7),
    updatedAt: hoursAgo(6),
  },

  // ── 3. ACTIVE — ending in 6h (Hot Wheels Redline Pink Camaro 1967) ─────────
  {
    id: "auction-hot-wheels-redline-camaro-pink",
    slug: "auction-hot-wheels-redline-camaro-pink",
    title:
      "Hot Wheels Redline 1967 Custom Camaro — Spectraflame Pink (Vintage, AUCTION)",
    description:
      "Extremely rare 1967 Hot Wheels Redline Custom Camaro in Spectraflame Pink — one of the most sought-after Redline colourways among serious diecast collectors. The Spectraflame Pink finish has a characteristic metallic candy-pink lustre that was only produced for a very limited run. This example is in Very Good (VG) condition: strong pink spectraflame with minor surface abrasion on the hood, red-line tyres intact, all four wheels spin freely. Sourced from a Japan Redline collector who acquired it at a 1980s Tokyo toy show. No repaints, no replaced parts. Accompanied by a collector's provenance letter.",
    category: "category-hot-wheels",
    categoryName: "Hot Wheels",
    brand: "Hot Wheels",
    brandSlug: "brand-hot-wheels",
    isAuction: true,
    auctionEndDate: hoursAhead(6),
    startingBid: 499900,
    currentBid: 1299900,
    bidCount: 4,
    reservePrice: 1000000,
    minBidIncrement: 100000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Diecast Depot",
    storeId: "store-diecast-depot",
    featured: false,
    isPromoted: true,
    tags: [
      "hot-wheels",
      "redline",
      "1967",
      "camaro",
      "pink",
      "spectraflame",
      "vintage",
      "rare",
      "auction",
    ],
    condition: "used",
    specifications: [
      { name: "Year", value: "1967" },
      { name: "Scale", value: "1:64" },
      { name: "Colour", value: "Spectraflame Pink" },
      { name: "Wheels", value: "Redline" },
      { name: "Condition Grade", value: "Very Good (VG)" },
      { name: "Reserve Price", value: "₹10,000" },
    ],
    features: [
      "Spectraflame Pink — rarest Camaro Redline colourway",
      "Japan collector provenance — Tokyo toy show 1980s",
      "Original — no repaints, no replaced parts",
      "Collector's provenance letter included",
      "Reserve met — guaranteed to sell",
    ],
    shippingInfo:
      "Winner-paid insured shipping. Bubble-wrapped in rigid foam-lined mailer.",
    returnPolicy:
      "No returns on auction lots. Detailed photos taken before shipping for reference.",
    insurance: true,
    insuranceCost: 5000,
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(1),
  },

  // ── 4. UPCOMING — starts in 72h (Beyblade Metal Fusion BB-10 Signed) ───────
  {
    id: "auction-beyblade-metal-fusion-signed",
    slug: "auction-beyblade-metal-fusion-signed",
    title:
      "Beyblade Metal Fusion BB-10 Storm Pegasus — Factory Sealed + Signed by Voice Actor (UPCOMING AUCTION)",
    description:
      "Extraordinary lot: a factory-sealed Beyblade Metal Fusion BB-10 Storm Pegasus Starter Set, signed on the outer box by the Japanese voice actor for Ginga Hagane (Kei Shindo), with certificate of authenticity. BB-10 Storm Pegasus is the iconic starting Beyblade for the Metal Fusion series, and factory-sealed examples are increasingly rare as most were opened immediately. The signature was obtained at WonFes 2019 and is accompanied by a photograph of the signing session. Opening bid at ₹2,999 — no reserve. This auction starts in 72 hours.",
    category: "category-beyblade-classic",
    categoryName: "Metal Fight Classic",
    brand: "Beyblade",
    brandSlug: "brand-beyblade",
    isAuction: true,
    auctionEndDate: daysAhead(7),
    startingBid: 299900,
    currentBid: 0,
    bidCount: 0,
    reservePrice: 0,
    minBidIncrement: 50000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 299900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Beyblade Arena",
    storeId: "store-beyblade-arena",
    featured: false,
    isPromoted: false,
    tags: [
      "beyblade",
      "metal-fusion",
      "bb-10",
      "storm-pegasus",
      "signed",
      "factory-sealed",
      "vintage",
      "upcoming-auction",
    ],
    condition: "new",
    specifications: [
      { name: "Product", value: "BB-10 Storm Pegasus Starter Set" },
      { name: "Generation", value: "Metal Fusion (2008)" },
      { name: "Condition", value: "Factory sealed" },
      { name: "Signature", value: "Kei Shindo (Japanese VA — Ginga Hagane)" },
      { name: "Event", value: "Wonder Festival 2019" },
      { name: "Reserve", value: "No reserve — sells at any price" },
    ],
    features: [
      "Factory-sealed BB-10 — rare to find sealed",
      "Signed by Japanese voice actor at WonFes 2019",
      "Certificate of authenticity + signing photo",
      "No reserve — auction opens to all bids",
      "Auction starts in 72 hours — set a reminder",
    ],
    shippingInfo:
      "Winner-paid insured shipping. Foam-lined rigid mailer, tamper-evident seal.",
    returnPolicy:
      "No returns on auction lots. All details disclosed upfront — no hidden flaws.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },

  // ── 5. ENDED — 7 days ago, winner declared (Gundam PG Strike Freedom) ──────
  {
    id: "auction-gundam-pg-strike-freedom-box",
    slug: "auction-gundam-pg-strike-freedom-box",
    title:
      "Bandai Gunpla PG 1/60 Strike Freedom Gundam — Factory Sealed (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — This auction has ended. Final winning bid: ₹29,999. A factory-sealed Bandai Perfect Grade 1/60 Strike Freedom Gundam — Bandai's magnum opus kit, widely regarded as the most complex and visually stunning Gunpla ever produced. The PG 1/60 stands 37 cm tall assembled, features 500+ parts, full LED lighting system runner (sold separately), internal frame with gold-plated parts, wing of light effect set, and METEOR unit attachment. The winner has been notified and shipment is being arranged.",
    category: "category-gunpla",
    categoryName: "Gunpla",
    brand: "Bandai",
    brandSlug: "brand-bandai",
    isAuction: true,
    auctionEndDate: daysAgo(7),
    startingBid: 999900,
    currentBid: 2999900,
    bidCount: 6,
    reservePrice: 2500000,
    minBidIncrement: 250000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 999900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1657664072470-99b02c2143f2?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1657664072470-99b02c2143f2?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=800&h=800&fit=crop",
    ],
    status: "sold",
    storeName: "LetItRip Official",
    storeId: "store-letitrip-official",
    featured: false,
    isPromoted: false,
    tags: [
      "gunpla",
      "perfect-grade",
      "strike-freedom",
      "bandai",
      "factory-sealed",
      "auction",
      "ended",
    ],
    condition: "new",
    specifications: [
      { name: "Grade", value: "Perfect Grade (PG)" },
      { name: "Scale", value: "1/60" },
      { name: "Height assembled", value: "~37 cm", unit: "cm" },
      { name: "Parts", value: "500+" },
      { name: "Final Bid", value: "₹29,999" },
      { name: "Status", value: "Auction ended — winner notified" },
    ],
    features: [
      "PG 1/60 Strike Freedom — most complex PG ever",
      "500+ parts — internal gold frame",
      "Wing of Light effect set included",
      "METEOR unit attachment",
      "Factory sealed — auction now closed",
    ],
    shippingInfo: "Shipping arranged with winner. Auction closed.",
    returnPolicy: "Auction ended. No returns.",
    createdAt: daysAgo(21),
    updatedAt: daysAgo(7),
  },

  // ── 7. ACTIVE — ending in 24h (Pokémon Mew 1st Edition PSA 10) ──────────────
  {
    id: "auction-pokemon-mew-1st-edition-psa10",
    slug: "auction-pokemon-mew-1st-edition-psa10",
    title:
      "Pokémon Base Set 1st Edition Mew Promo #8 — PSA 10 GEM MINT (AUCTION)",
    description:
      "A PSA 10 GEM MINT 1st Edition Mew Promo card (#8, Ancient Mew alt art) — one of the rarest PSA 10s in existence due to the delicate nature of the foil stock used in this promo. The Ancient Mew promotional card was distributed with Pokémon: The Movie 2000 tickets in Japan and the US. This copy has four perfect corners, flawless surface, and perfect centering under the PSA slab. PSA population report shows fewer than 50 PSA 10s of this card exist globally. Opening bid ₹99,999. Reserve met.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "The Pokémon Company",
    brandSlug: "brand-pokemon-company",
    isAuction: true,
    auctionEndDate: hoursAhead(24),
    startingBid: 9999900,
    currentBid: 14999900,
    bidCount: 3,
    reservePrice: 12000000,
    minBidIncrement: 500000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 9999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Pokémon Palace",
    storeId: "store-pokemon-palace",
    featured: false,
    isPromoted: false,
    tags: ["pokemon", "mew", "1st-edition", "psa-10", "graded", "promo", "vintage", "auction"],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Ancient Mew Promo #8" },
      { name: "Grade", value: "PSA 10 GEM MINT" },
      { name: "Print", value: "1st Edition Promo" },
      { name: "PSA Pop", value: "<50 PSA 10s worldwide" },
      { name: "Reserve Price", value: "₹1,20,000 — MET" },
    ],
    features: [
      "PSA 10 GEM MINT — rarest promo grade",
      "Ancient Mew Movie 2000 promo — iconic",
      "Sub-50 PSA 10 population globally",
      "Reserve met — guaranteed to sell",
      "Auto-extend: 5 minutes on last-minute bids",
    ],
    shippingInfo: "Winner-paid insured Blue Dart courier. PSA slab double-boxed with foam.",
    returnPolicy: "No returns on auction lots. All details and PSA cert photos provided before shipping.",
    insurance: true,
    insuranceCost: 50000,
    createdAt: daysAgo(10),
    updatedAt: hoursAgo(3),
  },

  // ── 8. ACTIVE — ending in 72h (Blue Eyes White Dragon LOB 1st PSA 9) ───────
  {
    id: "auction-yugioh-blue-eyes-lob-1st-psa9",
    slug: "auction-yugioh-blue-eyes-lob-1st-psa9",
    title:
      "Yu-Gi-Oh! Blue-Eyes White Dragon — LOB-001 1st Edition PSA 9 MINT (AUCTION)",
    description:
      "The most iconic card in Yu-Gi-Oh! — Blue-Eyes White Dragon (LOB-001) in 1st Edition, graded PSA 9 MINT. This is the first-print 1st Edition Blue-Eyes from the original Legend of Blue Eyes White Dragon set, identifiable by the 1st Edition stamp and the original Konami of America watermark text. PSA 9 MINT: four near-perfect corners, excellent surface, no visible scratches, well-centred. The Blue-Eyes 1st Edition LOB is a cornerstone of any serious Yu-Gi-Oh! investment collection and has shown consistent appreciation over 20 years.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "Konami",
    brandSlug: "brand-konami",
    isAuction: true,
    auctionEndDate: hoursAhead(72),
    startingBid: 2999900,
    currentBid: 7999900,
    bidCount: 8,
    reservePrice: 6000000,
    minBidIncrement: 250000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 2999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "CardGame Hub",
    storeId: "store-cardgame-hub",
    featured: true,
    isPromoted: false,
    tags: ["yugioh", "blue-eyes-white-dragon", "lob-001", "1st-edition", "psa-9", "graded", "vintage", "auction"],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Blue-Eyes White Dragon — LOB-001" },
      { name: "Grade", value: "PSA 9 MINT" },
      { name: "Print", value: "1st Edition" },
      { name: "Year", value: "2002" },
      { name: "Reserve Price", value: "₹60,000 — MET" },
    ],
    features: [
      "The most iconic Yu-Gi-Oh! card — LOB Blue-Eyes",
      "PSA 9 MINT — excellent corners and surface",
      "1st Edition stamp — most desirable print",
      "Reserve met — guaranteed to sell",
      "20-year appreciation track record",
    ],
    shippingInfo: "Winner-paid insured shipping. PSA slab in foam-lined rigid mailer via Blue Dart.",
    returnPolicy: "No returns on auction lots. Slab photos and cert number provided before shipping.",
    insurance: true,
    insuranceCost: 30000,
    createdAt: daysAgo(8),
    updatedAt: hoursAgo(5),
  },

  // ── 9. ACTIVE — ending in 36h (Hot Wheels Redline Deora 1968 Japan-sourced) ─
  {
    id: "auction-hot-wheels-redline-deora-japan",
    slug: "auction-hot-wheels-redline-deora-japan",
    title:
      "Hot Wheels Redline 1968 Deora — Spectraflame Copper (Japan-sourced, VG+, AUCTION)",
    description:
      "1968 Hot Wheels Redline Deora in the rare Spectraflame Copper finish — sourced from a Japanese Redline collector through the Tokyo Toy Show. Copper Deoras are considerably rarer than the standard aqua version, with fewer units produced and an extremely high attrition rate due to the delicate copper Spectraflame. This example is in Very Good Plus (VG+) condition: copper paint at approximately 90% vibrancy, both surfboards present, red-line tyres intact, all four wheels spin. One minor nick on the passenger door — visible in photos. Accompanied by a provenance letter from the Japanese collector.",
    category: "category-hot-wheels",
    categoryName: "Hot Wheels",
    brand: "Hot Wheels",
    brandSlug: "brand-hot-wheels",
    isAuction: true,
    auctionEndDate: hoursAhead(36),
    startingBid: 899900,
    currentBid: 1799900,
    bidCount: 5,
    reservePrice: 1500000,
    minBidIncrement: 100000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 899900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Diecast Depot",
    storeId: "store-diecast-depot",
    featured: false,
    isPromoted: true,
    tags: ["hot-wheels", "redline", "1968", "deora", "copper", "spectraflame", "vintage", "rare", "auction"],
    condition: "used",
    specifications: [
      { name: "Year", value: "1968" },
      { name: "Scale", value: "1:64" },
      { name: "Colour", value: "Spectraflame Copper" },
      { name: "Condition Grade", value: "Very Good Plus (VG+)" },
      { name: "Surfboards", value: "Both present" },
      { name: "Reserve Price", value: "₹15,000 — MET" },
    ],
    features: [
      "1968 Copper Deora — rarer than aqua version",
      "Both surfboards present — complete",
      "Japan collector provenance + letter",
      "Reserve met — guaranteed to sell",
      "All four wheels spin freely",
    ],
    shippingInfo: "Winner-paid insured shipping. Bubble-wrapped in rigid foam-lined mailer.",
    returnPolicy: "No returns on auction lots. Detailed photos available before bid confirmation.",
    insurance: true,
    insuranceCost: 8000,
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(2),
  },

  // ── 10. UPCOMING — starts in 5 days (Gundam PG Astray Red Frame) ──────────
  {
    id: "auction-gundam-pg-astray-red-frame",
    slug: "auction-gundam-pg-astray-red-frame",
    title:
      "Bandai Gunpla PG 1/60 Astray Red Frame — Factory Sealed (UPCOMING AUCTION, 5 Days)",
    description:
      "Upcoming auction for a factory-sealed Bandai Perfect Grade 1/60 MBF-P02 Gundam Astray Red Frame — one of the most visually striking PG kits ever made, featuring the iconic Gerbera Straight katana, red colour scheme, and articulated flight pack. The PG Astray stands 30cm assembled with 300+ parts including a complex inner frame. Factory sealed in original shrink wrap — never opened. Opens to bidding in 5 days. No reserve on this lot — opening bid ₹9,999.",
    category: "category-gunpla",
    categoryName: "Gunpla",
    brand: "Bandai",
    brandSlug: "brand-bandai",
    isAuction: true,
    auctionEndDate: daysAhead(12),
    startingBid: 999900,
    currentBid: 0,
    bidCount: 0,
    reservePrice: 0,
    minBidIncrement: 100000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1657664072470-99b02c2143f2?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1657664072470-99b02c2143f2?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Gundam Galaxy",
    storeId: "store-gundam-galaxy",
    featured: false,
    isPromoted: false,
    tags: ["gunpla", "perfect-grade", "pg", "astray-red-frame", "bandai", "factory-sealed", "upcoming-auction"],
    condition: "new",
    specifications: [
      { name: "Grade", value: "Perfect Grade (PG)" },
      { name: "Scale", value: "1/60" },
      { name: "Height assembled", value: "~30 cm", unit: "cm" },
      { name: "Parts", value: "300+" },
      { name: "Reserve", value: "No reserve — sells at any price" },
    ],
    features: [
      "PG Astray Red Frame — iconic katana kit",
      "Factory sealed — never opened",
      "Gerbera Straight katana and flight pack",
      "No reserve — opens to all bids",
      "Auction opens in 5 days",
    ],
    shippingInfo: "Winner-paid insured shipping. Double-boxed with foam corner protection.",
    returnPolicy: "No returns on auction lots.",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },

  // ── 11. ACTIVE — ending in 4h (Nendoroid Miku #100 Limited — rare) ────────
  {
    id: "auction-nendoroid-miku-100-limited",
    slug: "auction-nendoroid-miku-100-limited",
    title:
      "Good Smile Company Nendoroid Hatsune Miku #100 (Original Release, Rare) — AUCTION",
    description:
      "The original 2009 Good Smile Company Nendoroid Hatsune Miku #100 — the first Miku Nendoroid ever produced and the figure that launched the Nendoroid line into global fame. This is an original 2009 first-release box, not a re-release. Identifiable by the original box artwork (pre-2.0 box design) and the 2009 copyright date on the base. Condition: box is Very Good (minor shelf wear), figure is Near Mint — all accessories present including 3 faces, stand, and original inner tray. An absolute piece of Nendoroid history.",
    category: "category-nendoroids-chibis",
    categoryName: "Nendoroids & Chibis",
    brand: "Good Smile Company",
    brandSlug: "brand-good-smile",
    isAuction: true,
    auctionEndDate: hoursAhead(4),
    startingBid: 499900,
    currentBid: 1199900,
    bidCount: 7,
    reservePrice: 800000,
    minBidIncrement: 50000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Tokyo Toys India",
    storeId: "store-tokyo-toys-india",
    featured: false,
    isPromoted: true,
    tags: ["nendoroid", "hatsune-miku", "#100", "original-2009", "rare", "good-smile", "vocaloid", "auction"],
    condition: "used",
    specifications: [
      { name: "Nendoroid Number", value: "#100" },
      { name: "Character", value: "Hatsune Miku" },
      { name: "Release Year", value: "2009 (original, not re-release)" },
      { name: "Box", value: "Original box — Very Good (shelf wear)" },
      { name: "Figure Condition", value: "Near Mint — all accessories present" },
    ],
    features: [
      "Original 2009 first-release — not a re-release",
      "Nendoroid #100 — launched the Nendoroid franchise",
      "All original accessories and inner tray present",
      "Reserve met — guaranteed to sell",
      "Ending in 4 hours — bid now",
    ],
    shippingInfo: "Winner-paid insured shipping. Individually bubble-wrapped in rigid foam-lined box.",
    returnPolicy: "No returns on auction lots. Detailed photos and unboxing video available on request.",
    insurance: true,
    insuranceCost: 5000,
    createdAt: daysAgo(9),
    updatedAt: hoursAgo(1),
  },

  // ── 6. ENDED — 30 days ago (Bandai DBZ Bulma Vintage) ─────────────────────
  {
    id: "auction-bandai-dbz-bulma-vintage",
    slug: "auction-bandai-dbz-bulma-vintage",
    title:
      "Bandai Dragon Ball Z Bulma Vintage Figure — 1989 First-Run (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — This auction has ended. Final winning bid: ₹7,999. A rare 1989 first-run Bandai Dragon Ball Z Bulma figure from the original Bandai Japanese toy line, released to coincide with the DBZ anime broadcast. This early figure has the original Bandai stamp on the base, painted hair and face details accurate to the original 1989 anime character sheet, and all original accessories. Condition is Good (G) — honest display wear, original paint throughout, no missing parts. Sourced from a Tokyo toy collector through the 2024 Japan trip.",
    category: "category-vintage-figures",
    categoryName: "Vintage Figures",
    brand: "Bandai",
    brandSlug: "brand-bandai",
    isAuction: true,
    auctionEndDate: daysAgo(30),
    startingBid: 299900,
    currentBid: 799900,
    bidCount: 5,
    reservePrice: 0,
    minBidIncrement: 50000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 299900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1560762484-813fc97650a0?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
    ],
    status: "sold",
    storeName: "Diecast Depot",
    storeId: "store-diecast-depot",
    featured: false,
    isPromoted: false,
    tags: [
      "bandai",
      "dragon-ball-z",
      "dbz",
      "bulma",
      "1989",
      "vintage",
      "figure",
      "auction",
      "ended",
    ],
    condition: "used",
    specifications: [
      { name: "Character", value: "Bulma" },
      { name: "Series", value: "Dragon Ball Z" },
      { name: "Year", value: "1989 (first-run)" },
      { name: "Manufacturer", value: "Bandai Japan" },
      { name: "Condition Grade", value: "Good (G) — original paint" },
      { name: "Final Bid", value: "₹7,999" },
    ],
    features: [
      "1989 first-run Bandai DBZ figure",
      "Original Bandai Japan stamp on base",
      "All original accessories — no missing parts",
      "Tokyo collector provenance (2024 Japan trip)",
      "Auction closed — 30 days ago",
    ],
    shippingInfo: "Shipped to winner. Auction completed and settled.",
    returnPolicy: "Auction ended. No returns.",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(30),
  },

  // ── 12. ACTIVE — ending in 60h (Pokémon Lugia Neo Genesis Holo PSA 9) ─────
  {
    id: "auction-pokemon-lugia-neo-genesis-psa9",
    slug: "auction-pokemon-lugia-neo-genesis-psa9",
    title:
      "Pokémon Neo Genesis Lugia #9 Holo — PSA 9 MINT (AUCTION)",
    description:
      "Neo Genesis Lugia #9 Holo graded PSA 9 MINT — one of the most desirable Neo-era chase cards. Sharp corners, deep blue holo with full mirror, well-centred image. Neo Genesis was the first major post-Base set, and PSA 9 Lugias have a strong appreciation track record. Reserve set at ₹65,000. Authentication confirmed via PSA cert lookup.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "The Pokémon Company",
    brandSlug: "brand-pokemon-company",
    isAuction: true,
    auctionEndDate: hoursAhead(60),
    startingBid: 3499900,
    currentBid: 6999900,
    bidCount: 7,
    reservePrice: 6500000,
    minBidIncrement: 250000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 3499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Pokémon Palace",
    storeId: "store-pokemon-palace",
    featured: false,
    isPromoted: false,
    tags: ["pokemon", "lugia", "neo-genesis", "psa-9", "graded", "vintage", "auction"],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Lugia #9 Holo — Neo Genesis" },
      { name: "Grade", value: "PSA 9 MINT" },
      { name: "Year", value: "2000" },
      { name: "Reserve Price", value: "₹65,000 — MET" },
    ],
    features: [
      "PSA 9 MINT — Neo Genesis chase card",
      "Reserve met — guaranteed to sell",
      "PSA cert verified",
      "Auto-extend on last-minute bids",
    ],
    shippingInfo: "Winner-paid insured Blue Dart courier. PSA slab double-boxed.",
    returnPolicy: "No returns on auction lots.",
    insurance: true,
    insuranceCost: 25000,
    createdAt: daysAgo(9),
    updatedAt: hoursAgo(4),
  },

  // ── 13. ACTIVE — ending in 96h (Funko Pop Glow Chase Stan Lee) ────────────
  {
    id: "auction-funko-stan-lee-glow-chase",
    slug: "auction-funko-stan-lee-glow-chase",
    title:
      "Funko Pop Stan Lee Glow-in-the-Dark Chase Variant — Vaulted (AUCTION)",
    description:
      "Vaulted Funko Pop Stan Lee Glow-in-the-Dark Chase variant — the 1-in-6 chase exclusive that has appreciated significantly since Marvel's vaulting. Box near-mint with light shelf wear on one corner. Figure mint inside protector. Highly collectible Marvel-themed piece for Funko Pop chase hunters.",
    category: "category-funko-pops",
    categoryName: "Funko Pops",
    brand: "Funko",
    brandSlug: "brand-funko",
    isAuction: true,
    auctionEndDate: hoursAhead(96),
    startingBid: 599900,
    currentBid: 1099900,
    bidCount: 4,
    reservePrice: 900000,
    minBidIncrement: 50000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 599900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1608889825271-9696283b84bd?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Tokyo Toys India",
    storeId: "store-tokyo-toys-india",
    featured: false,
    isPromoted: false,
    tags: ["funko", "stan-lee", "glow-chase", "vaulted", "marvel", "auction"],
    condition: "new",
    specifications: [
      { name: "Variant", value: "Glow-in-the-Dark Chase (1-in-6)" },
      { name: "Status", value: "Vaulted" },
      { name: "Box Condition", value: "Near Mint" },
      { name: "Reserve Price", value: "₹9,000 — MET" },
    ],
    features: [
      "Glow Chase variant — 1-in-6 pull rate",
      "Vaulted by Funko — no re-issue",
      "Box NM, figure mint inside protector",
      "Reserve met — guaranteed to sell",
    ],
    shippingInfo: "Winner-paid insured shipping. Pop protector included.",
    returnPolicy: "No returns on auction lots.",
    insurance: true,
    insuranceCost: 5000,
    createdAt: daysAgo(7),
    updatedAt: hoursAgo(8),
  },

  // ── 14. ACTIVE — ending in 5d (Beyblade Burst Spriggan Requiem Limited) ────
  {
    id: "auction-beyblade-spriggan-requiem-tournament",
    slug: "auction-beyblade-spriggan-requiem-tournament",
    title:
      "Beyblade Burst B-100 Spriggan Requiem — Tournament Limited Edition (AUCTION)",
    description:
      "B-100 Spriggan Requiem Tournament Limited Edition — a prize-only release given to top finishers at the 2018 Japan National Tournament. Black recolour with gold accents and engraved serial number. Includes original tournament pouch. One of fewer than 500 produced. Mint condition.",
    category: "category-beyblade-burst",
    categoryName: "Beyblade Burst",
    brand: "Beyblade",
    brandSlug: "brand-beyblade",
    isAuction: true,
    auctionEndDate: daysAhead(5),
    startingBid: 399900,
    currentBid: 899900,
    bidCount: 6,
    reservePrice: 700000,
    minBidIncrement: 50000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 399900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Beyblade Arena",
    storeId: "store-beyblade-arena",
    featured: true,
    isPromoted: false,
    tags: ["beyblade", "burst", "spriggan-requiem", "tournament", "limited", "auction"],
    condition: "new",
    specifications: [
      { name: "Product", value: "B-100 Spriggan Requiem Tournament" },
      { name: "Edition", value: "Tournament Limited (<500 made)" },
      { name: "Year", value: "2018 Japan Nationals" },
      { name: "Reserve Price", value: "₹7,000 — MET" },
    ],
    features: [
      "Tournament prize edition — sub-500 made",
      "Engraved serial number",
      "Original tournament pouch included",
      "Reserve met — guaranteed to sell",
    ],
    shippingInfo: "Winner-paid insured shipping. Foam-lined rigid mailer.",
    returnPolicy: "No returns on auction lots.",
    insurance: true,
    insuranceCost: 3000,
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(12),
  },

  // ── 15. UPCOMING — starts in 4d (Pokémon Trophy Card Pikachu World) ───────
  {
    id: "auction-pokemon-trophy-pikachu-world",
    slug: "auction-pokemon-trophy-pikachu-world",
    title:
      "Pokémon Trophy Pikachu World Championships 2006 Promo (UPCOMING AUCTION)",
    description:
      "Authenticated Trophy Pikachu from the 2006 World Championships staff-only distribution — one of the rarest modern Pokémon promos. Card-only sale, no slab. Provenance: ex-WCS judge. Auction opens in 4 days. Opening bid ₹4,99,999. No reserve.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "The Pokémon Company",
    brandSlug: "brand-pokemon-company",
    isAuction: true,
    auctionEndDate: daysAhead(11),
    startingBid: 49999900,
    currentBid: 0,
    bidCount: 0,
    reservePrice: 0,
    minBidIncrement: 1000000,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionShippingPaidBy: "winner",
    price: 49999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Pokémon Palace",
    storeId: "store-pokemon-palace",
    featured: true,
    isPromoted: true,
    tags: ["pokemon", "trophy-pikachu", "worlds-2006", "promo", "ultra-rare", "upcoming-auction"],
    condition: "used",
    specifications: [
      { name: "Card", value: "Trophy Pikachu (Worlds 2006 Staff Promo)" },
      { name: "Provenance", value: "Ex-WCS judge" },
      { name: "Reserve", value: "No reserve" },
    ],
    features: [
      "Worlds 2006 Trophy Pikachu — staff-only distribution",
      "Provenance: ex-WCS judge",
      "Opens in 4 days — set reminder",
      "No reserve — sells at any price",
    ],
    shippingInfo: "Winner-paid insured Blue Dart. Toploader + rigid mailer.",
    returnPolicy: "No returns on auction lots.",
    insurance: true,
    insuranceCost: 150000,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(20),
  },

  // ── 16. UPCOMING — starts in 10d (Hot Wheels Treasure Hunt Set) ───────────
  {
    id: "auction-hot-wheels-th-set-2024",
    slug: "auction-hot-wheels-th-set-2024",
    title:
      "Hot Wheels 2024 Super Treasure Hunt Full Set — All 15 Cars (UPCOMING AUCTION)",
    description:
      "Complete 2024 Hot Wheels Super Treasure Hunt full series — all 15 cars assembled over the year via case-breaks. Each in original blister. A complete-year STH set is a rare find. Auction opens in 10 days. No reserve.",
    category: "category-hot-wheels",
    categoryName: "Hot Wheels",
    brand: "Hot Wheels",
    brandSlug: "brand-hot-wheels",
    isAuction: true,
    auctionEndDate: daysAhead(17),
    startingBid: 1499900,
    currentBid: 0,
    bidCount: 0,
    reservePrice: 0,
    minBidIncrement: 100000,
    autoExtendable: true,
    auctionExtensionMinutes: 5,
    auctionShippingPaidBy: "winner",
    price: 1499900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=800&fit=crop",
    ],
    status: "published",
    storeName: "Diecast Depot",
    storeId: "store-diecast-depot",
    featured: false,
    isPromoted: false,
    tags: ["hot-wheels", "super-treasure-hunt", "2024", "full-set", "upcoming-auction"],
    condition: "new",
    specifications: [
      { name: "Year", value: "2024" },
      { name: "Cars", value: "All 15 STH" },
      { name: "Packaging", value: "Original blister, all sealed" },
      { name: "Reserve", value: "No reserve" },
    ],
    features: [
      "Complete 2024 STH set — all 15 cars",
      "Each in sealed original blister",
      "No reserve — sells at any price",
      "Opens in 10 days",
    ],
    shippingInfo: "Winner-paid insured shipping. Each car bubble-wrapped.",
    returnPolicy: "No returns on auction lots.",
    insurance: true,
    insuranceCost: 10000,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(18),
  },

  // ── 17. ENDED (winner declared) — 3 days ago (S.H.Figuarts Goku UI) ───────
  {
    id: "auction-shf-goku-ultra-instinct",
    slug: "auction-shf-goku-ultra-instinct",
    title:
      "S.H.Figuarts Son Goku Ultra Instinct — Tamashii Limited (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — Final winning bid ₹14,999. S.H.Figuarts Goku Ultra Instinct Tamashii Web Exclusive — sealed in original packaging. Winner declared, shipment in progress.",
    category: "category-anime-figures",
    categoryName: "Anime Figures",
    brand: "Bandai",
    brandSlug: "brand-bandai",
    isAuction: true,
    auctionEndDate: daysAgo(3),
    startingBid: 599900,
    currentBid: 1499900,
    bidCount: 6,
    reservePrice: 1200000,
    minBidIncrement: 50000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 599900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&h=800&fit=crop",
    ],
    status: "sold",
    storeName: "Tokyo Toys India",
    storeId: "store-tokyo-toys-india",
    featured: false,
    isPromoted: false,
    tags: ["shfiguarts", "goku", "ultra-instinct", "dbz", "auction", "ended"],
    condition: "new",
    specifications: [
      { name: "Line", value: "S.H.Figuarts" },
      { name: "Character", value: "Goku Ultra Instinct" },
      { name: "Status", value: "Sold — winner notified" },
      { name: "Final Bid", value: "₹14,999" },
    ],
    features: [
      "Tamashii Web Exclusive — limited release",
      "Sealed in original packaging",
      "Reserve met — auction settled",
    ],
    shippingInfo: "Shipping arranged with winner.",
    returnPolicy: "Auction ended.",
    createdAt: daysAgo(17),
    updatedAt: daysAgo(3),
  },

  // ── 18. ENDED (winner declared) — 14 days ago (Pokémon Blastoise Holo) ────
  {
    id: "auction-pokemon-blastoise-shadowless-bgs",
    slug: "auction-pokemon-blastoise-shadowless-bgs",
    title:
      "Pokémon Base Set Shadowless Blastoise #2 Holo — BGS 8.5 (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — Final bid ₹39,999. Shadowless Base Set Blastoise graded BGS 8.5. Winner notified, slab dispatched.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "The Pokémon Company",
    brandSlug: "brand-pokemon-company",
    isAuction: true,
    auctionEndDate: daysAgo(14),
    startingBid: 1499900,
    currentBid: 3999900,
    bidCount: 8,
    reservePrice: 3500000,
    minBidIncrement: 250000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 1499900,
    currency: "INR",
    stockQuantity: 0,
    availableQuantity: 0,
    mainImage:
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=800&fit=crop",
    ],
    status: "sold",
    storeName: "Pokémon Palace",
    storeId: "store-pokemon-palace",
    featured: false,
    isPromoted: false,
    tags: ["pokemon", "blastoise", "shadowless", "bgs-8-5", "vintage", "auction", "ended"],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Blastoise #2 Holo — Shadowless" },
      { name: "Grade", value: "BGS 8.5" },
      { name: "Year", value: "1999" },
      { name: "Final Bid", value: "₹39,999" },
    ],
    features: [
      "Shadowless print — rarer than unlimited",
      "BGS 8.5 — strong subgrades",
      "Auction settled — slab shipped",
    ],
    shippingInfo: "Shipped to winner.",
    returnPolicy: "Auction ended.",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(14),
  },

  // ── 19. ENDED (no winner — reserve not met) — 10 days ago ────────────────
  {
    id: "auction-vintage-tomica-skyline-no-reserve-fail",
    slug: "auction-vintage-tomica-skyline-no-reserve-fail",
    title:
      "Vintage Tomica Nissan Skyline GT-R Hakosuka 1973 — Reserve Not Met (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — Reserve not met. Highest bid ₹4,999 fell short of the ₹8,000 reserve. Listing kept for record. Item remains with seller and may be relisted.",
    category: "category-tomica-premium",
    categoryName: "Tomica",
    brand: "Takara Tomy",
    brandSlug: "brand-takara-tomy",
    isAuction: true,
    auctionEndDate: daysAgo(10),
    startingBid: 199900,
    currentBid: 499900,
    bidCount: 3,
    reservePrice: 800000,
    minBidIncrement: 50000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 199900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&h=800&fit=crop",
    ],
    status: "draft",
    storeName: "Diecast Depot",
    storeId: "store-diecast-depot",
    featured: false,
    isPromoted: false,
    tags: ["tomica", "skyline", "hakosuka", "vintage", "auction", "ended", "no-winner"],
    condition: "used",
    specifications: [
      { name: "Year", value: "1973" },
      { name: "Reserve Price", value: "₹8,000 (NOT MET)" },
      { name: "Final High Bid", value: "₹4,999" },
      { name: "Outcome", value: "No sale — reserve not met" },
    ],
    features: [
      "Vintage 1973 Hakosuka Tomica",
      "Reserve not met — no winner",
      "May be relisted at a lower reserve",
    ],
    shippingInfo: "Not applicable — auction did not settle.",
    returnPolicy: "Not applicable.",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(10),
  },

  // ── 20. ENDED (no winner — zero bids) — 5 days ago ────────────────────────
  {
    id: "auction-vintage-yugioh-thousand-dragon-fail",
    slug: "auction-vintage-yugioh-thousand-dragon-fail",
    title:
      "Yu-Gi-Oh! Thousand Dragon LOB-040 1st Edition — Zero Bids (AUCTION ENDED)",
    description:
      "AUCTION CLOSED — No bids received. Opening bid of ₹9,999 was too high relative to recent comparables. Item remains with seller. Listing kept for analytics record.",
    category: "category-vintage-tcg",
    categoryName: "Vintage TCG",
    brand: "Konami",
    brandSlug: "brand-konami",
    isAuction: true,
    auctionEndDate: daysAgo(5),
    startingBid: 999900,
    currentBid: 0,
    bidCount: 0,
    reservePrice: 1000000,
    minBidIncrement: 100000,
    autoExtendable: false,
    auctionShippingPaidBy: "winner",
    price: 999900,
    currency: "INR",
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage:
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=800&fit=crop",
    ],
    status: "draft",
    storeName: "CardGame Hub",
    storeId: "store-cardgame-hub",
    featured: false,
    isPromoted: false,
    tags: ["yugioh", "thousand-dragon", "lob", "1st-edition", "auction", "ended", "no-bids"],
    condition: "graded",
    specifications: [
      { name: "Card", value: "Thousand Dragon — LOB-040" },
      { name: "Opening Bid", value: "₹9,999 (too high)" },
      { name: "Outcome", value: "Zero bids — no sale" },
    ],
    features: [
      "Yu-Gi-Oh! vintage 1st Edition",
      "No bids received",
      "Listing kept for analytics",
    ],
    shippingInfo: "Not applicable.",
    returnPolicy: "Not applicable.",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(5),
  },
];

/**
 * SB1-D backfill (S21 2026-05-12): every auction document is stamped with
 * `listingType: "auction"`. Keeps the existing `isAuction: true` flag in place
 * for backwards-compat until the boolean is removed from `ProductDocument`.
 */
export const productsAuctionsSeedData: Partial<ProductDocument>[] =
  _rawProductsAuctionsSeedData.map((p) => ({
    ...p,
    listingType: "auction" as const,
  }));
