/*
 * WHY: Seeds a Beyblade pre-order catalog with real state variety. The original 1-fixture
 *      file only ever exercised `preOrderProductionStatus:"in_production"` — the other two
 *      enum values ("upcoming"/"ready_to_ship"), a sold-out reservation, and a
 *      non-cancellable pre-order were structurally impossible to test against permanent
 *      data (see CLAUDE.md seed-data blandness sweep, 2026-08-20 session).
 * WHAT: Exports 7 pre-order products with listingType:"pre-order" — the original fixture
 *       (now with multiple images + customFields/customSections populated) plus 6 new
 *       ones covering every production-status value, a sold-out reservation, and a
 *       non-cancellable deposit-only pre-order.
 *
 * EXPORTS:
 *   productsPreordersSeedData — Array of 7 pre-order products with listingType:"pre-order"
 *
 * @tag domain:products,pre-orders
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTxt } from "../utils/search-txt";
import { seedPhoto } from "./_helpers/media";
import { withFinalSale } from "./_helpers/final-sale-fixtures";

const _rawPreordersSeedData: Partial<ProductDocument>[] = [
  {
    id: "preorder-beyblade-x-bx-08-wave",
    storeId: "store-beyblade-arena",
    brandSlug: "brand-takara-tomy",
    title: "Beyblade X BX-08 Booster — Next Wave",
    slug: "preorder-beyblade-x-bx-08-wave",
    description:
      "Reserve the next Beyblade X booster wave (BX-08) ahead of its India release. Includes randomized top + Xtreme Gear accessory.",
    price: 799,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    categorySlugs: ["category-x-starters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Starter Sets","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brand: "Takara-Tomy",
    images: [
      seedPhoto("preorder-image-beyblade-x-bx-08-wave-1-20260101", 900, 900),
      seedPhoto("preorder-image-beyblade-x-bx-08-wave-2-20260101", 900, 900),
    ],
    isSold: false,
    availableQuantity: 1,
    tags: ["booster-wave"],
    customFields: [{ key: "Randomized Contents", type: "boolean", value: "true" }],
    customSections: [
      {
        id: "whats-included",
        title: "What's Included",
        text: "1x randomized BX-08 top, 1x Xtreme Gear accessory, official Takara-Tomy packaging. Exact top assortment is randomized per case — no duplicate guarantee.",
      },
    ],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "in_production",
    preOrderDepositPercent: 25,
    preOrderMaxQuantity: 100,
    preOrderCurrentCount: 18,
    preOrderCancellable: true,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: "preorder-beyblade-x-bx-09-glide-ring",
    storeId: "store-beyblade-arena",
    brandSlug: "brand-takara-tomy",
    title: "Beyblade X BX-09 Glide Ring Booster — Coming Soon",
    slug: "preorder-beyblade-x-bx-09-glide-ring",
    description: "Announced but not yet in production — lock in your spot for the BX-09 Glide Ring wave before it goes into manufacturing.",
    price: 849,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    categorySlugs: ["category-x-boosters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Boosters","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brand: "Takara-Tomy",
    images: [
      seedPhoto("preorder-image-beyblade-x-bx-09-glide-ring-1-20260814", 900, 900),
      seedPhoto("preorder-image-beyblade-x-bx-09-glide-ring-2-20260814", 900, 900),
    ],
    isSold: false,
    availableQuantity: 1,
    tags: ["booster-wave"],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "upcoming",
    preOrderDepositPercent: 20,
    preOrderMaxQuantity: 80,
    preOrderCurrentCount: 6,
    preOrderCancellable: true,
    createdAt: new Date("2026-08-14"),
    updatedAt: new Date("2026-08-14"),
  },
  {
    id: "preorder-beyblade-burst-b-210-union",
    storeId: "store-beyblade-arena",
    brandSlug: "brand-beyblade",
    title: "Beyblade Burst B-210 Union Achilles — Ready to Ship",
    slug: "preorder-beyblade-burst-b-210-union",
    description: "Production complete — Union Achilles Cover Change Loaded reservations are boxed and ready to ship as soon as the wave closes.",
    price: 1099,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    categorySlugs: ["category-burst-superking","category-burst-tops","category-beyblade-burst","category-spinning-tops"],
    categoryNames: ["Superking","Burst Tops","Beyblade Burst","Spinning Tops"],
    brand: "Beyblade",
    images: [
      seedPhoto("preorder-image-beyblade-burst-b-210-union-1-20260814", 900, 900),
      seedPhoto("preorder-image-beyblade-burst-b-210-union-2-20260814", 900, 900),
    ],
    isSold: false,
    availableQuantity: 1,
    tags: ["stamina-type"],
    specifications: [
      { name: "Layer / Disc / Driver", value: "Union Achilles / Cover Change / Loaded" },
    ],
    customFields: [{ key: "Production Complete", type: "boolean", value: "true" }],
    customSections: [],
    featured: true,
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "ready_to_ship",
    preOrderDepositPercent: 100,
    preOrderMaxQuantity: 40,
    preOrderCurrentCount: 33,
    preOrderCancellable: false,
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date("2026-08-18"),
  },
  {
    id: "preorder-beyblade-x-bx-11-sold-out",
    storeId: "store-beyblade-arena",
    brandSlug: "brand-takara-tomy",
    title: "Beyblade X BX-11 Limited Wave (Sold Out)",
    slug: "preorder-beyblade-x-bx-11-sold-out",
    description: "This limited-run pre-order wave is fully reserved — all slots claimed. Join the waitlist for the next drop.",
    price: 999,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    categorySlugs: ["category-x-starters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Starter Sets","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brand: "Takara-Tomy",
    images: [
      seedPhoto("preorder-image-beyblade-x-bx-11-sold-out-1-20260812", 900, 900),
    ],
    // `isSold: false` until 2026-08-24, contradicting both the zero
    // availability and the filled allocation immediately below it — so the
    // one fixture whose whole purpose is to be sold out read as available to
    // any predicate that trusted the flag.
    isSold: true,
    availableQuantity: 0,
    tags: ["limited-run"],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "in_production",
    preOrderDepositPercent: 25,
    preOrderMaxQuantity: 25,
    preOrderCurrentCount: 25,
    preOrderCancellable: true,
    createdAt: new Date("2026-08-12"),
    updatedAt: new Date("2026-08-19"),
  },
  {
    id: "preorder-beyblade-burst-b-215-hells-scythe",
    storeId: "store-beyblade-arena",
    brandSlug: "brand-beyblade",
    title: "Beyblade Burst B-215 Hells Scythe — Deposit Locked",
    slug: "preorder-beyblade-burst-b-215-hells-scythe",
    description: "Hells Scythe Giga Reboost, a full-payment pre-order — no cancellation once reserved, guaranteeing your slot in a strictly limited case allocation.",
    price: 1299,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    categorySlugs: ["category-burst-classic","category-burst-tops","category-beyblade-burst","category-spinning-tops"],
    categoryNames: ["Burst Classic","Burst Tops","Beyblade Burst","Spinning Tops"],
    brand: "Beyblade",
    images: [
      seedPhoto("preorder-image-beyblade-burst-b-215-hells-scythe-1-20260817", 900, 900),
      seedPhoto("preorder-image-beyblade-burst-b-215-hells-scythe-2-20260817", 900, 900),
    ],
    isSold: false,
    availableQuantity: 1,
    tags: ["attack-type", "limited-run"],
    specifications: [
      { name: "Layer / Disc / Driver", value: "Hells Scythe / Giga / Reboost" },
    ],
    customFields: [{ key: "Full Payment Required", type: "boolean", value: "true" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "in_production",
    preOrderDepositPercent: 100,
    preOrderMaxQuantity: 20,
    preOrderCurrentCount: 9,
    preOrderCancellable: false,
    createdAt: new Date("2026-08-17"),
    updatedAt: new Date("2026-08-17"),
  },
  {
    id: "preorder-beyblade-original-remaster",
    storeId: "store-beyblade-arena",
    brandSlug: "brand-beyblade",
    title: "Beyblade Original Remaster Set — Announced",
    slug: "preorder-beyblade-original-remaster",
    description: "A 25th-anniversary remaster of the original 1999 lineup, freshly announced. Production hasn't started — early reservations lock in launch pricing.",
    price: 1899,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    categorySlugs: ["category-original-hms","category-original-tops","category-beyblade-original","category-spinning-tops"],
    categoryNames: ["Heavy Metal System","Original Tops","Beyblade Original","Spinning Tops"],
    brand: "Beyblade",
    images: [
      seedPhoto("preorder-image-beyblade-original-remaster-1-20260818", 900, 900),
      seedPhoto("preorder-image-beyblade-original-remaster-2-20260818", 900, 900),
    ],
    isSold: false,
    availableQuantity: 1,
    tags: ["vintage-collectible", "limited-run"],
    customFields: [{ key: "Anniversary Edition", type: "boolean", value: "true" }],
    customSections: [
      {
        id: "whats-included",
        title: "What's Included",
        text: "Remastered Dranzer S + Driger V pair, commemorative case, and a numbered certificate of authenticity.",
      },
    ],
    featured: true,
    isPromoted: true,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "upcoming",
    preOrderDepositPercent: 15,
    preOrderMaxQuantity: 200,
    preOrderCurrentCount: 47,
    preOrderCancellable: true,
    createdAt: new Date("2026-08-18"),
    updatedAt: new Date("2026-08-18"),
  },
  {
    id: "preorder-beyblade-x-bx-12-closed",
    storeId: "store-beyblade-arena",
    brandSlug: "brand-takara-tomy",
    title: "Beyblade X BX-12 Wave — Allocation Closed",
    slug: "preorder-beyblade-x-bx-12-closed",
    description: "Every slot in this wave is spoken for and the units are ready to ship to existing pre-orderers.",
    price: 1299,
    currency: "INR",
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    listingType: "pre-order" as const,
    categorySlugs: ["category-x-boosters","category-x-tops","category-beyblade-x","category-spinning-tops"],
    categoryNames: ["Boosters","Beyblade X Tops","Beyblade X","Spinning Tops"],
    brand: "Takara-Tomy",
    images: [
      seedPhoto("preorder-image-beyblade-x-bx-12-closed-1-20260824", 900, 900),
    ],
    isSold: true,
    availableQuantity: 0,
    tags: ["limited-run"],
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    preOrderDeliveryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    preOrderProductionStatus: "ready_to_ship",
    preOrderDepositPercent: 30,
    preOrderMaxQuantity: 40,
    preOrderCurrentCount: 40,
    preOrderCancellable: false,
    createdAt: new Date("2026-08-24"),
    updatedAt: new Date("2026-08-24"),
  },
];

export const productsPreordersSeedData = _rawPreordersSeedData.map((p) => withFinalSale({
  tags: [] as string[],
  stockQuantity: p.availableQuantity ?? 1,
  mainImage: p.images?.[0] ?? "",
  ...p,
  listingType: "pre-order" as const,
  searchTxt: buildSearchTxt([
    p.title, p.description, p.brand, p.brandSlug,
    p.categoryNames, p.tags, p.features, p.condition,
    p.specifications?.map((s) => `${s.name} ${s.value}`),
  ]),
}));
