/*
 * WHY: `listingType: "stickers"` shares ProductPrintMeta (size/material/finish/editionSize)
 *      with "art" — both printed-only physical goods. Previously left as an empty stub,
 *      but sticker sheets fit the Beyblade theme naturally (see CLAUDE.md seed-data
 *      blandness sweep, 2026-08-20 session).
 * WHAT: Exports 5 Beyblade sticker-sheet listings on Beyblade Arena, varying size,
 *       material, and finish (including a holographic variant and a die-cut vinyl set).
 *
 * EXPORTS:
 *   productsStickersSeedData — Array of 5 Partial<ProductDocument> with listingType:"stickers"
 *
 * @tag domain:products,stickers
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import { ProductDocument } from "../features/products/schemas/firestore";
import { PRODUCT_FIELDS } from "../constants/field-names";
import { buildSearchTokens } from "../utils/search-tokens";
import { seedExtMedia } from "./_helpers/media";

export const productsStickersSeedData: Partial<ProductDocument>[] = [
  {
    id: "stickers-beyblade-original-classic-sheet",
    slug: "stickers-beyblade-original-classic-sheet",
    title: "Beyblade Original Classic — Sticker Sheet",
    description: "A 5x5 cm sticker sheet featuring Dranzer, Driger, Draciel, and Dragoon in classic original-series art style.",
    categorySlugs: ["category-beyblade-original", "category-spinning-tops"],
    categoryNames: ["Beyblade Original", "Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 149,
    currency: "INR",
    stockQuantity: 100,
    availableQuantity: 100,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/stickers-image-original-classic-1-20260817/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/stickers-image-original-classic-1-20260817/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "stickers" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "5x5 cm sheet", material: "Vinyl", finish: "Glossy" },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["stickers", "vintage-collectible"],
    createdAt: new Date("2026-08-17"),
    updatedAt: new Date("2026-08-17"),
    searchTokens: buildSearchTokens(
      "Beyblade Original Classic — Sticker Sheet",
      "5x5 cm sticker sheet featuring Dranzer, Driger, Draciel, and Dragoon.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Original", "Spinning Tops"],
      ["stickers", "vintage-collectible"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "stickers-beyblade-x-holographic-pack",
    slug: "stickers-beyblade-x-holographic-pack",
    title: "Beyblade X Holographic Sticker Pack",
    description: "A holographic-finish sticker pack featuring the current Beyblade X lineup — catches the light with a rainbow shimmer.",
    categorySlugs: ["category-beyblade-x", "category-spinning-tops"],
    categoryNames: ["Beyblade X", "Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 199,
    currency: "INR",
    stockQuantity: 80,
    availableQuantity: 62,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/stickers-image-x-holo-1-20260818/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/stickers-image-x-holo-1-20260818/900/900"),
      seedExtMedia("https://picsum.photos/seed/stickers-image-x-holo-2-20260818/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "stickers" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "8x10 cm sheet", material: "Holographic vinyl", finish: "Holographic" },
    customFields: [],
    customSections: [],
    featured: true,
    isPromoted: false,
    isOnSale: false,
    tags: ["stickers"],
    createdAt: new Date("2026-08-18"),
    updatedAt: new Date("2026-08-19"),
    searchTokens: buildSearchTokens(
      "Beyblade X Holographic Sticker Pack",
      "Holographic-finish sticker pack featuring the current Beyblade X lineup.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["stickers"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "stickers-beyblade-burst-diecut-set",
    slug: "stickers-beyblade-burst-diecut-set",
    title: "Beyblade Burst Die-Cut Sticker Set (6-Pack)",
    description: "Individually die-cut vinyl stickers of 6 fan-favorite Burst tops — no background, clean edges, weatherproof.",
    categorySlugs: ["category-beyblade-burst", "category-spinning-tops"],
    categoryNames: ["Beyblade Burst", "Spinning Tops"],
    brandSlug: "brand-beyblade",
    brand: "Beyblade",
    price: 249,
    currency: "INR",
    stockQuantity: 60,
    availableQuantity: 60,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/stickers-image-burst-diecut-1-20260819/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/stickers-image-burst-diecut-1-20260819/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "stickers" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "Individually die-cut, ~6x6 cm each", material: "Weatherproof vinyl", finish: "Matte" },
    customFields: [{ key: "Pack Count", type: "number", value: "6" }],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["stickers"],
    createdAt: new Date("2026-08-19"),
    updatedAt: new Date("2026-08-19"),
    searchTokens: buildSearchTokens(
      "Beyblade Burst Die-Cut Sticker Set (6-Pack)",
      "Individually die-cut vinyl stickers of 6 fan-favorite Burst tops.",
      "Beyblade",
      "brand-beyblade",
      ["Beyblade Burst", "Spinning Tops"],
      ["stickers"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "stickers-beyblade-metal-retro-sheet",
    slug: "stickers-beyblade-metal-retro-sheet",
    title: "Metal Fight Retro Sticker Sheet — Limited /500",
    description: "A limited-edition retro-styled sticker sheet celebrating Metal Fight favorites, numbered out of 500.",
    categorySlugs: ["category-beyblade-metal", "category-spinning-tops"],
    categoryNames: ["Beyblade Metal Fight", "Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 179,
    currency: "INR",
    stockQuantity: 500,
    availableQuantity: 214,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/stickers-image-metal-retro-1-20260819/900/900"),
    images: [seedExtMedia("https://picsum.photos/seed/stickers-image-metal-retro-1-20260819/900/900")],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "stickers" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "6x8 cm sheet", material: "Vinyl", finish: "Matte", editionSize: 500 },
    customFields: [],
    customSections: [],
    featured: false,
    isPromoted: false,
    isOnSale: false,
    tags: ["stickers", "vintage-collectible", "limited-run"],
    createdAt: new Date("2026-08-19"),
    updatedAt: new Date("2026-08-19"),
    searchTokens: buildSearchTokens(
      "Metal Fight Retro Sticker Sheet — Limited /500",
      "Limited-edition retro-styled sticker sheet, numbered out of 500.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade Metal Fight", "Spinning Tops"],
      ["stickers", "vintage-collectible", "limited-run"],
    ),
  } as unknown as Partial<ProductDocument>,
  {
    id: "stickers-beyblade-x-glow-in-dark",
    slug: "stickers-beyblade-x-glow-in-dark",
    title: "Beyblade X Glow-in-the-Dark Sticker Pack",
    description: "Charge these stickers under light and watch the Beyblade X logos glow in the dark. Great for stadium cases and water bottles.",
    categorySlugs: ["category-beyblade-x", "category-spinning-tops"],
    categoryNames: ["Beyblade X", "Spinning Tops"],
    brandSlug: "brand-takara-tomy",
    brand: "Takara-Tomy",
    price: 229,
    currency: "INR",
    stockQuantity: 45,
    availableQuantity: 45,
    isSold: false,
    mainImage: seedExtMedia("https://picsum.photos/seed/stickers-image-x-glow-1-20260819/900/900"),
    images: [
      seedExtMedia("https://picsum.photos/seed/stickers-image-x-glow-1-20260819/900/900"),
      seedExtMedia("https://picsum.photos/seed/stickers-image-x-glow-2-20260819/900/900"),
    ],
    status: PRODUCT_FIELDS.STATUS_VALUES.PUBLISHED,
    condition: PRODUCT_FIELDS.CONDITION_VALUES.NEW,
    listingType: "stickers" as const,
    storeId: "store-beyblade-arena",
    storeName: "Beyblade Arena",
    printMeta: { size: "7x9 cm sheet", material: "Glow-in-the-dark vinyl", finish: "Matte" },
    customFields: [{ key: "Glow Duration", type: "text", value: "~3 hours after charging" }],
    customSections: [],
    featured: true,
    isPromoted: true,
    isOnSale: false,
    tags: ["stickers"],
    createdAt: new Date("2026-08-19"),
    updatedAt: new Date("2026-08-19"),
    searchTokens: buildSearchTokens(
      "Beyblade X Glow-in-the-Dark Sticker Pack",
      "Charge under light and watch the Beyblade X logos glow in the dark.",
      "Takara-Tomy",
      "brand-takara-tomy",
      ["Beyblade X", "Spinning Tops"],
      ["stickers"],
    ),
  } as unknown as Partial<ProductDocument>,
];
