/**
 * Retro Gaming & Vintage Diecast — Products Seed Data
 * Nintendo · SEGA · Vintage Diecast Cars
 * 18 general · 1 auction · 1 pre-order = 20 total
 * Seller: Retro Vault India (store-retro-vault-india)
 */

import { getDefaultCurrency } from "./seed-market-config";
import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

const RV = {
  sellerId: "user-retro-vault-owner",
  storeId: "store-retro-vault-india",
  sellerName: "Retro Vault India",
  sellerEmail: "retrovault@letitrip.in",
} as const;

const RG_IMGS = [
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Nintendo_Entertainment_System.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Super_Nintendo_Entertainment_System.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Game_Boy_original.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Nintendo_64.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Sega_Mega_Drive_PAL_version.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Game_Boy_Advance.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Game_Boy_Color.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Atari_2600.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Neo_Geo_AES.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/PlayStation_(console).jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Sega_Saturn.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Game_cartridge.jpg?width=640",
];
const img = (seed: string) => {
  let h = 0; for (const c of seed) h = (h * 31 + c.charCodeAt(0)) & 0x7fff;
  return RG_IMGS[h % RG_IMGS.length];
};

export const retroGamingSeedData: Partial<ProductDocument>[] = [

  // ── NINTENDO (6) ─────────────────────────────────────────────────────────

  {
    id: "product-rg-nes-console-boxed-rg-1",
    title: "Nintendo NES Console — Complete In Box (1985 Original)",
    description: "<p>Original 1985 Nintendo Entertainment System — complete in box with original cables, controller, zapper, and Super Mario Bros/Duck Hunt cartridge. Box has moderate shelf wear, console and accessories are in excellent working condition. HDMI mod available on request.</p>",
    slug: "nintendo-nes-console-complete-in-box-1985",
    category: "category-retro-nintendo",
    subcategory: "Consoles",
    brand: "Nintendo",
    price: 8999,
    currency: _CURRENCY,
    stockQuantity: 4,
    availableQuantity: 3,
    mainImage: img("nintendo-nes-console"),
    images: [img("nintendo-nes-console"), img("nintendo-nes-box"), img("nintendo-nes-contents")],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
      thumbnailUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Nintendo_Entertainment_System.jpg?width=640",
      duration: 30,
    },
    status: "published",
    ...RV,
    featured: true,
    tags: ["nintendo", "nes", "retro", "console", "1985", "complete in box", "vintage"],
    specifications: [
      { name: "Year", value: "1985 (Original)" },
      { name: "Condition", value: "Working — excellent" },
      { name: "Contents", value: "Console + 2 controllers + zapper + cables + 2 games" },
    ],
    features: ["Fully working console", "Original zapper gun", "Super Mario Bros + Duck Hunt", "Complete original box"],
    shippingInfo: "Padded rigid box. Insured nationwide.",
    returnPolicy: "10-day returns. Must be as described.",
    condition: "used",
    insurance: true,
    insuranceCost: 299,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.9,
    reviewCount: 12,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-rg-snes-console-boxed-rg-2",
    title: "Nintendo SNES Super Console — Complete In Box (1991)",
    description: "<p>Super Nintendo Entertainment System from 1991 — complete with box, console, 2 controllers, and Super Mario World cartridge. Controller buttons have normal wear. Console outputs composite video cleanly. A nostalgia centrepiece that still plays perfectly after 30+ years.</p>",
    slug: "nintendo-snes-console-complete-in-box-1991",
    category: "category-retro-nintendo",
    subcategory: "Consoles",
    brand: "Nintendo",
    price: 11999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 2,
    mainImage: img("nintendo-snes-console"),
    images: [img("nintendo-snes-console"), img("nintendo-snes-controllers")],
    status: "published",
    ...RV,
    featured: true,
    tags: ["nintendo", "snes", "super nintendo", "retro", "1991", "complete in box"],
    specifications: [
      { name: "Year", value: "1991 (Original)" },
      { name: "Contents", value: "Console + 2 controllers + cables + Super Mario World" },
    ],
    features: ["Fully working SNES", "Super Mario World included", "Original SNES box", "Normal controller wear"],
    shippingInfo: "Padded box. Insured nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: true,
    insuranceCost: 349,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 8,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(7),
  },

  {
    id: "product-rg-gameboy-original-dmg-rg-3",
    title: "Nintendo Game Boy DMG-01 — Original Grey Brick (1989)",
    description: "<p>The original Game Boy DMG-01 in working condition — the grey brick that started it all. Screen has light scratch (still clear display). Includes battery cover and Tetris cartridge. Authentic 1989 Japanese unit. Yellowing is minimal for age. A true gaming history artefact.</p>",
    slug: "nintendo-gameboy-dmg-01-original-1989",
    category: "category-retro-nintendo",
    subcategory: "Handhelds",
    brand: "Nintendo",
    price: 5999,
    currency: _CURRENCY,
    stockQuantity: 6,
    availableQuantity: 5,
    mainImage: img("nintendo-gameboy-dmg"),
    images: [img("nintendo-gameboy-dmg"), img("nintendo-gameboy-tetris")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["nintendo", "game boy", "dmg-01", "1989", "original", "retro", "handheld"],
    specifications: [
      { name: "Year", value: "1989" },
      { name: "Model", value: "DMG-01" },
      { name: "Includes", value: "Battery cover + Tetris cartridge" },
    ],
    features: ["Original 1989 DMG-01", "Includes Tetris", "Minimal yellowing", "Working speaker and controls"],
    shippingInfo: "Padded protective case. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 15,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(8),
  },

  {
    id: "product-rg-n64-console-rg-4",
    title: "Nintendo 64 Console — Charcoal Grey (1997) with Mario Kart 64",
    description: "<p>Nintendo 64 in charcoal grey — working perfectly with 1 original controller and Mario Kart 64 cartridge. Expansion pak slot covered. Analogue stick has typical N64 wear but works well. NTSC-J version (Japan). Plays all region games with adapter (not included).</p>",
    slug: "nintendo-64-console-charcoal-mario-kart-1997",
    category: "category-retro-nintendo",
    subcategory: "Consoles",
    brand: "Nintendo",
    price: 7499,
    currency: _CURRENCY,
    stockQuantity: 4,
    availableQuantity: 3,
    mainImage: img("nintendo-n64-console"),
    images: [img("nintendo-n64-console"), img("nintendo-n64-mk64")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["nintendo", "n64", "nintendo 64", "1997", "mario kart", "retro"],
    specifications: [
      { name: "Year", value: "1997" },
      { name: "Region", value: "NTSC-J" },
      { name: "Contents", value: "Console + 1 controller + Mario Kart 64" },
    ],
    features: ["Working N64 console", "Mario Kart 64 included", "Original controller", "NTSC-J region"],
    shippingInfo: "Padded box. Insured nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: true,
    insuranceCost: 249,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 9,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(10),
  },

  {
    id: "product-rg-super-mario-64-sealed-rg-5",
    title: "Super Mario 64 — Factory Sealed NTSC-J Cartridge (1996)",
    description: "<p>Factory-sealed Super Mario 64 N64 cartridge — original 1996 NTSC-J release. Never opened. Seal intact with no tears. The game that defined 3D platforming forever. VGA-comparable seal freshness. Extremely rare to find sealed after 30 years.</p>",
    slug: "super-mario-64-factory-sealed-ntscj-1996",
    category: "category-retro-nintendo",
    subcategory: "Cartridges",
    brand: "Nintendo",
    price: 14999,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("supermario64-sealed"),
    images: [img("supermario64-sealed"), img("supermario64-seal-close")],
    status: "published",
    ...RV,
    featured: true,
    tags: ["nintendo", "super mario 64", "sealed", "ntsc-j", "1996", "n64", "rare"],
    specifications: [
      { name: "Year", value: "1996 (Original Release)" },
      { name: "Region", value: "NTSC-J" },
      { name: "Seal Condition", value: "Intact — no tears" },
    ],
    features: ["Factory sealed original", "1996 first printing", "Seal fully intact", "Extremely rare find"],
    shippingInfo: "Protective sleeved box. Insured nationwide.",
    returnPolicy: "10-day returns for factory-sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 499,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-rg-gameboy-color-purple-rg-6",
    title: "Nintendo Game Boy Color — Atomic Purple (GBC, 1998)",
    description: "<p>Game Boy Color in Atomic Purple — transparent chassis showing internal PCB. Near-mint condition, light scratching on back only. Works perfectly with all GBC and original GB games. Comes with Pokemon Gold cartridge. Iconic late-90s design that still looks futuristic today.</p>",
    slug: "nintendo-gameboy-color-atomic-purple-1998",
    category: "category-retro-nintendo",
    subcategory: "Handhelds",
    brand: "Nintendo",
    price: 6499,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 4,
    mainImage: img("gameboy-color-purple"),
    images: [img("gameboy-color-purple"), img("gameboy-color-pokemon-gold")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["nintendo", "game boy color", "gbc", "atomic purple", "1998", "retro"],
    specifications: [
      { name: "Year", value: "1998" },
      { name: "Colour", value: "Atomic Purple (transparent)" },
      { name: "Includes", value: "Pokemon Gold cartridge" },
    ],
    features: ["Transparent atomic purple chassis", "Near-mint condition", "Pokemon Gold included", "Plays GBC + GB games"],
    shippingInfo: "Padded protective case. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 11,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(6),
  },

  // ── SEGA (5) ─────────────────────────────────────────────────────────────

  {
    id: "product-rg-sega-genesis-model1-rg-7",
    title: "Sega Genesis Model 1 — High Definition Compatible (1989)",
    description: "<p>Original Sega Genesis Model 1 with HDMI upscaler board pre-installed. VA3 motherboard revision — best audio output. Includes Sonic the Hedgehog cartridge. Controller is near mint. The definitive vintage SEGA setup for modern TVs.</p>",
    slug: "sega-genesis-model1-hdmi-mod-1989",
    category: "category-retro-sega",
    subcategory: "Consoles",
    brand: "SEGA",
    price: 9999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 2,
    mainImage: img("sega-genesis-model1"),
    images: [img("sega-genesis-model1"), img("sega-genesis-sonic")],
    status: "published",
    ...RV,
    featured: true,
    tags: ["sega", "genesis", "mega drive", "model 1", "hdmi", "1989", "retro"],
    specifications: [
      { name: "Year", value: "1989 (Original)" },
      { name: "Mod", value: "HDMI upscaler pre-installed" },
      { name: "Revision", value: "VA3 (best audio)" },
      { name: "Includes", value: "Sonic the Hedgehog" },
    ],
    features: ["HDMI upscaler mod", "VA3 best audio revision", "Sonic included", "Modern TV compatible"],
    shippingInfo: "Padded box. Insured nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: true,
    insuranceCost: 299,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 7,
    createdAt: daysAgo(110),
    updatedAt: daysAgo(9),
  },

  {
    id: "product-rg-sega-dreamcast-console-rg-8",
    title: "Sega Dreamcast — White Console with Controller (1998)",
    description: "<p>Sega Dreamcast in white — SEGA's final console and arguably their finest. Includes one VMU memory card, original controller, and Sonic Adventure 2 disc. GD-ROM drive reads well. A legendary console that died too young. Perfect for collectors and those new to retro gaming.</p>",
    slug: "sega-dreamcast-console-white-1998",
    category: "category-retro-sega",
    subcategory: "Consoles",
    brand: "SEGA",
    price: 7999,
    currency: _CURRENCY,
    stockQuantity: 4,
    availableQuantity: 3,
    mainImage: img("sega-dreamcast"),
    images: [img("sega-dreamcast"), img("sega-dreamcast-vmu")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["sega", "dreamcast", "white", "1998", "retro", "console", "sonic adventure"],
    specifications: [
      { name: "Year", value: "1998 (Japanese release)" },
      { name: "Contents", value: "Console + VMU + controller + Sonic Adventure 2" },
    ],
    features: ["GD-ROM drive working", "VMU memory card included", "Sonic Adventure 2", "Original controller"],
    shippingInfo: "Padded box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: true,
    insuranceCost: 249,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 6,
    createdAt: daysAgo(95),
    updatedAt: daysAgo(12),
  },

  {
    id: "product-rg-sega-master-system-rg-9",
    title: "Sega Master System II — Working Console (1986)",
    description: "<p>Sega Master System II — the European/Brazilian blockbuster SEGA console. Includes built-in Alex Kidd in Miracle World game, 2 standard controllers, and 3 cartridges: Sonic the Hedgehog, Wonder Boy, and Fantasy Zone. Composite output tested.</p>",
    slug: "sega-master-system-ii-console-1986",
    category: "category-retro-sega",
    subcategory: "Consoles",
    brand: "SEGA",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 4,
    mainImage: img("sega-master-system-2"),
    images: [img("sega-master-system-2")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["sega", "master system", "sms", "1986", "retro", "alex kidd"],
    specifications: [
      { name: "Built-in Game", value: "Alex Kidd in Miracle World" },
      { name: "Includes", value: "2 controllers + 3 cartridges" },
    ],
    features: ["Built-in Alex Kidd", "3 extra cartridges", "2 controllers", "Composite tested"],
    shippingInfo: "Padded box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 4,
    createdAt: daysAgo(130),
    updatedAt: daysAgo(15),
  },

  {
    id: "product-rg-sonic-hedgehog-genesis-cib-rg-10",
    title: "Sonic the Hedgehog — Genesis Complete In Box (1991 US Release)",
    description: "<p>Original 1991 Sonic the Hedgehog for Sega Genesis in complete-in-box condition. Box has light shelf wear. Manual complete with registration card. Cartridge tested working. The game that put SEGA on the map — an iconic piece of gaming history.</p>",
    slug: "sonic-hedgehog-sega-genesis-cib-1991",
    category: "category-retro-sega",
    subcategory: "Cartridges",
    brand: "SEGA",
    price: 3999,
    currency: _CURRENCY,
    stockQuantity: 6,
    availableQuantity: 5,
    mainImage: img("sonic-genesis-cib"),
    images: [img("sonic-genesis-cib"), img("sonic-genesis-manual")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["sega", "sonic", "genesis", "mega drive", "1991", "complete in box", "cib"],
    specifications: [
      { name: "Year", value: "1991" },
      { name: "Region", value: "NTSC-US" },
      { name: "Condition", value: "CIB — light shelf wear on box" },
    ],
    features: ["Complete in box", "Manual with registration card", "Cartridge tested", "1991 first print"],
    shippingInfo: "Protective sleeve and padded box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 10,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-rg-sega-saturn-console-rg-11",
    title: "Sega Saturn — Grey Console with Nights into Dreams (1994 JP)",
    description: "<p>Sega Saturn in original grey — Japanese 1994 release. Includes Nights Into Dreams disc, one original control pad. Disc tray mechanism tested smooth. NTSC-J region, plays all import titles. A beloved collector's console with exceptional 2D performance and a great library.</p>",
    slug: "sega-saturn-console-grey-nights-dreams-jp",
    category: "category-retro-sega",
    subcategory: "Consoles",
    brand: "SEGA",
    price: 8499,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 2,
    mainImage: img("sega-saturn-grey"),
    images: [img("sega-saturn-grey"), img("sega-saturn-nights")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["sega", "saturn", "grey", "1994", "nights into dreams", "japanese", "retro"],
    specifications: [
      { name: "Year", value: "1994 (JP release)" },
      { name: "Region", value: "NTSC-J" },
      { name: "Includes", value: "Console + controller + Nights Into Dreams" },
    ],
    features: ["NTSC-J original", "Nights Into Dreams included", "Tested disc tray", "Great 2D library"],
    shippingInfo: "Padded box. Insured nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: true,
    insuranceCost: 249,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 5,
    createdAt: daysAgo(105),
    updatedAt: daysAgo(11),
  },

  // ── VINTAGE DIECAST (7) ───────────────────────────────────────────────────

  {
    id: "product-rg-matchbox-ferrari-250-1960s-rg-12",
    title: "Matchbox Ferrari 250 GTO — 1960s Original Lesney (Loose, EX)",
    description: "<p>Original 1960s Matchbox Ferrari 250 GTO by Lesney — red body, smooth wheels, grey plastic base. Excellent condition for age with minimal paint wear. A true vintage die-cast from when Matchbox was the undisputed king of 1:64 scale. No box but figure is in excellent shape.</p>",
    slug: "matchbox-ferrari-250-gto-1960s-lesney-loose",
    category: "category-vintage-diecast",
    subcategory: "Matchbox Lesney",
    brand: "Matchbox",
    price: 1999,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 7,
    mainImage: img("matchbox-ferrari-1960s"),
    images: [img("matchbox-ferrari-1960s"), img("matchbox-ferrari-bottom")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["matchbox", "lesney", "ferrari", "250 gto", "1960s", "vintage", "diecast"],
    specifications: [
      { name: "Era", value: "1960s (Original Lesney)" },
      { name: "Scale", value: "1:64 approximate" },
      { name: "Condition", value: "Excellent — minimal paint wear" },
    ],
    features: ["1960s Lesney original", "Red Ferrari body", "Smooth wheels", "Minimal wear"],
    shippingInfo: "Bubble wrapped protective box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 6,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(14),
  },

  {
    id: "product-rg-corgi-aston-martin-db5-rg-13",
    title: "Corgi James Bond Aston Martin DB5 — 1965 Original (Boxed)",
    description: "<p>Original 1965 Corgi James Bond Aston Martin DB5 with ejector seat function — the most famous toy car ever made. Original box with wear, car in VG condition. Ejector seat mechanism works. Passenger figures present. Roof-mounted machine gun covers intact. Numbered 261.</p>",
    slug: "corgi-james-bond-aston-martin-db5-1965-boxed",
    category: "category-vintage-diecast",
    subcategory: "Corgi",
    brand: "Corgi",
    price: 12999,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 1,
    mainImage: img("corgi-aston-db5-bond"),
    images: [img("corgi-aston-db5-bond"), img("corgi-aston-db5-box"), img("corgi-aston-db5-ejector")],
    status: "published",
    ...RV,
    featured: true,
    tags: ["corgi", "james bond", "aston martin", "db5", "1965", "original", "boxed", "vintage"],
    specifications: [
      { name: "Year", value: "1965 (Original Corgi 261)" },
      { name: "Model No.", value: "261" },
      { name: "Car Condition", value: "Very Good" },
      { name: "Box Condition", value: "Good — wear" },
      { name: "Ejector Seat", value: "Working" },
    ],
    features: ["Working ejector seat", "Passenger figures included", "Machine gun covers intact", "Original 1965 261 release"],
    shippingInfo: "Protected collector box. Insured nationwide.",
    returnPolicy: "10-day returns for as-described condition.",
    condition: "used",
    insurance: true,
    insuranceCost: 399,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(15),
    avgRating: 5.0,
    reviewCount: 3,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-rg-dinky-spitfire-ww2-rg-14",
    title: "Dinky Toys Spitfire — WWII 1/72 Scale Original (1970s)",
    description: "<p>Dinky Toys Spitfire in 1/72 scale — WWII fighter plane from the 1970s Dinky military aircraft range. Die-cast with fabric-printed transfer roundel markings. Retractable undercarriage. Original box shows moderate wear, plane in very good condition with all decals.</p>",
    slug: "dinky-toys-spitfire-ww2-1970s-original",
    category: "category-vintage-diecast",
    subcategory: "Dinky Toys",
    brand: "Dinky",
    price: 3499,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 4,
    mainImage: img("dinky-spitfire-ww2"),
    images: [img("dinky-spitfire-ww2"), img("dinky-spitfire-box")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["dinky", "spitfire", "ww2", "military", "aircraft", "1970s", "vintage", "diecast"],
    specifications: [
      { name: "Scale", value: "1:72" },
      { name: "Era", value: "1970s" },
      { name: "Type", value: "WWII Military Aircraft" },
    ],
    features: ["Retractable undercarriage", "Roundel transfer decals", "1970s original", "WWII military deco"],
    shippingInfo: "Padded box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 5,
    createdAt: daysAgo(140),
    updatedAt: daysAgo(18),
  },

  {
    id: "product-rg-britains-soldiers-set-rg-15",
    title: "Britain's Diecast Soldiers — Cold War Era Set (1960s, Boxed)",
    description: "<p>Britain's Diecast Toy Soldiers in original box — Cold War era infantry set from the 1960s. 12 figures in khaki with full complement of rifles, machine guns, and mortar. Box is complete but worn. Figures are in excellent marching and firing poses. Rare complete set.</p>",
    slug: "britains-toy-soldiers-cold-war-1960s-set",
    category: "category-vintage-diecast",
    subcategory: "Britain's",
    brand: "Britain's",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 2,
    mainImage: img("britains-soldiers-1960s"),
    images: [img("britains-soldiers-1960s"), img("britains-soldiers-box")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["britains", "toy soldiers", "diecast", "cold war", "1960s", "vintage", "boxed"],
    specifications: [
      { name: "Era", value: "1960s Cold War" },
      { name: "Contents", value: "12 infantry figures + weapons" },
    ],
    features: ["12 figure complete set", "Rifles + mortar accessories", "Cold War khaki uniforms", "Original Britain's box"],
    shippingInfo: "Padded rigid box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 4,
    createdAt: daysAgo(160),
    updatedAt: daysAgo(20),
  },

  {
    id: "product-rg-hot-wheels-redline-camaro-rg-16",
    title: "Hot Wheels Redline Camaro — 1968 Original Spectraflame (Rare)",
    description: "<p>Original 1968 Hot Wheels Redline Camaro in Spectraflame red — the very first generation of Hot Wheels cars. Redline wheels (the rare original rubber tires) intact on all four corners. Minimal paint wear for a 55-year-old toy. This is what started the Hot Wheels legend.</p>",
    slug: "hot-wheels-redline-camaro-1968-spectraflame-original",
    category: "category-vintage-diecast",
    subcategory: "Hot Wheels Redlines",
    brand: "Hot Wheels",
    price: 8999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 2,
    mainImage: img("hw-redline-camaro-1968"),
    images: [img("hw-redline-camaro-1968"), img("hw-redline-camaro-wheels")],
    status: "published",
    ...RV,
    featured: true,
    tags: ["hot wheels", "redline", "camaro", "1968", "spectraflame", "original", "vintage", "rare"],
    specifications: [
      { name: "Year", value: "1968 (First Generation)" },
      { name: "Wheels", value: "Original Redline" },
      { name: "Finish", value: "Spectraflame Red" },
    ],
    features: ["Original 1968 first-gen Hot Wheels", "All-four Redline wheels intact", "Spectraflame metallic finish", "55+ year old toy in great shape"],
    shippingInfo: "Collector sleeve and padded box. Insured nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: true,
    insuranceCost: 299,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(25),
    avgRating: 5.0,
    reviewCount: 2,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-rg-tonka-steel-truck-1970s-rg-17",
    title: "Tonka Steel Pressed Dump Truck — 1970s Original (Large Scale)",
    description: "<p>Original 1970s Tonka steel pressed dump truck in classic yellow — the indestructible steel toy that defined an era. Large scale (~40 cm) with working dump bed raise/lower lever. Surface rust on underside only; exterior paint remarkably intact. A genuine nostalgia centrepiece.</p>",
    slug: "tonka-steel-pressed-dump-truck-1970s-yellow",
    category: "category-vintage-diecast",
    subcategory: "Tonka Steel",
    brand: "Tonka",
    price: 3999,
    currency: _CURRENCY,
    stockQuantity: 4,
    availableQuantity: 3,
    mainImage: img("tonka-dump-truck-1970s"),
    images: [img("tonka-dump-truck-1970s"), img("tonka-dump-truck-bed")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["tonka", "steel", "dump truck", "1970s", "vintage", "yellow", "pressed steel"],
    specifications: [
      { name: "Era", value: "1970s" },
      { name: "Material", value: "Pressed steel" },
      { name: "Length", value: "~40 cm" },
      { name: "Mechanism", value: "Working dump bed" },
    ],
    features: ["Working dump bed lever", "Pressed steel construction", "Classic yellow paint", "Minimal surface rust"],
    shippingInfo: "Padded heavy box. Nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: false,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.5,
    reviewCount: 7,
    createdAt: daysAgo(170),
    updatedAt: daysAgo(22),
  },

  {
    id: "product-rg-schuco-micro-racer-rg-18",
    title: "Schuco Micro Racer — Wind-Up German Tin Car (1960s)",
    description: "<p>Schuco Micro Racer wind-up tin car from the 1960s — the pinnacle of German toy engineering. Ferrari-inspired red body with working wind-up key mechanism. Steerable front wheels via key. Box present but heavily worn. Car mechanism works perfectly after 60+ years.</p>",
    slug: "schuco-micro-racer-wind-up-1960s-german",
    category: "category-vintage-diecast",
    subcategory: "Schuco",
    brand: "Schuco",
    price: 6999,
    currency: _CURRENCY,
    stockQuantity: 2,
    availableQuantity: 1,
    mainImage: img("schuco-micro-racer-1960s"),
    images: [img("schuco-micro-racer-1960s"), img("schuco-micro-racer-key")],
    status: "published",
    ...RV,
    featured: true,
    tags: ["schuco", "micro racer", "wind-up", "tin", "1960s", "german", "vintage"],
    specifications: [
      { name: "Era", value: "1960s (West Germany)" },
      { name: "Mechanism", value: "Wind-up key" },
      { name: "Material", value: "Tin plate" },
    ],
    features: ["Working wind-up mechanism", "Steerable front wheels", "Ferrari-inspired body", "German tin plate engineering"],
    shippingInfo: "Padded protective box. Insured nationwide.",
    returnPolicy: "10-day returns.",
    condition: "used",
    insurance: true,
    insuranceCost: 199,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 3,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(5),
  },

  // ── AUCTION (1) ───────────────────────────────────────────────────────────

  {
    id: "auction-rg-nes-punch-out-sealed-rg-1",
    title: "AUCTION — Mike Tyson's Punch-Out!! NES Factory Sealed (1987)",
    description: "<p>Factory sealed Mike Tyson's Punch-Out!! for NES — original 1987 US release with H-Seam seal intact. This is one of the most iconic NES games and extremely hard to find sealed. Professional authentication by WATA Games (graded 7.0 A+ seal). Reserve your bid now.</p>",
    slug: "auction-nes-mike-tysons-punch-out-sealed-1987",
    category: "category-retro-nintendo",
    subcategory: "Sealed Cartridges",
    brand: "Nintendo",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("nes-punchout-sealed"),
    images: [img("nes-punchout-sealed"), img("nes-punchout-seal"), img("nes-punchout-wata")],
    status: "published",
    ...RV,
    featured: true,
    tags: ["nes", "punch-out", "mike tyson", "sealed", "1987", "auction", "wata", "graded"],
    specifications: [
      { name: "Year", value: "1987 (H-Seam US Release)" },
      { name: "Grade", value: "WATA 7.0 A+" },
      { name: "Seal", value: "H-Seam intact" },
    ],
    features: ["WATA graded 7.0 A+", "H-Seam seal intact", "1987 original printing", "Professional authentication"],
    shippingInfo: "Graded slab protective shipping. Insured nationwide.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 999,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(12),
    startingBid: 14999,
    currentBid: 22000,
    bidCount: 11,
    reservePrice: 28000,
    buyNowPrice: 69999,
    minBidIncrement: 1000,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionOriginalEndDate: daysAhead(12),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(12),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
  },

  // ── PRE-ORDER (1) ─────────────────────────────────────────────────────────

  {
    id: "preorder-rg-nintendo-classic-mini-2026-rg-1",
    title: "PRE-ORDER — Nintendo Classic Mini Super NES 2026 Edition (Rumoured)",
    description: "<p>Reserve our notification spot for the rumoured Nintendo Classic Mini Super NES 2026 re-issue. Get priority access when Nintendo confirms the release. Our store allocation is limited to 20 units. No payment taken until dispatch confirmed. Register interest now to avoid missing out.</p>",
    slug: "preorder-nintendo-classic-mini-snes-2026",
    category: "category-retro-nintendo",
    subcategory: "Mini Classics",
    brand: "Nintendo",
    price: 7999,
    currency: _CURRENCY,
    stockQuantity: 20,
    availableQuantity: 17,
    mainImage: img("nintendo-mini-snes-2026"),
    images: [img("nintendo-mini-snes-2026")],
    status: "published",
    ...RV,
    featured: false,
    tags: ["nintendo", "classic mini", "snes", "pre-order", "2026", "rumoured"],
    specifications: [
      { name: "Expected", value: "Q2 2026 (subject to Nintendo confirmation)" },
      { name: "Store Allocation", value: "20 units" },
    ],
    features: ["Priority allocation", "No payment until dispatch", "Interest registration", "India-first allocation"],
    shippingInfo: "Dispatched on Nintendo release.",
    returnPolicy: "Full cancellation available any time before dispatch.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(160),
    preOrderProductionStatus: "upcoming",
    isPromoted: false,
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
];
