/**
 * Reviews Seed Data — LetItRip Collectibles Platform
 * 15 reviews distributed across the 5 stores from P15.
 * Uses buyer IDs from P15 and product IDs from P16/P17/P18.
 * review- prefix, system-generated IDs (not slug-based per slug prefix table).
 */

import type { ReviewDocument } from "../features/reviews/schemas";
import { REVIEW_FIELDS } from "../constants/field-names";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const SELLER_STORE: Record<string, { storeId: string; storeName: string }> = {
  "user-aryan-kapoor":    { storeId: "store-pokemon-palace",     storeName: "Pokémon Palace" },
  "user-nisha-reddy":     { storeId: "store-cardgame-hub",       storeName: "CardGame Hub" },
  "user-vikram-mehta":    { storeId: "store-diecast-depot",      storeName: "Diecast Depot" },
  "user-rohit-joshi":     { storeId: "store-beyblade-arena",     storeName: "Beyblade Arena" },
  "user-admin-letitrip":  { storeId: "store-letitrip-official",  storeName: "LetItRip Official" },
  "user-priya-singh":     { storeId: "store-tokyo-toys-india",   storeName: "Tokyo Toys India" },
  "user-amit-sharma":     { storeId: "store-gundam-galaxy",      storeName: "Gundam Galaxy" },
};

const rawReviews: Array<Partial<ReviewDocument> & { sellerId?: string }> = [
  // ── store-pokemon-palace (4 reviews) ─────────────────────────────────────

  {
    id: "review-pokemon-151-box-rahul-001",
    productId: "product-pokemon-151-booster-box",
    productTitle: "Pokémon 151 Booster Box (Sealed)",
    sellerId: "user-aryan-kapoor",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "Absolutely pristine sealed box — perfect packaging",
    comment:
      "Aryan packed this box like it was going to the moon. Double-boxed, foam corners, bubble wrap around the individual booster packs inside. The Pokémon 151 box arrived 100% sealed with no dents. Pulled a Mew ex SAR on my first pack — couldn't be happier. Will buy every new set from Pokémon Palace.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 14,
    reportCount: 0,
    verified: true,
    featured: true,
    sellerReply: "Thank you so much, Rahul! Double-boxing is our standard for all sealed products — we know how precious these are. So glad the Mew ex SAR made your day! 🎉",
    sellerRepliedAt: daysAgo(53),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(53),
    approvedAt: daysAgo(54),
  },

  {
    id: "review-base-set-sealed-arjun-002",
    productId: "product-pokemon-base-set-booster-sealed",
    productTitle: "Pokémon Base Set Shadowless Booster Box (Sealed)",
    sellerId: "user-aryan-kapoor",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 5,
    title: "Genuine shadowless box, exactly as described",
    comment:
      "This was a huge purchase for me — ₹89,999 is not nothing. I did video unboxing of the packaging for insurance purposes. The box is clearly genuine shadowless era (1999 print run visible on bottom), factory seal intact, no re-wrapping. Aryan provided provenance documentation (original purchase receipt from a US collector) without me even asking. Impeccable seller.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 32,
    reportCount: 0,
    verified: true,
    featured: true,
    sellerReply: "Arjun, this means the world to us. A Shadowless box is one of the rarest items we've ever handled and we treated it accordingly. Provenance documentation is always included for vintage lots — that's just our standard.",
    sellerRepliedAt: daysAgo(40),
    createdAt: daysAgo(42),
    updatedAt: daysAgo(40),
    approvedAt: daysAgo(41),
  },

  {
    id: "review-pokemon-etb-priya-003",
    productId: "product-pokemon-sv-etb",
    productTitle: "Pokémon Scarlet & Violet Paldean Fates Elite Trainer Box",
    sellerId: "user-aryan-kapoor",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 4,
    title: "Great ETB, arrived safely — shipping was a bit slow",
    comment:
      "The ETB was in perfect condition and sealed correctly. I pulled a Shiny Charizard ex which made my week! Shipping took 6 days which is on the longer end, but the packaging was excellent — my only minor complaint. Pokémon Palace is definitely a go-to store.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(27),
    approvedAt: daysAgo(27),
  },

  {
    id: "review-pikachu-plush-meera-004",
    productId: "product-pokemon-pikachu-plush-8",
    productTitle: "Pokémon Pikachu 8-inch Sitting Plush (Official Pokémon Center)",
    sellerId: "user-aryan-kapoor",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    rating: 5,
    title: "Adorable and authentic — tags intact, came with certificate",
    comment:
      "Bought this as a birthday gift for my niece. The plush has the Pokémon Center tag and feels premium — not the cheap knock-offs you see online. Aryan included a small thank-you note which was a lovely touch. Niece went crazy for it. Ordering the Gengar plush next.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 5,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(17),
    approvedAt: daysAgo(17),
  },

  // ── store-cardgame-hub (3 reviews) ────────────────────────────────────────

  {
    id: "review-yugioh-25th-tin-rahul-005",
    productId: "product-yugioh-25th-tin",
    productTitle: "Yu-Gi-Oh! 25th Anniversary Tin: Dueling Heroes",
    sellerId: "user-nisha-reddy",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "Nisha is the best YGO seller in India, period",
    comment:
      "I've ordered from three different YGO sellers on LetItRip and CardGame Hub is on another level. The 25th Anniversary Tin arrived with each mega pack in its own sleeve inside the tin. Nisha also included a handwritten note about recommended first packs to open — genuine community knowledge. Will only order YGO from here going forward.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 22,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(37),
    approvedAt: daysAgo(37),
  },

  {
    id: "review-yugioh-albaz-arjun-006",
    productId: "product-yugioh-structure-albaz",
    productTitle: "Yu-Gi-Oh! Structure Deck: Albaz Strike",
    sellerId: "user-nisha-reddy",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 4,
    title: "Solid structure deck, good beginner product",
    comment:
      "Bought 3 copies to complete a playset as Nisha recommended. Cards came in the original sealed structure deck packaging with no damage. Shipping was 4 days which is perfectly fine for a standard order. Would rate 5 stars if shipping was 2 days but that's a minor point.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 6,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(21),
    approvedAt: daysAgo(21),
  },

  {
    id: "review-charizard-auction-priya-007",
    productId: "auction-pokemon-charizard-base1-psa9",
    productTitle: "Pokémon 1st Edition Charizard PSA 9 (AUCTION)",
    sellerId: "user-nisha-reddy",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 3,
    title: "Card is beautiful but auction process was stressful",
    comment:
      "The card itself is perfect — genuine PSA 9, certificate verified on PSA website. Shipping was excellent (insured, signature required). My 3-star is about the bidding experience: I was outbid in the last 60 seconds three times before winning, which was nerve-wracking. That's a platform issue, not the seller's fault. Card arrived safely and I'm thrilled to own it.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 4,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
    approvedAt: daysAgo(11),
  },

  // ── store-diecast-depot (3 reviews) ───────────────────────────────────────

  {
    id: "review-redline-camaro-meera-008",
    productId: "product-hot-wheels-redline-1969-camaro",
    productTitle: "Hot Wheels Redline 1969 Camaro SS — Custom Paint (Bluebird)",
    sellerId: "user-vikram-mehta",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    rating: 5,
    title: "A true Redline beauty — mint condition, authentic",
    comment:
      "This was my first vintage Hot Wheels purchase and Vikram made it a great experience. The Redline arrived in a proper acrylic display case (not just a ziplock — a real display case!) with a card describing the car's production year and rarity. Vikram's description was honest — the car has minor paint wear on the roof which he mentioned in the listing. Very happy.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(48),
    updatedAt: daysAgo(47),
    approvedAt: daysAgo(47),
  },

  {
    id: "review-tomica-datsun-rahul-009",
    productId: "product-tomica-limited-datsun",
    productTitle: "Tomica Limited Vintage Datsun Bluebird 1600SSS (1969)",
    sellerId: "user-vikram-mehta",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "TLV quality is unreal — every detail perfect",
    comment:
      "I've been collecting Hot Wheels for years but Tomica Limited Vintage is something else entirely. The Datsun Bluebird has rubber tyres, a working bonnet, and tampo print so fine I need a magnifying glass to appreciate it. Vikram sourced this from his Japan trip — you can tell it's fresh stock. Arrived in the original TLV outer box in immaculate condition.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 19,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(34),
    approvedAt: daysAgo(34),
  },

  {
    id: "review-hw-rlc-boneshaker-arjun-010",
    productId: "product-hot-wheels-rlc-bone-shaker",
    productTitle: "Hot Wheels RLC Bone Shaker Special Edition",
    sellerId: "user-vikram-mehta",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 4,
    title: "Rare RLC exclusive, good price, slightly late dispatch",
    comment:
      "The RLC Bone Shaker is exactly as described — sealed in the original RLC mailer with the membership card insert. My only feedback: dispatch was on day 3 (not day 2 as listed in store policy). Vikram apologised proactively and offered a discount on my next order, which I appreciate. Car itself is perfect.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 7,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(19),
    approvedAt: daysAgo(19),
  },

  // ── store-beyblade-arena (3 reviews) ─────────────────────────────────────

  {
    id: "review-bx01-dran-sword-priya-011",
    productId: "product-beyblade-x-bx01-dran-sword",
    productTitle: "Beyblade X BX-01 Dran Sword 4-60F Starter Set",
    sellerId: "user-rohit-joshi",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 5,
    title: "My son's first BX top — perfect gift, fast delivery",
    comment:
      "Ordered for my 8-year-old who is obsessed with Beyblade X. Rohit shipped the same day I placed the order (I ordered at 10am, it was dispatched by 4pm). Arrived in 3 days. The BX-01 starter set comes with the top, rip cord launcher, and a stadium guide — everything a beginner needs. My son has launched it 200 times and it's still perfect.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 28,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(49),
    approvedAt: daysAgo(49),
  },

  {
    id: "review-b200-valkyrie-meera-012",
    productId: "product-beyblade-burst-b200-valkyrie",
    productTitle: "Beyblade Burst B-200 Brave Valkyrie Evolution",
    sellerId: "user-rohit-joshi",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    rating: 5,
    title: "Authentic Takara Tomy import, not the bootleg version",
    comment:
      "There are SO many bootleg Beyblades on other platforms. Rohit sells only genuine Takara Tomy product — you can tell by the QR code on the Beyblade passport card (scans correctly on the Beyblade app). Brave Valkyrie arrived fresh from its Japan import, unopened. The weight difference from bootlegs is immediately obvious.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 15,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(32),
    updatedAt: daysAgo(31),
    approvedAt: daysAgo(31),
  },

  {
    id: "review-preorder-beyblade-bx10-rahul-013",
    productId: "preorder-beyblade-x-bx10-booster",
    productTitle: "Beyblade X BX-10 Booster Set Pre-Order",
    sellerId: "user-rohit-joshi",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 4,
    title: "Pre-order arrived on time — worth the wait",
    comment:
      "Rohit's pre-order process was smooth. I paid the 30% deposit, received confirmation, and the balance was charged exactly when he said it would be (2 days before dispatch). Item arrived 42 days after ordering — right in the promised window. No complaints. Will pre-order the BX-12 when Rohit lists it.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 9,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(9),
    approvedAt: daysAgo(9),
  },

  // ── store-letitrip-official (2 reviews) ───────────────────────────────────

  {
    id: "review-shf-goku-arjun-014",
    productId: "product-shf-goku-ultra-instinct",
    productTitle: "S.H.Figuarts Goku Ultra Instinct -Sign- (Dragon Ball Super)",
    sellerId: "user-admin-letitrip",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 5,
    title: "Official LetItRip store delivers — SHF in perfect condition",
    comment:
      "This is my 4th S.H.Figuarts from LetItRip Official and they're consistently excellent. The Goku UI comes with 5 face plates, effect parts, and all the swap hands. Every accessory was accounted for (I always check). LetItRip Official is the most reliable store on the platform — their QC before dispatch is clearly thorough.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 17,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(26),
    updatedAt: daysAgo(25),
    approvedAt: daysAgo(25),
  },

  {
    id: "review-gundam-rx78-mg-arjun-015",
    productId: "product-gundam-rx78-mg",
    productTitle: "MG 1/100 RX-78-2 Gundam Ver. 3.0",
    sellerId: "user-admin-letitrip",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 2,
    title: "Kit was missing the beam rifle assembly — resolved via support",
    comment:
      "The box arrived safely but when I inventoried the sprues, the G runner (beam rifle parts) was missing — looks like a factory packing error. I opened a dispute on LetItRip and LetItRip Official resolved it within 48 hours by shipping the missing runner separately at no cost. They clearly take after-sales seriously. Updating from 1 star to 2 stars because the issue was resolved, but losing a star for the missing part.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 6,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(12),
    approvedAt: daysAgo(12),
  },

  // ── store-tokyo-toys-india (5 reviews) ────────────────────────────────────

  {
    id: "review-nendoroid-zero-two-sneha-016",
    productId: "product-nendoroid-zero-two",
    productTitle: "Nendoroid Zero Two (Darling in the FranXX) #942",
    sellerId: "user-priya-singh",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 5,
    title: "Zero Two is everything I dreamed of — authentic GSC, flawless",
    comment:
      "I've been hunting this Nendoroid for 2 years and finally found it at Tokyo Toys India. Priya sourced the re-release directly from GSC. The serial number on the base matches the box — definitely authentic. Three faceplates, the horns are perfect, and the stand works smoothly. Packed in foam-padded box, arrived in 3 days. Priya is the real deal — she knows her anime figures.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 24,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(44),
    approvedAt: daysAgo(44),
  },

  {
    id: "review-nendoroid-levi-tanvi-017",
    productId: "product-nendoroid-levi-aot",
    productTitle: "Nendoroid Levi Ackerman (Attack on Titan) #390",
    sellerId: "user-priya-singh",
    userId: "user-tanvi-desai",
    userName: "Tanvi Desai",
    rating: 5,
    title: "Cleaning mode faceplate alone is worth it — perfect figure",
    comment:
      "The cleaning mode Levi faceplate with the tiny mop is the most charming thing I own. Priya's packaging was impeccable — each faceplate in its own mini tray exactly as GSC intended. This is my 6th Nendoroid from Tokyo Toys India and Priya has never once let me down. Already eyeing the Ram Nendoroid on her store.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 18,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(37),
    approvedAt: daysAgo(37),
  },

  {
    id: "review-shf-sailor-moon-sneha-018",
    productId: "product-shf-sailor-moon-eternal",
    productTitle: "S.H.Figuarts Sailor Moon Eternal (2021)",
    sellerId: "user-priya-singh",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 5,
    title: "Rainbow wings are breathtaking — showpiece figure",
    comment:
      "The rainbow semi-translucent wings on this figure catch light in ways that my photos simply cannot capture. When sunlight hits them, the entire shelf lights up. Priya had this in stock while every other seller was out — she clearly has excellent supplier relationships. Arrived double-boxed, wings were in a separate padded compartment. No damage. 10/10.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 31,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(29),
    updatedAt: daysAgo(28),
    approvedAt: daysAgo(28),
  },

  {
    id: "review-funko-pop-tanjiro-tanvi-019",
    productId: "product-funko-pop-tanjiro-demon-slayer",
    productTitle: "Funko Pop! Tanjiro Kamado (Demon Slayer) #855",
    sellerId: "user-priya-singh",
    userId: "user-tanvi-desai",
    userName: "Tanvi Desai",
    rating: 4,
    title: "Perfect mint on card — Priya's packaging keeps boxes pristine",
    comment:
      "I collect Funko Pops for display out of box BUT I keep a carded mint copy for investment. Priya packs each Pop in a protector sleeve before shipping — the box arrived with zero corner wear. That level of care for a ₹1,699 Funko is impressive. Deducting one star only because dispatch was Day 2 instead of Day 1 (she mentioned a supply arrival delay in her dispatch message).",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 12,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(19),
    approvedAt: daysAgo(19),
  },

  {
    id: "review-racing-miku-priya-patel-020",
    productId: "product-gsc-racing-miku-2023",
    productTitle: "Good Smile Racing Miku 2023 Ver. 1/7 Scale",
    sellerId: "user-priya-singh",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 5,
    title: "Centrepiece of my collection — absolutely stunning 1/7 scale",
    comment:
      "Racing Miku 2023 Ver. is the most beautiful figure I own. The 1/7 scale means she stands tall on my shelf and catches everyone's eye. Priya sourced this from Akihabara directly — the box has the Japanese tax receipt inside. She packed the figure's base separately with foam and the wings were in bubble wrap. Nothing moved in transit. Worth every rupee.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 26,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
    approvedAt: daysAgo(11),
  },

  // ── store-gundam-galaxy (4 reviews) ──────────────────────────────────────

  {
    id: "review-hg-barbatos-kartik-021",
    productId: "product-gundam-hg-barbatos-lupus-rex",
    productTitle: "HG 1/144 Gundam Barbatos Lupus Rex (Iron-Blooded Orphans)",
    sellerId: "user-amit-sharma",
    userId: "user-kartik-nair",
    userName: "Kartik Nair",
    rating: 5,
    title: "First Gunpla ever — Amit's advice helped me pick the right kit",
    comment:
      "I messaged Amit before ordering asking which HG is best for a complete beginner. He replied within an hour with a detailed breakdown of the top 5 beginner HG kits and explained why Barbatos Lupus Rex is the best mix of posability and fun. Great advice — the build took me a weekend and the result is spectacular. Amit is clearly a passionate builder and that shows in how he sells.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 34,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(52),
    updatedAt: daysAgo(51),
    approvedAt: daysAgo(51),
  },

  {
    id: "review-mg-sazabi-arjun-022",
    productId: "product-gundam-mg-sazabi-verka",
    productTitle: "MG 1/100 Sazabi Ver.Ka (Master Grade)",
    sellerId: "user-amit-sharma",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 5,
    title: "The pinnacle of Master Grade — Amit's packaging was museum-grade",
    comment:
      "This is the most expensive kit I've ever bought (₹6,499) and Amit treated it accordingly. The Sazabi Ver.Ka arrived triple-boxed — outer cardboard, foam insert, and the kit box itself inside a second layer of rigid cardboard. Every runner individually wrapped. The kit itself is exactly as legendary as its reputation — 300+ parts, three-layer construction, and the most satisfying snap-fit engineering I've ever experienced. Amit is the best Gunpla seller in India.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 42,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(39),
    approvedAt: daysAgo(39),
  },

  {
    id: "review-rg-evangelion-sneha-023",
    productId: "product-gundam-rg-evangelion-unit01",
    productTitle: "RG 1/144 Evangelion Unit-01 (Rebuild of Evangelion)",
    sellerId: "user-amit-sharma",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 4,
    title: "EVA-01 in RG is spectacular — pre-coloured runners are a revelation",
    comment:
      "I'm not a regular Gunpla buyer but bought this for my EVA collection. Amit's store description mentioned that this is the first non-Gundam RG kit and the pre-coloured runners make it accessible for non-modellers. He was right — I built it with no paint and it looks exactly like the promo photos. Deducting one star because the umbilical cable tends to pop off at the connection point, but that's a Bandai design note, not Amit's fault.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 16,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(27),
    updatedAt: daysAgo(26),
    approvedAt: daysAgo(26),
  },

  {
    id: "review-rg-hi-nu-preorder-kartik-024",
    productId: "preorder-gundam-rg-hi-nu-verka",
    productTitle: "PRE-ORDER: RG 1/144 Hi-ν Gundam Ver.Ka",
    sellerId: "user-amit-sharma",
    userId: "user-kartik-nair",
    userName: "Kartik Nair",
    rating: 5,
    title: "Pre-order process is smooth — Amit updates you at every step",
    comment:
      "Placed this pre-order and Amit messaged me the same day confirming receipt, then sent weekly updates on Japan warehouse status. He also warned me about a potential 2-week delay due to Bandai production schedules before I even knew about it publicly. That level of proactive communication is rare. Kit hasn't arrived yet but the deposit process was seamless.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 8,
    reportCount: 0,
    verified: false,
    featured: false,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    approvedAt: daysAgo(4),
  },

  // ── store-vintage-vault (4 reviews) ──────────────────────────────────────

  {
    id: "review-pokemon-charizard-lp-divya-025",
    productId: "product-vintage-pokemon-charizard-base-lp",
    productTitle: "Pokémon Base Set Charizard #4/102 Holo Rare — LP Raw",
    sellerId: "user-kavya-iyer",
    userId: "user-divya-menon",
    userName: "Divya Menon",
    rating: 5,
    title: "Honest condition grading — exactly what she described",
    comment:
      "I was nervous buying a ₹3,999 Charizard online but Kavya sent me 8 high-res photos in different lighting before I confirmed. The card matches her LP description exactly — the corners and whitening are exactly as documented. She's been in this business 20 years and her grading vocabulary is precise. Most sellers say 'Near Mint' for LP cards — Kavya says LP for LP. Refreshing honesty.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 29,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(34),
    approvedAt: daysAgo(34),
  },

  {
    id: "review-hw-deora-vintage-siddharth-026",
    productId: "product-vintage-hot-wheels-deora-1968",
    productTitle: "Hot Wheels Redline 1968 Deora — Aqua (Vintage)",
    sellerId: "user-kavya-iyer",
    userId: "user-siddharth-rao",
    userName: "Siddharth Rao",
    rating: 5,
    title: "A piece of toy history — Kavya's knowledge is unmatched",
    comment:
      "I collect vintage Redlines and Kavya is the first Indian seller I've found who truly understands them. Her listing for the Deora was the most detailed I've seen anywhere — she identified it as an early production run based on the chassis stamp. The provenance documentation (original owner paperwork) is extraordinary. This car is now the centrepiece of my collection.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 21,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(23),
    updatedAt: daysAgo(22),
    approvedAt: daysAgo(22),
  },

  {
    id: "review-motu-he-man-rahul-027",
    productId: "product-vintage-motu-he-man-1982",
    productTitle: "Masters of the Universe He-Man (1982 Takara Japan)",
    sellerId: "user-kavya-iyer",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "My childhood hero — and a genuine 1982 first-year original",
    comment:
      "I grew up with He-Man but never had an original 1982 figure. When I saw Kavya's listing with the Takara sticker on the packaging, I knew it was legitimate — that detail is how you identify the Japan distribution version. She included a certificate of authenticity from a vintage toy appraiser. The torso twist mechanism works perfectly after 40+ years. Remarkable condition for the age.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 15,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(13),
    approvedAt: daysAgo(13),
  },

  {
    id: "review-jungle-vaporeon-tanvi-028",
    productId: "product-vintage-pokemon-jungle-vaporeon-holo",
    productTitle: "Pokémon WOTC Jungle Vaporeon #12/64 Holo Rare — NM Raw",
    sellerId: "user-kavya-iyer",
    userId: "user-tanvi-desai",
    userName: "Tanvi Desai",
    rating: 5,
    title: "WOTC era quality is incomparable — Kavya preserves history",
    comment:
      "I'm building a raw NM WOTC set and Kavya's Vintage Vault has the cleanest WOTC cards I've found in India. The Vaporeon has the original First Edition-era card stock texture that WOTC used before they cheapened the material in later sets. Holo is perfect. Kavya's estate-sale sourcing means these cards have been in private collections — not through dealer hands repeatedly.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
    approvedAt: daysAgo(6),
  },

  // ── Additional reviews across existing stores (new buyers) ────────────────

  {
    id: "review-pokemon-151-box-sneha-029",
    productId: "product-pokemon-151-booster-box",
    productTitle: "Pokémon 151 Booster Box (Sealed)",
    sellerId: "user-aryan-kapoor",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 5,
    title: "Investment-grade sealed product — Aryan's sourcing is legit",
    comment:
      "Bought the 151 booster box for long-term storage. The shrink wrap is tight with no air gaps (sign of authentic factory sealing). Aryan included a UK distributor invoice confirming the source — that level of documentation is exceptional. Box is now in my climate-controlled storage. When I eventually open it, I'll update this review with pull results.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 13,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(29),
    approvedAt: daysAgo(29),
  },

  {
    id: "review-yugioh-phantom-nightmare-siddharth-030",
    productId: "product-yugioh-phantom-nightmare-box",
    productTitle: "Yu-Gi-Oh! Phantom Nightmare Booster Box (24 Packs)",
    sellerId: "user-nisha-reddy",
    userId: "user-siddharth-rao",
    userName: "Siddharth Rao",
    rating: 5,
    title: "Hit a Fiendsmith Engraver UR — best opening of 2024",
    comment:
      "Ordered the Phantom Nightmare box for the Fiendsmith engine cards. Nisha had it at ₹5,999 when other sellers were charging ₹6,499 for the same product — she's clearly competitive on pricing. Box arrived factory sealed, split into two lots of 12 packs each inside the cardboard insert. Opened all 24 packs, hit the Fiendsmith Engraver Ultra Rare, two Snake-Eye Ash Secret Rares, and a complete Rescue-Ace suite. Excellent pull rate.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 22,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(17),
    approvedAt: daysAgo(17),
  },

  {
    id: "review-beyblade-xstadium-ankit-031",
    productId: "product-beyblade-x-xstadium-official",
    productTitle: "Beyblade X BX-08 XStadium (Official Takara Tomy)",
    sellerId: "user-rohit-joshi",
    userId: "user-ankit-gupta",
    userName: "Ankit Gupta",
    rating: 5,
    title: "Tournament quality — arrived well before my regional event",
    comment:
      "I needed this stadium for our city's Beyblade X regional. Rohit had it in stock when every other platform was out. Ordered Monday morning, arrived Thursday — with 2 days to spare before the event. The XStadium is the real tournament-spec — the X-Line rail is perfectly calibrated and the floor has no warping. Won my bracket. 10/10 seller.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 19,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(14),
    approvedAt: daysAgo(14),
  },

  {
    id: "review-sth-dodge-viper-siddharth-032",
    productId: "product-hot-wheels-sth-dodge-viper",
    productTitle: "Hot Wheels Super Treasure Hunt Dodge Viper SRT10 (STH)",
    sellerId: "user-vikram-mehta",
    userId: "user-siddharth-rao",
    userName: "Siddharth Rao",
    rating: 5,
    title: "Confirmed STH — Spectraflame is glorious, card is mint",
    comment:
      "Vikram's listing said 'immediately cased after retail pull' and that is exactly what arrived — you can see the factory crimp on the blister is undisturbed. The Spectraflame Red on this Viper is one of the deepest metallic finishes I've seen on a recent STH. Card is flat, no corner wear, graphic is crisp. This is a ₹2,999 car that will be worth ₹8,000 in a decade. Vikram knows his product.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 17,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
    approvedAt: daysAgo(7),
  },

  {
    id: "review-neca-tmnt-divya-033",
    productId: "product-neca-tmnt-4figure-set",
    productTitle: "NECA TMNT Classic 1990 Movie 4-Figure Set",
    sellerId: "user-admin-letitrip",
    userId: "user-divya-menon",
    userName: "Divya Menon",
    rating: 5,
    title: "The childhood dream — all 4 Turtles in one box, museum quality",
    comment:
      "I grew up watching the 1990 TMNT movie and this set made me feel like a kid again. The film-suit sculpts are extraordinary — you can see the texture of the foam rubber suits translated into articulated plastic. LetItRip Official packed the set in a rigid outer casing inside a foam-padded bag inside the shipping box. Three layers of protection for a ₹12,999 set. That's how it should be done.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 27,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
    approvedAt: daysAgo(5),
  },

  {
    id: "review-mg-sazabi-verka-kartik-034",
    productId: "product-gundam-mg-sazabi-verka",
    productTitle: "MG 1/100 Sazabi Ver.Ka",
    sellerId: "user-amit-sharma",
    userId: "user-kartik-nair",
    userName: "Kartik Nair",
    rating: 5,
    title: "Graduation kit from HG to MG — Amit guided me through it",
    comment:
      "After my Barbatos Lupus Rex HG build, I wanted to try Master Grade. I messaged Amit asking if Sazabi Ver.Ka is too advanced for a second build. He was honest — he said it's challenging but doable if you take your time, and he offered to share his build guide PDF. I took 3 weeks to build it and it's perfect. Amit genuinely cares about his customers having a great build experience.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 9,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    approvedAt: daysAgo(2),
  },

  {
    id: "review-pokemon-etb-temporal-ankit-035",
    productId: "product-pokemon-sv-temporal-forces-etb",
    productTitle: "Pokémon TCG: Temporal Forces Elite Trainer Box",
    sellerId: "user-aryan-kapoor",
    userId: "user-ankit-gupta",
    userName: "Ankit Gupta",
    rating: 4,
    title: "Great ETB, good pulls — would prefer faster dispatch",
    comment:
      "Temporal Forces ETB arrived in great condition — sealed correctly, no box damage. Pulled an Iron Leaves ex SAR on pack 4 which more than covered the cost. My only note: dispatch was on Day 3 (I ordered Sunday and it was dispatched Wednesday). Aryan's shipping info says 24-hour dispatch which wasn't met. Dropping one star for that. Card quality and packaging: 5 stars.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 6,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    approvedAt: daysAgo(1),
  },

  // ── New reviews 36–60 — expanded seed scale ──────────────────────────────

  // store-pokemon-palace (5 more)
  {
    id: "review-surging-sparks-box-anjali-036",
    productId: "product-pokemon-surging-sparks-booster",
    productTitle: "Pokémon TCG: Surging Sparks Booster Box",
    sellerId: "user-aryan-kapoor",
    userId: "user-anjali-verma",
    userName: "Anjali Verma",
    rating: 5,
    title: "Incredible box — pulled Pikachu ex SAR on the 4th pack",
    comment: "Ordered Sunday afternoon, dispatched Monday morning. Box arrived double-wrapped in bubble pack inside a snug shipper box. Seal was 100% intact. I pulled a Pikachu ex SAR on pack 4 and lost my mind. Aryan texted to confirm delivery — that personal touch goes a long way. Highly recommended.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 21,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(33),
    updatedAt: daysAgo(32),
    approvedAt: daysAgo(32),
  },
  {
    id: "review-151-etb-rohit-037",
    productId: "product-pokemon-151-etb",
    productTitle: "Pokémon TCG: Scarlet & Violet — 151 Elite Trainer Box",
    sellerId: "user-aryan-kapoor",
    userId: "user-rohit-verma",
    userName: "Rohit Verma",
    rating: 5,
    title: "Best ETB I've bought — zero issues, great seal",
    comment: "This was my third ETB from Pokémon Palace and the experience is consistently flawless. Box came in a heavy shipper with foam corners. The 151 ETB seal is known to be finicky (the flap can come loose in transit) but Aryan had taped the inner flap additionally — smart move. Pulled Charizard ex SIR on pack 7. 10/10.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 17,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(27),
    updatedAt: daysAgo(26),
    approvedAt: daysAgo(26),
  },
  {
    id: "review-charizard-sar-naman-038",
    productId: "product-pokemon-charizard-ex-sar-sv",
    productTitle: "Pokémon TCG: Charizard ex — Special Illustration Rare",
    sellerId: "user-aryan-kapoor",
    userId: "user-naman-gupta",
    userName: "Naman Gupta",
    rating: 4,
    title: "Genuine NM card, accurate description — arrived safely",
    comment: "Card is exactly as described: NM/M with great centering. Came in penny sleeve + toploader + team bag inside a rigid mailer. I'm planning to get it PSA graded and believe it will grade PSA 9. Slight deduction as the listing photo was slightly different angle from the actual card, but the condition is accurately described. Would buy again.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 9,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    approvedAt: daysAgo(2),
  },
  {
    id: "review-journey-together-etb-kavya-039",
    productId: "product-pokemon-journey-together-etb",
    productTitle: "Pokémon TCG: Journey Together Elite Trainer Box",
    sellerId: "user-aryan-kapoor",
    userId: "user-kavya-nair",
    userName: "Kavya Nair",
    rating: 5,
    title: "Factory fresh — exactly as expected from Pokémon Palace",
    comment: "Consistent five-star experience from Aryan. Journey Together ETB is genuinely one of the nicest ETB boxes in years — the sleeve design is gorgeous. Packs were fresh, no pack-weighed pulls removed. This is a store I trust completely.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(13),
    approvedAt: daysAgo(13),
  },
  {
    id: "review-mewtwo-sar-siddharth-040",
    productId: "product-pokemon-mewtwo-ex-sar-sv",
    productTitle: "Pokémon TCG: Mewtwo ex — Special Illustration Rare",
    sellerId: "user-aryan-kapoor",
    userId: "user-siddharth-mehta",
    userName: "Siddharth Mehta",
    rating: 5,
    title: "One of the best SIRs in the 151 set — perfect condition",
    comment: "Mewtwo ex SIR is stunning in person. Photos on the listing don't do it justice. Card is NM, corners are sharp, no whitening visible. Protected extremely well in transit. Aryan included a personal note in the package — rare touch from a marketplace seller. Fantastic.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 12,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
    approvedAt: daysAgo(5),
  },

  // store-cardgame-hub (5 more)
  {
    id: "review-op06-box-rohit-041",
    productId: "product-onepiece-op06-booster-box",
    productTitle: "One Piece Card Game: OP-06 Wings of the Captain Booster Box",
    sellerId: "user-nisha-reddy",
    userId: "user-rohit-verma",
    userName: "Rohit Verma",
    rating: 5,
    title: "Sealed box, excellent pulls — Whitebeard SR in pack 3",
    comment: "CardGame Hub dispatched within a day. Box was sealed beautifully in shrink wrap, original Bandai seal untouched. My first OP-06 box and I pulled the Whitebeard SR in pack 3. Nisha even messaged to check I received it safely. Exceptional seller and I'll be back for every new OP set.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 18,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(27),
    updatedAt: daysAgo(26),
    approvedAt: daysAgo(26),
  },
  {
    id: "review-blue-eyes-lob-neha-042",
    productId: "product-yugioh-blue-eyes-lob-nm",
    productTitle: "Yu-Gi-Oh! Blue-Eyes White Dragon — LOB 1st Edition (NM)",
    sellerId: "user-nisha-reddy",
    userId: "user-neha-gupta",
    userName: "Neha Gupta",
    rating: 5,
    title: "Incredible 1st Ed BEWD — better condition than the photos show",
    comment: "I've been hunting for a high-grade 1st Edition LOB Blue-Eyes for two years. This one from CardGame Hub exceeded my expectations — corners are sharper than the photos suggest, surface gloss is perfect. Submitting to PSA this week. Nisha was responsive to all my questions before purchase. Couldn't be happier.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 24,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(21),
    approvedAt: daysAgo(21),
  },
  {
    id: "review-25th-anniversary-tin-arjun-043",
    productId: "product-yugioh-25th-anniversary-tin",
    productTitle: "Yu-Gi-Oh! 25th Anniversary Tin: Dueling Heroes",
    sellerId: "user-nisha-reddy",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 4,
    title: "Great tin, solid pulls — packaging could have been better",
    comment: "The 25th Anniversary Tin is gorgeous — the embossed design is premium. Got an Ultra Rare Dark Magician as the guaranteed card, which is ideal. My only note is that the outer box wasn't padded very well; the tin corners took a small dent from shipping. Card contents were fine. Four stars — would use more padding next time.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 7,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(17),
    approvedAt: daysAgo(17),
  },
  {
    id: "review-op05-box-vikram-044",
    productId: "product-onepiece-op05-booster-box",
    productTitle: "One Piece Card Game: OP-05 Awakening of the New Era Booster Box",
    sellerId: "user-nisha-reddy",
    userId: "user-vikram-rao",
    userName: "Vikram Rao",
    rating: 5,
    title: "Sealed correctly, great communication — would repeat",
    comment: "I was skeptical buying a sealed box online but CardGame Hub's reputation and LetItRip's escrow gave me confidence. Box arrived with original Bandai shrink intact. Nisha sent dispatch notification with tracking within hours. Solid buying experience.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(9),
    approvedAt: daysAgo(9),
  },
  {
    id: "review-dark-magician-psa9-divya-045",
    productId: "product-yugioh-dark-magician-lob-psa9",
    productTitle: "Yu-Gi-Oh! Dark Magician — LOB 1st Edition PSA 9",
    sellerId: "user-nisha-reddy",
    userId: "user-divya-reddy",
    userName: "Divya Reddy",
    rating: 5,
    title: "Dream card — PSA 9 slab arrived in perfect shape",
    comment: "This was my biggest single purchase on LetItRip and I'm glad it was from CardGame Hub. The PSA slab came in a foam-fitted inner box with bubble wrap all round. The cert number verified on PSA's site immediately. Dark Magician in a 1st Ed PSA 9 is a piece of Yu-Gi-Oh history. Absolutely worth every rupee.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 29,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
    approvedAt: daysAgo(11),
  },

  // store-diecast-depot (5 more)
  {
    id: "review-rlc-porsche-anjali-046",
    productId: "product-hot-wheels-rlc-porsche-918",
    productTitle: "Hot Wheels RLC Exclusive: Porsche 918 Spyder — Spectraflame White",
    sellerId: "user-vikram-mehta",
    userId: "user-anjali-verma",
    userName: "Anjali Verma",
    rating: 5,
    title: "RLC Porsche in mint condition — great packaging",
    comment: "I collect Hot Wheels RLC releases and they're notoriously hard to find in India. Diecast Depot had stock and shipped it in the original RLC mailer inside a padded outer box. Card is perfectly flat, Spectraflame finish is immaculate. Vikram answered all my questions about provenance. Five stars.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 15,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(14),
    approvedAt: daysAgo(14),
  },
  {
    id: "review-tomica-lc300-pooja-047",
    productId: "product-tomica-land-cruiser-300",
    productTitle: "Tomica: Toyota Land Cruiser 300 (No. 107)",
    sellerId: "user-vikram-mehta",
    userId: "user-pooja-sharma",
    userName: "Pooja Sharma",
    rating: 5,
    title: "Perfect Tomica — excellent gift packaging",
    comment: "Bought 3 of these as gifts for my nephews. All three arrived in original Tomica boxes, no crushing or damage. The LC300 detail is fantastic for a 1:64. Each car was bubble-wrapped individually even though they were in one order. Really thoughtful packaging from Diecast Depot.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 10,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(16),
    approvedAt: daysAgo(16),
  },
  {
    id: "review-car-culture-german-vikram-048",
    productId: "product-hot-wheels-car-culture-german",
    productTitle: "Hot Wheels Car Culture: German Cars & Coffee (5-Car Set)",
    sellerId: "user-vikram-mehta",
    userId: "user-vikram-rao",
    userName: "Vikram Rao",
    rating: 4,
    title: "Lovely Car Culture set — one car slightly dusty in package",
    comment: "The German Cars & Coffee set is one of the best Car Culture assortments Mattel has produced. Real Riders on all five cars and the BMW M3 E30 is the standout. My only complaint: the Audi RS5 in the set had visible dust inside the blister pack — looks like a factory quality issue, not the seller's fault. Diecast Depot was responsive when I mentioned it.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
    approvedAt: daysAgo(7),
  },
  {
    id: "review-corgi-db5-kiran-049",
    productId: "product-corgi-aston-martin-db5",
    productTitle: "Corgi: Aston Martin DB5 — James Bond 007 Edition",
    sellerId: "user-vikram-mehta",
    userId: "user-kiran-reddy",
    userName: "Kiran Reddy",
    rating: 5,
    title: "Iconic Bond car — all gadgets work, display piece of the year",
    comment: "Corgi's DB5 is the definitive toy for James Bond fans. The ejector seat mechanism works perfectly, the revolving plates click satisfyingly, and the Spectraflame silver finish is gorgeous. Diecast Depot packed it in the original presentation box inside a custom foam-padded shipper. This is now the centrepiece of my display shelf.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 19,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    approvedAt: daysAgo(2),
  },
  {
    id: "review-civic-type-r-naman-050",
    productId: "product-tomica-civic-type-r-fl5",
    productTitle: "Tomica: Honda Civic Type R FL5 (No. 29)",
    sellerId: "user-vikram-mehta",
    userId: "user-naman-gupta",
    userName: "Naman Gupta",
    rating: 5,
    title: "The FL5 in 1:64 — brilliant detail for the price",
    comment: "Own the real FL5 and bought the Tomica to put on my desk. The proportions are spot on — Tomica's FL5 is significantly more accurate than the Hot Wheels version. Arrives in original box, mint. Diecast Depot's packaging is always reliable. Fast shipping too.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 13,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(8),
    approvedAt: daysAgo(8),
  },

  // store-beyblade-arena (3 more)
  {
    id: "review-bx01-dran-sword-preeti-051",
    productId: "product-beyblade-x-bx01-dran-sword",
    productTitle: "Beyblade X: BX-01 Dran Sword 3-60F",
    sellerId: "user-rohit-joshi",
    userId: "user-preeti-joshi",
    userName: "Preeti Joshi",
    rating: 5,
    title: "Perfect intro kit for Beyblade X — great for kids and adults",
    comment: "Bought 2 of these as a birthday gift combo. Rohit packed each one individually in bubble wrap. My nephew's face when he opened these was priceless. The Xtreme Dash mechanic on the X-format is genuinely exciting. Beyblade Arena is the go-to store for X-format in India.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 14,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    approvedAt: daysAgo(2),
  },
  {
    id: "review-bx07-hells-chain-ananya-052",
    productId: "product-beyblade-x-bx07-hells-chain",
    productTitle: "Beyblade X: BX-07 Hells Chain 5-60HT",
    sellerId: "user-rohit-joshi",
    userId: "user-ananya-krishna",
    userName: "Ananya Krishna",
    rating: 5,
    title: "Dominating stamina Bey — won my first local tournament with it",
    comment: "Hells Chain is the best stamina Bey in the current X format. Rohit shipped it fast and it arrived in original packaging. I won my first local LetItRip club tournament with this — the HT driver just refuses to stop spinning. Beyblade Arena is the best store for serious bladers.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 22,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(54),
    approvedAt: daysAgo(54),
  },
  {
    id: "review-bx16-launcher-siddharth-053",
    productId: "product-beyblade-x-bx16-sword-launcher",
    productTitle: "Beyblade X: BX-16 Sword Launcher",
    sellerId: "user-rohit-joshi",
    userId: "user-siddharth-mehta",
    userName: "Siddharth Mehta",
    rating: 4,
    title: "Great launcher, solid grip — small delay in dispatch",
    comment: "The BX-16 Sword Launcher is a significant upgrade over the included ripcord launchers. Grip angle control makes a real difference in competitive launches. Arrived intact. Dispatch was 3 days after order (listed as 2 days) — minor inconvenience. The launcher itself: full marks.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 6,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
    approvedAt: daysAgo(6),
  },

  // store-letitrip-official (4 more)
  {
    id: "review-figma-link-totk-naman-054",
    productId: "product-figma-link-totk",
    productTitle: "figma: The Legend of Zelda: Tears of the Kingdom — Link",
    sellerId: "user-admin-letitrip",
    userId: "user-naman-gupta",
    userName: "Naman Gupta",
    rating: 5,
    title: "Best figma I own — every accessory accounted for, perfect box",
    comment: "LetItRip Official is where I buy all my premium figures. The figma Link TotK is Max Factory at their best — articulation is incredible and the Ultrahand accessories are a lovely touch for TotK fans. Box arrived in a shipper with foam on all six sides. Not a single accessory missing. The photoshoot I did with this figure after unboxing got 400 likes on Instagram.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 26,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(44),
    updatedAt: daysAgo(43),
    approvedAt: daysAgo(43),
  },
  {
    id: "review-mafex-miles-rohan-055",
    productId: "product-mafex-miles-morales-spiderman",
    productTitle: "MAFEX No.240: Miles Morales Spider-Man",
    sellerId: "user-admin-letitrip",
    userId: "user-rohan-joshi",
    userName: "Rohan Joshi",
    rating: 5,
    title: "MAFEX quality is unmatched — Miles looks incredible on shelf",
    comment: "MAFEX figures are a premium buy and I needed to know LetItRip Official would handle the shipping correctly. They absolutely did — foam-lined shipper, original Medicom box in perfect shape. The figure itself is phenomenal: fabric suit texture, 12 web effect parts, 3 faceplates. Miles Morales has never looked better. This is the definitive Miles figure.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 33,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    approvedAt: daysAgo(1),
  },
  {
    id: "review-nendo-miku-v4x-pooja-056",
    productId: "product-nendoroid-hatsune-miku-v4x",
    productTitle: "Nendoroid: Hatsune Miku V4X",
    sellerId: "user-admin-letitrip",
    userId: "user-pooja-sharma",
    userName: "Pooja Sharma",
    rating: 5,
    title: "My first Nendoroid — couldn't have chosen a better store",
    comment: "As a first-time Nendoroid buyer I was nervous about getting a genuine GSC product. LetItRip Official made it easy — the box has all the Japanese and English authentication marks, the figure quality is incredible. Miku V4X is the perfect starter Nendoroid. The leek accessory made me laugh. Excellent from start to finish.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 16,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(37),
    updatedAt: daysAgo(36),
    approvedAt: daysAgo(36),
  },
  {
    id: "review-funko-gojo-kavya-057",
    productId: "product-funko-pop-gojo-satoru",
    productTitle: "Funko Pop! Animation: Jujutsu Kaisen — Gojo Satoru #1373",
    sellerId: "user-admin-letitrip",
    userId: "user-kavya-nair",
    userName: "Kavya Nair",
    rating: 5,
    title: "Mint box, quick delivery — Gojo looks great in blindfold",
    comment: "Ordered on Friday, arrived Tuesday — that's excellent for Kerala. Funko box had a protector sleeve on it and was in a padded mailer. Zero dents or crushes. Gojo's blindfold design is so much better than some of the unmasked variants. Perfect gift for my JJK fan friend.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
    approvedAt: daysAgo(11),
  },

  // store-tokyo-toys-india (3 more)
  {
    id: "review-alter-rem-wedding-anjali-058",
    productId: "product-alter-rem-wedding-scale",
    productTitle: "ALTER: Re:ZERO — Rem (Wedding Ver.) 1/7 Scale Figure",
    sellerId: "user-priya-singh",
    userId: "user-anjali-verma",
    userName: "Anjali Verma",
    rating: 5,
    title: "ALTER quality is another level — this figure is breathtaking",
    comment: "My most expensive figure purchase to date and absolutely worth it. ALTER's Rem Wedding Ver. is spectacular — the lace on the dress has visible weave texture, the bouquet flowers are individually painted, and the expression sculpt is perfect. Tokyo Toys India shipped in a double-box with foam cut to the figure's exact shape. Pristine arrival. I cried a little.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 35,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(34),
    updatedAt: daysAgo(33),
    approvedAt: daysAgo(33),
  },
  {
    id: "review-gsc-aqua-ananya-059",
    productId: "product-gsc-aqua-konosuba-scale",
    productTitle: "Good Smile Company: KonoSuba — Aqua 1/7 Scale Figure",
    sellerId: "user-priya-singh",
    userId: "user-ananya-krishna",
    userName: "Ananya Krishna",
    rating: 5,
    title: "Aqua deserves all the praise — this figure is stunning",
    comment: "The Aqua 1/7 scale from GSC captures her personality perfectly. The water effect base is translucent blue with shimmer built into the plastic — it looks magical in direct light. Tokyo Toys India's packaging was impeccable: foam form-fitting inserts, zero movement in the box. Figure arrived in showroom condition. Priya also included a polishing cloth — thoughtful.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 28,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(59),
    updatedAt: daysAgo(58),
    approvedAt: daysAgo(58),
  },
  {
    id: "review-nendo-zero-two-siddharth-060",
    productId: "product-nendoroid-zero-two-darling",
    productTitle: "Nendoroid: DARLING in the FRANXX — Zero Two #952",
    sellerId: "user-priya-singh",
    userId: "user-siddharth-mehta",
    userName: "Siddharth Mehta",
    rating: 3,
    title: "Great figure but one faceplate had a paint defect — resolved",
    comment: "The Zero Two Nendoroid is beautiful but one of the three faceplates (the sad expression) had a small paint smear near the right eye. I contacted Tokyo Toys India and Priya responded within 2 hours offering a replacement faceplate at no charge — which arrived 5 days later. The resolution was outstanding. Dropping two stars for the initial defect, adding one back for the excellent after-sale service. Net 3/5 but I would buy here again.",
    status: REVIEW_FIELDS.STATUS_VALUES.APPROVED,
    helpfulCount: 12,
    reportCount: 0,
    verified: true,
    featured: false,
    sellerReply: "Siddharth, we're genuinely sorry about the paint defect on the sad faceplate — QC missed that one. We're glad the replacement arrived quickly and we appreciate you updating your review. Your feedback helps us improve our inspection process.",
    sellerRepliedAt: daysAgo(2),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
    approvedAt: daysAgo(3),
  },
];

export const reviewsSeedData: Partial<ReviewDocument>[] = rawReviews.map(
  ({ sellerId, ...r }) => ({
    ...r,
    ...(sellerId ? (SELLER_STORE[sellerId] ?? {}) : {}),
  }),
);
