/**
 * Reviews Seed Data — LetItRip Collectibles Platform
 * 15 reviews distributed across the 5 stores from P15.
 * Uses buyer IDs from P15 and product IDs from P16/P17/P18.
 * review- prefix, system-generated IDs (not slug-based per slug prefix table).
 */

import type { ReviewDocument } from "../features/reviews/schemas";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const reviewsSeedData: Partial<ReviewDocument>[] = [
  // ── store-pokemon-palace (4 reviews) ─────────────────────────────────────

  {
    id: "review-pokemon-151-box-rahul-001",
    productId: "product-pokemon-151-booster-box",
    productTitle: "Pokémon 151 Booster Box (Sealed)",
    sellerId: "user-aryan-kapoor",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "Absolutely pristine sealed box — perfect packaging",
    comment:
      "Aryan packed this box like it was going to the moon. Double-boxed, foam corners, bubble wrap around the individual booster packs inside. The Pokémon 151 box arrived 100% sealed with no dents. Pulled a Mew ex SAR on my first pack — couldn't be happier. Will buy every new set from Pokémon Palace.",
    status: "approved",
    helpfulCount: 14,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(54),
    approvedAt: daysAgo(54),
  },

  {
    id: "review-base-set-sealed-arjun-002",
    productId: "product-pokemon-base-set-booster-sealed",
    productTitle: "Pokémon Base Set Shadowless Booster Box (Sealed)",
    sellerId: "user-aryan-kapoor",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 5,
    title: "Genuine shadowless box, exactly as described",
    comment:
      "This was a huge purchase for me — ₹89,999 is not nothing. I did video unboxing of the packaging for insurance purposes. The box is clearly genuine shadowless era (1999 print run visible on bottom), factory seal intact, no re-wrapping. Aryan provided provenance documentation (original purchase receipt from a US collector) without me even asking. Impeccable seller.",
    status: "approved",
    helpfulCount: 32,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(42),
    updatedAt: daysAgo(41),
    approvedAt: daysAgo(41),
  },

  {
    id: "review-pokemon-etb-priya-003",
    productId: "product-pokemon-sv-etb",
    productTitle: "Pokémon Scarlet & Violet Paldean Fates Elite Trainer Box",
    sellerId: "user-aryan-kapoor",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 4,
    title: "Great ETB, arrived safely — shipping was a bit slow",
    comment:
      "The ETB was in perfect condition and sealed correctly. I pulled a Shiny Charizard ex which made my week! Shipping took 6 days which is on the longer end, but the packaging was excellent — my only minor complaint. Pokémon Palace is definitely a go-to store.",
    status: "approved",
    helpfulCount: 8,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(27),
    approvedAt: daysAgo(27),
  },

  {
    id: "review-pikachu-plush-meera-004",
    productId: "product-pokemon-pikachu-plush-8",
    productTitle: "Pokémon Pikachu 8-inch Sitting Plush (Official Pokémon Center)",
    sellerId: "user-aryan-kapoor",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    rating: 5,
    title: "Adorable and authentic — tags intact, came with certificate",
    comment:
      "Bought this as a birthday gift for my niece. The plush has the Pokémon Center tag and feels premium — not the cheap knock-offs you see online. Aryan included a small thank-you note which was a lovely touch. Niece went crazy for it. Ordering the Gengar plush next.",
    status: "approved",
    helpfulCount: 5,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(17),
    approvedAt: daysAgo(17),
  },

  // ── store-cardgame-hub (3 reviews) ────────────────────────────────────────

  {
    id: "review-yugioh-25th-tin-rahul-005",
    productId: "product-yugioh-25th-tin",
    productTitle: "Yu-Gi-Oh! 25th Anniversary Tin: Dueling Heroes",
    sellerId: "user-nisha-reddy",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "Nisha is the best YGO seller in India, period",
    comment:
      "I've ordered from three different YGO sellers on LetItRip and CardGame Hub is on another level. The 25th Anniversary Tin arrived with each mega pack in its own sleeve inside the tin. Nisha also included a handwritten note about recommended first packs to open — genuine community knowledge. Will only order YGO from here going forward.",
    status: "approved",
    helpfulCount: 22,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(37),
    approvedAt: daysAgo(37),
  },

  {
    id: "review-yugioh-albaz-arjun-006",
    productId: "product-yugioh-structure-albaz",
    productTitle: "Yu-Gi-Oh! Structure Deck: Albaz Strike",
    sellerId: "user-nisha-reddy",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 4,
    title: "Solid structure deck, good beginner product",
    comment:
      "Bought 3 copies to complete a playset as Nisha recommended. Cards came in the original sealed structure deck packaging with no damage. Shipping was 4 days which is perfectly fine for a standard order. Would rate 5 stars if shipping was 2 days but that's a minor point.",
    status: "approved",
    helpfulCount: 6,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(21),
    approvedAt: daysAgo(21),
  },

  {
    id: "review-charizard-auction-priya-007",
    productId: "auction-pokemon-charizard-base1-psa9",
    productTitle: "Pokémon 1st Edition Charizard PSA 9 (AUCTION)",
    sellerId: "user-nisha-reddy",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 3,
    title: "Card is beautiful but auction process was stressful",
    comment:
      "The card itself is perfect — genuine PSA 9, certificate verified on PSA website. Shipping was excellent (insured, signature required). My 3-star is about the bidding experience: I was outbid in the last 60 seconds three times before winning, which was nerve-wracking. That's a platform issue, not the seller's fault. Card arrived safely and I'm thrilled to own it.",
    status: "approved",
    helpfulCount: 4,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
    approvedAt: daysAgo(11),
  },

  // ── store-diecast-depot (3 reviews) ───────────────────────────────────────

  {
    id: "review-redline-camaro-meera-008",
    productId: "product-hot-wheels-redline-1969-camaro",
    productTitle: "Hot Wheels Redline 1969 Camaro SS — Custom Paint (Bluebird)",
    sellerId: "user-vikram-mehta",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    rating: 5,
    title: "A true Redline beauty — mint condition, authentic",
    comment:
      "This was my first vintage Hot Wheels purchase and Vikram made it a great experience. The Redline arrived in a proper acrylic display case (not just a ziplock — a real display case!) with a card describing the car's production year and rarity. Vikram's description was honest — the car has minor paint wear on the roof which he mentioned in the listing. Very happy.",
    status: "approved",
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(48),
    updatedAt: daysAgo(47),
    approvedAt: daysAgo(47),
  },

  {
    id: "review-tomica-datsun-rahul-009",
    productId: "product-tomica-limited-datsun",
    productTitle: "Tomica Limited Vintage Datsun Bluebird 1600SSS (1969)",
    sellerId: "user-vikram-mehta",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "TLV quality is unreal — every detail perfect",
    comment:
      "I've been collecting Hot Wheels for years but Tomica Limited Vintage is something else entirely. The Datsun Bluebird has rubber tyres, a working bonnet, and tampo print so fine I need a magnifying glass to appreciate it. Vikram sourced this from his Japan trip — you can tell it's fresh stock. Arrived in the original TLV outer box in immaculate condition.",
    status: "approved",
    helpfulCount: 19,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(34),
    approvedAt: daysAgo(34),
  },

  {
    id: "review-hw-rlc-boneshaker-arjun-010",
    productId: "product-hot-wheels-rlc-bone-shaker",
    productTitle: "Hot Wheels RLC Bone Shaker Special Edition",
    sellerId: "user-vikram-mehta",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 4,
    title: "Rare RLC exclusive, good price, slightly late dispatch",
    comment:
      "The RLC Bone Shaker is exactly as described — sealed in the original RLC mailer with the membership card insert. My only feedback: dispatch was on day 3 (not day 2 as listed in store policy). Vikram apologised proactively and offered a discount on my next order, which I appreciate. Car itself is perfect.",
    status: "approved",
    helpfulCount: 7,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(19),
    approvedAt: daysAgo(19),
  },

  // ── store-beyblade-arena (3 reviews) ─────────────────────────────────────

  {
    id: "review-bx01-dran-sword-priya-011",
    productId: "product-beyblade-x-bx01-dran-sword",
    productTitle: "Beyblade X BX-01 Dran Sword 4-60F Starter Set",
    sellerId: "user-rohit-joshi",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 5,
    title: "My son's first BX top — perfect gift, fast delivery",
    comment:
      "Ordered for my 8-year-old who is obsessed with Beyblade X. Rohit shipped the same day I placed the order (I ordered at 10am, it was dispatched by 4pm). Arrived in 3 days. The BX-01 starter set comes with the top, rip cord launcher, and a stadium guide — everything a beginner needs. My son has launched it 200 times and it's still perfect.",
    status: "approved",
    helpfulCount: 28,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(49),
    approvedAt: daysAgo(49),
  },

  {
    id: "review-b200-valkyrie-meera-012",
    productId: "product-beyblade-burst-b200-valkyrie",
    productTitle: "Beyblade Burst B-200 Brave Valkyrie Evolution",
    sellerId: "user-rohit-joshi",
    userId: "user-meera-nair",
    userName: "Meera Nair",
    rating: 5,
    title: "Authentic Takara Tomy import, not the bootleg version",
    comment:
      "There are SO many bootleg Beyblades on other platforms. Rohit sells only genuine Takara Tomy product — you can tell by the QR code on the Beyblade passport card (scans correctly on the Beyblade app). Brave Valkyrie arrived fresh from its Japan import, unopened. The weight difference from bootlegs is immediately obvious.",
    status: "approved",
    helpfulCount: 15,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(32),
    updatedAt: daysAgo(31),
    approvedAt: daysAgo(31),
  },

  {
    id: "review-preorder-beyblade-bx10-rahul-013",
    productId: "preorder-beyblade-x-bx10-booster",
    productTitle: "Beyblade X BX-10 Booster Set Pre-Order",
    sellerId: "user-rohit-joshi",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 4,
    title: "Pre-order arrived on time — worth the wait",
    comment:
      "Rohit's pre-order process was smooth. I paid the 30% deposit, received confirmation, and the balance was charged exactly when he said it would be (2 days before dispatch). Item arrived 42 days after ordering — right in the promised window. No complaints. Will pre-order the BX-12 when Rohit lists it.",
    status: "approved",
    helpfulCount: 9,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(9),
    approvedAt: daysAgo(9),
  },

  // ── store-letitrip-official (2 reviews) ───────────────────────────────────

  {
    id: "review-shf-goku-arjun-014",
    productId: "product-shf-goku-ultra-instinct",
    productTitle: "S.H.Figuarts Goku Ultra Instinct -Sign- (Dragon Ball Super)",
    sellerId: "user-admin-letitrip",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 5,
    title: "Official LetItRip store delivers — SHF in perfect condition",
    comment:
      "This is my 4th S.H.Figuarts from LetItRip Official and they're consistently excellent. The Goku UI comes with 5 face plates, effect parts, and all the swap hands. Every accessory was accounted for (I always check). LetItRip Official is the most reliable store on the platform — their QC before dispatch is clearly thorough.",
    status: "approved",
    helpfulCount: 17,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(26),
    updatedAt: daysAgo(25),
    approvedAt: daysAgo(25),
  },

  {
    id: "review-gundam-rx78-mg-arjun-015",
    productId: "product-gundam-rx78-mg",
    productTitle: "MG 1/100 RX-78-2 Gundam Ver. 3.0",
    sellerId: "user-admin-letitrip",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 2,
    title: "Kit was missing the beam rifle assembly — resolved via support",
    comment:
      "The box arrived safely but when I inventoried the sprues, the G runner (beam rifle parts) was missing — looks like a factory packing error. I opened a dispute on LetItRip and LetItRip Official resolved it within 48 hours by shipping the missing runner separately at no cost. They clearly take after-sales seriously. Updating from 1 star to 2 stars because the issue was resolved, but losing a star for the missing part.",
    status: "approved",
    helpfulCount: 6,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(12),
    approvedAt: daysAgo(12),
  },

  // ── store-tokyo-toys-india (5 reviews) ────────────────────────────────────

  {
    id: "review-nendoroid-zero-two-sneha-016",
    productId: "product-nendoroid-zero-two",
    productTitle: "Nendoroid Zero Two (Darling in the FranXX) #942",
    sellerId: "user-priya-singh",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 5,
    title: "Zero Two is everything I dreamed of — authentic GSC, flawless",
    comment:
      "I've been hunting this Nendoroid for 2 years and finally found it at Tokyo Toys India. Priya sourced the re-release directly from GSC. The serial number on the base matches the box — definitely authentic. Three faceplates, the horns are perfect, and the stand works smoothly. Packed in foam-padded box, arrived in 3 days. Priya is the real deal — she knows her anime figures.",
    status: "approved",
    helpfulCount: 24,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(44),
    approvedAt: daysAgo(44),
  },

  {
    id: "review-nendoroid-levi-tanvi-017",
    productId: "product-nendoroid-levi-aot",
    productTitle: "Nendoroid Levi Ackerman (Attack on Titan) #390",
    sellerId: "user-priya-singh",
    userId: "user-tanvi-desai",
    userName: "Tanvi Desai",
    rating: 5,
    title: "Cleaning mode faceplate alone is worth it — perfect figure",
    comment:
      "The cleaning mode Levi faceplate with the tiny mop is the most charming thing I own. Priya's packaging was impeccable — each faceplate in its own mini tray exactly as GSC intended. This is my 6th Nendoroid from Tokyo Toys India and Priya has never once let me down. Already eyeing the Ram Nendoroid on her store.",
    status: "approved",
    helpfulCount: 18,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(38),
    updatedAt: daysAgo(37),
    approvedAt: daysAgo(37),
  },

  {
    id: "review-shf-sailor-moon-sneha-018",
    productId: "product-shf-sailor-moon-eternal",
    productTitle: "S.H.Figuarts Sailor Moon Eternal (2021)",
    sellerId: "user-priya-singh",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 5,
    title: "Rainbow wings are breathtaking — showpiece figure",
    comment:
      "The rainbow semi-translucent wings on this figure catch light in ways that my photos simply cannot capture. When sunlight hits them, the entire shelf lights up. Priya had this in stock while every other seller was out — she clearly has excellent supplier relationships. Arrived double-boxed, wings were in a separate padded compartment. No damage. 10/10.",
    status: "approved",
    helpfulCount: 31,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(29),
    updatedAt: daysAgo(28),
    approvedAt: daysAgo(28),
  },

  {
    id: "review-funko-pop-tanjiro-tanvi-019",
    productId: "product-funko-pop-tanjiro-demon-slayer",
    productTitle: "Funko Pop! Tanjiro Kamado (Demon Slayer) #855",
    sellerId: "user-priya-singh",
    userId: "user-tanvi-desai",
    userName: "Tanvi Desai",
    rating: 4,
    title: "Perfect mint on card — Priya's packaging keeps boxes pristine",
    comment:
      "I collect Funko Pops for display out of box BUT I keep a carded mint copy for investment. Priya packs each Pop in a protector sleeve before shipping — the box arrived with zero corner wear. That level of care for a ₹1,699 Funko is impressive. Deducting one star only because dispatch was Day 2 instead of Day 1 (she mentioned a supply arrival delay in her dispatch message).",
    status: "approved",
    helpfulCount: 12,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(19),
    approvedAt: daysAgo(19),
  },

  {
    id: "review-racing-miku-priya-patel-020",
    productId: "product-gsc-racing-miku-2023",
    productTitle: "Good Smile Racing Miku 2023 Ver. 1/7 Scale",
    sellerId: "user-priya-singh",
    userId: "user-priya-patel",
    userName: "Priya Patel",
    rating: 5,
    title: "Centrepiece of my collection — absolutely stunning 1/7 scale",
    comment:
      "Racing Miku 2023 Ver. is the most beautiful figure I own. The 1/7 scale means she stands tall on my shelf and catches everyone's eye. Priya sourced this from Akihabara directly — the box has the Japanese tax receipt inside. She packed the figure's base separately with foam and the wings were in bubble wrap. Nothing moved in transit. Worth every rupee.",
    status: "approved",
    helpfulCount: 26,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
    approvedAt: daysAgo(11),
  },

  // ── store-gundam-galaxy (4 reviews) ──────────────────────────────────────

  {
    id: "review-hg-barbatos-kartik-021",
    productId: "product-gundam-hg-barbatos-lupus-rex",
    productTitle: "HG 1/144 Gundam Barbatos Lupus Rex (Iron-Blooded Orphans)",
    sellerId: "user-amit-sharma",
    userId: "user-kartik-nair",
    userName: "Kartik Nair",
    rating: 5,
    title: "First Gunpla ever — Amit's advice helped me pick the right kit",
    comment:
      "I messaged Amit before ordering asking which HG is best for a complete beginner. He replied within an hour with a detailed breakdown of the top 5 beginner HG kits and explained why Barbatos Lupus Rex is the best mix of posability and fun. Great advice — the build took me a weekend and the result is spectacular. Amit is clearly a passionate builder and that shows in how he sells.",
    status: "approved",
    helpfulCount: 34,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(52),
    updatedAt: daysAgo(51),
    approvedAt: daysAgo(51),
  },

  {
    id: "review-mg-sazabi-arjun-022",
    productId: "product-gundam-mg-sazabi-verka",
    productTitle: "MG 1/100 Sazabi Ver.Ka (Master Grade)",
    sellerId: "user-amit-sharma",
    userId: "user-arjun-singh",
    userName: "Arjun Singh",
    rating: 5,
    title: "The pinnacle of Master Grade — Amit's packaging was museum-grade",
    comment:
      "This is the most expensive kit I've ever bought (₹6,499) and Amit treated it accordingly. The Sazabi Ver.Ka arrived triple-boxed — outer cardboard, foam insert, and the kit box itself inside a second layer of rigid cardboard. Every runner individually wrapped. The kit itself is exactly as legendary as its reputation — 300+ parts, three-layer construction, and the most satisfying snap-fit engineering I've ever experienced. Amit is the best Gunpla seller in India.",
    status: "approved",
    helpfulCount: 42,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(39),
    approvedAt: daysAgo(39),
  },

  {
    id: "review-rg-evangelion-sneha-023",
    productId: "product-gundam-rg-evangelion-unit01",
    productTitle: "RG 1/144 Evangelion Unit-01 (Rebuild of Evangelion)",
    sellerId: "user-amit-sharma",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 4,
    title: "EVA-01 in RG is spectacular — pre-coloured runners are a revelation",
    comment:
      "I'm not a regular Gunpla buyer but bought this for my EVA collection. Amit's store description mentioned that this is the first non-Gundam RG kit and the pre-coloured runners make it accessible for non-modellers. He was right — I built it with no paint and it looks exactly like the promo photos. Deducting one star because the umbilical cable tends to pop off at the connection point, but that's a Bandai design note, not Amit's fault.",
    status: "approved",
    helpfulCount: 16,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(27),
    updatedAt: daysAgo(26),
    approvedAt: daysAgo(26),
  },

  {
    id: "review-rg-hi-nu-preorder-kartik-024",
    productId: "preorder-gundam-rg-hi-nu-verka",
    productTitle: "PRE-ORDER: RG 1/144 Hi-ν Gundam Ver.Ka",
    sellerId: "user-amit-sharma",
    userId: "user-kartik-nair",
    userName: "Kartik Nair",
    rating: 5,
    title: "Pre-order process is smooth — Amit updates you at every step",
    comment:
      "Placed this pre-order and Amit messaged me the same day confirming receipt, then sent weekly updates on Japan warehouse status. He also warned me about a potential 2-week delay due to Bandai production schedules before I even knew about it publicly. That level of proactive communication is rare. Kit hasn't arrived yet but the deposit process was seamless.",
    status: "approved",
    helpfulCount: 8,
    reportCount: 0,
    verified: false,
    featured: false,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    approvedAt: daysAgo(4),
  },

  // ── store-vintage-vault (4 reviews) ──────────────────────────────────────

  {
    id: "review-pokemon-charizard-lp-divya-025",
    productId: "product-vintage-pokemon-charizard-base-lp",
    productTitle: "Pokémon Base Set Charizard #4/102 Holo Rare — LP Raw",
    sellerId: "user-kavya-iyer",
    userId: "user-divya-menon",
    userName: "Divya Menon",
    rating: 5,
    title: "Honest condition grading — exactly what she described",
    comment:
      "I was nervous buying a ₹3,999 Charizard online but Kavya sent me 8 high-res photos in different lighting before I confirmed. The card matches her LP description exactly — the corners and whitening are exactly as documented. She's been in this business 20 years and her grading vocabulary is precise. Most sellers say 'Near Mint' for LP cards — Kavya says LP for LP. Refreshing honesty.",
    status: "approved",
    helpfulCount: 29,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(34),
    approvedAt: daysAgo(34),
  },

  {
    id: "review-hw-deora-vintage-siddharth-026",
    productId: "product-vintage-hot-wheels-deora-1968",
    productTitle: "Hot Wheels Redline 1968 Deora — Aqua (Vintage)",
    sellerId: "user-kavya-iyer",
    userId: "user-siddharth-rao",
    userName: "Siddharth Rao",
    rating: 5,
    title: "A piece of toy history — Kavya's knowledge is unmatched",
    comment:
      "I collect vintage Redlines and Kavya is the first Indian seller I've found who truly understands them. Her listing for the Deora was the most detailed I've seen anywhere — she identified it as an early production run based on the chassis stamp. The provenance documentation (original owner paperwork) is extraordinary. This car is now the centrepiece of my collection.",
    status: "approved",
    helpfulCount: 21,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(23),
    updatedAt: daysAgo(22),
    approvedAt: daysAgo(22),
  },

  {
    id: "review-motu-he-man-rahul-027",
    productId: "product-vintage-motu-he-man-1982",
    productTitle: "Masters of the Universe He-Man (1982 Takara Japan)",
    sellerId: "user-kavya-iyer",
    userId: "user-rahul-sharma",
    userName: "Rahul Sharma",
    rating: 5,
    title: "My childhood hero — and a genuine 1982 first-year original",
    comment:
      "I grew up with He-Man but never had an original 1982 figure. When I saw Kavya's listing with the Takara sticker on the packaging, I knew it was legitimate — that detail is how you identify the Japan distribution version. She included a certificate of authenticity from a vintage toy appraiser. The torso twist mechanism works perfectly after 40+ years. Remarkable condition for the age.",
    status: "approved",
    helpfulCount: 15,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(13),
    approvedAt: daysAgo(13),
  },

  {
    id: "review-jungle-vaporeon-tanvi-028",
    productId: "product-vintage-pokemon-jungle-vaporeon-holo",
    productTitle: "Pokémon WOTC Jungle Vaporeon #12/64 Holo Rare — NM Raw",
    sellerId: "user-kavya-iyer",
    userId: "user-tanvi-desai",
    userName: "Tanvi Desai",
    rating: 5,
    title: "WOTC era quality is incomparable — Kavya preserves history",
    comment:
      "I'm building a raw NM WOTC set and Kavya's Vintage Vault has the cleanest WOTC cards I've found in India. The Vaporeon has the original First Edition-era card stock texture that WOTC used before they cheapened the material in later sets. Holo is perfect. Kavya's estate-sale sourcing means these cards have been in private collections — not through dealer hands repeatedly.",
    status: "approved",
    helpfulCount: 11,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
    approvedAt: daysAgo(6),
  },

  // ── Additional reviews across existing stores (new buyers) ────────────────

  {
    id: "review-pokemon-151-box-sneha-029",
    productId: "product-pokemon-151-booster-box",
    productTitle: "Pokémon 151 Booster Box (Sealed)",
    sellerId: "user-aryan-kapoor",
    userId: "user-sneha-kumar",
    userName: "Sneha Kumar",
    rating: 5,
    title: "Investment-grade sealed product — Aryan's sourcing is legit",
    comment:
      "Bought the 151 booster box for long-term storage. The shrink wrap is tight with no air gaps (sign of authentic factory sealing). Aryan included a UK distributor invoice confirming the source — that level of documentation is exceptional. Box is now in my climate-controlled storage. When I eventually open it, I'll update this review with pull results.",
    status: "approved",
    helpfulCount: 13,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(29),
    approvedAt: daysAgo(29),
  },

  {
    id: "review-yugioh-phantom-nightmare-siddharth-030",
    productId: "product-yugioh-phantom-nightmare-box",
    productTitle: "Yu-Gi-Oh! Phantom Nightmare Booster Box (24 Packs)",
    sellerId: "user-nisha-reddy",
    userId: "user-siddharth-rao",
    userName: "Siddharth Rao",
    rating: 5,
    title: "Hit a Fiendsmith Engraver UR — best opening of 2024",
    comment:
      "Ordered the Phantom Nightmare box for the Fiendsmith engine cards. Nisha had it at ₹5,999 when other sellers were charging ₹6,499 for the same product — she's clearly competitive on pricing. Box arrived factory sealed, split into two lots of 12 packs each inside the cardboard insert. Opened all 24 packs, hit the Fiendsmith Engraver Ultra Rare, two Snake-Eye Ash Secret Rares, and a complete Rescue-Ace suite. Excellent pull rate.",
    status: "approved",
    helpfulCount: 22,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(17),
    approvedAt: daysAgo(17),
  },

  {
    id: "review-beyblade-xstadium-ankit-031",
    productId: "product-beyblade-x-xstadium-official",
    productTitle: "Beyblade X BX-08 XStadium (Official Takara Tomy)",
    sellerId: "user-rohit-joshi",
    userId: "user-ankit-gupta",
    userName: "Ankit Gupta",
    rating: 5,
    title: "Tournament quality — arrived well before my regional event",
    comment:
      "I needed this stadium for our city's Beyblade X regional. Rohit had it in stock when every other platform was out. Ordered Monday morning, arrived Thursday — with 2 days to spare before the event. The XStadium is the real tournament-spec — the X-Line rail is perfectly calibrated and the floor has no warping. Won my bracket. 10/10 seller.",
    status: "approved",
    helpfulCount: 19,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(14),
    approvedAt: daysAgo(14),
  },

  {
    id: "review-sth-dodge-viper-siddharth-032",
    productId: "product-hot-wheels-sth-dodge-viper",
    productTitle: "Hot Wheels Super Treasure Hunt Dodge Viper SRT10 (STH)",
    sellerId: "user-vikram-mehta",
    userId: "user-siddharth-rao",
    userName: "Siddharth Rao",
    rating: 5,
    title: "Confirmed STH — Spectraflame is glorious, card is mint",
    comment:
      "Vikram's listing said 'immediately cased after retail pull' and that is exactly what arrived — you can see the factory crimp on the blister is undisturbed. The Spectraflame Red on this Viper is one of the deepest metallic finishes I've seen on a recent STH. Card is flat, no corner wear, graphic is crisp. This is a ₹2,999 car that will be worth ₹8,000 in a decade. Vikram knows his product.",
    status: "approved",
    helpfulCount: 17,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(7),
    approvedAt: daysAgo(7),
  },

  {
    id: "review-neca-tmnt-divya-033",
    productId: "product-neca-tmnt-4figure-set",
    productTitle: "NECA TMNT Classic 1990 Movie 4-Figure Set",
    sellerId: "user-admin-letitrip",
    userId: "user-divya-menon",
    userName: "Divya Menon",
    rating: 5,
    title: "The childhood dream — all 4 Turtles in one box, museum quality",
    comment:
      "I grew up watching the 1990 TMNT movie and this set made me feel like a kid again. The film-suit sculpts are extraordinary — you can see the texture of the foam rubber suits translated into articulated plastic. LetItRip Official packed the set in a rigid outer casing inside a foam-padded bag inside the shipping box. Three layers of protection for a ₹12,999 set. That's how it should be done.",
    status: "approved",
    helpfulCount: 27,
    reportCount: 0,
    verified: true,
    featured: true,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
    approvedAt: daysAgo(5),
  },

  {
    id: "review-mg-sazabi-verka-kartik-034",
    productId: "product-gundam-mg-sazabi-verka",
    productTitle: "MG 1/100 Sazabi Ver.Ka",
    sellerId: "user-amit-sharma",
    userId: "user-kartik-nair",
    userName: "Kartik Nair",
    rating: 5,
    title: "Graduation kit from HG to MG — Amit guided me through it",
    comment:
      "After my Barbatos Lupus Rex HG build, I wanted to try Master Grade. I messaged Amit asking if Sazabi Ver.Ka is too advanced for a second build. He was honest — he said it's challenging but doable if you take your time, and he offered to share his build guide PDF. I took 3 weeks to build it and it's perfect. Amit genuinely cares about his customers having a great build experience.",
    status: "approved",
    helpfulCount: 9,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    approvedAt: daysAgo(2),
  },

  {
    id: "review-pokemon-etb-temporal-ankit-035",
    productId: "product-pokemon-sv-temporal-forces-etb",
    productTitle: "Pokémon TCG: Temporal Forces Elite Trainer Box",
    sellerId: "user-aryan-kapoor",
    userId: "user-ankit-gupta",
    userName: "Ankit Gupta",
    rating: 4,
    title: "Great ETB, good pulls — would prefer faster dispatch",
    comment:
      "Temporal Forces ETB arrived in great condition — sealed correctly, no box damage. Pulled an Iron Leaves ex SAR on pack 4 which more than covered the cost. My only note: dispatch was on Day 3 (I ordered Sunday and it was dispatched Wednesday). Aryan's shipping info says 24-hour dispatch which wasn't met. Dropping one star for that. Card quality and packaging: 5 stars.",
    status: "approved",
    helpfulCount: 6,
    reportCount: 0,
    verified: true,
    featured: false,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    approvedAt: daysAgo(1),
  },
];
