/*
 * WHY: Seeds the singleton site-settings doc for a generic collectibles marketplace.
 * WHAT: 1 document — branding, SEO, features, legal, commissions, credentials, ad inventory.
 *
 * EXPORTS:
 *   siteSettingsSeedData — Partial<SiteSettingsDocument> for seed runner
 *
 * @tag domain:site-settings,admin
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts
 * @tag sideEffects:none
 */

import type { SiteSettingsDocument } from "../features/admin/schemas";
import { seedExtMedia } from "./_helpers/media";
import { ROUTES } from "../next/routing/route-map";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const adPlacementsSeed = [
  {
    id: "homepage-hero-banner",
    label: "Homepage Hero Banner",
    enabled: true,
    reservedHeight: 90,
  },
  {
    id: "listing-sidebar-top",
    label: "Listing Sidebar Top",
    enabled: true,
    reservedHeight: 90,
  },
  {
    id: "listing-sidebar-bottom",
    label: "Listing Sidebar Bottom",
    enabled: true,
    reservedHeight: 90,
  },
  {
    id: "search-inline",
    label: "Search Inline",
    enabled: true,
    reservedHeight: 90,
  },
] as const;

export const siteSettingsSeedData: Partial<SiteSettingsDocument> & {
  adSettings: {
    consentRequired: boolean;
    placements: readonly {
      id: string;
      label: string;
      enabled: boolean;
      reservedHeight: number;
    }[];
    providerCredentials: {
      adsenseClientId: string;
      thirdPartyScriptUrl: string;
    };
    inventory: {
      id: string;
      name: string;
      provider: "manual" | "adsense" | "thirdParty";
      status: "draft" | "active" | "scheduled" | "paused";
      placementIds: string[];
      requiresConsent: boolean;
      priority: number;
      startAt?: string;
      endAt?: string;
      createdAt: string;
      updatedAt: string;
      updatedBy: string;
      creative: {
        title?: string;
        body?: string;
        imageUrl?: string;
        ctaLabel?: string;
        ctaHref?: string;
        adsenseSlot?: string;
        thirdPartyUrl?: string;
      };
    }[];
  };
} = {
  id: "global",
  siteName: "LetItRip",
  motto: "India's Marketplace for Collectibles — Action Figures, Trading Cards, Spinning Tops & More",
  announcementBar: {
    enabled: true,
    message: "🎉 Up to 25% off select listings + free shipping on orders above ₹999 — See Events for codes",
  },
  watermark: {
    type: "text",
    text: "letitrip.in",
    imageUrl: "",
    size: 10,
    opacity: 10,
    position: "center",
    offsetX: 0,
    offsetY: 0,
  },
  logo: {
    url: "",
    alt: "LetItRip Logo",
    format: "svg",
  },
  aboutContent: {
    title: "Every collection has a story. Let It Rip.",
    subtitle:
      "We built India's marketplace for people who chase the thrill of the find — action figures, trading cards, spinning tops, model kits, and everything in between.",
    missionTitle: "Our Mission",
    missionText:
      "Collectibles are more than objects — they're the Saturday-morning cartoons we grew up on, the cards we traded at recess, the tops we battled on the playground. LetItRip exists to give India's collectors a place built specifically for that obsession: verified sellers, live auctions that actually feel alive, pre-orders for the drops you can't miss, and an escrow-backed checkout so a rare find never turns into a rare regret. We're not trying to be everything to everyone — we're trying to be the best place on the internet to buy, sell, and obsess over the things you collect.",
    howItWorksTitle: "How It Works",
    howItems: [
      {
        title: "Browse & Discover",
        text: "Search thousands of listings across action figures, trading cards, spinning tops, model kits, and vintage rarities — filtered by category, brand, condition, and price so you find exactly what you're hunting for.",
        icon: "🛒",
        tone: "indigo",
      },
      {
        title: "Sell With Confidence",
        text: "Open a store in minutes, list with our SEO-friendly slugging and media tools, and get paid through escrow-protected orders — no chasing buyers, no guessing games.",
        icon: "🏪",
        tone: "teal",
      },
      {
        title: "Bid, Win, Rip",
        text: "Live auctions with real-time bidding, transparent history, and instant outbid alerts. When the gavel falls, checkout and shipping are already lined up.",
        icon: "⚡",
        tone: "amber",
      },
    ],
    valuesTitle: "Our Values",
    valueItems: [
      {
        title: "Trust First",
        text: "Every seller is verified, every payment is escrow-protected, and every listing is held to the same authenticity bar we'd want as buyers ourselves.",
        icon: "🛡️",
      },
      {
        title: "Built By Collectors",
        text: "We're not a generic marketplace with a collectibles tab bolted on — every feature, from grading fields to condition tags, exists because a real collector asked for it.",
        icon: "🤝",
      },
      {
        title: "Move Fast, Ship Fast",
        text: "Rare drops don't wait, and neither do we — from pre-order alerts to 3-7 day delivery, we optimise for the moment you finally get to unbox it.",
        icon: "🚀",
      },
    ],
    milestonesTitle: "Our Journey",
    milestones: [
      { year: "2024", text: "LetItRip started as a weekend project — a single developer, a spinning-top collection outgrowing its shelf, and a conviction that India's collectors deserved a marketplace built just for them." },
      { year: "2025", text: "Live auctions, seller storefronts, and escrow-backed checkout shipped — turning a side project into a real marketplace with verified sellers across action figures, trading cards, and model kits." },
      { year: "2026", text: "Pre-orders, events, raffles, and a mobile-first redesign — built for the community that showed up, bid, sold, and kept coming back." },
    ],
    teamTitle: "Who's Behind LetItRip",
    teamSubtitle: "One collector obsessed with the same thing you are — the hunt for the next piece of the collection.",
    teamMembers: [
      {
        name: "Mohasin Chinnapattan",
        role: "Founder & Developer",
        bio: "Started LetItRip after one too many afternoons hunting for a specific 1st-edition card across a dozen disconnected forums and marketplaces. Built the entire platform — Next.js front end, Firebase backend, the auction engine, the whole thing — the same way most great collections start: one late night at a time. Still personally answers the support inbox.",
        photoUrl: seedExtMedia("https://picsum.photos/seed/letitrip-team-mohasin-chinnapattan-20260820/400/400"),
        isFounder: true,
        isDeveloper: true,
        githubUrl: "https://github.com/mohasinac",
      },
    ],
    ctaTitle: "Ready to Let It Rip?",
    ctaSell: "Start selling in minutes",
    ctaShop: "Browse the marketplace",
  },
  background: {
    light: {
      type: "gradient",
      value: "linear-gradient(135deg, #f0f4ff 0%, #f9fafb 100%)",
      overlay: {
        enabled: false,
        color: "#000000",
        opacity: 0,
      },
    },
    dark: {
      type: "gradient",
      value: "linear-gradient(135deg, #020617 0%, #0f172a 100%)",
      overlay: {
        enabled: false,
        color: "#000000",
        opacity: 0,
      },
    },
  },
  contact: {
    email: "support@letitrip.in",
    phone: "+91-8919665811",
    address: "Siddeshwar Peth, Solapur, Maharashtra 413001",
    upiVpa: "mohsin0502@okicici",
    whatsappNumber: "918919665811",
  },
  payment: {
    razorpayEnabled: false,
    upiManualEnabled: true,
    codEnabled: true,
    otpCheckoutThreshold: 5000,
  },
  emi: {
    enabled: true,
    minOrderValue: 10000,
    tenureOptions: [2, 3, 4, 5, 6],
    tokenPercent: 10,
    billingDay: 5,
    surchargePercentPerMonth: 1,
    surchargeSellerSharePercent: 50,
  },
  socialLinks: {
    facebook: "",
    twitter: "",
    instagram: "",
    linkedin: "",
  },
  emailSettings: {
    fromName: "LetItRip",
    fromEmail: "noreply@letitrip.in",
    replyTo: "support@letitrip.in",
  },
  seo: {
    defaultTitle:
      "LetItRip — Buy, Sell & Auction Collectibles | India's Collectibles Marketplace",
    defaultDescription:
      "Buy, sell, and auction collectibles on India's marketplace for enthusiasts — action figures, trading cards, spinning tops, model kits, and more from verified sellers.",
    keywords: [
      "collectibles marketplace india",
      "action figures india",
      "trading cards india",
      "spinning tops collectibles",
      "model kits india",
      "vintage collectibles",
      "live auction collectibles",
      "pre-order collectibles",
      "verified sellers india",
      "buy sell collectibles online",
    ],
    ogImage: seedExtMedia("https://picsum.photos/seed/site-og-image-collectibles-20260101/1200/630"),
  },
  features: [
    {
      id: "feature_001",
      name: "Huge Catalogue",
      description: "Curated Collectibles Across Every Category",
      icon: "📦",
      enabled: true,
    },
    {
      id: "feature_002",
      name: "Fast Shipping",
      description: "Delivered in 3–7 Days Across India",
      icon: "🚚",
      enabled: true,
    },
    {
      id: "feature_003",
      name: "Authentic Only",
      description: "Verified Sellers, Verified Products",
      icon: "✅",
      enabled: true,
    },
    {
      id: "feature_004",
      name: "Secure Payments",
      description: "Escrow-Protected Transactions",
      icon: "🔒",
      enabled: true,
    },
    {
      id: "feature_005",
      name: "Live Auctions",
      description: "Bid on Rare & Collectible Items",
      icon: "🏆",
      enabled: true,
    },
    {
      id: "feature_006",
      name: "Pre-Orders",
      description: "Reserve Upcoming Releases Early",
      icon: "⏳",
      enabled: true,
    },
  ],
  legalPages: {
    termsOfService: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Terms of Service" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "Welcome to LetItRip. By accessing our platform, you agree to these terms...",
            },
          ],
        },
      ],
    }),
    privacyPolicy: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Privacy Policy" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "Your privacy is important to us. This policy describes how we collect and use your data...",
            },
          ],
        },
      ],
    }),
    refundPolicy: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Refund Policy" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "We offer a 7-day return and refund policy on most products. Items must be in original condition...",
            },
          ],
        },
      ],
    }),
    shippingPolicy: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Shipping Policy" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "We offer free shipping on orders above ₹999. Standard delivery takes 3-7 business days...",
            },
          ],
        },
      ],
    }),
  },
  shipping: {
    estimatedDays: 7,
    minOrderForFree: 999,
  },
  returns: {
    windowDays: 7,
  },
  faq: {
    variables: {
      shippingDays: 7,
      minOrderValue: 999,
      returnWindow: 7,
      supportEmail: "support@letitrip.in",
      supportPhone: "+91-8919665811",
      codDeposit: 0.1,
    },
  },
  createdAt: daysAgo(799),
  updatedAt: daysAgo(29),
  navbarConfig: {
    hiddenNavItems: [],
  },
  footerConfig: {
    trustBar: {
      enabled: true,
      items: [
        { icon: "🚚", label: "Free Shipping", visible: true },
        { icon: "🔄", label: "Easy Returns", visible: true },
        { icon: "🔒", label: "Secure Payment", visible: true },
        { icon: "🎧", label: "24/7 Support", visible: true },
        { icon: "✅", label: "Authentic Sellers", visible: true },
      ],
    },
    newsletterEnabled: true,
  },
  adSettings: {
    consentRequired: true,
    placements: adPlacementsSeed,
    providerCredentials: {
      adsenseClientId: "ca-pub-0000000000000000",
      thirdPartyScriptUrl: seedExtMedia("https://cdn.example-ads.com/ad-runtime.js"),
    },
    inventory: [
      {
        id: "ad-homepage-hero-new-arrivals",
        name: "New Arrivals Hero Banner",
        provider: "manual",
        status: "active",
        placementIds: ["homepage-hero-banner"],
        requiresConsent: true,
        priority: 100,
        createdAt: daysAgo(20).toISOString(),
        updatedAt: daysAgo(2).toISOString(),
        updatedBy: "user-admin-letitrip",
        creative: {
          title: "New Arrivals Mega Drop",
          body: "Limited new arrivals across every category — this weekend only.",
          imageUrl: seedExtMedia("https://picsum.photos/seed/ad-homepage-hero-new-arrivals-20260101/1200/400"),
          ctaLabel: "Explore Deals",
          ctaHref: "/promotions/deals",
        },
      },
      {
        id: "ad-listing-sidebar-auction-boost",
        name: "Sidebar Auction Boost",
        provider: "manual",
        status: "active",
        placementIds: ["listing-sidebar-top", "listing-sidebar-bottom"],
        requiresConsent: true,
        priority: 80,
        createdAt: daysAgo(12).toISOString(),
        updatedAt: daysAgo(1).toISOString(),
        updatedBy: "user-admin-letitrip",
        creative: {
          title: "Live Auctions",
          body: "Rare and collectible items — auctions ending this week.",
          imageUrl: seedExtMedia("https://picsum.photos/seed/ad-listing-sidebar-auction-boost-20260101/600/600"),
          ctaLabel: "View Auctions",
          ctaHref: String(ROUTES.PUBLIC.AUCTIONS),
        },
      },
      {
        id: "ad-search-inline-spotlight",
        name: "Search Spotlight — Featured Picks",
        provider: "manual",
        status: "scheduled",
        placementIds: ["search-inline"],
        requiresConsent: true,
        priority: 70,
        startAt: daysAgo(-3).toISOString(),
        endAt: daysAgo(-10).toISOString(),
        createdAt: daysAgo(1).toISOString(),
        updatedAt: daysAgo(1).toISOString(),
        updatedBy: "user-admin-letitrip",
        creative: {
          title: "Complete Your Collection",
          body: "Find the pieces you're missing — new listings added daily.",
          imageUrl: seedExtMedia("https://picsum.photos/seed/ad-search-inline-spotlight-20260101/600/600"),
          ctaLabel: "Browse All",
          ctaHref: String(ROUTES.PUBLIC.PRODUCTS),
        },
      },
    ],
  },
  commissions: {
    platformFeePercent: 5,
    gstPercent: 18,
    minimumTransactionFee: 0,
    gatewayFeePercent: 2,
    codDepositPercent: 10,
    codHandlingFeeMin: 200,
    codHandlingFeePercent: 10,
    whatsappNotifyFeeEnabled: false,
    whatsappNotifyFee: 10,
    giftWrapFeeEnabled: false,
    giftWrapFee: 49,
    shipmentProtectionFeeEnabled: false,
    shipmentProtectionFeePercent: 2,
    shipmentProtectionFeeMin: 30,
    sellerShippingFixed: 0,
    platformShippingPercent: 0,
    platformShippingFixedMin: 0,
    autoPayoutWindowDays: 7,
    payoutHoldDays: 2,
    minPayoutAmount: 100,
    auctionListingFee: 0,
    preOrderListingFee: 0,
    featuredSlotFee: 999,
    promotedSlotFee: 499,
  },
  featureFlags: {
    chats: true,
    // Real per-SMS cost via the Firebase phone-auth quota — the one flag
    // that stays off by default; every other flag is enabled.
    smsVerification: false,
    translations: true,
    wishlists: true,
    auctions: true,
    reviews: true,
    events: true,
    blog: true,
    coupons: true,
    notifications: true,
    sellerRegistration: true,
    preOrders: true,
    adminCheckoutBypass: false,
    listingTypes: {
      standard: true,
      auction: true,
      "pre-order": true,
      "prize-draw": true,
      bundle: true,
      classified: true,
      "digital-code": true,
      live: true,
    },
    categoryTypes: {
      category: true,
      sublisting: true,
      brand: true,
      bundle: true,
    },
  },
  credentials: {
    razorpayKeyId: "rzp_test_PLACEHOLDER",
    razorpayKeySecret: "secret_PLACEHOLDER",
    razorpayWebhookSecret: "webhook_PLACEHOLDER",
    resendApiKey: "",
    whatsappApiKey: "wa_PLACEHOLDER",
    whatsappPhoneNumberId: "",
    whatsappCloudApiToken: "",
    whatsappAdminNotifyNumbers: "",
    metaAppId: "meta_app_PLACEHOLDER",
    metaAppSecret: "meta_secret_PLACEHOLDER",
    metaPageAccessToken: "meta_page_token_PLACEHOLDER",
    metaPageId: "meta_page_id_PLACEHOLDER",
    tiktokClientKey: "tiktok_client_key_PLACEHOLDER",
    tiktokClientSecret: "tiktok_client_secret_PLACEHOLDER",
    tiktokAccessToken: "tiktok_access_token_PLACEHOLDER",
    deviantartClientId: "deviantart_client_id_PLACEHOLDER",
    deviantartClientSecret: "deviantart_client_secret_PLACEHOLDER",
  },
  notificationChannels: {
    inApp: { enabled: true, readOnly: true },
    email: { enabled: true, minPriority: "normal" },
    whatsapp: { enabled: true, minPriority: "high", otpEnabled: true },
    sms: { enabled: true, minPriority: "high" },
  },
  actionConfig: {},
  navConfig: {},
  disabledRoutes: [],
  theme: {
    themes: [
      /* ── LIGHT THEMES ──────────────────────────────────────── */
      {
        id: "crimson-warrior",
        name: "Teal Tide",
        mode: "light" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#0d9488",
          "appkit-color-primary-50":  "#f0fdfa",
          "appkit-color-primary-100": "#ccfbf1",
          "appkit-color-primary-200": "#99f6e4",
          "appkit-color-primary-300": "#5eead4",
          "appkit-color-primary-400": "#2dd4bf",
          "appkit-color-primary-500": "#14b8a6",
          "appkit-color-primary-600": "#0d9488",
          "appkit-color-primary-700": "#0f766e",
          "appkit-color-primary-800": "#115e59",
          "appkit-color-primary-900": "#134e4a",
          "appkit-color-primary-950": "#042f2e",
          "appkit-color-secondary":     "#1a55f2",
          "appkit-color-secondary-50":  "#eef5ff",
          "appkit-color-secondary-100": "#d9e8ff",
          "appkit-color-secondary-200": "#bcd4ff",
          "appkit-color-secondary-300": "#8eb9ff",
          "appkit-color-secondary-400": "#5992ff",
          "appkit-color-secondary-500": "#3570fc",
          "appkit-color-secondary-600": "#1a55f2",
          "appkit-color-secondary-700": "#1343de",
          "appkit-color-secondary-800": "#1536b4",
          "appkit-color-secondary-900": "#18318e",
          "appkit-color-secondary-950": "#111e58",
          "appkit-color-bg":               "#fafaf9",
          "appkit-color-surface":          "#ffffff",
          "appkit-color-surface-elevated": "#ffffff",
          "appkit-color-surface-input":    "#ffffff",
          "appkit-color-border":           "#e7e5e4",
          "appkit-color-border-subtle":    "#f5f5f4",
          "appkit-color-text":             "#1c1917",
          "appkit-color-text-muted":       "#78716c",
          "appkit-color-text-faint":       "#a8a29e",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#059669",
          "appkit-color-success-surface":  "#ecfdf5",
          "appkit-color-warning":          "#d97706",
          "appkit-color-warning-surface":  "#fffbeb",
          "appkit-color-error":            "#dc2626",
          "appkit-color-error-surface":    "#fef2f2",
          "appkit-color-info":             "#0284c7",
          "appkit-color-info-surface":     "#f0f9ff",
          "appkit-color-focus-ring":       "#0d9488",
          "appkit-shadow-glow":      "0 0 0 1px rgba(13,148,136,0.10), 0 4px 16px -4px rgba(13,148,136,0.20)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(26,85,242,0.12), 0 4px 16px -4px rgba(26,85,242,0.22)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #0d9488, #1a55f2, #2dd4bf)",
          accent:           "linear-gradient(to right, var(--appkit-color-primary-600), var(--appkit-color-secondary-500))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface))",
          "section-cool":   "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-info-surface))",
          "section-mesh":   "radial-gradient(ellipse at top, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-secondary-50))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-primary), var(--appkit-color-secondary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-bg), var(--appkit-color-secondary-50))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-700) 0%, var(--appkit-color-primary-500) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-700), var(--appkit-color-secondary-600))",
        },
      },
      {
        id: "phantom-ice",
        name: "Phantom Ice",
        mode: "light" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#0284c7",
          "appkit-color-primary-50":  "#f0f9ff",
          "appkit-color-primary-100": "#e0f2fe",
          "appkit-color-primary-200": "#bae6fd",
          "appkit-color-primary-300": "#7dd3fc",
          "appkit-color-primary-400": "#38bdf8",
          "appkit-color-primary-500": "#0ea5e9",
          "appkit-color-primary-600": "#0284c7",
          "appkit-color-primary-700": "#0369a1",
          "appkit-color-primary-800": "#075985",
          "appkit-color-primary-900": "#0c4a6e",
          "appkit-color-primary-950": "#082f49",
          "appkit-color-secondary":     "#475569",
          "appkit-color-secondary-50":  "#f8fafc",
          "appkit-color-secondary-100": "#f1f5f9",
          "appkit-color-secondary-200": "#e2e8f0",
          "appkit-color-secondary-300": "#cbd5e1",
          "appkit-color-secondary-400": "#94a3b8",
          "appkit-color-secondary-500": "#64748b",
          "appkit-color-secondary-600": "#475569",
          "appkit-color-secondary-700": "#334155",
          "appkit-color-secondary-800": "#1e293b",
          "appkit-color-secondary-900": "#0f172a",
          "appkit-color-secondary-950": "#020617",
          "appkit-color-bg":               "#f0f9ff",
          "appkit-color-surface":          "#ffffff",
          "appkit-color-surface-elevated": "#ffffff",
          "appkit-color-surface-input":    "#f8fafc",
          "appkit-color-border":           "#e2e8f0",
          "appkit-color-border-subtle":    "#f1f5f9",
          "appkit-color-text":             "#0f172a",
          "appkit-color-text-muted":       "#475569",
          "appkit-color-text-faint":       "#94a3b8",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#059669",
          "appkit-color-success-surface":  "#ecfdf5",
          "appkit-color-warning":          "#d97706",
          "appkit-color-warning-surface":  "#fffbeb",
          "appkit-color-error":            "#dc2626",
          "appkit-color-error-surface":    "#fef2f2",
          "appkit-color-info":             "#0284c7",
          "appkit-color-info-surface":     "#f0f9ff",
          "appkit-color-focus-ring":       "#0284c7",
          "appkit-shadow-glow":      "0 0 0 1px rgba(2,132,199,0.10), 0 4px 16px -4px rgba(2,132,199,0.20)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(2,132,199,0.12), 0 4px 16px -4px rgba(2,132,199,0.22)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #0284c7, #475569, #38bdf8)",
          accent:           "linear-gradient(to right, var(--appkit-color-primary-600), var(--appkit-color-secondary-500))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface))",
          "section-cool":   "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-info-surface))",
          "section-mesh":   "radial-gradient(ellipse at top, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-secondary-50))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-bg), var(--appkit-color-primary-50))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-700) 0%, var(--appkit-color-primary-400) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-800), var(--appkit-color-secondary-600))",
        },
      },
      {
        id: "sunset",
        name: "Sunset",
        mode: "light" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#d97706",
          "appkit-color-primary-50":  "#fffbeb",
          "appkit-color-primary-100": "#fef3c7",
          "appkit-color-primary-200": "#fde68a",
          "appkit-color-primary-300": "#fcd34d",
          "appkit-color-primary-400": "#fbbf24",
          "appkit-color-primary-500": "#f59e0b",
          "appkit-color-primary-600": "#d97706",
          "appkit-color-primary-700": "#b45309",
          "appkit-color-primary-800": "#92400e",
          "appkit-color-primary-900": "#78350f",
          "appkit-color-primary-950": "#451a03",
          "appkit-color-secondary":     "#e11d48",
          "appkit-color-secondary-50":  "#fff1f2",
          "appkit-color-secondary-100": "#ffe4e6",
          "appkit-color-secondary-200": "#fecdd3",
          "appkit-color-secondary-300": "#fda4af",
          "appkit-color-secondary-400": "#fb7185",
          "appkit-color-secondary-500": "#f43f5e",
          "appkit-color-secondary-600": "#e11d48",
          "appkit-color-secondary-700": "#be123c",
          "appkit-color-secondary-800": "#9f1239",
          "appkit-color-secondary-900": "#881337",
          "appkit-color-secondary-950": "#4c0519",
          "appkit-color-bg":               "#fff7ed",
          "appkit-color-surface":          "#ffffff",
          "appkit-color-surface-elevated": "#ffffff",
          "appkit-color-surface-input":    "#fffbeb",
          "appkit-color-border":           "#fed7aa",
          "appkit-color-border-subtle":    "#ffedd5",
          "appkit-color-text":             "#431407",
          "appkit-color-text-muted":       "#9a3412",
          "appkit-color-text-faint":       "#c2410c",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#16a34a",
          "appkit-color-success-surface":  "#f0fdf4",
          "appkit-color-warning":          "#d97706",
          "appkit-color-warning-surface":  "#fffbeb",
          "appkit-color-error":            "#dc2626",
          "appkit-color-error-surface":    "#fef2f2",
          "appkit-color-info":             "#0284c7",
          "appkit-color-info-surface":     "#f0f9ff",
          "appkit-color-focus-ring":       "#f59e0b",
          "appkit-shadow-glow":      "0 0 0 1px rgba(245,158,11,0.10), 0 4px 16px -4px rgba(245,158,11,0.20)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(225,29,72,0.12), 0 4px 16px -4px rgba(225,29,72,0.22)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #d97706, #f43f5e, #e11d48)",
          accent:           "linear-gradient(to right, var(--appkit-color-primary-600), var(--appkit-color-secondary-500))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, #fffbeb, transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, #fff7ed, var(--appkit-color-surface))",
          "section-cool":   "linear-gradient(to bottom right, #fffbeb, #f0f9ff)",
          "section-mesh":   "radial-gradient(ellipse at top, #fffbeb, var(--appkit-color-surface), #fff1f2)",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-secondary), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, #fffbeb, var(--appkit-color-bg), #fffbeb)",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, #fffbeb, var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, #fff1f2, var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, #fff7ed, var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-700) 0%, var(--appkit-color-primary-500) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-700), var(--appkit-color-secondary-600))",
        },
      },
      /* ── DARK THEMES ───────────────────────────────────────── */
      {
        id: "shadow-abyss",
        name: "Teal Depths",
        mode: "dark" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#14b8a6",
          "appkit-color-primary-50":  "#f0fdfa",
          "appkit-color-primary-100": "#ccfbf1",
          "appkit-color-primary-200": "#99f6e4",
          "appkit-color-primary-300": "#5eead4",
          "appkit-color-primary-400": "#2dd4bf",
          "appkit-color-primary-500": "#14b8a6",
          "appkit-color-primary-600": "#0d9488",
          "appkit-color-primary-700": "#0f766e",
          "appkit-color-primary-800": "#115e59",
          "appkit-color-primary-900": "#134e4a",
          "appkit-color-primary-950": "#042f2e",
          "appkit-color-secondary":     "#3570fc",
          "appkit-color-secondary-50":  "#eef5ff",
          "appkit-color-secondary-100": "#d9e8ff",
          "appkit-color-secondary-200": "#bcd4ff",
          "appkit-color-secondary-300": "#8eb9ff",
          "appkit-color-secondary-400": "#5992ff",
          "appkit-color-secondary-500": "#3570fc",
          "appkit-color-secondary-600": "#1a55f2",
          "appkit-color-secondary-700": "#1343de",
          "appkit-color-secondary-800": "#1536b4",
          "appkit-color-secondary-900": "#18318e",
          "appkit-color-secondary-950": "#111e58",
          "appkit-color-bg":               "#042f2e",
          "appkit-color-surface":          "#115e59",
          "appkit-color-surface-elevated": "rgba(17,94,89,0.9)",
          "appkit-color-surface-input":    "rgba(19,78,74,0.6)",
          "appkit-color-border":           "#0f766e",
          "appkit-color-border-subtle":    "rgba(19,78,74,0.6)",
          "appkit-color-text":             "#f0fdfa",
          "appkit-color-text-muted":       "#99f6e4",
          "appkit-color-text-faint":       "#5eead4",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#34d399",
          "appkit-color-success-surface":  "rgba(6,78,59,0.25)",
          "appkit-color-warning":          "#fbbf24",
          "appkit-color-warning-surface":  "#1c1508",
          "appkit-color-error":            "#f87171",
          "appkit-color-error-surface":    "rgba(127,29,29,0.25)",
          "appkit-color-info":             "#38bdf8",
          "appkit-color-info-surface":     "rgba(12,74,110,0.25)",
          "appkit-color-focus-ring":       "#5eead4",
          "appkit-shadow-glow":      "0 0 0 1px rgba(20,184,166,0.20), 0 4px 16px -4px rgba(20,184,166,0.40)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(53,112,252,0.20), 0 4px 20px -4px rgba(53,112,252,0.35)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #14b8a6, #3570fc, #38bdf8)",
          accent:           "linear-gradient(to right, var(--appkit-color-info), var(--appkit-color-primary))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, rgba(20,184,166,0.15), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, rgba(53,112,252,0.10), transparent)",
          "section-cool":   "linear-gradient(to bottom right, rgba(56,189,248,0.10), transparent)",
          "section-mesh":   "radial-gradient(ellipse at top, rgba(20,184,166,0.15), var(--appkit-color-surface), rgba(56,189,248,0.08))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, rgba(20,184,166,0.12), var(--appkit-color-bg), rgba(56,189,248,0.10))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, rgba(20,184,166,0.12), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, rgba(56,189,248,0.10), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-400) 0%, var(--appkit-color-primary-300) 55%, var(--appkit-color-info) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-800), var(--appkit-color-secondary-800))",
        },
      },
      {
        id: "storm-champion",
        name: "Storm Champion",
        mode: "dark" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#2563eb",
          "appkit-color-primary-50":  "#eff6ff",
          "appkit-color-primary-100": "#dbeafe",
          "appkit-color-primary-200": "#bfdbfe",
          "appkit-color-primary-300": "#93c5fd",
          "appkit-color-primary-400": "#60a5fa",
          "appkit-color-primary-500": "#3b82f6",
          "appkit-color-primary-600": "#2563eb",
          "appkit-color-primary-700": "#1d4ed8",
          "appkit-color-primary-800": "#1e40af",
          "appkit-color-primary-900": "#1e3a8a",
          "appkit-color-primary-950": "#172554",
          "appkit-color-secondary":     "#ca8a04",
          "appkit-color-secondary-50":  "#fefce8",
          "appkit-color-secondary-100": "#fef9c3",
          "appkit-color-secondary-200": "#fef08a",
          "appkit-color-secondary-300": "#fde047",
          "appkit-color-secondary-400": "#facc15",
          "appkit-color-secondary-500": "#eab308",
          "appkit-color-secondary-600": "#ca8a04",
          "appkit-color-secondary-700": "#a16207",
          "appkit-color-secondary-800": "#854d0e",
          "appkit-color-secondary-900": "#713f12",
          "appkit-color-secondary-950": "#422006",
          "appkit-color-bg":               "#020c1b",
          "appkit-color-surface":          "#0a1628",
          "appkit-color-surface-elevated": "rgba(10,22,40,0.9)",
          "appkit-color-surface-input":    "rgba(20,40,70,0.6)",
          "appkit-color-border":           "#1e3a5f",
          "appkit-color-border-subtle":    "rgba(30,58,95,0.6)",
          "appkit-color-text":             "#fafafa",
          "appkit-color-text-muted":       "#93c5fd",
          "appkit-color-text-faint":       "#60a5fa",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#34d399",
          "appkit-color-success-surface":  "rgba(6,78,59,0.25)",
          "appkit-color-warning":          "#fbbf24",
          "appkit-color-warning-surface":  "#1c1508",
          "appkit-color-error":            "#f87171",
          "appkit-color-error-surface":    "rgba(127,29,29,0.25)",
          "appkit-color-info":             "#38bdf8",
          "appkit-color-info-surface":     "rgba(12,74,110,0.25)",
          "appkit-color-focus-ring":       "#60a5fa",
          "appkit-shadow-glow":      "0 0 0 1px rgba(37,99,235,0.20), 0 4px 16px -4px rgba(37,99,235,0.40)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(202,138,4,0.20), 0 4px 20px -4px rgba(202,138,4,0.35)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #2563eb, #ca8a04, #ef4444)",
          accent:           "linear-gradient(to right, var(--appkit-color-secondary), var(--appkit-color-primary))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, rgba(37,99,235,0.15), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, rgba(202,138,4,0.10), transparent)",
          "section-cool":   "linear-gradient(to bottom right, rgba(37,99,235,0.12), transparent)",
          "section-mesh":   "radial-gradient(ellipse at top, rgba(37,99,235,0.15), var(--appkit-color-surface), rgba(202,138,4,0.08))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-secondary))",
          spotlight:        "linear-gradient(to bottom right, rgba(37,99,235,0.12), var(--appkit-color-bg), rgba(202,138,4,0.08))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, rgba(37,99,235,0.12), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, rgba(202,138,4,0.10), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-400) 0%, var(--appkit-color-primary-300) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-800), var(--appkit-color-primary-900))",
        },
      },
      {
        id: "cobalt-night",
        name: "Cobalt Night",
        mode: "dark" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#3570fc",
          "appkit-color-primary-50":  "#eef5ff",
          "appkit-color-primary-100": "#d9e8ff",
          "appkit-color-primary-200": "#bcd4ff",
          "appkit-color-primary-300": "#8eb9ff",
          "appkit-color-primary-400": "#5992ff",
          "appkit-color-primary-500": "#3570fc",
          "appkit-color-primary-600": "#1a55f2",
          "appkit-color-primary-700": "#1343de",
          "appkit-color-primary-800": "#1536b4",
          "appkit-color-primary-900": "#18318e",
          "appkit-color-primary-950": "#111e58",
          "appkit-color-secondary":     "#65c408",
          "appkit-color-secondary-50":  "#f3ffe3",
          "appkit-color-secondary-100": "#e4ffc5",
          "appkit-color-secondary-200": "#c8ff90",
          "appkit-color-secondary-300": "#a3f550",
          "appkit-color-secondary-400": "#84e122",
          "appkit-color-secondary-500": "#65c408",
          "appkit-color-secondary-600": "#509c02",
          "appkit-color-secondary-700": "#3e7708",
          "appkit-color-secondary-800": "#345e0d",
          "appkit-color-secondary-900": "#2c5011",
          "appkit-color-secondary-950": "#142d03",
          "appkit-color-bg":               "#111e58",
          "appkit-color-surface":          "#1536b4",
          "appkit-color-surface-elevated": "rgba(21,54,180,0.9)",
          "appkit-color-surface-input":    "rgba(24,49,142,0.6)",
          "appkit-color-border":           "#1343de",
          "appkit-color-border-subtle":    "rgba(24,49,142,0.6)",
          "appkit-color-text":             "#eef5ff",
          "appkit-color-text-muted":       "#bcd4ff",
          "appkit-color-text-faint":       "#8eb9ff",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#4ade80",
          "appkit-color-success-surface":  "rgba(6,78,59,0.25)",
          "appkit-color-warning":          "#fbbf24",
          "appkit-color-warning-surface":  "#1c1508",
          "appkit-color-error":            "#f87171",
          "appkit-color-error-surface":    "rgba(127,29,29,0.25)",
          "appkit-color-info":             "#38bdf8",
          "appkit-color-info-surface":     "rgba(12,74,110,0.25)",
          "appkit-color-focus-ring":       "#8eb9ff",
          "appkit-shadow-glow":      "0 0 0 1px rgba(53,112,252,0.20), 0 4px 16px -4px rgba(53,112,252,0.40)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(101,196,8,0.20), 0 4px 20px -4px rgba(101,196,8,0.35)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #3570fc, #65c408, #8eb9ff)",
          accent:           "linear-gradient(to right, var(--appkit-color-secondary), var(--appkit-color-primary))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, rgba(53,112,252,0.20), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, rgba(101,196,8,0.10), transparent)",
          "section-cool":   "linear-gradient(to bottom right, rgba(53,112,252,0.20), transparent)",
          "section-mesh":   "radial-gradient(ellipse at top, rgba(53,112,252,0.20), var(--appkit-color-surface), rgba(101,196,8,0.10))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, rgba(53,112,252,0.15), var(--appkit-color-bg), rgba(53,112,252,0.15))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, rgba(53,112,252,0.20), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, rgba(101,196,8,0.15), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-secondary-400) 0%, var(--appkit-color-primary-400) 55%, var(--appkit-color-primary-300) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-950), var(--appkit-color-primary-900))",
        },
      },
    ],
    // Reverted 2026-08-15 — the live site had drifted onto the "Teal Tide" /
    // "Teal Depths" custom pair (added in a prior session's theme-experiment
    // sweep), which is not the brand's cobalt+lime/hot-pink identity. The
    // custom themes above stay available as selectable options (nothing
    // deleted); this just restores the appkit built-ins as what's live by
    // default. buildThemeRegistry() always resolves "default-light"/
    // "default-dark" to the true built-in records regardless of this list.
    defaultLightThemeId: "default-light",
    defaultDarkThemeId: "default-dark",
  },
};
