/*
 * WHY: Seeds the singleton site-settings doc for YGO marketplace.
 * WHAT: 1 document — branding, SEO, features, legal, commissions, credentials, ad inventory.
 *
 * EXPORTS:
 *   siteSettingsSeedData — Partial<SiteSettingsDocument> for seed runner
 *
 * @tag domain:site-settings,admin
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/index.ts,seed/runner.ts,SeedPanel
 * @tag sideEffects:none
 */

import { getDefaultPhonePrefix, getSeedLocale } from "./seed-market-config";

const _phonePrefix = getDefaultPhonePrefix();
const _locale = getSeedLocale();

import type { SiteSettingsDocument } from "../features/admin/schemas";
import { seedExtMedia } from "./_helpers/media";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

const adPlacementsSeed = [
  {
    id: "homepage-hero-banner",
    label: "Homepage Hero Banner",
    enabled: true,
    reservedHeight: 90,
  },
  {
    id: "listing-sidebar-top",
    label: "Listing Sidebar Top",
    enabled: true,
    reservedHeight: 90,
  },
  {
    id: "listing-sidebar-bottom",
    label: "Listing Sidebar Bottom",
    enabled: true,
    reservedHeight: 90,
  },
  {
    id: "search-inline",
    label: "Search Inline",
    enabled: true,
    reservedHeight: 90,
  },
] as const;

export const siteSettingsSeedData: Partial<SiteSettingsDocument> & {
  adSettings: {
    consentRequired: boolean;
    placements: readonly {
      id: string;
      label: string;
      enabled: boolean;
      reservedHeight: number;
    }[];
    providerCredentials: {
      adsenseClientId: string;
      thirdPartyScriptUrl: string;
    };
    inventory: {
      id: string;
      name: string;
      provider: "manual" | "adsense" | "thirdParty";
      status: "draft" | "active" | "scheduled" | "paused";
      placementIds: string[];
      requiresConsent: boolean;
      priority: number;
      startAt?: string;
      endAt?: string;
      createdAt: string;
      updatedAt: string;
      updatedBy: string;
      creative: {
        title?: string;
        body?: string;
        imageUrl?: string;
        ctaLabel?: string;
        ctaHref?: string;
        adsenseSlot?: string;
        thirdPartyUrl?: string;
      };
    }[];
  };
} = {
  id: "global",
  siteName: "LetItRip",
  motto: "India's #1 Yu-Gi-Oh! Collectibles Marketplace — Singles · Sealed · Graded Slabs · Accessories",
  announcementBar: {
    enabled: true,
    message: "🎉 Up to 25% off LOB singles + Free deck box with 2 sealed booster boxes — See Events for codes",
  },
  watermark: {
    type: "text",
    text: "letitrip.in",
    imageUrl: "",
    size: 30,
    opacity: 20,
  },
  logo: {
    url: "",
    alt: "LetItRip Logo",
    format: "svg",
  },
  background: {
    light: {
      type: "gradient",
      value: "linear-gradient(135deg, #f0f4ff 0%, #f9fafb 100%)",
      overlay: {
        enabled: false,
        color: "#000000",
        opacity: 0,
      },
    },
    dark: {
      type: "gradient",
      value: "linear-gradient(135deg, #020617 0%, #0f172a 100%)",
      overlay: {
        enabled: false,
        color: "#000000",
        opacity: 0,
      },
    },
  },
  contact: {
    email: "support@letitrip.in",
    phone: `${_phonePrefix}-9876543210`,
    address: `123, Marketplace Street, ${_locale.cities[0][0]}, ${_locale.cities[0][1]} - ${_locale.cities[0][2]}, ${_locale.countryName}`,
    upiVpa: "letitrip@upi",
    whatsappNumber: `${_phonePrefix.replace(/[^+\d]/g, "")}9876543210`,
  },
  payment: {
    razorpayEnabled: true,
    upiManualEnabled: true,
    codEnabled: false,
  },
  socialLinks: {
    facebook: "https://facebook.com/letitrip",
    twitter: "https://twitter.com/letitrip",
    instagram: "https://instagram.com/letitrip",
    linkedin: "https://linkedin.com/company/letitrip",
  },
  emailSettings: {
    fromName: "LetItRip",
    fromEmail: "noreply@letitrip.in",
    replyTo: "support@letitrip.in",
  },
  seo: {
    defaultTitle:
      "LetItRip — Yu-Gi-Oh! Singles, Sealed Booster Boxes, PSA Graded Slabs | India's YGO Marketplace",
    defaultDescription:
      "Buy, sell, and auction Yu-Gi-Oh! trading cards on India's premier Duel Monsters marketplace. LOB 1st Edition, Blue-Eyes White Dragon, Dark Magician, Exodia — singles, sealed products, PSA/BGS/CGC graded slabs from verified sellers.",
    keywords: [
      "yugioh cards india",
      "yu-gi-oh tcg india",
      "blue-eyes white dragon",
      "dark magician",
      "exodia the forbidden one",
      "lob 1st edition",
      "psa graded slabs",
      "sealed booster box",
      "collectibles marketplace india",
      "live auction yugioh",
      "pre-order konami",
      "duel monsters cards",
    ],
    ogImage: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
  },
  features: [
    {
      id: "feature_001",
      name: "Huge Catalogue",
      description: "200+ Yu-Gi-Oh! Cards & Sealed Products",
      icon: "📦",
      enabled: true,
    },
    {
      id: "feature_002",
      name: "Fast Shipping",
      description: "Delivered in 3–7 Days Across India",
      icon: "🚚",
      enabled: true,
    },
    {
      id: "feature_003",
      name: "Authentic Only",
      description: "Verified Genuine Konami Products",
      icon: "✅",
      enabled: true,
    },
    {
      id: "feature_004",
      name: "Secure Payments",
      description: "Escrow-Protected Transactions",
      icon: "🔒",
      enabled: true,
    },
    {
      id: "feature_005",
      name: "Live Auctions",
      description: "Bid on Rare & Graded YGO Cards",
      icon: "🏆",
      enabled: true,
    },
    {
      id: "feature_006",
      name: "Pre-Orders",
      description: "Reserve Upcoming Konami Set Releases",
      icon: "⏳",
      enabled: true,
    },
  ],
  legalPages: {
    termsOfService: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Terms of Service" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "Welcome to LetItRip. By accessing our platform, you agree to these terms...",
            },
          ],
        },
      ],
    }),
    privacyPolicy: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Privacy Policy" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "Your privacy is important to us. This policy describes how we collect and use your data...",
            },
          ],
        },
      ],
    }),
    refundPolicy: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Refund Policy" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "We offer a 7-day return and refund policy on most products. Items must be in original condition...",
            },
          ],
        },
      ],
    }),
    shippingPolicy: JSON.stringify({
      type: "doc",
      content: [
        {
          type: "heading",
          attrs: { level: 1 },
          content: [{ type: "text", text: "Shipping Policy" }],
        },
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "We offer free shipping on orders above ₹999. Standard delivery takes 3-7 business days...",
            },
          ],
        },
      ],
    }),
  },
  shipping: {
    estimatedDays: 7,
    minOrderForFree: 999,
  },
  returns: {
    windowDays: 7,
  },
  faq: {
    variables: {
      shippingDays: 7,
      minOrderValue: 999,
      returnWindow: 7,
      supportEmail: "support@letitrip.in",
      supportPhone: `${_phonePrefix}-9876543210`,
      codDeposit: 0.1,
    },
  },
  createdAt: daysAgo(799),
  updatedAt: daysAgo(29),
  navbarConfig: {
    hiddenNavItems: [],
  },
  footerConfig: {
    trustBar: {
      enabled: true,
      items: [
        { icon: "🚚", label: "Free Shipping", visible: true },
        { icon: "🔄", label: "Easy Returns", visible: true },
        { icon: "🔒", label: "Secure Payment", visible: true },
        { icon: "🎧", label: "24/7 Support", visible: true },
        { icon: "✅", label: "Authentic Sellers", visible: true },
      ],
    },
    newsletterEnabled: true,
  },
  adSettings: {
    consentRequired: true,
    placements: adPlacementsSeed,
    providerCredentials: {
      adsenseClientId: "ca-pub-0000000000000000",
      thirdPartyScriptUrl: seedExtMedia("https://cdn.example-ads.com/ad-runtime.js"),
    },
    inventory: [
      {
        id: "ad-homepage-hero-ygo-drop",
        name: "YGO Card Drop Hero Banner",
        provider: "manual",
        status: "active",
        placementIds: ["homepage-hero-banner"],
        requiresConsent: true,
        priority: 100,
        createdAt: daysAgo(20).toISOString(),
        updatedAt: daysAgo(2).toISOString(),
        updatedBy: "user-admin-letitrip",
        creative: {
          title: "LOB 1st Edition Mega Drop",
          body: "Limited Legend of Blue Eyes singles and sealed packs — this weekend only.",
          imageUrl: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/89631139.jpg"),
          ctaLabel: "Explore Deals",
          ctaHref: "/promotions/deals",
        },
      },
      {
        id: "ad-listing-sidebar-auction-boost",
        name: "Sidebar Auction Boost",
        provider: "manual",
        status: "active",
        placementIds: ["listing-sidebar-top", "listing-sidebar-bottom"],
        requiresConsent: true,
        priority: 80,
        createdAt: daysAgo(12).toISOString(),
        updatedAt: daysAgo(1).toISOString(),
        updatedBy: "user-admin-letitrip",
        creative: {
          title: "Graded Slab Auctions",
          body: "PSA 10 Blue-Eyes and Dark Magician auctions ending this week.",
          imageUrl: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/46986414.jpg"),
          ctaLabel: "View Auctions",
          ctaHref: "/auctions",
        },
      },
      {
        id: "ad-search-inline-exodia",
        name: "Search Spotlight — Exodia",
        provider: "manual",
        status: "scheduled",
        placementIds: ["search-inline"],
        requiresConsent: true,
        priority: 70,
        startAt: daysAgo(-3).toISOString(),
        endAt: daysAgo(-10).toISOString(),
        createdAt: daysAgo(1).toISOString(),
        updatedAt: daysAgo(1).toISOString(),
        updatedBy: "user-admin-letitrip",
        creative: {
          title: "Complete Your Exodia",
          body: "All 5 Forbidden One pieces available — LOB to modern reprints.",
          imageUrl: seedExtMedia("https://images.ygoprodeck.com/images/cards/cropped/33396948.jpg"),
          ctaLabel: "Browse Exodia",
          ctaHref: "/products?q=exodia",
        },
      },
    ],
  },
  commissions: {
    platformFeePercent: 5,
    gstPercent: 18,
    minimumTransactionFee: 0,
    gatewayFeePercent: 2,
    codDepositPercent: 10,
    sellerShippingFixed: 0,
    platformShippingPercent: 0,
    platformShippingFixedMin: 0,
    autoPayoutWindowDays: 7,
    payoutHoldDays: 2,
    minPayoutAmount: 100,
    auctionListingFee: 0,
    preOrderListingFee: 0,
    featuredSlotFee: 999,
    promotedSlotFee: 499,
  },
  featureFlags: {
    chats: true,
    smsVerification: true,
    translations: true,
    wishlists: true,
    auctions: false,
    reviews: true,
    events: false,
    blog: false,
    coupons: false,
    notifications: true,
    sellerRegistration: true,
    preOrders: false,
    seedPanel: true,
    adminCheckoutBypass: false,
    // P-1 MVP: only standard listing type active; others unlocked in later patches.
    listingTypes: {
      standard: true,
      auction: false,
      "pre-order": false,
      "prize-draw": false,
      bundle: false,
      classified: false,
      "digital-code": false,
      live: false,
    },
  },
  credentials: {
    razorpayKeyId: "rzp_test_PLACEHOLDER",
    razorpayKeySecret: "secret_PLACEHOLDER",
    razorpayWebhookSecret: "webhook_PLACEHOLDER",
    resendApiKey: "re_PLACEHOLDER",
    whatsappApiKey: "wa_PLACEHOLDER",
    whatsappPhoneNumberId: "",
    whatsappCloudApiToken: "",
    whatsappAdminNotifyNumbers: "",
    shiprocketEmail: "shiprocket@letitrip.in",
    shiprocketPassword: "shiprocket_PLACEHOLDER",
    metaAppId: "meta_app_PLACEHOLDER",
    metaAppSecret: "meta_secret_PLACEHOLDER",
    metaPageAccessToken: "meta_page_token_PLACEHOLDER",
    metaPageId: "meta_page_id_PLACEHOLDER",
    tiktokClientKey: "tiktok_client_key_PLACEHOLDER",
    tiktokClientSecret: "tiktok_client_secret_PLACEHOLDER",
    tiktokAccessToken: "tiktok_access_token_PLACEHOLDER",
    deviantartClientId: "deviantart_client_id_PLACEHOLDER",
    deviantartClientSecret: "deviantart_client_secret_PLACEHOLDER",
  },
  notificationChannels: {
    inApp: { enabled: true, readOnly: true },
    email: { enabled: true, minPriority: "normal" },
    whatsapp: { enabled: true, minPriority: "high", otpEnabled: true },
    sms: { enabled: true, minPriority: "high" },
  },
  actionConfig: {},
  navConfig: {},
  disabledRoutes: [],
  theme: {
    themes: [
      /* ── LIGHT THEMES ──────────────────────────────────────── */
      {
        id: "crimson-warrior",
        name: "Crimson Warrior",
        mode: "light" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#dc2626",
          "appkit-color-primary-50":  "#fef2f2",
          "appkit-color-primary-100": "#fee2e2",
          "appkit-color-primary-200": "#fecaca",
          "appkit-color-primary-300": "#fca5a5",
          "appkit-color-primary-400": "#f87171",
          "appkit-color-primary-500": "#ef4444",
          "appkit-color-primary-600": "#dc2626",
          "appkit-color-primary-700": "#b91c1c",
          "appkit-color-primary-800": "#991b1b",
          "appkit-color-primary-900": "#7f1d1d",
          "appkit-color-primary-950": "#450a0a",
          "appkit-color-secondary":     "#d97706",
          "appkit-color-secondary-50":  "#fffbeb",
          "appkit-color-secondary-100": "#fef3c7",
          "appkit-color-secondary-200": "#fde68a",
          "appkit-color-secondary-300": "#fcd34d",
          "appkit-color-secondary-400": "#fbbf24",
          "appkit-color-secondary-500": "#f59e0b",
          "appkit-color-secondary-600": "#d97706",
          "appkit-color-secondary-700": "#b45309",
          "appkit-color-secondary-800": "#92400e",
          "appkit-color-secondary-900": "#78350f",
          "appkit-color-secondary-950": "#451a03",
          "appkit-color-bg":               "#fafaf9",
          "appkit-color-surface":          "#ffffff",
          "appkit-color-surface-elevated": "#ffffff",
          "appkit-color-surface-input":    "#ffffff",
          "appkit-color-border":           "#e7e5e4",
          "appkit-color-border-subtle":    "#f5f5f4",
          "appkit-color-text":             "#1c1917",
          "appkit-color-text-muted":       "#78716c",
          "appkit-color-text-faint":       "#a8a29e",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#059669",
          "appkit-color-success-surface":  "#ecfdf5",
          "appkit-color-warning":          "#d97706",
          "appkit-color-warning-surface":  "#fffbeb",
          "appkit-color-error":            "#dc2626",
          "appkit-color-error-surface":    "#fef2f2",
          "appkit-color-info":             "#0284c7",
          "appkit-color-info-surface":     "#f0f9ff",
          "appkit-color-focus-ring":       "#dc2626",
          "appkit-shadow-glow":      "0 0 0 1px rgba(220,38,38,0.10), 0 4px 16px -4px rgba(220,38,38,0.20)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(220,38,38,0.12), 0 4px 16px -4px rgba(220,38,38,0.22)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #dc2626, #d97706, #0284c7)",
          accent:           "linear-gradient(to right, var(--appkit-color-primary-600), var(--appkit-color-secondary-500))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface))",
          "section-cool":   "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-info-surface))",
          "section-mesh":   "radial-gradient(ellipse at top, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-secondary-50))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-primary), var(--appkit-color-secondary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-bg), var(--appkit-color-secondary-50))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-700) 0%, var(--appkit-color-primary-500) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-700), var(--appkit-color-secondary-600))",
        },
      },
      {
        id: "phantom-ice",
        name: "Phantom Ice",
        mode: "light" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#0284c7",
          "appkit-color-primary-50":  "#f0f9ff",
          "appkit-color-primary-100": "#e0f2fe",
          "appkit-color-primary-200": "#bae6fd",
          "appkit-color-primary-300": "#7dd3fc",
          "appkit-color-primary-400": "#38bdf8",
          "appkit-color-primary-500": "#0ea5e9",
          "appkit-color-primary-600": "#0284c7",
          "appkit-color-primary-700": "#0369a1",
          "appkit-color-primary-800": "#075985",
          "appkit-color-primary-900": "#0c4a6e",
          "appkit-color-primary-950": "#082f49",
          "appkit-color-secondary":     "#475569",
          "appkit-color-secondary-50":  "#f8fafc",
          "appkit-color-secondary-100": "#f1f5f9",
          "appkit-color-secondary-200": "#e2e8f0",
          "appkit-color-secondary-300": "#cbd5e1",
          "appkit-color-secondary-400": "#94a3b8",
          "appkit-color-secondary-500": "#64748b",
          "appkit-color-secondary-600": "#475569",
          "appkit-color-secondary-700": "#334155",
          "appkit-color-secondary-800": "#1e293b",
          "appkit-color-secondary-900": "#0f172a",
          "appkit-color-secondary-950": "#020617",
          "appkit-color-bg":               "#f0f9ff",
          "appkit-color-surface":          "#ffffff",
          "appkit-color-surface-elevated": "#ffffff",
          "appkit-color-surface-input":    "#f8fafc",
          "appkit-color-border":           "#e2e8f0",
          "appkit-color-border-subtle":    "#f1f5f9",
          "appkit-color-text":             "#0f172a",
          "appkit-color-text-muted":       "#475569",
          "appkit-color-text-faint":       "#94a3b8",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#059669",
          "appkit-color-success-surface":  "#ecfdf5",
          "appkit-color-warning":          "#d97706",
          "appkit-color-warning-surface":  "#fffbeb",
          "appkit-color-error":            "#dc2626",
          "appkit-color-error-surface":    "#fef2f2",
          "appkit-color-info":             "#0284c7",
          "appkit-color-info-surface":     "#f0f9ff",
          "appkit-color-focus-ring":       "#0284c7",
          "appkit-shadow-glow":      "0 0 0 1px rgba(2,132,199,0.10), 0 4px 16px -4px rgba(2,132,199,0.20)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(2,132,199,0.12), 0 4px 16px -4px rgba(2,132,199,0.22)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #0284c7, #475569, #38bdf8)",
          accent:           "linear-gradient(to right, var(--appkit-color-primary-600), var(--appkit-color-secondary-500))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface))",
          "section-cool":   "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-info-surface))",
          "section-mesh":   "radial-gradient(ellipse at top, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-secondary-50))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-bg), var(--appkit-color-primary-50))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, var(--appkit-color-primary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, var(--appkit-color-secondary-50), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-700) 0%, var(--appkit-color-primary-400) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-800), var(--appkit-color-secondary-600))",
        },
      },
      {
        id: "sunset",
        name: "Sunset",
        mode: "light" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#d97706",
          "appkit-color-primary-50":  "#fffbeb",
          "appkit-color-primary-100": "#fef3c7",
          "appkit-color-primary-200": "#fde68a",
          "appkit-color-primary-300": "#fcd34d",
          "appkit-color-primary-400": "#fbbf24",
          "appkit-color-primary-500": "#f59e0b",
          "appkit-color-primary-600": "#d97706",
          "appkit-color-primary-700": "#b45309",
          "appkit-color-primary-800": "#92400e",
          "appkit-color-primary-900": "#78350f",
          "appkit-color-primary-950": "#451a03",
          "appkit-color-secondary":     "#e11d48",
          "appkit-color-secondary-50":  "#fff1f2",
          "appkit-color-secondary-100": "#ffe4e6",
          "appkit-color-secondary-200": "#fecdd3",
          "appkit-color-secondary-300": "#fda4af",
          "appkit-color-secondary-400": "#fb7185",
          "appkit-color-secondary-500": "#f43f5e",
          "appkit-color-secondary-600": "#e11d48",
          "appkit-color-secondary-700": "#be123c",
          "appkit-color-secondary-800": "#9f1239",
          "appkit-color-secondary-900": "#881337",
          "appkit-color-secondary-950": "#4c0519",
          "appkit-color-bg":               "#fff7ed",
          "appkit-color-surface":          "#ffffff",
          "appkit-color-surface-elevated": "#ffffff",
          "appkit-color-surface-input":    "#fffbeb",
          "appkit-color-border":           "#fed7aa",
          "appkit-color-border-subtle":    "#ffedd5",
          "appkit-color-text":             "#431407",
          "appkit-color-text-muted":       "#9a3412",
          "appkit-color-text-faint":       "#c2410c",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#16a34a",
          "appkit-color-success-surface":  "#f0fdf4",
          "appkit-color-warning":          "#d97706",
          "appkit-color-warning-surface":  "#fffbeb",
          "appkit-color-error":            "#dc2626",
          "appkit-color-error-surface":    "#fef2f2",
          "appkit-color-info":             "#0284c7",
          "appkit-color-info-surface":     "#f0f9ff",
          "appkit-color-focus-ring":       "#f59e0b",
          "appkit-shadow-glow":      "0 0 0 1px rgba(245,158,11,0.10), 0 4px 16px -4px rgba(245,158,11,0.20)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(225,29,72,0.12), 0 4px 16px -4px rgba(225,29,72,0.22)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #d97706, #f43f5e, #e11d48)",
          accent:           "linear-gradient(to right, var(--appkit-color-primary-600), var(--appkit-color-secondary-500))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, #fffbeb, transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, #fff7ed, var(--appkit-color-surface))",
          "section-cool":   "linear-gradient(to bottom right, #fffbeb, #f0f9ff)",
          "section-mesh":   "radial-gradient(ellipse at top, #fffbeb, var(--appkit-color-surface), #fff1f2)",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-secondary), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, #fffbeb, var(--appkit-color-bg), #fffbeb)",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, #fffbeb, var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, #fff1f2, var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, #fff7ed, var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-700) 0%, var(--appkit-color-primary-500) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-700), var(--appkit-color-secondary-600))",
        },
      },
      /* ── DARK THEMES ───────────────────────────────────────── */
      {
        id: "shadow-abyss",
        name: "Shadow Abyss",
        mode: "dark" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#7c3aed",
          "appkit-color-primary-50":  "#f5f3ff",
          "appkit-color-primary-100": "#ede9fe",
          "appkit-color-primary-200": "#ddd6fe",
          "appkit-color-primary-300": "#c4b5fd",
          "appkit-color-primary-400": "#a78bfa",
          "appkit-color-primary-500": "#8b5cf6",
          "appkit-color-primary-600": "#7c3aed",
          "appkit-color-primary-700": "#6d28d9",
          "appkit-color-primary-800": "#5b21b6",
          "appkit-color-primary-900": "#4c1d95",
          "appkit-color-primary-950": "#2e1065",
          "appkit-color-secondary":     "#a21caf",
          "appkit-color-secondary-50":  "#fdf4ff",
          "appkit-color-secondary-100": "#fae8ff",
          "appkit-color-secondary-200": "#f5d0fe",
          "appkit-color-secondary-300": "#f0abfc",
          "appkit-color-secondary-400": "#e879f9",
          "appkit-color-secondary-500": "#d946ef",
          "appkit-color-secondary-600": "#c026d3",
          "appkit-color-secondary-700": "#a21caf",
          "appkit-color-secondary-800": "#86198f",
          "appkit-color-secondary-900": "#701a75",
          "appkit-color-secondary-950": "#4a044e",
          "appkit-color-bg":               "#0a000f",
          "appkit-color-surface":          "#12001e",
          "appkit-color-surface-elevated": "rgba(18,0,30,0.9)",
          "appkit-color-surface-input":    "rgba(30,0,46,0.6)",
          "appkit-color-border":           "#2d1b4e",
          "appkit-color-border-subtle":    "rgba(45,27,78,0.6)",
          "appkit-color-text":             "#fafafa",
          "appkit-color-text-muted":       "#c4b5fd",
          "appkit-color-text-faint":       "#a78bfa",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#34d399",
          "appkit-color-success-surface":  "rgba(6,78,59,0.25)",
          "appkit-color-warning":          "#fbbf24",
          "appkit-color-warning-surface":  "#1c1508",
          "appkit-color-error":            "#f87171",
          "appkit-color-error-surface":    "rgba(127,29,29,0.25)",
          "appkit-color-info":             "#38bdf8",
          "appkit-color-info-surface":     "rgba(12,74,110,0.25)",
          "appkit-color-focus-ring":       "#a78bfa",
          "appkit-shadow-glow":      "0 0 0 1px rgba(124,58,237,0.20), 0 4px 16px -4px rgba(124,58,237,0.40)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(162,28,175,0.20), 0 4px 20px -4px rgba(162,28,175,0.35)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #7c3aed, #a21caf, #38bdf8)",
          accent:           "linear-gradient(to right, var(--appkit-color-info), var(--appkit-color-primary))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, rgba(124,58,237,0.15), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, rgba(162,28,175,0.10), transparent)",
          "section-cool":   "linear-gradient(to bottom right, rgba(56,189,248,0.10), transparent)",
          "section-mesh":   "radial-gradient(ellipse at top, rgba(124,58,237,0.15), var(--appkit-color-surface), rgba(56,189,248,0.08))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, rgba(124,58,237,0.12), var(--appkit-color-bg), rgba(56,189,248,0.10))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, rgba(124,58,237,0.12), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, rgba(56,189,248,0.10), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-400) 0%, var(--appkit-color-primary-300) 55%, var(--appkit-color-info) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-800), var(--appkit-color-secondary-800))",
        },
      },
      {
        id: "storm-champion",
        name: "Storm Champion",
        mode: "dark" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#2563eb",
          "appkit-color-primary-50":  "#eff6ff",
          "appkit-color-primary-100": "#dbeafe",
          "appkit-color-primary-200": "#bfdbfe",
          "appkit-color-primary-300": "#93c5fd",
          "appkit-color-primary-400": "#60a5fa",
          "appkit-color-primary-500": "#3b82f6",
          "appkit-color-primary-600": "#2563eb",
          "appkit-color-primary-700": "#1d4ed8",
          "appkit-color-primary-800": "#1e40af",
          "appkit-color-primary-900": "#1e3a8a",
          "appkit-color-primary-950": "#172554",
          "appkit-color-secondary":     "#ca8a04",
          "appkit-color-secondary-50":  "#fefce8",
          "appkit-color-secondary-100": "#fef9c3",
          "appkit-color-secondary-200": "#fef08a",
          "appkit-color-secondary-300": "#fde047",
          "appkit-color-secondary-400": "#facc15",
          "appkit-color-secondary-500": "#eab308",
          "appkit-color-secondary-600": "#ca8a04",
          "appkit-color-secondary-700": "#a16207",
          "appkit-color-secondary-800": "#854d0e",
          "appkit-color-secondary-900": "#713f12",
          "appkit-color-secondary-950": "#422006",
          "appkit-color-bg":               "#020c1b",
          "appkit-color-surface":          "#0a1628",
          "appkit-color-surface-elevated": "rgba(10,22,40,0.9)",
          "appkit-color-surface-input":    "rgba(20,40,70,0.6)",
          "appkit-color-border":           "#1e3a5f",
          "appkit-color-border-subtle":    "rgba(30,58,95,0.6)",
          "appkit-color-text":             "#fafafa",
          "appkit-color-text-muted":       "#93c5fd",
          "appkit-color-text-faint":       "#60a5fa",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#34d399",
          "appkit-color-success-surface":  "rgba(6,78,59,0.25)",
          "appkit-color-warning":          "#fbbf24",
          "appkit-color-warning-surface":  "#1c1508",
          "appkit-color-error":            "#f87171",
          "appkit-color-error-surface":    "rgba(127,29,29,0.25)",
          "appkit-color-info":             "#38bdf8",
          "appkit-color-info-surface":     "rgba(12,74,110,0.25)",
          "appkit-color-focus-ring":       "#60a5fa",
          "appkit-shadow-glow":      "0 0 0 1px rgba(37,99,235,0.20), 0 4px 16px -4px rgba(37,99,235,0.40)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(202,138,4,0.20), 0 4px 20px -4px rgba(202,138,4,0.35)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #2563eb, #ca8a04, #ef4444)",
          accent:           "linear-gradient(to right, var(--appkit-color-secondary), var(--appkit-color-primary))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, rgba(37,99,235,0.15), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, rgba(202,138,4,0.10), transparent)",
          "section-cool":   "linear-gradient(to bottom right, rgba(37,99,235,0.12), transparent)",
          "section-mesh":   "radial-gradient(ellipse at top, rgba(37,99,235,0.15), var(--appkit-color-surface), rgba(202,138,4,0.08))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-secondary))",
          spotlight:        "linear-gradient(to bottom right, rgba(37,99,235,0.12), var(--appkit-color-bg), rgba(202,138,4,0.08))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, rgba(37,99,235,0.12), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, rgba(202,138,4,0.10), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-primary-400) 0%, var(--appkit-color-primary-300) 55%, var(--appkit-color-secondary-400) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-800), var(--appkit-color-primary-900))",
        },
      },
      {
        id: "cobalt-night",
        name: "Cobalt Night",
        mode: "dark" as const,
        builtIn: false,
        tokens: {
          "appkit-color-primary":     "#3570fc",
          "appkit-color-primary-50":  "#eef5ff",
          "appkit-color-primary-100": "#d9e8ff",
          "appkit-color-primary-200": "#bcd4ff",
          "appkit-color-primary-300": "#8eb9ff",
          "appkit-color-primary-400": "#5992ff",
          "appkit-color-primary-500": "#3570fc",
          "appkit-color-primary-600": "#1a55f2",
          "appkit-color-primary-700": "#1343de",
          "appkit-color-primary-800": "#1536b4",
          "appkit-color-primary-900": "#18318e",
          "appkit-color-primary-950": "#111e58",
          "appkit-color-secondary":     "#65c408",
          "appkit-color-secondary-50":  "#f3ffe3",
          "appkit-color-secondary-100": "#e4ffc5",
          "appkit-color-secondary-200": "#c8ff90",
          "appkit-color-secondary-300": "#a3f550",
          "appkit-color-secondary-400": "#84e122",
          "appkit-color-secondary-500": "#65c408",
          "appkit-color-secondary-600": "#509c02",
          "appkit-color-secondary-700": "#3e7708",
          "appkit-color-secondary-800": "#345e0d",
          "appkit-color-secondary-900": "#2c5011",
          "appkit-color-secondary-950": "#142d03",
          "appkit-color-bg":               "#111e58",
          "appkit-color-surface":          "#1536b4",
          "appkit-color-surface-elevated": "rgba(21,54,180,0.9)",
          "appkit-color-surface-input":    "rgba(24,49,142,0.6)",
          "appkit-color-border":           "#1343de",
          "appkit-color-border-subtle":    "rgba(24,49,142,0.6)",
          "appkit-color-text":             "#eef5ff",
          "appkit-color-text-muted":       "#bcd4ff",
          "appkit-color-text-faint":       "#8eb9ff",
          "appkit-color-text-on-primary":  "#ffffff",
          "appkit-color-success":          "#4ade80",
          "appkit-color-success-surface":  "rgba(6,78,59,0.25)",
          "appkit-color-warning":          "#fbbf24",
          "appkit-color-warning-surface":  "#1c1508",
          "appkit-color-error":            "#f87171",
          "appkit-color-error-surface":    "rgba(127,29,29,0.25)",
          "appkit-color-info":             "#38bdf8",
          "appkit-color-info-surface":     "rgba(12,74,110,0.25)",
          "appkit-color-focus-ring":       "#8eb9ff",
          "appkit-shadow-glow":      "0 0 0 1px rgba(53,112,252,0.20), 0 4px 16px -4px rgba(53,112,252,0.40)",
          "appkit-shadow-glow-pink": "0 0 0 1px rgba(101,196,8,0.20), 0 4px 20px -4px rgba(101,196,8,0.35)",
          "appkit-font-display":   "var(--font-display), \"Poppins\", ui-sans-serif, system-ui, sans-serif",
          "appkit-font-sans":      "var(--font-body), ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          "appkit-font-editorial": "var(--font-editorial), \"Georgia\", serif",
          "appkit-font-mono":      "ui-monospace, \"SFMono-Regular\", \"Cascadia Mono\", \"Consolas\", monospace",
        },
        gradients: {
          brand:            "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          "brand-tri":      "linear-gradient(to right, #3570fc, #65c408, #8eb9ff)",
          accent:           "linear-gradient(to right, var(--appkit-color-secondary), var(--appkit-color-primary))",
          "accent-divider": "linear-gradient(to right, transparent, var(--appkit-color-primary), transparent)",
          "page-header":    "linear-gradient(to bottom right, rgba(53,112,252,0.20), transparent 60%, transparent)",
          "section-warm":   "linear-gradient(to bottom right, rgba(101,196,8,0.10), transparent)",
          "section-cool":   "linear-gradient(to bottom right, rgba(53,112,252,0.20), transparent)",
          "section-mesh":   "radial-gradient(ellipse at top, rgba(53,112,252,0.20), var(--appkit-color-surface), rgba(101,196,8,0.10))",
          "accent-banner":  "linear-gradient(to right, var(--appkit-color-primary), var(--appkit-color-secondary))",
          promotion:        "linear-gradient(to bottom right, var(--appkit-color-error), var(--appkit-color-primary), var(--appkit-color-warning))",
          spotlight:        "linear-gradient(to bottom right, rgba(53,112,252,0.15), var(--appkit-color-bg), rgba(53,112,252,0.15))",
          "whatsapp-card":  "linear-gradient(to bottom right, var(--appkit-color-success), var(--appkit-color-success))",
          glass:            "linear-gradient(to bottom right, color-mix(in srgb, var(--appkit-color-surface) 85%, transparent), color-mix(in srgb, var(--appkit-color-surface) 65%, transparent))",
          "card-indigo":    "linear-gradient(to bottom right, rgba(53,112,252,0.20), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-teal":      "linear-gradient(to bottom right, rgba(101,196,8,0.15), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-amber":     "linear-gradient(to bottom right, var(--appkit-color-warning-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          "card-rose":      "linear-gradient(to bottom right, var(--appkit-color-error-surface), var(--appkit-color-surface), var(--appkit-color-surface))",
          logo:             "linear-gradient(to right, var(--appkit-color-secondary-400) 0%, var(--appkit-color-primary-400) 55%, var(--appkit-color-primary-300) 100%)",
          sidebar:          "linear-gradient(to bottom, var(--appkit-color-primary-950), var(--appkit-color-primary-900))",
        },
      },
    ],
    defaultLightThemeId: "crimson-warrior",
    defaultDarkThemeId: "shadow-abyss",
  },
};
