/**
 * S-STORE Extensions Seed Data
 *
 * Compact sample documents for the 11 new Tier S-STORE collections.
 * Used by SeedPanel ("Store" group). Full demo dataset rewrite ships
 * with S-STORE-11.
 */

import type {
  AnalyticsAlertDocument,
  AnalyticsCardDocument,
  ItemRequestDocument,
  ListingTemplateDocument,
  ModerationQueueDocument,
  PayoutMethodDocument,
  ReportDocument,
  ShippingConfigDocument,
  StoreCategoryDocument,
  StoreGoogleConfigDocument,
  StoreWhatsAppConfigDocument,
} from "../features/store-extensions/schemas/firestore";

const NOW = new Date();

// ───── payoutMethods (6 records) ──────────────────────────────────────────
export const payoutMethodsSeedData: Partial<PayoutMethodDocument>[] = [
  {
    id: "payout-method-pokemon-palace-upi-default",
    sellerId: "user-pokemon-palace-owner",
    storeId: "store-pokemon-palace",
    type: "upi",
    label: "Primary UPI",
    upiVpa: "pokemonpalace@upi",
    isDefault: true,
    isActive: true,
  },
  {
    id: "payout-method-pokemon-palace-bank",
    sellerId: "user-pokemon-palace-owner",
    storeId: "store-pokemon-palace",
    type: "bank",
    label: "HDFC Current Account",
    accountNumber: "50200012345678",
    ifscCode: "HDFC0001234",
    accountHolderName: "Pokemon Palace LLP",
    bankName: "HDFC Bank",
    isDefault: false,
    isActive: true,
  },
  {
    id: "payout-method-diecast-depot-upi",
    sellerId: "user-diecast-depot-owner",
    storeId: "store-diecast-depot",
    type: "upi",
    label: "Default UPI",
    upiVpa: "diecastdepot@okhdfc",
    isDefault: true,
    isActive: true,
  },
  {
    id: "payout-method-tokyo-toys-upi",
    sellerId: "user-tokyo-toys-owner",
    storeId: "store-tokyo-toys-india",
    type: "upi",
    label: "Tokyo Toys UPI",
    upiVpa: "tokyotoys@ybl",
    isDefault: true,
    isActive: true,
  },
  {
    id: "payout-method-cardgame-hub-bank",
    sellerId: "user-cardgame-hub-owner",
    storeId: "store-cardgame-hub",
    type: "bank",
    label: "ICICI Current Account",
    accountNumber: "001234567890",
    ifscCode: "ICIC0000012",
    accountHolderName: "Cardgame Hub Pvt Ltd",
    bankName: "ICICI Bank",
    isDefault: true,
    isActive: true,
  },
  {
    id: "payout-method-beyblade-arena-upi",
    sellerId: "user-beyblade-arena-owner",
    storeId: "store-beyblade-arena",
    type: "upi",
    label: "Arena UPI",
    upiVpa: "beyarena@paytm",
    isDefault: true,
    isActive: true,
  },
];

// ───── shippingConfigs (8 records) ────────────────────────────────────────
export const shippingConfigsSeedData: Partial<ShippingConfigDocument>[] = [
  {
    id: "ship-config-pokemon-palace-free",
    storeId: "store-pokemon-palace",
    label: "Free over Rs 999",
    method: "free",
    freeAbovePaise: 99900,
    estimatedDays: 5,
    isDefault: true,
    isActive: true,
  },
  {
    id: "ship-config-pokemon-palace-express",
    storeId: "store-pokemon-palace",
    label: "Express (2 days)",
    method: "express",
    flatRateInPaise: 19900,
    expressSurchargeInPaise: 9900,
    estimatedDays: 2,
    isDefault: false,
    isActive: true,
  },
  {
    id: "ship-config-diecast-flat",
    storeId: "store-diecast-depot",
    label: "Flat Rs 99",
    method: "flat",
    flatRateInPaise: 9900,
    estimatedDays: 4,
    isDefault: true,
    isActive: true,
  },
  {
    id: "ship-config-diecast-pickup",
    storeId: "store-diecast-depot",
    label: "Pickup (Bangalore)",
    method: "pickup",
    estimatedDays: 0,
    isDefault: false,
    isActive: true,
  },
  {
    id: "ship-config-tokyo-toys-weight",
    storeId: "store-tokyo-toys-india",
    label: "By weight",
    method: "weight",
    pricePerKgInPaise: 12000,
    estimatedDays: 6,
    isDefault: true,
    isActive: true,
  },
  {
    id: "ship-config-cardgame-free-1500",
    storeId: "store-cardgame-hub",
    label: "Free over Rs 1500",
    method: "free",
    freeAbovePaise: 150000,
    estimatedDays: 5,
    isDefault: true,
    isActive: true,
  },
  {
    id: "ship-config-beyblade-flat",
    storeId: "store-beyblade-arena",
    label: "Flat Rs 79",
    method: "flat",
    flatRateInPaise: 7900,
    estimatedDays: 4,
    isDefault: true,
    isActive: true,
  },
  {
    id: "ship-config-gundam-galaxy-express",
    storeId: "store-gundam-galaxy",
    label: "Express Premium",
    method: "express",
    flatRateInPaise: 29900,
    estimatedDays: 3,
    isDefault: true,
    isActive: true,
  },
];

// ───── analyticsCards (9 records) ─────────────────────────────────────────
export const analyticsCardsSeedData: Partial<AnalyticsCardDocument>[] = [
  { id: "ac-seller-revenue-30d", scope: "seller", ownerId: "user-pokemon-palace-owner", title: "Revenue · 30d", type: "metric", metric: "revenue:30d", filters: {}, position: 0, isBuiltIn: true, isVisible: true },
  { id: "ac-seller-orders-30d", scope: "seller", ownerId: "user-pokemon-palace-owner", title: "Orders · 30d", type: "metric", metric: "orders:30d", filters: {}, position: 1, isBuiltIn: true, isVisible: true },
  { id: "ac-seller-aov", scope: "seller", ownerId: "user-pokemon-palace-owner", title: "Avg Order Value", type: "metric", metric: "aov:30d", filters: {}, position: 2, isBuiltIn: true, isVisible: true },
  { id: "ac-seller-traffic", scope: "seller", ownerId: "user-pokemon-palace-owner", title: "Storefront Traffic", type: "line", metric: "store-views:30d", filters: {}, position: 3, isBuiltIn: true, isVisible: true },
  { id: "ac-seller-top-products", scope: "seller", ownerId: "user-pokemon-palace-owner", title: "Top Products", type: "table", metric: "top-products:30d", filters: {}, position: 4, isBuiltIn: true, isVisible: true },
  { id: "ac-admin-platform-gmv", scope: "admin", ownerId: "user-admin-letitrip", title: "Platform GMV", type: "metric", metric: "platform-gmv:30d", filters: {}, position: 0, isBuiltIn: true, isVisible: true },
  { id: "ac-admin-active-stores", scope: "admin", ownerId: "user-admin-letitrip", title: "Active Stores", type: "metric", metric: "active-stores", filters: {}, position: 1, isBuiltIn: true, isVisible: true },
  { id: "ac-admin-pending-mod", scope: "admin", ownerId: "user-admin-letitrip", title: "Pending Moderation", type: "metric", metric: "moderation-pending", filters: {}, position: 2, isBuiltIn: true, isVisible: true },
  { id: "ac-admin-open-reports", scope: "admin", ownerId: "user-admin-letitrip", title: "Open Reports", type: "metric", metric: "reports-open", filters: {}, position: 3, isBuiltIn: true, isVisible: true },
];

// ───── analyticsAlerts (4 records) ────────────────────────────────────────
export const analyticsAlertsSeedData: Partial<AnalyticsAlertDocument>[] = [
  { id: "alert-low-stock-pokemon", scope: "seller", ownerId: "user-pokemon-palace-owner", label: "Low stock", metric: "min-stock", operator: "<", threshold: 5, windowHours: 24, isActive: true, notifyChannels: ["in-app", "email"] },
  { id: "alert-no-sales-pokemon", scope: "seller", ownerId: "user-pokemon-palace-owner", label: "Zero sales 48h", metric: "orders-window", operator: "==", threshold: 0, windowHours: 48, isActive: true, notifyChannels: ["in-app"] },
  { id: "alert-platform-error-rate", scope: "admin", ownerId: "user-admin-letitrip", label: "API error rate > 5%", metric: "api-error-rate", operator: ">", threshold: 0.05, windowHours: 1, isActive: true, notifyChannels: ["in-app", "email", "whatsapp"] },
  { id: "alert-fraud-surge", scope: "admin", ownerId: "user-admin-letitrip", label: "Fraud reports surge", metric: "reports-1h", operator: ">", threshold: 10, windowHours: 1, isActive: true, notifyChannels: ["in-app", "email"] },
];

// ───── storeCategories (6 records) ────────────────────────────────────────
export const storeCategoriesSeedData: Partial<StoreCategoryDocument>[] = [
  { id: "scat-pokemon-1st-edition", storeId: "store-pokemon-palace", label: "1st Edition Holos", slug: "1st-edition-holos", displayOrder: 0, productIds: [], isActive: true, description: "Vintage 1st-edition Pokémon holos.", coverImageUrl: "https://picsum.photos/seed/scat-pokemon-1e/640/360" },
  { id: "scat-pokemon-japanese", storeId: "store-pokemon-palace", label: "Japanese Imports", slug: "japanese-imports", displayOrder: 1, productIds: [], isActive: true, coverImageUrl: "https://picsum.photos/seed/scat-pokemon-jp/640/360" },
  { id: "scat-diecast-redline", storeId: "store-diecast-depot", label: "Hot Wheels Redline", slug: "hot-wheels-redline", displayOrder: 0, productIds: [], isActive: true, coverImageUrl: "https://picsum.photos/seed/scat-redline/640/360" },
  { id: "scat-diecast-tomica", storeId: "store-diecast-depot", label: "Tomica Premium", slug: "tomica-premium", displayOrder: 1, productIds: [], isActive: true, coverImageUrl: "https://picsum.photos/seed/scat-tomica/640/360" },
  { id: "scat-beyblade-burst", storeId: "store-beyblade-arena", label: "Burst Series", slug: "burst-series", displayOrder: 0, productIds: [], isActive: true, coverImageUrl: "https://picsum.photos/seed/scat-bey/640/360" },
  { id: "scat-gundam-rg", storeId: "store-gundam-galaxy", label: "Real Grade Kits", slug: "real-grade", displayOrder: 0, productIds: [], isActive: true, coverImageUrl: "https://picsum.photos/seed/scat-gundam/640/360" },
];

// ───── listingTemplates (5 records) ───────────────────────────────────────
export const listingTemplatesSeedData: Partial<ListingTemplateDocument>[] = [
  {
    id: "tmpl-standard-pokemon-card",
    storeId: "store-pokemon-palace",
    ownerId: "user-pokemon-palace-owner",
    name: "Pokémon Card · Standard",
    description: "Default fields for a graded Pokémon card listing.",
    listingType: "standard",
    defaults: { condition: "mint", currency: "INR", tags: ["pokemon", "tcg"] },
    isShared: true,
    isActive: true,
    usageCount: 14,
  },
  {
    id: "tmpl-auction-vintage-pokemon",
    storeId: "store-pokemon-palace",
    ownerId: "user-pokemon-palace-owner",
    name: "Vintage Pokémon Auction",
    listingType: "auction",
    defaults: { reserveMultiplier: 1.2, auctionDays: 7, currency: "INR" },
    isShared: false,
    isActive: true,
    usageCount: 5,
  },
  {
    id: "tmpl-preorder-bandai",
    storeId: "store-tokyo-toys-india",
    ownerId: "user-tokyo-toys-owner",
    name: "Bandai Pre-Order",
    listingType: "pre-order",
    defaults: { releaseLeadDays: 90, depositPercent: 30 },
    isShared: false,
    isActive: true,
    usageCount: 9,
  },
  {
    id: "tmpl-bundle-starter",
    storeId: "store-diecast-depot",
    ownerId: "user-diecast-depot-owner",
    name: "Starter Bundle",
    listingType: "bundle",
    defaults: { minItems: 3, maxItems: 10, autoDiscountPercent: 12 },
    isShared: true,
    isActive: true,
    usageCount: 2,
  },
  {
    id: "tmpl-digital-code-steam",
    storeId: "store-cardgame-hub",
    ownerId: "user-cardgame-hub-owner",
    name: "Steam Key Listing",
    listingType: "digital-code",
    defaults: { vendor: "steam", region: "in" },
    isShared: false,
    isActive: true,
    usageCount: 1,
  },
];

// ───── moderationQueue (5 records) ────────────────────────────────────────
export const moderationQueueSeedData: Partial<ModerationQueueDocument>[] = [
  { id: "mod-video-pokemon-charizard", mediaType: "video", mediaUrl: "/media/product-video-charizard-psa9-20260518.mp4", entityType: "product", entityId: "product-pokemon-charizard-psa9", ownerId: "user-pokemon-palace-owner", storeId: "store-pokemon-palace", status: "pending", submittedAt: new Date(NOW.getTime() - 3600_000) },
  { id: "mod-video-beyblade-burst", mediaType: "video", mediaUrl: "/media/product-video-beyblade-burst-20260518.mp4", entityType: "product", entityId: "product-beyblade-burst-evolution", ownerId: "user-beyblade-arena-owner", storeId: "store-beyblade-arena", status: "pending", submittedAt: new Date(NOW.getTime() - 7200_000) },
  { id: "mod-review-hot-wheels", mediaType: "rich-text", entityType: "review", entityId: "review-hot-wheels-redline-1", ownerId: "user-ravi-kumar", status: "approved", reviewerId: "user-admin-letitrip", reviewedAt: new Date(NOW.getTime() - 86400_000), submittedAt: new Date(NOW.getTime() - 90000_000) },
  { id: "mod-image-diecast-banner", mediaType: "image", mediaUrl: "/media/store-banner-diecast-depot-20260518.jpg", entityType: "storefront", entityId: "store-diecast-depot", ownerId: "user-diecast-depot-owner", storeId: "store-diecast-depot", status: "auto-approved", submittedAt: new Date(NOW.getTime() - 172800_000) },
  { id: "mod-blog-grading-guide", mediaType: "rich-text", entityType: "blog", entityId: "blog-how-to-grade-pokemon-cards", ownerId: "user-admin-letitrip", status: "approved", reviewerId: "user-admin-letitrip", reviewedAt: new Date(NOW.getTime() - 432000_000), submittedAt: new Date(NOW.getTime() - 438000_000) },
  { id: "mod-video-tomica-unbox", mediaType: "video", mediaUrl: "/media/product-video-tomica-tlv-bmw-20260518.mp4", entityType: "product", entityId: "product-tomica-tlv-bmw-2002", ownerId: "user-diecast-depot-owner", storeId: "store-diecast-depot", status: "pending", submittedAt: new Date(NOW.getTime() - 1800_000) },
  { id: "mod-video-rg-build-time", mediaType: "video", mediaUrl: "/media/product-video-rg-nu-gundam-20260518.mp4", entityType: "product", entityId: "product-rg-nu-gundam-real-grade", ownerId: "user-gundam-galaxy-owner", storeId: "store-gundam-galaxy", status: "pending", submittedAt: new Date(NOW.getTime() - 5400_000) },
  { id: "mod-event-cover", mediaType: "image", mediaUrl: "/media/event-cover-summer-tcg-meetup-20260518.jpg", entityType: "event", entityId: "event-summer-tcg-meetup", ownerId: "user-admin-letitrip", status: "approved", reviewerId: "user-admin-letitrip", reviewedAt: new Date(NOW.getTime() - 86400_000), submittedAt: new Date(NOW.getTime() - 90000_000) },
  { id: "mod-storefront-bey-banner", mediaType: "image", mediaUrl: "/media/store-banner-beyblade-arena-20260518.jpg", entityType: "storefront", entityId: "store-beyblade-arena", ownerId: "user-beyblade-arena-owner", storeId: "store-beyblade-arena", status: "rejected", reason: "Banner has off-brand watermark.", reviewerId: "user-admin-letitrip", reviewedAt: new Date(NOW.getTime() - 172800_000), submittedAt: new Date(NOW.getTime() - 180000_000) },
  { id: "mod-review-bootleg-flag", mediaType: "rich-text", entityType: "review", entityId: "review-bootleg-flag", ownerId: "user-anonymous-2", status: "pending", submittedAt: new Date(NOW.getTime() - 600_000) },
  { id: "mod-blog-collectibles-trends", mediaType: "rich-text", entityType: "blog", entityId: "blog-2026-collectibles-trends", ownerId: "user-admin-letitrip", status: "auto-approved", submittedAt: new Date(NOW.getTime() - 14400_000) },
];

// ───── reports (4 records) ────────────────────────────────────────────────
export const reportsSeedData: Partial<ReportDocument>[] = [
  { id: "report-counterfeit-charizard", entityType: "product", entityId: "product-suspect-charizard", reporterId: "user-ravi-kumar", reason: "counterfeit", detail: "Card edges look reprinted; texture inconsistent.", evidenceUrls: [], status: "pending" },
  { id: "report-scam-store-fly-by-night", entityType: "store", entityId: "store-suspect-fly-by-night", reporterId: "user-priya-sharma", reason: "scam", detail: "Reports of orders not shipped after 4 weeks.", evidenceUrls: [], status: "under-review", assignedTo: "user-admin-letitrip" },
  { id: "report-spam-review-bey", entityType: "review", entityId: "review-bey-spammy", reporterId: "user-arjun-rao", reason: "spam", detail: "Promotional link in review.", evidenceUrls: [], status: "actioned", resolution: "Review hidden.", resolvedAt: new Date(NOW.getTime() - 86400_000) },
  { id: "report-harassment-comment", entityType: "comment", entityId: "comment-bad-actor-1", reporterId: "user-mohsin-c", reason: "harassment", detail: "Targeted abuse in blog comments.", evidenceUrls: [], status: "dismissed", resolvedAt: new Date(NOW.getTime() - 172800_000) },
  { id: "report-prohibited-replica-listing", entityType: "product", entityId: "product-suspect-replica-rolex", reporterId: "user-mohsin-c", reason: "prohibited", detail: "Replica branded merchandise.", evidenceUrls: [], status: "pending" },
  { id: "report-ip-violation-fan-art-print", entityType: "product", entityId: "product-bootleg-pokemon-print", reporterId: "user-priya-sharma", reason: "ip-violation", detail: "Unauthorised Pokémon art prints.", evidenceUrls: [], status: "under-review", assignedTo: "user-admin-letitrip" },
  { id: "report-spam-listing-mass-post", entityType: "store", entityId: "store-spammer-mass", reporterId: "user-arjun-rao", reason: "spam", detail: "Same product listed 50+ times.", evidenceUrls: [], status: "pending" },
  { id: "report-inappropriate-blog", entityType: "blog", entityId: "blog-controversial-post", reporterId: "user-anonymous-1", reason: "inappropriate", detail: "Off-topic political content.", evidenceUrls: [], status: "dismissed", resolvedAt: new Date(NOW.getTime() - 259200_000) },
];

// ───── itemRequests (3 records) ───────────────────────────────────────────
export const itemRequestsSeedData: Partial<ItemRequestDocument>[] = [
  {
    id: "irq-charizard-shadowless",
    opUserId: "user-ravi-kumar",
    opDisplayName: "Ravi Kumar",
    title: "Looking for Shadowless Charizard PSA 8+",
    description: "Hunting a Shadowless Base Set Charizard, grade 8 or above. Budget Rs 2,50,000.",
    category: "trading-cards",
    brand: "pokemon",
    maxBudgetInPaise: 25000000,
    imageUrls: ["https://picsum.photos/seed/irq-1/640/480"],
    status: "open",
    replyCount: 2,
    replies: [],
    approvedAt: new Date(NOW.getTime() - 86400_000),
    approvedBy: "user-admin-letitrip",
  },
  {
    id: "irq-tomica-redline-bmw",
    opUserId: "user-arjun-rao",
    opDisplayName: "Arjun Rao",
    title: "Tomica Limited Vintage BMW 2002",
    description: "Mint condition only. Box must be intact.",
    category: "diecast-vehicles",
    brand: "tomica",
    maxBudgetInPaise: 850000,
    imageUrls: ["https://picsum.photos/seed/irq-2/640/480"],
    status: "open",
    replyCount: 0,
    replies: [],
    approvedAt: new Date(NOW.getTime() - 43200_000),
    approvedBy: "user-admin-letitrip",
  },
  {
    id: "irq-pending-funko-grail",
    opUserId: "user-priya-sharma",
    opDisplayName: "Priya Sharma",
    title: "Funko Pop SDCC Exclusive Glow Batman",
    description: "Searching for the 2013 SDCC Glow-in-Dark Batman exclusive.",
    category: "action-figures",
    brand: "funko",
    imageUrls: ["https://picsum.photos/seed/irq-3/640/480"],
    status: "pending-approval",
    replyCount: 0,
    replies: [],
  },
  {
    id: "irq-bey-spriggan-bb-105",
    opUserId: "user-arjun-rao",
    opDisplayName: "Arjun Rao",
    title: "Beyblade Spriggan BB-105 boxed",
    description: "Need original-box Spriggan from the Metal Fight series. Mint launcher.",
    category: "spinning-tops",
    brand: "takara-tomy",
    maxBudgetInPaise: 450000,
    imageUrls: ["https://picsum.photos/seed/irq-4/640/480"],
    status: "open",
    replyCount: 1,
    replies: [],
    approvedAt: new Date(NOW.getTime() - 28800_000),
    approvedBy: "user-admin-letitrip",
  },
  {
    id: "irq-rg-nu-gundam",
    opUserId: "user-mohsin-c",
    opDisplayName: "Mohsin C",
    title: "RG 1/144 Nu Gundam mint sealed",
    description: "Sealed runner. Will pay shipping insurance.",
    category: "model-kits",
    brand: "bandai",
    maxBudgetInPaise: 320000,
    imageUrls: ["https://picsum.photos/seed/irq-5/640/480"],
    status: "fulfilled",
    replyCount: 4,
    replies: [],
    approvedAt: new Date(NOW.getTime() - 7 * 86400_000),
    approvedBy: "user-admin-letitrip",
    closedAt: new Date(NOW.getTime() - 2 * 86400_000),
  },
  {
    id: "irq-tcg-base-set-booster",
    opUserId: "user-ravi-kumar",
    opDisplayName: "Ravi Kumar",
    title: "Pokémon Base Set booster pack — unopened",
    description: "Any printing. Western or Japanese OK. Sealed only.",
    category: "trading-cards",
    brand: "pokemon",
    maxBudgetInPaise: 1500000,
    imageUrls: ["https://picsum.photos/seed/irq-6/640/480"],
    status: "open",
    replyCount: 0,
    replies: [],
    approvedAt: new Date(NOW.getTime() - 14400_000),
    approvedBy: "user-admin-letitrip",
  },
  {
    id: "irq-rejected-replica-watch",
    opUserId: "user-anonymous-flagged",
    opDisplayName: "Anonymous",
    title: "Replica luxury watches",
    description: "Looking for replica watches at discount.",
    category: "other",
    imageUrls: ["https://picsum.photos/seed/irq-7/640/480"],
    status: "rejected",
    replyCount: 0,
    replies: [],
  },
];

// ───── storeWhatsAppConfig (2 records) ────────────────────────────────────
export const storeWhatsAppConfigSeedData: Partial<StoreWhatsAppConfigDocument>[] = [
  {
    id: "whatsapp-pokemon-palace",
    storeId: "store-pokemon-palace",
    isConnected: true,
    isPaid: true,
    phoneNumber: "+919876543210",
    businessProfileName: "Pokémon Palace",
    catalogUrl: "https://wa.me/c/919876543210",
    autoReply: "Hi! Thanks for messaging Pokémon Palace. We respond within 2 hours.",
    welcomeMessage: "Welcome to Pokémon Palace! Browse our catalog above.",
    onboardingStatus: "approved",
  },
  {
    id: "whatsapp-tokyo-toys",
    storeId: "store-tokyo-toys-india",
    isConnected: false,
    isPaid: false,
    onboardingStatus: "pending",
  },
];

// ───── storeGoogleConfig (2 records) ──────────────────────────────────────
export const storeGoogleConfigSeedData: Partial<StoreGoogleConfigDocument>[] = [
  {
    id: "google-pokemon-palace",
    storeId: "store-pokemon-palace",
    isConnected: true,
    placeId: "ChIJpokemonpalace12345",
    businessName: "Pokémon Palace",
    averageRating: 4.7,
    totalReviews: 124,
    lastSyncedAt: new Date(NOW.getTime() - 3600_000),
  },
  {
    id: "google-diecast-depot",
    storeId: "store-diecast-depot",
    isConnected: false,
  },
];
