/**
 * Sublisting Categories Seed Data — Curated sub-collections within root categories.
 * 20 sublisting categories across all collectibles verticals.
 * id === slug convention. sublisting- prefix.
 */

import type { SublistingCategoryDocument } from "../features/sublisting/schemas/firestore";

const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const sublistingCategoriesSeedData: Partial<SublistingCategoryDocument>[] = [
  // ── Trading Cards / Pokémon ──────────────────────────────────────────────
  {
    id: "sublisting-pokemon-base-set",
    slug: "sublisting-pokemon-base-set",
    title: "Base Set (102/102)",
    parentCategorySlug: "category-pokemon-cards",
    rootCategorySlug: "category-trading-cards",
    description: "Complete set of all 102 Base Set cards including Shadowless, 1st Edition, and Unlimited variants. The original 1999 Wizards of the Coast set that started the Pokémon TCG.",
    coverImage: "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    seoTitle: "Pokémon Base Set Cards — Buy Base Set Singles, Holos & Shadowless",
    seoDescription: "Shop original 1999 Pokémon Base Set cards. Charizard, Blastoise, Venusaur, and all 102 cards. Shadowless, 1st Edition, and Unlimited variants available.",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: "sublisting-pokemon-psa-graded",
    slug: "sublisting-pokemon-psa-graded",
    title: "PSA Graded Cards",
    parentCategorySlug: "category-pokemon-cards",
    rootCategorySlug: "category-trading-cards",
    description: "PSA-authenticated and graded Pokémon cards. Grades PSA 7 through PSA 10 Gem Mint. Investment-grade collectibles with guaranteed authenticity.",
    coverImage: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&h=600&fit=crop",
    sortOrder: 2,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    seoTitle: "PSA Graded Pokémon Cards India — Buy PSA 9, PSA 10 Slabs",
    seoDescription: "Verified PSA-graded Pokémon cards. Base Set holos, ex cards, V-max, and modern rare cards in PSA slabs. Secure packaging, authentic certificates.",
    createdAt: daysAgo(55),
    updatedAt: daysAgo(2),
  },
  {
    id: "sublisting-pokemon-sealed-booster-boxes",
    slug: "sublisting-pokemon-sealed-booster-boxes",
    title: "Sealed Booster Boxes",
    parentCategorySlug: "category-sealed-products",
    rootCategorySlug: "category-trading-cards",
    description: "Factory-sealed Pokémon TCG booster boxes. Current sets, vintage boxes, and Japanese exclusives. All boxes inspected for intact shrinkwrap before listing.",
    coverImage: "https://images.unsplash.com/photo-1614108831137-558fffac9ead?w=800&h=600&fit=crop",
    sortOrder: 3,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(3),
  },

  // ── Trading Cards / Yu-Gi-Oh! ────────────────────────────────────────────
  {
    id: "sublisting-yugioh-lob-1st-edition",
    slug: "sublisting-yugioh-lob-1st-edition",
    title: "Legend of Blue-Eyes (LOB) 1st Edition",
    parentCategorySlug: "category-yugioh-cards",
    rootCategorySlug: "category-trading-cards",
    description: "The original Yu-Gi-Oh! LOB set 1st Edition singles. Blue-Eyes White Dragon, Dark Magician, Exodia pieces, and other iconic WOTC-era cards.",
    coverImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(5),
  },
  {
    id: "sublisting-yugioh-tournament-singles",
    slug: "sublisting-yugioh-tournament-singles",
    title: "Tournament-Ready Singles",
    parentCategorySlug: "category-yugioh-cards",
    rootCategorySlug: "category-trading-cards",
    description: "TCG-legal singles for competitive play. Current format staples, hand traps, board breakers, and meta-relevant cards verified against latest banlist.",
    coverImage: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&h=600&fit=crop",
    sortOrder: 2,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(4),
  },

  // ── Diecast Vehicles ─────────────────────────────────────────────────────
  {
    id: "sublisting-hotwheels-vintage-redlines",
    slug: "sublisting-hotwheels-vintage-redlines",
    title: "Vintage Redlines (1968–1977)",
    parentCategorySlug: "category-hot-wheels-cars",
    rootCategorySlug: "category-diecast-vehicles",
    description: "Original Hot Wheels Redline era cars from the first decade of production. US cards, Hong Kong manufacturing, and rare color variants. Collector's paradise.",
    coverImage: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    seoTitle: "Hot Wheels Vintage Redlines India — 1968-1977 Original Cars",
    seoDescription: "Buy original Hot Wheels Redline cars from 1968-1977. US card, Hong Kong cars, rare color variants. Authenticated vintage diecast collectibles.",
    createdAt: daysAgo(38),
    updatedAt: daysAgo(1),
  },
  {
    id: "sublisting-hotwheels-super-treasure-hunts",
    slug: "sublisting-hotwheels-super-treasure-hunts",
    title: "Super Treasure Hunts (STH)",
    parentCategorySlug: "category-hot-wheels-cars",
    rootCategorySlug: "category-diecast-vehicles",
    description: "Hot Wheels Super Treasure Hunt cars — the rarest regular production releases. Real Riders rubber tyres, spectraflame paint, Treasure Hunt logo. One per case.",
    coverImage: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=600&fit=crop",
    sortOrder: 2,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(2),
  },
  {
    id: "sublisting-hotwheels-car-culture",
    slug: "sublisting-hotwheels-car-culture",
    title: "Car Culture Series",
    parentCategorySlug: "category-hot-wheels-cars",
    rootCategorySlug: "category-diecast-vehicles",
    description: "Hot Wheels Car Culture premium 1:64 diecast cars. Real Riders, premium paint, highly detailed castings. Series: Japan Historics, Germany, Boulevard, Team Transport, and more.",
    coverImage: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=600&fit=crop",
    sortOrder: 3,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(32),
    updatedAt: daysAgo(3),
  },
  {
    id: "sublisting-tomica-limited-vintage",
    slug: "sublisting-tomica-limited-vintage",
    title: "Tomica Limited Vintage",
    parentCategorySlug: "category-tomica-cars",
    rootCategorySlug: "category-diecast-vehicles",
    description: "Tomica Limited Vintage (TLV) 1:64 scale Japanese cars. Highly accurate models of classic Japanese vehicles from the 1950s–1980s. Display stands included.",
    coverImage: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },

  // ── Action Figures / Anime ───────────────────────────────────────────────
  {
    id: "sublisting-nendoroid-001-100",
    slug: "sublisting-nendoroid-001-100",
    title: "Nendoroid #001–#100",
    parentCategorySlug: "category-anime-figures",
    rootCategorySlug: "category-action-figures",
    description: "Early Nendoroid series numbers 001 through 100 — the foundational GSC figures. Many are discontinued and highly sought after. Includes Saber, Haruhi, Yotsuba, and Miku.",
    coverImage: "https://images.unsplash.com/photo-1536896407451-6e3dd976edd6?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    seoTitle: "Nendoroid #001-#100 — Buy Rare Early Series Good Smile Figures",
    seoDescription: "Shop discontinued early Nendoroid figures numbered 001-100. Original Good Smile Company releases. Rare collector finds with original boxes.",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(2),
  },
  {
    id: "sublisting-shf-dragonball",
    slug: "sublisting-shf-dragonball",
    title: "S.H.Figuarts Dragon Ball",
    parentCategorySlug: "category-anime-figures",
    rootCategorySlug: "category-action-figures",
    description: "Bandai S.H.Figuarts Dragon Ball Z and Super figures. Goku, Vegeta, Gohan, Piccolo, Frieza, and more. Ultra articulation, premium accessories, Kame House stand compatible.",
    coverImage: "https://images.unsplash.com/photo-1536896407451-6e3dd976edd6?w=800&h=600&fit=crop",
    sortOrder: 2,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: "sublisting-funko-pop-anime",
    slug: "sublisting-funko-pop-anime",
    title: "Funko Pop! Anime",
    parentCategorySlug: "category-vinyl-figures",
    rootCategorySlug: "category-action-figures",
    description: "Official Funko Pop! vinyl figures from anime franchises: Naruto, Dragon Ball Z, One Piece, Attack on Titan, My Hero Academia, Demon Slayer, and Jujutsu Kaisen.",
    coverImage: "https://images.unsplash.com/photo-1536896407451-6e3dd976edd6?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(3),
  },

  // ── Spinning Tops / Beyblade ─────────────────────────────────────────────
  {
    id: "sublisting-beyblade-x-series",
    slug: "sublisting-beyblade-x-series",
    title: "Beyblade X Series",
    parentCategorySlug: "category-beyblade-tops",
    rootCategorySlug: "category-spinning-tops",
    description: "All Beyblade X (2023+) products. The latest generation with xtreme dash ratchet system. BX-01 through current releases. Takara Tomy Japan import only.",
    coverImage: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    seoTitle: "Beyblade X Series India — BX-01 and Beyond, Takara Tomy Import",
    seoDescription: "Buy Beyblade X generation tops from Japan. BX-01 Dran Sword, BX-02 Hells Scythe, XStadiums, launchers. Official Takara Tomy import.",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: "sublisting-beyblade-burst-gt",
    slug: "sublisting-beyblade-burst-gt",
    title: "Beyblade Burst GT / Sparking",
    parentCategorySlug: "category-beyblade-tops",
    rootCategorySlug: "category-spinning-tops",
    description: "Beyblade Burst GT (Sparking) generation. The final gen of the Burst era with DBZ crossover tops. Achilles, Longinus, Ragnaruk, and God chip variants.",
    coverImage: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&h=600&fit=crop",
    sortOrder: 2,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(4),
  },

  // ── Model Kits / Gundam ──────────────────────────────────────────────────
  {
    id: "sublisting-gundam-master-grade",
    slug: "sublisting-gundam-master-grade",
    title: "Gundam Master Grade (MG) 1/100",
    parentCategorySlug: "category-gundam-kits",
    rootCategorySlug: "category-model-kits",
    description: "Bandai Gundam Master Grade kits. 1/100 scale with full inner frame and panel-line detail. For intermediate to advanced builders. Wide selection from UC to SEED to 00 to IBO.",
    coverImage: "https://images.unsplash.com/photo-1536896407451-6e3dd976edd6?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    seoTitle: "Gundam MG 1/100 Model Kits India — Buy Master Grade Gunpla",
    seoDescription: "Shop Gundam Master Grade 1/100 scale kits. RX-78, Unicorn, Wing Zero, Exia, Strike. Official Bandai Spirits Japan release. Beginner to advanced.",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },
  {
    id: "sublisting-gundam-real-grade",
    slug: "sublisting-gundam-real-grade",
    title: "Gundam Real Grade (RG) 1/144",
    parentCategorySlug: "category-gundam-kits",
    rootCategorySlug: "category-model-kits",
    description: "Bandai Gundam Real Grade kits. 1/144 scale with Advanced MS Joint system — incredible detail in a smaller form. Great for collectors with limited display space.",
    coverImage: "https://images.unsplash.com/photo-1536896407451-6e3dd976edd6?w=800&h=600&fit=crop",
    sortOrder: 2,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },
  {
    id: "sublisting-gundam-high-grade",
    slug: "sublisting-gundam-high-grade",
    title: "Gundam High Grade (HG) 1/144",
    parentCategorySlug: "category-gundam-kits",
    rootCategorySlug: "category-model-kits",
    description: "Bandai Gundam High Grade kits. 1/144 scale entry-level kits — perfect for beginners or collectors who want to build quickly. Wide selection, lowest price point in the Gunpla lineup.",
    coverImage: "https://images.unsplash.com/photo-1536896407451-6e3dd976edd6?w=800&h=600&fit=crop",
    sortOrder: 3,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
  },

  // ── Vintage & Rare ───────────────────────────────────────────────────────
  {
    id: "sublisting-vintage-pokemon-wotc-era",
    slug: "sublisting-vintage-pokemon-wotc-era",
    title: "WOTC Era (1999–2003)",
    parentCategorySlug: "category-vintage-pokemon",
    rootCategorySlug: "category-vintage-rare",
    description: "Pokémon TCG from the Wizards of the Coast era: Base Set, Jungle, Fossil, Base Set 2, Team Rocket, Gym Heroes, Gym Challenge, Neo Genesis, Neo Discovery, Neo Revelation, Neo Destiny, Legendary Collection.",
    coverImage: "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=600&fit=crop",
    sortOrder: 1,
    isActive: true,
    isFeatured: true,
    productCount: 0,
    seoTitle: "WOTC Era Pokémon Cards India — Buy Vintage 1999-2003 TCG",
    seoDescription: "Shop vintage Wizards of the Coast era Pokémon cards from 1999-2003. Base Set, Jungle, Fossil, Neo series. Graded and raw copies available.",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: "sublisting-vintage-hotwheels-pink-card",
    slug: "sublisting-vintage-hotwheels-pink-card",
    title: "Pink Card Era (1979–1984)",
    parentCategorySlug: "category-vintage-rare",
    rootCategorySlug: "category-vintage-rare",
    description: "Hot Wheels from the Pink Card era (1979–1984). The post-Redline transition period with new body styles and Hot Bird, Real Riders debut. International variants and factory errors valued by collectors.",
    coverImage: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=600&fit=crop",
    sortOrder: 2,
    isActive: true,
    isFeatured: false,
    productCount: 0,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
];
