/**
 * Transformers â€” Products Seed Data
 * 10 general Â· 1 auction Â· 1 pre-order = 12 total
 * Seller: Speed King Diecast (store-speed-king-diecast)
 */

import { getDefaultCurrency } from "./seed-market-config";
import type { ProductDocument } from "../features/products/schemas";

const _CURRENCY = getDefaultCurrency();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);
const daysAhead = (n: number) => new Date(NOW.getTime() + n * 86_400_000);

const SK = {
  sellerId: "user-speed-king-diecast",
  storeId: "speed-king-diecast",
  sellerName: "Speed King Diecast",
  sellerEmail: "speedking@letitrip.in",
} as const;

const TF_IMGS = [
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Optimus_Prime_toy.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Transformers_toy.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Action_figure.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Robot_action_figure.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Transformer_toy.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hasbro_Transformers_toy.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Megatron_toy.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Transformers_action_figure.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Robot_toy.jpg?width=640",
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Converting_robot_toy.jpg?width=640",
];
const img = (seed: string) => {
  let h = 0; for (const c of seed) h = (h * 31 + c.charCodeAt(0)) & 0x7fff;
  return TF_IMGS[h % TF_IMGS.length];
};

export const transformersProductsSeedData: Partial<ProductDocument>[] = [

  // â”€â”€ AUTOBOTS (5) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "product-tf-optimus-prime-studio-voyager-sk-1",
    title: "Transformers Studio Series Optimus Prime â€” Voyager Class (Bumblebee Movie)",
    description: "<p>Studio Series Optimus Prime from the Bumblebee movie â€” Voyager Class figure with intricate Cybertronian mode conversion. Highly articulated with 30+ points of articulation. Includes energy axe accessory. Converts between robot and Peterbilt truck mode in 22 steps.</p>",
    slug: "product-tf-studio-series-optimus-prime-voyager-bumblebee-movie",
    category: "category-tf-autobots",
    subcategory: "Studio Series",
    brand: "Transformers",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 15,
    availableQuantity: 12,
    mainImage: img("tf-optimus-prime-ss"),
    images: [img("tf-optimus-prime-ss"), img("tf-optimus-prime-ss-truck")],
    video: {
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      thumbnailUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Optimus_Prime_toy.jpg?width=640",
      duration: 15,
    },
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "optimus prime", "studio series", "voyager", "bumblebee movie"],
    specifications: [
      { name: "Class", value: "Voyager Class" },
      { name: "Series", value: "Studio Series" },
      { name: "Film", value: "Bumblebee (2018)" },
      { name: "Height (Robot)", value: "~18 cm" },
      { name: "Conversion Steps", value: "22" },
      { name: "Articulation", value: "30+ points" },
    ],
    features: ["Converts Peterbilt truck to robot", "30+ articulation points", "Includes energy axe", "Movie-accurate deco"],
    shippingInfo: "Original box. Padded nationwide delivery.",
    returnPolicy: "10-day returns for factory-sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 149,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.8,
    reviewCount: 34,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-tf-bumblebee-deluxe-wfc-sk-2",
    title: "Transformers War for Cybertron Bumblebee â€” Deluxe Class",
    description: "<p>War for Cybertron Siege Bumblebee â€” a faithful G1-inspired Bumblebee redesign with Earthrise weapon compatibility. Converts in 15 steps between VW Beetle-inspired Cybertronian alt mode and articulated robot mode.</p>",
    slug: "product-tf-wfc-siege-bumblebee-deluxe",
    category: "category-tf-autobots",
    subcategory: "War for Cybertron",
    brand: "Transformers",
    price: 2799,
    currency: _CURRENCY,
    stockQuantity: 18,
    availableQuantity: 15,
    mainImage: img("tf-bumblebee-wfc"),
    images: [img("tf-bumblebee-wfc")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["transformers", "bumblebee", "war for cybertron", "siege", "deluxe"],
    specifications: [
      { name: "Class", value: "Deluxe Class" },
      { name: "Series", value: "War for Cybertron: Siege" },
      { name: "Height (Robot)", value: "~14 cm" },
      { name: "Conversion Steps", value: "15" },
    ],
    features: ["G1-inspired design", "WFC weapon attachment points", "15-step conversion"],
    shippingInfo: "Original packaging nationwide.",
    returnPolicy: "10-day returns for sealed items.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 21,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(5),
  },

  {
    id: "product-tf-jazz-deluxe-legacy-sk-3",
    title: "Transformers Legacy Jazz â€” Deluxe Class (G1 Inspired)",
    description: "<p>Legacy Jazz â€” a modern reimagining of the G1 classic with enhanced articulation and screen-accurate Porsche 935 alt mode. Vibrant white with racing livery tampo. A fan-favourite upgrade.</p>",
    slug: "product-tf-legacy-jazz-deluxe-g1-inspired",
    category: "category-tf-autobots",
    subcategory: "Legacy",
    brand: "Transformers",
    price: 2999,
    currency: _CURRENCY,
    stockQuantity: 12,
    availableQuantity: 10,
    mainImage: img("tf-jazz-legacy"),
    images: [img("tf-jazz-legacy")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "jazz", "legacy", "deluxe", "g1", "porsche"],
    specifications: [
      { name: "Class", value: "Deluxe Class" },
      { name: "Series", value: "Legacy" },
      { name: "Alt Mode", value: "Porsche 935-inspired" },
    ],
    features: ["Porsche 935-inspired alt mode", "Racing livery tampo", "Enhanced G1 articulation"],
    shippingInfo: "Original box nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 18,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(4),
  },

  {
    id: "product-tf-ironhide-voyager-legacy-sk-4",
    title: "Transformers Legacy Ironhide â€” Voyager Class",
    description: "<p>Ironhide Voyager from Legacy â€” the big red battle veteran in his most articulated form yet. Converts to GMC TopKick pickup truck. Ion blaster and missile launcher accessories included.</p>",
    slug: "product-tf-legacy-ironhide-voyager",
    category: "category-tf-autobots",
    subcategory: "Legacy",
    brand: "Transformers",
    price: 4499,
    currency: _CURRENCY,
    stockQuantity: 10,
    availableQuantity: 8,
    mainImage: img("tf-ironhide-legacy"),
    images: [img("tf-ironhide-legacy")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["transformers", "ironhide", "legacy", "voyager", "gmctopkick"],
    specifications: [
      { name: "Class", value: "Voyager Class" },
      { name: "Series", value: "Legacy" },
      { name: "Alt Mode", value: "GMC TopKick pickup truck" },
      { name: "Height (Robot)", value: "~18 cm" },
    ],
    features: ["GMC TopKick truck alt mode", "Ion blaster + missile launcher", "Heavy battle armour deco"],
    shippingInfo: "Original packaging. Padded nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: true,
    insuranceCost: 99,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.7,
    reviewCount: 15,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(6),
  },

  {
    id: "product-tf-grimlock-leader-legacy-sk-5",
    title: "Transformers Legacy Grimlock â€” Leader Class Dinobot",
    description: "<p>Grimlock Leader Class from Legacy â€” the king of the Dinobots in his most detailed form. Converts from T-Rex dinosaur to robot in 35 steps. Sword and shield accessories. Chrome head and chest elements. Me Grimlock strongest!</p>",
    slug: "product-tf-legacy-grimlock-leader-dinobot",
    category: "category-tf-autobots",
    subcategory: "Legacy",
    brand: "Transformers",
    price: 8999,
    currency: _CURRENCY,
    stockQuantity: 6,
    availableQuantity: 5,
    mainImage: img("tf-grimlock-legacy"),
    images: [img("tf-grimlock-legacy"), img("tf-grimlock-t-rex")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "grimlock", "legacy", "leader", "dinobot", "g1"],
    specifications: [
      { name: "Class", value: "Leader Class" },
      { name: "Series", value: "Legacy" },
      { name: "Alt Mode", value: "Tyrannosaurus Rex" },
      { name: "Height (Robot)", value: "~26 cm" },
      { name: "Conversion Steps", value: "35" },
    ],
    features: ["T-Rex to robot 35-step conversion", "Chrome head and chest", "Sword + shield accessories", "Light-up eyes in T-Rex mode"],
    shippingInfo: "Large rigid box. Insured nationwide delivery.",
    returnPolicy: "10-day returns for factory-sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 249,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(20),
    avgRating: 4.9,
    reviewCount: 42,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(2),
  },

  // â”€â”€ DECEPTICONS (4) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "product-tf-megatron-leader-ss-sk-6",
    title: "Transformers Studio Series Megatron â€” Leader Class (TF1 Movie)",
    description: "<p>Studio Series Megatron from the 2007 movie â€” Leader Class with movie-accurate alien jet alt mode. Complex 40-step conversion. Fusion cannon accessory with clear energon blast effect. The most detailed Megatron figure ever made.</p>",
    slug: "product-tf-studio-series-megatron-leader-tf1",
    category: "category-tf-decepticons",
    subcategory: "Studio Series",
    brand: "Transformers",
    price: 9999,
    currency: _CURRENCY,
    stockQuantity: 5,
    availableQuantity: 4,
    mainImage: img("tf-megatron-ss"),
    images: [img("tf-megatron-ss"), img("tf-megatron-jet")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "megatron", "studio series", "leader", "tf1", "decepticons"],
    specifications: [
      { name: "Class", value: "Leader Class" },
      { name: "Series", value: "Studio Series" },
      { name: "Film", value: "Transformers (2007)" },
      { name: "Alt Mode", value: "Cybertronian Jet" },
      { name: "Height (Robot)", value: "~28 cm" },
      { name: "Conversion Steps", value: "40" },
    ],
    features: ["40-step conversion", "Movie-accurate Cybertronian jet", "Fusion cannon with blast FX", "Light-piping eyes"],
    shippingInfo: "Large rigid box. Insured heavy-duty shipping.",
    returnPolicy: "10-day returns for factory-sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 299,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(25),
    avgRating: 4.9,
    reviewCount: 38,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(2),
  },

  {
    id: "product-tf-starscream-deluxe-legacy-sk-7",
    title: "Transformers Legacy Starscream â€” Deluxe Class (F-15 Eagle)",
    description: "<p>Legacy Starscream â€” an F-15 Eagle that faithfully represents the treacherous Decepticon Air Commander. Converts in 18 steps. Null ray cannons and display stand included. Classic null-ray shoulder cannons that clip to fighter jet mode.</p>",
    slug: "product-tf-legacy-starscream-deluxe-f15",
    category: "category-tf-decepticons",
    subcategory: "Legacy",
    brand: "Transformers",
    price: 3299,
    currency: _CURRENCY,
    stockQuantity: 11,
    availableQuantity: 9,
    mainImage: img("tf-starscream-legacy"),
    images: [img("tf-starscream-legacy")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["transformers", "starscream", "legacy", "deluxe", "f-15", "decepticons"],
    specifications: [
      { name: "Class", value: "Deluxe Class" },
      { name: "Series", value: "Legacy" },
      { name: "Alt Mode", value: "F-15 Eagle jet fighter" },
      { name: "Conversion Steps", value: "18" },
    ],
    features: ["F-15 Eagle jet fighter alt mode", "Null ray shoulder cannons", "18-step conversion", "Crown accessory"],
    shippingInfo: "Original packaging. Nationwide delivery.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.6,
    reviewCount: 14,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(7),
  },

  {
    id: "product-tf-soundwave-voyager-legacy-sk-8",
    title: "Transformers Legacy Soundwave â€” Voyager Class (Cassette Player)",
    description: "<p>Legacy Soundwave â€” the Decepticon Communications Officer in his iconic cassette player alt mode. Voyager Class with Laserbeak cassette that converts and perches on Soundwave's arm. Two included Minicons.</p>",
    slug: "product-tf-legacy-soundwave-voyager-cassette",
    category: "category-tf-decepticons",
    subcategory: "Legacy",
    brand: "Transformers",
    price: 4999,
    currency: _CURRENCY,
    stockQuantity: 8,
    availableQuantity: 6,
    mainImage: img("tf-soundwave-legacy"),
    images: [img("tf-soundwave-legacy")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "soundwave", "legacy", "voyager", "cassette", "laserbeak"],
    specifications: [
      { name: "Class", value: "Voyager Class" },
      { name: "Series", value: "Legacy" },
      { name: "Alt Mode", value: "Cassette Player" },
      { name: "Height (Robot)", value: "~18 cm" },
      { name: "Includes", value: "Laserbeak + Ravage cassette Mini-Cons" },
    ],
    features: ["Cassette player alt mode", "Includes Laserbeak + Ravage Mini-Cons", "Ejectable cassette door", "Shoulder cannon"],
    shippingInfo: "Original packaging. Padded nationwide.",
    returnPolicy: "10-day returns.",
    condition: "new",
    insurance: false,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.9,
    reviewCount: 51,
    createdAt: daysAgo(65),
    updatedAt: daysAgo(3),
  },

  {
    id: "product-tf-shockwave-leader-wfc-sk-9",
    title: "Transformers War for Cybertron Shockwave â€” Leader Class",
    description: "<p>WFC Siege Shockwave â€” the logical Decepticon scientist in his most articulated form. Converts between a Cybertronian tank/cannon and a towering robot. Two-way arm-cannon fires projectiles. Purple and grey precision engineering.</p>",
    slug: "product-tf-wfc-siege-shockwave-leader",
    category: "category-tf-decepticons",
    subcategory: "War for Cybertron",
    brand: "Transformers",
    price: 8499,
    currency: _CURRENCY,
    stockQuantity: 6,
    availableQuantity: 5,
    mainImage: img("tf-shockwave-wfc"),
    images: [img("tf-shockwave-wfc")],
    status: "published",
    ...SK,
    featured: false,
    tags: ["transformers", "shockwave", "war for cybertron", "siege", "leader"],
    specifications: [
      { name: "Class", value: "Leader Class" },
      { name: "Series", value: "War for Cybertron: Siege" },
      { name: "Alt Mode", value: "Cybertronian Tank/Cannon" },
      { name: "Height (Robot)", value: "~25 cm" },
    ],
    features: ["Firing arm cannon projectile", "Cybertronian tank alt mode", "WFC Weaponizer parts", "Purple precision deco"],
    shippingInfo: "Large rigid box. Insured nationwide.",
    returnPolicy: "10-day returns for sealed items.",
    condition: "new",
    insurance: true,
    insuranceCost: 249,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: false,
    avgRating: 4.8,
    reviewCount: 27,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(4),
  },

  // â”€â”€ COMBINERS (1) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "product-tf-devastator-combiner-ss-sk-10",
    title: "Transformers Studio Series Devastator â€” Combiner Set (6 Constructicons)",
    description: "<p>Studio Series Devastator â€” all 6 Constructicons that combine to form the massive Devastator from Revenge of the Fallen. Each figure individually transforms, and all 6 combine in a precise 50+ step sequence. The most screen-accurate Devastator toy ever made. Giant at 47 cm tall in combined mode.</p>",
    slug: "product-tf-studio-series-devastator-combiner-6pack",
    category: "category-tf-combiners",
    subcategory: "Studio Series",
    brand: "Transformers",
    price: 24999,
    currency: _CURRENCY,
    stockQuantity: 3,
    availableQuantity: 2,
    mainImage: img("tf-devastator-ss"),
    images: [img("tf-devastator-ss"), img("tf-devastator-combined"), img("tf-devastator-parts")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "devastator", "studio series", "combiner", "constructicons", "rotf"],
    specifications: [
      { name: "Class", value: "Combiner (6 Constructicons)" },
      { name: "Series", value: "Studio Series" },
      { name: "Film", value: "Revenge of the Fallen (2009)" },
      { name: "Combined Height", value: "~47 cm" },
      { name: "Vehicle Modes", value: "6 construction vehicles" },
      { name: "Combination Steps", value: "50+" },
    ],
    features: ["All 6 Constructicons included", "Each transforms individually", "50+ step combination sequence", "47 cm combined height", "Movie-accurate colour scheme"],
    shippingInfo: "Very large collector box. Insured heavyweight shipping.",
    returnPolicy: "10-day returns for factory-sealed items only.",
    condition: "new",
    insurance: true,
    insuranceCost: 699,
    shippingPaidBy: "buyer",
    isAuction: false,
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(30),
    avgRating: 4.9,
    reviewCount: 29,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },

  // â”€â”€ AUCTION (1) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "auction-tf-g1-optimus-prime-1984-misb-sk-1",
    title: "AUCTION â€” Vintage G1 Optimus Prime 1984 MISB (Factory Sealed)",
    description: "<p>Ultra-rare 1984 Generation 1 Optimus Prime â€” Mint In Sealed Box (MISB). Original Hasbro US release in full G1 packaging with Rubsign on box. The box is sealed with original tape. Never opened. This is the holy grail of Transformers collecting. Certificate of authenticity from Hasbro Heritage verified.</p>",
    slug: "auction-tf-g1-optimus-prime-1984-misb",
    category: "category-tf-autobots",
    subcategory: "G1 Vintage",
    brand: "Transformers",
    price: 0,
    currency: _CURRENCY,
    stockQuantity: 1,
    availableQuantity: 1,
    mainImage: img("tf-g1-optimus-misb"),
    images: [img("tf-g1-optimus-misb"), img("tf-g1-optimus-box-back"), img("tf-g1-optimus-box-side")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "g1", "optimus prime", "1984", "vintage", "misb", "auction", "grail"],
    specifications: [
      { name: "Year", value: "1984 (Original Release)" },
      { name: "Series", value: "Generation 1 (G1)" },
      { name: "Condition", value: "MISB â€” Mint in Sealed Box" },
      { name: "Market", value: "US Hasbro Release" },
      { name: "Authentication", value: "Hasbro Heritage verified" },
    ],
    features: ["Original 1984 G1 release", "Factory-sealed box", "Hasbro Heritage certificate of authenticity", "Original Rubsign intact on box", "Full G1 cardback artwork"],
    shippingInfo: "Insured white-glove shipping. Museum-grade protective casing.",
    returnPolicy: "No returns on auction wins.",
    condition: "new",
    insurance: true,
    insuranceCost: 1999,
    shippingPaidBy: "buyer",
    isAuction: true,
    auctionEndDate: daysAhead(14),
    startingBid: 99999,
    currentBid: 145000,
    bidCount: 22,
    reservePrice: 150000,
    buyNowPrice: 349999,
    minBidIncrement: 5000,
    autoExtendable: true,
    auctionExtensionMinutes: 10,
    auctionOriginalEndDate: daysAhead(14),
    auctionShippingPaidBy: "winner",
    isPreOrder: false,
    isPromoted: true,
    promotionEndDate: daysAhead(14),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },

  // â”€â”€ PRE-ORDER (1) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  {
    id: "preorder-tf-legacy-united-collector-2026-sk-1",
    title: "PRE-ORDER â€” Transformers Legacy United Collector Edition 2026",
    description: "<p>Reserve the upcoming Transformers Legacy United Collector Edition 2026 set â€” featuring G1, Beast Wars, and Unicron Trilogy characters in a massive 10-figure set. Includes exclusive clear Energon variants, collector book, and display plinth. Limited to 1,500 sets India-wide.</p>",
    slug: "preorder-tf-legacy-united-collector-2026",
    category: "category-tf-combiners",
    subcategory: "Legacy United",
    brand: "Transformers",
    price: 19999,
    currency: _CURRENCY,
    stockQuantity: 50,
    availableQuantity: 37,
    mainImage: img("tf-legacy-united"),
    images: [img("tf-legacy-united")],
    status: "published",
    ...SK,
    featured: true,
    tags: ["transformers", "legacy united", "collector edition", "pre-order", "2026", "g1", "beast wars"],
    specifications: [
      { name: "Series", value: "Transformers Legacy United" },
      { name: "Edition", value: "Collector Edition 2026" },
      { name: "Contents", value: "10 figures + book + display" },
      { name: "India Limit", value: "1,500 sets" },
      { name: "Expected Delivery", value: "Q4 2026" },
    ],
    features: ["10 unique figures (G1 + Beast Wars + Unicron Trilogy)", "Exclusive Energon clear variants", "Collector's artbook (100 pages)", "Display plinth"],
    shippingInfo: "Special collector packaging. Insured dispatch on release.",
    returnPolicy: "Pre-orders: cancel before dispatch date.",
    condition: "new",
    insurance: true,
    insuranceCost: 499,
    shippingPaidBy: "seller",
    isAuction: false,
    isPreOrder: true,
    preOrderDeliveryDate: daysAhead(200),
    preOrderProductionStatus: "upcoming",
    isPromoted: true,
    promotionEndDate: daysAhead(100),
    avgRating: 0,
    reviewCount: 0,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
];