/*
 * WHY: Provides 18 seed user accounts covering all marketplace roles and demographics.
 * WHAT: Exports 18 UserDocument partials — 1 admin, 2 sellers (store owners, one of which
 *       is also the dedicated isTester QA account), 15 buyers.
 *       All passwords are TempPass123! in the Firebase Auth emulator. UIDs match slugs.
 *
 * EXPORTS:
 *   usersSeedData — array of 18 Partial<UserDocument> objects for the seed runner
 *
 * @tag domain:users,auth
 * @tag layer:seed
 * @tag pattern:none
 * @tag access:server-only
 * @tag consumers:seed/runner.ts
 * @tag sideEffects:none
 */

import { getDefaultPhonePrefix } from "./seed-market-config";
import type { UserDocument } from "../features/auth/schemas";
import { USER_FIELDS } from "../constants/field-names";
import { seedPhoto } from "./_helpers/media";

const _ph = getDefaultPhonePrefix();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const usersSeedData: Partial<UserDocument>[] = [
  // ── Admin (also acts as buyer — has orders/cart/wishlist/history) ───────────
  {
    uid: "user-admin-letitrip",
    email: "admin@letitrip.in",
    phoneNumber: `${_ph}9999900000`,
    phoneVerified: true,
    displayName: "Mock User 1",
    photoURL:
      seedPhoto("user-avatar-letitrip-admin-20260101", 400, 400),
    avatarMetadata: {
      url: seedPhoto("user-avatar-letitrip-admin-20260101", 400, 400),
      position: { x: 50, y: 50 },
      zoom: 1.0,
    },
    role: USER_FIELDS.ROLE_VALUES.ADMIN,
    emailVerified: true,
    disabled: false,
    storeId: "store-letitrip-official",
    storeSlug: "store-letitrip-official",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "LetItRip platform administrator. India's largest collectibles marketplace.",
      location: "Mumbai, Maharashtra",
      storeName: "LetItRip Official",
      storeCategory: "category-spinning-tops",
    },
    stats: { totalOrders: 20, auctionsWon: 2, itemsSold: 200, reviewsCount: 0 },
    metadata: {
      lastSignInTime: daysAgo(1),
      creationTime: daysAgo(400).toISOString(),
      loginCount: 400,
    },
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },

  // ── Buyer: Mock User 2 (rival tournament blader — was a seller persona, now a
  //    high-spend buyer/collector; the platform only has 2 real seller stores) ──
  {
    uid: "user-seto-kaiba",
    email: "vivaan.kapoor@gmail.com",
    phoneNumber: `${_ph}9999900001`,
    phoneVerified: true,
    displayName: "Mock User 2",
    photoURL: seedPhoto("user-avatar-vivaan-kapoor-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Beyblade collector and rival tournament blader. Always hunting the next limited edition to add to my vault.",
      location: "Nagpur, Maharashtra",
      socialLinks: { instagram: "https://instagram.com/vivaan.beyblade" },
    },
    stats: { totalOrders: 20, auctionsWon: 3, itemsSold: 0, reviewsCount: 35 },
    metadata: {
      lastSignInTime: daysAgo(1),
      creationTime: daysAgo(350).toISOString(),
      loginCount: 250,
    },
    createdAt: daysAgo(350),
    updatedAt: daysAgo(1),
  },

  // ── Buyer: Mock User 3 (Beyblade stadium champion, pure buyer) ─────────────
  {
    uid: "user-yugi-muto",
    email: "rehan.sheikh@gmail.com",
    phoneNumber: `${_ph}9999900002`,
    phoneVerified: true,
    displayName: "Mock User 3",
    photoURL: seedPhoto("user-avatar-rehan-sheikh-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Beyblade stadium champion — undefeated in 40+ local tournaments. Chasing limited-edition Takara-Tomy launchers and vintage originals.",
      location: "Indore, Madhya Pradesh",
      socialLinks: { instagram: "https://instagram.com/rehan.letitrip" },
    },
    stats: { totalOrders: 30, auctionsWon: 5, itemsSold: 0, reviewsCount: 20 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(300).toISOString(),
      loginCount: 180,
    },
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },

  // ── Buyer: Ash (Pokémon + collectibles enthusiast) ──────────────────────────
  {
    uid: "user-ash-trainer",
    email: "ash@pokemonpalace.in",
    phoneNumber: `${_ph}9999900003`,
    phoneVerified: true,
    displayName: "Mock User 4",
    photoURL: seedPhoto("user-avatar-ash-ketchum-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Pokémon Master and collectibles enthusiast from Bengaluru. Always chasing the next rare pull.",
      location: "Bengaluru, Karnataka",
    },
    stats: { totalOrders: 5, auctionsWon: 1, itemsSold: 0, reviewsCount: 8 },
    metadata: { lastSignInTime: daysAgo(3), creationTime: daysAgo(200).toISOString(), loginCount: 90 },
    createdAt: daysAgo(200),
    updatedAt: daysAgo(3),
  },

  // ── Buyer: Priya (multi-TCG collector) ──────────────────────────────────────
  {
    uid: "user-priya-cards",
    email: "priya@cardgamehub.in",
    phoneNumber: `${_ph}9999900004`,
    phoneVerified: true,
    displayName: "Mock User 5",
    photoURL: seedPhoto("user-avatar-priya-sharma-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "TCG enthusiast and tournament organizer from Hyderabad. Multi-TCG collector.",
      location: "Hyderabad, Telangana",
    },
    stats: { totalOrders: 3, auctionsWon: 0, itemsSold: 0, reviewsCount: 4 },
    metadata: { lastSignInTime: daysAgo(5), creationTime: daysAgo(180).toISOString(), loginCount: 60 },
    createdAt: daysAgo(180),
    updatedAt: daysAgo(5),
  },

  // ── Seller: Tyson (Beyblade Arena owner) ────────────────────────────────────
  {
    uid: "user-tyson-blader",
    email: "tyson@beybladearena.in",
    phoneNumber: `${_ph}9999900006`,
    phoneVerified: true,
    displayName: "Mock User 6",
    photoURL: seedPhoto("user-avatar-tyson-granger-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.SELLER,
    emailVerified: true,
    disabled: false,
    storeId: "store-beyblade-arena",
    storeSlug: "store-beyblade-arena",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Beyblade champion. Importing authentic Takara-Tomy Beyblades from Japan. Let It Rip!",
      location: "Chennai, Tamil Nadu",
      storeName: "Beyblade Arena",
      storeCategory: "category-spinning-tops",
    },
    stats: { totalOrders: 4, auctionsWon: 0, itemsSold: 95, reviewsCount: 6 },
    metadata: { lastSignInTime: daysAgo(4), creationTime: daysAgo(150).toISOString(), loginCount: 70 },
    createdAt: daysAgo(150),
    updatedAt: daysAgo(4),
  },

  // ── Buyer: Megumi (anime figure + model kit collector) ─────────────────────
  {
    uid: "user-megumi-figures",
    email: "megumi@tokyotoys.in",
    phoneNumber: `${_ph}9999900007`,
    phoneVerified: true,
    displayName: "Mock User 7",
    photoURL: seedPhoto("user-avatar-megumi-tanaka-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Anime figure and model kit collector from Pune. Always on the hunt for authentic imports.",
      location: "Pune, Maharashtra",
    },
    stats: { totalOrders: 2, auctionsWon: 0, itemsSold: 0, reviewsCount: 3 },
    metadata: { lastSignInTime: daysAgo(2), creationTime: daysAgo(120).toISOString(), loginCount: 55 },
    createdAt: daysAgo(120),
    updatedAt: daysAgo(2),
  },

  // ── Buyer: Amuro (Gunpla builder) ───────────────────────────────────────────
  {
    uid: "user-amuro-builder",
    email: "amuro@gundamgalaxy.in",
    phoneNumber: `${_ph}9999900008`,
    phoneVerified: true,
    displayName: "Mock User 8",
    photoURL: seedPhoto("user-avatar-amuro-ray-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Gunpla builder since 2005. Over 200 kits built. Collects Bandai Hobby imports.",
      location: "Kolkata, West Bengal",
    },
    stats: { totalOrders: 1, auctionsWon: 0, itemsSold: 0, reviewsCount: 2 },
    metadata: { lastSignInTime: daysAgo(6), creationTime: daysAgo(90).toISOString(), loginCount: 35 },
    createdAt: daysAgo(90),
    updatedAt: daysAgo(6),
  },

  // ── Buyer: Ananya (Pokémon + anime collector) ──────────────────────────────
  {
    uid: "user-ananya-collector",
    email: "ananya.patel@gmail.com",
    phoneNumber: `${_ph}9999900009`,
    phoneVerified: true,
    displayName: "Mock User 9",
    photoURL: seedPhoto("user-avatar-ananya-patel-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: true,
      bio: "Pokémon TCG and anime figure collector from Mumbai. Charizard enthusiast.",
      location: "Mumbai, Maharashtra",
    },
    stats: { totalOrders: 15, auctionsWon: 3, itemsSold: 0, reviewsCount: 10 },
    metadata: { lastSignInTime: daysAgo(1), creationTime: daysAgo(180).toISOString(), loginCount: 120 },
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },

  // ── Buyer: Vikram (Hot Wheels collector) ────────────────────────────────────
  {
    uid: "user-vikram-wheels",
    email: "vikram.hw@gmail.com",
    phoneNumber: `${_ph}9999900010`,
    phoneVerified: true,
    displayName: "Mock User 10",
    photoURL: seedPhoto("user-avatar-vikram-singh-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Hot Wheels Treasure Hunt collector. Chasing the next Super TH.",
      location: "Jaipur, Rajasthan",
    },
    stats: { totalOrders: 22, auctionsWon: 0, itemsSold: 0, reviewsCount: 8 },
    metadata: { lastSignInTime: daysAgo(3), creationTime: daysAgo(200).toISOString(), loginCount: 95 },
    createdAt: daysAgo(200),
    updatedAt: daysAgo(3),
  },

  // ── Buyer: Meera (Beyblade collector) ───────────────────────────────────────
  {
    uid: "user-meera-bey",
    email: "meera.blader@gmail.com",
    phoneNumber: `${_ph}9999900011`,
    phoneVerified: true,
    displayName: "Mock User 11",
    photoURL: seedPhoto("user-avatar-meera-nair-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.SELLER,
    emailVerified: true,
    disabled: false,
    storeId: "store-blader-bazaar",
    storeSlug: "store-blader-bazaar",
    storeStatus: "pending",
    publicProfile: {
      storeName: "Blader Bazaar",
      storeCategory: "category-beyblade-burst",
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: true,
      bio: "Beyblade X collector and tournament player from Kochi.",
      location: "Kochi, Kerala",
    },
    stats: { totalOrders: 8, auctionsWon: 1, itemsSold: 0, reviewsCount: 4 },
    metadata: { lastSignInTime: daysAgo(5), creationTime: daysAgo(100).toISOString(), loginCount: 45 },
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },

  // ── Buyer: Arjun (Gunpla builder) ───────────────────────────────────────────
  {
    uid: "user-arjun-gunpla",
    email: "arjun.builder@gmail.com",
    phoneNumber: `${_ph}9999900012`,
    phoneVerified: true,
    displayName: "Mock User 12",
    photoURL: seedPhoto("user-avatar-arjun-reddy-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Gunpla hobbyist building MG and PG kits. Airbrushing enthusiast.",
      location: "Hyderabad, Telangana",
    },
    stats: { totalOrders: 6, auctionsWon: 0, itemsSold: 0, reviewsCount: 3 },
    metadata: { lastSignInTime: daysAgo(7), creationTime: daysAgo(80).toISOString(), loginCount: 30 },
    createdAt: daysAgo(80),
    updatedAt: daysAgo(7),
  },

  // ── Buyer: Sneha (vintage collector) ────────────────────────────────────────
  {
    uid: "user-sneha-vintage",
    email: "sneha.vintage@gmail.com",
    phoneNumber: `${_ph}9999900013`,
    phoneVerified: true,
    displayName: "Mock User 13",
    photoURL: seedPhoto("user-avatar-sneha-gupta-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.SELLER,
    emailVerified: true,
    disabled: false,
    storeId: "store-vintage-vault-co",
    storeSlug: "store-vintage-vault-co",
    storeStatus: "approved",
    publicProfile: {
      storeName: "Vintage Vault Co.",
      storeCategory: "category-beyblade-original",
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: true,
      bio: "Vintage toy collector. 80s/90s action figures and first-edition cards.",
      location: "Lucknow, Uttar Pradesh",
    },
    stats: { totalOrders: 12, auctionsWon: 4, itemsSold: 0, reviewsCount: 6 },
    metadata: { lastSignInTime: daysAgo(2), creationTime: daysAgo(160).toISOString(), loginCount: 75 },
    createdAt: daysAgo(160),
    updatedAt: daysAgo(2),
  },

  // ── Buyer: Rohit (multi-category) ───────────────────────────────────────────
  {
    uid: "user-rohit-collector",
    email: "rohit.collect@gmail.com",
    phoneNumber: `${_ph}9999900014`,
    phoneVerified: true,
    displayName: "Mock User 14",
    photoURL: seedPhoto("user-avatar-rohit-agarwal-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Collector of everything — cards, figures, diecast. If it's collectible, I want it.",
      location: "Pune, Maharashtra",
    },
    stats: { totalOrders: 25, auctionsWon: 6, itemsSold: 0, reviewsCount: 12 },
    metadata: { lastSignInTime: daysAgo(1), creationTime: daysAgo(220).toISOString(), loginCount: 140 },
    createdAt: daysAgo(220),
    updatedAt: daysAgo(1),
  },

  // ── Buyer: Divya (Funko Pop collector) ──────────────────────────────────────
  {
    uid: "user-divya-funko",
    email: "divya.funko@gmail.com",
    phoneNumber: `${_ph}9999900015`,
    phoneVerified: true,
    displayName: "Mock User 15",
    photoURL: seedPhoto("user-avatar-divya-menon-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: true,
      bio: "Funko Pop! collector. Chase variants are my weakness. Marvel and anime pops.",
      location: "Bengaluru, Karnataka",
    },
    stats: { totalOrders: 18, auctionsWon: 2, itemsSold: 0, reviewsCount: 7 },
    metadata: { lastSignInTime: daysAgo(4), creationTime: daysAgo(130).toISOString(), loginCount: 65 },
    createdAt: daysAgo(130),
    updatedAt: daysAgo(4),
  },

  // ── Buyer: Karthik (new user, few orders) ──────────────────────────────────
  {
    uid: "user-karthik-new",
    email: "karthik.new@gmail.com",
    phoneNumber: `${_ph}9999900016`,
    phoneVerified: false,
    displayName: "Mock User 16",
    photoURL: seedPhoto("user-avatar-karthik-iyer-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "New to collecting. Exploring trading cards and diecast.",
      location: "Chennai, Tamil Nadu",
    },
    stats: { totalOrders: 2, auctionsWon: 0, itemsSold: 0, reviewsCount: 1 },
    metadata: { lastSignInTime: daysAgo(10), creationTime: daysAgo(30).toISOString(), loginCount: 8 },
    createdAt: daysAgo(30),
    updatedAt: daysAgo(10),
  },

  // ── Buyer: Neha (One Piece TCG fan) ─────────────────────────────────────────
  {
    uid: "user-neha-onepiece",
    email: "neha.op@gmail.com",
    phoneNumber: `${_ph}9999900017`,
    phoneVerified: true,
    displayName: "Mock User 17",
    photoURL: seedPhoto("user-avatar-neha-joshi-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.USER,
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: true,
      bio: "One Piece TCG and manga collector. Luffy is king!",
      location: "Ahmedabad, Gujarat",
    },
    stats: { totalOrders: 10, auctionsWon: 1, itemsSold: 0, reviewsCount: 5 },
    metadata: { lastSignInTime: daysAgo(3), creationTime: daysAgo(110).toISOString(), loginCount: 50 },
    createdAt: daysAgo(110),
    updatedAt: daysAgo(3),
  },

  // ── Tester QA account (role stays "seller" — isTester unlocks Tester Hub + auto-approved store) ──
  {
    uid: "user-tester-qa",
    email: "tester@letitrip.in",
    phoneNumber: `${_ph}9999900018`,
    phoneVerified: true,
    displayName: "Mock User 18",
    photoURL: seedPhoto("user-avatar-qa-tester-20260101", 400, 400),
    role: USER_FIELDS.ROLE_VALUES.SELLER,
    isTester: true,
    emailVerified: true,
    disabled: false,
    storeId: "store-tester-qa-seller",
    storeSlug: "store-tester-qa-seller",
    storeStatus: "approved",
    payoutDetails: {
      method: "upi",
      upiId: "tester-qa@upi",
      isConfigured: true,
    },
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Dedicated QA tester account for the Tester QA Program — runs through the checklist against the shared test sandbox.",
      location: "Bengaluru, Karnataka",
      storeName: "Tester QA Seller Store",
      storeCategory: "category-spinning-tops",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 0, reviewsCount: 0 },
    metadata: { lastSignInTime: daysAgo(1), creationTime: daysAgo(1).toISOString(), loginCount: 5 },
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];
