/**
 * Users Seed Data — Collectibles Marketplace
 * 9 users: 1 admin, 4 sellers (one per collectibles vertical), 4 buyers.
 * id === uid === slug convention. Indian market locale.
 */

import { getDefaultPhonePrefix } from "./seed-market-config";
import type { UserDocument } from "../features/auth/schemas";

const _ph = getDefaultPhonePrefix();
const NOW = new Date();
const daysAgo = (n: number) => new Date(NOW.getTime() - n * 86_400_000);

export const usersSeedData: Partial<UserDocument>[] = [
  // ── Admin ──────────────────────────────────────────────────────────────────
  {
    uid: "user-admin-letitrip",
    email: "admin@letitrip.in",
    phoneNumber: `${_ph}9876500000`,
    phoneVerified: true,
    displayName: "LetItRip Admin",
    photoURL: null,
    avatarMetadata: null,
    role: "admin",
    emailVerified: true,
    disabled: false,
    storeId: "store-letitrip-official",
    storeSlug: "store-letitrip-official",
    storeStatus: "approved",
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "LetItRip platform administrator.",
    },
    stats: { totalOrders: 0, auctionsWon: 0, itemsSold: 0, reviewsCount: 0 },
    metadata: {
      lastSignInTime: daysAgo(1),
      creationTime: daysAgo(400).toISOString(),
      loginCount: 300,
    },
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },

  // ── Sellers ────────────────────────────────────────────────────────────────

  // Seller 1: Pokémon TCG specialist
  {
    uid: "user-aryan-kapoor",
    email: "aryan@pokemonpalace.in",
    phoneNumber: `${_ph}9876501001`,
    phoneVerified: true,
    displayName: "Aryan Kapoor",
    photoURL:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeId: "store-pokemon-palace",
    storeSlug: "store-pokemon-palace",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Pokémon TCG enthusiast and collector since 2010. Specialising in sealed product, graded slabs, and rare vintage cards.",
      location: "Mumbai, Maharashtra",
      socialLinks: { instagram: "https://instagram.com/aryan.pokecollector" },
      storeName: "Pokémon Palace",
      storeCategory: "trading-cards",
    },
    stats: { totalOrders: 12, auctionsWon: 3, itemsSold: 87, reviewsCount: 42 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(380).toISOString(),
      loginCount: 95,
    },
    createdAt: daysAgo(380),
    updatedAt: daysAgo(2),
  },

  // Seller 2: Yu-Gi-Oh! & Trading Cards
  {
    uid: "user-nisha-reddy",
    email: "nisha@cardgamehub.in",
    phoneNumber: `${_ph}9876502002`,
    phoneVerified: true,
    displayName: "Nisha Reddy",
    photoURL:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeId: "store-cardgame-hub",
    storeSlug: "store-cardgame-hub",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Yu-Gi-Oh! TCG player and sealed product trader. WCS 2022 qualifier. Top-grade singles and booster boxes.",
      location: "Hyderabad, Telangana",
      socialLinks: { instagram: "https://instagram.com/nisha.cardgamehub" },
      storeName: "CardGame Hub",
      storeCategory: "trading-cards",
    },
    stats: { totalOrders: 8, auctionsWon: 1, itemsSold: 64, reviewsCount: 31 },
    metadata: {
      lastSignInTime: daysAgo(3),
      creationTime: daysAgo(350).toISOString(),
      loginCount: 67,
    },
    createdAt: daysAgo(350),
    updatedAt: daysAgo(3),
  },

  // Seller 3: Diecast cars (Hot Wheels + Tomica)
  {
    uid: "user-vikram-mehta",
    email: "vikram@diecastdepot.in",
    phoneNumber: `${_ph}9876503003`,
    phoneVerified: true,
    displayName: "Vikram Mehta",
    photoURL:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeId: "store-diecast-depot",
    storeSlug: "store-diecast-depot",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Hot Wheels and Tomica collector since 2005. STH hunter, Car Culture completionist, and Tomica Limited Vintage dealer.",
      location: "Delhi, NCR",
      socialLinks: {
        instagram: "https://instagram.com/vikram.diecastdepot",
        facebook: "https://facebook.com/diecastdepot",
      },
      storeName: "Diecast Depot",
      storeCategory: "diecast-vehicles",
    },
    stats: { totalOrders: 5, auctionsWon: 2, itemsSold: 115, reviewsCount: 58 },
    metadata: {
      lastSignInTime: daysAgo(1),
      creationTime: daysAgo(320).toISOString(),
      loginCount: 140,
    },
    createdAt: daysAgo(320),
    updatedAt: daysAgo(1),
  },

  // Seller 4: Beyblade X + Burst
  {
    uid: "user-rohit-joshi",
    email: "rohit@beyladearena.in",
    phoneNumber: `${_ph}9876504004`,
    phoneVerified: true,
    displayName: "Rohit Joshi",
    photoURL:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeId: "store-beyblade-arena",
    storeSlug: "store-beyblade-arena",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "India's top Beyblade X and Burst supplier. Directly importing from Takara Tomy Japan. Official tops, launchers, and XStadiums.",
      location: "Pune, Maharashtra",
      socialLinks: {
        instagram: "https://instagram.com/rohit.beyaladearena",
      },
      storeName: "Beyblade Arena",
      storeCategory: "spinning-tops",
    },
    stats: { totalOrders: 9, auctionsWon: 0, itemsSold: 73, reviewsCount: 47 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(290).toISOString(),
      loginCount: 88,
    },
    createdAt: daysAgo(290),
    updatedAt: daysAgo(2),
  },

  // ── Buyers ─────────────────────────────────────────────────────────────────

  // Buyer 1
  {
    uid: "user-rahul-sharma",
    email: "rahul.sharma@gmail.com",
    phoneNumber: `${_ph}9876511001`,
    phoneVerified: false,
    displayName: "Rahul Sharma",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Pokémon TCG collector. Chasing Base Set and Jungle holos.",
      location: "Bengaluru, Karnataka",
    },
    stats: { totalOrders: 7, auctionsWon: 2, itemsSold: 0, reviewsCount: 5 },
    metadata: {
      lastSignInTime: daysAgo(4),
      creationTime: daysAgo(200).toISOString(),
      loginCount: 24,
    },
    createdAt: daysAgo(200),
    updatedAt: daysAgo(4),
  },

  // Buyer 2
  {
    uid: "user-priya-patel",
    email: "priya.patel@gmail.com",
    phoneNumber: `${_ph}9876512002`,
    phoneVerified: true,
    displayName: "Priya Patel",
    photoURL:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Nendoroid and figma collector. Good Smile Company fan.",
      location: "Ahmedabad, Gujarat",
    },
    stats: { totalOrders: 11, auctionsWon: 1, itemsSold: 0, reviewsCount: 8 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(180).toISOString(),
      loginCount: 31,
    },
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
  },

  // Buyer 3
  {
    uid: "user-arjun-singh",
    email: "arjun.singh@gmail.com",
    phoneNumber: `${_ph}9876513003`,
    phoneVerified: false,
    displayName: "Arjun Singh",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Gunpla builder. Working through MG grade. Next target: PG Wing Zero.",
      location: "Jaipur, Rajasthan",
    },
    stats: { totalOrders: 4, auctionsWon: 0, itemsSold: 0, reviewsCount: 3 },
    metadata: {
      lastSignInTime: daysAgo(7),
      creationTime: daysAgo(150).toISOString(),
      loginCount: 12,
    },
    createdAt: daysAgo(150),
    updatedAt: daysAgo(7),
  },

  // Buyer 4
  {
    uid: "user-meera-nair",
    email: "meera.nair@gmail.com",
    phoneNumber: `${_ph}9876514004`,
    phoneVerified: true,
    displayName: "Meera Nair",
    photoURL:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Hot Wheels STH hunter and Tomica Premium collector.",
      location: "Kochi, Kerala",
    },
    stats: { totalOrders: 6, auctionsWon: 3, itemsSold: 0, reviewsCount: 4 },
    metadata: {
      lastSignInTime: daysAgo(3),
      creationTime: daysAgo(120).toISOString(),
      loginCount: 19,
    },
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },

  // ── New Sellers ────────────────────────────────────────────────────────────

  // Seller 5: Anime Figures, Gundam, Funko Pop (Tokyo Toys India)
  {
    uid: "user-priya-singh",
    email: "priya@tokyotoysindia.in",
    phoneNumber: `${_ph}9876505005`,
    phoneVerified: true,
    displayName: "Priya Singh",
    photoURL:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeId: "store-tokyo-toys-india",
    storeSlug: "store-tokyo-toys-india",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Anime figure collector and importer. Specialising in Nendoroids, S.H.Figuarts, scale figures, and Funko Pops. Direct sourcing from Akihabara and Good Smile Company.",
      location: "Chennai, Tamil Nadu",
      socialLinks: { instagram: "https://instagram.com/priya.tokyotoys" },
      storeName: "Tokyo Toys India",
      storeCategory: "action-figures",
    },
    stats: { totalOrders: 6, auctionsWon: 1, itemsSold: 52, reviewsCount: 28 },
    metadata: {
      lastSignInTime: daysAgo(1),
      creationTime: daysAgo(260).toISOString(),
      loginCount: 74,
    },
    createdAt: daysAgo(260),
    updatedAt: daysAgo(1),
  },

  // Seller 6: Gundam kits specialist (Gundam Galaxy)
  {
    uid: "user-amit-sharma",
    email: "amit@gundamgalaxy.in",
    phoneNumber: `${_ph}9876506006`,
    phoneVerified: true,
    displayName: "Amit Sharma",
    photoURL:
      "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeId: "store-gundam-galaxy",
    storeSlug: "store-gundam-galaxy",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Master Grade builder and HG completionist. Running Gundam Galaxy since 2021. All kits are authenticated Bandai — sourced from official Bandai distributors in Japan and Singapore.",
      location: "Bengaluru, Karnataka",
      socialLinks: {
        instagram: "https://instagram.com/amit.gundamgalaxy",
        twitter: "https://twitter.com/gundamgalaxy",
      },
      storeName: "Gundam Galaxy",
      storeCategory: "model-kits",
    },
    stats: { totalOrders: 4, auctionsWon: 0, itemsSold: 41, reviewsCount: 22 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(230).toISOString(),
      loginCount: 58,
    },
    createdAt: daysAgo(230),
    updatedAt: daysAgo(2),
  },

  // Seller 7: Vintage collectibles (Vintage Vault)
  {
    uid: "user-kavya-iyer",
    email: "kavya@vintagevault.in",
    phoneNumber: `${_ph}9876507007`,
    phoneVerified: true,
    displayName: "Kavya Iyer",
    photoURL:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "seller",
    emailVerified: true,
    disabled: false,
    storeId: "store-vintage-vault",
    storeSlug: "store-vintage-vault",
    storeStatus: "approved",
    publicProfile: {
      isPublic: true,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Vintage toy and collectibles specialist. 20+ years sourcing from estate sales, Tokyo flea markets, and private collections. Pokémon WOTC era, 80s action figures, and vintage Redlines.",
      location: "Kolkata, West Bengal",
      socialLinks: { instagram: "https://instagram.com/kavya.vintagevault" },
      storeName: "Vintage Vault",
      storeCategory: "vintage-rare",
    },
    stats: { totalOrders: 3, auctionsWon: 2, itemsSold: 34, reviewsCount: 19 },
    metadata: {
      lastSignInTime: daysAgo(3),
      creationTime: daysAgo(200).toISOString(),
      loginCount: 45,
    },
    createdAt: daysAgo(200),
    updatedAt: daysAgo(3),
  },

  // ── New Buyers ─────────────────────────────────────────────────────────────

  // Buyer 5 (referenced in conversations seed)
  {
    uid: "user-sneha-kumar",
    email: "sneha.kumar@gmail.com",
    phoneNumber: `${_ph}9876515005`,
    phoneVerified: true,
    displayName: "Sneha Kumar",
    photoURL:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Anime figure collector — Nendoroids and scale figures. Building a Re:Zero shelf.",
      location: "Bengaluru, Karnataka",
    },
    stats: { totalOrders: 9, auctionsWon: 1, itemsSold: 0, reviewsCount: 6 },
    metadata: {
      lastSignInTime: daysAgo(1),
      creationTime: daysAgo(110).toISOString(),
      loginCount: 28,
    },
    createdAt: daysAgo(110),
    updatedAt: daysAgo(1),
  },

  // Buyer 6 (referenced in conversations seed)
  {
    uid: "user-kartik-nair",
    email: "kartik.nair@gmail.com",
    phoneNumber: `${_ph}9876516006`,
    phoneVerified: false,
    displayName: "Kartik Nair",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Gunpla builder — currently on my first MG kit. Also collecting Hot Wheels Car Culture.",
      location: "Thiruvananthapuram, Kerala",
    },
    stats: { totalOrders: 3, auctionsWon: 0, itemsSold: 0, reviewsCount: 2 },
    metadata: {
      lastSignInTime: daysAgo(5),
      creationTime: daysAgo(90).toISOString(),
      loginCount: 9,
    },
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },

  // Buyer 7 (referenced in conversations seed)
  {
    uid: "user-divya-menon",
    email: "divya.menon@gmail.com",
    phoneNumber: `${_ph}9876517007`,
    phoneVerified: true,
    displayName: "Divya Menon",
    photoURL:
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Pokémon fan and casual collector. Pulling packs and hoping for shiny Charizard.",
      location: "Hyderabad, Telangana",
    },
    stats: { totalOrders: 5, auctionsWon: 0, itemsSold: 0, reviewsCount: 3 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(80).toISOString(),
      loginCount: 15,
    },
    createdAt: daysAgo(80),
    updatedAt: daysAgo(2),
  },

  // Buyer 8 (referenced in conversations seed)
  {
    uid: "user-ankit-gupta",
    email: "ankit.gupta@gmail.com",
    phoneNumber: `${_ph}9876518008`,
    phoneVerified: false,
    displayName: "Ankit Gupta",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Beyblade X tournament player. Building competitive lineup — Dran Sword is my go-to.",
      location: "Lucknow, Uttar Pradesh",
    },
    stats: { totalOrders: 4, auctionsWon: 0, itemsSold: 0, reviewsCount: 2 },
    metadata: {
      lastSignInTime: daysAgo(3),
      creationTime: daysAgo(75).toISOString(),
      loginCount: 11,
    },
    createdAt: daysAgo(75),
    updatedAt: daysAgo(3),
  },

  // Buyer 9
  {
    uid: "user-siddharth-rao",
    email: "siddharth.rao@gmail.com",
    phoneNumber: `${_ph}9876519009`,
    phoneVerified: true,
    displayName: "Siddharth Rao",
    photoURL:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Yu-Gi-Oh! TCG competitive player. Chasing Blue-Eyes and Chaos archetype singles.",
      location: "Pune, Maharashtra",
    },
    stats: { totalOrders: 7, auctionsWon: 1, itemsSold: 0, reviewsCount: 5 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(65).toISOString(),
      loginCount: 22,
    },
    createdAt: daysAgo(65),
    updatedAt: daysAgo(2),
  },

  // Buyer 10
  {
    uid: "user-tanvi-desai",
    email: "tanvi.desai@gmail.com",
    phoneNumber: `${_ph}9876520010`,
    phoneVerified: true,
    displayName: "Tanvi Desai",
    photoURL:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Funko Pop collector — over 200 on my shelf. Anime and Marvel are my favourites.",
      location: "Ahmedabad, Gujarat",
    },
    stats: { totalOrders: 12, auctionsWon: 0, itemsSold: 0, reviewsCount: 9 },
    metadata: {
      lastSignInTime: daysAgo(1),
      creationTime: daysAgo(55).toISOString(),
      loginCount: 35,
    },
    createdAt: daysAgo(55),
    updatedAt: daysAgo(1),
  },

  // Buyer 11 — referenced in scammers seed as a victim reporter
  {
    uid: "user-anjali-verma",
    email: "anjali.verma@gmail.com",
    phoneNumber: `${_ph}9876521011`,
    phoneVerified: true,
    displayName: "Anjali Verma",
    photoURL:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Hot Wheels collector — OLX veteran. Specialising in vintage Redlines and Car Culture sets.",
      location: "Jaipur, Rajasthan",
    },
    stats: { totalOrders: 6, auctionsWon: 0, itemsSold: 0, reviewsCount: 4 },
    metadata: {
      lastSignInTime: daysAgo(6),
      creationTime: daysAgo(50).toISOString(),
      loginCount: 14,
    },
    createdAt: daysAgo(50),
    updatedAt: daysAgo(6),
  },

  // Buyer 12
  {
    uid: "user-rohit-verma",
    email: "rohit.verma@gmail.com",
    phoneNumber: `${_ph}9876522012`,
    phoneVerified: false,
    displayName: "Rohit Verma",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "One Piece TCG player and Manga collector. Always looking for OP singles at fair price.",
      location: "Delhi, Delhi",
    },
    stats: { totalOrders: 4, auctionsWon: 0, itemsSold: 0, reviewsCount: 3 },
    metadata: {
      lastSignInTime: daysAgo(4),
      creationTime: daysAgo(45).toISOString(),
      loginCount: 12,
    },
    createdAt: daysAgo(45),
    updatedAt: daysAgo(4),
  },

  // Buyer 13
  {
    uid: "user-pooja-sharma",
    email: "pooja.sharma@gmail.com",
    phoneNumber: `${_ph}9876523013`,
    phoneVerified: true,
    displayName: "Pooja Sharma",
    photoURL:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Scale figure collector — Good Smile and Alter. Currently building a KonoSuba shelf.",
      location: "Mumbai, Maharashtra",
    },
    stats: { totalOrders: 8, auctionsWon: 1, itemsSold: 0, reviewsCount: 6 },
    metadata: {
      lastSignInTime: daysAgo(2),
      creationTime: daysAgo(40).toISOString(),
      loginCount: 19,
    },
    createdAt: daysAgo(40),
    updatedAt: daysAgo(2),
  },

  // Buyer 14
  {
    uid: "user-kiran-reddy",
    email: "kiran.reddy@gmail.com",
    phoneNumber: `${_ph}9876524014`,
    phoneVerified: false,
    displayName: "Kiran Reddy",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Gundam model kit builder. Starting with HG, working up to Master Grade. Zeon supporter.",
      location: "Hyderabad, Telangana",
    },
    stats: { totalOrders: 3, auctionsWon: 0, itemsSold: 0, reviewsCount: 2 },
    metadata: {
      lastSignInTime: daysAgo(7),
      creationTime: daysAgo(35).toISOString(),
      loginCount: 8,
    },
    createdAt: daysAgo(35),
    updatedAt: daysAgo(7),
  },

  // Buyer 15
  {
    uid: "user-naman-gupta",
    email: "naman.gupta@gmail.com",
    phoneNumber: `${_ph}9876525015`,
    phoneVerified: true,
    displayName: "Naman Gupta",
    photoURL:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Magic: The Gathering player and Pokémon casual. Drafting Modern Horizons 3 this month.",
      location: "Chandigarh, Punjab",
    },
    stats: { totalOrders: 5, auctionsWon: 0, itemsSold: 0, reviewsCount: 3 },
    metadata: {
      lastSignInTime: daysAgo(3),
      creationTime: daysAgo(30).toISOString(),
      loginCount: 11,
    },
    createdAt: daysAgo(30),
    updatedAt: daysAgo(3),
  },

  // Buyer 16
  {
    uid: "user-preeti-joshi",
    email: "preeti.joshi@gmail.com",
    phoneNumber: `${_ph}9876526016`,
    phoneVerified: true,
    displayName: "Preeti Joshi",
    photoURL:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    avatarMetadata: null,
    role: "user",
    emailVerified: true,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "Beyblade X casual fan. Daughter loves Hells Chain, I ended up getting addicted too.",
      location: "Bhopal, Madhya Pradesh",
    },
    stats: { totalOrders: 2, auctionsWon: 0, itemsSold: 0, reviewsCount: 1 },
    metadata: {
      lastSignInTime: daysAgo(8),
      creationTime: daysAgo(25).toISOString(),
      loginCount: 5,
    },
    createdAt: daysAgo(25),
    updatedAt: daysAgo(8),
  },

  // Buyer 17
  {
    uid: "user-varun-bhat",
    email: "varun.bhat@gmail.com",
    phoneNumber: `${_ph}9876527017`,
    phoneVerified: false,
    displayName: "Varun Bhat",
    photoURL: null,
    avatarMetadata: null,
    role: "user",
    emailVerified: false,
    disabled: false,
    publicProfile: {
      isPublic: false,
      showEmail: false,
      showPhone: false,
      showOrders: false,
      showWishlist: false,
      bio: "New to collecting — started with Funko Pops and now falling down the figure rabbit hole.",
      location: "Mangalore, Karnataka",
    },
    stats: { totalOrders: 1, auctionsWon: 0, itemsSold: 0, reviewsCount: 0 },
    metadata: {
      lastSignInTime: daysAgo(10),
      creationTime: daysAgo(20).toISOString(),
      loginCount: 3,
    },
    createdAt: daysAgo(20),
    updatedAt: daysAgo(10),
  },
];
