"use client";

/**
 * StatusTimeline — the one rail that renders any entity's status history.
 *
 * Both the order timeline and the offer timeline were about to be written
 * separately, against the same `StatusChangeEntry[]` shape, with the same
 * dot-and-connector rail and the same two load-bearing rules. That is the
 * duplication the Rule of Three exists to prevent, so this is the single
 * implementation and each feature supplies only its own phase vocabulary.
 *
 * ## Two rules this component must never break
 *
 * **1. Never fabricate a timestamp.** A step with no recorded date renders an
 * em-dash. Not `new Date()`, and not a proxy field: `updatedAt` means "last
 * write of any kind" and `expiresAt` is a deadline, not an event. An offer
 * that expired has no timestamp at all because `expireMany` never wrote one
 * before this wave, and inventing one would make the record lie.
 *
 * **2. It never fetches.** A client component that loaded its own chain would
 * fire one request per opened modal per portal. The API returns the chain;
 * this renders it.
 */

import type { ReactNode } from "react";
import type { FieldChange } from "../../../_internal/shared/history/index";
import { Badge, Div, Heading, Row, Stack, Text } from "../../../ui";

/** The client-facing entry shape — dates already serialised to ISO. */
export interface TimelineEntry {
  at: string;
  actorUid?: string;
  actorRole: "buyer" | "seller" | "admin" | "system";
  changes: Record<string, FieldChange>;
  reason?: string;
  note?: string;
  trigger: string;
}

export interface TimelineStep {
  key: string;
  label: string;
  /** ISO string, or absent — absent renders an em-dash, never a guess. */
  date?: string;
  /** Terminal-negative: cancelled, declined, rejected. Renders in error tone. */
  negative?: boolean;
  /**
   * Neutral-but-ended, e.g. a superseded offer round. Deliberately distinct
   * from `negative`: the buyer did not walk away, they countered, and the
   * negotiation continued.
   */
  muted?: boolean;
  actorRole?: TimelineEntry["actorRole"];
  reason?: string;
  note?: string;
  /** Round divider text for multi-round chains ("Round 2"). */
  roundLabel?: string;
}

const ACTOR_LABEL: Record<TimelineEntry["actorRole"], string> = {
  buyer: "Buyer",
  seller: "Store",
  admin: "Admin",
  system: "System",
};

export interface StatusTimelineProps {
  title?: string;
  steps: TimelineStep[];
  /** Entries trimmed off the front of the capped history, if any. */
  truncatedCount?: number;
  /** Rendered below the rail — tracking details, chain summary, etc. */
  footer?: ReactNode;
  /** Suppress `footer` when the last step is terminal-negative. */
  hideFooterWhenNegative?: boolean;
  emptyLabel?: string;
  className?: string;
}

export function StatusTimeline({
  title = "Timeline",
  steps,
  truncatedCount,
  footer,
  hideFooterWhenNegative = true,
  emptyLabel = "No history yet",
  className = "",
}: StatusTimelineProps) {
  const isTerminalNegative = steps[steps.length - 1]?.negative === true;
  const showFooter = footer && !(hideFooterWhenNegative && isTerminalNegative);

  return (
    <Div className={className} rounded="xl" padding="md" surface="muted" border="default">
      <Heading level={3} size="sm" weight="semibold" color="muted" className="mb-3">
        {title}
      </Heading>

      {truncatedCount && truncatedCount > 0 ? (
        // Say what is not being shown. Silent truncation reads as "this is all
        // of it", which is the same lie as a silently dropped field.
        <Text size="xs" color="muted" className="mb-2">
          {truncatedCount} earlier {truncatedCount === 1 ? "entry" : "entries"} trimmed
        </Text>
      ) : null}

      {steps.length === 0 ? (
        <Badge variant="default">{emptyLabel}</Badge>
      ) : (
        <Stack gap="none">
          {steps.map((step, i) => {
            const isLast = i === steps.length - 1;
            return (
              <Stack key={`${step.key}-${i}`} gap="none">
                {step.roundLabel && (
                  <Text size="xs" weight="semibold" color="muted" className="mb-1 mt-2">
                    {step.roundLabel}
                  </Text>
                )}
                <Row gap="sm" padding={isLast ? "none" : "b-md"}>
                  <Stack gap="none" align="center" className="shrink-0">
                    {/*
                      Colour comes from the `surface` VARIANT prop, which
                      resolves through surface-tokens.ts. The equivalent raw
                      utility class is never generated by either Tailwind
                      config — `danger` is a flat alias of `error` with no
                      sub-keys — so Tailwind would drop it silently and the
                      dot would render unstyled. Root Cause #67.
                    */}
                    <Div
                      className={`h-2.5 w-2.5 ${
                        step.negative || step.muted ? "" : "bg-[var(--appkit-color-primary)]"
                      }`}
                      rounded="full"
                      surface={step.negative ? "danger-surface" : step.muted ? "subtle" : "none"}
                    />
                    {!isLast && <Div className="w-px flex-1 min-h-[24px]" surface="subtle" />}
                  </Stack>

                  <Stack gap="none" className="min-w-0 flex-1">
                    <Row gap="xs" align="center" wrap>
                      <Text
                        size="sm"
                        weight="medium"
                        className={step.negative ? "text-error" : undefined}
                        color={step.muted ? "muted" : undefined}
                      >
                        {step.label}
                      </Text>
                      {step.actorRole && step.actorRole !== "system" && (
                        <Badge variant="default" size="xs">{ACTOR_LABEL[step.actorRole]}</Badge>
                      )}
                    </Row>

                    <Text size="xs" color="muted">
                      {step.date ? new Date(step.date).toLocaleString() : "—"}
                    </Text>

                    {step.reason && (
                      <Text size="xs" color="muted" className="mt-0.5">{step.reason}</Text>
                    )}
                    {step.note && (
                      <Text size="xs" color="muted" italic className="mt-0.5">“{step.note}”</Text>
                    )}
                  </Stack>
                </Row>
              </Stack>
            );
          })}
        </Stack>
      )}

      {showFooter ? (
        <Div className="mt-3 border-t border-[var(--appkit-color-border)]" padding="t-sm">
          {footer}
        </Div>
      ) : null}
    </Div>
  );
}

/**
 * Turn recorded history entries into steps.
 *
 * Only entries that actually changed `status` become steps — an entry
 * recording a tracking number or a payment-review outcome is real history but
 * is not a phase, and putting every entry on the rail would bury the five
 * transitions anyone reads.
 */
export function stepsFromEntries(
  entries: TimelineEntry[] | undefined,
  labelFor: (status: string) => string,
  isNegative: (status: string) => boolean,
): TimelineStep[] {
  if (!entries?.length) return [];
  return entries
    .filter((e) => "status" in e.changes)
    .map((e) => {
      const to = String(e.changes.status?.to ?? "");
      return {
        key: to,
        label: labelFor(to),
        date: e.at,
        negative: isNegative(to),
        actorRole: e.actorRole,
        reason: e.reason,
        note: e.note,
      };
    });
}
