// AUTO-GENERATED — browser-safe barrel
// Run: node scripts/generate-client.mjs

export { COLORS, FLUID_GRID_MIN_WIDTHS, LOCALE_CONFIG, RADIUS, SHADOWS, THEME_CONSTANTS, TOKENS, Z_INDEX, token } from "./tokens/index";
export { Accordion, AccordionItem, ActiveFilterChips, Alert, Article, Aside, Avatar, AvatarDisplay, AvatarGroup, BackgroundRenderer, Badge, BaseListingCard, BlockFooter, BlockHeader, Breadcrumb, BulkActionBar, Button, Caption, Card, CardBody, CardFooter, CardHeader, Checkbox, ConfirmDeleteModal, Container, CountdownDisplay, DEFAULT_PAGINATION_CONFIG, DEFAULT_STICKY_CONFIG, DEFAULT_TABLE_CONFIG, DashboardStatsCard, DataTable, DescriptionField, DetailViewShell, Div, Divider, Drawer, Dropdown, DropdownItem, DropdownMenu, DropdownSeparator, DropdownTrigger, DynamicSelect, EmptyState, FilterDrawer, FlowDiagram, Footer, Form, FormActions, FormField, FormFieldSpan, FormGrid, FormGridField, FormGroup, GRID_MAP, Grid, Header, Heading, HorizontalScroller, IconButton, ImageGallery, ImageLightbox, IndeterminateProgress, Input, ItemRow, Label, Li, ListingLayout, ListingViewShell, Main, Menu, MenuContent, MenuItem, MenuSeparator, MenuTrigger, Modal, ModalFooter, Nav, Ol, Pagination, PasswordStrengthIndicator, PriceDisplay, Progress, RadioGroup, RatingDisplay, ResponsiveView, RichText, RoleBadge, Row, RowActionMenu, Section, SectionTabs, Select, SideDrawer, SideModal, Skeleton, SkipToMain, Slider, SlottedListingView, SortDropdown, Span, Spinner, Stack, StackedViewShell, StarRating, StatsGrid, StatusBadge, StepperNav, SummaryCard, TabStrip, TablePagination, Tabs, TabsContent, TabsList, TabsTrigger, TagInput, Text, TextLink, Textarea, ToastProvider, Toggle, Tooltip, Ul, UnsavedChangesModal, ViewToggle, buildColumns, classNames, createColumnBuilder, mergeTableConfig, mergeTailwindClasses, renderBoolean, renderCount, renderCurrency, renderCurrencyCompact, renderNullable, renderRating, useToast } from "./ui/index";
export type { AccordionItemProps, AccordionProps, ActiveFilter, ActiveFilterChipsProps, AlertProps, ArticleProps, AsideProps, AsyncPage, AvatarDisplayProps, AvatarGroupProps, AvatarProps, BackgroundConfig, BackgroundRendererProps, BadgeOrderStatus, BadgePaymentStatus, BadgeProps, BadgeReviewStatus, BadgeTicketStatus, BadgeVariant, BaseListingCardCheckboxProps, BaseListingCardHeroProps, BaseListingCardInfoProps, BaseListingCardRootProps, BlockFooterProps, BlockHeaderProps, BooleanRenderOpts, BreadcrumbItem, BreadcrumbProps, BulkActionBarLabels, BulkActionBarProps, BulkActionItem, ButtonProps, CardProps, CardSectionProps, CheckboxProps, ConfirmDeleteModalProps, ContainerProps, ContainerSize, CountdownDisplayProps, DashboardStatsCardProps, DataTableColumn, DataTableProps, DescriptionFieldProps, DetailViewLayout, DetailViewShellProps, DivProps, DividerProps, DrawerMode, DrawerProps, DropdownMenuItem, DropdownProps, DynamicSelectOption, DynamicSelectProps, EmptyStateProps, FilterDrawerProps, FlowDiagramProps, FlowStep, FooterProps, FormActionsProps, FormFieldProps, FormFieldSpanProps, FormGridProps, FormGroupProps, FormProps, GalleryImage, GapKey, GapToken, GenericStatus, GridCols, GridProps, HeaderProps, HorizontalScrollerProps, IconButtonProps, ImageGalleryProps, ImageLightboxProps, IndeterminateProgressProps, InputProps, ItemRowProps, LiProps, LightboxImage, ListingLayoutLabels, ListingLayoutProps, ListingViewShellProps, MainProps, MenuProps, ModalProps, NavProps, OlProps, PaginationConfig, PaginationProps, PasswordStrengthIndicatorProps, PerViewConfig, PriceDisplayProps, ProgressProps, RadioGroupProps, RadioOption, RatingDisplayProps, RatingMode, RatingRenderOpts, ResponsiveViewProps, RichTextProps, RoleBadgeProps, RowAction, RowActionMenuProps, RowProps, SectionProps, SectionTab, SectionTabsProps, SelectOption, SelectProps, SideDrawerProps, SideModalProps, SkeletonProps, SkipToMainProps, SliderProps, SlottedListingViewLabels, SlottedListingViewProps, SmartFormFieldProps, SortDropdownProps, SortOption, SpinnerProps, StackProps, StackedViewShellLabels, StackedViewShellProps, StarRatingProps, StatItem, StatsGridProps, StatusBadgeProps, StatusBadgeStatus, StepperNavProps, StepperNavStep, StickyConfig, SummaryCardProps, SummaryLine, TabStripProps, TabStripTab, TableConfig, TablePaginationLabels, TablePaginationProps, TableViewMode, TabsContentProps, TabsListProps, TabsProps, TabsTriggerProps, TagInputProps, TextLinkProps, TextareaProps, ToastPosition, ToastProviderProps, ToastVariant, ToggleProps, TooltipProps, UlProps, UnsavedChangesLabels, UnsavedChangesModalProps, ViewMode, ViewPortal, ViewToggleLabels, ViewToggleProps } from "./ui/index";
export { ErrorBoundary, RTDBPayloadStatus, RealtimeEventStatus, RealtimeEventType, SessionProvider, ThemeProvider, UNSAVED_CHANGES_EVENT, useAuth, useBreakpoint, useBulkAction, useBulkSelection, useCamera, useClickOutside, useContainerGrid, useCountdown, useGesture, useKeyPress, useLongPress, useMediaQuery, useMessage, useModalStack, usePendingFilters, usePendingTable, usePullToRefresh, useRealtimeEvent, useSession, useSwipe, useTheme, useUnsavedChanges, useUrlTable, useVisibleItems } from "./react/index";
export type { AvatarMetadataShape, BulkActionItemFailure, BulkActionPayload, BulkActionResult, BulkActionSummary, CountdownRemaining, ErrorBoundaryProps, GestureType, InvalidateQueriesFn, KeyModifiers, ModalEntry, PendingTable, RTDBEventPayload, RealtimeEventMessages, RealtimeEventStatusValue, RealtimeEventTypeValue, SessionContextValue, SessionEndpoints, SessionProviderProps, SessionUser, SwipeDirection, ThemeMode, UseBulkActionOptions, UseBulkActionReturn, UseBulkSelectionOptions, UseBulkSelectionReturn, UseCameraOptions, UseCameraReturn, UseClickOutsideOptions, UseContainerGridOptions, UseContainerGridResult, UseGestureOptions, UseKeyPressOptions, UsePendingFiltersOptions, UsePendingFiltersReturn, UsePendingTableReturn, UsePullToRefreshOptions, UsePullToRefreshReturn, UseRealtimeEventConfig, UseRealtimeEventReturn, UseSwipeOptions, UseUnsavedChangesOptions, UseUnsavedChangesReturn, UseUrlTableOptions, UseVisibleItemsOptions, UseVisibleItemsResult } from "./react/index";
export { CONFIRMATION_MESSAGES, INFO_MESSAGES, SUCCESS_MESSAGES } from "./values/index";
export { BUSINESS_DAY_HOUR_IST, arrayToObject, booleanToString, buildSieveFilters, calculatePagination, capitalize, capitalizeWords, chunk, cleanObject, coerceMediaField, coerceMediaFieldArray, currentYear, dateToISOString, deepClone, deepMerge, deleteCookie, deriveFormFields, easings, escapeHtml, firestoreTimestampToDate, formatCompactNumber, formatCurrency, formatCustomDate, formatDate, formatDateRange, formatDateTime, formatDecimal, formatFileSize, formatMonthYear, formatNumber, formatOrdinal, formatPercentage, formatRelativeTime, formatTime, generateAuctionId, generateAuctionImageFilename, generateBarcodeFromId, generateBidId, generateBlogImageFilename, generateBlogPostId, generateCarouselId, generateCarouselImageFilename, generateCategoryId, generateCategoryImageFilename, generateCouponId, generateCroppedImageFilename, generateEventImageFilename, generateFAQId, generateHomepageSectionId, generateInvoiceFilename, generateMediaFilename, generateOfferId, generateOrderId, generatePayoutDocFilename, generatePayoutId, generatePreOrderId, generatePreOrderImageFilename, generateProductId, generateProductImageFilename, generateProductVideoFilename, generateQRCodeData, generateReviewId, generateReviewImageFilename, generateReviewVideoFilename, generateRichTextImageFilename, generateStoreBannerFilename, generateStoreLogoFilename, generateTrimmedVideoFilename, generateUniqueId, generateUserAvatarFilename, generateUserId, getBusinessDayEligibilityDate, getBusinessDayStart, getBusinessDaysElapsed, getBusinessDaysRemaining, getContrastColor, getCookie, getMediaUrl, groupBy, hasCookie, hexToRgb, idExists, inferMediaTypeFromMime, isEmptyObject, isEmptyString, isEqual, isFuture, isPast, isSameMonth, isToday, maskString, mediaFieldSchema, nowISO, nowMs, objectToArray, objectToQueryString, omit, paginate, parseCookies, parseFormattedNumber, pick, proseMirrorToHtml, queryStringToObject, randomString, resolveDate, rgbToHex, slugify, sort, sortBy, splitCartIntoOrderGroups, stringToBoolean, stripHtml, truncate, truncateWords, unique, uniqueBy } from "./utils/index";
export type { DeriveFormFieldsOptions, DerivedField, DerivedFieldOption, DerivedFieldType, GenerateAuctionIdInput, GenerateAuctionImageFilenameInput, GenerateBidIdInput, GenerateBlogImageFilenameInput, GenerateBlogPostIdInput, GenerateCarouselIdInput, GenerateCategoryIdInput, GenerateEventImageFilenameInput, GenerateFAQIdInput, GenerateHomepageSectionIdInput, GenerateOfferIdInput, GenerateOrderIdInput, GeneratePayoutIdInput, GeneratePreOrderIdInput, GeneratePreOrderImageFilenameInput, GenerateProductIdInput, GenerateProductImageFilenameInput, GenerateProductVideoFilenameInput, GenerateReviewIdInput, GenerateReviewImageFilenameInput, GenerateReviewVideoFilenameInput, GenerateRichTextImageFilenameInput, GenerateUserIdInput, MediaField, MediaFieldInput, MediaFieldType, MediaFilenameContext, OrderGroup, OrderType, PaginationOptions, PaginationResult, SortOrder } from "./utils/index";
export { ACCOUNT_ENDPOINTS, ADMIN_ENDPOINTS, API_ENDPOINTS, AUCTION_ENDPOINTS, AUTH_ENDPOINTS, AUTH_ROUTES, BID_ENDPOINTS, BLOG_ENDPOINTS, CART_ENDPOINTS, CATEGORY_ENDPOINTS, CHAT_ENDPOINTS, CHECKOUT_ENDPOINTS, COLLECTION_CACHE_PATHS, COLLECTION_ENDPOINTS, CONSULTATION_ENDPOINTS, COPILOT_ENDPOINTS, CORPORATE_ENDPOINTS, DEMO_ENDPOINTS, EVENT_ENDPOINTS, FAQ_ENDPOINTS, HOMEPAGE_ENDPOINTS, LOGS_ENDPOINTS, LOYALTY_ENDPOINTS, MEDIA_ENDPOINTS, NOTIFICATIONS_ENDPOINTS, ORDER_ENDPOINTS, PAYMENT_ENDPOINTS, PREORDER_ENDPOINTS, PRODUCT_ENDPOINTS, PROFILE_STATS_ENDPOINTS, PROMOTION_ENDPOINTS, PROTECTED_ROUTES, PUBLIC_ROUTES, REVIEW_ENDPOINTS, ROUTES, SEARCH_ENDPOINTS, SELLER_ENDPOINTS, SITE_SETTINGS_ENDPOINTS, STORE_ENDPOINTS, WISHLIST_ENDPOINTS, resolveEndpoint, resolveEndpointFn } from "./constants/index";
export { _resetCollectionHooks, _resetFormFields, _resetProviders, arrayRemove, arrayUnion, deleteField, getClientAuthProvider, getClientPaymentGateway, getClientRealtimeProvider, getClientSessionAdapter, getCollectionHooks, getProviders, getRegisteredPaymentGateways, increment, mergeFilterDefinitions, mergeSortDefinitions, registerClientAuthProvider, registerClientPaymentGateway, registerClientRealtimeProvider, registerClientSessionAdapter, registerFieldOps, registerFormFields, registerProviders, removeCollectionHooks, removeFormFields, resolveFormFields, serverTimestamp, setCollectionHooks } from "./contracts/index";
export type { AdapterAuthUser, ApiRouteStub, AuthPayload, AuthUnsubscribe, AuthUser, ColumnExtensionOpts, CreateShipmentInput, CreateUserInput, EmailAttachment, EmailOptions, EmailResult, EventHandler, ExtraFieldRenderArgs, ExtraFormField, FeatureExtension, FeatureManifest, FeaturesConfig, FieldSentinel, FilterDefinition, FilterOption, FilterType, GatewayPaymentResponse, GenericListResponse, IAuthProvider, ICacheProvider, IClientAuthProvider, IClientPaymentGateway, IClientRealtimeProvider, IClientSessionAdapter, IDbProvider, IEmailProvider, IEventBus, IFieldOps, IPaymentProvider, IQueueProvider, IReadRepository, IRealtimeRepository, IRepository, ISearchProvider, ISessionProvider, IShippingProvider, IStorageProvider, IStyleAdapter, IWriteRepository, LayoutSlots, NavItem, OpenGatewayOptions, PagedResult, PaymentCapture, PaymentOrder, ProviderRegistry, QueueJob, RealtimeSnapshot, Refund, RepositoryLifecycleHooks, RouteStub, SearchHit, SearchOptions, SearchResult, ServiceabilityResult, Shipment, ShippingAddress, SieveQuery, SiteConfig, SortDefinition, StorageFile, SuggestOptions, TableColumn, TrackingEvent, TrackingInfo, Unsubscribe, UploadOptions, WhereOp, WithTransformOpts } from "./contracts/index";
export { ZodSetup, addPhoneSchema, addressSchema, calculatePasswordStrength, changePasswordSchema, cropDataSchema, dateStringSchema, deleteAccountSchema, emailSchema, exactLength, extractCountryCode, formatPhone, formatZodErrors, inRange, isCommonPassword, isDisposableEmail, isExternalUrl, isInList, isNumeric, isRequired, isValidEmail, isValidEmailDomain, isValidIndianPincode, isValidMobile, isValidPhone, isValidUrl, isValidUrlWithProtocol, matchesPattern, maxLength, mediaUrlSchema, meetsPasswordRequirements, minLength, normalizeEmail, normalizePhone, objectIdSchema, paginationQuerySchema, passwordSchema, phoneSchema, resetPasswordSchema, sanitizeUrl, sendVerificationSchema, setupZodErrorMap, trimDataSchema, urlSchema, validateRequestBody, verifyPhoneSchema, zodErrorMap } from "./validation/index";
export type { PasswordRequirements, PasswordStrength, ZodSetupProps } from "./validation/index";
export { ApiError, AppError, AuthenticationError, AuthorizationError, DatabaseError, ERROR_CODES, ERROR_MESSAGES, NotFoundError, ValidationError, handleApiError, isAppError, logError } from "./errors/index";
export type { ErrorCode } from "./errors/index";
export { SEO_CONFIG, aggregateRatingJsonLd, auctionJsonLd, blogPostJsonLd, breadcrumbJsonLd, createSeoConfig, faqJsonLd, generateAuctionMetadata, generateBlogMetadata, generateCategoryMetadata, generateMetadata, generateProductMetadata, generateProfileMetadata, generateSearchMetadata, organizationJsonLd, productJsonLd, reviewJsonLd, searchBoxJsonLd } from "./seo/index";
export type { AuctionSeoInput, BlogPostJsonLdInput, BlogSeoInput, BreadcrumbJsonLdItem, CategorySeoInput, FaqJsonLdInput, ProductJsonLdInput, ProductSeoInput, ReviewJsonLdInput, SeoConfig } from "./seo/index";
export { FEATURE_SUBPATH_MAP, mergeFeatureMessages, withFeatures } from "./cli/index";
export type { NextConfig } from "./cli/index";
export { configureMarketDefaults, getDefaultCountry, getDefaultCurrency, getDefaultCurrencySymbol, getDefaultLocale, getDefaultPhonePrefix, getDefaultTimezone, getMarketProfile, resetMarketDefaults } from "./core/baseline-resolver";
export type { MarketProfile } from "./core/baseline-resolver";
export { DEFAULT_ROUTE_MAP, createRouteMap } from "./next/routing/route-map";
export type { RouteMap, RoutePath } from "./next/routing/route-map";
export { getBooleanParam, getNumberParam, getOptionalSessionCookie, getRequiredSessionCookie, getSearchParams, getStringParam } from "./next/request-helpers";
export { GlobalError, ErrorView, NotFoundView, UnauthorizedView } from "./next/index";
export type { GlobalErrorProps, ErrorViewProps, NotFoundViewProps, UnauthorizedViewProps } from "./next/index";
